### ISSUE TITLE
docs: Service documentation callable section is repeated in public SDK web-page

### ISSUE THREAD

**Issue by MathBunny** [firebase/firebase-admin-node#1006]
### Describe the problem

The public SDK documentation repeats the callable section of the service overview for some services. These are the files that are `admin.<serviceName>.html`. For example, [instanceId](https://firebase.google.com/docs/reference/admin/node/admin.instanceId).

#### Steps to reproduce:

Simply visit the documentation page for the Admin SDK and click the `Overview` link for impacted services (more below). To reproduced locally, run `npm run apidocs` and open the emitted HTML from the `docgen` folder.

#### Observations:

1. This regression was introduced when the `.d.ts` files were split for the individual services. 

For example:
- `646d90ff26bd4df6e53bf2f8a2d362ed7e4a537a`: Move manual typings for remote-config into a separate file
- `4974d009b8d1ee557bc9f9e36a627881753a4b21`: Splitting the `index.d.ts` file into smaller files

2. The services impacted do not include the ones that do not have a manually curated `d.ts` file, and for some unknown reason does not impact `auth.d.ts`.

| Service Name        | Impacted           | Separate .d.ts File  |
|:-------------:|:-------------:|:-----:|
| Auth     | No | Yes |
| Credentials     | No | No |
| Database     | Yes | Yes |
| Firestore     | No | No |
| InstanceId     | Yes | Yes |
| MachineLearning     | No | No |
| Messaging     | Yes | Yes |
| ProjectManagement     | Yes | Yes |
| SecurityRules     | Yes | Yes |
| Storage     | No | No |
| RemoteConfig     | Yes | Yes |

3. The tool used to generate the documentation, TypeDoc, resolves the namespace documentation selection using the following technique (as seen [here](https://typedoc.org/guides/doccomments/#namespaces)):

>  As namespaces can be defined in multiple files, TypeDoc selects the longest comment by default. One may override this behavior with the special @preferred comment tag.

4. By applying the `@preferred` comment tag in the `index.d.ts` file we can fix this problem. For example:

```ts
/**
 * @preferred
 */
declare namespace admin.instanceId {
  export import InstanceId = _instanceId.admin.instanceId.InstanceId;
}
```

After, running `npm run apidocs` the duplicated documentation will be removed.

5. As an extension of the previous point, applying `@preferred` in the `d.ts` file right above the exported namespaces works as well.

```ts
/**
 * @preferred
 */
export namespace admin.instanceId {
 // …
}
```

6. While debugging, I noticed that the moment the separate `d.ts` file added an `export namespace admin.instanceId{}` the problem became eminent. 

I also attempted changing the export mechanism by declaring the namespace first and then exporting it, or using a different import structure for the namespace but no luck.

#### Screenshot
![](https://i.imgur.com/i7NuOgH.png)

**Comment by hiranya911** [comment]
This was fixed when the new typing auto-generation scheme rolled out.
