### ISSUE TITLE
Can't Install firebase-admin!

### ISSUE THREAD

**Issue by SurajPandey186** [firebase/firebase-admin-node#1008]
### [REQUIRED]: Describe your environment

  * Operating System version: Window 10
  * Node.js version: 12.16.1
  * NPM version: 6.14.8

### [REQUIRED] Step 3: Describe the problem
npm ERR! Unexpected end of JSON input while parsing near '...stry.npmjs.org/@fireb'

**Comment by hiranya911** [comment]
Doesn't reproduce. Either a temporary network glitch or some issue with your local NPM setup.
