### ISSUE TITLE
MachineLearning createModel, updateModel always fails

### ISSUE THREAD

**Issue by hohteri** [firebase/firebase-admin-node#1013]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Firebase Cloud Functions
  * Firebase SDK version: 9.11
  * Firebase Product: machine-learning
  * Node.js version: 10
  * NPM version: 6.14.3

#### Steps to reproduce:

Whenever I try to call createModel or updateModel a seemingly unrelated error occurs. Calling listModels works fine. It is hard to understand why listModels is called when calling createModel or updateModel

Error: Request contains an invalid argument.
    at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28)
    at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28)
    at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23)
    at MachineLearningApiClient.toFirebaseError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:178:16)
    at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:161:25
    at process._tickCallback (internal/process/next_tick.js:68:7) 

#### Relevant Code:

```
exports.updateMLModel = functions.https.onRequest((req, resp) => {
             ...
             return bucket.upload(filePath, {destination: `${file.name}` }).then( files => {
                     const bucketX = files[0].metadata.bucket;
                     const nameX = files[0].metadata.name;
                     console.log('gcsTfliteUri: ' + `gs://${bucketX}/${nameX}`);
                 return firebaseml.listModels({filter: `display_name = ${name}`}).then( result => {
                     var modelId
                     for (const model of result.models) {
                       console.log(`${model.displayName} (ID: ${model.modelId})`);
                         modelId = model.modelId
                     }
                     return firebaseml.updateModel(modelId, {
                            displayName: name,
                            tags: [version],
                            tfliteModel: {gcsTfliteUri: `gs://${bucketX}/${nameX}`},
                         }).then( res => resolve())
                     //})
                 })
           })
```

**Comment by ifielker** [comment]
Hello, 
It looks like this code is loosely based on our publish model sample is that correct? Then the reason you are doing the list when updating is to get the modelId, so you can update the model using that modelId. 
If I'm reading this right, it looks like the list filter is invalid. Which means that the ${name} variable contains something that shouldn't be in a list filter. Have a look at the ${name} variable before you list. It should only contain alpha-numeric values, underscores and hyphens.

**Comment by hohteri** [comment]
Hi,

I mentioned that listModels works, also I get the exact same error if I do only createModel without listModels. Below is the console.log which shows that I do get result for listModels

`8:13:02.962 PM | warning | updateMLModel Error: Request contains an invalid argument.     at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28)     at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28)     at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23)     at MachineLearningApiClient.toFirebaseError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:178:16)     at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:161:25     at process._tickCallback (internal/process/next_tick.js:68:7) |  
-- | -- | -- | --


8:13:02.953 PM |   | updateMLModel Unhandled rejection
-- | -- | --

8:13:02.162 PM |   | updateMLModel testModel (ID: 13044359)
-- | -- | --
8:13:02.025 PM |   | updateMLModel gcsTfliteUri: gs://xxx/yyy.tflite
-- | -- | --
`

**Comment by hohteri** [comment]
Okay, I resolved it, my tag contained the version of the model, which _naturally_ contains illegal characters. Replacing the dots and dashes with underscores, this problems goes away.

**Comment by ifielker** [comment]
Glad it's been resolved.
