### ISSUE TITLE
 Permission denied fetching Google Analytics data

### ISSUE THREAD

**Issue by hlongvu** [firebase/firebase-admin-node#1015]
Unable to get template
{ Error: [AUTHORIZATION_ERROR]: Permission denied fetching Google Analytics data
    at FirebaseRemoteConfigError.FirebaseError [as constructor] (/Users/longvu/Works/HDC/firebase/node_modules/firebase-admin/lib/utils/error.js:43:28)
    at FirebaseRemoteConfigError.PrefixedFirebaseError [as constructor] (/Users/longvu/Works/HDC/firebase/node_modules/firebase-admin/lib/utils/error.js:89:28)
    at new FirebaseRemoteConfigError (/Users/longvu/Works/HDC/firebase/node_modules/firebase-admin/lib/remote-config/remote-config-api-client-internal.js:403:23)
    at RemoteConfigApiClient.toFirebaseError (/Users/longvu/Works/HDC/firebase/node_modules/firebase-admin/lib/remote-config/remote-config-api-client-internal.js:242:16)
    at /Users/longvu/Works/HDC/firebase/node_modules/firebase-admin/lib/remote-config/remote-config-api-client-internal.js:87:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errorInfo:
   { code: 'remote-config/permission-denied',
     message:
      '[AUTHORIZATION_ERROR]: Permission denied fetching Google Analytics data' },
  codePrefix: 'remote-config' }

I run the sample code and encountered this error! Searching in google does not provide any result, look like a new error from the sdk.

**Comment by lahirumaramba** [comment]
Hi @hlongvu! Thank you for reporting this issue. I am sorry for the trouble, and let me try and help you resolve this.

Do you encounter this error only for `getTemplate` operations? To better understand the problem, could you please provide a code sample you used to reproduce this error?

We have seen a similar error before with the `rollback` operation if your Firebase project has Google Analytics enabled.
Could you try adding the role `Firebase Analytics Viewer` to the Service Account of your project?

On the Firebase Console, if you navigate to `Settings -> Service accounts` you will see a link to `Manage service account permissions`. Clicking this link will take you to Google Cloud Console where you can add the role `Firebase Analytics Viewer` to that Service Account.

**Comment by hlongvu** [comment]
Thanks @lahirumaramba, adding Firebase Analytics Viewer permission resolved this issue.

**Comment by amirrezvanibc** [comment]
@lahirumaramba I'm having the same issue but seems like I cannot see "Firebase Analytics Viewer" role over in Google Cloud console.
This is what I do:
in Google Cloud Console >> Service Accounts >> Permissions >> Grant Access, then in Roles section I search for Firebase Analytics Viewer, nothing shows up there

**Comment by lahirumaramba** [comment]
Hi @amirrezvanibc! You are right! It looks like the role does not show up in `Service Accounts >> Permissions`.

Could you check in `IAM >> Permissions` instead? You should be able to edit the Firebase service account from there and add a new role for `Firebase Analytics Viewer`.  Let me know if that doesn't work.

**Comment by amirrezvanibc** [comment]
thanks @lahirumaramba, it worked from ```IAM >> permissions```

**Comment by dhruvmehtad11** [comment]
Hi anyone please help me. I am still getting this issue even after me being the owner of the project

**Comment by dhruvmehtad11** [comment]
@lahirumaramba please help me with the issue. I have firebase admin sdk version 8.1.0. I have tried the above solutions but not able to find any success in it.

**Comment by lahirumaramba** [comment]
Hi @dhruvmehtad11 could you confirm you have added the role `Firebase Analytics Viewer` to the Service Account you are using? See: https://github.com/firebase/firebase-admin-node/issues/1015#issuecomment-760511489

**Comment by pedropedruzzi** [comment]
Got the same issue right after adding a remote config condition based on "User Audience(s)". The remote config client worked fine. But the Admin API started failing. Adding the `Firebase Analytics Viewer` role to the `firebase-adminsdk` princial in IAM stopped the issue immediately.
I don't recall if I had to create that role manually. But it seems like a Firebase bug to not have this handled

**Comment by yaohuiwu** [comment]
> Hi @amirrezvanibc! You are right! It looks like the role does not show up in `Service Accounts >> Permissions`.
> 
> Could you check in `IAM >> Permissions` instead? You should be able to edit the Firebase service account from there and add a new role for `Firebase Analytics Viewer`. Let me know if that doesn't work.

Thanks for the information. It helps me a lot! But it's a little weired that  `Service Accounts >> Permissions` has no `Firebase Analytics Viewer` role.
