### ISSUE TITLE
Firebase ServerValue.increment(1) doesnt work on cloud functions

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-admin-node#1018]
### [READ] Step 1: Are you in the right place?

  Yes

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: firebase cloud functions
  * Firebase SDK version: 9.1.1
  * Firebase Product: admin-sdk-node
  * Node.js version: 10
  * NPM version: i dont know

#### Steps to reproduce:

I'm trying to use the `increment ` feature on the firebase admin sdk for node.js.
My function is deployed to cloud functions node version 10

here is the code

#### Relevant Code:

```
let admin = require('firebase-admin').initializeApp({
    databaseURL: "https://igibo-b0b27.firebaseio.com",
    projectId: "igibo-b0b27"
});

const igDatabase = admin.database();

exports.test = (req, res) => {

igDatabase.ref('test123').set(admin.database.ServerValue.increment(1));
res.status(200).send('ok');
};
```

As this was said is been deployed in firebase cloud functions so it has permission to write the database... but still i get:
`TypeError: Cannot read property 'increment' of undefined`

here is the package.json

```
{
  "name": "authenticate",
  "version": "1.0.0",
   "dependencies": {
 
     "firebase-admin": "^9.1.1"
   }
}
```

**Comment by hiranya911** [comment]
The above code is incorrect. The `initializeApp()` function returns an `App` object which you've assigned to `admin`. So the expression `admin.database.ServerValue` makes no sense. Your code should look like:

```js
const admin = require('firebase-admin'); // admin now points to the namespace
const app = admin.initializeApp();

// Now you can call admin.database.ServerValue
```
