### ISSUE TITLE
Incorrect typings for ApnsPayload

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-admin-node#1023]
`ApnsPayload` is typed as:

```ts
export interface ApnsPayload {

  /**
   * The `aps` dictionary to be included in the message.
   */
  aps: Aps;
  [customData: string]: object;
}
```

However, that prevents from passing string values as custom data.

Note that according to Apple

> Your custom keys must have values with primitive types, such as dictionary, array, string, number, or Boolean. Custom keys are available in the userInfo dictionary of the UNNotificationContent object delivered to your app.

So I think the correct types should be something like either:

```ts
[customData: string]: any;
```
or
```ts
[customData: string]: JSON;

interface JSON {
    [x: string]: string|number|boolean|Date|JSON|JSONArray;
}
interface JsonArray extends Array<string|number|boolean|Date|JSON|JSONArray> { }
```

**Comment by hiranya911** [comment]
We can change the type to `[customData: string]: any;`. Feel free to provide a PR, or I will get around to it soon.
