### ISSUE TITLE
createCustomToken not working

### ISSUE THREAD

**Issue by Alynva** [firebase/firebase-admin-node#1026]
### Environment

  * Operating System version: Windows 8.1
  * Firebase SDK version: firebase-admin ^8.10.0, firebase-functions ^3.6.1
  * Firebase Product: auth
  * Node.js version: v14.10.1
  * NPM version: v6.14.8

### The problem

I'm trying to create a custom token but the function throw this error:

<details>
<summary>View</summary>

Code: `app/unable-to-parse-response`

Message:

>  Error while parsing response data: "SyntaxError: Unexpected token < in JSON at position 0". Raw server response: "<!DOCTYPE html>
>  <html lang=en>
>    <meta charset=utf-8>
>    <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
>    <title>Error 404 (Not Found)!!1</title>
>    <style>
>      *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
>    </style>
>    <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
>    <p><b>404.</b> <ins>That’s an error.</ins>
>    <p>The requested URL <code>/v1/projects/-/serviceAccounts/%3Chtml%3E%3Chead%3E%3Cmeta%20HTTP-EQUIV=%22Pragma%22%20CONTENT=%22no-cache%22%3E%3Cscript%20language=%27javascript%27%3Eparent.location=%22/index.html</code> was not found on this server.  <ins>That’s all we know.</ins>
>  ". Status code: "404". Outgoing request: "POST https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/<html><head><meta HTTP-EQUIV="Pragma" CONTENT="no-cache"><script language='javascript'>parent.location="/index.html#/login"</script></head><body></body></html>:signBlob."

</details>

I tried to do some debbug into the source, and found out that the strange HTML in the URL is actually returned by the request [here](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/token-generator.ts#L198). Apparently the text are splited somewhere, but the full HTML was:

```html
<html><head><meta HTTP-EQUIV="Pragma" CONTENT="no-cache"><script language='javascript'>parent.location="/index.html#/login"</script></head><body></body></html>
```

I did not understood where that request in the `IAMSigner.prototype.getAccountId` are handled, so my debbug stoped here.

#### Steps to reproduce:

I had some crazy code going on at start, by I tried the code from #500 and the result was the same. I think that it's important to mention that I'm running in the emulator. I didn't have issues with it, but probably some things can go wrong in that.

#### Relevant Code:

```js
functions.https.onRequest((req, res) => {
    return admin.auth()
        .createCustomToken('123456')
        .then(token => res.send(token))
});
```

**Comment by hiranya911** [comment]
The SDK cannot discover a valid service account ID when running locally. I don't know if the emulator is supposed to handle this scenario correctly. I'd advise you to file a separate bug for the emulator for that. To try this API locally you must specify a service account when initializing the SDK.
