### ISSUE TITLE
Cannot find module node-v46-win32-ia32\grpc_node.node

### ISSUE THREAD

**Issue by YamanSehzade** [firebase/firebase-admin-node#103]
### Environment
  * Operating System version: Windows 10 x64
  * Firebase SDK version: 4.5.0
  * Library version: 5.4.1
  * Meteor version: 1.5.2.2
  * npm version: 5.2.0

### Problem

I get the following error when server starts:

> Cannot find module 'XXX\node_modules\firebase-admin\node_modules\grpc\src\node\extension_binary\node-v46-win32-ia32\grpc_node.node

main.ts:
```
import { Meteor } from 'meteor/meteor';
import * as admin from "firebase-admin";

Meteor.startup(() => {
    admin.initializeApp({
        credential: admin.credential.cert("./key.json"),
        databaseURL: "XXX"
    });
});
```

picture of error:
![whatsapp image 2017-10-09 at 17 30 11](https://user-images.githubusercontent.com/22771125/31347448-b4ef4176-ad1c-11e7-99e6-c3d87e7b3b91.jpeg)

picture of the lost file's path:
![inkedwhatsapp image 2017-10-09 at 17 33 28_li](https://user-images.githubusercontent.com/22771125/31347664-5795ea9c-ad1d-11e7-9241-fd635284518a.jpg)

Could you help me please ?

**Comment by hiranya911** [comment]
@YamanSehzade Can you try the instructions available in https://stackoverflow.com/questions/46153099/unable-to-install-grpc-binaries?

**Comment by YamanSehzade** [comment]
@hiranya911 thank you so much. that's work.


i have little question too..
` firebase.storage().ref().child('test/').put(soundBufferArray, { contentType: 'audio/mpeg' })`
this code works in firebase. Is there a similar method in admin-firebase?

**Comment by YamanSehzade** [comment]
and could you close this tag please ? I could not find how to close it

**Comment by hiranya911** [comment]
`admin.storage().bucket()` returns a reference to a bucket. And here are the API docs for the bucket: https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.2.0/storage/bucket
