### ISSUE TITLE
Firestore Emulator doesn't handle admin.firestore.FieldValue.increment on 9.2.0

### ISSUE THREAD

**Issue by elvisun** [firebase/firebase-admin-node#1034]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows
  * Firebase SDK version: 9.2.0
  * Firebase Product: Emulator
  * Node.js version: 10.15.3
  * NPM version: 6.4.1

### [REQUIRED] Step 3: Describe the problem

I had a function that does `doc.update({field: admin.firestore.FieldValue.increment(1)})`, and a test to expect that `field === 1`. It was working fine when I was on `~8.0.0`, but I tried to update to `9.2.0`, this test started to fail. 

```
    Expected: 1
    Received: undefined
```

I wonder if `admin.firestore.FieldValue.increment` is still properly handled in the emulator?

#### Steps to reproduce:

1. Write a cloud function and a test
2. Run test with it connected to emulator

#### Relevant Code:
Running test:
```
firebase emulators:exec --only firestore \"jest --config jest.config.js\"
```

Connecting to emulator:
```
const projectId = Math.random()
  .toString(36)
  .substring(7);
process.env.GCLOUD_PROJECT = projectId;
process.env.FIRESTORE_EMULATOR_HOST = "127.0.0.1:8080";
initializeApp({ projectId });
```

Code for function:
```
...

        await db.doc(`users/${USER_ID}`).update({
          // This field is undefined before
          field: admin.firestore.FieldValue.increment(1)
        });

...
```

Test:
```
  it("successfullly marks an item as purchased if it's made by the requester and increment counter", async () => {
    const wrapped = testEnv.wrap(functionName);
    const data = {};

    const res = await wrapped(data, {
      auth: { uid: USER_ID }
    });
    await expect(res).resolves;

    const userDoc = await db.doc(`users/${USER_ID}`).get();
    expect(userDoc .data()!["field"]).toBe(1);
  });
```

**Comment by schmidt-sebastian** [comment]
@elvisun This issue is usually caused by using types from different versions of Firestore together. Can you verify that you only have a single version of `@google-cloud/firestore` (and ideally no version of `@firebase/firestore`) in your dependency tree?

**Comment by elvisun** [comment]
Thanks Sebastian! Look like having `@firebase/firestore` is the issue. This was my old `package.json`.

```
  "dependencies": {
    "@google-cloud/logging": "^7.3.0",
    "@sendgrid/mail": "^7.2.1",
    "crypto-random-string": "^3.3.0",
    "firebase-admin": "~9.2.0",
    "firebase-functions": "^3.0.0",
    "google-libphonenumber": "^3.2.7",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.8"
  },
  "devDependencies": {
    "@types/google-libphonenumber": "^7.4.17",
    "@types/jasmine": "^3.5.1",
    "@types/jest": "^24.9.0",
    "@types/node": "^13.13.4",
    "@types/request-promise": "^4.1.45",
    "@types/request-promise-native": "^1.0.17",
    "firebase": "^7.15.0",
    "firebase-functions-test": "^0.1.7",
    "firebase-tools": "^7.12.1",
    "firestore-jest-mock": "^0.1.0",
    "jest": "^24.9.0",
    "prettier": "^1.19.1",
    "ts-jest": "^24.3.0",
    "tslint": "^5.12.0",
    "typescript": "^3.7.2"
  },
```

I took out ` "firebase": "^7.15.0",` from the dev dep and the tests passed again, woohoo, thanks!!

Anything we can do so developers don't run into issues like this?

**Comment by schmidt-sebastian** [comment]
We are aware of the confusion this is causing. We are currently revamping our Web API, and one of the unintended consequences will be that it will be much harder to use types from the "invalid" SDK. I am glad we were able to help you.

**Comment by hassanzadeh** [comment]
Hello, 
I'm experiencing the same issue and I don't have duplicate installs, only thing I can think of is that I have firebase installed in the parent directory (ie, functions is a sub-directory of the main project), but that should not cause interference, any thoughts why I'm getting that?

**Comment by BennetE** [comment]
For anyone who still has the problem and is looking for a solution. I found this answer that helped me:

https://github.com/firebase/firebase-admin-node/issues/1803#issuecomment-1179244087
https://stackoverflow.com/a/73047370/10433038


Do **not** use this:
```ts
import * as admin from "firebase-admin";

admin.firestore.FieldValue
```

use this:
```ts
import { FieldValue } from "firebase-admin/firestore";
```

**Comment by masterkrang** [comment]
also don't use this

``` import { FieldValue } from 'firebase/firestore' ```

**Comment by loolooii** [comment]
@BennetE there's no `firebase-admin/firestore`. What package is this exactly? I have `firebase-admin`, is that the correct one?

**Comment by BennetE** [comment]
> @BennetE there's no `firebase-admin/firestore`. What package is this exactly? I have `firebase-admin`, is that the correct one?

`import { FieldValue } from "firebase-admin/firestore";` Can be used since version 10.0.0 (https://www.npmjs.com/package/firebase-admin/v/10.0.0)

**Comment by rignaneseleo** [comment]
In my case, I had to use

`const { FieldValue } = require ("firebase-admin/firestore");
`
