### ISSUE TITLE
Firebase realtime database calls freeze / never return

### ISSUE THREAD

**Issue by rbabayoff** [firebase/firebase-admin-node#1036]
## Environment

Latest firebase-admin npm package - v9.2.0

### Describe the problem

Calls to someRef.once("value") or someRef.transaction(cb) freeze with await or never call success or error callbacks, if provided instead.

#### Steps to reproduce:

It's intermediate but I have specific paths it happens at, even though with siblings of that path with the same rules it doesn't happen.

#### Relevant Code:

Just the standard once and transaction calls. The code worked perfectly prior to today and even today works on sibling nodes.

From my past experience, when db calls freeze, it has something to do with locks not being released, I suspect it's a problem with the db itself.

Related questions: 

1. Are there any logs I can enable to see what happens?

2. Any way to reset the db?

Thanks,
Ronen

**Comment by hiranya911** [comment]
> Are there any logs I can enable to see what happens?

I believe you can do `admin.database().enableLogging(console.log)` to get a debug log output. Please share one, as that will be helpful in analyzing this issue.

> Any way to reset the db?

There's no such thing.

**Comment by hiranya911** [comment]
I'm going to close this due to lack of activity. If there's any new information/results/logs, we'd be happy to take a look.
