### ISSUE TITLE
How can i Login with Google on my backend?

### ISSUE THREAD

**Issue by GuilhermeCunha** [firebase/firebase-admin-node#1041]
I know that there is the possibility to create a custom token on the backend (I have done this, but I can only do it with authentication through email and password) and send it to my front end. 

But how can I do this through the login / registration by Google / Facebook among others?

**Comment by hiranya911** [comment]
We don't support user authentication in Admin SDK.  Typically you would use a Firebase client SDK and handle Google auth in the frontend.
