### ISSUE TITLE
[messaging] condition fcm sending not work!

### ISSUE THREAD

**Issue by zl910627** [firebase/firebase-admin-node#1045]
![image](https://user-images.githubusercontent.com/53897531/94454426-70b4cb00-01e4-11eb-90d3-42d5f8f61761.png)
this code does not work.
![image](https://user-images.githubusercontent.com/53897531/94454548-9215b700-01e4-11eb-862a-d81107c831f6.png)
Also above does not work too.

As you can see sending successfully, no notification on mobile!

**Comment by zl910627** [comment]
PS: They were working code before a month.

**Comment by hiranya911** [comment]
Please file a support issue. If the server is responding with a successful response, the SDK to FCM handoff has been successful. Any further investigation has to be done at the backend.
