### ISSUE TITLE
Cannot add multifactor with phone number for new and current user

### ISSUE THREAD

**Issue by grzegorz-ogrodowski** [firebase/firebase-admin-node#1048]
Operating System version: Win 10
Firebase SDK version: firebase admin 9.2.0
Firebase Product: auth
Angular version: 9.1.3

**Steps to reproduce:**
Try to update existing user for add multifactor with phone number. Using piece of code from
https://cloud.google.com/identity-platform/docs/admin/manage-mfa-users

**Relevant Code:**
```
admin.auth().updateUser('123456789', {
            multiFactor: {
              enrolledFactors: [
                {
                  // uid will be auto-generated.
                  phoneNumber: '+16505550003',
                  displayName: 'Spouse\'s phone',
                  factorId: 'phone',
                }
              ],
            },
          })
          .then((userRecord) => {
            console.log(userRecord.multiFactor.enrolledFactors);
          })
          .catch((error) => {
            console.log(error);
          })
```

**Expected:**
User is updated with new enrolledFactor

**Result:**
Code is not compilable:
Object literal may only specify known properties, and 'phoneNumber' does not exist in type 'UpdateMultiFactorInfoRequest'.

**Comment by zepol-yerffej** [comment]
@grzegorz-ogrodowski why did you close the issue? I'm running into the same error but with the CreateMultiFactorInfoRequest interface. Did you find any solution for this?
