### ISSUE TITLE
Unable to deploy to AWS EBS

### ISSUE THREAD

**Issue by srameshr** [firebase/firebase-admin-node#105]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: AWS Ubuntu Linux 16
  * Firebase SDK version: 5.4.2
  * Library version: 
  * Firebase Product: Messaging (Admin sdk)

#### Steps to reproduce: 
``` npm install --save firebase-admin``` and run ```eb-deploy```
The deploy fails with:
```
============= i-05310204bd3adbe90 ==============
-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------

module.js:487
    throw err;
    ^

Error: Cannot find module 'grpc'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/firebase-admin/node_modules/@google-cloud/common-grpc/src/service.js:26:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Frills@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Frills@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │
└──────────────────────────────────────────────────┘

> App@1.0.0 start /var/app/current
```

Here is my package.json
```
{
  "name": "App",
  "version": "1.0.0",
  "description": "App backend code",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "body-parser": "^1.17.2",
    "express": "^4.15.4",
    "firebase-admin": "5.2.1",
    "kerberos": "~0.0.x",
    "parse": "^1.10.0",
    "parse-server": "^2.6.0",
    "pug": "^2.0.0-rc.4",
    "shortid": "^2.2.8"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

```

**Comment by hiranya911** [comment]
Can you check if grpc package is installed under node_modules?

**Comment by srameshr** [comment]
How do I check the contents of node_modules folder in ebs? In my local node_modules folder I see the ```grpc``` lib.

**Comment by hiranya911** [comment]
This should be fixed now: https://firebase.google.com/support/release-notes/admin/node#5.4.3

We no longer load Firestore/gRPC packages unless `admin.firestore()` is called explicitly.

**Comment by shadow1349** [comment]
@hiranya911 
This still doesn't work for me. I can't deploy to EB if I have firebase-admin greater than 4.2.1

I have to use firestore for my project, are there any workarounds?

**Comment by rtkhanas** [comment]
@shadow1349 I switched from NPM to yarn on EB and it works great now.

**Comment by shadow1349** [comment]
@rtkhanas I'm afraid I can't switch my whole company over to yarn

**Comment by rtkhanas** [comment]
@shadow1349 anyway the problems looks like NPM is installing some dependencies to a wrong folder on AWS. Maybe, not really related to firebase-admin-node, but more to NPM itself.

**Comment by yerassyl** [comment]
Hello all, have this issue been resolved? I am getting it too. Any suggestions?

**Comment by albinekb** [comment]
I have this issue too, we we're running t2.micro with 512MB ram, but compiling GRPC module seems to only work with t2.medium (4GB ram). Why is this package installed when I'm just using firebase.messaging() ?

**Comment by ehansen31** [comment]
appreciate you @albinekb , upgraded t2.mico => t2.medium and it worked.

**Comment by sthielen** [comment]
For any latecomers to this thread: I encountered this issue when deploying to Elastic Beanstalk. Installing `grpc` was breaking during `node-gyp`with a permission error:

`node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/grpc/src/node' `

I was able to resolve temporarily by installing with `unsafe-perm=true` as detailed [here](https://stackoverflow.com/questions/46001516/beanstalk-node-js-deployment-node-gyp-fails-due-to-permission-denied/46001517#46001517).
