### ISSUE TITLE
 Unable to resolve module `fs` from `node_modules\firebase-admin\lib\firebase-namespace.js`: fs could not be found within the project

### ISSUE THREAD

**Issue by ashwani1234** [firebase/firebase-admin-node#1058]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)
  * Node.js version: _____
  * NPM version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
`fs` is a core Node.js module. If the runtime cannot find it, you're likely running in an environment that doesn't provide core Node.js modules (like a browser environment).

**Comment by vismayainnow8** [comment]
hey i got the same issue... what should i do
