### ISSUE TITLE
Unable to import users with SHA512 passwords

### ISSUE THREAD

**Issue by AdamBCo** [firebase/firebase-admin-node#1059]
### Environment

  * Operating System version: OSX 10.15.5 (19F101)
  * Firebase SDK version: firebase-admin 8.12.0
  * Firebase Product: auth
  * Node.js version: 12.18.3.
  * NPM version: 6.14.6

### Problem

At the moment, I'm unable to authenticate users imported from my existing database outside of Firebase. The import is successful, but user authentications fail with auth/wrong-password. I commented about this issue in another #792 , but haven't found a solution to the problem.

Can someone please help me understand what's going on? And how I can successfully migrate my users to Firebase.

    const salt = crypto.randomBytes(16).toString('hex');  
    const user = {  
      uid: "tbSL53PN7zVTMsWc9up24hev4CN2",  
      email: "test@test.com",  
      hash: crypto.pbkdf2Sync("test123", salt, 100, 64, 'sha512').toString('hex'),  
      salt  
    }  

    const importUser = {  
      uid: user.uid,  
      email: user.email,  
      passwordHash: Buffer.from(user.hash, 'hex'),  
      passwordSalt: Buffer.from(user.salt, 'hex')  
    }  
      
    const results = await auth().importUsers([importUser], {  
        hash: {  
            algorithm: "SHA512",  
            rounds: 100,  
      }  
    })  

    console.log(results)  
    const c = await auth().listUsers()  
    console.log(c)

In addition to the problem above, I'm also noticing that passwordHash and passwordSalt are always undefined; even thought I am logged in as an admin/owner for the project.

    { successCount: 1, failureCount: 0, errors: [] }
    {
      users: [
        UserRecord {
          uid: 'tbSL53PN7zVTMsWc9up24hev4CN2',
          email: 'test@test.com',
          emailVerified: false,
          displayName: undefined,
          photoURL: undefined,
          phoneNumber: undefined,
          disabled: false,
          metadata: [UserMetadata],
          providerData: [Array],
          passwordHash: undefined,
          passwordSalt: undefined,
          tokensValidAfterTime: 'Wed, 07 Oct 2020 10:17:12 GMT',
          tenantId: undefined
        }
      ]
    }

**Comment by hiranya911** [comment]
The way you hash passwords is incorrect. Please see my response to your comment in #792. Also see my older responses in the same issue.

For a comparison of different hashing mechanisms you can try the following script:

```js
const crypto = require('crypto');
const { sha512 } = require('js-sha512'); // third-party library (npm install js-sha512)

const pass = 'test123';
const salt = crypto.randomBytes(16).toString('hex');

// Your approach
const got = crypto.pbkdf2Sync(pass, salt, 100, 64, 'sha512').toString('hex');

// My approach using the native sha512 support of Node.js
function sha512_local(salt, pass) {
  let current = Buffer.from(salt + pass);
  for (let i = 0; i < 100; i++) {
    const hash = crypto.createHash('sha512');
    current = hash.update(current).digest();
  }

  return current;
}

// My other approach using a 3rd party hashing library
function sha512_lib(salt, pass) {
  let c = pass;
  if (salt) { c = salt + c; } // Salt-first
  for (let ii = 0; ii < 100; ii++) {
      const hex = sha512(c)
      c = new Buffer(hex, 'hex');
  }
  return c.toString('hex');
}

console.log('PBKDF2: ', got);
console.log('SHA512 (LOCAL): ', sha512_local(salt, pass).toString('hex'));
console.log('SHA512 (LIB): ', sha512_lib(salt, pass));
```

This hahses the same salt+password pair using 3 different approaches (100 rounds):

1. Using the a pbkdf2 function (your approach)
2. Using the native sha512 hash
3. Using a third-party sha512 library

You will notice that your approach produces a result different from the other 2:
```
PBKDF2:  f99186d242c30af294af80575abc9dea85c70889468926f82321836c4a15d101dba816eebcd71bc8cff1c38f99d4c7e8446cb32f5982d687d4c5ded6d260435b
SHA512 (LOCAL):  fc5e8ab58bd140ce63978b0e051883a9c3f02d8c408cc36efc5e4a5a8a22cbd8315eb33c210474d5314fbbb48f9e81d2b8a532e02d62a67c858f0ec70d62f830
SHA512 (LIB):  fc5e8ab58bd140ce63978b0e051883a9c3f02d8c408cc36efc5e4a5a8a22cbd8315eb33c210474d5314fbbb48f9e81d2b8a532e02d62a67c858f0ec70d62f830
```

**Comment by AdamBCo** [comment]
@hiranya911 Are you saying that crypto is doing things incorrectly, or my use of the crypto library is incorrect? From what I've gathered, I'm following the documentation as evidenced [here](https://www.geeksforgeeks.org/node-js-crypto-pbkdf2-method/). I appreciate you taking the time to help me on this.

**Comment by hiranya911** [comment]
Your use of crypto is incorrect. If you're specifying `SHA512` as the hash algorithm type, the hash needs to be calculated using a plain sha512 digest function. You're currently using a pbkdf sha function.
