### ISSUE TITLE
TypeError: Cannot read property 'applicationDefault' of undefined

### ISSUE THREAD

**Issue by samyoungnyc** [firebase/firebase-admin-node#1061]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.15.4
  * Firebase SDK version: N/A
  * Firebase Product: firebase-admin 9.2.0
  * Node.js version: 14.13.0
  * NPM version: 6.14.8

### [REQUIRED] Step 3: Describe the problem

I have a Node (14.3.0) server where I enabled ES6 module imports in my package.json by adding the following line:

package.json:
`"type": "module",`

According to the firebase-admin docs here: https://firebase.google.com/docs/admin/setup/#node.js

>     If you are using ES2015, you can import the module instead:
>     import * as admin from 'firebase-admin';

When I use `import * as admin from 'firebase-admin'`; I get the following error:

> credential: admin.credential.applicationDefault(),
>     TypeError: Cannot read property 'applicationDefault' of undefined

It seems that firebase-admin isn't imported properly - I have tried removing the "type": "module" line in package.json and importing firebase-admin with require:

`const admin = require(firebase-admin)`

and it works, so my question is - is it possible to import firebase-admin in Node using ES6, and if so, how?

#### Steps to reproduce:
Create a node project and add the following files:
```
// server.js
import express from 'express';
import * as admin from 'firebase-admin';

const app = express();
const PORT = process.env.PORT || 5000;

app.use(express.json());

admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: process.env.FIREBASE_DB_URL,
});

app.listen(PORT, () => console.log(`listening on ${PORT}`));

export default app;
```

```
// package.json
{
  "name": "server",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "^4.17.1",
    "firebase-admin": "^9.2.0",
  },
  "type": "module",
  "scripts": {
    "dev": "node server.js"
  },
  "engines": {
    "node": "14.x"
  }
}
```
Set the `GOOGLE_APPLICATION_CREDENTIALS` as described in the firebase documentation via shell:

`export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/service-account-file.json"`

Then do `npm install`, then `npm run dev` or `node server.js`

When doing this, I get the following error:

```
TypeError: Cannot read property 'applicationDefault' of undefined
    at file:///Users/xxx/xxx/xxx/src/server.js:xx:xx
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by hiranya911** [comment]
Thanks for reporting this. I was able to repro the problem, but I'm not sure if this is something we can support right now. We transpile our sources down to ES5. I believe that means downstream consumers cannot really use the ES6 syntax to import the package, unless they are using TypeScript.

Also I don't think we've ever tested the ES6 syntax with Node.js 14. Usually we only use the ES6 syntax when working with TypeScript (which works as expected). 

However, following seems to work (on Node14, with `type: module`):

```js
import admin from 'firebase-admin';
```

This might be a reasonable temporary workaround for you.

**Comment by hiranya911** [comment]
Found some relevant information at https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_commonjs_namespaces

> When importing a CommonJS module, it can be reliably imported using the ES module default import or its corresponding sugar syntax:

> The ECMAScript Module Namespace representation of a CommonJS module is always a namespace with a default export key pointing to the CommonJS module.exports value.

This explains why `import * as admin` doesn't work while `import admin` does. The former imports a module with a default export:

```
[Module] {
  default: <ref *1> FirebaseNamespace {
    __esModule: true,
    credential: {
      cert: [Function: cert],
      refreshToken: [Function: refreshToken],
      applicationDefault: [Function: applicationDefault]
    },
    SDK_VERSION: '9.2.0',
    Promise: [Function: Promise],
    INTERNAL: FirebaseNamespaceInternals {
      firebase_: [Circular *1],
      serviceFactories: {},
      apps_: {},
      appHooks_: {}
    },
    default: [Circular *1]
  }
}
```

**Comment by samyoungnyc** [comment]
> Found some relevant information at https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_commonjs_namespaces
> 
> > When importing a CommonJS module, it can be reliably imported using the ES module default import or its corresponding sugar syntax:
> 
> > The ECMAScript Module Namespace representation of a CommonJS module is always a namespace with a default export key pointing to the CommonJS module.exports value.
> 
> This explains why `import * as admin` doesn't work while `import admin` does. The former imports a module with a default export:
> 
> ```
> [Module] {
>   default: <ref *1> FirebaseNamespace {
>     __esModule: true,
>     credential: {
>       cert: [Function: cert],
>       refreshToken: [Function: refreshToken],
>       applicationDefault: [Function: applicationDefault]
>     },
>     SDK_VERSION: '9.2.0',
>     Promise: [Function: Promise],
>     INTERNAL: FirebaseNamespaceInternals {
>       firebase_: [Circular *1],
>       serviceFactories: {},
>       apps_: {},
>       appHooks_: {}
>     },
>     default: [Circular *1]
>   }
> }
> ```

I ended up removing `type: module` and just using `module.exports` and the old import syntax. Good to know that I can switch back if need be but at this point it would be quite time-consuming to revert. Wish I'd thought of trying `import admin from 'firebase-admin'` before I reverted. In any case, thank you for the clarification.
