### ISSUE TITLE
No Connection established

### ISSUE THREAD

**Issue by mparpaillon** [firebase/firebase-admin-node#1063]
### Environment

  * Operating System version: MacOS 10.15.6
  * Firebase SDK version: 8.x et 9.x (only works on 7.x)
  * Firebase Product: firestore
  * Node.js version: 14.3.0
  * NPM version: 6.14.5

#### Steps to reproduce:

- `mkdir test`
- `cd test`
- `npm i firebase-admin` (9.2.0 in my case)

<img width="571" alt="Capture d’écran 2020-10-15 à 13 26 00" src="https://user-images.githubusercontent.com/1062115/96117178-f9707e00-0ee9-11eb-9684-814ec3dcbd48.png">

- Create serviceAccount.json (downloaded from Firebase console)
```json
{
  "type": "service_account",
  "project_id": "PROJECT_NAME",
  "private_key_id": "PRIVATE_KEY_HERE",
  "private_key": "-----BEGIN PRIVATE KEY-----[ CONTENT HERE ]-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-x49go@PROJECT_NAME.iam.gserviceaccount.com",
  "client_id": "CLIENT_ID_HERE",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-x49go%PROJECT_NAME.iam.gserviceaccount.com"
}
```

- create file test.js
```js
const admin = require('firebase-admin');

serviceAccount = require('./serviceAccount.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://PROJECT_NAME.firebaseio.com"
});

return admin.firestore()
  .collection('chapters') // or any collection you might have
  .get()
  .then(chaptersSnapshots => {
    console.log(chaptersSnapshots.size);
  })
  .catch(e => console.log(e));

```

- node test.js

=> `Error: 14 UNAVAILABLE: No connection established`

<img width="563" alt="Capture d’écran 2020-10-15 à 13 28 11" src="https://user-images.githubusercontent.com/1062115/96117366-46eceb00-0eea-11eb-88da-c87138bfa9ae.png">

#### 1 - Rollback to 7.4.0 (Worked)

- `npm i firebase-admin@7.x`
- node test.js

<img width="384" alt="Capture d’écran 2020-10-15 à 13 32 22" src="https://user-images.githubusercontent.com/1062115/96117759-dc887a80-0eea-11eb-92ad-1b5bcd856da3.png">

#### 3 - Calling RTDB instead (Worked)

```js
return admin.database()
  .ref('MY_COLLECTION')
  .once('value', snap => console.log(snap.val()));
```

**Comment by schmidt-sebastian** [comment]
@mparpaillon The networking layer changed between the 2 releases, but we have been using our new [JavaScript-based](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) networking layer for quite a while now. Does this issue continue to reproduce for you? If so, we probably need to look at your Service Account credentials (via a private support ticket) or your network setup.

The RTDB SDK uses another vastly different networking layer, which will likely not help us debug the Firestore issue.

**Comment by mparpaillon** [comment]
Thanks @schmidt-sebastian. I still have this issue yes. As soon as I update firebase-admin > 7.14.
Am I the only one? That's odd

**Comment by mparpaillon** [comment]
Yes. From 8.0.0 and above I have this issue.

**Comment by mparpaillon** [comment]
@schmidt-sebastian Who should I contact for this issue then?

**Comment by hiranya911** [comment]
I've tried your example code above on Node14 with the latest version of the SDK, and ran without any problems. It seems this issue is rather specific to your environment or the project. The v8 series of the SDK is pretty old (released over a year ago), and this is probably the first time we've seen an issue like this. Try a simple environment refresh, and if that doesn't work, file an issue with Support at https://firebase.google.com/support

To do an environment refresh, delete `node_modules` and `package-lock.json` and reinstall the dependencies from the scratch.

If you do end up filing a support issue, please specify your project, and ideally provide a zipped up version of your repro for us to test.

**Comment by mparpaillon** [comment]
The environment refresh didn't fix it. I'm creating an issue. Thanks anyway

**Comment by mparpaillon** [comment]
Turns out I had the FIREBASE_EMULATOR_HOST set to localhost:5002 in my zshrc file
Removing it solved my issue
