### ISSUE TITLE
Firebase Cloud Functions - Invalid condition expression provided.

### ISSUE THREAD

**Issue by deadsoul44** [firebase/firebase-admin-node#1065]
### Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 8.12.1
  * Firebase Product: Firebase Cloud Functions
  * Node.js version: v.10.20.0
  * NPM version: 6.14.4

#### Steps to reproduce:

I get "Invalid condition expression provided." with the code below.

#### Relevant Code:

```
      topic = "_full";
      topic1 = `${myObj.field1}` + topic;
      topic2 = (`${myObj.field2.field1}_${myObj.field2.field2}` + topic)
        .toString()
        .toLowerCase()
        .split(" ")
        .join("_");
      topic3 = `${myObj.field3.field1}` + topic;
      topic4 = `${myObj.field4.field1}` + topic;

      condition = `${topic1} in topics || ${topic2} in topics || ${topic3} in topics || ${topic4} in topics`;
```

When I try to send to topic1 instead of the condition, I am able to get the notification.

I am not sure if this is bug or related to my code since there is no clue in the error message. When I try to build the condition string with an editor, it looks fine.

I also asked this on stackoverflow:
https://stackoverflow.com/questions/64375575/how-to-use-template-literal-in-firebase-cloud-function-condition

**Comment by hiranya911** [comment]
> Invalid condition expression provided

That indicates the runtime value of the condition is somehow malformed or incorrect. What's the final value of your condition?

**Comment by deadsoul44** [comment]
When I run the following with an editor:
```
      myObj={field1:123212,
      			 field2:{field1:"San Francisco",field2:"Hot News"},
             field3:{field1:12},
             field4:{field1:13},
      			};
      
      topic = "_full";
      topic1 = `${myObj.field1}` + topic;
      topic2 = (`${myObj.field2.field1}_${myObj.field2.field2}` + topic)
        .toString()
        .toLowerCase()
        .split(" ")
        .join("_");
      topic3 = `${myObj.field3.field1}` + topic;
      topic4 = `${myObj.field4.field1}` + topic;

      condition = `${topic1} in topics || ${topic2} in topics || ${topic3} in topics || ${topic4} in topics`;
      
      console.log(condition);
```
I get the following as expected:
```
"123212_full in topics || san_francisco_hot_news_full in topics || 12_full in topics || 13_full in topics"
```

**Comment by hiranya911** [comment]
Topic names should be within quotes. See the examples at https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-topics

So the above should be:
```
'123212_full' in topics || 'san_francisco_hot_news_full' in topics || '12_full' in topics || '13_full' in topics
```

**Comment by hiranya911** [comment]
Look into string interpolation in JS. Something like the following should work:

```js
condition = `'${topic1}' in topics || '${topic2}' in topics`;
```
