### ISSUE TITLE
[Question] How to handle Webpush action?

### ISSUE THREAD

**Issue by moshfeu** [firebase/firebase-admin-node#1066]
The types say that 

> /**
     * An action available to the user when the notification is presented
     */
    action: string;

How the client code can handle this action? Is there a way to focus / open the app's url (or PWA instance) on click on the notification?

It's not more clean in the docs: https://firebase.google.com/docs/reference/admin/node/admin.messaging.WebpushNotification#actions

Thanks

**Comment by hiranya911** [comment]
Probably best asked in StackOverflow. @chong-shao do you have any guidance?

**Comment by moshfeu** [comment]
It's not just a question, I believe that the docs should be improved with this information, that's basically why I opened that issue..

**Comment by hiranya911** [comment]
Existing documentation in our code already links out to the Webpush spec:

https://developer.mozilla.org/en-US/docs/Web/API/notification/Notification
https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction

I have tagged one of the FCM maintainers who might be able to follow up and suggest improvements.

**Comment by moshfeu** [comment]
I understand that concept in the client, but when using firebase-admin-node, the consumer (a.k.a me) doesn't deal with the notification API, the client sdk does it for them so maybe it's not related to this package only but the integration between the client and the server.

**Comment by chong-shao** [comment]
The Admin SDK documentation for WebpushNotification has the reference to the specification (https://firebase.google.com/docs/reference/admin/node/admin.messaging.WebpushNotification) so I think it's consistent with the REST API documentation

**Comment by hiranya911** [comment]
@chong-shao if there's no further action for this issue, lets close it.

**Comment by chong-shao** [comment]
Sure. Closed this for now.
