### ISSUE TITLE
require("firebase-admin").FieldValue is undefined

### ISSUE THREAD

**Issue by bagintz** [firebase/firebase-admin-node#107]
* Operating System version: Firebase cloud functions
  * Firebase SDK version: n/a
  * Library version: node.js:5.4.2
  * Firebase Product: node admin & firestore

`var FieldValue = require("firebase-admin").FieldValue;`

in cloud functions index.js (as per https://firebase.google.com/docs/firestore/manage-data/delete-data) is showing as undefined.  Which leads to an error when trying to delete from Firestore:

`TypeError: Cannot read property 'delete' of undefined at /user_code/index.js:239:34 at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

**Comment by bagintz** [comment]
This is resolved by replacing:

`var FieldValue = require("firebase-admin").FieldValue;`

with

`var FieldValue = admin.firestore.FieldValue;`

Any ideas why (and why it isn't in the official docs)?

**Comment by hiranya911** [comment]
It is in the documentation: https://firebase.google.com/docs/reference/admin/node/admin.firestore.FieldValue

All Firestore types are exposed from the `admin.firestore` namespace. You can also do:

```
firestore_ns = require('@google-cloud/firestore');
firestore_ns.FieldValue
```

**Comment by bagintz** [comment]
@hiranya911 do you know where I should send a request for Firebase to change/update their documentation I originally followed:

https://firebase.google.com/docs/firestore/manage-data/delete-data

?

**Comment by hiranya911** [comment]
@bagintz Thanks for pointing this out. Please use the "Send Feedback" option on the top right of the page.
