### ISSUE TITLE
[React-native] Unable to resolve module `fs` from `node_modules\firebase-admin\lib\firebase-namespace.js`: fs could not be found within the project

### ISSUE THREAD

**Issue by tuanndl** [firebase/firebase-admin-node#1071]
Unable to resolve module `fs` from `node_modules\firebase-admin\lib\firebase-namespace.js`: fs could not be found within the project

**Comment by hiranya911** [comment]
This library doesn't support client-side environments like React Native. This is for server-side (Node.js) use only (Note that `fs` is one of the core Node.js modules available in server-side environments).
