### ISSUE TITLE
Documentation missing for using Auth Emulation

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-admin-node#1075]
### Describe your environment

  * Operating System version: macOS
  * Firebase SDK version: firebase-admin 9.3.0
  * Firebase Product: auth (under emulation)
  * Node.js version: 14.13.0
  * NPM version: 6.14.8

### Describe the problem

[Version 9.3.0 CHANGELOG](https://github.com/firebase/firebase-admin-node/releases/tag/v9.3.0) states "Add support for auth emulation", but it is not clear, how this could be used, i.e. I don't find any documentation.

My use case: 

For local browser app development, I wish to create a user and then automatically authenticate as that user.

This works from within the browser, but it felt wrong so I tried doing it in the node script that already primes Firestore. I couldn't.

Tried (snippet):

```
  //admin.auth().useEmulator(AUTH_URL);   // "not a function" (firebase-admin 9.3.0)

  for (const [uid,{ displayName, photoURL }] of Object.entries(users)) {
    await admin.auth().createUser({
      uid,
      displayName,
      photoURL
    });
  }
```

There is no `admin.auth().useEmulator(...)` like there is for the client side JS library.

Without using such, I get:

>FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: invalid_grant (Bad Request)". [...] 

I won't spend more time on this. Just wanted to have a place to track, whether this *should* work. It's been earlier mentioned in the [Configuration for firebase-admin to call auth emulator](https://groups.google.com/g/firebase-db-testing/c/dlq3k2122Uk) thread (EA program mailing list). Since the feature is now in the public client, I wanted to continue it here.

**Comment by hiranya911** [comment]
This feature is not available for use yet. Changes mentioned above are just a small part of a larger upcoming change. Stay tuned.

**Comment by johnnyasantoss** [comment]
So, still not available? 👀

**Comment by hiranya911** [comment]
https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks

**Comment by johnnyasantoss** [comment]
> https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks

Thank you!
