### ISSUE TITLE
"TypeError: Cannot read property 'objectMode' of undefined" when process.env.NODE_ENV == 'test'

### ISSUE THREAD

**Issue by jorg1piano** [firebase/firebase-admin-node#1076]
**System**
  * Operating System version: Windows 10
  * Firebase SDK version: "firebase-admin": "^9.2.0",
  * Firebase Product: storage
  * Node.js version: v12.18.3
  * NPM version: 6.14.8

**The Problem:**
I get an error while trying to run some code to upload a file to cloud storage in a test environment.

**Error**
` 
TypeError: Cannot read property 'objectMode' of undefined

      at Pumpify.Object.<anonymous>.Writable.write (node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:292:22)

So the state (references _writeableState) is undefined. 

Running the same code in live cloud functions work perfectly 

**Steps to reproduce**
1. Setup a jest test
2. Run the code below with a file of name image.png in the same dir as the test file.

Code:

```
const { v4: uuid } = require('uuid');
test("Uploads a file to cloud storage without throwing an error",()=>{
    const metadata = {
        metadata: {
            firebaseStorageDownloadTokens: uuid()
        },
        contentType: 'image/png',
        cacheControl: 'public, max-age=31536000',
    };
    let filePath = path.join(__dirname, "image.png");
    await bucket.upload(filePath, {
        destination: `users/testUser/documents/image.png`,
        gzip: true,
        metadata: metadata,
    });
});

```

**Comment by jorg1piano** [comment]
If someone is running into this issue and are using JEST. 

Scoping your upload inside a beforeAll instead of beforeEach seems to do the trick. I have no idea why...

`/// This does not work
beforeEach(async () => {
    /// Trying to upload your file here will fail
})

afterEach(async () => {});
describe("Upload image", () => {
    test("Test whatever ", async () => { });
});`

This does for some reason:
`describe("Upload image", () => {

    beforeAll(async () => {
        /// Upload your file
    })

    afterAll(async () => {
        /// the file delete
    });
    test("Test whatever ", async () => { });
});
`

**Comment by hiranya911** [comment]
Also asked here: https://stackoverflow.com/questions/64557855/typeerror-cannot-read-property-objectmode-of-undefined-when-calling-bucket

Use SO for questions and debugging usage issues.

**Comment by jorg1piano** [comment]
> Also asked here: https://stackoverflow.com/questions/64557855/typeerror-cannot-read-property-objectmode-of-undefined-when-calling-bucket
> 
> Use SO for questions and debugging usage issues.

Because I asked it there...

Seems like a bug in the library, thats why I've posted it here...

**Comment by sewidat** [comment]
same here!
