### ISSUE TITLE
Issue while loading with typescript

### ISSUE THREAD

**Issue by ysfjwd** [firebase/firebase-admin-node#108]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: OSX
  * Firebase SDK version: 5.4.2
  * Library version: 5.4.2
  * Firebase Product: admin (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

I am trying to make it work with nestjs server. I had a problem doing a normal require('cert.json') so i changes my cert file to a ts file and modified the typescript file as

```ts
export default {
  ...SETTINGS
}
```

and then did

```ts
import * as firebase from 'firebase-admin';
import { default as config } from './firebase-config';

firebase.initializeApp({
  credential: firebase.credential.cert(config),
  databaseURL: 'https://xxx.firebaseio.com'
});
```

the firebase-admin is running fine, but along the way, it throws an error first.

```log
ERROR in [at-loader] ./src/electron/nest/firebase-config.ts:2:3
    TS2345: Argument of type '{ "type": string; "project_id": string; "private_key_id": string; "private_key": string; "client_...' is not assignable to parameter of type 'string | ServiceAccount'.
  Object literal may only specify known properties, and '"type"' does not exist in type 'string | ServiceAccount'.
```

#### Steps to reproduce:

as explained in above.

#### Relevant Code:

as explained above.

**Comment by ysfjwd** [comment]
closing it, i believe the bug is not with this package, but the way my project is configured.

**Comment by zinzinday** [comment]
It warn by tslint?

```js
import * as admin from 'firebase-admin';
import {ServiceAccount} from "firebase-admin";

const adminConfig: ServiceAccount = {
    "projectId": "your_project_id",
    "privateKey": "-----BEGIN PRIVATE KEY-----\n\n-----END PRIVATE KEY-----\n",
    "clientEmail": "firebase-adminsdk-xxxx@your_project_id.iam.gserviceaccount.com"
};
admin.initializeApp({
    credential: admin.credential.cert(adminConfig),
    databaseURL: "https://lodenhacai.firebaseio.com"
});
```

Work find with Ts )

**Comment by ysfjwd** [comment]
@zinzinday you are absolutely right. I figured it out yesterday. The quick-start repo i cloned was transpiling via webpack. I undid that, and transpiled via tsc and the problem went away. I did say in my last comment "closing it" but forgot to close. My bad.

**Comment by ysfjwd** [comment]
on a totally unrelated subject, to run this inside electron, i had to compile from source for electron .. here is my .env file

```bash
export npm_config_target=1.7.9
# The architecture of Electron, can be ia32 or x64.
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron.
export npm_config_disturl=https://atom.io/download/electron
# Tell node-pre-gyp that we are building for Electron.
export npm_config_runtime=electron
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
```
