### ISSUE TITLE
Creating\Getting dummy tokens which are valid by the verifyToken() for testing

### ISSUE THREAD

**Issue by ItayTur** [firebase/firebase-admin-node#1083]
**Is your feature request related to a problem? Please describe.**
I want to test server api. I started to work with firebase auth service, and it works but custom tokens are not valid by the admin sdk verifyToken(). In the tests i use jest and super-test npm, for running the server and make the api calles.
 so I can't test any of the server services, because they all dependent on the auth.

**Describe the solution you'd like**
It would be great, if there was a way to create tokens in the server, that pass the verifyToken() validation.

**Describe alternatives you've considered**
First, I tried the custom tokens, but then I saw the warning in the docs that it won't work. 
I work with node js and express. I thought of adding the custom verification (that do work with the custom tokens) in the catch method of the auth middleware, but it is very quirky.
Another way I think of is creating a user for testing every time I run the tests, or save it's token as environment variable. again not maintainable.

**Additional context**
**Example Test**
```
const request = require('supertest')
const admin = require('firebase-admin')
const app = require('../app')

test('Should create new user', async () => {
    const user = {
        id: 'fe3dd',
        name: 'Joe',
        lastName: 'Jonas',
    }

    const sanitizeUser = sanitize(user, userSanitizers)
// need valid token here for the verifyToken()  
    const token = await admin.auth().createCustomToken('token')
    const response = await request(app)
        .post(usersRoute)
        .set(Authorization, token)
        .send(user)
        .expect(201)
}
```

**Auth Middleware**
```
const auth = async (req, res, next) => {
    try {
        const token = req.header('Authorization').replace('Bearer ', '')
        const { uid } = await admin.auth().verifyIdToken(token)
        req.userId = uid
        req.token = token
        next()
    } catch (error) {
        res.status(401).send({ error: 'Please authenticate' })
    }
}
```

**Comment by hiranya911** [comment]
You have 2 options:

1. Create a custom token and exchange it for an ID token. This is the approach taken in our integration tests.
2. Use the Firebase emulator suite, which can create mock ID tokens that can be validated by the SDK.
