### ISSUE TITLE
Error [ERR_HTTP2_NO_SOCKET_MANIPULATION]: HTTP/2 sockets should not be directly manipulated (e.g. read and written) whenever I'm querying the document

### ISSUE THREAD

**Issue by jameswtc** [firebase/firebase-admin-node#1093]
* Operating System version: MacOS 11.0.1
  * Firebase SDK version: 9.2.0
  * Firebase Product: firestore
  * Node.js version: 14.2.0
  * NPM version: 6.14.8

I'm getting this error whenever I'm querying the firestore documents using the firebase-admin:

```
(node:3363) UnhandledPromiseRejectionWarning: Error [ERR_HTTP2_NO_SOCKET_MANIPULATION]: HTTP/2 sockets should not be directly manipulated (e.g. read and written)
    at Object.get (internal/http2/core.js:826:15)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:162:31)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:175:25)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:162:18)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:162:18)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:162:18)
    at _clone (/<path-to-project>/node_modules/clone/clone.js:175:25)
    at /<path-to-project>/node_modules/clone/clone.js:94:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

However, the query returns data as expected, but the console output logs the above error.

The following is my code where I'm reading the document (actual function & type names are modified):
```typescript
export const getDataById = async (id: string): Promise<Data | null> => {
    const doc = await getCollection().doc(id).get();
    if (!doc.exists) {
        return null;
    } else {
        return doc.data() as Data;
    }
};
```

Does anyone have the similar issue? It happens on all codes that query the firestore.

I don't remember this showing up few days ago but I have the following updates / changes:
* Upgrade Mac to Big Sur
* Yarn upgrade packages to latest version (including firebase and firebase-admin)
* Firestore dev mode (public access to everything) expired.

**Comment by schmidt-sebastian** [comment]
Thanks for reporting this. `clone` is actually not in our dependency chain. Can you see what pulls it in for you (by running `npm ls clone`)?

**Comment by jameswtc** [comment]
I have this output @schmidt-sebastian 

```
❯ npm ls clone
xxxx@1.0.0 /Users/james/Projects/xxxx-xxx
└─┬ node-cache@5.1.2
  └── clone@2.1.2
```

**Comment by schmidt-sebastian** [comment]
Thanks for letting me know. It looks like a similar problem existed in PubSub (see https://github.com/GoogleCloudPlatform/node-red-contrib-google-cloud/commit/f64932046069ec472ec4713bc1ca554b33b6807e) and there it was because the response object contained non-cloneable data. I don't think we can apply the fix from PubSub here, as we have to return the full document data. Does you document contain any special data (e.g. not just strings, numbers, booleans and combinations thereof)? Do you see this with every operation?

It might also help if you provide log output, which will provide the full network traffic (albeit after the `clone` operation takes place).

**Comment by jameswtc** [comment]
> Thanks for letting me know. It looks like a similar problem existed in PubSub (see [GoogleCloudPlatform/node-red-contrib-google-cloud@f649320](https://github.com/GoogleCloudPlatform/node-red-contrib-google-cloud/commit/f64932046069ec472ec4713bc1ca554b33b6807e)) and there it was because the response object contained non-cloneable data. I don't think we can apply the fix from PubSub here, as we have to return the full document data. Does you document contain any special data (e.g. not just strings, numbers, booleans and combinations thereof)? Do you see this with every operation?
> 

Yes. It happens on every operation to read the data from Firestore. The document contains only string, nothing else. 

> It might also help if you provide log output, which will provide the full network traffic (albeit after the `clone` operation takes place).

I don't have any more logs other that the output in my original post. The console just output those lines whenever I read data from Firestore. Or any other way I could help you by grabbing useful data for your analysis?

Thanks!

**Comment by schmidt-sebastian** [comment]
You can enable additional logging by invoking `setLogFunction`.

This would look as such:

```
admin.firestore.setLogFunction(console.log);
```

**Comment by jameswtc** [comment]
> You can enable additional logging by invoking `setLogFunction`.
> 
> This would look as such:
> 
> ```
> admin.firestore.setLogFunction(console.log);
> ```

Doesn't look like offering much info:

```
Firestore (4.7.1) 2020-12-10T16:54:07.830Z mlVqM [ClientPool.acquire]: Creating a new client
Firestore (4.7.1) 2020-12-10T16:54:07.923Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (4.7.1) 2020-12-10T16:54:07.923Z mlVqM [Firestore.requestStream]: Sending request: {"parent":"projects/xxxxxxx/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"users"}],"where":{"fieldFilter":{"field":{"fieldPath":"userId"},"op":"EQUAL","value":{"stringValue":"S6TUK2QBCyPVNSPqhBTvZ23uEZR2"}}},"limit":{"value":1}}}
Firestore (4.7.1) 2020-12-10T16:54:08.037Z kfBh0 [ClientPool.acquire]: Re-using existing client with 99 remaining operations
Firestore (4.7.1) 2020-12-10T16:54:08.037Z kfBh0 [Firestore.requestStream]: Sending request: {"parent":"projects/xxxxxxx/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"users"}],"where":{"fieldFilter":{"field":{"fieldPath":"userId"},"op":"EQUAL","value":{"stringValue":"S6TUK2QBCyPVNSPqhBTvZ23uEZR2"}}},"limit":{"value":1}}}
Firestore (4.7.1) 2020-12-10T16:54:08.140Z kfBh0 [Firestore.requestStream]: Received response: {xxxxxxxx}
Firestore (4.7.1) 2020-12-10T16:54:08.140Z kfBh0 [Firestore._initializeStream]: Releasing stream
Firestore (4.7.1) 2020-12-10T16:54:08.143Z kfBh0 [Firestore._initializeStream]: Received stream end
Firestore (4.7.1) 2020-12-10T16:54:08.146Z i5acF [ClientPool.acquire]: Re-using existing client with 99 remaining operations
Firestore (4.7.1) 2020-12-10T16:54:08.146Z i5acF [Firestore.requestStream]: Sending request: {"parent":"projects/xxxxxxx/databases/(default)/documents/users/S6TUK2QBCyPVNSPqhBTvZ23uEZR2","structuredQuery":{"from":[{"collectionId":"belongsTo"}],"limit":{"value":1}}}
Firestore (4.7.1) 2020-12-10T16:54:08.148Z mlVqM [Firestore.requestStream]: Received response: {xxxxxxx},"name":"projects/xxxxxx/databases/(default)/documents/users/S6TUK2QBCyPVNSPqhBTvZ23uEZR2","createTime":{"seconds":"1603280190","nanos":595123000},"updateTime":{"seconds":"1603756489","nanos":122028000}},"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1607619248","nanos":166083000},"skippedResults":0}
Firestore (4.7.1) 2020-12-10T16:54:08.148Z mlVqM [Firestore._initializeStream]: Releasing stream
Firestore (4.7.1) 2020-12-10T16:54:08.149Z mlVqM [Firestore._initializeStream]: Received stream end
Firestore (4.7.1) 2020-12-10T16:54:08.274Z i5acF [Firestore.requestStream]: Received response: {xxxxxxx},"name":"projects/xxxxxxx/databases/(default)/documents/users/S6TUK2QBCyPVNSPqhBTvZ23uEZR2/belongsTo/NQHc8ihqVreQECaGxyAB","createTime":{"seconds":"1604510991","nanos":76989000},"updateTime":{"seconds":"1606496626","nanos":612437000}},"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1607619248","nanos":222305000},"skippedResults":0}
Firestore (4.7.1) 2020-12-10T16:54:08.274Z i5acF [Firestore._initializeStream]: Releasing stream
Firestore (4.7.1) 2020-12-10T16:54:08.275Z i5acF [Firestore._initializeStream]: Received stream end
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_HTTP2_NO_SOCKET_MANIPULATION]: HTTP/2 sockets should not be directly manipulated (e.g. read and written)
    at new NodeError (node:internal/errors:277:15)
    at Object.get (node:internal/http2/core:839:15)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:162:31)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:175:25)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:162:18)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:162:18)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:162:18)
    at _clone (/Users/james/Projects/fixify-next/node_modules/clone/clone.js:175:25)
    at /Users/james/Projects/fixify-next/node_modules/clone/clone.js:94:19
    at runMicrotasks (<anonymous>) {
  code: 'ERR_HTTP2_NO_SOCKET_MANIPULATION'
}
```

**Comment by schmidt-sebastian** [comment]
You are sending a query that produces no results. I was hoping that we would see a Document as part of the result set that contains some non-standard types, which could then explain the error message (and it would be similar to GoogleCloudPlatform/node-red-contrib-google-cloud@f649320).

Is this error pretty reproducible for you? If so, is there a repro you could share with us (either publicly or privately at mrschmidt<at>google.com)? Does it occur with just this one type of query?

**Comment by jameswtc** [comment]
> You are sending a query that produces no results. I was hoping that we would see a Document as part of the result set that contains some non-standard types, which could then explain the error message (and it would be similar to GoogleCloudPlatform/node-red-contrib-google-cloud@f649320).
> 
> 
> 
> Is this error pretty reproducible for you? If so, is there a repro you could share with us (either publicly or privately at mrschmidt<at>google.com)? Does it occur with just this one type of query?

There is a document returned. I'll grab more log when I start working on it again. Yes, it happens on each call.

**Comment by jameswtc** [comment]
> You are sending a query that produces no results. I was hoping that we would see a Document as part of the result set that contains some non-standard types, which could then explain the error message (and it would be similar to [GoogleCloudPlatform/node-red-contrib-google-cloud@f649320](https://github.com/GoogleCloudPlatform/node-red-contrib-google-cloud/commit/f649320)).
> 
> Is this error pretty reproducible for you? If so, is there a repro you could share with us (either publicly or privately at mrschmidt(at)google.com)? Does it occur with just this one type of query?

Funny thing. Whenever I have the logging enable:

`firebaseAdmin.firestore.setLogFunction(console.log);`

the error is gone.

**Comment by jameswtc** [comment]
It seems that the issue is gone now with the latest updates. But I'm not sure if it will happens again with npm/node upgrade.

**Comment by schmidt-sebastian** [comment]
Thanks for the update. I have not heard of any other instances, so I hope that this issue will not occur again.
