### ISSUE TITLE
[FR] Configure to use production database even when running with emulators

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-admin-node#1096]
I'm trying to run test for a migration logic that get data from a production database, and inject it into another database. But when using firebase-admin, it always use the local emulator for both, there is no way to have `firebase-admin` use the product database when `FIREBASE_DATABASE_EMULATOR_HOST` is defined.

I think `firebase-admin` should not connect to the emulator if a specific configuration is passed.

**Comment by SamyPesse** [comment]
The source of this is https://github.com/firebase/firebase-js-sdk/blob/ef33328f7cb7d585a1304ed39649f5b69a111b3c/packages/database/src/core/RepoManager.ts#L140

**Comment by samtstern** [comment]
@SamyPesse thanks for the feedback, can you elaborate on what you mean by "when a specific configuration is passed"?

**Comment by SamyPesse** [comment]
@samtstern We don't use the configuration coming from google cloud cli file or from the function itself, we always pass the service account ourselves using:

```typescript
const app = admin.initializeApp(
    {
        // @ts-ignore
        credential: admin.credential.cert(someConfigObject),
        projectId: someConfigObject.project_id,
        databaseURL: `https://${someConfigObject.project_id}.firebaseio.com`,
    },
    'origin'
);
```

When passing a file with a projectId and credential, I don't always want firebase-admin to connect to the firebase emulator.
Running the emulator doesn't mean that I want **all** firebase requests to go to the emulator.

**Comment by hiranya911** [comment]
@samtstern @yuchenshi is there anything more to this? Looks like WAI to me.

**Comment by SamyPesse** [comment]
An alternative solution that works for me is:

```ts
const { auth, database } = withoutEnvs(() => {
    const app = admin.initializeApp(
        {
           // PRODUCTION config here
        },
        'origin'
    );

    return {
        auth: app.auth(),
        database: app.database(),
    };
}, [
    // Remove env used to connect to local emulator if any
    // because of https://github.com/firebase/firebase-admin-node/issues/1096
    'FIREBASE_DATABASE_EMULATOR_HOST',
    'FIRESTORE_EMULATOR_HOST',
    'FIREBASE_AUTH_EMULATOR_HOST',
]);

function withoutEnvs<T>(fn: () => T, envs: string[]): T {
    const saved: Array<[string, string]> = [];

    envs.forEach((key) => {
        saved.push([key, process.env[key]]);
        delete process.env[key];
    });

    const result = fn();

    saved.forEach(([key, value]) => {
        if (value) {
            process.env[key] = value;
        }
    });

    return result;
}
```

**Comment by samtstern** [comment]
I've been thinking about this one and I don't think there is a feasible way to fix this without reducing safety for those who don't understand this.  Right now we're sticking with "if the emulator is running, we should connect to it". 

The worst possible situation is the reverse of yours: if someone wants to connect to the emulator but accidentally connects to production they could be destroying real user data. We have to optimize to prevent that where we can.

For advanced use cases like yours you'll probably need to continue using "hacks" like the workaround you discovered. Thanks for prompting this discussion, I hope my rationale makes sense!

**Comment by SamyPesse** [comment]
@samtstern Thanks and yes it totally makes sense 👍  especially "if someone wants to connect to the emulator but accidentally connects to production they could be destroying real user data. We have to optimize to prevent that where we can."
