### ISSUE TITLE
missing "path" field in Query  typescript type definition

### ISSUE THREAD

**Issue by beyondeye** [firebase/firebase-admin-node#1099]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 9.4.1
  * Firebase Product: database
  * Node.js version: 10
  * NPM version: 6.9.0
  * typescript version: 3.9.7

### [REQUIRED] Step 3: Describe the problem
I have just updated the firebase-admin-node:
from  8.9.0 to  9.4.1

and now there are some missing properties in type definition for admin.database.Query;
the "path" property is not defined anymore.
also admin.database.Reference.push() method used to be defined to return a promise while now in the type definition
it returns a Reference.
the "wrong" type definitions seems to come from the package  @firebase/database-types@^0.5.2
what I want to use are the type definitions from "@firebase/database" package, that is also installed as a dependency of
firebase-admin, but I cannot do it. I need to install @firebase/database as separate dependency in order to use it

#### Steps to reproduce:
N/A
#### Relevant Code:
N/A

**Comment by schmidt-sebastian** [comment]
This property was removed since it was only ever accidentally added to the typings of the Firebase Admin SDK and referred to an internal type that was never published. We have since converged out types, and unfortunately this resulted in a breaking change from 8.x to 9.x. 
Here are some ideas for workarounds: https://stackoverflow.com/questions/37872478/how-to-get-firebase-database-reference-full-path

**Comment by beyondeye** [comment]
thanks for the explanation and for the workaround. Still there is a problem with Reference.push(). in @firebase/database-types@^0.5.2 its output is  defined as a Reference not a ThenableReference. I saw in the documentation 
https://firebase.google.com/docs/reference/js/firebase.database.Reference#push  that it should return a ThenableReference.

**Comment by schmidt-sebastian** [comment]
@beyondeye This was fixed in the 0.6.x release of database-types. I will ping @hiranya911 to update the dependency. Thanks for letting us know!
