### ISSUE TITLE
Support types for NodeJS 12

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-admin-node#1100]
### [REQUIRED] Step 2: Describe your environment

  * Firebase SDK version: 9.4.1
  * Firebase Product: admin
  * Node.js version: 12

### [REQUIRED] Step 3: Describe the problem
Now that cloud functions support for[ NodeJS 12 is at the GA level](https://cloud.google.com/functions/docs/release-notes), the type dependencies should reflect that, so instead of depending on the types for Node 10, it should depend in either the types for node 10 or the types for node 12.

See https://github.com/firebase/firebase-admin-node/blob/a98a3cc275f9fee0474ff1905d2217a600d5f57e/package.json#L61

That line should probably be changed to something like:
```
"@types/node": "^10.10.0 || ^12"
```

I'm not sure though if that dependency really needs to be a runtime dependency or it it could be moved to a dev dependency.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
I think we can make it a dev dependency (and is probably the right course of action). I'll take a look in the coming days.

**Comment by swftvsn** [comment]
This has proven to be a problem for us also. Please consider to work on it.

**Comment by nikhilag** [comment]
I believe this issue has been fixed in https://github.com/firebase/firebase-admin-node/pull/1258
