### ISSUE TITLE
[FR] Better handling of Date objects

### ISSUE THREAD

**Issue by PomegranateApps** [firebase/firebase-admin-node#1108]
**Is your feature request related to a problem? Please describe.**

Currently, you have to handle Date objects differently when updating to a Firestore document or returning to a Firebase client from a cloud function.

```
// Saving to Firestore requires Date object:
var item = {
   "myDate": new Date()
}

// Returning to client requires something else like a timestamp:
var item = {
   "myDate": (new Date()).getTime()
}
```

**Describe the solution you'd like**

I would like to see a way to return a Date object back to the client and have Firebase automatically handle the conversion. Currently, I have to send the Date object back as a timestamp and then also know from the client to convert that number back to a date object.

**Comment by schmidt-sebastian** [comment]
@PomegranateApps Thanks for filing this.

Unfortunately, Dates are lossy for Firestore as they cannot represent the precision that the backend exposes. This leads to all sorts of unintended consequences and can even result in data loss (say when the Date object that is based on a `FieldValue.serverTimestamp()` is used in Query constraint). To make it easier to write correct code, we deliberate expose every Date as a Timestamp object, thereby preserving microsecond precision.

If you purely want to read the same type of data that you wrote, we recommend using Timestamps even when you initially write the data.

**Comment by PomegranateApps** [comment]
I'm having a lot of issues working with dates when going back and forth between my iOS app and my cloud function.

I'm sending complex documents sometimes to my cloud function from my iOS app. The dates are encoded as `FIRTimestamp`objects but when I save these documents from my cloud function the date fields get saved as numbers with the timestamp values.

I'm not sure the best way to make sure these fields always get saved as a timestamp in Firestore instead of as a number.

**Comment by schmidt-sebastian** [comment]
The issues you described led us to remove first-party support for Date objects. The interchange format we recommend is a tuple of seconds and nanos as exposed here: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L1880
