### ISSUE TITLE
Setting metadata in upload method doesn't work as expected

### ISSUE THREAD

**Issue by RezaRahmati** [firebase/firebase-admin-node#1115]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Win 10
* firebase-admin": "9.4.1",
* firebase-functions": "3.11.0",
  * Firebase Product: storage
  * Node.js version: 14.15.0
  * NPM version: 6.13.0

#### Steps to reproduce:

Upload a file to storage via node.js
Confirm you get the downloadLink, and downloadlink is working
Find the uploaded file in Firebase Console > Storage
Click on Open button

Expected
Open the file

Actual
It adds Undefined to the url and opens the project home page

Root cause:
Seems metadata is not set on the files

#### Relevant Code:

```
import * as admin from 'firebase-admin';
import { v4 as uuidV4 } from 'uuid';
...
		const bucket = admin.storage().bucket();
		const [file, meta] = await bucket.upload(tempLocalFile, {
			destination: 'test/file.png',
			resumable: false,
			public: true,
			contentType: 'image/png',
			metadata: {
				firebaseStorageDownloadTokens: uuidV4(),
			},
		});

		return {
			imageUrl: meta.mediaLink,
			imageStorageLocation: `gs://${meta.bucket}/${meta.name}`,
		};
```

#### Workaround to solve the issue
As a workaround you need to set the metadata again as below

```
		const bucket = admin.storage().bucket();
		const [file, meta] = await bucket.upload(tempLocalFile, {
			destination: 'test/file.png',
			resumable: false,
			public: true,
			contentType: 'image/png',
			metadata: {
				firebaseStorageDownloadTokens: uuidV4(),
			},
		});

		const metadata = {
			metadata: {
				firebaseStorageDownloadTokens: uuidV4(),
			},
		};

		await file.setMetadata(metadata);

		return {
			imageUrl: meta.mediaLink,
			imageStorageLocation: `gs://${meta.bucket}/${meta.name}`,
		};
```
![storgae-issue](https://user-images.githubusercontent.com/10086092/101851584-d6e59480-3b29-11eb-8cbf-6af6e453d52a.gif)

**Comment by hiranya911** [comment]
Your metadata configuration is not correct. It should be:

```js
                 const [file, meta] = await bucket.upload(tempLocalFile, {
			destination: 'test/file.png',
			resumable: false,
			public: true,			
			metadata: {
                                 contentType: 'image/png', // This should also be nested within metadata
                                 metadata: { // needs another level of "metadata" for the storage token
				    firebaseStorageDownloadTokens: uuidV4(),
                                 },
			},
		});
```

See the code samples in https://googleapis.dev/nodejs/storage/latest/Bucket.html#upload and https://stackoverflow.com/a/43764656/5190886
