### ISSUE TITLE
[FR] messaging. Messaging .send*: Documentation should clarify dryRun deficiency detecting APNS token unregistration

### ISSUE THREAD

**Issue by CapnSpellcheck** [firebase/firebase-admin-node#1116]
**Is your feature request related to a problem? Please describe.**
Based on a complete review of Apple APNS documentation, I've found no support of anything like a "dry run" feature. The dryRun feature is documented on this SDK as simply: "Whether to send the message in the dry-run (validation only) mode." When dryRun is used with tokens delivered to Android, errors such as 'messaging/registration-token-not-registered' are returned in appropriate cases where the token has been unregistered. However, I believe this is not the case with tokens delivered to iOS. Do you have any evidence otherwise?

**Describe the solution you'd like**
The documentation for the send methods, at https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging, should elaborate on the nuances of `dryRun` for APNS-served devices if my belief stated above is correct.

**Describe alternatives you've considered**

**Additional context**

**Comment by chong-shao** [comment]
Hi @CapnSpellcheck , just to clarify: in this request, "APNS token unregistration" means the deletion of APNS token using this client-side API: https://developer.apple.com/documentation/uikit/uiapplication/1623093-unregisterforremotenotifications . is that correct?

**Comment by CapnSpellcheck** [comment]
Hello,

Actually, I am referring to unregistration without any request from the app
or app's infrastructure. In other words, automatic unregistration by
Apple/APNS due to user's deletion of the app.

**Comment by chong-shao** [comment]
Hi @CapnSpellcheck thanks fo the clarification. Yes I confirm that in the case you described, dry-run cannot be used to detect the deletion of the APNS token.  I'll update the documentation to reflect that.
