### ISSUE TITLE
TenantAwareAuth creates users in the wrong tenant when using createCustomToken

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [firebase/firebase-admin-node#1119]
**Thank you for submitting your issue. We are operating at reduced capacity from Dec 18 2020 to Jan 4 2021. Please expect delayed responses. For more urgent requests please reach us via our  support channels https://firebase.google.com/support**

### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS 10.15.7 
  * Firebase SDK version: firebase-admin@9.4.2
  * Firebase Product: auth
  * Node.js version: v10.22.1
  * NPM version: 6.14.6

### [REQUIRED] Step 3: Describe the problem

I have a custom login system that assigns users to particular Identity Platform tenants, and passes back a custom token so the client can log in to the particular tenant. Unfortunately, the `createCustomToken` method is not tenant-aware and is creating the user in the root tenant instead of the one I specified.

#### Steps to reproduce:

When creating the token, we use a TenantAwareAuth object with a particular tenantId set:
```
const firebaseTenantId = 'org1-y6bqo';  // Taken from Cloud Console, where this tenant already exists. 
const auth = admin.auth().tenantManager().authForTenant(firebaseTenantId)
const newUid = uuidv4();
return await auth.createCustomToken(newUid, {
        fooClaim: 'bar'
});
```
This is supposed to create a new user in the `org1-y6bqo` tenant, but instead it is creating users in the root tenant (id-less).

![image](https://user-images.githubusercontent.com/66106280/102923519-1d51c200-444d-11eb-98f6-18ceb8eb8a3b.png)

**Comment by jakebiesinger-storyhealth** [comment]
More code to show the problem:

```
const firebaseTenantId = 'org1-y6bqo';  // Taken from Cloud Console, where this tenant already exists. 
const auth = admin.auth().tenantManager().authForTenant(firebaseTenantId)
const newUid = uuidv4();

const token = await auth.createCustomToken(newUid, {
        fooClaim: 'bar'
});

// Try to get the user we just created
try {
  console.log(`tenant-aware auth user: ${await auth.getUser(uid)});
} catch (err) {
  console.log(`tenant-aware auth failed! ${JSON.stringify(err)}`);
}

try {
  console.log(`Root auth user: ${await admin.auth().getUser(uid)});
} catch (err) {
  console.log(`root auth failed! ${JSON.stringify(err)}`);
}
```

Running the above will yield a failure on the tenant-aware auth, but the user will be found by the root auth, without a tenantId set:

```
>  UserRecord {
>    uid: '3ef937ff-66ac-46c5-91ff-b9ac6d3dbbe5',
>    email: undefined,
>    emailVerified: false,
>    displayName: undefined,
>    photoURL: undefined,
>    phoneNumber: undefined,
>    disabled: false,
>    metadata: UserMetadata {
>      creationTime: 'Tue, 22 Dec 2020 18:41:48 GMT',
>      lastSignInTime: 'Tue, 22 Dec 2020 19:08:52 GMT',
>      lastRefreshTime: 'Tue, 22 Dec 2020 19:08:52 GMT'
>    },
>    providerData: [],
>    passwordHash: undefined,
>    passwordSalt: undefined,
>    tokensValidAfterTime: undefined,
>    tenantId: undefined
>  }
```

**Comment by jakebiesinger-storyhealth** [comment]
Testing more with this, it appears to be a problem in the client rather than the server. Our client login code does not specify a tenantId when performing the login:

```
await firebase.auth().signInWithCustomToken(result.data.token);
```

Makes sense, but I see a few issues here: 

1. I expected the firebase auth library to notice that the tenant_id is set in the token and to utilize it without any work from me. In particular, to work around this problem, I have to decode the token, grab the `tenant_id`, get a tenant-aware-auth object and use *that* to sign in.

2. I would not expect that a token generated by one tenant would be valid for logging in to another tenant, yet apparently a token generated for my `org1-y6bqo` tenant can be used to create a user and log in to the root tenant. This seems like a huge security hole-- these MUST NOT be interchangeable, otherwise, a bad actor with a legitimate account in `tenant1` can create a user account in some other tenant, potentially gaining access to areas they shouldn't be able to. Seems like separate tenants should have their own signing keys rather than having them shared across tenants.

**Comment by bojeil-google** [comment]
I think there are 2 issues here:

- You need to set the tenant ID before sign in: `firebase.auth().tenantId = 'my-tenant';`
- We should throw an error if the JWT has a tenant and sign in is triggered using a tenant scoped custom token without a tenant ID in the request.

**Comment by wuyanna** [comment]
If the sign-in request does not have a tenant ID, then the custom token is considered to be created for the default root project. That's why you only saw the user in the root project but not the tenant. To be clear the custom token can only be used to sign-in to the root project and the tenant specified in the token, but not the other tenants. It is a valid concern though that the token created for a specific tenant should not be used to sign-in to the root project, but erroring out on that could potentially introduce a breaking change because some projects might set tenant_id as a custom claim in the custom token. We will investigate on the potential impact on enforcing this.

**Comment by jakebiesinger-storyhealth** [comment]
> If the sign-in request does not have a tenant ID, then the custom token
is considered to be created for the default root project.

Understood, and glad that this doesn't allow log in in arbitrary tenants,
though to be fair, the root tenant is possibly the most sensitive as that's
where it own developer accounts reside.

And again, I was just very surprised that the login request doesn't observe
the tenantid in the jwt. Hopefully this can be fixed without further impact.

>

**Comment by hiranya911** [comment]
@bojeil-google @wuyanna is there any action item for this repo? Looks like the suggested changes are for the client (JS) SDK.

**Comment by hiranya911** [comment]
I see. Can we reference an internal bug number and close this?

**Comment by wuyanna** [comment]
Internal bug tacking: b/176188967
