### ISSUE TITLE
Conflicting Types for @types/node when using node 14

### ISSUE THREAD

**Issue by DrCheddar** [firebase/firebase-admin-node#1121]
**Thank you for submitting your issue. We are operating at reduced capacity from Dec 18 2020 to Jan 4 2021. Please expect delayed responses. For more urgent requests please reach us via our  support channels https://firebase.google.com/support**

### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows
  * Firebase SDK version: firebase-admin@9.4.2
  * Firebase Product: firebase-admin
  * Node.js version: 14.2.0
  * NPM version: 6.14.4

### [REQUIRED] Step 3: Describe the problem

When using node 14 with typescript's @types/node@14.14.16, attempting to compile with tsc gives a conflicting definition of 'node' error: 
![image](https://user-images.githubusercontent.com/46302202/103184160-b5540f00-4884-11eb-87c2-dc1a5c9a256e.png)

I need to use node 14 because something in fs-extra is broken in node 12.

#### Steps to reproduce:

1. Upgraded node version to node 14
2. Upgraded node types to @types/node@latest to fix fs-extra error in node 12
3. Ran tsc - got the conflicting node error

#### Relevant Code:

```tsconfig.json
  "dependencies": {
    "@types/node": "^14.14.16",
...
    "firebase-admin": "^9.4.2",

```

**Comment by DrCheddar** [comment]
for some reason if I downgrade firebase-admin to 9.0.0 it seems to work fine

**Comment by hiranya911** [comment]
> for some reason if I downgrade firebase-admin to 9.0.0 it seems to work fine

That's strange. Both v9.0.0 and v9.4.0 depends on same version of `@types/node`. 

https://github.com/firebase/firebase-admin-node/blob/v9.0.0/package.json#L58
https://github.com/firebase/firebase-admin-node/blob/v9.4.0/package.json#L61

However, v9.4.0 ships with auto-generated typings that contains `/// <reference types="node" />` directives. It seems in that case `tsc` requires both the SDK and the user code agree on the typing versions they use.

This is partially related to #1100. I'm not sure what the right fix in this case could be. Will continue to explore options. Also appreciate any thoughts from other TS experts who might know better.

**Comment by swftvsn** [comment]
This has proven to be a problem for us also. Please consider to work on it.

**Comment by francescov1** [comment]
+1 this issue is preventing us from upgrading as well

**Comment by rmsy** [comment]
I was also having this issue, but I only needed to downgrade to `9.3.0` to resolve it, not all the way to `9.0.0`.

**Comment by jeansoonsik** [comment]
+1 I have downgraded to `9.3.0` to resolve it, but it got an error when sending push notification `FirebaseMessagingError: SenderId mismatch`

**Comment by nikhilag** [comment]
I started a PR to fix this issue. I also published a temporary package "firebase-admin-nikhilag" (https://www.npmjs.com/package/firebase-admin-nikhilag) to unblock my own project.

**Comment by hiranya911** [comment]
I don't think the PR will actually "fix" this issue (see my comment on the PR). You will most likely need a project-level workaround like this in the `tsconfig.json` to resolve it:

```
"typeRoots": [
    "node_modules/@types"
]
```

**Comment by nikhilag** [comment]
@hiranya911 Thanks for reviewing the fix. With my fix, I did try with `"@types/node": "^14.14.16",` and it worked correctly. I followed the same usage pattern as grpc-js where they use the greater than or equal to sign to allow higher versions: ` "@types/node": ">=12.12.47",`
Please let me know if I am missing something.

**Comment by hiranya911** [comment]
I'm trying to repro the original issue, but so far haven't been able to. I've tried `firebase-admin` 9.7.0 and 9.6.0, and `@types/node` v12 and v14. But none of the combinations have resulted in a compilation error. Can somebody share a minimal, complete repro for us to test?

Here's one of the configurations I tested:

```
{
  "name": "helloworld",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^14.14.16",
    "firebase-admin": "9.6.0"
  },
  "devDependencies": {
    "typescript": "^3.8.0"
  }
}
```

```ts
import { Agent } from 'http';
import * as admin from 'firebase-admin';

export function init(agent: Agent): admin.app.App {
  return admin.initializeApp({
    httpAgent: agent,
  });
}

export function createCustomToken(): Promise<string> {
  const auth: admin.auth.Auth = admin.auth();
  return auth.createCustomToken('alice');
};

export function addUser(): Promise<void> {
  const db: admin.firestore.Firestore = admin.firestore();
  return db.collection('users').doc().set({uid: 'alice'})
    .then(() => {
      console.log('DONE');
    });
}
```

**Comment by nikhilag** [comment]
@hiranya911 I will work over the weekend to try to find a repro. In my backend code, I did check that 9.7.0 is failing but 9.8.0 is working correctly.

**Comment by nikhilag** [comment]
@hiranya911 I was unable to repro the issue using your code but in my backend code, I get these errors:-
![image](https://user-images.githubusercontent.com/54072321/118433870-98b45880-b6f9-11eb-952c-3fbd7bca3f19.png)

Tried a bunch of imports but nothing seemed to break in your code above. Will definitely give it a few more tries.

**Comment by hiranya911** [comment]
Going to close this for now, since#1258 provides a solution for now.
