### ISSUE TITLE
[FR] Change userId API

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-admin-node#1123]
**Is your feature request related to a problem? Please describe.**

I have a server logic that will create firebase userID with custom format, but also want a user to login only with third party provider. Which is a flow that firebase auth can't handle easily

And so the solution I use is, I let user login at client side with auth provider. But then user will send IdToken to my server, I will use admin sdk to verify, get user record then delete that user and then import data and provider from the deleted record to the new ID I create for them (with `importUsers`)

It seem like it work fine but because it was 3 step processes. There was a chance that it wouldn't run properly. Such as error when import, the user was already deleted and the process flow are interrupted. Simply put it was the problem of atomic transaction. Also these 3 api are tedious and not so wieldy, especially import that need to get the record before 

**Describe the solution you'd like**

I wish we could have an API that, given the userID and another string ID, it will just do the process I explain above, just changing the userID to the new ID we specify with every data and provider intact. And so user can just reload or reauthenticate with the same and their userID will be changed

With this API we could also decide to change userID to be a new format anytime we need. We might decide to change application logic to have all userID formatted with some kind of data, such as create an ID that formatted to be creation time, which will allow us to sort by userID in database

```js
// server side, admin sdk
var idToken = queryString["idToken"];
var verified = await admin.auth().verifyIdToken(idToken);
var newid = GenerateCustomUniqueID();
await admin.auth().changeUserID(verified.uid,newid);


// at client side
await firebase.auth().currentUser.reload(); // userID would be changed to newid
```

**Describe alternatives you've considered**

I think the better solution for user creation is, there should be another API in client to allow sign in with provider, but not create user just yet. `firebase.auth().logInWithCredential(credential)` for example (`logIn` as oppose to `signIn`). And also an ability to serialize login credential in some way, to let user send it to server, and admin SDK then have another API to sign in with that serialized

```js
// client side
var user = await firebase.auth().logInWithCredential(credential);
if(user == null) // user not exist then not create user, just return null
{
    var token = await firebase.auth().getSignInTokenFromCredential(credential); // encrypted token to send to server
    var response = await HttpGet("https://serverside.io/?token=" + token);
    if(response.statusCode == 200)
        user = await firebase.auth().logInWithCredential(credential); // should be able to get user with uid
}


// server side, admin sdk
var token = queryString["token"];
var uid = GenerateCustomUniqueID();
var user = await admin.auth().createUserWithCredentialToken(uid,token);
if(user != null)
    return { statusCode : 200 }; // success
return { statusCode : 400 }; // fail
```

But this api only fit for initializing

**Comment by bojeil-google** [comment]
User ID is immutable and cannot be changed. We are also unable to sign in a user without provisioning a user ID.
If you want the ability to provision your own user ID, you can sign in with custom token using your own provisioned user ID and then link the credential to that account.

**Comment by Thaina** [comment]
> User ID is immutable and cannot be changed. We are also unable to sign in a user without provisioning a user ID

I know but as I was emphasize that it is totally possible to do. It just `getUser` then `deleteUser` then `importUsers` with the exact same data except ID. It just prone to failure to have to do this task by separate functions. I would like to have these 3 combined into one call, internally it just do these 3 steps in the server, which as I said, totally possible

**Comment by Thaina** [comment]
`If you want the ability to provision your own user ID, you can sign in with custom token using your own provisioned user ID and then link the credential to that account.`

The problem here is I want to do that in server, not in the client. As I have speculate in the alternative that, it would be great if there would be some function in client to serialize credential that user would like to link their account to, send it to server, and in server SDK there would be another function to take that credential to link with our own custom ID

Which as of today, there was none and I need to work around with IDToken, just as in #1124 

Please reopen both this and #1124

**Comment by bojeil-google** [comment]
You can use the [REST API](https://firebase.google.com/docs/reference/rest/auth#section-verify-custom-token) to do so. You can also use the client SDK from a Node.js environment. We currently don't have dedicated authenticated APIs to handle sign in operations in the Admin SDK.

**Comment by Thaina** [comment]
@bojeil-google The point is it also not ideal to have user send their access token to the server. That's why I propose both this and #1124 so that user can send just `idToken` (which is designed to be sent to server)

> We currently don't have

Isn't that the point of opening `feature request` issue?

**Comment by bojeil-google** [comment]
Hey @Thaina, these feature requests are very specific to your use case (eg. change user ID feature). If you want to re-file as a feature request for general admin sdk APIs to authenticate users, you are welcome to do so. (though we may already have that filed). I would also encourage you to open an [official feature request](https://firebase.google.com/support) for either use case.

**Comment by Thaina** [comment]
@bojeil-google Because this feature can be used to achieve the same goal

If you could allow us to change userID easily, then it don't really need to have user try to initial their account at creation site. We could allow user to signing in with their credential on client normally, but then we would be able to change their ID when they request account initializing on the server. And it would appeared to be perfectly the same in the end

Which is why I would like to have at least one reopen, the one that you would consider better suited for firebase admin API

**Comment by Thaina** [comment]
Also your feature request channel which is private is just totally a bin that was use to throwing request their and you will just neglect it. I has request features there for 3 years and mostly nothing have been moving at all since then

Feature request should be done in public repo like this so that people who face the same problem can also aggregate their voice in the same direction

**Comment by hiranya911** [comment]
Just want to reiterate that the user ID is an immutable primary key in Firebase Auth. So we cannot provide an API to facilitate that -- the model simply doesn't allow it. You can of course try to "emulate" changing the UID, by doing a sequence of `deleteUser()` and `createUser()` calls, but as far as Firebase Auth is concerned, you would have created 2 separate accounts with different UIDs. Deleting the old account forces that user to logout, and they will have to log back in with the new account. Other Firebase services like Firestore, Storage, Rules etc will essentially see and treat them as 2 separate users. 

As @bojeil-google mentioned, account linking is the closest you can come to implementing your use case with Firebase Auth.

**Comment by Thaina** [comment]
> "emulate" changing the UID, by doing a sequence of `deleteUser()` and `createUser()` calls, but as far as Firebase Auth is concerned, you would have created 2 separate accounts with different UIDs. Deleting the old account forces that user to logout, and they will have to log back in with the new account. Other Firebase services like Firestore, Storage, Rules etc will essentially see and treat them as 2 separate users.

That's totally acceptable behaviour of `changeUserID` function. At the time user has been logged out from deleted old account, that old account coun't have connection to any other service anymore. Other service would then only know about the new account and that's what I want (If there was anything that was related to old account in other services, then I know I need to cleanup after that)

What I really need is the API that would `emulate` this behaviour in one promise, in transactional process. It must delete and create with the deleted data. And because userdata should be exactly the same except userID. It should accept just old userID and new userID, then do that sequence above for me
