### ISSUE TITLE
[FR] Create user with idToken

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-admin-node#1124]
**Is your feature request related to a problem? Please describe.**

For the user login flow
- User signin with provider in client sdk
- User get idToken and send to server
- Server verified token. But there are not user exist in firebase yet

I then want a simple API to create user with idToken

**Describe the solution you'd like**

A new apis

```js
admin.auth().getOrCreateUser(idToken) => {}
admin.auth().createUserWithID(overrideID,verifiedFirebaseToken) => {} 
admin.auth().getOrCreateUserWithID(idToken,idIfNotExist) => {}

//// usage

var idToken = "xxx";
var verified = await admin.auth().verifyIdToken(idToken);
try
{
    return await admin.auth().getUser(verified.Uid);
}
catch(e)
{
    console.error(e);
    return await admin.auth().createUserWithID("overrideCustomID",verified);
}
```

Above is equivalence to 

```js
var idToken = "xxx";
return await admin.auth().getOrCreateUserWithID(idToken,"overrideCustomID");
```

`admin.auth().getOrCreateUser(idToken)` will create user directly with the idToken's uid

**Describe alternatives you've considered**

Currently now I just use api `importUsers` by extract datas from verified idtoken claims. Which is hard and tedious. There aren't even documentation about how IdToken was linked with user identities credential (it was in the field `Claims.firebase.identities` and the identity is an array, why it is array though?)

**Additional context**

**Comment by bojeil-google** [comment]
This is a different form of: https://github.com/firebase/firebase-admin-node/issues/1123
Please check the answer there. You can use custom tokens to provision your own user ID and then link the credential.
For the most of it, sign in with custom token is a form of creating a user with a JWT / ID token.

**Comment by Thaina** [comment]
@bojeil-google No, it was the opposite flow from what I would like to do

I couldn't give the ID I would like to link user with beforehand. I need to have user send a proper request to the server that they would like to create new account, with some required initial data. I then take that request to determine the ID for that user, and create firebase account with that ID

With your flow there would be a chance that, they give the initial data to us and I was prepare the account for them, but then they decide not to link their account with my data, and then I would waste my storage and other computation for that unowned account

And as I was explain above. I was able to workaround by complicate method, extracting idToken and then `importUsers`, which is possible but tedious. It should be able to handled with SDK directly
