### ISSUE TITLE
[FR] != and not-in query operators

### ISSUE THREAD

**Issue by eladdad** [firebase/firebase-admin-node#1131]
**Is your feature request related to a problem? Please describe.**
`!=` and `not-in` query operators are available in the Firestore client sdk, can we get them in the admin sdk?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hiranya911** [comment]
It's already supported. Feature added in v4.3.0 of `@google-cloud/firestore`: https://github.com/googleapis/nodejs-firestore/releases/tag/v4.3.0

Admin SDK currently uses Firestore v4.5.0 and higher.

**Comment by jaxnz** [comment]
Can confirm that `!=` and `not-in` aren't working in `firebase-admin` 9.4.2 

Current dependency `@google-cloud/firestore: "^3.0.0"` - needs to be updated to min v4.3
