### ISSUE TITLE
Database rules apis does not automatically use emulator

### ISSUE THREAD

**Issue by rams23** [firebase/firebase-admin-node#1149]
###  Describe your environment

  * Operating System version:  Windows 10 Pro 20H2
  * Firebase SDK version: 9.4.2
  * Firebase Product: database
  * Node.js version: 12.15.0
  * NPM version: 6.13.4

### Describe the problem
When using the rules APIs of the database (setRules or getRules) against the emulator, the DatabaseRulesClient does not automatically change the URL to FIREBASE_DATABASE_EMULATOR_HOST, while the other APIs do. Moreover, it does not use the EmulatorAdminTokenProvider. Instead, it tries to get a real token.

### Steps to reproduce:

* setup env variables for FIREBASE_DATABASE_EMULATOR_HOST and GCLOUD_PROJECT 
* run a production-ready code that should utilize the emulator when env variables are set

#### Relevant Code:

```js
const admin = require('firebase-admin');
const rules = require('./database.rules.json');

const app = admin.initializeApp();

app.database('https://database-instance.firebasedatabase.app').setRules(rules)
    .then(res=>console.log('Rules set successfully'))
    .catch(err=>console.error(err));

```

#### Analysis

The initStandalone method from @firebase/database is aware of FIREBASE_DATABASE_EMULATOR_HOST and switches to emulator URLs and EmulatorAdminTokenProvider. However, the DatabaseRulesClient does not use getToken nor the URL from the RTDB instance initialized by initStandalone.  

I'm not too familiar with the repo, but I see that the URL and the authProvider are deep inside private fields of the RTDB instance and Repo classes. I would be happy to help to create a PR if anyone can provide me with a nice way to get the actual URL and provider from the RTDB instance.

**Comment by hiranya911** [comment]
Good catch. The RTDB rules management APIs are actually implemented in this repo itself, and are currently agnostic of the emulator. @yuchenshi any thoughts on what's the best course of action here?

**Comment by yuchenshi** [comment]
I've created b/179089690 in track this internally. In the meantime, feel free to create a PR to implement support for RTDB rules -- the emulators responds to `/.settings/rules.json?ns=database-instance` just like production.

The Firestore rules management API should be punted though since the emulator only supports updating security rules and therefore there is no one-to-one match with the ruleset management features.
