### ISSUE TITLE
self signed certificate in certificate chain error

### ISSUE THREAD

**Issue by benhurott** [firebase/firebase-admin-node#115]
* Operating System version: [Docker PM2](https://hub.docker.com/r/keymetrics/pm2/)
  * Firebase SDK version: 5.2.1
  * Library version: _____ (???)
  * Firebase Product: database (auth, database, storage, etc)

When use express with HTTPS we facing this error: `0|www      | FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"self signed certificate in certificate chain\"."}`

When we use HTTP, no errors.

**Comment by hiranya911** [comment]
Try the instructions at https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request and see if that helps.

**Comment by benhurott** [comment]
Hi @hiranya911, 

When a try it, the error now is: `0|www      | FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"socket hang up\"."}`

I try some other solutions for this error message but none of them works...

**Comment by hiranya911** [comment]
Have you tried syncing your clock? Can you also share more details about your code and environment?

**Comment by benhurott** [comment]
We are investigating if is some issue with our infrastructure.

For now we have these informations:
* Firebase works in dev, on my machine independently HTTP or HTTPS.
* Firebase works on my machine, inside a PM2 Docker container.
* Firebase not works inside PM2 Docker container running on production VM (Ubuntu 16.04).

**Comment by benhurott** [comment]
Resolved!

Our infraestructure was blocking some google services.
Closing =).

**Comment by purusingh** [comment]
Hi there,

I am having the same issue.  its workingon azure but  locally in the office I am getting same error. can you please tell me  what service is blocking google servies?

**Comment by hiranya911** [comment]
Probably a corporate proxy/firewall.

**Comment by nhoctanker** [comment]
@benhurott Hello how to fix that . my copnay block some service . What service we need eabled
