### ISSUE TITLE
node-forge high severity security issue

### ISSUE THREAD

**Issue by denno020** [firebase/firebase-admin-node#1150]
* Operating System version: Windows 10
  * Firebase SDK version: 7.10.0
  * Firebase Product: admin
  * Node.js version: 12.16.3
  * NPM version: 6.14.4

#### Steps to reproduce:

Run `npm audit` in a cloud functions folder.

There are 4 high severity security issues, all related to `node-forge@0.10.0`

#### Relevant Code:

![image](https://user-images.githubusercontent.com/2059313/106370229-ef469280-63a7-11eb-9ae8-dfec5de595ca.png)

**Comment by hiranya911** [comment]
False positive? The issue description says the problem exists in node-forge versions before 0.10.0. But we are already on 0.10.0 (which is also the latest available today).

**Comment by hiranya911** [comment]
I think this is your problem:

```
Firebase SDK version: 7.10.0
```

Upgrade to a more recent version of the SDK.
