### ISSUE TITLE
[FR] Import user with a non U.S. phone number

### ISSUE THREAD

**Issue by andreyorlov33** [firebase/firebase-admin-node#1154]
**Is your feature request related to a problem? Please describe.**
When using `admin.auth().importUsers` - if a user does not have a US phone number (+1XXXXXXXXXX) an error is going to be thrown saying that the phone number format is invalid. 
**Describe the solution you'd like**
Need to be able import users with non U.S. phone numbers - ex +(86) XXX XXXXXXXX (China)
**Describe alternatives you've considered**
Make `phoneNumber` field optional when importing users.  
**Additional context**
Add any other context, code samples or screenshots about the feature request here.

**Comment by hiranya911** [comment]
`phoneNumber` field is optional when importing users:

 https://github.com/firebase/firebase-admin-node/blob/1862342636e816b61337262254cdfe0cc410c640/src/auth/index.ts#L814-L817

We only check that the phone number starts with `+`. It doesn't have to be `+1`. 

https://github.com/firebase/firebase-admin-node/blob/1862342636e816b61337262254cdfe0cc410c640/src/utils/validator.ts#L176-L187

Please share the exact error message you received.

**Comment by bojeil-google** [comment]
I don't understand the question. We definitely accept non-US phone numbers as long as they are in E.164 format.
`phoneNumber` field is optional already.

**Comment by hiranya911** [comment]
Closing this due to lack of context.
