### ISSUE TITLE
Invalid database URL causes Node process to get stuck

### ISSUE THREAD

**Issue by pulyaevskiy** [firebase/firebase-admin-node#116]
* Operating System version: macOS 10.12.6 (Sierra)
  * Firebase SDK version: 5.4.2
  * Library version: 5.4.2
  * Firebase Product: database
  * Node version: v8.1.0

#### Steps to reproduce:

If `databaseUrl` is malformed in any way then Node process gets stuck and does nothing. No error is reported and it seems to never timeout.

#### Relevant Code

Example to reproduce the issue:

```js
var admin = require("firebase-admin");

var serviceAccount = require("path/to/serviceAccountKey.json");

admin.initializeApp({
  credential: serviceAccount,
  databaseURL: "“https://your-project-id.firebaseio.com“" // note extra quotes
});

var ref = admin.database().ref("/messages/test/uppercase");
// This Promise never resolves:
ref.set('some value').then(function (value) {
    admin.app().delete();
});
```

### Expected behavior:

* Validate URL for structure and invalid characters. In my case I had extra quotes around the URL in an environment variable: `export FIREBASE_DATABASE_URL="“https://proj-id.firebaseio.com”"`. However a properly structured URL but wrong URL results in the same behavior, e.g. `https://proj-id.some-other-domain.com`.
* Throw an error after timeout.
* Bonus points: if timeout is configurable.

**Comment by pulyaevskiy** [comment]
Is anyone watching this repository?

**Comment by pulyaevskiy** [comment]
@hiranya911 thanks for getting back and for the link! Just needed to get some feedback here.
I'll see if I can find some time for a PR.

**Comment by hiranya911** [comment]
@jshcrowthe @schmidt-sebastian can we implement some stronger URL validation in the RTDB module?

**Comment by hiranya911** [comment]
Actually I see that more recent versions of the RTDB client logs a warning for malformed URLs:

```
[1970-01-01T00:00:01.000Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
```

Marking as fixed.
