### ISSUE TITLE
message: 'TTL must be a non-negative duration in milliseconds'  issue in 9.4.2 version using .messaging().sendMulticast

### ISSUE THREAD

**Issue by EgHubs** [firebase/firebase-admin-node#1163]
My function is
```
 var message = { 
      "tokens": registrationTokens,
        "notification": {
            "title": "Fire!!!",
            "body": "There is a smoke detected at" ,//+firedata
        },
        "android":{
          "priority":"high",
          "ttl":"259200s",//3 days in seconds
          "notification":{ 
            "channel_id": "notii_push",
            "sound": "alarm.mp3",
            "color":"#900000"
          }
        },
        "apns": {  
         "headers":{
           "apns-priority":"10"
         },
        "payload": {
           "aps": {
              "sound": 'alarm.wav'
            }
          }
      } ,
      "priority" : "high",   
      "content_available" : true
    };
    console.log('Tokens to send are ' + registrationTokens);
   await admin.messaging().sendMulticast(message)
    .then((response) => {
     return console.log(response.successCount + ' messages were sent successfully');
    }
    )  .catch((error) => {
      return console.log('Error sending message:', error);
    });
```
and i get message: 'TTL must be a non-negative duration in milliseconds'..

The issue still appears in 9.4.2 version using .messaging().sendMulticast

_Originally posted by @tominou in https://github.com/firebase/firebase-admin-node/issues/479#issuecomment-770352274_

**Comment by hiranya911** [comment]
ttl must be a "number":

https://github.com/firebase/firebase-admin-node/blob/bea66a90b12408313c3f1b54b67e19cc32c25421/src/messaging/index.ts#L426-L429

You have passed a string value:
```
"ttl":"259200s",//3 days in seconds
```

**Comment by EgHubs** [comment]
I wrote it like the [documentation ](https://firebase.google.com/docs/cloud-messaging/concept-options#example-notification-message-with-platform-specific-delivery-options)

**Comment by hiranya911** [comment]
That documentation is for the REST API and the examples show the low-level JSON payload that should be sent in the HTTP request. Here's the documentation for the Node.js SDK:

https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig#ttl

**Comment by smash-96** [comment]
> That documentation is for the REST API and the examples show the low-level JSON payload that should be sent in the HTTP request. Here's the documentation for the Node.js SDK:
> 
> https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig#ttl

He's right. This solved my issue!

**Comment by tethridge** [comment]
Updated link.  The one above doesn't work anymore.

https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.androidconfig.md#androidconfigttl
