### ISSUE TITLE
Typescript build issue - "no exported member BaseExternalAccountClient"

### ISSUE THREAD

**Issue by thatjuan** [firebase/firebase-admin-node#1169]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 18.04
  * Firebase SDK version: 8.2.7
  * Firebase Product: firebase-admin (auth, database, storage, etc)
  * Node.js version: 10.23.0
  * NPM version: 6.14.8

### [REQUIRED] Step 3: Describe the problem

After a recent update to `firebase-admin@9.5.0`, I'm running into a TypeScript build error:

```
node_modules/google-gax/build/src/fallback.d.ts:21:69 - error TS2305: Module '"../../../google-auth-library/build/src"' has no exported member 'BaseExternalAccountClient'.

21 import { GoogleAuth, OAuth2Client, Compute, JWT, UserRefreshClient, BaseExternalAccountClient } from 'google-auth-library';
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~
```

#### Steps to reproduce:

Not entirely sure. I'm using TypeScript 4.0.3 to build.

**Comment by trex-quo** [comment]
@thatjuan Did you fix this?

**Comment by rully-orenda** [comment]
@trex-quo Did you fix this?

**Comment by rully-orenda** [comment]
After diving into the node_modules folder i found that the google-auth-library installed was an older version that do not export a BaseExternalAccountClient class. So i just get the new version and then the error is gone.
