### ISSUE TITLE
[FR] [Cloud Firestore] Add device connectivity triggers for online presence 

### ISSUE THREAD

**Issue by VictorUvarov** [firebase/firebase-admin-node#1171]
**Is your feature request related to a problem? Please describe.**
I want to implement a realtime online status of users on `Cloud Firestore` and `Cloud Functions`, but the current solution requires `Realtime Database` [current solution](https://firebase.google.com/docs/firestore/solutions/presence)

**Describe the solution you'd like**
I don't want to have to depend on `Realtime Database` for online presense. I wish the events were built/exposed into the cloud firestore apis.

**Describe alternatives you've considered**
Using my own server with websockets instead of `Cloud Firestore`

**Additional context**
I don't know if this is even the correct repo to ask for this feature request

**Comment by hiranya911** [comment]
> I don't know if this is even the correct repo to ask for this feature request

It's not :)

Please file a feature request at https://firebase.google.com/support/troubleshooter/report
