### ISSUE TITLE
Possible security risk of credentials being exposed

### ISSUE THREAD

**Issue by Joebayld** [firebase/firebase-admin-node#1174]
I've been looking for a library that handles recursive importing / exporting. After doing some digging - I found something rather frightening. 

If a FieldValue of type `DocumentReference` is in the document and you recursively convert that object to JSON, all of firebase's settings are encoded to JSON - including sensitive info such as the private keys. I'm wondering if there's a way that this doesn't get stored in the object as it could be dangerous? 

An example of this going south would be a malicious user that knows exporting is used in a project would save any document reference as a field, then after performing the export - the user would now have the private keys. 

I know this is something developers need to make sure they're handling - but I was totally blindsided by the fact that my private keys were in a JSON export! I'm attaching some links to other issues (some that I've created) with this happening. However, I'm opening this issue here as well to see if there's anything that can be done on the library side of things. 

https://github.com/dalenguyen/firestore-backup-restore/issues/84
https://github.com/dalenguyen/firestore-backup-restore/issues/87
https://github.com/jloosli/node-firestore-import-export/issues/673

Thanks!
Joe

**Comment by hiranya911** [comment]
We don't offer any APIs for export/import. It seems you're using a third-party tool (firestore-backup-restore) for that functionality. How they have chosen to handle the export of document references is a design choice they have made.

Both `firebase-admin` and the underlying `@google-cloud/firestore` packages offer basic primitives for saving and querying data in Firestore. We do not attempt to interpret the user data in any way. At our API level it's all treated as Firestore data types (string, number, boolean, map etc).

**Comment by Joebayld** [comment]
An update on this - this doesn’t pertain to 3rd party libraries. 

A simple `JSON.stringing(documentRef)` will return my private keys in the string. Do you not agree that this can be a vulnerability? 

I’m not insisting that google is interpreting the data, but as a user of firebase - it would be dangerous if I ever returned a stringified JSON to the client.

**Comment by hiranya911** [comment]
> A simple JSON.stringify(documentRef) will return my private keys in the string.

It looks like you're not referring to the actual data queried from Firestore, but how the `DocumentReference` type is implemented in `@google-cloud/firestore`, which exposes `credentials` via `DocumentReference.firestore.settings`:

https://github.com/googleapis/nodejs-firestore/blob/685e75cf447b80679fc5a94731f5307d4601b750/types/firestore.d.ts#L916-L920
https://github.com/googleapis/nodejs-firestore/blob/685e75cf447b80679fc5a94731f5307d4601b750/types/firestore.d.ts#L132-L139

This is what causes `JSON.stringify(docRef)` to serialize credentials. 

> Do you not agree that this can be a vulnerability?

I would argue that the same level of caution that is exercised to safeguard the credentials on the server runtime, should be applied in coding to make sure any internal APIs are not exposed to the user. That implies not directly json serializing any Firestore data that may contain references to other documents.

However, this case is somewhat interesting so I'd also recommend you to file an issue at the `@google-cloud/firestore` repo (linked above), and see if they have a more specific fix or a mitigation. That's where the Firestore SDK is developed, and therefore that's where this issue can be addressed.
