### ISSUE TITLE
when Reference.key can be null

### ISSUE THREAD

**Issue by Sagunt0022** [firebase/firebase-admin-node#1177]
this my code

    const userKey = (await db.ref(`/users`).push(user)).key;

typescript says userKey can be string | null.

when `(await db.ref("/users").push(user)).key` return null ?

**Comment by hiranya911** [comment]
Please use StackOverflow for usage questions. For your specific question: https://github.com/firebase/firebase-js-sdk/blob/97f7e38819cda74cafbb7e9a8b86fdfead47d7fc/packages/database/src/api/Reference.ts#L81-L90
