### ISSUE TITLE
Firebase Cloud Messaging not getting the Android Icon in notification

### ISSUE THREAD

**Issue by AugustoAleGon** [firebase/firebase-admin-node#1178]
Describe your environment

  * Operating System version: Mac
  * Firebase SDK version: ^9.4.2
  * Firebase Product: messaging
  * Node.js version: 12.16.3
  * NPM version: 6.14.8

Currently I am testing push notification on Android using the method `.send` in messages.
I already tested my client side with FCM console and the notification icon works perfect, also I used the method `.sendToDevice`and is working fine. 

In order to reproduce send I used this:

```
const note = {
    android: {
        priority: 'HIGH',
        data: {
            title: '#test',
            body: 'New message',
            icon: 'ic_notification',
            color: '#FFF',
            sound: 'default',
            tag: 'undefined',
            channelId: 'bundle.id,
            visibility: 'private',
            // image: '',
            host: 'http://localhost:3000/',
            type: 'p',
            name: 'test'
        },
        fcm_options: {
            analytics_label: 'click_notification'
        }
    },
    token: 'FCM_TOKEN'
};

admin.messaging().send(note)
```

The result is the following:

![result](https://user-images.githubusercontent.com/14319083/109072590-38e27e80-76c3-11eb-87b1-8dbd7beefc07.jpg)

This actually what I got from FCM console:

![expected_result](https://user-images.githubusercontent.com/14319083/109072627-46980400-76c3-11eb-888f-f929a06c8981.jpg)

I also tried to remove the icon section as well. I got the same result.

**Comment by hiranya911** [comment]
You are passing icon and other settings as part `data`. It should be set as part of `notification`:

https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig#notification
https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidNotification

**Comment by AugustoAleGon** [comment]
@hiranya911 I am checking the structure of the code and I don't see any `icon` label on the `notification` object.

This the notification object in your own library. https://github.com/firebase/firebase-admin-node/blob/93362d5721fc45f3fc541543813d5739eda8ba2d/src/messaging/index.ts#L90

**Comment by AugustoAleGon** [comment]
@hiranya911 I was testing your suggestion on the method send. The response is the following:

```
(node:21096) UnhandledPromiseRejectionWarning: Error: Invalid JSON payload received. Unknown name "icon" at 'message.notification': Cannot find field.
```

I am sending this payload:

const note = {
    notification: {
        icon: 'ic_notification'
    },
    android: {
        priority: 'HIGH',
        data: {
            title: '#test',
            body: 'New message',
            color: '#FFF',
            sound: 'default',
            tag: 'undefined',
            channelId: 'bundle.id,
            visibility: 'private',
            // image: '',
            host: 'http://localhost:3000/',
            type: 'p',
            name: 'test'
        },
        fcm_options: {
            analytics_label: 'click_notification'
        }
    },
    token: 'FCM_TOKEN'
};

admin.messaging().send(note)

**Comment by hiranya911** [comment]
You're looking at the wrong type. Correct type is called `AndroidNotification`:

https://github.com/firebase/firebase-admin-node/blob/93362d5721fc45f3fc541543813d5739eda8ba2d/src/messaging/index.ts#L455-L633

**Comment by hiranya911** [comment]
>  I was testing your suggestion on the method send. The response is the following:

Your payload is still incorrect. Please take another look at the API reference docs I've linked above. You can also find an example involving the `icon` setting here:

https://firebase.google.com/docs/cloud-messaging/send-message#example-notification-message-with-platform-specific-delivery-options

**Comment by AugustoAleGon** [comment]
Ohh I see. You are totally right. I was sending the information wrong. Thank you so much.
