### ISSUE TITLE
NodeJS crashes while running in cloud due to --> Error: Failed to import the Cloud Storage client library for Node.js.

### ISSUE THREAD

**Issue by AnthonyNahas** [firebase/firebase-admin-node#118]
Cloud 
 * Operating System version: cloud - Heroku PAAS NodeJS
  * Firebase SDK version: 5.4.3
  * Library version: 5.4.3
  * Firebase Product: auth,storage

Local
 * Operating System version: MacOS 10.11.6
  * Firebase SDK version: 5.4.3
  * Library version: 5.4.3
  * Firebase Product: auth,storage

### Problem

I am using firebase-admin with nodejs in order to authenticate users and manage the storage with firebase. Everything is working fine locally. But when i push my code to heroku and after executing npm install, my nodejs crashes directly --> see below.

local
![local](https://user-images.githubusercontent.com/20149774/31965595-1f6e8c04-b908-11e7-9b92-811a393ef816.png)

cloud
![cloud](https://user-images.githubusercontent.com/20149774/31965606-271bb364-b908-11e7-8f1e-f5331d8bbd5e.png)

PS: @google-cloud/storage is installed within firebase-admin...

```
app/node_modules/firebase-admin/lib/storage/storage.js:61
            throw new error_1.FirebaseError({
            ^

Error: Failed to import the Cloud Storage client library for Node.js. Make sure to install the "@google-cloud/storage" npm package.
    at new FirebaseError (/app/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new Storage (/app/node_modules/firebase-admin/lib/storage/storage.js:61:19)
    at /app/node_modules/firebase-admin/lib/firebase-app.js:247:20
    at FirebaseApp.ensureService_ (/app/node_modules/firebase-admin/lib/firebase-app.js:307:23)
    at FirebaseApp.storage (/app/node_modules/firebase-admin/lib/firebase-app.js:246:21)
    at FirebaseNamespace.fn (/app/node_modules/firebase-admin/lib/firebase-namespace.js:270:42)
```

why should i install additionally @google-cloud/storage or firebase-admin's dependencies?

### workaround

is to install @google-cloud/storage as deps for my server...

#### Steps to reproduce (standard execution..):

```
- npm install
- npm run build
- npm start (nodejs server will start)
```

**Comment by hiranya911** [comment]
Can you check if the code is actually installed under `@google-cloud/storage`?

Also share your full stack trace. The one above seems truncated.

**Comment by hiranya911** [comment]
It is also interesting that you have `firestore` and `common` installed in your local set up (which is expected), but not in heroku. I wonder if your installation was interrupted somehow.

**Comment by AnthonyNahas** [comment]
Hi, i will close the issue since i found that the problem is related to npm engine and not to firebase-admin sdk.

## Observation and solution:
i am running node v 8.5.0 on my local machine as well as in the cloud. The only difference between the two states, is the npm engine! On my local OS, npm is running with the latest version 5.5.1 and on heroku npm is running under the version 5.4.0.
To Fix that, i pulled the latest version of npm on heroku --> it works!
`npm install` seems to be interrupted with version 5.4.0

**Comment by SamuelSaltzmann** [comment]
Just to let you know, I got the same message and when I updated my node engine within the package.json it worked.

So I added to package.json:
`"engines": {"node": "8"}
`
