### ISSUE TITLE
ERR_HTTP_HEADERS_SENT: Cannot set cookie

### ISSUE THREAD

**Issue by Darfion** [firebase/firebase-admin-node#1180]
this is my code

    import { Request, Response } from "express";
    import { database } from "firebase-admin";

    async function updatereAccessToken(
      req: Request,
      res: Response,
      db: database.Database
    ) {
      try {

        await db
          .ref(
            `/token/${"-MUQK0wGmrjPVBdFH7gr"}/${"90417abf-b085-4072-b4ec-f009b5fe4016"}`
          )
          .set("90417abf-b085-4072-b4ec-f009b5fe4016");

        
        await db
          .ref(
            `/token/${"-MUQK0wGmrjPVBdFH7gr"}/${"90417abf-b085-4072-b4ec-f009b5fe4016"}`
          )
          .set("90417abf-b085-4072-b4ec-f009b5fe4016");

    //comments

        res.cookie("act", "tokenAuth.accessToken", {
          httpOnly: true,
          sameSite: "lax",
        });
    
        res.cookie("ret", "tokenAuth.refreshToken", {
          httpOnly: true,
          sameSite: "lax",
        });
    
        return "currentUser";
      } catch (error) {}
    }

Code works before comment.then i get error

> [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
   at ServerResponse.setHeader (_http_outgoing.js:558:11)

Split the code into two parts

***1***

        await db
          .ref(
            `/token/${"-MUQK0wGmrjPVBdFH7gr"}/${"90417abf-b085-4072-b4ec-f009b5fe4016"}`
          )
          .set("90417abf-b085-4072-b4ec-f009b5fe4016");

        
        await db
          .ref(
            `/token/${"-MUQK0wGmrjPVBdFH7gr"}/${"90417abf-b085-4072-b4ec-f009b5fe4016"}`
          )
          .set("90417abf-b085-4072-b4ec-f009b5fe4016");

***2***

    res.cookie("act", "tokenAuth.accessToken", {
              httpOnly: true,
              sameSite: "lax",
            });
        
            res.cookie("ret", "tokenAuth.refreshToken", {
              httpOnly: true,
              sameSite: "lax",
            });

These two parts of the code work separately, but not together. What is the reason ?.

**Comment by hiranya911** [comment]
Please use StackOverflow for usage questions and debugging help.
