### ISSUE TITLE
Messaging interface BaseMessage is no longer exported

### ISSUE THREAD

**Issue by rubenvereecken** [firebase/firebase-admin-node#1184]
I just upgraded to `7.5.0`coming from `7.2.1`. I just noticed I could no longer import the `BaseMessage` interface, which I use because I've got some functionality that is independent of the exact type of Message. It looks like the interface is no longer exported. Is this on purpose? I had a look at where this was taken out but I struggled navigating the `git blame` on Github.

https://github.com/firebase/firebase-admin-node/blob/01d8177650676a142474229538f0b469fc363a65/src/messaging/index.ts#L52

**Comment by lahirumaramba** [comment]
Hi @rubenvereecken! Thank you for reporting this issue.

@hiranya911 should we export `BaseMessage` along with the rest we did in #1147 ?

**Comment by hiranya911** [comment]
`BaseMessage` was never intended to be part of our public API surface. In the old releases it was declared outside of the `admin.messaging` namespace to keep it separate from the public API:

https://github.com/firebase/firebase-admin-node/blob/d0ccf8fcb168e773a3ea7f1869abb003a90c5105/src/index.d.ts#L392-L398

In more recent versions it is in the namespace, but is not exported:

https://github.com/firebase/firebase-admin-node/blob/6bcffa2fdca8ee9b9fb49a0109ddc72f4f6d4c2e/src/messaging/index.ts#L52-L59

@rubenvereecken can you use the `Message` type for your use case? Most things that that can be assigned to `BaseMessage` can be assigned to `Message`.

Also, can you please verify your SDK versions? We have never released a 7.2.1 or a 7.5.0.

**Comment by rubenvereecken** [comment]
... I think I meant 9.2.1 and 9.5.0 as I seem to have 9.5.0 installed currently.

My current solution to get this working consists of using `TokenMessage | MulticastMessage`, pretty close to using `Message` which I noticed is a union type. The problem is that `TokenMessage` for example requires the `token` field, which I currently simply set to `null` until it gets populated later, if indeed it does. I used to use `BaseMessage` because I've got some generic functionality that fills in a bunch of basic fields. Only afterwards does the object become a `TokenMessage` or `MulticastMessage`, depending on what I need. Maybe this is unorthodox use of typing because I "upgrade" an object from one type to another.

**Comment by hiranya911** [comment]
You can probably do something like this:

```typescript
type MyBaseMessage = Partial<TokenMessage | MulticastMessage>

function addCommonFields(m: MyBaseMessage) {
  
}

const m = { };
addCommonFields(m);

const tm: TokenMessage = {...m, token: 'token'};
const mm: MulticastMessage = {...m, tokens: ['token']};
```

**Comment by rubenvereecken** [comment]
Actually, that's right, I'm very happy with that solution. Thanks @hiranya911!

**Comment by hiranya911** [comment]
Glad to hear that @rubenvereecken. We can also revisit the issue of exposing `BaseMessage` once our new modular API surface (on going effort), is a bit more fleshed out.
