### ISSUE TITLE
[Messaging] Missing condition for 404 error response status

### ISSUE THREAD

**Issue by jor3l** [firebase/firebase-admin-node#1191]
Code is running on firebase functions. We check for error.code and always get `messaging/unknown-error` when the body of the requests clearly shows a 404. This should be either `messaging/registration-token-not-registered` or something similar.

Looking at the source, you can see that there is no case for 404 here:
https://github.com/firebase/firebase-admin-node/blob/6bcffa2fdca8ee9b9fb49a0109ddc72f4f6d4c2e/src/messaging/messaging-errors-internal.ts#L37-L58

Reproduce by passing a unregistered token to the messaging.send and check the returned error code.

**Comment by hiranya911** [comment]
The code you're referring to is for handling non-JSON/HTML responses. Are you getting an HTML response from FCM? Can you please share the full error message and stack traces?

If you're getting HTML back from FCM that indicates an operational problem in the FCM service. There was a similar bug report yesterday on a different repo.

@chong-shao FYA

**Comment by chong-shao** [comment]
Yesterday we identified and fixed a problem in our backend. Does the issue still persist?

**Comment by jor3l** [comment]
We were consistently getting this error for the past we days, it seem to have stopped a few hours ago so probably fixed?. Thanks for the input and I'll let you guys know if it happens again.

**Comment by hiranya911** [comment]
Closing this based on the last couple of comments. Let us know if the problem surfaces again.
