### ISSUE TITLE
[FR] FCM Error handling

### ISSUE THREAD

**Issue by nasht00** [firebase/firebase-admin-node#1192]
The `SendResponse` object contains an `err` object of type `FirebaseError`.  
`FirebaseError` contains a string `code` with the only description being `Some examples include "auth/invalid-uid" and "messaging/invalid-recipient".`.  

What am I supposed to do with the errors? Is there a more detailed list?  

For example, I probably want to remove users that unregistered the app. What would be the error code for this?

**Comment by hiranya911** [comment]
Error handling for Admin Node.js SDK is expected to change in the future. But in the meantime error codes are defined at https://firebase.google.com/docs/cloud-messaging/send-message#admin
