### ISSUE TITLE
[Messaging]: send method unexpected behavior

### ISSUE THREAD

**Issue by stoleruradu** [firebase/firebase-admin-node#1196]
### Environment
  * Operating System version: MacOS Big Sur
  * Firebase SDK version: 9.5.0
  * Firebase Product: messaging
  * Node.js version: v12.18.4
  * NPM version: 6.14.6

#### Steps to reproduce:
Let's say we have a simple wrapper function on top of original **messaging.send** method. 
```
import { messaging, Message } from 'firebase-admin';

function sendPushNotificationToDevice(device: IDevice, message: Message): void {
   messaging()
        .send(message)
        .then(() => console.log(`Successfully send push notification(s) to ${device.token}`))
        .catch(() => console.error(`Failed to send push notification to token: ${device.token}`));
}
```
At first look this code is 100% safe.
After checking the implementation of the ***[send method](https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging.ts#L241)*** you'll find that not all parts of the method return a ***Promise*** and the ***send*** itself is not defined as ***async***.
Consequently when something is wrong the call of ***send method*** sometimes will throw errors and sometimes will return promises with rejected state. This behavior is in contradiction with the defined return type ***Promise\<string\>***.

#### Expected behavior:
Send method should always return a ***Promise***.

#### Potentially related to this [issue](https://github.com/firebase/firebase-admin-node/issues/1000)
Because of the catch branch in the example code sample.

**Comment by hiranya911** [comment]
We currently do all local argument validation synchronously, and throw errors instead of rejecting. This may not be ideal, but it is fairly consistent. We do not expect developers to "handle" these errors, as they generally represent programming errors and violations of the API contract. 

We do have some upcoming plans to adopt an "always-reject" policy for our errors. But in the meantime, we do not plan to change the existing behavior, as it could be a breaking change for some developers.

**Comment by stoleruradu** [comment]
@hiranya911 I understand your worries about breaking changes for some developers, but what about current developers that build their applications on top of existing "unexpected behavior"?

**Comment by hiranya911** [comment]
Like I said, we don't expect anybody to handle these error conditions. They represent programming errors, and should be handled at the developer's end. Current implementation simply results in fail-fast semantics, which is good enough to track down what the issue is and fix it.

**Comment by hiranya911** [comment]
Also current developers can just use async/await, which side steps this problem entirely. That is if they really must catch argument validation errors for some reason.

```typescript
try {
  await admin.messaging().send(msg);
} catch (err) {
  // Will catch both throws exceptions as well as rejections
}
```

**Comment by lahirumaramba** [comment]
Closing due of inactivity.
