### ISSUE TITLE
Unable to check if token is revoked for tenant user

### ISSUE THREAD

**Issue by rohitmohan96** [firebase/firebase-admin-node#1199]
* Operating System version: macOS 11.2.1
  * Firebase SDK version: 9.5.0
  * Firebase Product: auth (auth, database, storage, etc)
  * Node.js version: 14.15.1
  * NPM version: 6.14.8

In a multi-tenant setup where the `tenantId` is not known, I am able to verify the token using the admin sdk but I am not able to check if the token is revoked using `checkRevoked=true` in the `verifyIdToken` api.  

#### Steps to reproduce:

Using a token created from the client sdk, following these steps (https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#identity_verification), 

```javascript
admin.auth().verifyIdToken(token)
```

returns the decoded token with the `tenantId` available in `decodedToken.firebase.tenant`. 

But if I were to call the api using, 
```javascript
admin.auth().verifyIdToken(token, true)
```
I get the following error 
```
Error: There is no user record corresponding to the provided identifier.
```

This seems to be because the tenantId is not used from the decoded token when getting the user to check if the token is revoked here: https://github.com/firebase/firebase-admin-node/blob/bea66a90b12408313c3f1b54b67e19cc32c25421/src/auth/auth.ts#L735

**Comment by bojeil-google** [comment]
You need to provide the tenant ID. It looks like it is trying to lookup the user info but not finding it.
```
const tenantAuth = tenantManager.authForTenant(tenantId);
await tenantAuth.verifyIdToken(token, true)
```

`admin.auth().verifyIdToken(token)` succeeds because it just verifies the JWT without calling our server to confirm the user.

**Comment by hiranya911** [comment]
@bojeil-google we might want to document this behavior going forward. `Auth.verifyIdToken(token)` can verify tokens from any tenant. But `Auth.verifyIdToken(token, checkRevoked=true)`, can only verify tokens for the main tenant.

**Comment by hiranya911** [comment]
Possible workaround for @rohitmohan96:

```typescript
const decoded = await admin.auth().verifyIdToken(token);
const tenantId = decoded.firebase.tenantId;
const tenantAuth = admin.auth().tenantManager.authForTenant(tenantId);

await tenantAuth.verifyIdToken(token, true);
```

This will end up decoding the JWT twice, but it should be fairly fast once the certificates have been fetched and cached.

**Comment by rohitmohan96** [comment]
@hiranya911 Thanks. This is what I'm doing right now.
My current workaround is this, because tenantId can be undefined. 

```javascript
let auth = firebase.auth();
const decodedToken = await auth.verifyIdToken(token);
const tenantId = decodedToken.firebase.tenant;
if (tenantId) {
  auth = firebase.auth().tenantManager().authForTenant(tenantId);
}

// Check if token is revoked
return auth.verifyIdToken(token, true);
```
But I feel this is rather clunky.  Shouldn't this be done as part of the `verifyIdToken` itself?

**Comment by hiranya911** [comment]
> But I feel this is rather clunky. Shouldn't this be done as part of the verifyIdToken itself?

The `admin.auth()` API is not meant to handle tenant-scoped operations (and checking if a token is revoked is a tenant-scoped operation). You must use `authForTenant()` for that.

**Comment by bojeil-google** [comment]
> @bojeil-google we might want to document this behavior going forward. `Auth.verifyIdToken(token)` can verify tokens from any tenant. But `Auth.verifyIdToken(token, checkRevoked=true)`, can only verify tokens for the main tenant.

Good idea. I filed a request to document this.
