### ISSUE TITLE
Firebase-admin server nodejs initialization error

### ISSUE THREAD

**Issue by nestorLanex** [firebase/firebase-admin-node#1206]
please help! I got this error when initializing firebase-admin on my server. 

<img width="807" alt="Screen Shot 2021-03-26 at 11 44 18 PM" src="https://user-images.githubusercontent.com/46700497/112657245-2fe4f880-8e8d-11eb-98a2-d5e7eda754a8.png">

Error occurs here: 
<img width="587" alt="Screen Shot 2021-03-26 at 11 45 41 PM" src="https://user-images.githubusercontent.com/46700497/112657555-82beb000-8e8d-11eb-8636-6b0be503f83c.png">

**Environment details**
EXPRESS_FIREBASE_SERVICE_KEY_PATH=../serviceAccountKey.json

<img width="607" alt="Screen Shot 2021-03-26 at 11 47 43 PM" src="https://user-images.githubusercontent.com/46700497/112657729-ab46aa00-8e8d-11eb-8988-a0cba1378ce6.png">

npm version = 6.14.6
node version = 12.18.4
firebase admin version = 9.5.0

**Comment by lahirumaramba** [comment]
Hi @nestorLanex,
Looks like it is failing to identify the spread syntax. Are you using ES5?
Are you also using babel to transpile your code? If yes, you might need `@babel/plugin-proposal-object-rest-spread` in your environment. https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread
Otherwise, could you share the `package.json` file with us?
Thanks!

**Comment by nestorLanex** [comment]
This is how my package json looks like.
<img width="564" alt="Screen Shot 2021-03-27 at 11 19 13 AM" src="https://user-images.githubusercontent.com/46700497/112708665-45d6d580-8eee-11eb-9d6c-2fa0a42436d0.png">

i also tried your suggestion by adding `@babel/plugin-proposal-object-rest-spread`. It still didn't work

also tried this, 

<img width="333" alt="Screen Shot 2021-03-27 at 11 22 58 AM" src="https://user-images.githubusercontent.com/46700497/112708750-cd244900-8eee-11eb-8fd4-dcd53c14872a.png">

However, when i tried this method: 
<img width="482" alt="Screen Shot 2021-03-27 at 11 23 56 AM" src="https://user-images.githubusercontent.com/46700497/112708776-f1802580-8eee-11eb-9093-197799a93583.png">

it showed a different error: 
<img width="1350" alt="Screen Shot 2021-03-27 at 11 25 24 AM" src="https://user-images.githubusercontent.com/46700497/112708802-22605a80-8eef-11eb-9017-4575c0e693f2.png">

**Comment by nestorLanex** [comment]
i also did try a test spreading to see if it works: 
<img width="824" alt="Screen Shot 2021-03-29 at 10 37 44 AM" src="https://user-images.githubusercontent.com/46700497/112780148-cd514f80-907a-11eb-8247-e9c63ac86173.png">

It works just fine
<img width="695" alt="Screen Shot 2021-03-29 at 10 38 22 AM" src="https://user-images.githubusercontent.com/46700497/112780335-36d15e00-907b-11eb-949f-7a6b32206b1a.png">

**Comment by hiranya911** [comment]
Try loading the Firestore module directly:

```
const firestore = require('@google-cloud/firestore')
```

You can also try the spread operator on some sample code and see if it works.

```
const a = {foo: 'test'};
const b = {...a};
console.log(b);
```

**Comment by nestorLanex** [comment]
Finally found issue to my problem! 

I thought my node version was on node 12, but i forgot i was running this instance on docker.

My docker's node version was on Node 7, that's why the object didn't work.

I appreciate your help though. Sorry for the buzz guys. 

Have a great day!
