### ISSUE TITLE
npm update firebase-admin fails with ENOENT: no such file or directory, rename

### ISSUE THREAD

**Issue by dschnelldavis** [firebase/firebase-admin-node#121]
I think I have the same issue as posted [here](https://github.com/npm/npm/issues/18916) for NPM. However, I have not had this issue with any other packages, so I think the problem is firebase-admin version 5.4.3 (version 5.4.2 works fine), not NPM.

#### System info
Mac OS: 10.12.6
Node: 8.6.0
NPM:  5.5.1
firebase-admin: 5.4.2 -> 5.4.3
Installed NPM Packages:
> @ google-cloud/storage@1.4.0
> @ types/fs-extra@4.0.3
> child-process-promise@2.2.1
> cloudconvert@1.1.2
> firebase-admin@5.4.2
> firebase-functions@0.7.1
> fs-extra@4.0.2
> lodash@4.17.4
> mailgun-js@0.13.1
> mime@1.4.1
> ringcentral@3.1.3
> typescript@2.5.3

#### Install Error
Running `npm update` gives this error:
```shell
npm ERR! path /Users/Username/Sites/Sitename/functions/node_modules/firebase-admin/node_modules/grpc/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/abbrev' -> '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Username/.npm/_logs/2017-10-25T01_25_07_312Z-debug.log
```
And here's the relevant part of the log file:
```text
8231 verbose unlock done using /Users/Username/.npm/_locks/staging-e6d3ce262201f329.lock for /Users/Username/Sites/Sitename/node_modules/.staging
8232 verbose stack Error: ENOENT: no such file or directory, rename '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/abbrev' -> '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/.abbrev.DELETE'
8233 verbose cwd /Users/Username/Sites/Sitename
8234 verbose Darwin 16.7.0
8235 verbose argv "/Users/Username/.nvm/versions/node/v8.6.0/bin/node" "/Users/Username/.nvm/versions/node/v8.6.0/bin/npm" "update"
8236 verbose node v8.6.0
8237 verbose npm  v5.5.1
8238 error path /Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/abbrev
8239 error code ENOENT
8240 error errno -2
8241 error syscall rename
8242 error enoent ENOENT: no such file or directory, rename '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/abbrev' -> '/Users/Username/Sites/Sitename/node_modules/firebase-admin/node_modules/grpc/node_modules/.abbrev.DELETE'
8243 error enoent This is related to npm not being able to find a file.
8244 verbose exit [ -2, true ]
```

#### Fix

For now, I've locked my firebase-admin at version 5.4.2, which prevents the error, but also prevents upgrading.

Hopefully you can fix this in the next version.

Thanks!

**Comment by thakkaryash94** [comment]
I faced the same issue. try to remove `node_modules` and install again. It worked for me.

**Comment by dschnelldavis** [comment]
Issue Template:

### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue. - YES

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS 10.12.6
  * Firebase SDK version: 5.4.2 installed—attempting to install 5.4.3
  * Library version: 5.4.2 installed—attempting to install 5.4.3
(how is the "Library version" different from the "Firebase SDK version"?)
  * Firebase Product: N/A - problem is installing the library, not using it
Once I install it, I would like to use it for database and auth

### [REQUIRED] Step 3: Describe the problem

I am attempting to install firebase-admin version 5.4.3 through NPM.

#### Steps to reproduce:

In an NPM repository, install firebase-admin version 5.4.2. Then run `npm update` to attempt to install firebase-admin version 5.4.3. On my system it fails with the error message posted above. I tried completely removing my node_modules directory and reinstalling everything, but got the same error.

However, other people don't appear to be having the exact same symptoms, so it's possible you won't be able to reproduce it, which is why I posted the full error message and relevant section of the log file above.

#### Relevant Code:

See initial post, above.

**Comment by hiranya911** [comment]
What if you directly install the latest version of firebase-admin, instead of going the update route? Can't you just specify firebase-admin 5.4.3 as a dependency in your `package.json`?

**Comment by dschnelldavis** [comment]
Yes, that works. This definitely appears to be a problem _updating_, not installing.

Based on @thakkaryash94's and @hiranya911's comments, I unlocked my version of firebase-admin (changing it in package.json from "5.4.2" to "^5.4.2"), deleted my `node_modules` directory again, and did a clean `npm install`. And this time it re-installed everything without error.

Apparently the problem last time was that my firebase-admin version had been locked to "5.4.2", so after I reinstalled everything else, I still had to to upgrade from version 5.4.2 to 5.4.3 as a separate action, which gave me the error again. So, at least for me, updating from a previous version causes the error, but a clean install does not. (Though [this person](https://github.com/npm/npm/issues/18916) appears to have gotten a very similar error while doing a regular install, so it might act differently on different systems.)

So my personal problem is fixed. But I don't know whether you still need to change something to prevent this from happening again in future upgrades. (Having to delete node_modules and reinstall for every upgrade would get annoying, though I suppose I could live with it if I had to.) I'll let you decide if you think this issue should be closed immediately or warrants further investigation.

Thanks for the help!

Firebase rocks. Keep up the good work. :-)

**Comment by hiranya911** [comment]
Thanks @dschnelldavis for the update.

I was able to reproduce the issue with `npm update`, but have no idea what caused it or how to fix it. The most likely reason I can think of is that the `npm-shrinkwrap` files shipped with the 2 versions have slightly different formats (likely due to the releases being packaged from 2 versions of NPM). We've been thinking about pulling the shrinkwraps from the release artifacts, so that will probably clear this up.

**Comment by dschnelldavis** [comment]
Actually, if your theory is correct, this may no longer be an issue.

Assuming the change in `npm-shrinkwrap` caused the problem (which seems reasonable), then users of version 5.4.3 or above will never have this problem again (unless you change the npm-shrinkwrap file formats again in a future version).

The only people who will encounter this bug are people with version 5.4.2 or earlier who are upgrading to version 5.4.3 or later. And they can fix it by deleting their `node_modules` directory and running `npm install`—once—then it will never bother them again.

If that's the case, I'd say temporarily adding a note to your readme warning current users about the potential problem and its solution would be plenty.

(Or, if you got rid of the npm-shrinkwrap files instead, then you wouldn't even need the readme note. That's up to you. As a user, I'd be perfectly satisfied with either solution.)

**Comment by VinceOPS** [comment]
Hi guys. Just to share my experience as I've been through the exact same error using npm v4.6.1 with `npm install --save firebase-admin` (last version being 5.4.3 at the present time).

I had to update npm to npm 5 (v5.5.1) to install the package.

Cheers!

**Comment by hiranya911** [comment]
Thanks all for the comments. We have removed the shrinkwrap file, and future releases will not ship with one. This should not cause issues in the future.

**Comment by Shashaness** [comment]
OS X 10.12.x 

1) sudo rm -rf /usr/local/lib/node_modules
2) Install Stable Node.js from https://nodejs.org/dist/v8.9.4/node-v8.9.4.pkg
3) sudo npm install --unsafe-perm -g firebase-tools
4) firebase init <setup a new firebase deployment with functions and hosting)
5) firebase serve --only functions,hosting

The key for me was to completely delete node_modules directory from /usr/local/lib, and reinstall firebase-tools using the --unsafe-perm command line option. No other suggestion worked.

Hope this helps.

**Comment by kiransai333** [comment]
I got this error for adding firebase plugin
plugin : npm install angularfire2@4.0.0-rc0 firebase --save

npm ERR! code ENOLOCAL
npm ERR! Could not install from "firebase" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\system1\AppData\Roaming\npm-cache\_logs\2019-03-18T06_56_58_886Z-debug.log

**Comment by 5murdok5** [comment]
i soklved whit nvn 
-  nvm install 14
-  nvm use 14 
-  npm install -g firebase-tools
