### ISSUE TITLE
Problems with constructing geopoint using admin.firestore.Geopoint(0, 0) [Firestore]

### ISSUE THREAD

**Issue by aponski** [firebase/firebase-admin-node#1215]
### Describe the problem

In a cloud function I'm constructing geopoint using `new admin.firestore.Geopoint(0, 0)` and store it in firestore. However it is not properly recognised when viewing in the firestore UI browser. It is shown as simple object {_latitude: 0, _longitude: 0}. 

![image](https://user-images.githubusercontent.com/6552146/113316812-0ace0b00-930f-11eb-944b-d3cfe6e72f28.png)

When I construct geopoint in a frontend web app using `new firebase.firestore.GeoPoint(0, 0)` it is shown ok in firestore UI browser as [0° N, 0° E].

![image](https://user-images.githubusercontent.com/6552146/113316987-351fc880-930f-11eb-9c3a-80158cbac0b8.png)

**Comment by schmidt-sebastian** [comment]
Can you share you code? One possibility might that you are using `JSON.stringify()` before sending the data to the SDK.

**Comment by aponski** [comment]
I'm using axios to make request 

`
const payload = {
     geoPoint: new admin.firestore.GeoPoint(latitude, longitude), 
}

const response = await axios(
                {
                    method: 'post',
                    baseURL: baseApiUrl,
                    url: '/address',
                    params: {
                        api_token: apiToken
                    },
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    responseType: 'json',
                    data: paylod
                }
            )
`

**Comment by schmidt-sebastian** [comment]
Our types are only supported if you use the Admin SDK to write to the backend. If you are using the REST API, you have to manually serialize your data to the Protobuf REST representation (which can be quite a bit of work).

See details here: https://firebase.google.com/docs/firestore/use-rest-api
