### ISSUE TITLE
[FR] Hash round max limit for PBKDF2_SHA256

### ISSUE THREAD

**Issue by christopherbradleybanks** [firebase/firebase-admin-node#1219]
**Is your feature request related to a problem? Please describe.**
It is really frustrating that I am limited to 120000 rounds when choosing to Import Users with the PBKDF2_SHA256 algorithm as the database I am attempting to migrate from, uses 150000. This limit that is imposed appears arbitrary and prevents a legitimate use case from working.

**Describe the solution you'd like**
Remove this limitation or support the larger rounds option. 

**Describe alternatives you've considered**

I have considered 
Creating all the users using their hash as the password and forcing them to select forgot password (Bad User Experience)
Creating all the users using their hash as the password and intercepting their login request and performing the algorithm from the previous db programatically and passing that output as the password. (Introduces Janky Code)
Modifying the previous db to use a lower rounds option and rehash all the passwords the next time they sign in  (cannot guarantee completeness in a timely manor)

**Additional context**

**Comment by bojeil-google** [comment]
Thanks, @christopherbradleybanks. I filed an internal bug to address this and check if it is feasible to increase the limit.

**Comment by hiranya911** [comment]
Internally tracked at b/184668782

**Comment by josejibin** [comment]
@hiranya911 Just checking in on the PBKDF2 hash round limit (b/184668782). It’s been ~4 years, so totally understand if folks have moved teams. But any update or guidance would be really appreciated
