### ISSUE TITLE
[BUG] Firebase oficial documentation example has an error

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-admin-node#1232]
### [READ] Step 1: Are you in the right place?

I don't know, but I'm trying to report an obvious error if this is wrong place and you dont solve i dont care

### [REQUIRED] Step 2: Describe your environment

doesn't matter

#### Steps to reproduce:

The official firebase admin documentation show a code snippet with a serious error.

at the page: https://firebase.google.com/docs/auth/admin/manage-sessions
is said:

> Any data that requires authenticated access must have the following rule configured. This logic only allows authenticated users with unrevoked ID tokens to access the protected data:

```
{
  "rules": {
    "users": {
      "$user_id": {
        ".read": "$user_id === auth.uid && (
            !root.child('metadata').child(auth.uid).child('revokeTime').exists()
          || auth.token.auth_time > root.child('metadata').child(auth.uid).child('revokeTime').val()
        )",
        ".write": "$user_id === auth.uid && (
            !root.child('metadata').child(auth.uid).child('revokeTime').exists()
          || auth.token.auth_time > root.child('metadata').child(auth.uid).child('revokeTime').val()
        )",
      }
    }
  }
}
```

Although this rule is  syntactically correct, it will fail to evaluate and crash if `auth == null` causing firebase to register an "rule error" insteado of "permission denied"

There isn't much problem to the client application... but for someone monitoring firebase dashboard the "rule error metric" is usually a red flag while permission denied would be something like a yellow flag

**Comment by hiranya911** [comment]
This has been forwarded to the docs team.
