### ISSUE TITLE
Drop legacy import/export syntax

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-admin-node#1237]
This package uses legacy import/export syntax, the proposal was withdrawn and this syntax should not be used. Example:

https://github.com/firebase/firebase-admin-node/blob/58f60d680bc47641ef0216fbe8eff07afb030e5b/src/index.ts#L38

This causes issues across popular tools such as Babel and TypeScript and requires workarounds to make it work in newer environments (especially with native ESM).

I reported a similar issue against a different library of Firebase in the past: https://github.com/firebase/firebase-functions-test/issues/40.

**Comment by hiranya911** [comment]
I suppose the alternatives are named exports or default exports, both of which are breaking changes. We are not planning to make any changes to the old `firebase-admin` API surface at this point. It's on its way out. In the new API surface we are using named exports (although native ESM users will have to use the ESM-CJS interop mode for now):  #1230

**Comment by merlinnot** [comment]
Awesome, thanks for the update. Migration to a new version works for me.
