### ISSUE TITLE
Unable to resolve module os react native firebase-admin !

### ISSUE THREAD

**Issue by nessagh** [firebase/firebase-admin-node#1239]
Error: Unable to resolve module os from /Users/ghassen_gh/React/Okito/node_modules/firebase-admin/lib/credential/credential-internal.js: os could not be found within the project or in these directories:
  node_modules/firebase-admin/node_modules
  node_modules

**Comment by lahirumaramba** [comment]
The Admin SDK is a server library and requires a Node.js environment. The SDK will not work in a react native environment.
