### ISSUE TITLE
Upgrade @firebase/database (and possibly other @firebase/ dependencies)

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-admin-node#1241]
https://github.com/firebase/firebase-admin-node/blob/be4ebc61ed013315ffad954575f6223d44b5a80a/package.json#L59

Currently the `@firebase/database` dependency is limited to `^0.8.1` but there have been a [few releases](https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/CHANGELOG.md) since then - mainly the new `Query#startAfter` and `Query#endBefore` methods added in `0.9.X`.

I've tried upgrading `yarn add firebase-admin@latest` and also `yarn upgrade` and not getting a later `@firebase/database` version than `0.8.3` - but that does make sense as `^0.8.1` will only allow patch updates on the `0.8.X` line...

**Comment by 0xdevalias** [comment]
I believe this may also be the root cause of the issue we are seeing in our app (see https://github.com/sparkletown/sparkle/pull/1362#issuecomment-833438685), trying to use the latest `firebase` (`8.5.0`) with the latest `firebase-admin` (`8.7.0`).

See the linked comment for more specific details, but at a high level, it seems as though `firebase@8.5.0` requires  a `1.x` version of `@firebase/util` and `firebase-admin@8.7.0` requires a `0.x` version of `@firebase/util`. So having them together in the same package leads to issues.

---

This leads to the following warnings when installing the packages:

By default:
```
npm WARN @firebase/auth-types@0.10.3 requires a peer of @firebase/util@1.x but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/firestore-types@2.3.0 requires a peer of @firebase/util@1.x but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/storage-types@0.4.1 requires a peer of @firebase/util@1.x but none is installed. You must install peer dependencies yourself.
```

If I manually install `npm i @firebase/util@1.1.0`:

```
npm WARN @firebase/auth-interop-types@0.1.5 requires a peer of @firebase/util@0.x but none is installed. You must install peer dependencies yourself.
```

We can see the issue with `npm ls @firebase/util`:

```
⇒  npm ls @firebase/util
co-reality-map@0.1.0 /Users/devalias/dev/sparkle/sparkle
├── @firebase/util@1.1.0
├─┬ firebase@8.5.0
│ ├─┬ @firebase/analytics@0.6.10
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/app@0.6.21
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/database@0.10.0
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0  deduped
│ ├─┬ @firebase/firestore@2.3.0
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/functions@0.6.8
│ │ └─┬ @firebase/component@0.5.0
│ │   └── @firebase/util@1.1.0
│ ├─┬ @firebase/installations@0.4.26
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/messaging@0.7.10
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/performance@0.4.12
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/remote-config@0.1.37
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ ├─┬ @firebase/storage@0.5.2
│ │ ├─┬ @firebase/component@0.5.0
│ │ │ └── @firebase/util@1.1.0  deduped
│ │ └── @firebase/util@1.1.0
│ └── @firebase/util@1.1.0
└─┬ firebase-admin@9.7.0
  └─┬ @firebase/database@0.8.3
    ├─┬ @firebase/component@0.1.21
    │ └── @firebase/util@0.3.4
    └── UNMET PEER DEPENDENCY @firebase/util@0.3.4

npm ERR! peer dep missing: @firebase/util@0.x, required by @firebase/auth-interop-types@0.1.5
```

**Comment by 0xdevalias** [comment]
Potentially related: https://github.com/firebase/firebase-admin-node/issues/973#issuecomment-733414981

> We can fix every package except for . Fixing it for  will bring https://github.com/firebase/firebase-admin-node/issues/614 back.
> 
> I'm pondering if we should add  back to 's peerDependencies as it also breaks our compatibility with Yarn2 in the JS SDK repo. see https://github.com/firebase/firebase-js-sdk/issues/3707
> 
> The downside is admin SDK users will start seeing https://github.com/firebase/firebase-admin-node/issues/614 again. Maybe we should talk about creating a  package again, as the workaround in place seems to start causing compatibility issues with newer tools.
> 
> _Originally posted by @Feiyang1 in https://github.com/firebase/firebase-admin-node/issues/973#issuecomment-733414981_
