### ISSUE TITLE
File upload with firebase-admin doesn't have the same behavior of client library

### ISSUE THREAD

**Issue by pedroBruno7** [firebase/firebase-admin-node#1244]
Hi,

This issue is related to this other [issue](https://github.com/firebase/firebase-admin-node/issues/156)

When we upload a file to firebase via node.js, the preview does not appear on firebase dashboard and the public url is not generated

When we upload a file with node.js using:

upload bucket.upload(file.path, {
destination: ...
});

It will upload to google cloud and not to the firebase dashboard, hence the loading

I've tried it and was able to get the public link from google cloud

How to create the same behavior of the client API and upload the file to firebase and get a public URL with a token in a easy way?

It seems that there is no way to upload a file to firebase on the server

Thank you

**Comment by hiranya911** [comment]
This is a known issue, and unfortunately there's no simple fix. The two libraries use different backend APIs to access Cloud Storage, which result in different behaviors. 

> How to create the same behavior of the client API and upload the file to firebase and get a public URL with a token in a easy way?

#156 provides some possible workarounds. Specifically, you need to set you own token when uploading the file:

```
bucket.upload('example.txt', {
  metadata: {
    metadata: {
      firebaseStorageDownloadTokens: uuid(),
    },
  },
});
```

This will make the file appear on Firebase console.

**Comment by pedroBruno7** [comment]
@hiranya911  Thanks or the answer

I have two questions:
1. The final url file is not returned by the upload function like in the client. I concatenated the url using the structure https://firebasestorage.googleapis.com/v0/b/[app]/o/  ,  added %2F for the folder separation and the token in the end. Is this safe to do, the structure is always this one? with /o?
2. Finally, wouldn't it be a good idea for you to already to this inside the package, add a token and get the final url for consistency of the firebase ecosystem and package? It should be easy for you to do and it would decrease developer friction

Thanks a lot

**Comment by hiranya911** [comment]
Hi @pedroBruno7. My answers below:

1. Yes. You can reliably infer the download URL using this formula:

```js
const url = `https://firebasestorage.googleapis.com/v0/b/${bucketName}/o/${urlEncode(objectName)}?alt=media&token=${token}`
```

2. It would be great if we can reconcile these differences. But unfortunately it's not going to happen anytime soon. The server-side API for Cloud Storage is not developed by Firebase. It's a whole other subproject in Google Cloud at https://github.com/googleapis/nodejs-storage. Their use cases and priorities are somewhat different from ours when it comes to supporting download URLs. In the past we have attempted to add some of the Firebase-specific functionality into the server-side API (see https://github.com/googleapis/nodejs-storage/pull/1321), but that didn't receive a warm reception on their end.  The best we can hope at this point is to provide some extra utility APIs in `firebase-admin` that allow developers to upload objects and obtain token-based download URLs. That might happen someday, but it's not on our immediate roadmap.
