### ISSUE TITLE
[Firebase] hangs and return Error: Client is offline.

### ISSUE THREAD

**Issue by apotox** [firebase/firebase-admin-node#1256]
I'm using "firebase-admin": "^9.7.0" on gke, the pods have access to the internet but I got this error when trying to query documents from a real-time database.

root@pod-75d4865d87-sjz9p:/src/services# node trace.js 
starting...
Error: Error: Client is offline.
    at /node_modules/@firebase/database/dist/index.node.cjs.js:12813:35

**Comment by codinsonn** [comment]
> be sure to check !empty and trim() the database url

How?
