### ISSUE TITLE
Incorrect typing on `createUser` api in admin.auth leads to broken multi-factor auth

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [firebase/firebase-admin-node#1267]
* Operating System version: Mac OS 11.2.3
  * Firebase SDK version: 9.7.0
  * Firebase Product: auth
  * Node.js version: 12.21.0
  * NPM version: 7.7.0

### [REQUIRED] Step 3: Describe the problem

Typescript types are incorrect for `CreateMultiFactorInfoRequest` and `CreatePhoneMultiFactorInfoRequest` in `admin.auth.createUser`. I expect to be able to pass in a phone number but am not allowed by the type system. Instead, I have to cast the type as `any`.

#### Steps to reproduce:

```
admin.auth.createUser({
  displayName: 'somebody',
  email: 'some@one.com'
  emailVerified: true,
  multiFactor: { enrolledFactors: [{ factorId: 'phone', phoneNumber: request.phoneNumber }] }
}
```

This yields the error 
  
![image](https://user-images.githubusercontent.com/66106280/117735791-11239280-b1ab-11eb-9793-96f9288f8b1d.png)

You can work around this by casting the object to an `any`, but the type system is still wrong here.

This was also raised in https://github.com/firebase/firebase-admin-node/issues/1048 but for some reason that ticket was closed by the OP.

As a side-note, it feels like the code was written by someone who thought that extending a typescript `interface` would mean that instances of the derived class can be passed in instead of the base class, but with structural typing, this is not allowed.

**Comment by hiranya911** [comment]
How about rearranging our typings like this?

```ts
export interface BaseCreateMultiFactorInfoRequest {
  displayName?: string;
}

export interface CreatePhoneMultiFactorInfoRequest extends BaseCreateMultiFactorInfoRequest {
  factorId: 'phone';
  phoneNumber: string;
}

export type CreateMultiFactorInfoRequest = | CreatePhoneMultiFactorInfoRequest;

// Same for update types
```

This also enforces that the `factorId` field on `CreatePhoneMultiFactorInfoRequest` must be set to `"phone"`. Any semantically correct existing code should compile against the new typings, and therefore won't be a breaking change.

**Comment by bojeil-google** [comment]
> How about rearranging our typings like this?
> 
> ```ts
> export interface BaseCreateMultiFactorInfoRequest {
>   displayName?: string;
> }
> 
> export interface CreatePhoneMultiFactorInfoRequest extends BaseCreateMultiFactorInfoRequest {
>   factorId: 'phone';
>   phoneNumber: string;
> }
> 
> export type CreateMultiFactorInfoRequest = | CreatePhoneMultiFactorInfoRequest;
> 
> // Same for update types
> ```
> 
> This also enforces that the `factorId` field on `CreatePhoneMultiFactorInfoRequest` must be set to `"phone"`. Any semantically correct existing code should compile against the new typings, and therefore won't be a breaking change.

I think that looks reasonable.
