### ISSUE TITLE
Replacing the deprecated `request` dependency - gives a warning on `npm install`

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-admin-node#1269]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 11.3
  * Firebase SDK version: firebase-admin 9.8.0
  * Node.js version: 16.1
  * NPM version: 7.12

### [REQUIRED] Step 3: Describe the problem

`firebase-admin` uses `request` and `npm` gives a warning about it:

```
$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

jsdom (used in JEST) has already gone through a similar re-engineering.

- [Replace request with something better](https://github.com/jsdom/jsdom/issues/2792)
- [Replace request (as a direct dependency) with node-fetch](https://github.com/jsdom/jsdom/pull/3092)

They chose `node-fetch` after considering multiple options.

---

Related: `@firebase/rules-unit-testing` has a [similar issue](https://github.com/firebase/firebase-js-sdk/issues/3009) reported a year ago.

**Comment by hiranya911** [comment]
It's only a dev dependency (perhaps used in some of our tests?). It's not even typically installed alongside `firebase-admin`:

```
$ npm install firebase-admin
$ npm ls request
~/reqtest
└── (empty)
``` 

I think some other dependency in your project is bringing in `request`. Try the above `npm ls` command to see the dependency chain.

**Comment by akauppi** [comment]
I'm so sorry!  Got confused with the libraries - the problem is `firebase-tools`, not `firebase-admin`.

And the issue is already covered (since a year!) here: https://github.com/firebase/firebase-tools/issues/2215

Closing.
