### ISSUE TITLE
FCM message time to live value clarification needed 

### ISSUE THREAD

**Issue by calhu** [firebase/firebase-admin-node#1271]
I'm sending FCM messages  and trying to configure the android:  { ttl: value 

According to the documentation the ttl value should be string of the format 
"android":{
      "ttl":"4500s"
    },

However, the linting tool suggest that the value should be of type number. I'm using a number of 60 in my example bellow which is not working.  The ttl value of 60 is not causing the message to disappear after 60 seconds which is what I'm expecting. Please confirm that the value is in seconds.

https://firebase.google.com/docs/cloud-messaging/concept-options#ttl

I'm running this in a Firebase cloud function. It executes without error. I receive notifications on Android and IOS. 
There maybe an issue with my IOS ttl value that I'm calculation so lets stick to Android in this case.

 
  *  Node.js version: __v16.0.0___
  * NPM version: __7.11.1___
  * firebase --version 9.10.2

--
Kalevi

### [READ] Step 1: Are you in the right place?

  * hopefully

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _node 10, 256MB, timeout 60s ___
  * Firebase SDK version: _____
  * Firebase Product: _functions, admin ____ (auth, database, storage, etc)
 
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin'

const euFunctions = functions.region('europe-west1') 

export const roomUserHangingOut =
euFunctions.https.onCall(async (data, context) => {
  
      const COLLAPSE_KEY = data.channel_uid + "ROOM";

      const myDate = new Date();
      const currentTimeMS:number = myDate.getMilliseconds();
      const channelTTLSeconds:number = 60; //seconds
      const appleTTL = currentTimeMS + (channelTTLSeconds * 1000);

      await admin.messaging().send({
        topic: data.channel_uid,
        notification: {
          title: data.speaker_name + " is hanging out in",
          body: "Room: " + data.channel_name + myDate.toString()
          //clickAction: 'FLUTTER_NOTIFICATION_CLICK', clickaction is in android section
        },
        data: {
          'route': '/userRoomHangout', //UI routing
        },
        android: {
          priority:     'normal',
          ttl:          60, //86400, //24h
          collapseKey:  COLLAPSE_KEY,
          notification: {
            clickAction: 'FLUTTER_NOTIFICATION_CLICK'
          },
        },
        apns: { // Add APNS (Apple) config
          headers: {
            "apns-expiration":  appleTTL.toString(), //added
            "apns-collapse-id": COLLAPSE_KEY,
            "apns-topic":       "io.flutter.plugins.firebase.messaging", // bundle identifier, was  used in BG message
          },
        },
      })
       
      return true;
})

**Comment by calhu** [comment]
I'm hanging super tight!

**Comment by hiranya911** [comment]
> Time-to-live duration of the message in milliseconds.

https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig#optional-ttl

**Comment by calhu** [comment]
The question is why is TTL not working?  I tried 60000. I see the notification after 1 minute

**Comment by hiranya911** [comment]
How are you testing it? Are you keeping the device offline for a minute before checking to see if it receives the notification?

**Comment by calhu** [comment]
Hi, I have interpreted the incorrectly the ttl meaning. I didn't realise this only to prevent delivery. Thank you for you help! Please close this case!

Best regards,
Kalevi
