### ISSUE TITLE
The second factor "uid" must be a valid non-empty string

### ISSUE THREAD

**Issue by flyingluscas** [firebase/firebase-admin-node#1276]
### Describe your environment

  * Operating System version: Arch Linux
  * Firebase SDK version: 9.5.0
  * Firebase Product: Auth
  * Node.js version: 14.15
  * NPM version: 6.14.11

### Describe the problem

The `admin.auth().updateUser` function does not allow me to add a second factor to an existing user, always triggering the error `The second factor "uid" must be a valid non-empty string.`, the function expects a valid uid but [according to the docs it should not, if no uid is informed it should auto generate one](https://cloud.google.com/identity-platform/docs/admin/manage-mfa-users#updating_a_user). Can anyone help me understand if this is a bug in the lib or am I doing something wrong?

#### Steps to reproduce:

1. Create a user without any secondary factors.
2. Try to add a new secondary factor using the [`.updateUser`](https://cloud.google.com/identity-platform/docs/admin/manage-mfa-users#updating_a_user) function.

#### Relevant Code:

```js
admin.auth().updateUser('123456789', {
  phoneNumber: '+16505550003',
  emailVerified: true,
  multiFactor: {
    enrolledFactors: [
      {
        phoneNumber: '+16505550003',
        displayName: 'Bender Bending Rodríguez',
        factorId: 'phone',
      },
    ],
  },
})
```

**Comment by hiranya911** [comment]
Current implementation treats UID to be required for update operations:

https://github.com/firebase/firebase-admin-node/blob/e7155eacddd59cb449991476227c3a38681176cf/src/auth/auth-api-request.ts#L278

@bojeil-google is that a bug?

**Comment by bojeil-google** [comment]
I think it is a bug in our code. I tried to send the request directly to confirm the backend API does not require the `uid` and it seems to work without it. It will provision a new `uid` on its own. We should remove that check `uidRequired`. I am also double checking this is the intended behavior with some backend folks.

**Comment by bojeil-google** [comment]
The tests seem to be currently broken (only partially running). If you can help fix that, I am happy to review.

**Comment by silviokucz** [comment]
As of 1/31/2023 I am still experiencing this issue.
My environment:

    Operating System version: Ubuntu Linux
    Firebase SDK version:11.19.0
    Firebase Product: Auth
    Node.js version: v14.21.2
    NPM version: 6.14.17
    
My exact call:
admin.auth().updateUser('yBap141NgrR6o4cvaVOAEQVdaGCl', {
  multiFactor: {
    enrolledFactors: [
      {
        phoneNumber: '+4255555504',
        displayName: 'MFA',
        factorId: 'phone',
      },
    ],
  },
})
