### ISSUE TITLE
missing `kid` in `createCustomToken` token header

### ISSUE THREAD

**Issue by Bamieh** [firebase/firebase-admin-node#128]
### [REQUIRED] Step 2: Describe your environment

  * Library version: `"firebase-admin": "5.4.3"`
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

The `createCustomToken` function does not add `kid` to the header of the jwt token. This makes me unable to use the token in many applications (i have to sign in with the username and password using `firebase` rather than `firebase-admin`)a

**Comment by Bamieh** [comment]
@firebase-oss-bot hmmmmm 🤔

**Comment by bojeil-google** [comment]
How do you use a custom token to "sign in with the username and password using `firebase` rather than `firebase-admin`"?

**Comment by hiranya911** [comment]
@Bamieh The only meaningful thing you can do with a custom token is to pass it to one of the [`signInWithCustomToken()`](https://firebase.google.com/docs/auth/admin/create-custom-tokens#sign_in_using_custom_tokens_on_clients) methods provided by the client SDKs. This will send the token to a Firebase auth backend server, which does not care if the `kid` header exists. For this reason it is [not required](https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library).

How are you using custom tokens? What service/application is complaining about the `kid` header not being present?

**Comment by Bamieh** [comment]
Our backend uses `firebase-php` which calls the method `\JWT::decode` to verify firebase user tokens, this method (provided by firebase) checks for the `KID`.

My intent was to create a user via admin auth, then create a token for that uid, and send it to the backend to access the services.

I started using the admin auth in the first place because the web auth focus a limit of a 100 user creations per IP per day and i create more than that (I'm heavily automating e2e testing for our platform).

Currently i solved this issue by creating the user via admin auth, then sign in via the firebase-node as a web user to get the backend verifiable token. I didnt see anyway to adjust the token headers.

**Comment by hiranya911** [comment]
It sounds like you're doing the right thing now: using the custom token in a client SDK to sign in, and obtain an ID token. The ID token can be verified in the server side. 

Verifying custom tokens in user code is not a supported use case, as they are meant to be verified by the Firebase auth backend servers only.

**Comment by hiranya911** [comment]
It sounds like you're doing the right thing now: using the custom token in a client SDK to sign in, and obtain an ID token. The ID token can be verified in the server side. 

Verifying custom tokens in user code is not a supported use case, as they are meant to be verified by the Firebase auth backend servers only.

**Comment by Bamieh** [comment]
@hiranya911 okay, can you clarify what exactly you mean by "Firebase auth backend servers only"? Our backend uses firebase auth, doesnt that make it qualified for such token?

**Comment by bojeil-google** [comment]
The custom Auth token is only meant to be consumed by the Firebase Auth backend server. The public certificate for a project is not exposed as a result.
So the flow works as follows:
1. Mint custom token with your private key
2. send custom token to Firebase Auth backend via `signInWithCustomToken` API.
3. Auth backend verifies it with your allocated cert.
4. A Firebase Auth refresh token and ID token are sent back to the client.
5. You can verify the ID token using the public cert which is shared by all projects. Admin SDK provides an API for that.

What should be of interest to you is the final ID token which was obtained from the original custom token.

**Comment by peicodes** [comment]
`Verifying custom tokens in user code is not a supported use case, as they are meant to be verified by the Firebase auth backend servers only.`

According to your docs, verifying with a third party library is a supported use case. The `kid` is still missing from the headers though.

https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library

**Comment by hiranya911** [comment]
The doc link you're referring to is about verifying "ID tokens", and not "custom tokens". That's a different use case.

**Comment by hiranya911** [comment]
Like @bojeil-google has mentioned in a previous comment, those public keys are not exposed by Firebase. So there's really no way to verify a custom token in your own code. You can find some alternative solutions at https://stackoverflow.com/questions/61767695/how-to-verify-a-custom-token

**Comment by peicodes** [comment]
We are able to retrieve the public keys for signed custom tokens here: `https://www.googleapis.com/robot/v1/metadata/x509/<PROJECT_ID>@appspot.gserviceaccount.com`. We just have no idea which one is being used by Firebase to sign it. 

Should we just totally ignore the tokens listed in that URL, and assume it's for Firebase internal use only?

**Comment by hiranya911** [comment]
> Do you know of any way for a Function to know the key ID being used when calling createCustomToken?

Not that I know of. But you might be able to request that information from IAM: https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob
