### ISSUE TITLE
[FR] Support publishing messages to a PubSub topic

### ISSUE THREAD

**Issue by elvisun** [firebase/firebase-admin-node#1286]
**Is your feature request related to a problem? Please describe.**
There's no way to publish messages to a pubsub topic within the firebase admin SDK. The whole pubsub journey feels very incomplete.

**Describe the solution you'd like**
Ideally we have something like this that can publish a message to a pubsub topic.
```
admin.pubsub.topic('my_topic').publish("hello world");
```

**Describe alternatives you've considered**
Could use the GCP pubsub sdk but get this error when I tried: `Getting metadata from plugin failed with error: invalid_grant`. Seems like we'd need to set the default project with cloud's sdk from [this thread](https://github.com/firebase/firebase-functions/issues/121). However, this won't work with `firebase use` for multiple environments.

**Comment by hiranya911** [comment]
Cloud PubSub is not a Firebase product. So that's not something  we wish to expose. You should use https://www.npmjs.com/package/@google-cloud/pubsub to access PubSub (and if that's not working as expected please report at the respective GitHub repo for Cloud PubSub).
