### ISSUE TITLE
Defining a new method on Object causes RTDB to freeze

### ISSUE THREAD

**Issue by inlined** [firebase/firebase-admin-node#1298]
Moving firebase/firebase-functions/issues/819 from that repo to this since I was able to reproduce it without the Functions SDK. Adding a new method to Object somehow causes `ref.once` to hang:

```
const admin = require('firebase-admin');
admin.initializeApp({...});

Object.prototype.getKeyByValue = function(value) { return Object.keys(this).find(key => this[key] === value) }

admin.database().ref('yy/zz').once('value').then(() => console.log('done'));
```

**Comment by inlined** [comment]
FWIW, it doesn't matter what the new function is. I defined `Object.prototype.foo = () => "bar"` and that caused a freeze too.

**Comment by schmidt-sebastian** [comment]
This is a problem in our dependencies. We proposed a fix but it has been rejected: https://github.com/faye/websocket-driver-node/pull/41
