### ISSUE TITLE
_stream_writable unable to resolve modules 

### ISSUE THREAD

**Issue by Kiozak** [firebase/firebase-admin-node#130]
Describe your environment

  * Operating System version: ubuntu 17.10
  * Firebase SDK version: lastest
  * Nodejs version : 7.9.0
  * Npm version : 5.5.2
  * Library version: lastest
  * Firebase Product: database  (auth, database, storage, etc)

 Describe the problem
  Well this is my problem , i tried to re-install the module more than 10 time , but the error still pop-up
![error](https://user-images.githubusercontent.com/18468446/32545751-a0b1c534-c474-11e7-93c0-8a70e676fa7d.png)

i really don't know that to do after all this ,

**Comment by hiranya911** [comment]
It looks you're trying to use `firebase-admin` in a React Native mobile app. `firebase-admin` is not supported in client-side frameworks like React native. It is for server-side use only.

**Comment by Kiozak** [comment]
oh i see thank you a lot
