### ISSUE TITLE
[Storage] Download Tokens does not support lowercase object metadata

### ISSUE THREAD

**Issue by frankyn** [firebase/firebase-admin-node#1306]
Forwarding an issue from nodejs-storage: https://github.com/googleapis/nodejs-storage/issues/1341

_from: @leoalopes_:
Basically, what I'm trying to do is to have my server send a signed URL to the client and have the client upload the file and generate a Firebase download URL that gives public access to the upload file. The problem is that I cant send my download token as metadata to uploaded file, because it has to be camel case. I read somewhere in the docs that I could send the metadata as a JSON file too, but I couldn't make it work (it didn't gave me an error, just didn't set the metadata).

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: v12.16.3
  - npm version: 6.14.4
  - `@google-cloud/storage` version: 5.5.0

#### Steps to reproduce

  1. Generate a signed URL with the code below
```
const [url] = await storage.bucket(bucket_name).file(file).getSignedUrl({
    version: 'v4',
    action: 'resumable',
    expires: Date.now() + 24 * 60 * 60 * 1000,
    extensionHeaders: {
        'x-goog-meta-firebaseStorageDownloadTokens': 'a883673-4957-4120-8f52-f383ddddbfb1',
    }
})
```
  2. Upload a file using this signed URL and sending the `x-goog-meta-firebaseStorageDownloadTokens`. My code looks something like this:
```
const chunkSize = 1024 * 1024

async uploadFile(file) {
    let sessionUri = await axios.post(signedUrl, null, {
        headers: {
            'x-goog-resumable': 'start',
            'x-goog-meta-firebaseStorageDownloadTokens': 'a883673-4957-4120-8f52-f383ddddbfb1',
            'content-type': 'image/jpeg'
        }
    }).then(response => {
        return response.headers.location
    })

    const slice = file.mozSlice ? file.mozSlice :
        file.webkitSlice ? file.webkitSlice :
        file.slice ? file.slice : () => {}

    let chunkStart = 0
    while(chunkStart < file.size) {
        let chunkEnd = chunkStart + chunkSize
        if (chunkEnd > file.size) {
            chunkEnd = file.size
        }

        let currentChunk = slice.bind(file)(chunkStart, chunkEnd)
        console.log(chunkStart, chunkEnd, currentChunk)

        await new Promise((resolve, reject) => {
            axios.put(sessionUri, currentChunk, {
                headers: {
                    'Content-Type': file.type,
                    'Content-Lenght': chunkSize,
                    'Content-Range': `bytes ${chunkStart}-${chunkEnd - 1}/${file.size}`
                }
            }).then(response => {
                console.log('[RESPONSE]', response)
                resolve()
            }).catch(error => {
                // RESPONSE WITH 308 ARE TREATED LIKE ERRORS BY AXIOS
                console.log('[ERROR]', error)
                resolve()
            })
        })

        chunkStart = chunkEnd
    }

    console.log('FILE UPLOADED')
}
```

So, the problem is that, the metadata `firebaseStorageDownloadTokens`, sent on the headers, become all lower case, which I understand is the way it is supposed to work, but that makes me unable to upload a file and retrieve a firebase download URL, because the file doesn't contain any firebase download token.

This is how it is:
![image](https://user-images.githubusercontent.com/33356180/99461493-b0f51780-2910-11eb-9bbb-5fd03d8e1f5a.png)

And this is how I need it:
![image](https://user-images.githubusercontent.com/33356180/99462429-6f656c00-2912-11eb-80bd-0e57cdb91d9a.png)

For firebase to read that as an access token it needs to be camel case and I don't know how I could accomplish that without asking for my server to change the metadata after the client uploads a file using the generated signed URL.

**Comment by schmidt-sebastian** [comment]
I don't know much about the Storage SDK that is used by Firebase Admin. Assigning to the Admin team for triage.

**Comment by avolkovi** [comment]
Good find, per https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#settable-fields;-field-values the keys should be case insensitive, let me file an internal bug

**Comment by tonyjhuang** [comment]
Thanks for raising this. Just pushed a fix to our server code that should start rolling out next week.

**Comment by hiranya911** [comment]
Closing this based on the last comment. Please comment here if the issue still exists.
