### ISSUE TITLE
Is Deno support on the horizon?

### ISSUE THREAD

**Issue by dadepo** [firebase/firebase-admin-node#1307]
Hi there 👋

I would love to use the SDK in a Deno project and it looks like all the conventional methods of using npm packages within Deno does not work.

It would be nice to have deno support support for the SDK, with that there won't be a need to try to use the npm package from Deno.

**Comment by hiranya911** [comment]
There are no specific plans for Deno support at this point (both in Firebase, and within the Google Cloud ecosystem as far as I can tell). But I'd recommend you to file this as a feature request at https://firebase.google.com/support for more visibility within the team.

**Comment by akauppi** [comment]
@hiranya911 Narrowing the Deno/Bun? compatibility gap would likely have a welcome side effect of aligning `firebase-admin` with where Node itself is going. One example is the `fetch` API. Node.js 18 has it built-in, and the same implementation is available for Node.js >= 16.5 (if I recall right) with the `undici` library.

So the limiting factor is Firebase's willingness (customer pressure) to keep supporting Node.js 14.
