### ISSUE TITLE
[FR]ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'node_modules/firebase-admin/lib'

### ISSUE THREAD

**Issue by menarayanzshrestha** [firebase/firebase-admin-node#1318]

**Comment by hiranya911** [comment]
`fs` is a core Node.js module. If your runtime doesn't provide it, that's usually an indication that you're not running in a Node..js environment (probably web or some other frontend framework).

https://nodejs.org/api/fs.html
