### ISSUE TITLE
[FR] Admin 'getDownloadURL' for Storage

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-admin-node#1352]
**Is your feature request related to a problem? Please describe.**

Download URLs are one of the most convenient ways to display content from Cloud Storage for Firebase, but right now they can only be created on the client. 

There has been extensive discussion of this on the Cloud side, and their basic stance is "we don't like the Firebase URLs and we don't think you should be able to make them": https://github.com/googleapis/nodejs-storage/issues/697

As a result the best documentation on how to make these URLs on the server is this massive StackOverflow answer:
https://stackoverflow.com/questions/42956250/get-download-url-from-file-uploaded-with-cloud-functions-for-firebase/56010225#56010225

**Describe the solution you'd like**

A simple `getDownloadURL()` method in the Node.js Admin SDK

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by spotvin42** [comment]
I am also struggling with this and the community as well, we can see it on stackoverflow...

I've created my own way to get one following the described method in your shared link.

I think it's not right as one commenter from Google said, but I don't see another way?

https://stackoverflow.com/questions/70563169/resizing-images-already-on-google-storage-locally-through-sharpjs-and-keeping-u

Thank you in advance for supporting this issue!

**Comment by ArnabXD** [comment]
I found an interesting article regarding this 

https://www.sentinelstand.com/article/guide-to-firebase-storage-download-urls-tokens

**Comment by samatcolumn** [comment]
Well I've got a new job but still running into this same issue, we'd love a simple way to generate download URLs for objects from our backend Node.js server. Right now we can only do this on our frontend.

I do understand there are many workarounds but we'd like the solution to be the same on frontend and backend, not have different types of URLs depending on where they were generated.

**Comment by willbattel** [comment]
Yeah it's a bit ridiculous that we can't directly access the tokened URL from the Admin SDK. We want the token feature so we have the ability to revoke, as opposed to just making everything public. Ideally we would keep the URL in the associated Firestore document that we're already fetching on the client so we don't need to make extra round trip requests that needlessly slows down the application. I'm not sure why there has been so much pushback from Google on this- it feels like a major handicap to their Storage product that only the client SDKs can access the URL.

**Comment by atif7865** [comment]
@lahirumaramba is this being looked at internally? Any updates?

**Comment by dellumdeus** [comment]
Any updates on this?

**Comment by willbattel** [comment]
Looks like they are open to it in principle but are changing the mechanism internally this year so I guess we'll just have to wait and see what that means...

See: https://github.com/firebase/firebase-admin-node/pull/2036#pullrequestreview-1246148110

**Comment by tonyjhuang** [comment]
Hi, Firebaser here. Sorry for the radio silence and thanks for the continued interest in this FR. @willbattel is correct in that we are looking to offer alternatives to download urls in the future as there are some interesting security implications of this feature that makes it unideal in security-critical applications.

That being said, while we can't provide an estimated timeline on when it will become available, @maneesht is actively working on adding `getDownloadUrl` functionality to the admin SDK to bridge the gap in the meantime.

**Comment by dellumdeus** [comment]
Would be amazing if this [PR#2036](https://github.com/firebase/firebase-admin-node/pull/2036#pullrequestreview-1246148110) gets merged soon👌

**Comment by samatcolumn** [comment]
Thank you @maneesht!!! Been wanting this feature for two years.

**Comment by Whimfoome** [comment]
> Is this released? If so how do we use it? The documentation don't mention this.
```js
import admin from 'firebase-admin';
import { getDownloadURL } from 'firebase-admin/storage';

const bucket = admin.storage().bucket('your-storage-bucket-url.appspot.com');
const file = bucket.file('path');
const downloadUrl = await getDownloadURL(file);

console.log(downloadUrl);
```

**Comment by tonyjhuang** [comment]
Thanks for the code sample @Whimfoome, our official docs have also been updated to include an example: https://firebase.google.com/docs/storage/admin/start#shareable_urls

**Comment by davit-b** [comment]
@samasthwafer that's an API error due to the object not being found. Make sure your platform (emulator or cloud) and the file actually exist.

**Comment by KishorJena** [comment]
> > Is this released? If so how do we use it? The documentation don't mention this.
> 
> ```js
> import admin from 'firebase-admin';
> import { getDownloadURL } from 'firebase-admin/storage';
> 
> const bucket = admin.storage().bucket('your-storage-bucket-url.appspot.com');
> const file = bucket.file('path');
> const downloadUrl = await getDownloadURL(file);
> 
> console.log(downloadUrl);
> ```

Thanks for snippet.

**Comment by gregfenton** [comment]
> [@samasthwafer](https://github.com/samasthwafer) that's an API error due to the object not being found. Make sure your platform (emulator or cloud) and the file actually exist.

That error message is vague.  Would be nice if it said something along the lines of "Firebase Storage Object not found" or similar.

IMO, 
> ApiError: Not Found

is pretty ambiguous.

In my case, `bucket.file('/foo/bar.png')` got the above error.  But I should have called `bucket.file('foo/bar.png')` to avoid the error.  🤨
