### ISSUE TITLE
[firebase_admin] Unable to set object metadata in Firebase Storage

### ISSUE THREAD

**Issue by bigbang489** [firebase/firebase-admin-node#1358]
My Code:

```
const admin = await import("firebase-admin");
const bucket = admin.storage().bucket();
const file = bucket.file(path);
await file.save(content, 
    {'gzip': gzip, 'contentType':'application/json',
      'metadata': {
        'Cache-Control': 'no-transform'}})
```
Expected result: Object Metadata 'Cache-Control' will be set to 'no-transform' 
Actual result: Object Metadata 'Cache-Control' is empty

**Comment by lahirumaramba** [comment]
I think the key should be `cacheControl` https://github.com/googleapis/nodejs-storage/blob/9f1790913ddcdc303482a4355c5d0c6bf5404d4d/samples/fileSetMetadata.js#L45

The following code sets the cacheControl correctly. Hope this helps!

```
file.save(contents, {
    gzip: true,
    contentType: 'application/json',
    metadata: {
      cacheControl: 'no-transform',
    },
  })
```
