### ISSUE TITLE
[FR] Making `db.collection` method generic to provide the referenced collection's document structure

### ISSUE THREAD

**Issue by Devorein** [firebase/firebase-admin-node#1366]
**Is your feature request related to a problem? Please describe.**
I just started with firebase so this might have already been resolved somewhere. Sorry if it has been. I've searched existing issues but haven't found any similar to this.

My issue revolves around the following code snippet.

```ts
const tasksCollection = db.collection('tasks');
```

When using the following code in typescript, there is no way to provide a structure of the document that the collection references. If I take a look at the `firestore.d.ts` file this is the type definition for the `collection` method

```ts
collection(collectionPath: string): CollectionReference<DocumentData>
```
Where `DocumentData` could be the structure of the underlying document of the collection.

**Describe the solution you'd like**
I think a mechanism to provide the underlying structure of the collection documents would be a solution.

For example
```ts
const tasksCollection = db.collection<ITask>('tasks');
// Would be the same as
const tasksCollection = db.collection('tasks') as FirebaseFirestore.CollectionReference<ITask>;
```

**Describe alternatives you've considered**
Right now the only way to get around it is by using the following code snippet, which is not a big issue, but using a generic might make the dx a bit better.

```ts
const tasksCollection = db.collection('tasks') as FirebaseFirestore.CollectionReference<ITask>;
```

**Additional context**
None.

**Comment by hiranya911** [comment]
Please report at https://github.com/googleapis/nodejs-firestore
