### ISSUE TITLE
admin.intializeApp returns Raw server response

### ISSUE THREAD

**Issue by peterwiebe** [firebase/firebase-admin-node#137]
* Operating System version: Nodejs (Alpine based) docker container, node:8.7.0-alpine
  * Firebase SDK version: 5.4.3
  * Library version: 0.8.2
  * Firebase Product: Auth

I am trying to initialize the connection to my Firebase application using admin.intializeApp with the credentials that were provided when downloading the private key in the service accounts tab of the Firebase console. The result of calling that function is `Error: An internal error has occurred. Raw server response: "{}"`.

The application that utilizes the Firebase SDK is deployed to a Kubernetes cluster inside of GKE. It is behind an ClusterIP Service object which is reachable via an Ingress Object for external requests.

Our implementation of the function is as follows:

```
admin.initializeApp({
  credential: admin.credential.cert({
    projectId: FIREBASE_PROJECT_ID,
    clientEmail: FIREBASE_CLIENT_EMAIL,
    privateKey: FIREBASE_PRIVATE_KEY
  })
});
```
Where the constants are set as environment variables.

**Comment by hiranya911** [comment]
`admin.initializeApp()` is a local operation, and doesn't make any network calls. You will have to debug your app, and see what the underlying error is. It is likely to do with your use of environment variables. Can you show the code where you instantiate those constants?

**Comment by peterwiebe** [comment]
@hiranya911 figured it out. I put quotes around the private key for the yaml file that shouldn't have been there.
