### ISSUE TITLE
[FR] Support exporting utils/error.ts types

### ISSUE THREAD

**Issue by kenchan0130** [firebase/firebase-admin-node#1373]
**Is your feature request related to a problem? Please describe.**

If the type information for errors such as `FirebaseAuthError` is not published as an npm package and is written in TypeScript, the user of the library must prepare the type information for those errors by themselves.

As a concrete use case, when an error occurs, we may want to use `instanceof` to identify the Error because the argument of the catch clause is any or unknown value.

**Describe the solution you'd like**
I'd like to see the type information in `lib/utiils/error.d.ts` included for the npm package.

**Describe alternatives you've considered**

Create `d.ts` by myself.

**Additional context**
None

**Comment by hiranya911** [comment]
Deduping with #579 which is expected to address all the error handling improvements.
