### ISSUE TITLE
[QUESTION] How to exclude an optional dependency?

### ISSUE THREAD

**Issue by diavrank** [firebase/firebase-admin-node#1374]
Hello, I have a meteor app (nodejs) which only uses **Cloud Storage**. When I do deployments (I use Docker), the build takes longer than normal because it compiles something related to **[gRPC](https://github.com/disney/meteor-base/issues/55)** which is a nested dependency from **google/firestore** and this one is an optional dependency from **firebase-admin**. 

_yarn.lock_
```yaml
firebase-admin@^9.9.0:
  version "9.9.0"
  resolved "https://registry.yarnpkg.com/firebase-admin/-/firebase-admin-9.9.0.tgz#40442704b5ac0fddfdcdf4255601f8acb1e6fab3"
  integrity sha512-04HT7JAAqcJYty95qf15IBD9CXf+vr7S8zNU6Zt1ayC1J05DLaCsUd19/sCNAjZ614KHexAYUtyLgZoJwu2wOQ==
  dependencies:
    "@firebase/database" "^0.10.0"
    "@firebase/database-types" "^0.7.2"
    "@types/node" ">=12.12.47"
    dicer "^0.3.0"
    jsonwebtoken "^8.5.1"
    jwks-rsa "^2.0.2"
    node-forge "^0.10.0"
  optionalDependencies:
    "@google-cloud/firestore" "^4.5.0"
    "@google-cloud/storage" "^5.3.0"
```

So, I wonder if it currently exists a way to exclude **Firestore** from firebase-admin?

**Comment by hiranya911** [comment]
No such option is available in the SDK. But NPM provides certain flags that you can use for this sort of things. See https://stackoverflow.com/questions/53969343/how-i-can-skip-installing-optional-dependencies-by-npm-ci
