### ISSUE TITLE
[FR] Allow credential file type "external_account" when calling `admin.credential.applicationDefault()`

### ISSUE THREAD

**Issue by thomasmburke** [firebase/firebase-admin-node#1377]
## **Is your feature request related to a problem? Please describe.**

Developers would like the ability to initialize a Firebase app instance with a credential file type "external_account". An example of when credential file of type "external_account" is used is when following the instructions listed in the GCP public docs for using [AWS Identify Federated Credentials](https://cloud.google.com/iam/docs/access-resources-aws). This credential file type is supported by other Google APIs (e.g. @google-cloud/storage, @google-cloud/firestore, etc...) and is also supported by the Firebase Admin SDK in other languages (e.g. [Java](https://github.com/firebase/firebase-admin-java))

## **Describe the solution you'd like**

Allow the initialization of a Firebase app instance using credential file type "external_account". This will likely require an update to the [`credentialFromFile` function](https://github.com/firebase/firebase-admin-node/blob/d961c3f705a8259762a796ac4f4d6a6dd0992eb1/src/credential/credential-internal.ts#L427-L448)

## **Describe alternatives you've considered**

Developers are currently limited to:
- Leveraging the Firebase Java Admin SDK instead
- Using Secrets Manager/environment variables to store a service account key outside of code
- Calling a corresponding RESTful endpoint from within node.js via something like `http.request`

## **Additional context**

When a developer has configured GOOGLE_APPLICATION_CREDENTIALS to point to a credential file type of "external_account" (e.g. a AWS Identity Federation Credentials Config file) the below are the differences between the implementations for the Firebase Java Admin SDK and the Firebase Node.js Admin SDK:

**Node.js Details:**
 Developer initializes Firebase app instance with code similar to the below:
```
const fbApp = admin.initializeApp({
        credential: admin.credential.applicationDefault(),
        projectId: 'GCP_PROJECT_ID',
        databaseURL: 'https://GCP_PROJECT_ID.firebaseio.com'
    });
```
Which in turn calls the [`credentialFromFile` function](https://github.com/firebase/firebase-admin-node/blob/d961c3f705a8259762a796ac4f4d6a6dd0992eb1/src/credential/credential-internal.ts#L427-L448) and returns the following error: 'Invalid contents in the credentials file'

**Java Details:**
Developer initializes Firebase app instance with code similar to the below:
```
        GoogleCredentials credentials = GoogleCredentials.getApplicationDefault();

        FirebaseOptions options = FirebaseOptions.builder()
                .setCredentials(credentials)
                .setProjectId(GCP_PROJECT_ID)
                .setDatabaseUrl(FIREBASE_DB_URL)
                .build();

        FirebaseApp app = FirebaseApp.initializeApp(options);
```
Which in turn calls [this function](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L153-L184) that has support for credential file type of "external_account"

**Comment by hiranya911** [comment]
Thanks for reporting this. We can try to prioritize this for in the coming months. You can also help speed things up by sending a PR if you have the time.

**Comment by hiranya911** [comment]
Had a quick look at the external_account (federated authorization) support in GCP, and how libraries like https://github.com/googleapis/google-auth-library-nodejs have implemented it. Turns out it's actually quite a bit of code. Personally, I don't think we should duplicate this feature in the Admin Node.js SDK. Rather we should migrate all our credentials implementation to use `google-auth-library-nodejs`  (we have already done similar migrations in other languages, which is why you can already use external_account support in Java Admin SDK).

I think doing this migration is going to be somewhat tricky. A rough plan would look something like:

1. Update existing credentials to use `google-auth-library-nodejs`.
2. Add a new `admin.credential.externalAccount()` API.
3. Remove the token management logic currently in `FirebaseApp`.
4. Tie RTDB code to the tokens events fired by `google-auth-library-nodejs`.

**Comment by enchorb** [comment]
Is there any status update on this? Would be great not to store a service account for dev purposes and simply use the credentials generated from `gcloud auth application-default login --impersonate-service-account`

**Comment by ElvirK81** [comment]
> lol

**Comment by andrewmclagan** [comment]
Any movement on this issue? Currently not possible to use https://github.com/google-github-actions/auth as this is blocking it

**Comment by Burekasim** [comment]
I spend hours trying to figure out why it's not working until I encounter this issue, 
I am very disappointed that this is not even documented, there is a service (workload identity federation) that is supposed to be the best practice and it is not supported by other GCP services :/

I give up, it's impossible to deal with Google's libraries :/

**Comment by lhermann** [comment]
I had the same experience as @Burekasim. I am trying to follow best practice and then find out that the lack of support is not documented.

Thank you @thomasmburke for this excellent and detailed issue.

Please Google Team, treat this issue as a priority so Firebase can be used with Github Actions in the recommended way.

**Comment by erik-induro** [comment]
This just ate a few hours of my life. The documentation is misleading when it says:
> create_credentials_file: (Optional) If true, the action will securely generate a credentials file which can be used for authentication via gcloud and Google Cloud SDKs in other steps in the workflow. The default is true.
It should indicate that it doesn't work with Firestore.

**Comment by lahirumaramba** [comment]
I understand your frustration. Firebase Admin Node.js SDK uses a custom credentials implementation and does not currently support many features that are already supported in `google-auth-library-nodejs` including external accounts.

Migrating to https://github.com/googleapis/google-auth-library-nodejs is not a simple task, but we have started the process. Stay tuned! In the meantime, we will see what we can do to improve the docs. Thank you for your patience!

**Comment by Mistic92** [comment]
How Workload Identity Federation can be not supported by GCP product. What is the roadmap to enable use of WIF?

**Comment by enchorb** [comment]
+1, how can an important feature like this be delayed/ not implemented for so long...

**Comment by jordanebelanger** [comment]
+1 seems like I was an other one of the chosen one selected for losing a couple hours on this while setuping my ci/cd

**Comment by gkawin** [comment]
Ok, I will stay tuned on this issue.

**Comment by erlichmen** [comment]
urgently need to emphasize the severity of this particular issue. It presents itself when utilizing tools like Terraform, Pulumi, or when attempting to run local Firebase CLIs under application default credentials. Currently, the only feasible workaround is to employ a service account (SA) key.

This SA key has to be duplicated among the engineering team, and anyone who needs to operate one of the CLIs or any affected tool. Consequently, this poses a significant challenge for the CISO, necessitating the implementation of stringent processes - something that wouldn't be necessary if WIF was supported.

Furthermore, people are wasting innumerable hours attempting to decipher an issue that fundamentally stems from AdminSDK's neglect in using the most updated Google auth packages. There are numerous perplexing forum responses to odd errors like "missing quota project" or SERVICE_DISABLED (I mention these to potentially guide others in the right direction).

In spite of the complexity tied to integrating auth-library-nodejs, a span of two years ought to have been ample time. While I comprehend that @hiranya911 might no longer be a part of the team, this issue must be promptly assigned to a new lead.

**Comment by dylanenabled** [comment]
I wrote a script that works around this issue for our deployment pipeline by generating an expiring service account key before it runs the node scripts.

**Comment by lox** [comment]
Folks, any updates on this? This is also blocking the use of service impersonation (e.g. https://github.com/firebase/firebase-admin-node/issues/2169).

**Comment by k2wanko** [comment]
This is an important topic for me.
I would like to be provided with a solution that does not require this [workaround](https://gist.github.com/k2wanko/289f5cf231ca80da099c7414dceb465d).

**Comment by theunlitshadow** [comment]
We are also awaiting an update on this issue. It's not apparent if this issue is being prioritized or even worked on.

**Comment by lox** [comment]
One could say that about almost all Firebase development work from what I can tell @theunlitshadow.

**Comment by lahirumaramba** [comment]
Hey folks, thanks again for your patience! We are actively working on this feature! Stay tuned for updates.

**Comment by josekasna** [comment]
We are also facing the same issue

**Comment by breathe** [comment]
Also ran into this issue ...  Strugglefest!

In my case I'm deploying a nextjs firebase webapp which needs to use the firebase-admin sdk at build time within ci ...  We only needed/wanted to use external account auth when running in ci ...  I ended up modifying one of the prior workarounds to get firebase-admin sdk auth to happen against external account when in ci and otherwise follow a normal path ...

Solution snippets for anyone else to save some time ...

https://gist.github.com/breathe/5b73c82f3ef3564b8b8f0641bf3e0a11

**Comment by lox** [comment]
I have a more generic workaround that I am using for service account impersonation, should work for external_account without needing to import the internal credential classes (which is hard with ESModules). 

https://gist.github.com/lox/8bff5607c3e713c92a03a631796ab3f3

**Comment by rapuckett** [comment]
Any... progress?

**Comment by mitchkoby** [comment]
Also awaiting an update on this.

**Comment by hdpz** [comment]
Would be great to see some progress on this issue :pray:

**Comment by BenJackGill** [comment]
In case anyone is using Firebase resources in Terraform with Github Actions [google-github-actions/auth](https://github.com/google-github-actions/auth) then you will also get strange unknown authentication errors because of this bug.

You have to use the Service Account JSON method as described in the docs instead of the Workload Identity Federation methods and that will avoid the strange errors.

To be fair the docs do warn about this error when working with Firebase Admin SDK but I didn't realise that also means Terraform resources will fail, which I assume is because the Terraform resources are interacting with the Firebase Admin SDK.

**Comment by Burekasim** [comment]
In another 20 or so years, in some documentary that will review why Google collapsed. They will present this GitHub Issue, to demonstrate Google's behavior towards paying users who just want to be treated.

In the meantime, they only have 10 more years left until this issue celebrates Bar Mitzvah.

**Comment by lebenitza** [comment]
> Hey folks, thanks again for your patience! We are actively working on this feature! Stay tuned for updates.

Can we get an update on this? Maybe a separate issues at least with required steps that this change might need so at least we have an idea where to start, if one would want to implement this themselves.

A good documented workaround would also be nice in the meantime.

**Comment by lahirumaramba** [comment]
Hey folks, thank you again for your patience on this!

We have made progress on the credentials migration work and we have a custom build to share with you for testing purposes.

If you are interested in trying out the custom build and give us some feedback, please find the steps below!

Download the custom build from https://drive.google.com/file/d/1gd5M21TDx3rVrRLgxVEJdfYAkPiNTBHd/view?usp=drive_link

You can use `npm install` to install the custom module

```
npm install path/to/firebase-admin-12.0.0.tgz
```

Or upload the custom build along with your test code and add the following in the package.json

```
  "dependencies": {
    "firebase-admin": "file:firebase-admin-12.0.0.tgz"
  }
```

**NOTE: Only use this custom build for testing purposes and do not use it in production.**

**Comment by jars** [comment]
> We have made progress on the credentials migration work and we have a custom build to share with you for testing purposes.

It works for me, thanks for the patch and look forward to the release. :tada:

**Comment by andrewmbenton** [comment]
Hoping to see this resolved soon. Is there anything blocking merge and release for https://github.com/firebase/firebase-admin-node/pull/2466?

**Comment by balloman** [comment]
Is there anything blocking #2466 , it hasn't had any activity for almost two months now?

**Comment by mitchkoby** [comment]
Also hoping for the release soon. Please provide an update.

**Comment by 7Hazard** [comment]
Why is this still an issue? This should be highly prioritized. Currently blocking us from deploying to Google Cloud through GitHub Actions.

**Comment by JFGHT** [comment]
> I urgently need to emphasize the severity of this particular issue. It presents itself when utilizing tools like Terraform, Pulumi, or when attempting to run local Firebase CLIs under application default credentials. Currently, the only feasible workaround is to employ a service account (SA) key.
> 
> This SA key has to be duplicated among the engineering team, and anyone who needs to operate one of the CLIs or any affected tool. Consequently, this poses a significant challenge for the CISO, necessitating the implementation of stringent processes - something that wouldn't be necessary if WIF was supported.
> 
> Furthermore, people are wasting innumerable hours attempting to decipher an issue that fundamentally stems from AdminSDK's neglect in using the most updated Google auth packages. There are numerous perplexing forum responses to odd errors like "missing quota project" or SERVICE_DISABLED (I mention these to potentially guide others in the right direction).
> 
> In spite of the complexity tied to integrating auth-library-nodejs, a span of two years ought to have been ample time. While I comprehend that @hiranya911 might no longer be a part of the team, this issue must be promptly assigned to a new lead.

It's impacting in our whole DX.

**Comment by KemingHe** [comment]
Hello, I'm pinging both here and #2466, @lahirumaramba , really hoping for this issue to resolve as soon as the team can. Much appreciated!!

**Comment by jordanebelanger** [comment]
Is Firebase dead?

**Comment by coolbho3k** [comment]
This is a joke lol

**Comment by sanlanka** [comment]
Could the priority on this be increased? This is such a blocker for firebase auth.

**Comment by exetico** [comment]
@lahirumaramba It looks like the preview build did work for some users. Could you please let us know, what the estimated timeline are, at this point?

I get why people are starting bumping this issue with spam-like comments as this point, now that no one at Google had this implemented, for more than 3 years.

**Comment by lahirumaramba** [comment]
Hey folks, thanks for your patience on this. This is now fixed in the latest major version `v13`. If you run into any issues, please let us know by opening a new issue.

**Comment by exetico** [comment]
What's GREAT NEWS! Thank you for the effort on this.

**Comment by sam-teleprompter-apps** [comment]
I realise this is bumping a possibly fixed issue, but I'm still having troubles using WIF, where as using a credentials files with google auth used to work. The auth step passes, but when attempting to deploy functions, I get:

`Error: Failed to authenticate, have you run firebase login?`

Here is the workflow I'm using:

```
name: Deploy to Firebase Functions via github action
"on":
  push:
    branches:
      - sam/gha-testing
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - name: Download deps
        working-directory: functions
        run: |
            npm install
            npm install -g firebase-tools

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '{redcated}'
          access_token_scopes: '{redcated}'
          workload_identity_provider: '{redacted}'
          service_account: '{redcated}'
          create_credentials_file: true
        
      - run: |
          echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

      - name: Deploy
        run: npx firebase-tools deploy --only functions:functionsname
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
```

And the versions of the various Firebase products we're using:

```
    "firebase-admin": "^13.0.2",
    "firebase-tools": "13.18.0",
    "firebase-functions": "^6.3.1",
```

Just to reiterate, this was worked find when supplying a credentials file to the Google Auth step.

**Comment by lahirumaramba** [comment]
Hi @sam-teleprompter-apps cloud please create a new issue for this? Thanks!
