### ISSUE TITLE
Type names not found

### ISSUE THREAD

**Issue by McStuffins** [firebase/firebase-admin-node#138]
* Operating System version: Windows 10: 1709
  * Library version: 5.5.0
  * Firebase Product: Firestore

`npm install firebase-admin`

try to use the sdk

have these errors show up: 
![errors](https://user-images.githubusercontent.com/23535075/32974120-d46a3cb0-cbc9-11e7-8d33-c6fa36cfbb33.PNG)

**Comment by hiranya911** [comment]
This should be fixed in 5.5.1. We no longer use the typings provided by `@firebase/database`.
