### ISSUE TITLE
Got an email on publicly accessible web api key which is supposed to be public.

### ISSUE THREAD

**Issue by dreamerchandra** [firebase/firebase-admin-node#1380]
### Environment

  * Firebase SDK version: admin sdk(^9.2.0)
  * Firebase Product: firebase admin
  * Node.js version: 12+

### Problem
I got an email saying a web API key is publicly accessible in my Github repo. I know for a fact that it's totally fine to expose the web API key in fact it should be present in client-side code to identify the firebase project. 

But why am I getting email saying my API key is compromised please change it?
![image](https://user-images.githubusercontent.com/17010408/125922177-066ae516-6b28-4431-a0ac-9ddc862be91e.png)

#### Steps to reproduce:
- Admin SDK with API key
- Push to Github on a public repo

Please note I haven't exposed the service account.

**Comment by hiranya911** [comment]
You should probably file a support request, since there's nothing we can do in this repo about this issue. However, the Admin SDK does not accept API keys. So perhaps it's not even necessary to include in your code?

**Comment by dreamerchandra** [comment]
Thanks
