### ISSUE TITLE
FCM not working in Prod (working fine in localhost)

### ISSUE THREAD

**Issue by jaysu77** [firebase/firebase-admin-node#1381]
import * as admin from 'firebase-admin';
admin.initializeApp({
  credential: admin.credential.cert({
    projectId: '**********'',
    clientEmail: '**********'',
    privateKey:'**********''
      }),
  databaseURL: '**********',
});

export const sendNotificationAll = async (
  messageTitle?: string,
  messageBody?: string,
  topic?: string,
  type?: string,
) => {
  const message = {
    notification: {
      title: messageTitle,
      body: messageBody,
    },
    topic: 'test',
  };
  const response = await admin
    .messaging()
    .send(message)
    .then((response) => {
      // Response is a message ID string.
      console.log('Successfully sent message:', response);
    })
    .catch((error) => {
      console.log('Error sending message:', error);
    });
};
notification coming for localhost or local IP through node API but not working for Production using HTTPS .

**Comment by hiranya911** [comment]
Most likely a problem with your receiver implementation. The sender implementation is same regardless of where and how you are running it (i.e. calls the same backend endpoint). Please file an issue with Firebase Support who can likely help you debug the issue: https://firebase.google.com/support
