### ISSUE TITLE
[FR] Allow credentials from environment variables

### ISSUE THREAD

**Issue by sanny-io** [firebase/firebase-admin-node#1383]
Environment variables are easier to work with when it comes to credentials. Credentials in a file causes unnecessary work to be done ensuring that they aren't committed into version control, but are also present on deployed servers. I propose that credentials also be loaded from environment variables directly, [such as in this library here.](https://github.com/googleapis/google-auth-library-ruby/blob/1119fbecad1d00b942c630c64dacb48ff640511b/lib/googleauth/credentials_loader.rb#L42-L49)

My use case is a Next.js app.

```javascript
admin.initializeApp({
 /**
 * Loads from GOOGLE_APPLICATION_CREDENTIALS, which specifies a file, but should
 * also support explicit definitions of the credentials in environment variables.
 * 
 * GOOGLE_PRIVATE_KEY
 * GOOGLE_CLIENT_EMAIL
 * GOOGLE_CLIENT_ID
 * GOOGLE_CLIENT_SECRET
 * GOOGLE_REFRESH_TOKEN
 * GOOGLE_ACCOUNT_TYPE
 * GOOGLE_PROJECT_ID
 */
    credential: admin.credential.applicationDefault(),
    databaseURL: 'https://<DATABASE_NAME>.firebaseio.com'
});
```

[Relevant documentation section.](https://firebase.google.com/docs/admin/setup#initialize-sdk)

**Comment by sanny-io** [comment]
I see now that I can use `admin.credential.cert` to achieve this. I guess my suggestion now is that `admin.credential.applicationDefault` should also support this by default if it can't read `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by hiranya911** [comment]
We fully support the application default credentials protocol as described in https://cloud.google.com/docs/authentication/production. The above environment variables are not standard, and not supported by most Google Auth libraries. For instance, you won't find them in the [Node.js](https://github.com/googleapis/google-auth-library-nodejs) and [Java](https://github.com/googleapis/google-auth-library-java) Google Auth packages. Therefore we want to stick to the same standard, and only support the already documented and well-known environment variables like `GOOGLE_APPLICATION_CREDENTIALS` and `GOOGLE_CLOUD_PROJECT`.
