### ISSUE TITLE
[FR] add support for listing users by provider id

### ISSUE THREAD

**Issue by mdneyazahmad** [firebase/firebase-admin-node#1395]
I have a large list of users with mixed provider id, some are anonymous, some authenticated by Google and so on. When we have to fetch all users authenticated by Google, we need to fetch all the (say ~ 1M) records and then loop through the users to checks it's provider id.

It would by good to add a method find by provider id.

**Comment by bojeil-google** [comment]
Hey @mdneyazahmad, I think you are basically asking for support for filtering/advanced querying options in our `listUsers` API. I don't think we have existing plans to support this on our backend. You may want to file an [official feature request](https://firebase.google.com/support) for it.

**Comment by mdneyazahmad** [comment]
Thank you @bojeil-google for your quick response. I want to know, if we can achieve the same in the current version of the library? If not, I will find another method. I am going to close this issue.

**Comment by bojeil-google** [comment]
> Thank you @bojeil-google for your quick response. I want to know, if we can achieve the same in the current version of the library? If not, I will find another method. I am going to close this issue.

It is not possible in the current implementation. You would need to download the user data and search through it based on your own criteria.

**Comment by mdneyazahmad** [comment]
Thank you @bojeil-google you have saved my time in researching to fix this issue. I am closing the issue.
