### ISSUE TITLE
Admin SDK does not work with the "regular" Firestore db when using a fake project ID

### ISSUE THREAD

**Issue by QuaternionMark** [firebase/firebase-admin-node#1400]
When attempting to use the admin SDK to access Firestore collections that were filled by the "regular" db instance (`firebase.firestore()`), the admin SDK is unable to find those collections. It works when I'm using my real project ID, but does not work with a fake ID.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase Product: Firestore, Admin SDK
  * Node.js version: 14.17.3
  * NPM version: 6.14.13

Relevant package.json files:
```
"@google-cloud/firestore": "^4.14.1",
"firebase": "^8.6.3",
"firebase-admin": "^9.11.0",
```

#### Steps to reproduce:

- Start the emulator with a fake project ID
- Define `FIRESTORE_EMULATOR_HOST` and `GCLOUD_PROJECT` variables.
- Run a code snippet that uses the admin SDK and the firestore db pointed to the emulator.

#### Relevant Code:
Running `firebase emulators:start --project test-project --only firestore,auth`

```
console.log(process.env.FIRESTORE_EMULATOR_HOST); // returns "localhost:8080"
console.log(process.env.GCLOUD_PROJECT); // returns "test-project"
const adminSDK = admin.initializeApp({ projectId: process.env.GCLOUD_PROJECT });
admin.firestore.setLogFunction(console.log);

const db = firebase.firestore();
const [host, port] = process.env.FIRESTORE_EMULATOR_HOST.split(":");
db.useEmulator(host, parseInt(port));

// fill the document using the regular db
await db.collection("unsecure_collection").doc("test").set({
    foo: "bar"
});

// attempt to access it using the admin SDK
const uh = await adminSDK.firestore().collection("unsecure_collection").doc("test").get();
console.log(uh.get("foo")); // returns undefined
```

Firestore logging returns this:
```
Firestore (4.13.2) 2021-08-04T18:19:13.175Z ##### [Firestore]: Initialized Firestore
Firestore (4.13.2) 2021-08-04T18:19:13.195Z dZIjV [ClientPool.acquire]: Creating a new client
Firestore (4.13.2) 2021-08-04T18:19:13.462Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (4.13.2) 2021-08-04T18:19:13.462Z dZIjV [Firestore.requestStream]: Sending request: {"database":"projects/test-project/databases/(default)","documents":["projects/test-project/databases/(default)/documents/unsecure_collection/test"]}
Firestore (4.13.2) 2021-08-04T18:19:13.551Z dZIjV [Firestore.requestStream]: Received response: {"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1628101153","nanos":544000000},"missing":"projects/test-project/databases/(default)/documents/unsecure_collection/test","result":"missing"}
Firestore (4.13.2) 2021-08-04T18:19:13.551Z dZIjV [Firestore._initializeStream]: Releasing stream
Firestore (4.13.2) 2021-08-04T18:19:13.552Z dZIjV [DocumentReader.fetchDocuments]: Document missing: projects/test-project/databases/(default)/documents/unsecure_collection/test
Firestore (4.13.2) 2021-08-04T18:19:13.554Z dZIjV [Firestore._initializeStream]: Received stream end
Firestore (4.13.2) 2021-08-04T18:19:13.556Z dZIjV [DocumentReader.fetchDocuments]: Received 1 results

```

The code works if I use the admin SDK or `firebase.firestore()` exclusively, or if I omit the `--project test-project` flag (which isn't an option since it's required for running the emulator in a CI environment). It also doesn't work if I do it the other way around, with the admin populating the document and then using the normal firestore code to read it.

My use case is that I want to unit test some production code that uses `firebase.firestore()`, but I need to populate the database using the admin SDK so I can bypass the security rules for the sake of testing small pieces of code.

In case it's relevant, the Firebase Auth portion of the admin appears to work fine with `firebase.auth()` code.

Is it not possible to use the admin SDK in this way or is there something wrong with my setup?

**Comment by lahirumaramba** [comment]
Hi @QuaternionMark,
Did a quick test with this setup and it seems to be working for me. Did you initialize `firebase` with the same project id as well?
```
firebase.initializeApp({
  projectId: process.env.GCLOUD_PROJECT,
})
```

**Comment by QuaternionMark** [comment]
@lahirumaramba I forgot to do that.

However, when I pass the correct fake ID to `initializeApp()` and then attempt to initialize the regular `firestore.auth()` instance it throws a `Error: Your API key is invalid, please check you have copied it correctly.`

**Comment by QuaternionMark** [comment]
@lahirumaramba Out of curiosity I tried passing a fake API key and that seemed to work.

```
firebase.initializeApp(usingEmulatorMode() ? {
    projectId: process.env.GCLOUD_PROJECT,
    apiKey: "fake-api-key",
} : config.result.sdkConfig);
```

Is this the intended way to set it up?

**Comment by yuchenshi** [comment]
The Firestore emulator emulates multiple projects, each with its own database. I think you've already figured out by now that you need to get your app and the admin script to agree on a single project ID. You're not alone with the confusion and we're considering ways to improve the experience.

As for the API key -- yes, the Auth Emulator requires a API key like production since it emulates the API. However, all non-empty strings are considered valid, including your snippet above.
