### ISSUE TITLE
Data message was received as a Notification message on Android device when sending to topic with mutableContent true

### ISSUE THREAD

**Issue by chalermpong** [firebase/firebase-admin-node#1407]
### Environment

  * Operating System version: Linux kernel – 4.14.165-102.205.amzn2.x86_64
  * Firebase SDK version: 9.10
  * Firebase Product: Messaging
  * Node.js version: 12.x (the code is run on Amazon Lambda)
  * yarn version: 1.22.10

### Describe the problem

Data message was received as a Notification message on Android device when sending with `sendToTopic` and `mutableContent: true`

#### Steps to reproduce:

Send a data message to topic by calling `sendToTopic` as shown below.
```javascript
messaging.sendToTopic(
  'my_topic',
   {
    data: {
      title: 'test_title',
      body: 'test_body'
    }
  },
  {mutableContent: true}
)
```
The message will arrive on Android device with `notification` field is not `null`, so it will be treated as a Notification message.

### Note
1. `mutableContent` is an option for iOS APN. The [document](https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingOptions#mutablecontent) said it will be ignored on Android
2. The message will be sent as a Data message correctly if `mutableContent: true` is removed from `MessageOptions`
3. `sendToDevice` can send this message (with `mutableContent: true`) correctly

### Expected Behavior

The message shall be received as a Data message on Android device (field `notification` shall be `null`)

**Comment by hiranya911** [comment]
@chong-shao note that this is using the legacy FCM API.

**Comment by chong-shao** [comment]
Hi @chalermpong thanks for reporting this. We confirm that this was a regression in the backend. It should have been fixed since around Aug 19. 

If the issue still happens on your side please reopen this issue. thanks!
