### ISSUE TITLE
[Messaging] Notification payload image name

### ISSUE THREAD

**Issue by OozyGrub** [firebase/firebase-admin-node#1408]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Big Sur
  * Firebase SDK version: 9.10
  * Firebase Product: Messaging
  * Node.js version: 14.7.0
  * YARN version: 1.22.10

### [REQUIRED] Step 3: Describe the problem

Hi, this is just about naming on message payload. According to [firebase documentation](https://firebase.google.com/docs/cloud-messaging/android/send-image), the image field names `image` however, in [this project](https://github.com/firebase/firebase-admin-node/blob/a9d8b410848babfa9b1dfeedbf1ae00572deea57/src/messaging/index.ts#L102) is `imageUrl`.  I think to make it consistent this should be changed to `image` as shown in document.

```
  /**
   * A notification that can be included in {@link messaging.Message}.
   */
  export interface Notification {
    /**
     * The title of the notification.
     */
    title?: string;
    /**
     * The notification body
     */
    body?: string;
    /**
     * URL of an image to be displayed in the notification.
     */
    imageUrl?: string; // Should be image?: string
  }

**Comment by schmidt-sebastian** [comment]
Sorry, I don't work on Messaging.

**Comment by hiranya911** [comment]
You're referring to the documentation of the REST API. There it's called `image`. But in the Node.js SDK it's intentionally called `imageUrl`.
