### ISSUE TITLE
`auth/insufficient-permission` (FirebaseAuthError: The caller does not have permission) when using default SA or SA by id

### ISSUE THREAD

**Issue by ZYinMD** [firebase/firebase-admin-node#1410]
### [READ] Step 1: Are you in the right place?
Yes
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: deployed firebase cloud functions 
  * Firebase SDK version: 9.2.0
  * Firebase Product: auth
  * Node.js version: 14
  * NPM version: yarn 1.x

### [REQUIRED] Step 3: Describe the problem
When using `admin.auth()` in deployed cloud functions, if I have a hardcoded SA.json it'll succeed, but if I use default credentials or "get SA by id" I'll get the `auth/insufficient-permission` [error](https://firebase.google.com/docs/auth/admin/errors).

In my case, I was trying to create a custom jwt with `admin.auth().createCustomToken(uid)` in a callable function.

#### Steps to reproduce:

Deploy the callable function below, and call it with client sdk (I used js sdk v9).

#### Relevant Code:

```ts
import * as admin from "firebase-admin";
import * as functions from "firebase-functions";

admin.initializeApp(); // will throw `auth/insufficient-permission`
admin.initializeApp({ serviceAccountId: "my-sa-id@my.iam.gserviceaccount.com" }); // will also throw 
admin.initializeApp({ credential: admin.credential.cert("path/to/json") }); // works

export const getJWT = functions.https.onCall(async (data) => {
  try {
    const jwt = await admin.auth().createCustomToken(data.uid);
    return jwt;
  } catch (err) {
    return functions.logger.error(err); /* -> 
   FirebaseAuthError: The caller does not have permission; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature.
    at FirebaseAuthError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAuthError (/workspace/node_modules/firebase-admin/lib/utils/error.js:149:16)
    at Function.FirebaseAuthError.fromServerError (/workspace/node_modules/firebase-admin/lib/utils/error.js:188:16)
    at handleCryptoSignerError (/workspace/node_modules/firebase-admin/lib/auth/token-generator.js:182:46)
    at /workspace/node_modules/firebase-admin/lib/auth/token-generator.js:141:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /workspace/dist/functions/initUser/initUser.js:8:21
    at async /workspace/node_modules/firebase-functions/lib/common/providers/https.js:322:26 {
  
   errorInfo: {
    code: 'auth/insufficient-permission',
    message: 'The caller does not have permission; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature.'
  },
  codePrefix: 'auth'
} 
    */
  }
});

```

**Comment by hiranya911** [comment]
Refer to the link in the error message for troubleshooting steps. That page provides information on what permissions/roles should be granted for this use case to work.

**Comment by ZYinMD** [comment]
@hiranya911 Of course I have read the page in the link before filling the issue. I read it 3 times. It does not have relevant information.

The two common issues with auto credential are the `iam.serviceAccounts.signBlob` permisssion issue, and the `IAM API not enabled` issue. My issue is neither of them. Please look at the error code.

**Comment by hiranya911** [comment]
Have you granted the "Service Account Token Creator" role to your service accounts as stated in that page?

**Comment by ZYinMD** [comment]
Yes:
1. The doc link has mentioned the signBlob issue in the "trouble shooting" section, and I have read it before filing the issue.
2. My error message does not mention `signBlob`, while the real signBlob issue does mention signBlob in its error message.
3. I did check my IAM, and I did have the `Service Account Token Creator` role.
4. This role is ON by default, at least from what I see in my newly created project.

I can use json for now, and see if other people find this issue via search in the future.

I agree it's not a bug to be fixed in the SDK, it's about the doc & error message – the doc says "auto credential is strongly recommended", then it doesn't work, then the error message is not specific enough, while pointing back to the same doc.

**Comment by hiranya911** [comment]
> "auto credential is strongly recommended"

It is indeed the recommended approach, and used by many developers. Also shown in most of our existing guides and codelabs.

> then it doesn't work

Just double checked with a simple cloud function, and it seems to work fine. No errors observed when running the following example:

```
const functions = require("firebase-functions");
const admin = require('firebase-admin');

admin.initializeApp();

exports.signMyTokens = functions.https.onRequest(async (request, response) => {
  const token = await admin.auth().createCustomToken('john');
  response.send("MyToken: " + token);
});
```

> then the error message is not specific enough

I'm starting to think your problem is somehow unique to your specific project/setup. Either your code is deployed to a different project than the one you think. Or if it's the right project, then it has a broken permissions.

**Comment by hiranya911** [comment]
Btw, you are right about points 3 and 4 above. The "Service Account Token Creator" role is indeed available on the default service account used by Cloud Functions, and I didn't have to change any permissions when testing the above example.
