### ISSUE TITLE
[Firestore] Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

### ISSUE THREAD

**Issue by evgeniy-skakun** [firebase/firebase-admin-node#1419]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Debian GNU/Linux 10 (buster) [Google Cloud VM]
  * Firebase SDK version: 9.11.1
  * Firebase Product: Firestore
  * Node.js version: 10.24.0
  * NPM version: 5.8.0
  * Plan: Blaze
 
### [REQUIRED] Step 3: Describe the problem

From time to time the following error occurs:
```
Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
     at Object.callErrorFromStatus (/var/www/html/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
     at Object.onReceiveStatus (/var/www/html/node_modules/@grpc/grpc-js/build/src/client.js:330:49)
     at Object.onReceiveStatus (/var/www/html/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
     at /var/www/html/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
     at processTicksAndRejections (internal/process/task_queues.js:75:11)
 Caused by: Error
     at Firestore.getAll (/var/www/html/node_modules/@google-cloud/firestore/build/src/index.js:797:23)
     at DocumentReference.get (/var/www/html/node_modules/@google-cloud/firestore/build/src/reference.js:201:32)
     at parseChannels (/var/www/html/src/pubnub.js:250:22)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async exports.getAllMemberships (/var/www/html/src/pubnub.js:381:26) {
   code: 16,
   details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
   metadata: Metadata {
     internalRepr: Map {
       'google.rpc.errorinfo-bin' => [Array],
       'grpc-status-details-bin' => [Array],
       'www-authenticate' => [Array]
     },
     options: {}
   }
 }
```

#### Steps to reproduce:

I cannot reproduce this, it happens from time to time when many users use our server which makes various requests to Firestore

#### Relevant Code:

```js

admin.initializeApp({
  credential: admin.credential.cert(credential),
  databaseURL: databaseURL,
  databaseAuthVariableOverride: {
    uid: "admin-service-worker"
  }
});

...

firestore.collection('someName').add(data);
```

**Comment by shehan-mark** [comment]
I am getting this error inside a heroku dyno. Not sure if we can do anything with the hosting environment. Is there any other solution for this?

**Comment by emirpasic** [comment]
Faced the same issue, and synced the clocks (using _ntp_) and it fixed the issue. 

Please fix the error message above as it was misleading, or amend it to tell what the possible cause for this could be. Luckily I found this thread before growing grey hair.

**Comment by alijuniorbr** [comment]
This error can occur when your computer's clock has the wrong date and time. Simply adjust the date and time and the error will disappear.

**Comment by pedrorambo** [comment]
FYI: In my case, the issue was related to my system date and time. I’m using Windows 11 with “Set time automatically” enabled, but for some reason the time was completely wrong.

Disabling the option and enabling it again fixed the issue and set the correct time.

**Comment by lucasdmmc** [comment]
> This error can occur when your computer's clock has the wrong date and time. Simply adjust the date and time and the error will disappear.

you saved my life <3
