### ISSUE TITLE
I am able to initializeApp in multiple files. Is it a bug or is it allowed somehow?

### ISSUE THREAD

**Issue by yaziciahmet** [firebase/firebase-admin-node#1428]
index.js :
```
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const cors = require("cors")({ credentials: true, origin: true });

exports.addVehicle = functions.https.onRequest(async (req, res) => {
  cors(req, res, async () => {
    await require("./src/vehicles/addVehicle").addVehicle(req, res);
  });
});
```

addVehicle.js:
```
const admin = require("firebase-admin");
const Vehicle = require("../../models/Vehicle");

const app = admin.initializeApp();
const db = app.firestore();

exports.addVehicle = async (req, res) => {
  try{
    const vehicleInfo = new Vehicle(req.body);
    
    const addedVehicle = await db.collection("vehicles").add(vehicleInfo);
    
    res.json({data: "Succesfully added vehicle"});
  }
  catch(err){
    if(err){
      res.json(err);
    }
  }
};
```

Basically my question is that I use initializeApp in all of the seperate files for the functions (in addVehicle.js, getVehicles.js ex...). Is it legal or is there any downsides to this? I tried and all of the functions are working as expected. Normally it shouldn't be allowed to initializeApp multiple times. So I thought is it legal or is there any downsides to this?

**Comment by hiranya911** [comment]
Calling `initializeApp()` multiple times with the same arguments in the same Node.js process is not allowed. You will get errors if you try to do so. So as long as your "files" run in different processes, everything will be fine.

Also please use StackOverflow or GitHub Discussions for usage questions such as this.
