### ISSUE TITLE
firebase-admin throws dependency error

### ISSUE THREAD

**Issue by KevinMind** [firebase/firebase-admin-node#143]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOs 10.13.1 High Sierra
  * Firebase SDK version: 4.2.1 and 5.4.0 (tried both, both threw same error
  * Library version: ?
  * Firebase Product: firebase-admin

### [REQUIRED] Step 3: Describe the problem

React app trying to connect to firestore through firebase-admin.

const admin = require('firebase-admin');

throws error 

./node_modules/firebase-admin/node_modules/isemail/lib/isemail.js
Module not found: Can't resolve 'dns' in '/Users/devmode/Documents/projects/google-crm/node_modules/firebase-admin/node_modules/isemail/lib'

#### Steps to reproduce:

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "apiai": "^4.0.3",
    "firebase-admin": "4.2.1",
    "firebase-functions": "0.5.9",
    "gactions": "0.0.0",
    "material-ui": "^0.19.4",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {}
}

**Comment by esparkman** [comment]
@KevinMind I was having the same issue. I had an issue open that has since been closed I'll referenece it for you #84 . The short of it is, if you're trying to use firebase-admin in a Frontend framework(React, Vue, etc) it is not supported. firebase-admin is supported only on server side implementations.

**Comment by crossRT** [comment]
@esparkman I using firebase-admin on server side with webpack.
But still having such errors:

```
WARNING in ./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
16:20-67 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/grpc/src/grpc_extension.js
32:12-33 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/bytebuffer/dist/bytebuffer-node.js
Module not found: Error: Can't resolve 'memcpy' in '/Users/crossrt/www/malaysia-election/node_modules/bytebuffer/dist'
 @ ./node_modules/bytebuffer/dist/bytebuffer-node.js 29:38-55
 @ ./node_modules/protobufjs/dist/protobuf.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts
```

Do you have any idea?

**Comment by hiranya911** [comment]
@crossRT when do you get this error? Install time or run time?

**Comment by crossRT** [comment]
Hi @hiranya911 during webpack compile time.

**Comment by hiranya911** [comment]
I don't know enough about webpack to be helpful here. But I'd see if the above can be ignored altogether. After all they are logged as warnings. If there is a compilation failure, it may be due to some other reason. 

Try posting this on Stackoverflow. There are more than a few developers who use Admin SDK with Webpack, and somebody might have a clue. Alternatively provide a detailed repro (code and instructions), so we can dig into it.
