### ISSUE TITLE
FR: admin.auth().generateVerifyAndChangeEmailLink()

### ISSUE THREAD

**Issue by marchbox** [firebase/firebase-admin-node#1475]
**Feature request**

The JS API includes `firebase.auth().currentUser.verifyBeforeUpdateEmail()` method. This is a great way to make sure the ownership of the new email, also avoid inability to sign in in case the user made a typo when changing their email.

But currently there's no way to customize the email template for this. Also the custom email action handler is not well documented (on [this page](https://firebase.google.com/docs/auth/custom-email-handler), no mention of the `mode` `verifyAndChangeEmail`).

Would be great if, in the admin SDK, there was `firebaseAdmin.auth().generateVerifyAndChangeEmailLink()`.

**Comment by mattrltrent** [comment]
Any progress on this yet?

**Comment by mattrltrent** [comment]
@Xiaoshouzi-gh This function still doesn't seem to actually exist in the admin SDK? I'm using Golang and no matter what I do can't find it. Anyway you can link it? 

Thanks.
