### ISSUE TITLE
FIREBASE WARNING: wss:// URL used, but browser isn't known to support websockets.

### ISSUE THREAD

**Issue by arnav-kr** [firebase/firebase-admin-node#1487]
constantly getting this message in the console and also unable to read and write to the database, I have another project running with the same version but that one is working correctly

logs:
![image](https://user-images.githubusercontent.com/72879799/140478806-cf27fa9d-daf6-4012-bfbc-9e5a18ab8efc.png)

dependencies:
![image](https://user-images.githubusercontent.com/72879799/140479049-2c599971-541b-4506-a300-ca9e64546025.png)

code:
![image](https://user-images.githubusercontent.com/72879799/140479184-5781e368-e06d-4a9b-bb1f-0a7598fa094e.png)

**Comment by raulnetspot** [comment]
I have the same problem, but using Typescript:

```ts
import * as functions from 'firebase-functions';
import {initializeApp, cert, getApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getDatabase, getDatabaseWithUrl} from 'firebase-admin/database';
import {getStorage} from 'firebase-admin/storage';
import {getMessaging} from 'firebase-admin/messaging';

const config = functions.config().env;
const serviceAccount =
  config.production === 'true'
    ? require('../service-credential-prod.json')
    : require('../service-credential-staged.json');

initializeApp({
  credential: cert(serviceAccount, ),
  databaseURL: config.dbUrl,
});

export const app = getApp();
export const auth = getAuth();
export const db = getDatabase();
export const medicalDb = getDatabaseWithUrl(config.dbMedicalUrl);
export const storage = getStorage();
export const messaging = getMessaging();
```

```json
"engines": {
    "node": "14"
  },
  "main": "build/index.js",
  "dependencies": {
    "ajv": "^8.6.3",
    "date-fns": "^2.25.0",
    "firebase-admin": "^10.0.0",
    "firebase-functions": "^3.16.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.3.3",
    "firebase-tools": "^9.22.0",
    "typescript": "^4.4.4"
  },
```

**Comment by lahirumaramba** [comment]
Hi @arnav-kr, Thank you for reporting this issue!

@jsdt I can reproduce the issue with the following dependencies.
```
└─┬ firebase-admin@10.0.0
  ├── @firebase/database-compat@0.1.3
  ├── @firebase/database-types@0.7.3
  ├── @google-cloud/firestore@4.15.1
  ├── @google-cloud/storage@5.15.5
  ├── @types/node@16.11.6
  ├── dicer@0.3.0
  ├── jsonwebtoken@8.5.1
  ├── jwks-rsa@2.0.5
  └── node-forge@0.10.0
```
Any thoughts on what could be wrong?

**Comment by lpellegr** [comment]
Some functions with the warning mentioned in this issue time out. Is this also your case?

**Comment by jcurlier** [comment]
Same issue here +1

started last night, first error 2021-11-04 19:09:57

**Comment by acoyfellow** [comment]
+1 same issue. i had to revert cloud run to an older revision to get it working

And, using that same exact codebase on a new deploy (same cloud run environment)- i see this error as well.

**Comment by amitsingh-007** [comment]
I also faced the same issue with firebase-admin version `9.12.0`. Reverted to `9.11.0` and it works fine for now.

**Comment by lahirumaramba** [comment]
Thank you for your patience! Our team has identified the root cause and currently working on a fix.
In the meantime you can pin `@firebase/database-compat` to version `0.1.2` in your `package.json` file as a temporary fix.
```
  "dependencies": {
    "@firebase/database-compat": "0.1.2"
  }
```
We will update here as soon as a fix is ready.

**Comment by ayyysh04** [comment]
I am getting the same error/warning when trying to change/access something in realtime database,I tried the above solution but they didn't work.
could anyone see whats wrong in my code:
https://stackoverflow.com/questions/69853038/firebase-function-with-realtime-database-error

**Comment by ayyysh04** [comment]
> Thank you for your patience! Our team has identified the root cause and currently working on a fix. In the meantime if you are on the latest Admin SDK version, you can pin `@firebase/database-compat` to version `0.1.2` in your `package.json` file as a temporary fix.
> 
> ```
>   "dependencies": {
>     "@firebase/database-compat": "0.1.2"
>   }
> ```
> 
> We will update here as soon as a fix is ready.

I tried using this fix but it is still giving me the same warning/error.
If possible check out  my same question on stackoverflow:https://stackoverflow.com/questions/69853038/firebase-function-with-realtime-database-error

**Comment by lpellegr** [comment]
To force pin a specific version of `@firebase/database-compat`, I had to use the `resolutions` field of _package.json_:

```json
"resolutions": {
    "@firebase/database-compat": "0.1.2"
},
```

**Comment by ayyysh04** [comment]
> To force pin a specific version of `@firebase/database-compat`, I had to use the `resolutions` field of _package.json_:
> 
> ```json
> "resolutions": {
>     "@firebase/database-compat": "0.1.2"
> },
> ```

still getting the same warning/error

**Comment by acoyfellow** [comment]
> Thank you for your patience! Our team has identified the root cause and currently working on a fix. In the meantime if you are on the latest Admin SDK version, you can pin `@firebase/database-compat` to version `0.1.2` in your `package.json` file as a temporary fix.
> 
> ```
>   "dependencies": {
>     "@firebase/database-compat": "0.1.2"
>   }
> ```
> 
> We will update here as soon as a fix is ready.

This isn't working for me - even if it's added to `package.json` `resolutions`

**Comment by lpellegr** [comment]
@ayyysh04  @acoyfellow Did you rebuild your _package-lock.json_ or _yarn.lock_ after updating the _package.json_ file?

**Comment by ayyysh04** [comment]
> @ayyysh04 @acoyfellow Did you rebuild your _package-lock.json_ or _yarn.lock_ after updating the _package.json_ file?

no,i only edited the package.json but didn't rebuild the package-lock.json.
How can i rebuild the package-lock.json ?

**Comment by lpellegr** [comment]
A simple way is to delete `node_modules/` and `package-lock.json`, and then run `npm install`.

**Comment by acoyfellow** [comment]
Yes, I did. 

I'm only seeing this in a Cloud Run environment.  I've been unable to replicate in my local/dev environment.

**Comment by ayyysh04** [comment]
> A simple way is to delete `node_modules/` and `package-lock.json`, and then run `npm install`.

thanks it worked ,but for rebuilding the package lock file i have to use ```npm install --package-lock-only```

**Comment by lounerios** [comment]
I am also faced the problem with "@firebase/database-compat": "0.1.2" and firebase-admin@10.0.0

**Comment by JCsplash** [comment]
I'm using "firebase-admin": "9.7.0" and am also facing this issue. 

This seems to have suddenly started happening a couple days ago because it didn't happen last week. I didn't change / update any code and this bug started to happen. Is this the experience others have had too?

**Comment by MarianBe** [comment]
Same issues here, with runtime `nodejs10` none of the combinations worked for me
`firebase-admin: 10.0.0
@firebase/database-compat: 0.1.2`

**Comment by lounerios** [comment]
> 
> 
> Same issues here, with runtime `nodejs10` none of the combinations worked for me
> 
> ```json
> "firebase-admin": "10.0.0",
> "@firebase/database-compat": "0.1.2"
> ```
I found the solution by using the resolutions for the database-compat and using yarn instead of npm.

**Comment by MarianBe** [comment]
Found a solution, downgrading to 
`firebase-admin@9.11.0` worked for me

**Comment by JCsplash** [comment]
@Feiyang1  why did you close this issue? Is this fixed now? I've just tried and it still doesn't seem to work.

**Comment by JCsplash** [comment]
> Found a solution, downgrading to `firebase-admin@9.11.0` worked for me

I've upgraded from  `firebase-admin@9.7.0` to  `firebase-admin@9.11.0` and did not have success :(

**Comment by lahirumaramba** [comment]
This issue is now fixed in `@firebase/database-compat@0.1.4`. You might have to clean your `package-lock` files and run `npm install` to get the latest version of the `database-compat` dependency. Thank you.

**Comment by robertedjones** [comment]
Do we still need to add database-compat as a dependency and in resollutions?

**Comment by larssn** [comment]
Please reopen

**Comment by james-ingold** [comment]
> Do we still need to add database-compat as a dependency and in resollutions?

No, you should be able to npm install with latest firebase deps
```
    "firebase": "^9.4.0",
    "firebase-admin": "^10.0.0",
```

**Comment by larssn** [comment]
I can confirm that using the latest dependencies fixes the problem.

**Comment by JCsplash** [comment]
Yesterday afternoon my functions were still throwing errors, but in the evening - without upgrading any packages or doing npm install - suddenly the functions started to work again. Anyone know why this is the case?

**Comment by lahirumaramba** [comment]
> Yesterday afternoon my functions were still throwing errors, but in the evening - without upgrading any packages or doing npm install - suddenly the functions started to work again.
> 
> It seems like the fix was purely on firebase's end and does not require any updates. Can someone confirm this is the case?
> 
> @Feiyang1 @jsdt

@JCsplash this is interesting. Once the functions are deployed it should not pull dependencies unless the function is re-created or updated. Do you by any chance have a mechanism to update the functions in your setup?
