### ISSUE TITLE
using a custom bucket name causes errors

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-admin-node#1490]
when I create a bucket instance with its default name it works fine, but it causes errors when I provide a custom bucket name.

```
import { storage, app as _app } from 'firebase-admin';
import { Bucket } from '@google-cloud/storage';

let bucket: Bucket = storage().bucket('custom-bucket-name')

bucket.upload('./file.jpg');
```

using a custom bucket name causes an error:
```
The project to be billed is associated with an absent billing account
```
but using `.bucket()` without any name makes it work fine and `.upload()` works

**Comment by lahirumaramba** [comment]
This might be because the Cloud Storage bucket you are trying to access does not exist. Please make sure the a bucket with the custom-name exists in your project. To create a new storage bucket using the SDK you should use the `storage.createBucket(...)` API.

**Comment by tonyjhuang** [comment]
Yep, please verify that the bucket you're trying to access exists and you have permission to access it.

Also note that creating new buckets is only supported for Blaze projects.
