### ISSUE TITLE
Program doesn't terminate when running FCM.sendToDevice in nodejs.

### ISSUE THREAD

**Issue by SiestaMadokaist** [firebase/firebase-admin-node#150]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS High Sierra (10.13.1)
  * Firebase SDK version: firebase: (^4.5.1)
  * Library version: firebase-admin (^5.4.2)
  * Firebase Product: FCM / admin.messaging()

### [REQUIRED] Step 3: Describe the problem

NodeJS program doesn't terminate after running FCM command.

#### Steps to reproduce:

- save the following code as: fcm-test.js
- run the code with

`node fcm-test.js`
- In my enviroment, it'll not stop untill you forcefully stop it by pressing CTRL+C.

#### Relevant Code:
```
const admin = require('firebase-admin');
const serviceAccount = require("../../../service-accounts/production.json");
const registrationTokens = require('./tokens');
// ["someShortString1:someLongString1", "someShortString2:someLongString2", ...];
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
})
const body = 'body';
const title = 'title';
const payload = {
  data: {
    body,
    title
  },
  notification: {
    body,
    title
  }
}
const fcm = admin.messaging();
const printJSON = (thing) => { console.log(JSON.stringify(thing, null, 2))};
fcm.sendToDevice(registrationTokens, payload).then(printJSON).catch(printJSON);
```

**Comment by hiranya911** [comment]
This is because Admin SDK starts background tasks. You need to call [`app.delete()`](https://firebase.google.com/docs/reference/admin/node/admin.app.App#delete) if you wish to ensure graceful termination of the process.

**Comment by SiestaMadokaist** [comment]
may I ask one more thing?
is it safe to have an cloudfunction endpoint that looks something like:
`// some initialization code`
const FCM = admin.messaging();
module.exports.sendToDevices = functions.https.onRequest((req, res) => {
    const { tokens } = req.body;
    FCM
      .sendToDevice(tokens, payload)
      .then(() => {res.send("OK")} )
      .catch(() => { res.send("FAIL")});
})

**Comment by hiranya911** [comment]
Given that you're calling `res.send()` in each possible case, I believe it's fine.

**Comment by dandv** [comment]
> You need to call app.delete() if you wish to ensure graceful termination of the process.

How was the developer supposed to know they had to call `app.delete()`?
