### ISSUE TITLE
createSessionCookie does not pick up USER_DISABLED errors

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-admin-node#1503]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS
  * Firebase SDK version: 10.0.0
  * Firebase Product: auth
  * Node.js version: 16
  * NPM version: N/A

### [REQUIRED] Step 3: Describe the problem

The following generic error is returned:

```
{
    code: 'auth/internal-error', 
    message: 'An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"USER_DISABLED","errors":[{"message":"USER_DISABLED","reason":"invalid","domain":"global"}]}}"'
}
```

Where as there is a `auth/user-disabled` error code defined so should use that instead:
https://github.com/firebase/firebase-admin-node/blob/94dd7c3efb9ff00b0462cf772b803d6abecc2dcc/src/utils/error.ts#L724-L727

So I'd expect a similar error to using `.verfiyIdToken` for a disabled user:

```
{
   code: 'auth/user-disabled',
   message: 'The user record is disabled.'
}
```

#### Steps to reproduce:

1. Create a user
2. Sign in to a client SDK as the user and `.getIdToken`
3. Disable the user
4. In Admin SDK try `.createSessionCookie(idToken, { expiresIn: 300000 })`

**Comment by lahirumaramba** [comment]
@bojeil-google @xil222 Should we check for disabled accounts in `createSessionCookie ()` similar to #1401 ?

**Comment by rhodgkins** [comment]
Just to node the issue, for me, isn’t that it’s not checking for disabled users, it’s just not parsing the server error correctly and dumping it into the message, like it’s just been missed:

`An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"USER_DISABLED","errors":[{"message":"USER_DISABLED","reason":"invalid","domain":"global"}]}}"`

**Comment by xil222** [comment]
Thanks for the info, I'm looking on this
