### ISSUE TITLE
Update node-forge dependency

### ISSUE THREAD

**Issue by rrnara** [firebase/firebase-admin-node#1529]
npm audit generates the following error for node-forge < 1.0.0:
Prototype Pollution in node-forge debug API. - https://github.com/advisories/GHSA-5rrq-pxf6-6jx5

**Comment by fanxiosrepo** [comment]
Another advisory was published that has to do with the `node-forge` dependency.

[URL parsing in node-forge could lead to undesired behavior.](https://github.com/advisories/GHSA-gf8q-jrpm-jvxq)

**Comment by TheBrockEllis** [comment]
There was another advisory published a few days ago regarding `firebase-admin` and the `node-forge` dependency.

[URL parsing in node-forge could lead to undesired behavior.](https://github.com/advisories/GHSA-gf8q-jrpm-jvxq)

**Comment by lahirumaramba** [comment]
It does not look like `firebase-admin` uses the `forge.util.parseUrl` API directly. We also updated the dependency in #1533
Thank you.

**Comment by AviVahl** [comment]
@lahirumaramba 
Appreciate you verifying vulnerable API is not used by `firebase-admin` :+1: I know I can ignore that one.
Any chance to release a patch version so we'll get a clean audit report? (or is it already planned for some future date?)

**Comment by lahirumaramba** [comment]
This change will be included (along with other updates) in a release planned for next week. I will update this issue once the release is out. In the meantime please update to `node-forge 1.0.0` in your server environments. Thank you for your patience!

**Comment by lahirumaramba** [comment]
`node-forge` version update is included in today's release v10.0.2. Thank you for your patience everyone!
