### ISSUE TITLE
Start testing against Node 8 and 9

### ISSUE THREAD

**Issue by ofrobots** [firebase/firebase-admin-node#153]
Hi Folks, over at my PR (#265) I noticed that the tests are run against Node 4, 5, 6, 7. Is there a reason for not testing against the actual LTS and Current releases (8.x and 9.x respectively).

BTW, Node 5 and 7 are no longer supported upstream. You can stop testing against those.

**Comment by hiranya911** [comment]
@jshcrowthe WDYT?

**Comment by hiranya911** [comment]
I actually got a test failure on Node 9: https://travis-ci.org/firebase/firebase-admin-node/builds/313726251

**Comment by hiranya911** [comment]
Testing on Node 8 is now in place.

**Comment by hiranya911** [comment]
Closing this since we have Node 8 CI set up now. We can add Node 9 in the future.

**Comment by ofrobots** [comment]
Is there rationale for not starting to test against Node 9 immediately? Node 9 is the "current" version of Node, and as you can see from the [charts here](https://nodesource.com/node-by-numbers), Node 9 is already has significant usage.

Either way, I don't believe you've adequately addressed the original issue I opened that requested testing on both 8.x and 9.x. Either this bug should be reopened, or you should open another bug to track the addition of Node 9.x, if you're not going to address it immediately.
