### ISSUE TITLE
[Firestore] Firestore bundler assigning wrong path to documents in the bundle.

### ISSUE THREAD

**Issue by Jac0xb** [firebase/firebase-admin-node#1530]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google Cloud Function
  * Firebase SDK version: 10.0.1
  * Firebase Product: Firestore
  * Node.js version: Node.js 16
  * NPM version: N/a

#### Steps to reproduce:

Could not load bundle client-side and couldn't figure out why because all the documents appeared to be in the bundle. That's when I realized the paths are screwed up for ever document.

In firebase, the document path is
`/camelCaseCollection/AduBDwBuaUnJzNjVbU2DCPmQrDZsW5DAPGCpdSievXoB`

In the bundle file each document has a path similar to.
`projects/feeble-labs/databases/(default)/documents/feeble/AduBDwBuaUnJzNjVbU2DCPmQrDZsW5DAPGCpdSievXoB`

It's really weird that "feeble" is the collection name, the project id is "feeble-labs".

I had to query the collection "feeble" and not "camelCaseCollection" in the clientside firebase app.

#### Relevant Code:

```javascript
const firestore = admin.firestore();

const bundle = firestore.bundle("bundle-id");

const snapshot = await firestore.collection("camelCaseCollection").get();

const buffer = bundle.add("query-id", snapshot).build();

const storage = admin.storage().bucket(GS_BUCKET);

await storage.file(GS_BUNDLE_PATH).save(buffer);
```

**Comment by schmidt-sebastian** [comment]
@Jac0xb Thanks for filing this. I just verified bundling with the underlying SDK and was able to see the expected document names. If you can reproduce this issue, are you able to provide debug logs and the bundle itself? This would allows us to verify that we are saving the correct documents. Your code sample looks correct.

You can turn on debug logging by invoking `setLogFunction(console.log)`.

**Comment by Jac0xb** [comment]
> @Jac0xb Thanks for filing this. I just verified bundling with the underlying SDK and was able to see the expected document names. If you can reproduce this issue, are you able to provide debug logs and the bundle itself? This would allows us to verify that we are saving the correct documents. Your code sample looks correct.
> 
> You can turn on debug logging by invoking `setLogFunction(console.log)`.

I rebuilt the bundle and the paths fixed. I'm not sure what caused it. I'm having a similar class of issues in google cloud functions where it won't let me specify in the config UI the correct document path to listen to and I have to use the firebase functions library.

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know. Will close this issue for now. We can re-open if needed.
