### ISSUE TITLE
NPM package includes an old dependency of node-forge

### ISSUE THREAD

**Issue by maorizenberg** [firebase/firebase-admin-node#1547]
I've extracted firebase-admin-10.0.1.tgz and found that inside package.json there's a dependency of     "node-forge": "^0.10.0"

It should be the newer version as in current Github rep
[firebase-admin-10.0.1.zip](https://github.com/firebase/firebase-admin-node/files/7895082/firebase-admin-10.0.1.zip)
o

**Comment by kaldenswart** [comment]
+1

**Comment by kaldenswart** [comment]
It seems like node-forge was bumped to 1.0.0 but only on 1/10/2022 and firebase-admin 10.0.1 was released December 2021. Think we going to have to sit and wait for the next release.

**Comment by tocak** [comment]
any manual solution we can do while we wait for the release?

**Comment by lahirumaramba** [comment]
Thank you for your patience!
We just released a patch with `node-forge` version bump. The update #1533 is included in v10.0.2.
