### ISSUE TITLE
Upload via FirbaseStorage - Issue: Firebase/Storage in the console

### ISSUE THREAD

**Issue by AnthonyNahas** [firebase/firebase-admin-node#156]
## Environment

  * Operating System version:  MacOS High Sierra 10.13.2
  * Firebase SDK version: 5.5.1
  * Library version: 5.5.51
  * Firebase Product: storage

## Description:

I am using `firebase-admin` module on the server side with NodeJS in order to manage the authentication process, the storage and more.

I am facing only problem with the firebase storage product!
I am able to upload the target file to the cloud, however the firebase console is acting like i dont know what... very strange.

The destination of the file is like estimated in the cloud, but i cant preview the image!!!
In the console, the image is replaced by mat-progress-spinner and never ends to load(see below)!!

![screenshot 2017-12-12 21 53 11](https://user-images.githubusercontent.com/20149774/33908297-39fc3386-df88-11e7-9cfc-748dd0ebb4b4.png)

the path of the image is available on the console, but the url and the "other meta data" are always empty.

![screenshot 2017-12-12 22 27 39](https://user-images.githubusercontent.com/20149774/33909355-aede7f08-df8b-11e7-91f7-f4348cc1ae34.png)

A nice idea was to generate a new url! But unfortunately i became the following error --> 

![screenshot 2017-12-12 22 06 05](https://user-images.githubusercontent.com/20149774/33908453-c0d77b04-df88-11e7-8029-55056289cef7.png)
![screenshot 2017-12-12 22 06 15](https://user-images.githubusercontent.com/20149774/33908454-c0f78098-df88-11e7-9919-786d741302f5.png)
![screenshot 2017-12-12 22 06 23](https://user-images.githubusercontent.com/20149774/33908455-c1105a46-df88-11e7-8084-7ac5d3a73535.png)
 
"Error/Failed while generating a new url"!

And even more i cant download the checked image with the raised button "**download**"!
But very scary, the raised button "**delete**" works!

If i open the chrome dev tools --> console --> i can see few more informations - errors (maybe that could helps)

- `Uncaught TypeError: ng.probe is not a function
    at Object.exports.isDebugMode`
- `Uncaught TypeError: a.indexOf is not a function
    at FBC_Ea`

In chrome dev tools --> network i got a 401 error while loading the image (see below)

![screenshot 2017-12-12 22 15 42](https://user-images.githubusercontent.com/20149774/33908880-1d1ae544-df8a-11e7-9c63-7cd194d3ecba.png)

I thinks there are few bugs to fix... and i would be very thankful for a feedback from the core team!

# Code

```
...
@injectable()
export class FirebaseStorage {

    // Get the Storage service for the default app
    private _defaultStorage: admin.storage.Storage = admin.storage();
    private _bucket = this.defaultStorage.bucket();
    private _metadata = {
        cacheControl: "public,max-age=36000",
        customMetadata: {
            "method": Methods[Methods.Upload]
        }
    };


    constructor(@inject("FirebaseAdmin") firebaseAdmin: FirebaseAdmin) {
    }

    /**
     * Uplaod image to the storage
     *
     * @param {string} imageSrc - the path od the temp image to upload
     * @param imageDist
     * @returns {Promise<any>} - the media link of the uploaded image
     */
    public async uploadFileToStorage(imageSrc: string, imageDist: string): Promise<any> {
        const upload = await this.bucket.upload(imageSrc,
            {
                destination: imageDist,
                public: true,
                metadata: this._metadata
            });
        // console.log("upload done --> ", upload);
        return upload[0].metadata.mediaLink;
    }

    get defaultStorage(): admin.storage.Storage {
        return this._defaultStorage;
    }

    set defaultStorage(value: admin.storage.Storage) {
        this._defaultStorage = value;
    }

    get bucket(): any {
        return this._bucket;
    }

    set bucket(value: any) {
        this._bucket = value;
    }
}
```

## Note:

I am using the firebase module on the client side with Angular, and the upload process works really good and everything act like expected! Using the firebase-admin module in combination with the storage, the upload process is a little bit critical, since the firebase console does not works as expected.

_Final note:_ in the **response** of the upload request, with `firebase-admin` (**NodeJS**) the _url_ of the image is like  `https://www.googleapis.com/download/storage/v1/b/mybucket/blablabla/image.png` but the _url_ received in the **response** with `firebase` module (**Angular**) it's like `https://firebasestorage.googleapis.com/v0/b/mybucket/blablabla/image.png`

**Comment by hiranya911** [comment]
You might have to set a few additional properties for the console to work as expected in this case. @katfang do you have any idea what's going on here?

**Comment by AnthonyNahas** [comment]
I would be really thanksful if you could provide min. an example and more info regarding this bug

**Comment by diegonzs** [comment]
The image doesn't show because it uses the download URL and if you see the details of the image it doesn't have one.

I found the solution to the problem in stackoverflow. [https://stackoverflow.com/a/43764656/7332915](url)

**Comment by hiranya911** [comment]
I assume this is fixed now. Or at least the workarounds mentioned in the previous comment helps alleviate it. If the problem still occurs, please file a support issue as this is something that needs be be investigated and fixed at a higher level as opposed to the code in this repo.

**Comment by eddyoc** [comment]
This issue persists

**Comment by sohebcakewalk** [comment]
Hi,
I was have same error, review google cloud console if very simple, no display in console because firebase console need firebaseStorageDownloadTokens, check example:

first install : npm install uuid

    bucket.upload(filename, {
      destination,
      metadata: {
          metadata :{
            firebaseStorageDownloadTokens: uuidv4(),
         }
      },
    })

**Comment by pedroBruno7** [comment]
In 2021, this still doesn't work, there's no easy and straightforward way to upload a file in node.js to firebase

Using:

 upload bucket.upload(file.path, {
                destination: ...
            });
            
It will upload on google cloud and not on the firebase dashboard, hence the loading

I've tried it and was able to get the public king from google cloud
