### ISSUE TITLE
[FR] recursiveDelete also for firebase-admin

### ISSUE THREAD

**Issue by dcts** [firebase/firebase-admin-node#1566]
**problem**
There is no easy way to delete a document and all its nested elements (subcollections and documents as well as deeper nested elements) with the `firebase-admin` package. 

**Describe the solution you'd like**
A function to delete a document and all its descendant elements, similar to [`firestore.recursiveDelete()`](https://googleapis.dev/nodejs/firestore/latest/Firestore.html#recursiveDelete) from the [google-cloud/firestore](https://www.npmjs.com/package/@google-cloud/firestore) package.

**Describe alternatives you've considered**
- 1: using both `firestore-admin` and `google-cloud/firestore` packages simultaniously. Seems overkill to have that much duplicate functionalities.
- 2: creating a cloud function as described [here](https://firebase.google.com/docs/firestore/solutions/delete-collections). I would prefere to not have a publically accessible function that lets you delete data from the database. Although you can secure it with authentication, this would not let me sleep peacfully at night.

**Additional context**
firebase is the best 🔥

**Comment by lahirumaramba** [comment]
Hey @dcts ,
The Admin SDK uses `google-cloud/firestore` so you should be able to do the following:
```
import { initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore';

const app = initializeApp()

const fs = getFirestore()
fs.recursiveDelete(...)
```
Please provide a repro if this is not what you expected. Thanks!

**Comment by dcts** [comment]
Awesome, this indeed does work! Thanks for your answer! I realized that I was using version 9, and this seems to only work with v10. I guess will need to update to v 10 soon :)
