### ISSUE TITLE
FR: Add Support for getting all topics - Part 2

### ISSUE THREAD

**Issue by sovlful** [firebase/firebase-admin-node#1568]
#462 

are there any news about this topic?
Also, I would like to add a bit:

it would be cool if this API could return topics and the number of users subscribed to each one, in order to know which topics are more popular than others

Thank you!

**Comment by chong-shao** [comment]
Hi @sovlful thanks for the feature request! 
I think it might be better to consolidate the discussion in the original thread. Let me close this one and re-open #462 (https://github.com/firebase/firebase-admin-node/issues/462)
