### ISSUE TITLE
FR: Function to remove all users from firebase

### ISSUE THREAD

**Issue by nivida** [firebase/firebase-admin-node#157]
* Firebase SDK version: 5.5.1
* Firebase Product: admin

## Feature Request
It would be nice to have a function like ``deleteAllUsers()`` for the Admin SDK. Currently, I'm testing a user-import that runs over the Google Cloud Functions. It's a bit annoying because I have to delete all the imported users by hand after each import for testing another dataset.

**Comment by avishalom** [comment]
Note the existence of :
https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#listUsers
See usage in:
https://firebase.google.com/docs/auth/admin/manage-users#list_all_users
You can programmatically delete all users.

**Comment by hiranya911** [comment]
@bojeil-google wdyt? Is this something we should consider supporting? To me it sounds like a niche, and for those users who want it we can always suggest the solution mentioned by @avishalom above.

**Comment by bojeil-google** [comment]
Thanks for the request. I will relay this to the Auth team. +1 to @avishalom's suggestion.
I agree with @hiranya911 that this sounds like a niche. I don't think it's a common use case. Most developers that want to delete their users would typically be deleting their project. In that case, all users are automatically deleted in the process.

**Comment by nivida** [comment]
@avishalom thats my actually solution over the cloud functions 
@bojeil-google yeah it is an special use case but i think that i'm not the only one with this use case. Thank you for your reply :)

**Comment by jaroki** [comment]
I'm facing the same issue, while doing test import of several thousand users. Using the admin api to  delete them, you're quickly faced with the "Exceeded quota for deleting accounts." error message. Attempting to figure out the right amount of throttling is pain in the neck.

**Comment by erichiggins** [comment]
I ran into this same issue this week when writing a cron job to delete inactive anonymous users.

It'd be useful for the Admin SDK to provide bulk-action methods for tasks like deleting multiple users.  Even in the Firebase function samples, you can see [an example of the complexity that developers are forced to implement](https://github.com/firebase/functions-samples/blob/master/delete-unused-accounts-cron/functions/index.js#L53-L60) to work around this issue.

**Comment by bojeil-google** [comment]
Acknowledged, your concerns are valid. We have plans to provide a bulk delete API.

**Comment by mqln** [comment]
I'm also crying blood from the pain of trying to purge a test migration environment of its 300,000 users.

The max rate of 10/s is just the worst.

gimme this feature plz

**Comment by tasinsahin** [comment]
I also need this feature. In my story, my main users create  2000 sub-users in a minute programmatically.  I am facing quota problem.

**Comment by filol** [comment]
Same here

**Comment by NewITCorp** [comment]
today i just click deleting one by one in the console for 1000 test users.
looping admin.auth().deleteUser() for 1000 times always give me a timeout.

**Comment by filol** [comment]
@NewITCorp My actual solution for don't get timeout, is not perfect but it's faster than doing it yourself
```javascript
function listAllUsers(nextPageToken) {
  // List batch of users, 10 at a time.
  admin.auth().listUsers(10, nextPageToken)
    .then(function(listUsersResult) {
      listUsersResult.users.forEach(function(userRecord) {
          
        //console.log("user", userRecord.toJSON());
        admin.auth().deleteUser(userRecord.uid)
            .then(function() {
                console.log("Successfully deleted user");
            })
            .catch(function(error) {
                console.log("Error deleting user:", error);
            });

      });
      if (listUsersResult.pageToken) {
        // List next batch of users.
          //Wait because timeout
          setTimeout(listAllUsers(listUsersResult.pageToken), 2000);        
      }
    })
    .catch(function(error) {
      console.log("Error listing users:", error);
    });
}

exports.clean = functions.https.onRequest((req, res) => {
    listAllUsers();
});
```

**Comment by daviduzan** [comment]
@filol Good solution for the quota problem. 
But you need to send to `setTimout` the function name and arguments at the end:
`setTimeout(listAllUsers, 2000, listUsersResult.pageToken);`

**Comment by adihat** [comment]
solution in python:
(not the best way but does the job)
```python
import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth


creds = credentials.Certificate('/users/adarsh/Downloads/prod_firebase_cert.json')
firebase_admin.initialize_app(creds)

for user in auth.list_users().iterate_all():
    user_id = user.uid
    print('User: ', user_id)
    auth.delete_user(user_id)
print('deleted_successfully')
```

**Comment by adihat** [comment]
import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth


creds = credentials.Certificate(PATH_TO_CERT_FILE)
firebase_admin.initialize_app(creds)

for user in auth.list_users().iterate_all():
	user_id = user.uid
	print('User: ', user_id)
	auth.delete_user(user_id)
print('deleted_successfully')

**Comment by adihat** [comment]
Solution in python: (not elegent way to do it but does the job for now)

```python
import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth

creds = credentials.Certificate('path-to-cert.json')
firebase_admin.initialize_app(creds)

for user in auth.list_users().iterate_all():
    user_id = user.uid
    print('User: ', user_id)
    auth.delete_user(user_id)
print('deleted_successfully')
```

**Comment by jaycenhorton** [comment]
Here's a version of @filol 's script that's typescript compatible

```ts
const deleteAllUsers = async (nextPageToken?) => {
    // List batch of users, 10 at a time.
    const listUsersResult = await admin.auth().listUsers(10, nextPageToken);
    listUsersResult.users.forEach(async userRecord => {
      await admin.auth().deleteUser(userRecord.uid);
      console.log('Successfully deleted user');
    });
    if (listUsersResult.pageToken) {
      // Wait to delete each set of users to abide by Firebase timeout
      setTimeout(() => deleteAllUsers(listUsersResult.pageToken), 2000);
    } else {
      console.log('no more users found');
    }
};
await deleteAllUsers();
```

**Comment by ChristofferSkog21st** [comment]
Any ETA on when the bulk delete will be available?

**Comment by hiranya911** [comment]
I believe there's a new API proposal under consideration to support this, but there's no timeline for an implementation yet.

**Comment by gsunit** [comment]
You can use this: stackoverflow.com/a/56365233/8682568 This does not require the use of your browser's developers tools (which is unbearably slow). Rather, it uses Firebase Admin SDK to nuke all users quickly.

**Comment by elucidsoft** [comment]
This is by the most annoying thing ever, can you just ad a button to the admin console for god sake? Why is this so difficult?

**Comment by FunFetched** [comment]
Is anything happening on this? With anonymous login, the database fills up FAST. I have an overwhelming number of ghost accounts that I need to get rid of. Also, why on earth does listUsers() have no filters of any kind? If my service worker fails, it has to start all over again and parse through every single account, anonymous or not.

**Comment by Kronhyx** [comment]
```javascript
      let users = document.querySelectorAll('.fb-table-elem tbody[ng-repeat]')
      users.forEach(user => {
        let button = user.querySelector('md-menu > button')
        let dropdown = document.getElementById(button.getAttribute('aria-owns'))
        let removeBTN = dropdown.querySelector('md-menu-content md-menu-item:last-child > button')
        removeBTN.click()
        document.querySelector('md-dialog .fb-dialog-actions > button:last-child').click()
      })

**Comment by linhnvhicts** [comment]
It's 2020 bulk delete button should be a thing in admin console, instead of writing a script just to delete all users which take a ridiculous amount of time just to wait for them to delete all user

**Comment by TaylorAbraham** [comment]
Just stumbled into exactly this issue, would love to see a bulk delete get added.

**Comment by rsgowman** [comment]
A bulk user delete (and bulk get) feature has *just* been released in the admin sdk:

https://firebase.google.com/support/release-notes/admin/node#version_8120_-_06_may_2020

There's a few limitations worth calling out here:
* node.js only for now; other ports should be rolling out soon.
* Full documentation hasn't been published yet, but api docs can be found here: https://firebase.google.com/docs/reference/admin/node/admin.auth.BaseAuth#deleteusers
* it's limited to 1000 users per call.
* the backend rate limits this call to 1qps. (This might be relaxed in the future.)

Those last two items imply you won't be able to delete users faster than 1000 per second.

Feel free to give it a try!

**Comment by jkossis** [comment]
@rsgowman even with the new API, how is getUsers easing the burden that listUsers presented?

It seems that in order to delete users in bulk, you still need to pass uids for each user, which requires the aforementioned `getUsers`/`listUsers` calls.

**Comment by hiranya911** [comment]
@jkossis that's correct. An API that unconditionally deletes all users from a project (like the `deleteAllUsers()` API proposed by the OP) is not currently in our radar as far as I know. So you will still have to fetch UIDs via `getUsers()` or `listUsers()`. The difference is `listUsers()` + `deleteUser()` require 1001 RPC calls to delete 1000 users. Whereas `listUsers()` + `deleteUsers()` only need 2.

**Comment by jdbence** [comment]
What I'm currently doing to delete inactive anonymous users
```TS
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import { UserRecord } from 'firebase-functions/lib/providers/auth';

// At 00:00 on every 13th day-of-month.
const onUserCleanup = functions
    .runWith({
        timeoutSeconds: 540
    })
    .pubsub.schedule('0 0 */13 * *')
    .onRun(async (context) => {
        console.log('Run onUserCleanup start');
        const inactiveUsers = await getInactiveUsers();
        await deleteInactiveUsers(inactiveUsers);
        console.log('Run onUserCleanup end');
    });

async function getInactiveUsers(users: UserRecord[] = [], nextPageToken?: string): Promise<UserRecord[]> {
    const halfMonthOld = Date.now() - 15 * 24 * 60 * 60 * 1000;
    const result = await admin.auth().listUsers(1000, nextPageToken);

    // Anonymous users 15 days since last login
    const inactiveUsers = result.users.filter(
        (user) => user.providerData.length === 0 && Date.parse(user.metadata.lastSignInTime) <= halfMonthOld,
    );

    users = [...users, ...inactiveUsers];

    // More users
    if (result.pageToken) {
        return getInactiveUsers(users, result.pageToken);
    }

    return users;
}

async function deleteInactiveUsers(users: UserRecord[] = []) {
    const p = [];
    while (users.length > 0) {
        let group: string[] = users.splice(0, Math.min(users.length, 1000)).map((u) => u.uid);
        p.push(admin.auth().deleteUsers(group));
    }
    return Promise.all(p);
}

export default onUserCleanup;
```

**Comment by hiranya911** [comment]
@jdbence this solution looks pretty solid. Only thing I'd like to call out is that `deleteUsers()` is rate limited in backend for 1 call per second. So you might need to implement some logic to add some delay between calls to `deleteUsers()` in case when the `users` list is longer than 1000.

**Comment by jovansuzic** [comment]
If you have a cloud function that is triggered when the user is deleted (functions.auth.user().onDelete) it is not triggered when bulk delete is called (`deleteUsers(ids)`) whereas when calling one by one delete (`deleteUser(id)`) it is. Anyone know is this expected behavior?

**Comment by hiranya911** [comment]
@jovansuzic that could be a bug. You should report it at https://github.com/firebase/firebase-functions

**Comment by silexcorp** [comment]
#**This work for me**

- Go to your Firebase project -> Project Settings -> Service Accounts.
-     Click on Generate new Private Key to download the JSON file. Copy the path to JSON file and replace it in the code below in the path to service accounts private key json file.
-     Also, copy the databaseURL from the settings page. Replace it in the code.
-     Copy and paste the code in index.js.
-     Run in terminal node index.js. Watch the mayhem!

```var admin = require('firebase-admin');

var serviceAccount = require("/path/to/service/accounts/private/key/json/file");

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "/url/to/your/database"
});
function deleteUser(uid) {
    admin.auth().deleteUser(uid)
        .then(function() {
            console.log('Successfully deleted user', uid);
        	return null;   // add this line
        })
        .catch(function(error) {
            console.log('Error deleting user:', error);
        });
}

function getAllUsers(nextPageToken) {
    admin.auth().listUsers(100, nextPageToken)
        .then(function(listUsersResult) {
            listUsersResult.users.forEach(function(userRecord) {
                uid = userRecord.toJSON().uid;
                deleteUser(uid);
            });
            if (listUsersResult.pageToken) {
                getAllUsers(listUsersResult.pageToken);
            }
        	return null;   // add this line
        })
        .catch(function(error) {
            console.log('Error listing users:', error);
        });
}

getAllUsers();```
