### ISSUE TITLE
FR: Improve auth.createUser to support importing users from a different service

### ISSUE THREAD

**Issue by jpreynat** [firebase/firebase-admin-node#158]
After migrating our app from Heroku to a fully hosted Firebase application, we need to migrate our users database and login capabilities to this new Firebase app.
However, we want our migration to be incremental, since our DB contains 400000+ users.

We have been successfully testing this approach manually with [`firebase-tools`'s `auth:import` command](https://firebase.google.com/docs/cli/auth). However, since our migration process is meant to be totally automated and executed in a cloud function of our app, [`firebase-tools` cannot be used](https://www.npmjs.com/package/firebase-tools#using-as-a-module).

The better way for us to achieve this would be to improve the admin SDK `auth.createUser()` method, or alternatively add an `auth.importUser()` method, to support creating an user with the same set of informations than the [`auth:import` command](https://firebase.google.com/docs/cli/auth), especially the ability to pass the user's password hash instead of the unencrypted password and a prior creation date.

Ideally, this method would also allow passing the user's login providers, though this can be achieved later using the Node Firebase SDK for now.

**Comment by bojeil-google** [comment]
Similar functionality is on our list of features to support. Stay tuned.

**Comment by bojeil-google** [comment]
It's in the pipeline. A few things came up like refresh token revocation which was higher priority for security reasons.

**Comment by bojeil-google** [comment]
Hey folks, this was released yesterday: 
https://github.com/firebase/firebase-admin-node/releases/tag/v5.11.0
The guide is located here:
https://firebase.google.com/docs/auth/admin/import-users
