### ISSUE TITLE
Firebase database transaction not behaving as expected

### ISSUE THREAD

**Issue by Rofer11607** [firebase/firebase-admin-node#1588]
** I had to repost this because the person who evaluated my previous post did not look at my question closely. He said that I was using the emulator... yes I am, the screenshots are of the emulator; the document is written with the same value and not incremented.  This is not a usage question this behavior seems to directly contradict the documentation. please help.

### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Monterey 12.1
  * Firebase SDK version: firebase-admin ^9.8.0
  * Firebase Product: firestore
  * Node.js version: 16.13.2
  * NPM version: 8.1.2

** note I'm not sure this is system specific 2 of our developers have tried to make this work.

#### Steps to reproduce:

When running firebase database transactions, they fail; but no error is thrown.

#### Relevant Code:
Given the following code:
```
Code:

import * as admin from "firebase-admin";
const db = admin.firestore();

class Doc {
  first = 0;
  second = 0;
  third = 0;
  id = Math.random();
  constructor(data: any) {
    if (data) Object.assign(this, data);
    this.first += 1;
    this.second += 2;
    this.third += 3;
    console.log(this);
  }
  serialze() {
    return {
      first: this.first,
      second: this.second,
      third: this.third,
      id: this.id,
    };
  }
}

export function runSingleTransaction() {
  return db
    .runTransaction(async (transaction) => {
      const docSnapshot = await db
        .collection("transaction-test")
        .doc("base-test")
        .get();
      let doc = docSnapshot.data();
      const writeDoc = new Doc(doc);
      if (doc) transaction.update(docSnapshot.ref, writeDoc.serialze());
      else transaction.set(docSnapshot.ref, writeDoc.serialze());
      return writeDoc;
    }, {})
    .then((wd) => {
      console.log("the transaction passed");
      return wd;
    })
    .catch((err) => {
      console.log("the transaction failed");
      return err;
    });
}


Test:
  it.only("should run db transactions in practice", async () => {
    const ret = [];
    for (let i = 0; i < 10; i++) {
      const res = axios.get(
        "http://localhost:5001/guestfeedback-2f0f8/us-central1/runTransaction"
      );
      ret.push(res);
    }
    await Promise.all(ret);
  });
```

This is the output:
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/55964540/155599109-dada0007-852b-4758-94b3-cb84d051e1e3.png">

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/55964540/155599154-44b2128f-b7b9-410d-a48e-268ca914462c.png">

Expected:
In firestore we should see an increment by 10 so the property first should be 10 second should be 20 and third should be 30

In the logs we should see it fail and retry several times as writes are happening concurrently. however all logs are passing

**Comment by lahirumaramba** [comment]
Hi @Rofer11607 let's continue the discussion on #1587. I re-opened it. Thanks
