### ISSUE TITLE
database: Reference#transaction return type

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-admin-node#1606]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS
  * Firebase SDK version: 10
  * Firebase Product: database
  * Node.js version: 14
  * NPM version: 8

### [REQUIRED] Step 3: Describe the problem

The `transaction` method on a reference is typed to return `Promise<any>` as opposed to `Promise<{ committed: boolean, snapshot: DataSnapshot }>`.

https://github.com/firebase/firebase-js-sdk/blob/a7f4a2eb6ed08596dffe75825bca1a2034bfcd2e/packages/database-types/index.d.ts#L140-L144

This is the same problem in the [docs](https://firebase.google.com/docs/reference/js/v8/firebase.database.Reference#transaction).

I've already raise this in the JS SDK (firebase/firebase-js-sdk#6071) but was told it belong here - I'm not totally sure this is the case though as `firebase-admin` references `@firebase/database-types` which is in the `firebase/firebase-js-sdk` repo...

#### Steps to reproduce:

See above.

#### Relevant Code:

See above.

**Comment by lahirumaramba** [comment]
Hi @rhodgkins Thank you for reporting this. You are right, this should be addressed in `@firebase/database-types`.

@hsubox76 does this belong in the `firebase-js-sdk` repo?

**Comment by lahirumaramba** [comment]
Closing this as https://github.com/firebase/firebase-js-sdk/issues/6071 is now reopened.
