### ISSUE TITLE
[Firestore] recursiveDelete() unavailable in firebase-admin-node 10.0.2 because @google-cloud/firestore dependency is set to 4.5.0 in package.json

### ISSUE THREAD

**Issue by pureimpro** [firebase/firebase-admin-node#1609]
Hi,

please upgrade firebase-admin-node **@google/firestore dependency** from 4.5.0 to at least **4.11.0** in package.json

Have a nice day !

**Comment by lahirumaramba** [comment]
Hi @pureimpro @google-cloud/firestore is an optional dependency in Admin Node SDK so you should be able to upgrade it in your development environment to a version other than the one set in the SDK package.json. We are working on a plan to upgrade to Firestore 5.x. However, given that it is a breaking change (Firestore 5.x requires Typescript 4.1.5+) I can't currently promise you a timeline on that.

**Comment by lahirumaramba** [comment]
Fixed in: #1625

**Comment by pureimpro** [comment]
Hi @lahirumaramba,

thank you for your action and advice.
Have a great day :)
