### ISSUE TITLE
Uploading files to Firebase Storage cannot be opened 

### ISSUE THREAD

**Issue by ElihuJ** [firebase/firebase-admin-node#1613]
I have been following the documentation on how to upload files (Writing from memory) [Google Documentation](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-code-sample)[](https://i.stack.imgur.com/9hZMC.png)

So I have the following:

```javascript
await admin.storage().bucket().file("test.txt").save("Some text");
```
After this I can see my file successfully uploaded to my bucket:

<img width="1020" alt="Screen Shot 2022-03-20 at 5 01 15 pm" src="https://user-images.githubusercontent.com/30395400/159152812-3f961e6d-0cc8-4764-8c85-cc2912a10994.png">

but whenever I try to open it, it gives me an undefined URL:

https://console.firebase.google.com/project/my-project/storage/my-project.appspot.com/undefined

Which causes a redirect and I can't open the file from the the firebase console, I have also tried to make sure the file is public by running this right after the creation of the file:

```javascript
await admin.storage().bucket().file("test.txt").makePublic();
```

I have tried this from my firebase functions emulator as well as deploying it to production
Maybe I'm missing something silly here but I can't spot it

SO Link: https://stackoverflow.com/questions/71544472/how-to-upload-file-with-content-to-firebase-storage-bucket-from-firebase-functio

=================
Question originally raised on https://github.com/googleapis/nodejs-storage/issues/1818 but asked to redirect this issue to https://github.com/firebase/firebase-js-sdk/issues/6089 then redirected here

**Comment by lahirumaramba** [comment]
Hi @ElihuJ, The Admin SDK wraps the https://github.com/googleapis/nodejs-storage library and the issue should be addressed there. Sorry that you have been redirected multiple times! Based on your reply on SO it looks like you were able to fix the issue. I will close this for now and we can re-open later if needed. Thanks!
