### ISSUE TITLE
Nodejs App crashes at random

### ISSUE THREAD

**Issue by theavijitsarkar** [firebase/firebase-admin-node#1623]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macos 11.6
  * Firebase SDK version: 8.13
  * Firebase Product: messaging
  * Node.js version: 16.4.1
  * NPM version: 7.18

### [REQUIRED] Step 3: Describe the problem
My app is crashing at random times, possibly when disconnected from the network

#### Steps to reproduce:
Disconnect from network

#### Log
```
/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/utils/error.js:42
        var _this = _super.call(this, errorInfo.message) || this;
                           ^

FirebaseMessagingError: Requested entity was not found.
    at FirebaseMessagingError.FirebaseError [as constructor] (/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseMessagingError (/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/utils/error.js:254:16)
    at Function.FirebaseMessagingError.fromServerError (/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/utils/error.js:287:16)
    at Object.createFirebaseError (/Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/messaging/messaging-errors.js:34:47)
    at /Applications/MAMP/htdocs/godial-server/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:76:42
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorInfo: {
    code: 'messaging/registration-token-not-registered',
    message: 'Requested entity was not found.'
  },
  codePrefix: 'messaging'
}
```

**Comment by lahirumaramba** [comment]
Hi @theavijitsarkar it is difficult to diagnose without looking at a complete repro. Does this happen when you try to use the messaging API without a network connection? Please provide a complete code block or a project to reproduce the issue if you can (please omit any sensitive information) and we can further investigate this. Thanks!

**Comment by lahirumaramba** [comment]
Closing due of inactivity. Please let us know if you still face this problem and we can re-open later.

**Comment by Sanjeevbadnur** [comment]
Hi Team,

Issue : 
       Facing inconsistent push notifications. With same token without any changes push notifications works for some times and does not works some times.
    
Platform : Android and IOS
Codebase : node.js
Firebase-admin sdk version : 12.4.0
Node.js version: Node.JS 20

Sample node code : 
```
let message = {
  tokens: array of fcm tokens
  notification: 
    {
       title: "test_title",
       body: push notification message,
    },
  data: 
    {
       data: payload,
       alertType: "crash",
    },
};

let response = await firebaseAdmin.messaging().sendEachForMulticast(message);
``` 

The error message is random and either one of them 
1. {"success":false,"error":{"code":"messaging/mismatched-credential","message":"SenderId mismatch"}}

2. {"success":false,"error":{"code":"messaging/unknown-error","message":"Operation is not implemented, or supported, or enabled. Raw server response: \"{\"error\":{\"code\":501,\"message\":\"Operation is not implemented, or supported, or enabled.\",\"status\":\"UNIMPLEMENTED\"}}\""}}

3. {"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}}
