### ISSUE TITLE
High Severity Vulnerability on  node-forge-0.10.0.tgz (Vulnerable Library)

### ISSUE THREAD

**Issue by biswajit-ibm** [firebase/firebase-admin-node#1627]
JavaScript implementations of network transports, cryptography, ciphers, PKI, message digests, and various utilities.

Library home page: https://registry.npmjs.org/node-forge/-/node-forge-0.10.0.tgz

Path to dependency file: /package.json

Path to vulnerable library: /node_modules/google-p12-pem/node_modules/node-forge/package.json

Dependency Hierarchy:

firebase-admin-10.0.2.tgz (Root Library)
storage-5.3.0.tgz
gcs-resumable-upload-3.1.1.tgz
google-auth-library-6.1.2.tgz
gtoken-5.0.4.tgz
google-p12-pem-3.0.3.tgz
❌ node-forge-0.10.0.tgz (Vulnerable Library)

**Comment by lahirumaramba** [comment]
Admin SDK v10.0.2 is on `"node-forge": "^1.0.0"` https://github.com/firebase/firebase-admin-node/blob/5b0a49ba0dbc22dc7ef8a5646d028f1b55b3e9bc/package.json#L168

What you see could have been a cached version in your development environment or pulled by a different package. You should also be able to just update `node-forge` manually in you environment. Thanks!

**Comment by biswajit-ibm** [comment]
node-forge has a transient dependency on firebase-admin-10.0.2.tgz (Root Library) as shown in the description. I can't manually update it. For me, even after updating to 10.0.2 the node-forge version stays at 0.10.0. How do I make this work?

**Comment by lahirumaramba** [comment]
Please see my answer on https://github.com/firebase/firebase-admin-node/issues/1634
