### ISSUE TITLE
unmet peer dependency "@firebase/app-compat@0.x"

### ISSUE THREAD

**Issue by thomaswang** [firebase/firebase-admin-node#1656]
### Describe your environment

  * Operating System version: macOS Monterey v12.3.1
  * Firebase SDK version: v10.1.0
  * Firebase Product: `firebase-admin`
  * Node.js version: v17.5.0
  * Yarn version: v1.22.18

#### Steps to reproduce:

I get the following warning when installing the latest version of `firebase-admin` (10.1.0) 

```
warning "firebase-admin > @firebase/database-compat@0.1.8" has unmet peer dependency "@firebase/app-compat@0.x".
```

**Comment by hsubox76** [comment]
Same cause as https://github.com/firebase/firebase-js-sdk/pull/2082 and potentially same fix (inside the Firebase JS SDK). When transitioning from v8 to v9, app (now app-compat) was moved back into peerDependencies. I think the same conditions still exist such that we can move it back to devDependencies.

**Comment by lahirumaramba** [comment]
This should be fixed in https://github.com/firebase/firebase-js-sdk/pull/6319
Thank you!
