### ISSUE TITLE
TypeError: Cannot read property 'isJson' of undefined

### ISSUE THREAD

**Issue by Rizky-Iqbal36** [firebase/firebase-admin-node#1659]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: `node:14-alpine3.11`
  * Firebase-admin: 10.1.0
  * Firebase Product: Remote Config
  * Node.js version: 14.18.1
  * NPM version: 6.14.15

#### Steps to reproduce:

I try to fetch remote config template from firebase, it work perfecly fine on my local machine but when the API is hitted on cloud server, it got error: `TypeError: Cannot read property 'isJson' of undefined`, i use google kubernetes engine to deploy my app

#### Relevant Code:

```typescript
public async getRemoteConfig() {
      return this.remoteConfig.getTemplate().catch(err=>{
        console.log(err);
        throw new InternalServerError({detail: {err}});  
      });
  }
```

**Comment by lahirumaramba** [comment]
Hi @Rizky-Iqbal36 could you provide a minimal code/project to reproduce this issue so we can further investigate it? Our nightly tests for Remote Config API currently do not show any errors.
Since you log the error in your code `console.log(err), do you see any error responses from the Remote Config API? This could also be an issue when you parse the error response in your custom class `InternalServerError()`.

**Comment by Rizky-Iqbal36** [comment]
sure @lahirumaramba, in order to be able to connect my server app with firebase, i create firebase adapter class that look like this

```typescript
class FirebaseAdapter {
  private readonly remoteConfig: firebaseAdmin.remoteConfig.RemoteConfig;

  constructor(private readonly firebaseApp:firebaseAdmin.app.App) {
    this.firebaseApp = firebaseApp;
    this.remoteConfig = this.firebaseApp.remoteConfig();
  }

  public async getRemoteConfig() {
    return this.remoteConfig.getTemplate().catch((err)=>{
      console.log(err);
      throw new InternalServerError({detail: {err}});
    });
  }
}

export default new FirebaseAdapter(
    firebaseAdmin.initializeApp({
      credential: firebaseAdmin.credential.cert({
        clientEmail: config.firebase.clientEmail,
        privateKey: config.firebase.privateKey.replace(/\\n/g, '\n'),
        projectId: config.firebase.projectId,
      }),
    }),
);
```
and here is the error that i got from terminal:
<img width="1147" alt="Screen Shot 2022-04-26 at 08 43 20" src="https://user-images.githubusercontent.com/70442114/165203571-7d8596f7-ad0d-4511-a9f1-2182acb6cab5.png">

Note: i already got the same error before i parse the error response to my custom class

**Comment by Rizky-Iqbal36** [comment]
I'm gonna close this issue, i found the problem, the private key i use on cloud environment is including double quote

**Comment by matthewp672261** [comment]
Hopefully this helps someone else. I was seeing this exact error using v9.12.0 of the SDK. Everything worked just fine locally, but I was seeing this error in our Heroku app logs. After looking at the following discussion, I rolled the Heroku stack from "Heroku-22" >> "Heroku-20" which fixed the issue. According to the below, Ubuntu v22 is the issue.

https://github.com/nodejs/node/discussions/43184
