### ISSUE TITLE
Not clear how to set channel for messaging

### ISSUE THREAD

**Issue by esprehn** [firebase/firebase-admin-node#168]
There's value mentions of android_channel_id in some stackoverflow posts, but nothing in the docs or in this repo. How do you set the channel? The console has a field for it even though the API makes no mention of it.

**Comment by hiranya911** [comment]
`NotificationMessagePayload` type is defined as follows:

```
type NotificationMessagePayload = {
    tag?: string;
    body?: string;
    icon?: string;
    badge?: string;
    color?: string;
    sound?: string;
    title?: string;
    bodyLocKey?: string;
    bodyLocArgs?: string;
    clickAction?: string;
    titleLocKey?: string;
    titleLocArgs?: string;
    [key: string]: string | undefined;
  };
```

Since it allows arbitrary keys, I would expect that if you just add `android_channel_id` under notification, it will just work.

**Comment by esprehn** [comment]
Can something be added to the docs? It's strange the web console has a field for this and nothing is mentioned in the docs for how to do it programmatically.

**Comment by hiranya911** [comment]
You can still use the [legacy APIs](https://firebase.google.com/docs/cloud-messaging/admin/legacy-fcm) for this. The new REST API doesn't support it as far as I can tell: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidConfig

SDK's `admin.messaging.send()` API cannot support it until it's exposed in the REST interface.

**Comment by Stefan300381** [comment]
hey guys, bringing this old thread back to live. it took me a few days to find out how to use firebase admin sdk with node.js and assign a channel ID to a notification. thanks for the post above I just added "android_channel_id" to my notification payload object, see below.

It works, but is it the correct way?

```
                        //prepare firebase cloud messaging push notification
                        var notification_message =  {                                                                                                             notification: {
                                        title: topic.toString(),                                                                                                          body: message.toString(),
                                        android_channel_id: config.mqtt_subscriptions[index].channelID
                                }
                        };
```

**Comment by hiranya911** [comment]
That looks correct for the legacy API.

Channel ID is also supported by the new (v1) API now: https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidNotification#optional-channelid
