### ISSUE TITLE
Admin SDK orderByChild().equalTo sometimes returns null

### ISSUE THREAD

**Issue by deremer** [firebase/firebase-admin-node#169]
Originally raised on SO at: https://stackoverflow.com/questions/47931563/admin-sdk-orderbychild-equalto-sometimes-returns-null

We have a fixed list of data where each item in the list has a display_date in a format like this...

![image](https://user-images.githubusercontent.com/772290/34390100-8ef6cbe2-eb0b-11e7-8ba1-c5f3111523d8.png)

We run a query to retrieve results that have a display_date equal to the date string we are looking for.

Using typescript and the Firebase Admin node.js SDK, the code looks like this:

```
let trivia = (await admin.database().ref('trivia/GLOBAL')
  .orderByChild('display_date')
  .equalTo(triviaDate)
  .once('value')).val()

if (isNil(trivia)) {
  throw new NotFoundError(`No trivia questions found for ${triviaDate}`)
} else {
  return trivia;
}
```
(Note that isNil() is from lodash.)

The weird part is that for 1000's of runs this works perfectly. But for a very small fraction, it throws the NotFoundError. We have confirmed that the value of triviaDate is correct and there should be results. It's as if the first 'value' returned is null sometimes and in an inconsistent way.

As an update to the SO post, we added a check where if the first time it returns null we attempt to do it again before throwing the error indicating we have null. And, we are still seeing it return null the second time. In fact, it has happened 59 times in the last 24 hours, and we have had 49k+ invocations of the cloud function that executes this code. That means it's happening 0.12% of the time. Very small, but I'd expect a range query on a db to _always_ return the same result.

Any ideas?

**Comment by hiranya911** [comment]
Database code resides at https://github.com/firebase/firebase-js-sdk. Please report this there.
