### ISSUE TITLE
Suddenly getting "Request contains an invalid argument" for sending notifications, it was working before

### ISSUE THREAD

**Issue by PaulvanMotman** [firebase/firebase-admin-node#1694]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google App Engine (F4_1G)
  * Firebase SDK version: 10.0.2
  * Firebase Product: firebase-admin/messaging
  * Node.js version: 14
  * NPM version: v6.14.17

#### Steps to reproduce:

I’m sending push notifications to both iOS/android devices, looking at my analytics it seems that the iOS notifications are not arriving anymore. I’m getting messaging/invalid-argument, with errorMessage: Request contains an invalid argument. The notifications I’m sending look like this:  
```
{
              notification: { 
                title: 'alarmName', 
                body: 'pushMessage',
              },
              data: {
                uid: 'user_id'
              },
              apns: {
                payload: {
                  aps: {
                    badge: 2,
                  },
                },
              },
              android: {
                priority: 'high',
                notification: {
                    sound: 'default',
                    notification_priority: 'PRIORITY_HIGH',
                    visibility: 'public'
                }
              },
              token: 'fcm_token',
}
```

There is an array of messages like this, I’m sending with messaging.sendAll(). I’m sending these messages on a daily basis, the issue started on the 9th of May. Anything changed in the firebase sdk, or perhaps apple side?

**Comment by chong-shao** [comment]
Hello @PaulvanMotman I would suggest contact Firebase support https://support.google.com/firebase/?hl=en where you can share your details including Firebase project number and the support team will help the debugging. Thanks!

**Comment by PaulvanMotman** [comment]
@chong-shao You linked to a FAQ, there is no form to file a bug report?

**Comment by chong-shao** [comment]
Hello @PaulvanMotman , apologies. https://firebase.google.com/support/troubleshooter/fcm/delivery would be the correct link.

**Comment by PaulvanMotman** [comment]
Great @chong-shao , thank you!

**Comment by ayZagen** [comment]
I also face with this while sending to iOS devices with following `apns` config: 
```
{
  payload: {
    aps: {
      contentAvailable: true,
    },
  },
  headers: {
    "apns-priority": "10",
    "apns-push-type": "background",
  },
}
```
it works for android targets.
