### ISSUE TITLE
Missing export for functions and getFuncitons

### ISSUE THREAD

**Issue by gitdast** [firebase/firebase-admin-node#1704]
### [REQUIRED] Step 2: Describe your environment

Windows, Node.js
Firebase SDK version: latest firebase-admin = 10.2.0
Firebase Product: Cloud Functions (+ Auth, Firestore,...)
Node.js version: 16
NPM version: 8.1.0

### [REQUIRED] Step 3: Describe the problem
I want to use TaskQueue with Cloud Functions as described here https://firebase.google.com/docs/functions/task-functions,
but neither firebase-functions SDK v3.21.1 nor firebase-admin SDK v10.2.0 has export for all described functions.
**There is missing export for getFunctions in firebase-admin v10.2.0.**
(Why is not TaskQueue related stuff present in firebase-functions SDK and we have to use two SDK in CF...that's another question.)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
```
import {getFunctions} from 'firebase-admin' - this will never work
```

**Comment by gitdast** [comment]
I have found an option how to import by 
```
import {getFunctions} from 'firebase-admin/functions';
```
but there is another issue - this function getFunctins has no option to specify the `region` - so all queues must be in us-central1 ?

**Comment by lahirumaramba** [comment]
Hi @gitdast ,

You are correct, the right way to import `functions` types is 
```
import { getFunctions, TaskOptions } from 'firebase-admin/functions'
```

The default `region` is `us-central1`, but you can specify a different region in the `getFunctions().taskQueue()` API by passing it in the function resource name. 

```
getFunctions().taskQueue('locations/{location}/functions/{functionName}')
```

See the reference docs for more information:
https://firebase.google.com/docs/reference/admin/node/firebase-admin.functions.functions#functionstaskqueue

**Comment by gitdast** [comment]
Thank you, it was hard to find these two information.
Maybe consider exposing getFunctions from the top module and unify the syntax with the firebase SDK... 
![image](https://user-images.githubusercontent.com/4412816/168654082-98322f76-80a4-4c2a-931f-587b736a4eab.png)

**Comment by gijo-varghese** [comment]
@dastrouvy upgrading to firebase-admin to latest fixed the issue.

**Comment by ShanahJr** [comment]
> @dastrouvy upgrading to firebase-admin to latest fixed the issue.

This worked for me as well.

**Comment by ShanahJr** [comment]
Upgrading to the latest firebase-admin (11.1.0) allowed me to access the queueing functions it is incompatible with the latest firebase-functions (3.24.1). Breaking changes for me
