### ISSUE TITLE
firebase-admin snyk issues

### ISSUE THREAD

**Issue by harshagarwal00** [firebase/firebase-admin-node#1718]
Snyk is throwing a warning how to fix it ?
Link: https://snyk.io/test/npm/firebase-admin/10.2.0

node: v16.14.2
npm: 8.5.0

**Comment by harshagarwal00** [comment]
This is duplicate of https://github.com/firebase/firebase-admin-node/issues/1512
But needs a fix.. cant believe above issue got ignored for 5 months :)

**Comment by lahirumaramba** [comment]
Thank you @harshagarwal00 for reporting this issue.
The Admin Node.js SDK uses `dicer` to parse multipart responses from Firebase and GCP backend servers.
https://github.com/firebase/firebase-admin-node/blob/94dd7c3efb9ff00b0462cf772b803d6abecc2dcc/src/utils/api-request.ts#L592
IIUC the threat introduced by the vulnerability in `dicer` is pretty low here as we can trust the responses from the BE servers. However, if you are using the `dicer` package to parse responses in your own code then you might be at a higher risk. Having said that, we are looking into the fixes mentioned in #1512 and the potential to use the fixed version of dicer in Admin SDK. I will use this issue to update the progress.

**Comment by fbartho** [comment]
Thanks @lahirumaramba -- I recognize this is a low vulnerability point, but given that Github/Dependabot are alerting, it'd be great to address this issue permanently.

**Comment by Corrob** [comment]
Another reason to fix this quickly is that some people block our releases on "npm audit" results to make sure we don't have high vulnerabilities in our release build. Currently, our releases are blocked or must be worked around until firebase-admin stops being reported as being with a high vulnerability in the audit.

**Comment by samarpanB** [comment]
Rightly said @Corrob . We are also facing the same issue. We are blocked for deployment on production environment because of `npm audit` failing and snyk also failing. Reason is this issue only. How soon can we fix it ?

**Comment by harshagarwal00** [comment]
@lahirumaramba : brilliant but its not tagged in release... by when will we get that :) 
waiting to import the fix
thanks!!!

**Comment by lahirumaramba** [comment]
This should be fixed in v10.3.0. Thanks everyone for you patience while we were working on the fix.

**Comment by Diribar** [comment]
The alert is still showng, both in Github and nodejs. Do you have any news about the solution?

**Comment by ellie-ochieno** [comment]
Because multer vulnerability issue was being classified as severity:high in my nodejs application, i resolved to use a lightweight version "busboy": "^1.6.0" as an alternative and all seemed to work well.
