### ISSUE TITLE
npm install reports high severity vulnerability of dicer in firebase-admin 10.2.0

### ISSUE THREAD

**Issue by owaineevans** [firebase/firebase-admin-node#1727]
### Describe your environment

  * Operating System version: debian stable
  * Firebase SDK version: 10.2.0
  * Firebase Product: firebase-admin
  * Node.js version: 18
  * NPM version: 8.11.0

### Describe the problem

`npm install` reports:
```
2 high severity vulnerabilities
```
`npm audit` reports:
```
npm audit
# npm audit report

dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
fix available via `npm audit fix --force`
Will install firebase-admin@7.0.0, which is a breaking change
node_modules/dicer
  firebase-admin  >=7.1.0
  Depends on vulnerable versions of dicer
  node_modules/firebase-admin

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

#### Steps to reproduce:

1) Create a project.
2) Run `npm install firebase-admin`
3) Run `npm audit`

#### Relevant Code:

```
{
    "name": "audit",
    "main": "lib/index.js",
    "scripts": {
        "start": "node lib/index.js",
    },
    "dependencies": {
        "firebase-admin": "^10.2.0",
    },
    "devDependencies": {
        "@types/node": "^17.0.21",
        "typescript": "^4.5.4"
    },
    "engines": {
        "node": "18.x"
    },
    "private": true
}

```

**Comment by owaineevans** [comment]
Whoops - duplicate of https://github.com/firebase/firebase-admin-node/issues/1718 Sorry!

**Comment by taishi55** [comment]
Hi @owaineevans, 

I'm having the same issue!
Did you find a solution for this?

**Comment by PedroEmanuelMoreiraCarvalho** [comment]
I'm with the exactaly same issue :/ some help?

**Comment by taishi55** [comment]
@PedroEmanuelMoreiraCarvalho 

[This post](https://github.com/firebase/firebase-admin-node/issues/1718#issuecomment-1137874274) seems the only related comment I found so far. But I still have no idea to fix the error. Let me know if you find something!
