### ISSUE TITLE
Crash in HeaderParser in dicer

### ISSUE THREAD

**Issue by kirank21** [firebase/firebase-admin-node#1729]
Installed package firebase-admin@^10.0.2 which has dependency upon dicer "^0.3.0".

GitHub Advisory has notified me regarding the Crash in HeaderParser in dicer with High severity status.

Please help me fix this security issue.

<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/73246713/170628265-3f05e5e7-3c7f-4b93-8cd0-4ace57d75461.PNG">

**Comment by BowTiedSwan** [comment]
Hi team, this issue seems to be critical as the dicer package hasn't had a patch fixing it:
![image](https://user-images.githubusercontent.com/86532747/170657401-5f5e3a18-2ed0-4746-a628-b3170d8dc512.png)

**Comment by mgav** [comment]
"…affects all versions of package dicer." 

Running "npm audit report" for me yields:

```dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
fix available via `npm audit fix --force`
Will install firebase-functions@2.3.1, which is a breaking change
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/busboy
    @apollographql/graphql-upload-8-fork  *
    Depends on vulnerable versions of busboy
    node_modules/@apollographql/graphql-upload-8-fork
      apollo-server-core  2.21.0-alpha.0 - 2.25.4
      Depends on vulnerable versions of @apollographql/graphql-upload-8-fork
      node_modules/apollo-server-core
        apollo-server-express  2.0.1 || 2.21.0-alpha.0 - 2.25.4
        Depends on vulnerable versions of apollo-server-core
        node_modules/apollo-server-express
          @vue/cli-ui  >=5.0.0-alpha.0
          Depends on vulnerable versions of apollo-server-express
          node_modules/@vue/cli-ui
            @vue/cli  >=5.0.0-alpha.0
            Depends on vulnerable versions of @vue/cli-ui
            node_modules/@vue/cli
  firebase-admin  >=7.1.0
  Depends on vulnerable versions of dicer
  node_modules/firebase-admin
    firebase-functions  >=3.0.0
    Depends on vulnerable versions of firebase-admin
    node_modules/firebase-functions

9 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force```

**Comment by Kondamon** [comment]
It seems it will be not fixed in dicer: https://github.com/mscdex/dicer/pull/22
However, a fix is on going in multer https://github.com/expressjs/multer/pull/1097

**Comment by Kondamon** [comment]
Duplicate of #1512

**Comment by mgav** [comment]
> Duplicate of #1512

FYI, that issue was opened Dec 4, 2021

**Comment by lahirumaramba** [comment]
Please see my reply to https://github.com/firebase/firebase-admin-node/issues/1718#issuecomment-1137874274
The Admin Node.js SDK uses `dicer` to parse multipart responses from Firebase APIs so the risk here is pretty minimal. However, I agree that it would be great to address this properly. We are currently looking into the available options.

I am going to close this issue as we will continue to track this in #1718. Thanks everyone.

**Comment by RoadAssist** [comment]
Is there any workaround available guys ?
