### ISSUE TITLE
[Firestore] Boolean values defaulting to false in set method

### ISSUE THREAD

**Issue by jadonhansen** [firebase/firebase-admin-node#1738]
### [READ] Step 1: Are you in the right place?

**Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.**

If you still think the problem is related to the code in this repository, then read on.

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Monterey 12.3.1
  * Firebase SDK version: firestore-admin: 10.2.0
  * Firebase Product: Firestore
  * Node.js version: 14.18.0
  * NPM version: 6.14.15

### [REQUIRED] Step 3: Describe the problem
I am calling a specific cloud function from the client app. This function is taking a data object and setting it as the property of another object. The final object will be a new firestore document which is created/updated using the `.set()` method with `merge = true`.

Inside the original data object there is a field called `purchase_usability`, a boolean, which must be set as true. However, once saved, the document in firestore always shows it as 'false'.

#### Steps to reproduce:

Check the code below to reproduce. Note that `apple_data` is the data object I was referring to and contains `purchase_usability: true`.
I have tried this client side using react-native-firestore and it works. Admin sdk or node sdk must have differences?

#### Relevant Code:

```
exports.mergeUserDoc = async function mergeUserDoc(uid, email, apple_data, process) {
	let userObj;

	if (process == "login") {
		userObj = {
			device_os: "ios",
			apple_data: apple_data,
		};
	} else {
		userObj = {
			user_email: email,
			user_creation_datetime: admin.firestore.Timestamp.fromDate(new Date()),
			device_os: "ios",
			apple_data: apple_data,
			gplay_data: { purchase_usability: false },
		};
	}

	try {
		await admin.firestore().collection(FIREBASE_USERS_COLLECTION).doc(uid).set(userObj, { merge: true });
		return userObj;
	} catch (error) {
		logger.error(`mergeUserDoc: ${error}`);
	}
	return null;
}
```

**Comment by lahirumaramba** [comment]
Hi @jadonhansen, Cloud Firestore support is provided by the [@google-cloud/firestore](https://npmjs.com/package/@google-cloud/firestore) library. Please directly report this at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo. Thanks!
