### ISSUE TITLE
Unit Test: FirebaseTokenGenerator verifyIdToken failed on Node.js 8

### ISSUE THREAD

**Issue by micksatana** [firebase/firebase-admin-node#174]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: OS X
  * Firebase SDK version: 5.7.0
  * Library version: google-auth-library 0.12.0
  * Firebase Product: auth
  * Node.js version: 8.9.0

#### Steps to reproduce:
 * Checkout the project from master
 * Install node modules 
    ```
    npm install
    ```
 * Run test
    ```
    npm run test:unit
    ```
 * Error occurs

```
  1) FirebaseTokenGenerator verifyIdToken() "after each" hook for "should be rejected given an ID token with a kid which does not match any of the actual public keys":

      AssertionError [ERR_ASSERTION]: Mocks not yet satisfied:
GET https://www.googleapis.com:443/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
      + expected - actual

      -false
      +true
      
      at Scope.done (node_modules/nock/lib/scope.js:158:10)
      at test/unit/auth/token-generator.spec.ts:419:66
      at arrayEach (node_modules/lodash/lodash.js:537:11)
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at Context.<anonymous> (test/unit/auth/token-generator.spec.ts:419:9)
```

#### Relevant Code:
[test/unit/auth/token-generator.spec.ts#L419](https://github.com/firebase/firebase-admin-node/blob/master/test/unit/auth/token-generator.spec.ts#L419)

**Comment by hiranya911** [comment]
We've seen this on Node 9, but not on 8 -- https://travis-ci.org/firebase/firebase-admin-node/jobs/313749376

In any case I believe it's a problem with tests/mocks rather than an actual bug. Will keep an eye on for it. If you have any suggestions as to how to fix it, please share with us.

**Comment by hiranya911** [comment]
I'm going to resolve this as cannot reproduce. We regularly test on Node 8 now (#175), and CI hasn't detected any issues in unit tests for Node 8.
