### ISSUE TITLE
adding firebase-admin failing npm install

### ISSUE THREAD

**Issue by dosapati** [firebase/firebase-admin-node#177]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: __MAC OS___
  * Firebase SDK version: ___5.7.0__
  * Library version: _____
  * Firebase Product: _messaging____ (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
npm install is failing
npm install --save firebase-admin
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "firebase-admin"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dosapati/Developer/NodeJS/powerup-nodejs/npm-debug.log
#### Steps to reproduce:
add firebase-admin to the project and the "npm install fails"
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
npm install --save firebase-admin
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "firebase-admin"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dosapati/Developer/NodeJS/powerup-nodejs/npm-debug.log
#### Relevant Code:
npm install --save firebase-admin
```
// code here to reproduce the problem
just use "npm install --save firebase-admin"

**Comment by hiranya911** [comment]
This is likely an issue in your environment (or your package.json file). Works fine in the 2 environments I tested (Mac and Linux). For instance:

```
$ node --version
v6.10.3
$ npm --version
5.5.1
$ npm install --save firebase-admin

> grpc@1.7.3 install ~/Projects/firebase-admin-node/temp/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "~/Projects/firebase-admin-node/temp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node" is installed via remote

> grpc@1.7.3 install ~/Projects/firebase-admin-node/temp/node_modules/@google-cloud/common-grpc/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "~/Projects/firebase-admin-node/temp/node_modules/@google-cloud/common-grpc/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node" is installed via remote

> grpc@1.7.1 install ~/Projects/firebase-admin-node/temp/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "~/Projects/firebase-admin-node/temp/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64/grpc_node.node" is installed via remote

> protobufjs@6.8.4 postinstall ~/Projects/firebase-admin-node/temp/node_modules/google-gax/node_modules/protobufjs
> node scripts/postinstall

npm WARN saveError ENOENT: no such file or directory, open '~/Projects/firebase-admin-node/temp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '~/Projects/firebase-admin-node/temp/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

+ firebase-admin@5.7.0
added 549 packages in 11.718s
```

**Comment by dosapati** [comment]
this is a issue resulted due to a major incident happened at npm registry


Several Packages Missing from the Registry
--
Incident Report for npm, Inc.


Identified
--
Several packages including "require-from-string" are currently unavailable. We are aware of the issue and are working to restore the affected user and packages. Please do not attempt to republish packages, as this will hinder our progress in restoring them.
Jan 6, 19:45 UTC

Closing this as its working now.

**Comment by pimatco** [comment]
Not working, I'm having the same problem
