### ISSUE TITLE
[FR] Documentation on using impersonation with Realtime Database Emulator

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-admin-node#1777]
**Is your feature request related to a problem? Please describe.**

I'd like to use `firebase-admin` for testing of Firebase Realtime Database access rules. I'm not sure how to intialize the library, to make it reliably connect to the emulator.

Documentation has [Authenticate with limited privileges](https://firebase.google.com/docs/database/admin/start#authenticate-with-limited-privileges) but the samples it gives are real-world, not emulator URLs.

**Describe the solution you'd like**

Documentation showing the initialization steps that work with Firebase Realtime Database emulator.

**Describe alternatives you've considered**

I think I had this code working, but now it fails.

```
const databaseURL = `http://localhost:6800?ns=demo-2`;

const app = admin.initializeApp({
  databaseURL,
  databaseAuthVariableOverride: { uid },
  projectId
});
```

Gives (`firebase-admin` 11.0.0):

```
Error: Client is offline.
```

I'll keep looking and post here if I find something that works.

---

Related: 
- [RTDB emulator doesn't work properly with databaseAuthVariableOverride](https://github.com/firebase/firebase-tools/issues/2554) (`firebase-tools` GitHub Issues)

**Comment by rhodgkins** [comment]
There's already [documentation](https://firebase.google.com/docs/emulator-suite/connect_rtdb#admin_sdks) for this?

**Comment by akauppi** [comment]
Thanks, @rhodgkins 

I believe this is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/6390 .
