### ISSUE TITLE
Getting "Client is offline" error reading from Realtime Database after upgrading to 11.0.0

### ISSUE THREAD

**Issue by Hivemind9000** [firebase/firebase-admin-node#1780]
Environment:

Firebase SDK version: 11.0.0
Firebase Product: database
Node.js version: 14

Problem:

After upgrading to 11.0.0 I started to get the error "Client is offline" when reading from the Realtime Database. The cloud function that threw the issue had not been changed for months. When I reverted back to 10.2.0 (the version I was on previously) the problem disappeared.

The relevant line of code was:
```
const sysCtlDS = await admin.database().ref('/system/directive/status').get();
```

I tried a solution from Stackoverflow, but instead of getting the "Client is offline" error, the cloud function just hung on that request and timed out.
```
const sysCtlDS = await admin.database().ref('/system/directive/status').once('value');
```

Any ideas as to why this is occurring?

**Comment by lahirumaramba** [comment]
Following are the changes in `firebase/database` packages from `firebase-admin 10.2.0` to `11.0.0`.
v10.2.0 `firebase-admin`:
```
v11.0.0 `firebase-admin`:
```
"@firebase/database-compat": {
      "version": "0.2.1",
      "requires": {
        "@firebase/component": "0.5.15",
        "@firebase/database": "0.13.1",
        "@firebase/database-types": "0.9.9",
        "@firebase/logger": "0.3.3",
        "@firebase/util": "1.6.1",
        "tslib": "^2.1.0"
      }
    },
```
