### ISSUE TITLE
Differentiating between invalid and expired tokens when verifying

### ISSUE THREAD

**Issue by simenbrekken** [firebase/firebase-admin-node#179]
### Environment

  * Operating System version: MacOS High Sierra 10.13.1 (17B1003)
  * Firebase SDK version: 5.7.0
  * Library version: 5.7.0
  * Firebase Product: auth

### Description

There's currently no robust way to detect if an id token is invalid or has expired when performing verification via `auth().verifyIdToken` other than checking if the actual `error.message` contains the string "expired". 

The [`verifyIdToken` implementation of `token-generator`](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/token-generator.ts#L227-L236) correctly detects expired tokens by checking for `error.name === 'TokenExpiredError'` but this error code is discarded as it's rejected as an `FirebaseAuthError` with the `AuthClientErrorCode.INVALID_ARGUMENT` error code.

Would it be possible to to add something like `AuthClientErrorCode.TOKEN_EXPIRED` or expose the original `error.name` as `error.errorInfo.name`?

I'd be glad to contribute a PR for any of the above propsals.

**Comment by hiranya911** [comment]
Sounds reasonable to me. @bojeil-google what do you think? Shall we introduce a new `auth/id-token-expired` error code? (we already have `auth/id-token-revoked`, so there's precedent for something like this)

**Comment by bojeil-google** [comment]
In general, I think it is a good idea but I think this could be a breaking changes. Developers may be expecting the current error code for both. If we add a new error code, they would basically miss it (they won't be catching it). I suggest we keep this until the next major version bump.

**Comment by simenbrekken** [comment]
While waiting for the next major version bump would it be possible as per my second suggestion to surface the original `TokenExpiredError` as `error.errorInfo.name` in the meantime?

**Comment by hiranya911** [comment]
It's going to be hard to justify an API change that will become unnecessary a few months later. What if we modify the error message (`errorInfo.message`) to some constant value for the moment?

**Comment by simenbrekken** [comment]
How about `${message} (auth/id-token-expired)` so the same constant can be reused when it's introduced as a separate error type?

**Comment by hiranya911** [comment]
Yes, that sounds reasonable. @simenbrekken would you be able to give us a patch?

**Comment by simenbrekken** [comment]
Certainly. I'll have a patch ready this weekend.

**Comment by vlapo** [comment]
Is this change still on roadmap? I see major release is out and this issue is closed but `auth/id-token-expired` error code is not implemented.

**Comment by hiranya911** [comment]
It's still on roadmap. Just haven't gotten around to it yet.
