### ISSUE TITLE
serverTimestamp is undefined after upgrading from v10 to v11

### ISSUE THREAD

**Issue by abedzantout** [firebase/firebase-admin-node#1799]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 12.4
  * Firebase SDK version: 11
  * Firebase Product: admin and functions (auth, database, storage, etc)
  * Node.js version: ^16
  * NPM version: ^8

### [REQUIRED] Step 3: Describe the problem

Upgrading from v10 to v11 breaks admin.firestore.FieldValue.serverTimestamp(); functionality.

#### Steps to reproduce:

Run any set, add, update on collection, and include a timestamp on cloud function.

Downgrading back to v10 works.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

`TypeError: Cannot read properties of undefined (reading 'serverTimestamp')`

#### Relevant Code:

```
`collection('any').add({createdAt: admin.firestore.FieldValue.serverTimestamp()})` 
```

I apologize if this was mentioned somewhere else or if there are migration steps in the changelog.

**Comment by redpandatronicsuk** [comment]
I get the same, all of `admin.firestore.FieldValue` is undefinded.

**Comment by redpandatronicsuk** [comment]
Importing like this seems to work: `import { FieldValue } from 'firebase-admin/firestore';`

**Comment by abedzantout** [comment]
Yes @lahirumaramba, this does seem to fix the issue.

Thank you!

Closing issue.

**Comment by ishowta** [comment]
`admin.firestore.FieldValue` should not be called. There seems to be a discrepancy between `default-namespace.js` and `default-namespace.d.ts`.

**Comment by Yayo-Arellano** [comment]
I am having the same issue. Importing like this `import { FieldValue } from 'firebase-admin/firestore';` works but it looks like a workaround instead of a solution.

**Comment by ishowta** [comment]
A similar issue is discussed here https://github.com/firebase/firebase-admin-node/discussions/1959
