### ISSUE TITLE
[Firestore] Timestamp.now() not working after upgrading to v11.0.0

### ISSUE THREAD

**Issue by wolfbane** [firebase/firebase-admin-node#1804]
* Operating System version: macOS 12.4
  * Firebase SDK version: 11.0.0
  * Firebase Product: Firestore
  * Node.js version: 16

After update of firebase-admin getting runtime error "cannot read property 'now' of undefined". Seeing [similar](https://github.com/firebase/firebase-admin-node/issues/1803) issues but the suggested solution isn't valid as my codebase does not support modules: 

`Error: Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module`

Steps to reproduce:
const admin = require("firebase-admin");
const ts = admin.firestore.Timestamp;
const newTS = ts.now();

**Comment by tommyzat** [comment]
Hello, how did you fix this?

**Comment by wolfbane** [comment]
@tommyzat I updated my include to: 

`const { Timestamp: ts } = require("firebase-admin/firestore");`
`const newTS = ts.now();`
