### ISSUE TITLE
When trying to create a firestore index through a the error generated link shows "Uh oh, something went wrong"

### ISSUE THREAD

**Issue by haris-wilson** [firebase/firebase-admin-node#1805]
Firebase SDK version: 11.2.1
  Firebase Product: Firestore
  Node.js version: v16.13.2
  NPM version: 8.3.0

What happened? How can we make the problem occur?
![Screenshot (147)](https://user-images.githubusercontent.com/65351245/178149613-d5b7c356-ccab-41e8-9647-b716e85f5b92.png)

**Comment by s1davide** [comment]
The same issue :(

**Comment by 345ml** [comment]
I encountered the same symptoms.

Hypothesis.
Array index target is too big data?

**Comment by pespiritu25** [comment]
getting the same issue, I notice we have similar index that its trying to generate

![image](https://user-images.githubusercontent.com/59666660/203868852-c108262e-9b0c-43cc-8008-53be4d8714e7.png)

**Comment by lahirumaramba** [comment]
Hey @haris-wilson This is the repo for the Firebase Admin Node.js SDK.
What Firebase Admin Node.js SDK version are you using? The issue mentions `11.2.1` but that version was [released](https://firebase.google.com/support/release-notes/admin/node#version_1121_-_10_november_2022) in November 2022.

Are you experiencing this issue when using Firebase Admin Node.js SDK? Could you provide us with a sample code or minimal repro so we take a look? Thanks!

**Comment by 345ml** [comment]
@lahirumaramba 
Oh, sorry.
This may not be the right place to address this issue.
In my case this occurred when indexing from the web console.
