### ISSUE TITLE
Random grpc "Stream removed" in cloud function

### ISSUE THREAD

**Issue by edjayks** [firebase/firebase-admin-node#184]
### [READ] Step 1: Are you in the right place?
YES

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Firebase Cloud Function
  * Firebase SDK version: 5.8.0
  * Library version: _____
  * Firebase Product: Firestore

### [REQUIRED] Step 3: Describe the problem
Querying firestore document from cloud function sometimes results in "Stream removed" error, and the discussion here: https://groups.google.com/forum/#!topic/firebase-talk/oza-JZMtXlo seems to have found a solution which is available on @google-cloud/firestore version 0.10.1.

Current firebase-admin-node repository is only dependant on @google-cloud/firestore 0.10.0, is there any plan to upgrade the version? If so, when will you plan to do so?
I would be more than happy to submit a pull request (if i may do so).

#### Steps to reproduce:
Please refer here: https://groups.google.com/forum/#!topic/firebase-talk/oza-JZMtXlo

**Comment by hiranya911** [comment]
See #182
