### ISSUE TITLE
Package path ./standalone is not exported from package database-compat

### ISSUE THREAD

**Issue by ArchyInUse** [firebase/firebase-admin-node#1855]
### Background
Hello everyone, I've just installed the admin SDK and it's bringing me the following error:
```
error - ./node_modules/firebase-admin/lib/app/firebase-namespace.js:106:0
Module not found: Package path ./standalone is not exported from package D:\NewRepos\1d3a\node_modules\@firebase\database-compat (see exports field in D:\NewRepos\1d3a\node_modules\@firebase\database-compat\package.json)

Import trace for requested module:
./node_modules/firebase-admin/lib/default-namespace.js
./node_modules/firebase-admin/lib/index.js
./lib/firebaseAdminSdk.ts
```

I've found [this StackOverflow post](https://stackoverflow.com/questions/71956447/module-not-found-error-due-to-a-file-not-being-exported-from-firebase-database) regarding this, but he has not gotten answers.
The only other information I have on this error is that this warning comes up when checking the relevant package's package.json file:
![image](https://user-images.githubusercontent.com/40056705/183161662-f94c7627-dbc4-49ab-8ae1-5ce46bbc12c5.png)

#### Relevant Code:

```
import { initializeApp, apps, app } from 'firebase-admin';
import { credential } from "firebase-admin"

var firebaseAdminAccount = require("../serviceAccount.json");

var FbApp : app.App = null;

if(!apps.length)
{
  FbApp = initializeApp({
    credential: credential.cert(firebaseAdminAccount)
  })
}

if(FbApp === null)
{
  FbApp = apps[0];
}

export default FbApp;
```
This code is for getting the admin SDK in my backend, and not trying to initialize it twice.
It's important to note, this crashes **at the imports, and not the code itself.**

does anyone know how to fix this? I cannot run my site because of this.

### Environment
OS: Windows 10
Firebase SDK Ver: ^11.0.1
Firebase Product: auth, but happens at initialization.
Node.js: v18.7.0
NPM: v8.15.0

**Comment by ArchyInUse** [comment]
Hi, I have recently realized that next.js middleware runs on V8, which firebase-admin cannot run at. I thought the middleware was node.js and therefor would run fine.
Either way, now I gotta figure out how to run authorization before API call code all over again.
Thanks for the comment though

**Comment by clipsai** [comment]
> Hi, I have recently realized that next.js middleware runs on V8, which firebase-admin cannot run at. I thought the middleware was node.js and therefor would run fine. Either way, now I gotta figure out how to run authorization before API call code all over again. Thanks for the comment though

Did you end up figuring it out?

**Comment by yoonghan** [comment]
If anyone had this issue add the runtime to use nodejs. It can be anywhere in the file.
---
export const config = {
  runtime: "nodejs",
}

**Comment by fontoful** [comment]
JUST FYI, 

this is actually an issue with Next JS's middleware:
https://www.reddit.com/r/Firebase/comments/sbhg4b/firebase_and_nextjs_middleware_for_authentication/
