### ISSUE TITLE
Inconsistent imports can lead to deployment errors.

### ISSUE THREAD

**Issue by arthurgubaidullin** [firebase/firebase-admin-node#1856]
### Environment

  * Operating System version: macOS 12.4
  * Firebase SDK version: 11.4.2
  * Firebase Product: firebase-admin
  * Node.js version: 16.14.2
  * NPM version: 8.14.0

### The problem

When global imports from `firebase-admin` are used, as in the example below, along with modular imports, the deployment will break with an incomprehensible error.

It is difficult to understand something from this error, and it took some time to localize the problem.

#### Error:
```text
Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'INTERNAL')
```

#### Relevant Code:
```js
import {initializeApp} from 'firebase-admin';
import {getApps, getApp} from 'firebase-admin/app';
```

**Comment by lahirumaramba** [comment]
`initializeApp` is in `firebase-admin/app`.

The correct import would be:
```
import { initializeApp } from 'firebase-admin/app';
```
Check out the [modular SDK migration guide](https://firebase.google.com/docs/admin/migrate-node-v10#use-modules-instead-of-namespaces) for more information.

**Comment by arthurgubaidullin** [comment]
@lahirumaramba I know how to write correctly.  

The point is that it's easy to make a mistake, for example through auto-import in an ide, and very difficult to find the cause. 

Currently, non-modular imports are not marked as deprecated.  

Maybe you can make a rule for eslint or at the code level make the error more understandable?

**Comment by lahirumaramba** [comment]
Good point on the IDE auto-imports. Once we complete the switch to modular SDK this issue will become obsolete, but I will check if there is anything we can do to minimize the confusion in the meantime. Thanks for reporting this!
