### ISSUE TITLE
Fail fast on initializing with a different project's databaseUrl

### ISSUE THREAD

**Issue by snarfed** [firebase/firebase-admin-node#1873]
_Originally filed in https://github.com/firebase/firebase-functions/issues/1191 and [on StackOverflow](https://stackoverflow.com/questions/73355121/firebase-cloud-function-not-triggering-on-different-apps-realtime-database)._

Hi all! Thanks for Firebase, it's great!

I recently tried to set up a Firebase Cloud Function to trigger on a Realtime Database owned by a different project: the [Hacker News API](https://github.com/HackerNews/API). I passed `databaseUrl: https://hacker-news.firebaseio.com/` to `admin.initializeApp()`, and it deployed fine, but it never triggered.

I eventually learned that [Firebase just doesn't support triggering across projects like this](https://stackoverflow.com/a/73355286/186123). Fair enough. Could you consider failing fast and reporting an error in this case? That would have saved me a fair amount of debugging.

Code below. Thanks in advance!

```js
const functions = require('firebase-functions')
const admin = require('firebase-admin')
admin.initializeApp({databaseUrl: 'https://hacker-news.firebaseio.com/'})

exports.itemUpdated = functions.database.ref('/v0/item/{id}').onCreate((snapshot, context) => {
      functions.logger.log('Item: ', context.params.id, snapshot.val())
      return null
})
```

**Comment by lahirumaramba** [comment]
Since the database URL doesn't always contain the project ID (you can create a new database with any random string in the URL) I don't think this is something we can check on the SDK side. Closing this as `won't fix`.
