### ISSUE TITLE
[FR] Admin version of the Firestore Lite SDK

### ISSUE THREAD

**Issue by GriffinJohnston** [firebase/firebase-admin-node#1879]
**The problem**
There is a longstanding issue with extremely slow cold-start times when using the official Nodejs Firestore library in serverless environments: https://issuetracker.google.com/issues/158014637. It appears that the underlying issue is very difficult to address (hence the unresolved years-old P1/S1 issue), and a proper interim fix is long overdue.

One solution is to use the Firestore REST API directly. This dramatically improves cold start times, but at the cost of a seriously degraded developer experience. There has been at least one attempt by a Firestore user to create an unofficial wrapper library (https://github.com/bountyrush/nodejs-firestore). This library works, but is maintained by a single developer, and is not a replacement for an official library for obvious reasons.

**The solution**
A lightweight wrapper library that adds a friendly interface to the Firestore REST API for simple CRUD operations would do a lot to ameliorate the three year old cold start bug. Essentially a Nodejs equivalent of the Firestore Lite SDK. A Google employee has suggested that this library might even be able to share significant code with Firestore Lite: https://issuetracker.google.com/issues/158014637#comment183

**Comment by bsplosion** [comment]
As a note, this issue does not just affect cloud functions, but rather affects anything that needs to be cold-started.  Reproduction samples work the same way on Docker containers hosted virtually anywhere, or when rebuilding an application during a live reload - the library itself appears to be the culprit, not the hosting environment.

**Comment by willbattel** [comment]
This would definitely help a lot of developers, however in our case we use a lot of transactions which seem to potentially be beyond the scope of a "lite" SDK. If we could get, either in addition to or instead of this, an official Google-maintained equivalent of https://github.com/bountyrush/nodejs-firestore it could help with that case. We really just want the speed of REST with the DX of the Admin SDK.

**Comment by rodneyrd** [comment]
Thanks for creating the issue, indeed it would definitely help a lot of us !

**Comment by ganey** [comment]
I'm also interested in this, parsing an access token and calling firestore in a single request can take ages when cold on AWS lambda

**Comment by nth-child** [comment]
Much needed. Thank you.

**Comment by manwithsteelnerves** [comment]
I'm the developer for REST api implementation - https://github.com/bountyrush/nodejs-firestore

I thought of giving a try with lite web js sdk but the links are broken for source code. Can someone point at the right link?
https://cloud.google.com/firestore/docs/reference/libraries

**Comment by ganey** [comment]
@manwithsteelnerves I think it's this? https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore/lite

**Comment by jamesdaniels** [comment]
This was posted to the public issue but repeating here for visibility. 

`@google-cloud/firestore` has begun experimenting with a `preferRest` option (`@6.1.0-pre.0`). Folks should give that a spin. I'm sure once it lands we'll look at exposing that option in firebase-admin, as this library wraps `@google-cloud/firestore`.

**Comment by GriffinJohnston** [comment]
I'm seeing a significant performance boost from this, which is very exciting. It will be even better if it ends up in firebase-admin, which will simplify usage and help prevent problems like this: https://github.com/googleapis/nodejs-firestore/issues/760

**Comment by lahirumaramba** [comment]
This feature is now available in `firebase-admin` `v11.4.0`. Thank you everyone for your patience!

**Comment by jdgamble555** [comment]
We need to reopen this again. Now that `Edge Functions` are popular, we need `Firebase Admin Lite` SDK to be allowed to handle session variables and fetch calls with the admin key on the server.

J

**Comment by dconeybe** [comment]
PSA: Please continue discussion on this topic at https://github.com/firebase/firebase-admin-node/issues/2572

**Comment by Rizzist** [comment]
+1
