### ISSUE TITLE
[messaging] http module : failed to execute source

### ISSUE THREAD

**Issue by Tom3652** [firebase/firebase-admin-node#1902]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MongoDB Atlas Trigger (Realm App)
  * Firebase SDK version: 11.0.1
  * Firebase Product: messaging 
  * JS SDK Version: [3.18.0](https://github.com/mongodb/stitch-js-sdk/releases/tag/v3.18.0)
  * NPM version: I don't know

### [REQUIRED] Step 3: Describe the problem

Executing `admin.messaging().sendMulticast(message)` returns an error but is actually working : 

```
FunctionError: 'http' module: FunctionError: failed to execute source for 'node_modules/@fastify/busboy/lib/main.js': FunctionError: failed to execute source for 'node_modules/@fastify/busboy/deps/dicer/lib/Dicer.js': FunctionError: failed to execute source for 'node_modules/@fastify/busboy/deps/dicer/lib/HeaderParser.js': FunctionError: failed to execute source for 'node_modules/@fastify/busboy/lib/utils.js': TypeError: Value is not an object: undefined
    at node_modules/@fastify/busboy/lib/utils.js:23:27(322)

    at require (native)
    at node_modules/@fastify/busboy/deps/dicer/lib/HeaderParser.js:15:24(29)

    at require (native)
    at node_modules/@fastify/busboy/deps/dicer/lib/Dicer.js:19:28(39)

    at require (native)
    at node_modules/@fastify/busboy/lib/main.js:28:21(44)

    at execute (native)
    at <eval>:16:29(8)
    at K (<eval>:10:6625(35))
    at <eval>:10:4454(115)
    at M (<eval>:10:9199(23))
    at T (<eval>:10:9026(174))
    at <eval>:10:9810(49)
    at onStreamRead (<eval>:10:2062(36))
```

My Atlas Trigger reports error anyway even if the code is successfully executed. 

Here is my [StackOverflow](https://stackoverflow.com/questions/73687131/http-module-failed-to-execute-source-node-js-atlas-trigger) bounty on the subject but since no one has an obvious answer i have decided to raise an issue here. 

#### Steps to reproduce:

1. Create a MongoDB Atlas trigger
2. Add `firebase-admin` as external dependency
3. Add the service-account.json as a `value`
4. Run the code with the below code  

#### Relevant Code:

```
exports = async function() {

  const admin = require("firebase-admin");
  const json_creds = context.values.get("service_account_value_name");
  	  
    const title = "Test";
    const body = "This is a test";
   
    const message= {
      android: {
        notification: {
          title: title,
          sound: "default",
          body: body,
        },
      },
      apns: {
        payload: {
          aps: {
            alert: {
              title: title,
              body: body,
            },
            mutableContent: 1,
            contentAvailable: 1
          }
        },
      },
      tokens: ["device_token_1", "device_token_2"]
    };
    	
    admin.initializeApp({
        credential: admin.credential.cert(JSON.parse(json_creds))
      });
  
    admin.messaging().sendMulticast(message);

    console.log("Messages sent !");
  }
}
```

**Comment by kibertoad** [comment]
@Tom3652 Can you check what is the exact version of fastify/busboy that you are using? I'm having difficulties tracing back your stacktrace to actual lines of code. Do you have some kind of minification in place perhaps?
Would be great to know what line of code does `node_modules/@fastify/busboy/lib/utils.js:23:27(322)` stands for in your environment.

**Comment by Tom3652** [comment]
Hi @kibertoad thanks for the very quick reply, i am trying to find the answers in `firebase-admin` repo, i will update here when i find it.

**Comment by kibertoad** [comment]
@Tom3652 That's what I see in the repo too, which doesn't mean that it's the same version you currently have in your node_modules. Lines do not match between 1.1.0 and your stacktrace.

**Comment by Tom3652** [comment]
Oh but in my Atlas trigger i am only using the latest version of `firebase-admin` as dependency : 
![Capture d’écran 2022-09-24 à 17 12 31](https://user-images.githubusercontent.com/32631467/192105524-13bbf937-0243-4c35-b82e-05fd5d7e38f2.png)

 Is it possible there is a conflict ? I mean MongoDB Atlas would also be using your package ? 
Sorry for my basic knowledge here.. 

I have found the code that throws this error in `firebase-admin` : 

```
private handleMultipartResponse(
    response: LowLevelResponse, respStream: Readable, boundary: string): void {

    const busboy = require('@fastify/busboy'); // eslint-disable-line @typescript-eslint/no-var-requires
    const multipartParser = new busboy.Dicer({ boundary });
    const responseBuffer: Buffer[] = [];
    multipartParser.on('part', (part: any) => {
      const tempBuffers: Buffer[] = [];

      part.on('data', (partData: Buffer) => {
        tempBuffers.push(partData);
      });

      part.on('end', () => {
        responseBuffer.push(Buffer.concat(tempBuffers));
      });
    });

    multipartParser.on('finish', () => {
      response.data = undefined;
      response.multipart = responseBuffer;
      this.finalizeResponse(response);
    });

    respStream.pipe(multipartParser);
  }
```

**Comment by kibertoad** [comment]
@Tom3652 Can you find which specific line is throwing? I wonder what exactly is undefined and whether we need to make some part of the code more defensive against such cases.

**Comment by Tom3652** [comment]
It's very weird, my error says (if i actually understand something..) that you would be using a `HeaderParser` in `utils.js` but i don't see it in your class... 
I am really not sure what should i look, but i don't think i will be much of a help here unfortunately, you have my `message` object that i pass to the method that has only `String`, `Integer` and `List` types :/  

But if the error comes from a `HeaderParser`, i don't see where Firebase is passing / building the said "header" to the HTTP request.

**Comment by kibertoad** [comment]
@Tom3652 I wonder if this is related to Atlas triggers not supporting some of the Node.js standard lib functionality and one of the imports resolving to undefined, e. g. "inherits" from util.
what is your runtime, technically? it is a full-blown Node.js instance, or some kind of a lambda? what are the compatibility constraints there?

**Comment by Tom3652** [comment]
Thanks for the explanations you may be right. 
Here is what i have found regarding Atlas functions : https://www.mongodb.com/docs/atlas/app-services/functions/javascript-support/#std-label-js-support that contains some list of supported modules. 

![Capture d’écran 2022-09-24 à 19 41 52](https://user-images.githubusercontent.com/32631467/192111526-f4325dec-5b44-43f6-a879-a24301e9582b.png)

**Comment by kibertoad** [comment]
@Tom3652 Yup, looks like we've got it: `App Services does not support [util.TextDecoder](https://nodejs.org/docs/v10.18.1/api/util.html#util_class_util_textdecoder)`, which we are using.
@Uzlopak what's your take on this?

**Comment by Uzlopak** [comment]
I will have a look at it latest on monday.

**Comment by Tom3652** [comment]
Hi guys, is there any news regarding this ? or should i do something myself ? 
Thanks !

**Comment by georgesjamous** [comment]
We have faced similar issue. 
Until a solution is available we are using a Transitional AWS Lambda to call the API.

**Comment by tm00-git** [comment]
I have faced similar issue. No solution so far.
Atlas App Services run Fuctions on Node v10.18.1. Latest firebase-admin requires Node v16.
I tried installing lower firebase-admin version (which supports Node v10) to Atlas, however no success yet.

**Comment by lahirumaramba** [comment]
@kibertoad @Uzlopak Thank you for looking into this!
We only use `Dicer` in `firebase-admin` and it doesn't look like `Dicer` needs `util.TextDecoder`, does it? Do you know if there is a way for us to load Dicer separately from `@fastify/busboy`?

**Comment by tm00-git** [comment]
firebase-admin v9.4.2 works well without any external dependencies

**Comment by lahirumaramba** [comment]
@tm00-git `firebase-admin v9.4.2` uses the `mscdex/dicer` package, which contains security vulnerabilities. We replaced that package with `@fastify/busboy` in `v10.3.0` as a fix. https://firebase.google.com/support/release-notes/admin/node#version_1030_-_09_june_2022

**Comment by Tom3652** [comment]
Hi @lahirumaramba, do you have any updates or workarounds ? My triggers are all in error state :/

**Comment by Uzlopak** [comment]
@lahirumaramba 

If you can provide a PR, I would gladly look in to it.

**Comment by lahirumaramba** [comment]
> @lahirumaramba
> 
> If you can provide a PR, I would gladly look in to it.

Thanks @Uzlopak !
Created https://github.com/fastify/busboy/pull/102

**Comment by lahirumaramba** [comment]
Closing this as the issue is now fixed in `fastify/busboy` `v1.2.0` (Thanks folks!) https://github.com/fastify/busboy/issues/100
We can reopen later if needed.

**Comment by Tom3652** [comment]
Thanks everyone for fixing this ! 
Only upgrading `firebase-admin` is enough for me to not see this error ?

**Comment by kibertoad** [comment]
No, you need to ensure your package-lock references correct fastify-busboy version.

**Comment by Tom3652** [comment]
Yes but i am using an Atlas trigger i have not the hand of the package-lock. 
I will try adding `fastify-busboy` package and hope it will overwrite the `firebase-admin` then

**Comment by lahirumaramba** [comment]
We do not pin to a specific version of `@fastify/busboy` in `firebase-admin` so if you do a fresh install of `firebase-admin` npm should pull the latest version of `@fastify/busboy`. https://github.com/firebase/firebase-admin-node/blob/88ae832ac86bbdd015a7c859e6fa09f467391dfb/package.json#L199

The easiest way to do this is by removing your `node_modules` and `package-lock.json` and then running `npm install`. Keep in mind though that this will update `all` the dependencies along with `firebase-admin`.

You might also be able to force the package version of `@fastify/busboy` using [resolutions](https://stackoverflow.com/a/66470615) key or [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (in NPM 8+) in package.json.

**Comment by Tom3652** [comment]
Thanks for your details explanation @lahirumaramba, but i am seeing a new error now that is preventing me from sending push notifications. I will raise a new issue as this one is closed but it's very possible it's related.
