### ISSUE TITLE
TOO_MANY_ATTEMPTS_TRY_LATER calling generateEmailVerificationLink

### ISSUE THREAD

**Issue by JoakoI98** [firebase/firebase-admin-node#1916]
### Describe your environment

  * Operating System version: Debian GNU/Linux 9.13
  * Firebase SDK version: _____
  * Firebase Product: auth admin sdk
  * Node.js version: 12.22.12
  * NPM version: 6.14.16

### Describe the problem
Call generateEmailVerificationLink more than once, throws this error:
`{"error":{"code":400,"message":"TOO_MANY_ATTEMPTS_TRY_LATER","errors":[{"message":"TOO_MANY_ATTEMPTS_TRY_LATER","domain":"global","reason":"invalid"}]}}`

Wait more than a minute between calls is needed in order to work. 

#### Steps to reproduce:
Call generateEmailVerificationLink more than once in less than a minute.

#### Relevant Code:
```
private async emailVerficiation(email: string): Promise<string> {
        await this.initializeFirebaseApp();
        const mailVerificationLink: string = await admin.auth().generateEmailVerificationLink(email);`
```

**Comment by Apri34** [comment]
I have been running into the same issue

**Comment by lahirumaramba** [comment]
Hi, if you are still having this issue I would encourage you to submit a support request through https://firebase.google.com/support/troubleshooter/contact where you can include the project id. Thanks!
