### ISSUE TITLE
Latest firebase-admin@11.1.0 not compatible with latest firebase-functions@3.24.1

### ISSUE THREAD

**Issue by ShanahJr** [firebase/firebase-admin-node#1924]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 11
  * Firebase SDK version:  
  * Firebase Product: Functions
  * Node.js version: 16.13.1
  * NPM version:  8.1.2

#### Steps to reproduce:

I wanted to use the firebase task function and to do so I needed to update my fire-base admin to the latest version but it is not conflicting with my firebase-functions. 
errors such as:
```
Error: functions/node_modules/firebase-functions/lib/providers/firestore.d.ts:1:27 - error TS2307: Cannot find module 'firebase-admin' or its corresponding type declarations.
import * as firebase from 'firebase-admin';
```
#### Relevant Code:

```
import * as firebase from 'firebase-admin';
```

**Comment by taeold** [comment]
@ShanahJr Hey Shanah - I tried to reproduce the problem but wasn't able to.

Here's what I did:

```
$ node -v
v16.14.0

$ npm ls firebase-functions firebase-admin typescript
functions@ /Users/danielylee/google/cf3-admin-v11/ts
├── firebase-admin@11.0.0
├─┬ firebase-functions@3.24.1
│ └── firebase-admin@11.0.0 deduped
└── typescript@4.8.4

$ cat src/index.ts
import * as functions from "firebase-functions";
import * as admin from 'firebase-admin';

admin.initializeApp();

export const helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});

exports.myFunction = functions.firestore
  .document('my-collection/{docId}')
  .onWrite((change, context) => {});

$ npm run build

> build
> tsc
```

No type error from me. Can you share a minimal example to help us reproduce your problem?

**Comment by ShanahJr** [comment]
@taeold  Hey Taeold. Thank you for taking your time to assist me with this. I am using ionic and firebase in this case. I hope the below is detailed enough. Please let me know if I you need any more information

$ node -v
16.13.1

 npm -v
8.1.2 

// Functions
$ npm ls firebase-functions firebase-admin typescript
+-- @typescript-eslint/eslint-plugin@3.10.1
| `-- tsutils@3.21.0
|   `-- typescript@3.9.10 deduped
+-- firebase-admin@11.1.0
+-- firebase-functions-test@0.2.3
| +-- firebase-admin@11.1.0 deduped
| `-- firebase-functions@3.24.1 deduped
+-- firebase-functions@3.24.1
| `-- firebase-admin@11.1.0 deduped
`-- typescript@3.9.10

//Ionic
$npm ls
+-- @angular-devkit/build-angular@13.0.4
+-- @angular-eslint/builder@13.0.1
+-- @angular-eslint/eslint-plugin-template@13.0.1
+-- @angular-eslint/eslint-plugin@13.0.1
+-- @angular-eslint/template-parser@13.0.1
+-- @angular/cli@13.0.4
+-- @angular/common@13.0.3
+-- @angular/compiler-cli@13.0.3
+-- @angular/compiler@13.0.3
+-- @angular/core@13.0.3
+-- @angular/fire@7.2.0
+-- @angular/forms@13.0.3
+-- @angular/language-service@13.0.3
+-- @angular/platform-browser-dynamic@13.0.3
+-- @angular/platform-browser@13.0.3
+-- @angular/router@13.0.3
+-- @awesome-cordova-plugins/deeplinks@5.37.3
+-- @awesome-cordova-plugins/pdf-generator@5.38.0
+-- @awesome-cordova-plugins/social-sharing@5.39.1
+-- @capacitor/android@3.3.4
+-- @capacitor/app@1.0.7
+-- @capacitor/cli@3.3.3
+-- @capacitor/core@3.3.3
+-- @capacitor/electron@2.5.0
+-- @capacitor/haptics@1.1.3
+-- @capacitor/keyboard@1.2.0
+-- @capacitor/status-bar@1.0.6
+-- @ionic/angular-toolkit@5.0.3
+-- @ionic/angular@6.0.1
+-- @ionic/lab@3.2.10
+-- @ionic/storage-angular@3.0.6
+-- @types/crypto-js@4.1.1
+-- @types/jasmine@3.6.11
+-- @types/jasminewd2@2.0.10
+-- @types/node@12.20.38
+-- @typescript-eslint/eslint-plugin@5.3.0
+-- @typescript-eslint/parser@5.3.0
+-- cordova-pdf-generator@2.1.1
+-- cordova-plugin-x-socialsharing@6.0.3
+-- crypto-js@4.1.1
+-- eslint-plugin-import@2.22.1
+-- eslint-plugin-jsdoc@30.7.6
+-- eslint-plugin-prefer-arrow@1.2.2
+-- eslint@7.32.0
+-- firebase@9.6.1
+-- html2canvas@1.4.1
+-- ionic-plugin-deeplinks@1.0.24
+-- jasmine-core@3.8.0
+-- jasmine-spec-reporter@5.0.2
+-- jquery@3.6.0
+-- js-sha512@0.8.0
+-- jspdf@2.5.1
+-- karma-chrome-launcher@3.1.0
+-- karma-coverage-istanbul-reporter@3.0.3
+-- karma-coverage@2.0.3
+-- karma-jasmine-html-reporter@1.7.0
+-- karma-jasmine@4.0.1
+-- karma@6.3.9
+-- protractor@7.0.0
+-- rxfire@6.0.3
+-- rxjs@6.6.7
+-- save@2.4.0
+-- swiper@7.4.1
+-- tailwindcss@2.2.19
+-- ts-md5@1.2.10
+-- ts-node@8.3.0
+-- tslib@2.3.1
+-- typescript@4.4.4
`-- zone.js@0.11.4

Some of my classes imports the following:
```
import {firestore} from "firebase-admin";
```
The above gives me the following error when I serve my ionic app:

```
Error: functions/src/classes/AllAgent.ts:5:9 - error TS2305: Module '"firebase-admin"' has no exported member 'firestore'.

 5 import {firestore} from "firebase-admin";
```

And then in node_ modules folder I am getting some errors like below: 
```
 Error: functions/node_modules/firebase-admin/lib/index.d.ts:21:16 - error TS2671: Cannot augment module 'firebase-admin' because it resolves to a non-module entity.

21 declare module 'firebase-admin' {
```

AND 

```
Error: functions/node_modules/firebase-functions/lib/providers/firestore.d.ts:1:27 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

1 import * as firebase from 'firebase-admin';
```

Please note I do not get these errors when I build my  firebase functions but only when I serve my ionic application



### Project Structure
d----          2022/08/24    13:44                .angular
d----          2022/10/07    11:37                .vscode
d----          2022/10/07    11:06                android
d----          2022/08/23    16:11                e2e
d----          2022/10/07    19:11                functions
d----          2022/10/07    17:56                node_modules
d----          2022/08/23    16:25                public
d----          2022/08/23    16:25                resources
d----          2022/08/23    16:25                src
d----          2022/10/07    17:55                www
-a---          2022/08/23    16:11            720 .browserslistrc
-a---          2022/08/23    16:11            290 .editorconfig
-a---          2022/08/23    16:11           1197 .eslintrc.json
-a---          2022/08/23    16:25             84 .firebaserc
-a---          2022/08/23    18:32            528 .gitignore
-a---          2022/08/23    16:25           5645 angular.json
-a---          2022/08/23    16:25            226 capacitor.config.json
-a---          2022/08/23    16:25            379 firebase.json
-a---          2022/08/23    16:11            121 ionic.config.json
-a---          2022/08/23    16:11           1464 karma.conf.js
-a---          2022/08/23    16:25            451 ng-tailwind.js
-a---          2022/10/07    17:56        1649918 package-lock.json
-a---          2022/10/07    17:56           3175 package.json
-a---          2022/08/23    16:25            172 tailwind.config.js
-a---          2022/08/23    16:11            302 tsconfig.app.json
-a---          2022/08/23    16:25            653 tsconfig.json
-a---          2022/08/23    16:11            351 tsconfig.spec.json
-a---          2022/08/23    16:25           1719 tslint.json

### Functions Structure 
d----          2022/10/07    14:03                lib
d----          2022/10/07    14:19                node_modules
d----          2022/10/07    19:11                src
-a---          2022/08/23    16:25           1132 .eslintrc.js
-a---          2022/08/23    16:25            155 .gitignore
-a---          2022/08/23    16:25            177 .prettierrc.js
-a---          2022/08/23    16:25            236 launch.json
-a---          2022/10/07    19:11         331854 package-lock.json
-a---          2022/10/07    19:11           1355 package.json
-a---          2022/08/23    16:25             47 tsconfig.dev.json
-a---          2022/08/23    16:25            270 tsconfig.json

**Comment by lahirumaramba** [comment]
Hi @ShanahJr 
`import {firestore} from "firebase-admin";` is not the correct way to use firestore. Please use `import { getFirestore } from 'firebase-admin/firestore'` instead.

You can see more on upgrading to the modular SDK here https://firebase.google.com/docs/admin/migrate-node-v10
