### ISSUE TITLE
[Bug] 'The provided ID token is not a valid token' after using admin.credentials.cert() in intializeApp()

### ISSUE THREAD

**Issue by jrmoynihan** [firebase/firebase-admin-node#1925]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS v12.6 (Monterey)
  * Firebase SDK version: 9.10.0
  * Firebase Admin version: 11.0.1
  * Firebase Product: Admin (auth, database, storage, etc)
  * Node.js version: 18.6.0
  * NPM version: pnpm v7.12.2

### [REQUIRED] Step 3: Describe the problem

I'm unable to use the provided token from `admin.credential.cert()` to create or verify cookies.  The app is initialized without any errors or warnings, but the `try/catch` blocks (below) where I create or verify cookies will throw the following error with that provided admin app instance's id token:

```js
// FirebaseAuthError received:
 errorInfo: {
    code: 'auth/invalid-id-token',
    message: 'The provided ID token is not a valid Firebase ID token.'
  },
```

#### Steps to reproduce:

1) Export admin SDK service account JSON from Firebase console
2) Import service account JSON to a server-side Typescript module
3) Map the fields to a `ServiceAccount` object (the exported JSON's fields do not match the expected types of `ServiceAccount`; e.g. projectId !== project_id)
4) Create a credential for the admin app instance after certifying the service account object with `admin.credential.cert(serviceAccount)`
5) Initialize the admin app instance with `admin.initializeApp()`
6) Call `auth().createSessionCookie()` on the provided app instance.

#### Relevant Code:

``` js
import type { ServiceAccount } from 'firebase-admin/app';
import serviceAccountJSON from '../private/admin-sdk-service-account.json';
import admin, { auth } from 'firebase-admin';

const adminAccount: ServiceAccount = {
	projectId: serviceAccountJSON.project_id,
	clientEmail: serviceAccountJSON.client_email,
	privateKey: serviceAccountJSON.private_key
};
const app = admin.initializeApp({
	credential: admin.credential.cert(adminAccount),
	databaseURL: 'https://<PROJECT_ID>.firebaseio.com'
});

// A server-side hook that runs in response to RequestEvents in SvelteKit apps:
export const handle: Handle = async ({ event, resolve }) => {
	const { cookies, locals } = event;

	const session = cookies.get('session');

	if (session) {
		try {
			const user = await auth(app).verifySessionCookie(session);
		} catch (error) {
			console.error('error verifying session cookie', session, error);
		}
	} else {
		try {
			const expiresIn = 60 * 60 * 24 * 5 * 1000;
			const options = { expiresIn, httpOnly: true };
			const cookie = await auth(app).createSessionCookie('session', options);
			const user = await auth(app).verifySessionCookie('session');
		} catch (error) {
			console.error('error in creating session cookie', error);
		}
	}
	return resolve(event);
};

```
#### Expected:
Able to use the provided id token with the admin functions to create a session cookie.

**Comment by lahirumaramba** [comment]
Hi @jrmoynihan you need to pass the full service account to initialize the SDK. Please try below and see if it fixes the issue.

```
import serviceAccount from '../private/admin-sdk-service-account.json';

const app = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});
```

You can also find other ways to initialize the SDK on: https://firebase.google.com/docs/admin/setup#initialize-sdk

Also, please use StackOverflow for usage questions in the future. Thanks!

**Comment by woosuk288** [comment]
in my case, the first param of "createSessionCookie" had to be idToken string not just any string.

I referred to [this link](https://stackoverflow.com/q/68864193/4411993)
