### ISSUE TITLE
[FR] getCountFromServer for firebase-admin

### ISSUE THREAD

**Issue by RohovDmytro** [firebase/firebase-admin-node#1936]
Firebase Web SDK introduced a `getCountFromServer` function to get count of documents in a collection bypassing downloading documents. Would be neat to get it in `firebase-admin`.

**Comment by dconeybe** [comment]
We literally JUST released it! See https://firebase.google.com/support/release-notes/admin/node#11.2.0

**Comment by ShanArosh2002** [comment]
I have no idea how to use COUNT( )  in  firebase-admin .currently my code is  await admin.firestore().collection("Class").count().get();

**Comment by laug** [comment]
For those who came here via google and are looking for the function name: `.count()` as in
`const snapshot = await db.collection("users").where("team", "==", "sales").count().get()
console.log(snapshot.data().count)`
