### ISSUE TITLE
Cannot read properties of undefined (reading 'SDK_VERSION')

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-admin-node#1957]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS M1 (Monterey)
  * Firebase SDK version: 8.10.0
  * Firebase Product: firebase-admin
  * Node.js version: 16
  * NPM version: 8.1.0

### [REQUIRED] Step 3: Describe the problem

```
const admin = require('firebase-admin')
console.log(admin) // because firebase-admin is initialized at server start-up it is valid instance as shown below
let db = admin.database()
```

`console.log(admin)` yields this:
```
<ref *1> FirebaseNamespace {
>    __esModule: true,
>    credential: {
>      cert: [Function: cert],
>      refreshToken: [Function: refreshToken],
>      applicationDefault: [Function: applicationDefault]
>    },
>    SDK_VERSION: '8.10.0',
>    Promise: [Function: Promise],
>    INTERNAL: FirebaseNamespaceInternals {
>      firebase_: [Circular *1],
>      serviceFactories: {},
>      apps_: { '[DEFAULT]': [FirebaseApp] },
>      appHooks_: {}
>    },
>    default: [Circular *1]
>  }
```

and the next line `admin.database()` yields this error:
```
TypeError: Cannot read properties of undefined (reading 'SDK_VERSION')
>      at registerDatabase (/Users/me/Developer/project/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15318:28)
```
even though `SDK_VERSION` is in `admin` object.

What I'm trying to achieve is to access database via my cloud functions server. It's supposed to be reading that instance as proper.

**Comment by janswist** [comment]
Updated the code to the modular one without upgrading package version. Now it works.

**Comment by spearkyu** [comment]
how to upgrading package version? i didn't work too

**Comment by xhelson** [comment]
Uninstall firebase: npm uninstall firebase
And install the latest firebase-admin
