### ISSUE TITLE
Can't initialize app after update firebase-admin

### ISSUE THREAD

**Issue by trigonometric-act** [firebase/firebase-admin-node#1994]
* Operating System version: Windows 11
  * Firebase SDK version:  "firebase-admin": "^11.3.0" (was "firebase-admin": "^9.12.0"), and "firebase-functions": "^3.24.1",
  * Firebase Product: Cloud functions
  * Node.js version: 16
  * NPM version: 8.5.5

I updated firebase-admin dependency from 9.12 to 11.3.0 and tried to deploy cloud functions.
Following the new convention the initialize app must look like:

import { initializeApp } from "firebase-admin/app";
/*... logic for import service account*/
initializeApp({
  credential: admin.credential.cert(serviceAcc)
});

Deploy output: 

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

node_modules/@firebase/util/dist/util-public.d.ts:491:91 - error TS1005: ',' expected.

491 export declare const getDefaultEmulatorHostnameAndPort: (productName: string) => [hostname: string, port: number] | undefined;
                                                                                              ~

node_modules/@firebase/util/dist/util-public.d.ts:491:105 - error TS1005: ',' expected.

491 export declare const getDefaultEmulatorHostnameAndPort: (productName: string) => [hostname: string, port: number] | undefined;
                                                                                                            ~

node_modules/@firebase/util/dist/util-public.d.ts:498:103 - error TS1005: ']' expected.

498 export declare const getExperimentalSetting: <T extends ExperimentalKey>(name: T) => FirebaseDefaults[`_${T}`];
                                                                                                          ~~~~

node_modules/@firebase/util/dist/util-public.d.ts:498:110 - error TS1005: ';' expected.

498 export declare const getExperimentalSetting: <T extends ExperimentalKey>(name: T) => FirebaseDefaults[`_${T}`];
                                                                                                                 ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:120:29 - error TS1005: ']' expected.

120     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                ~~

node_modules/@google-cloud/firestore/types/firestore.d.ts:120:48 - error TS1005: ';' expected.

120     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                   ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:120:50 - error TS1109: Expression expected.


120     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                     ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:120:51 - error TS1109: Expression expected.

120     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                      ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:2427:1 - error TS1128: Declaration or statement expected.

2427 }
     ~


Found 9 errors.


Error: functions predeploy error: Command terminated with non-zero exit code 2

**Comment by lahirumaramba** [comment]
Hey @trigonometric-act could you confirm your TypeScript version? Starting `v11.0.0` `firebase-admin` uses TypeScript `v4.6.4`. https://firebase.google.com/support/release-notes/admin/node#version_1100_-_16_june_2022

Also, on cloud functions you can use Google Application Default Credentials. You don't need to initialize with a service account. See https://firebase.google.com/docs/admin/setup#initialize-without-parameters for more information.

**Comment by trigonometric-act** [comment]
@lahirumaramba I am using "^4.6.4" as ts version. I've found in docs that you need to import cert the following way in order to use a service account: 

`import {  initializeApp, cert  } from "firebase-admin/app";`

Also I'm using two different environments to deploy functions, I suppose that if code inits without paramenters will respect the environment used in command: deploy --project ...

Am I right?

**Comment by lahirumaramba** [comment]
That is correct, please see the migration guide for more: https://firebase.google.com/docs/admin/migrate-node-v10

> Also I'm using two different environments to deploy functions, I suppose that if code inits without paramenters will respect the environment used in command: deploy --project ...

If it is a Google environment, the project id will be obtained by the SDK. Otherwise, you can set `GOOGLE_CLOUD_PROJECT` environment variable to specify the project ID explicitly or pass in the app initialization.

```
import { initializeApp, applicationDefault } from 'firebase-admin/app';

initializeApp({
  credential: applicationDefault(),
  projectId: '<FIREBASE_PROJECT_ID>',
});
```
