### ISSUE TITLE
Firebase Storage.publicUrl() returns gcloud storage url which ignores firebase storage rules

### ISSUE THREAD

**Issue by Bastianowicz** [firebase/firebase-admin-node#2011]
### environment

  * Operating System version: MacOS 12.6; Firebase Functions Runtime
  * Firebase SDK version: firebase-admin: 11.2.1, 11.3.0
  * Firebase Product: storage
  * Node.js version: 16.13.1
  * NPM version: 8.1.2

#### Steps to reproduce:

When using File.publicUrl the returned URL leads to cloud storage API endpoints. This leads to unexpected behavior regarding firebase storage rules.
In my case I defined some files to be publicly available (no auth). Although this rule does work the urls generated by the sdk point to cloud storage api (https://storage.googleapis.com/...) and this API seems to ignore the applied firebase rules (in comparison to firebasestorage api https://firebasestorage.googleapis.com/v0/b/...). In consequence I receive `Access Denied` and an XML response. 

Steps to reproduce
* Create Storage Rule to make images publicly available (see example below)
* upload file to location specified in rule
* check if rule is applied (open path generated by firebase console in incognito tab)
* generate publicUrl using the admin sdk (see code below)
* open generated publicUrl in incognito tab

expected
* generated public url is publicly accessibly (apparently a firebasestorage api url)

actual
* Access denied

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details>
</Error>
```

#### Relevant Code:

```typescript
const [res] = await this.storage.bucket(AvatarFirebaseStorageRepository.bucketName)
                .getFiles({
                    prefix: `users/${userId}/avatars/thumbs/`,
                    delimiter: "/",
                    maxResults: 2,
                });
            return .filter(f => f.metadata.contentType !== "text/plain")
                    .shift()
                    .publicUrl();
```

```
match /users/{userId}/avatars/thumbs/{file} {
            // avatars thumbs are publicly available
            allow read;
}
```

**Comment by tonyjhuang** [comment]
@Bastianowicz `publicUrl()` is not designed to return a Firebase Storage-friendly download URL that will evoke Firebase Security Rules, as it is a GCS-specific method.

Firebase Storage download urls are deterministic; they follow one of the following patterns:
* `https://www.firebasestorage.googleapis.com/v0/b/<bucket>/o/<object>`, to download the object's metadata, or 
* `https://www.firebasestorage.googleapis.com/v0/b/<bucket>/o/<object>?alt=media` to download the object's file contents.

Both of these URLs will evaluate security rules on each visit. I would recommend you manually create the download urls you need rather than trying to use the admin SDK.

**Comment by Bastianowicz** [comment]
Thanks for the clarification. I will close this issue than and build it myself.
I was a little worried if i'd need to generate a different url for local emulator suite but fortunately the emulator uses the same pattern.
Please just allow me this little feedback though: Since the docs for cloud storage sdk is pretty rudimentary this piece lacks a little of developer experience. I would either love a method, that does the job for me or at least some improvements in the docs.
Either way thanks a lot for your help

**Comment by Bastianowicz** [comment]
ChatGPT suggested this:

```typescript
import * as admin from 'firebase-admin';

const bucket = admin.storage().bucket();

// Replace 'path/to/file' with the actual path to the file in your Firebase Storage bucket
const file = bucket.file('path/to/file');

// Get the file's metadata, including its download URL
file.getMetadata()
  .then((metadata: admin.storage.FileMetadata) => {
    const downloadUrl = metadata[0].mediaLink;

    // The download URL can be used to access the file
    console.log(downloadUrl);
  })
  .catch((error: any) => {
    // Handle any errors
    console.error(error);
  });
```

I then changed it to the following which worked out

```typescript
const [, , meta] = await this.storage.bucket(AvatarFirebaseStorageRepository.bucketName)
            .getFiles({
                prefix: `users/${userId}/avatars/thumbs/`,
                delimiter: "/",
                maxResults: 2,
            });
const downloadUrl = meta.items.filter(f => f.contentType !== "text/plain").shift().mediaLink;
```

**Comment by Bastianowicz** [comment]
To make things work with local emulator suite and production code I ended up with the following:

```typescript
const [, , meta] = await bucket
                .getFiles({
                    prefix: `users/${userId}/avatars/thumbs/`,
                    delimiter: "/",
                    maxResults: 2,
                });
            const bucketName = AvatarFirebaseStorageRepository.bucketName;
            const baseUrl = bucket.storage.baseUrl.startsWith("http://127.0.0.1")
                ? bucket.storage.baseUrl
                : "https://firebasestorage.googleapis.com";
            const file = meta.items.filter(f => f.contentType !== "text/plain").shift();
            const filePath = encodeURIComponent(file.name);

            const storageUrl = `${baseUrl}/v0/b/${bucketName}/o/${filePath}?alt=media`;
```

@tonyjhuang you will agree that this looks pretty ugly and cumbersome for such a trivial task. Especially since this is not obvious. It looks like I am using firebase storage but actually it is gcloud. Which is not a problem per sé but becomes one when security rules are applied. 
Maybe just reconsider if there are better solutions on sdk side or tell me what approach you'd be ok with. Maybe I can come up with a PR

**Comment by kwameopareasiedu** [comment]
To anyone finding this now, I discovered a `makePublic()` function on the file object which u call to make the file public on GCP. The file then becomes accessible using the `publicUrl()` method.

```typescript
const filePath = `path/to/file.pdf`;
const file = getStorage().bucket().file(filePath);

await file.save(pdfBuffer, { contentType: "application/pdf" });
await file.makePublic();

const publicUrl = await file.publicUrl();
```

I think the only downside is, accessing the public URL may not evaluate the storage rules (not tested though), but it works for me...

**Comment by daniyarchambylov** [comment]
> To anyone finding this now, I discovered a makePublic() function on the file object which u call to make the file public on GCP. The file then becomes accessible using the publicUrl() method.

This would require to turn off UBLA. Another option is to grant Storage Object Viewer to allUsers  via Google Console

**Comment by kwameopareasiedu** [comment]
@daniyarchambylov I didn't have to turn off UBLA on the bucket. It was a new Firebase project with default configuration. I just called the `makePublic()` on the file and it worked. I had public access to just that file...

**Comment by 54ted222** [comment]
```javascript
import firebase from "firebase-admin";
import { getDownloadURL } from "firebase-admin/storage";

const file: File = /* file */;
const storageRef = firebase.storage().bucket().file("name");
  const buffer = Buffer.from(await file.arrayBuffer());
  await storageRef.save(buffer, {
    contentType: file.type,
    public: false,
  });
const url = await getDownloadURL(storageRef);
```
