### ISSUE TITLE
Outgoing HTTP requests involved in App Check token verification

### ISSUE THREAD

**Issue by monoblaine** [firebase/firebase-admin-node#2014]
I'm trying to verify Firebase App Check tokens on my custom backend. Everything is fine so far, but there's one thing I'm not sure about: My backend is hosted on a private network therefore I need to know if grabbing key sets from https://firebaseappcheck.googleapis.com/v1/jwks is the only necessary outgoing HTTP request involved in the verification process.

**Comment by lahirumaramba** [comment]
Hey @monoblaine, that's correct. Obtaining the Firebase App Check public JSON Web Key Set is the only outgoing request **for the app check verify token API**. The SDK might make other http calls during the initialization based on your environment (obtaining the service account or credentials etc.) or if you use other APIs in combination with the App check token verification.

The rest of the JWT verification happens all offline. We also cache the public keys (JWKS) for up to 6 hours, so if your environment doesn't lose its state then the outgoing request to fetch the keys should not happen (if the keys are cached) every time you call the API.

You can read more on the App check token verification process here: https://firebase.blog/posts/2021/10/protecting-backends-with-app-check
