### ISSUE TITLE
Seems different SDKs somewhat disagree on the max depth limit

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [firebase/firebase-admin-node#2017]
* Operating System version: MacOS Monteray 12.5.1
  * Firebase SDK version: firebase-admin: 11.4.0
  * Firebase Product: firestore
  * Node.js version: 16.13.2
  * NPM version: 8.3.2

It seems that the data in my firestore is either breaking the 20 field depth limit described here:  https://firebase.google.com/docs/firestore/quotas, or the firebase-admin sdk is enforcing this limit wrongly client side. 

That is, I can't run this code which simply fetches data from firestore and then tries to set it again.
```
	const calcRef = devDb.collection('users').doc('e6O3fMOB7yarL7HgRa5I53jntzy1').collection('calculations').doc('calculator')

	const calcData = (await calcRef.get()).data()

	if (calcData) {	
		calcRef.set(calcData)
	}
```

**Comment by JoachimKoenigslieb** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

It's not super trivial to reproduce this issue without sharing my firebase secrets, as the way I get the offending data into firestore also seems to be a part of the puzzle. I've created a private github repo with the secrets in them that is very minimal (only dep is firebase-admin!), that shows the issue. 

I will invite any to be a collaborator so they can reproduce the issue in an attempt to minimize credentials leak. If there is any other way I can create a shared sandbox of firestore for debugging let me know!

**Comment by lahirumaramba** [comment]
Hi @JoachimKoenigslieb,

Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.

Please do not share any credentials on github, instead file a support request through: https://firebase.google.com/support. Thanks!

**Comment by JoachimKoenigslieb** [comment]
> Hi @JoachimKoenigslieb,
> 
> Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.
> 
> Please do not share any credentials on github, instead file a support request through: https://firebase.google.com/support. Thanks!

Thank you! I'll report it trough proper channel!
