### ISSUE TITLE
Get Google access token

### ISSUE THREAD

**Issue by Gabriel2048** [firebase/firebase-admin-node#2027]
**Is your feature request related to a problem? Please describe.**
I want to be able to use Google apis (like calendar) inside Firebase Callable functions on behalf of a Firebase user that authenticated using Google sign in.

**Describe the solution you'd like**
Add a function in the that given a firebase token will return the google access token.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lahirumaramba** [comment]
If you mean to obtain the oAuth token (generated from your service account/application default credentials) to access Google APIs the following code might help. Please note that the access token from the SDK won't be associated with the user login as it was generated with service account credentials and admin privileges. 

```
import { initializeApp } from 'firebase-admin/app'

const app = initializeApp()

const token = await app.options.credential.getAccessToken()
```
