### ISSUE TITLE
Deleting a file from firebase storage

### ISSUE THREAD

**Issue by soryy708** [firebase/firebase-admin-node#204]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 3.4.1
  * Library version: 5.0.0
  * Firebase Product: storage

### [REQUIRED] Step 3: Describe the problem

I can't do anything with the `storage` object. How do I use this? (documentation is very lean)

#### Relevant Code:

    var admin = require("firebase-admin");
    var bucket = /* ... */;
    admin.initializeApp({credential: /* ... */}, databaseURL: /* ... */, storageBucket: bucket);
    admin.storage().bucket(bucket).refFromURL(/* ... */).delete()
    .then(function() {
        console.log("deleted successfully!");
    })
    .catch(function() {
        console.log("unable to delete");
    });

**Comment by hiranya911** [comment]
There's no `refFromURL()` method on Bucket. Here are the API docs: https://cloud.google.com/nodejs/docs/reference/storage/1.5.x/Bucket

Here's a delete example from our tests: https://github.com/firebase/firebase-admin-node/blob/master/test/integration/storage.spec.ts#L60

**Comment by ardwiinoo** [comment]
very cool sir
