### ISSUE TITLE
Error: 14 UNAVAILABLE: 403:Forbidden

### ISSUE THREAD

**Issue by iAMkVIN-S** [firebase/firebase-admin-node#2050]
### Describe your environment

  * Operating System version: Ubuntu 20.04.1 LTS
  * Firebase SDK version: 11.4.1
  * Firebase Product: Firebase Admin
  * Node.js version: 18.13.0
  * NPM version: 8.19.3

#### Steps to reproduce:

Our NodeJS backend, running ExpressJS and using Firebase Admin SDK has been running smoothly for 2 years. All of a sudden, on the morning of the 17th of Jan, our service was interupted by a seemignly routine Firebase call made by our baseModel. This causes all requests to fail until we reboot the backend. Since then, the error has happened randomly every 2-6+ hours with thousands of OK requests in between. The error seems to stem from the Firebase Admin SDK package/its depencies.

#### Relevant Code:

**Error Log:**
```
Jan 17 10:02:08 Error: 14 UNAVAILABLE: 403:Forbidden
Jan 17 10:02:08 at Object.callErrorFromStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
Jan 17 10:02:08 at Object.onReceiveStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:352:49)
Jan 17 10:02:08 at Object.onReceiveStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
Jan 17 10:02:08 at /app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
Jan 17 10:02:08 at processTicksAndRejections (internal/process/task_queues.js:82:9)
Jan 17 10:02:08 for call at
Jan 17 10:02:08 at ServiceClientImpl.makeServerStreamRequest (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:336:30)
Jan 17 10:02:08 at ServiceClientImpl.<anonymous> (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
Jan 17 10:02:08 at /app/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:205:29
Jan 17 10:02:08 at /app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
Jan 17 10:02:08 at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
Jan 17 10:02:08 at Object.request (/app/node_modules/google-gax/build/src/streamingCalls/streaming.js:126:40)
Jan 17 10:02:08 at Timeout.makeRequest [as _onTimeout] (/app/node_modules/retry-request/index.js:139:28)
Jan 17 10:02:08 at listOnTimeout (internal/timers.js:531:17)
Jan 17 10:02:08 at processTimers (internal/timers.js:475:7)
Jan 17 10:02:08 Caused by: Error
Jan 17 10:02:08 at Firestore.getAll (/app/node_modules/@google-cloud/firestore/build/src/index.js:902:23)
Jan 17 10:02:08 at DocumentReference.get (/app/node_modules/@google-cloud/firestore/build/src/reference.js:211:32)
Jan 17 10:02:08 at Function.<anonymous> (/app/dist/models/baseModel.js:278:62)
Jan 17 10:02:08 at Generator.next (<anonymous>)
Jan 17 10:02:08 at /app/dist/models/baseModel.js:31:71
Jan 17 10:02:08 at new Promise (<anonymous>)
Jan 17 10:02:08 at __awaiter (/app/dist/models/baseModel.js:27:12)
Jan 17 10:02:08 at Function.findById (/app/dist/models/baseModel.js:274:16)
Jan 17 10:02:08 at /app/dist/routes/routeUtils.js:62:42
Jan 17 10:02:08 at Generator.next (<anonymous>) {
Jan 17 10:02:08 code: 14,
Jan 17 10:02:08 details: '403:Forbidden',
Jan 17 10:02:08 metadata: Metadata {
Jan 17 10:02:08 internalRepr: Map {
Jan 17 10:02:08 'content-type' => [Array],
Jan 17 10:02:08 'content-length' => [Array],
Jan 17 10:02:08 'date' => [Array],
Jan 17 10:02:08 'alt-svc' => [Array]
Jan 17 10:02:08 },
Jan 17 10:02:08 options: {}
Jan 17 10:02:08 }
Jan 17 10:02:08 }
```

**Trickled down baseModel line from our code that does the Firebase fetch:**
```
   static findById(id, showDeleted = false) {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                if (!id)
                    throw new Error(`Invalid id provided for model ${this.name}`);
                const result = yield this.collection.doc(id).get();
                if (!result.exists)
                    return null;
                if (!showDeleted && result.data().isDeleted)
                    return null;
                return new this(Object.assign({}, result.data()));
            }
            catch (e) {
                console.error(e);
            }
        });
    }
```

**Our package.json:**
```
"dependencies": {
        "@sendgrid/mail": "^7.7.0",
        "axios": "^1.2.3",
        "cors": "^2.8.5",
        "crypto-js": "^4.1.1",
        "express": "^4.17.1",
        "firebase-admin": "^11.4.1",
        "lodash": "^4.17.21",
        "moment": "^2.29.4",
        "morgan": "^1.10.0",
        "nanoid": "^3.3.4",
        "stripe": "^11.6.0",
        "yup": "^0.32.11"
    },
    "devDependencies": {
        "@types/cors": "^2.8.13",
        "@types/crypto-js": "^4.1.1",
        "@types/express": "^4.17.15",
        "@types/lodash": "^4.14.191",
        "@types/morgan": "^1.9.4",
        "@types/node": "^18.11.18",
        "@types/yup": "^0.32.0",
        "@typescript-eslint/eslint-plugin": "^4.31.2",
        "@typescript-eslint/parser": "^4.31.2",
        "eslint": "^7.32.0",
        "nodemon": "^2.0.4",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.4"
    }
```

**Comment by lahirumaramba** [comment]
The error seem to be coming from `gogole-gax` through `@google-cloud/firestore`.

Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.

Additionally, check the `@google-cloud/firestore` version in your environment by running `npm list @google-cloud/firestore` and try upgrading `@google-cloud/firestore` to the latest.

**Comment by iAMkVIN-S** [comment]
Thanks for the prompt reply Lahiru. 

We've opened an issue at `nodejs-firestore` as well.

All our package versions seem to be up to date with the latest and most commonly used of everything.

Additionally,  here is the version number for `@google-cloud/firestore`:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/40800721/213556183-976fea88-1e76-41be-94be-f8188fea8aac.png">

It is very confusing because our current configuration has ran millions of requests over months without ever hitting the crash and suddenly since the 17th of Jan it's been messy!

**Comment by MarkDuckworth** [comment]
Opened in nodejs-firestore: https://github.com/googleapis/nodejs-firestore/issues/1814.

**Comment by leadhouse-manu** [comment]
> ### Describe your environment
> * Operating System version: Ubuntu 20.04.1 LTS
> * Firebase SDK version: 11.4.1
> * Firebase Product: Firebase Admin
> * Node.js version: 18.13.0
> * NPM version: 8.19.3
> 
> ### Describe the problem
> #### Steps to reproduce:
> Our NodeJS backend, running ExpressJS and using Firebase Admin SDK has been running smoothly for 2 years. All of a sudden, on the morning of the 17th of Jan, our service was interupted by a seemignly routine Firebase call made by our baseModel. This causes all requests to fail until we reboot the backend. Since then, the error has happened randomly every 2-6+ hours with thousands of OK requests in between. The error seems to stem from the Firebase Admin SDK package/its depencies.
> 
> #### Relevant Code:
> **Error Log:**
> 
> ```
> Jan 17 10:02:08 Error: 14 UNAVAILABLE: 403:Forbidden
> Jan 17 10:02:08 at Object.callErrorFromStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
> Jan 17 10:02:08 at Object.onReceiveStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:352:49)
> Jan 17 10:02:08 at Object.onReceiveStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
> Jan 17 10:02:08 at /app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
> Jan 17 10:02:08 at processTicksAndRejections (internal/process/task_queues.js:82:9)
> Jan 17 10:02:08 for call at
> Jan 17 10:02:08 at ServiceClientImpl.makeServerStreamRequest (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:336:30)
> Jan 17 10:02:08 at ServiceClientImpl.<anonymous> (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
> Jan 17 10:02:08 at /app/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:205:29
> Jan 17 10:02:08 at /app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
> Jan 17 10:02:08 at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
> Jan 17 10:02:08 at Object.request (/app/node_modules/google-gax/build/src/streamingCalls/streaming.js:126:40)
> Jan 17 10:02:08 at Timeout.makeRequest [as _onTimeout] (/app/node_modules/retry-request/index.js:139:28)
> Jan 17 10:02:08 at listOnTimeout (internal/timers.js:531:17)
> Jan 17 10:02:08 at processTimers (internal/timers.js:475:7)
> Jan 17 10:02:08 Caused by: Error
> Jan 17 10:02:08 at Firestore.getAll (/app/node_modules/@google-cloud/firestore/build/src/index.js:902:23)
> Jan 17 10:02:08 at DocumentReference.get (/app/node_modules/@google-cloud/firestore/build/src/reference.js:211:32)
> Jan 17 10:02:08 at Function.<anonymous> (/app/dist/models/baseModel.js:278:62)
> Jan 17 10:02:08 at Generator.next (<anonymous>)
> Jan 17 10:02:08 at /app/dist/models/baseModel.js:31:71
> Jan 17 10:02:08 at new Promise (<anonymous>)
> Jan 17 10:02:08 at __awaiter (/app/dist/models/baseModel.js:27:12)
> Jan 17 10:02:08 at Function.findById (/app/dist/models/baseModel.js:274:16)
> Jan 17 10:02:08 at /app/dist/routes/routeUtils.js:62:42
> Jan 17 10:02:08 at Generator.next (<anonymous>) {
> Jan 17 10:02:08 code: 14,
> Jan 17 10:02:08 details: '403:Forbidden',
> Jan 17 10:02:08 metadata: Metadata {
> Jan 17 10:02:08 internalRepr: Map {
> Jan 17 10:02:08 'content-type' => [Array],
> Jan 17 10:02:08 'content-length' => [Array],
> Jan 17 10:02:08 'date' => [Array],
> Jan 17 10:02:08 'alt-svc' => [Array]
> Jan 17 10:02:08 },
> Jan 17 10:02:08 options: {}
> Jan 17 10:02:08 }
> Jan 17 10:02:08 }
> ```
> 
> **Trickled down baseModel line from our code that does the Firebase fetch:**
> 
> ```
>    static findById(id, showDeleted = false) {
>         return __awaiter(this, void 0, void 0, function* () {
>             try {
>                 if (!id)
>                     throw new Error(`Invalid id provided for model ${this.name}`);
>                 const result = yield this.collection.doc(id).get();
>                 if (!result.exists)
>                     return null;
>                 if (!showDeleted && result.data().isDeleted)
>                     return null;
>                 return new this(Object.assign({}, result.data()));
>             }
>             catch (e) {
>                 console.error(e);
>             }
>         });
>     }
> ```
> 
> **Our package.json:**
> 
> ```
> "dependencies": {
>         "@sendgrid/mail": "^7.7.0",
>         "axios": "^1.2.3",
>         "cors": "^2.8.5",
>         "crypto-js": "^4.1.1",
>         "express": "^4.17.1",
>         "firebase-admin": "^11.4.1",
>         "lodash": "^4.17.21",
>         "moment": "^2.29.4",
>         "morgan": "^1.10.0",
>         "nanoid": "^3.3.4",
>         "stripe": "^11.6.0",
>         "yup": "^0.32.11"
>     },
>     "devDependencies": {
>         "@types/cors": "^2.8.13",
>         "@types/crypto-js": "^4.1.1",
>         "@types/express": "^4.17.15",
>         "@types/lodash": "^4.14.191",
>         "@types/morgan": "^1.9.4",
>         "@types/node": "^18.11.18",
>         "@types/yup": "^0.32.0",
>         "@typescript-eslint/eslint-plugin": "^4.31.2",
>         "@typescript-eslint/parser": "^4.31.2",
>         "eslint": "^7.32.0",
>         "nodemon": "^2.0.4",
>         "ts-node": "^10.9.1",
>         "typescript": "^4.9.4"
>     }
> ```

I have the same issue. Need a fix for this.
