### ISSUE TITLE
Option to only accept connections to firebase emulator [FR]

### ISSUE THREAD

**Issue by honungsburk** [firebase/firebase-admin-node#2057]
**Is your feature request related to a problem? Please describe.**
I would like to guarantee that the admin SDK only connects to the firebase emulators.

**Describe the solution you'd like**
I want an option/flag that guarantees that the SDK only connects to the emulators.

```ts
import { initializeApp } from "firebase-admin/app";

const app = initializeApp({ emulatorOnly: true });
```

**Describe alternatives you've considered**
I've not yet found an easy and reliable way of checking what the SDK has connected to.

**Comment by lahirumaramba** [comment]
Would [setting the environment variables](https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks) help your use case?
```sh
export FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
```
You can also set the env vars in your code (in your test environment) if you prefer that.

```js
process.env.FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
process.env.FIREBASE_DATABASE_EMULATOR_HOST="localhost:9000"
process.env.FIRESTORE_EMULATOR_HOST="localhost:8080"
...
```

**Comment by honungsburk** [comment]
Yeah, that works. But is it guaranteed that it will not try to connect to the cloud instance if the emulator isn't running?

My Current Solution

```ts 

process.env.FIREBASE_AUTH_EMULATOR_HOST = "localhost:9099";
process.env.FIRESTORE_EMULATOR_HOST = "localhost:8080";
process.env.FIREBASE_STORAGE_EMULATOR_HOST = "localhost:9199";

const app = App.initializeApp({ projectId: "my-project" });

const config = {
  firestore: Firestore.getFirestore(app),
  auth: Auth.getAuth(app),
};

await Promise.all([
  axios.get(
    `http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/emulator/v1/projects/my-project/config`
  ),
]).catch(() => {
  console.log("Could not connect to firebase emulators");
  process.exit(1);
});
```

**Comment by lahirumaramba** [comment]
Yes, if the environment variables are set, the admin SDK will only try to connect to the emulator. This is true for the services that comes with emulator support (Auth, Firestore, etc.) and only if the corresponding environment variables are set in the environment.
