### ISSUE TITLE
[Security Issue] in tiffyDB in package.lock.json

### ISSUE THREAD

**Issue by thanhtutzaw** [firebase/firebase-admin-node#2061]
**I got security alert from GitHub Bot . How to solve it ? Should I uninstall firebase-admin ?**
https://github.com/firebase/firebase-admin-node/blob/master/package-lock.json#L5758
### Taffy
https://www.npmjs.com/package/taffy 

![image](https://user-images.githubusercontent.com/71011043/215650736-37672fc2-b4ac-4efa-a81f-595718e4bfb8.png)

![Screenshot (157)](https://user-images.githubusercontent.com/71011043/215649861-bcbd8f1f-f4d0-45a1-9bcd-e558767e7f16.png)

**Comment by lahirumaramba** [comment]
`tiffyDB` is not a direct dependency of `firebase-admin`. This needs to be fixed in `google-gax` first. We are tracking the issue in https://github.com/firebase/firebase-admin-node/issues/1976

**Comment by lahirumaramba** [comment]
Thanks for your patience. Addressed in #1976
