### ISSUE TITLE
There are 3 vulnerable dependencies according to nsp

### ISSUE THREAD

**Issue by THPubs** [firebase/firebase-admin-node#207]
Hi, this package has three vulnerable dependencies according to nsp. Namely, `mime`, `request` and `hawk` which come from the packages `@google-cloud/storage@1.5.2`. Please check and update them.

**Comment by THPubs** [comment]
Reported in the `@google-cloud/storage` package: https://github.com/googleapis/nodejs-storage/issues/134 . Please update this package when they fix the issue.

**Comment by THPubs** [comment]
The package `@google-cloud/storage` has been updated with new dependencies! Can you please update yours to include the latest version of it?

**Comment by hiranya911** [comment]
Cutting too close to the release currently in progress. Will include in the following patch release.

**Comment by THPubs** [comment]
@hiranya911 Great thnaks!
