### ISSUE TITLE
[FR] Better type support for Firestore.doc, Firestore.collection and Firestore.collectionGroup

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-admin-node#2098]
`Firestore.doc(...)`, `Firestore.collection(...)` and `Firestore.collectionGroup(...)` all return Typed return value and the type is carried over nicely to all underlying functions.

However, we have no way to actually nicely input the type. This forces to write code that is prone to breaking as it contains casts:
```ts
const collectionRef = firestore.collection('contracts/' + customerKey + '/drafts') as CollectionReference<ContractDraft>
```

The correct TS way would be to be able to write
```ts
firestore.collection<ContractDraft>('contracts/' + customerKey + '/drafts')....
```

The current type is
```ts
collection(collectionPath: string): CollectionReference<DocumentData>;
```

It should be 
```ts
collection<T = DocumentData>(collectionPath: string): CollectionReference<T>
```

The same should be applied for .doc and .collectionGroup.

**Comment by swftvsn** [comment]
Ah, this it actually the types in @google-cloud/firestore package. Issue here: https://github.com/googleapis/nodejs-firestore/issues/1792

**Comment by dconeybe** [comment]
I'll be addressing this in the nodejs-firestore repository in the foreseeable future. See the linked issue above for details.
