### ISSUE TITLE
what's happen with signInWithEmailAndPassword?

### ISSUE THREAD

**Issue by eudago** [firebase/firebase-admin-node#210]
Why delete method signInWithEmailAndPassword, is not possible sign in with a nodejs server?

**Comment by bojeil-google** [comment]
`signInWithEmailAndPassword` was never supported in the Admin SDK. You would need to use the `firebase` client library in order to do so.

**Comment by eudago** [comment]
And use two dependences only for one feature?

```
const firebase = require('firebase');
const admin   = require("firebase-admin");

```

**Comment by bojeil-google** [comment]
Please explain your use case. If you just want to sign in a user. You should just stick to the client SDK. 

Firebase Admin SDK has no sign-in APIs and is meant for user management and administrative purposes. The client API is designed for the former.

**Comment by eudago** [comment]
I will create a api (/login aka /signin) because I use the firebase only on the server.

My only solution is use firebase web sdk in my nodejs server?

**Comment by hiranya911** [comment]
Admin SDKs are used to implement privileged server-side use cases, and therefore do not support client authentication operations. You should use the Web SDK, and get your end users to authenticate directly from their web browsers (Node.js server is not required for this). If you wish to execute some privileged operation on your Node.js server on behalf of an end user, you can get them to send their ID tokens to the server, where they can be validated using the Admin SDK.

I've written about some of these subtleties at https://medium.com/google-cloud/firebase-the-server-side-story-1f89064e9c16
