### ISSUE TITLE
Firebase and Firebase-admin Modules won't let me access the .auth() object on them to use the accompanying methods

### ISSUE THREAD

**Issue by LanceSamaria** [firebase/firebase-admin-node#211]
**Describe your environment:**
-2011 Macbook Pro
-OS High Sierra v10.13.3
-Sublime Version 3.0, Build 3143
-Node 7.8.0
-Firebase package v4.6.0
-Firebase-admin package v5.4.3
-Firebase Database, Firebase Storage

First let me say that I contacted the Firebase Technical Support team https://firebase.google.com/support/contact/troubleshooting/ about this issue and I also posted a question on Stackoverflow [https://stackoverflow.com/questions/47081163/firebase-node-js-auto-complete-doesnt-show-auth-or-its-accompanying-method](url)  about it but no one answered it. I'm not sure why when pressing the ink it won't take you to the page but if you copy and paste it into the browser it will work.

The Firebase tech team member said they couldn't resolve it and told me to file a bug report at this repo.

![screen shot 2018-02-19 at 2 42 18 pm](https://user-images.githubusercontent.com/36642507/36394643-42a796e8-1583-11e8-93db-a696ff8b4053.png)

**Describe your problem:**
I have installed the Firebase and Firebase-admin modules into the app.js file. I want to use these 2 methods:

```
.createCustomToken()
.authenticateWithCustomToken()
```

**The problem is they both get called on a .auth() object and I cannot access the .auth() object to access them:**

```
var myCustomToken = '12345'

myCustomToken = firebaseAdmin.auth().createCustomToken(myCustomToken) //firebaseAdmin.auth()

firebase.auth().authenticateWithCustomToken(myCustomToken) // firebase.auth()
```

The reason I want to use these is because I want to create a custom token so I can login into firebase with safe security rules. Without creating the token firebase won't let my app.js file read any data. I'm using a service named Algolia to run searches on my Firebase database and their tech team suggested I login that way:

[https://discourse.algolia.com/t/firebase-rules-doesnt-let-algolia-run-node-js-searches-unless-rules-are-set-to-true/3516](url)

Can you please get the .auth() object to appear on **Both** the **firebase** and **firebase-admin** modules so I can access the 2 methods I need? Look at the autocomplete results on **line 14** and **line 25** in the pictures below and you can see that **.auth()** doesn't appear in the list.
![screen shot 2018-02-19 at 2 12 26 pm](https://user-images.githubusercontent.com/36642507/36393792-209c85f8-157f-11e8-9baf-57d2242498d7.png)
![screen shot 2018-02-19 at 2 12 49 pm](https://user-images.githubusercontent.com/36642507/36393795-2273ff00-157f-11e8-9323-e2c6df22b730.png)

**Steps to reproduce:**

1. created a folder, ran `npm init`, downloaded the firebase service account json file, added the info from there that is needed to the app.js file, ran these below commands, and finally hooked everything up to a heroku instance
```
$ npm install —-save
$ npm install dotenv --save
$ npm install firebase-admin --save
$ npm install algoliasearch --save
$ npm install firebase --save
$ npm install -g firebase-tools
$ npm install -g npm-install-missing
```

**Comment by avishalom** [comment]
Have a look at https://firebase.google.com/docs/admin/setup
and https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk 

for `createCustomToken()`

As for the client part, did you try `signInWithCustomToken()` ?

(You can also have a look at how this is used in the integration tests) in https://github.com/firebase/firebase-admin-node.

**Comment by hiranya911** [comment]
`firebase-admin` exports the `auth()` function as you would expect:  https://github.com/firebase/firebase-admin-node/blob/master/src/index.d.ts#L57

See how it's been used in our integration tests to create custom tokens: https://github.com/firebase/firebase-admin-node/blob/master/test/integration/auth.spec.ts#L281

It also shows up in IDE suggestions as far as I can tell (tested with latest VS Code). I've noticed that some IDE environments/versions do not handle this properly, but the `auth()` function is definitely available in the `firebase-admin` namespace, and can be used without issues.

**Comment by LanceSamaria** [comment]
@hiranya911 someone else on SO suggested VSCode. I haven't used that before nut I'm watching some tutorials now. If I understand you correctly even though .auth() doesn't appear on the auto complete when using Sublime 3, I can still go ahead and use .auth() with the methods I need by manually typing it and them and they will still work?

**Comment by hiranya911** [comment]
@LanceSamaria yes, it will work. You can also check the installed JS files to verify this. For example I see the following in my `node_modules/firebase-admin/lib/firebase-namespace.js` file:

```
Object.defineProperty(FirebaseNamespace.prototype, "auth", {
        /**
         * Gets the `Auth` service namespace. The returned namespace can be used to get the
         * `Auth` service for the default app or an explicitly specified app.
         */
        get: function () {
            var _this = this;
            var fn = function (app) {
                return _this.ensureApp(app).auth();
            };
            return Object.assign(fn, { Auth: auth_1.Auth });
        },
        enumerable: true,
        configurable: true
    });
```

This means the `auth()` function exists in the installed Admin SDK library. If you get any runtime errors, report them back here and we can take a look.

**Comment by LanceSamaria** [comment]
@hiranya911 Thank you very much. Everything is working fine now. Enjoy your day! :)
