### ISSUE TITLE
DocumentRef.update() does not respect withConverter setting

### ISSUE THREAD

**Issue by 0xJem** [firebase/firebase-admin-node#2116]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 13.2.1
  * Firebase SDK version: 11.5.0 of firebase-admin
  * Firebase Product: database
  * Node.js version: 18.2.1
  * NPM version: yarn 8.19.2

#### Steps to reproduce:

1. Obtain a DocumentReference from a collection with the converter set.
```
  const firestoreClient = new firestore.Firestore();
  firestoreClient.settings({ ignoreUndefinedProperties: true });

  const testRef = firestoreClient
    .collection("tests")
    .withConverter(TestConverter)
    .doc(testId);
```

2. Call `testRef.update()` with data.
```
testRef.update({
 key: value,
});
```

The functions in the converter, TestConverter, are not called.

However, if the following is performed instead, the functions in TestConverter are called:
```
testRef.set({
 key: value,
}, { merge: true});
```

**Comment by lahirumaramba** [comment]
Hi @0xJem,

Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.

Thanks!

**Comment by 0xJem** [comment]
Ah, thanks for the correction!

**Comment by 0xJem** [comment]
That makes sense... but this nuance not mentioned in the documentation, nor is it explicitly mentioned that the converter will not be used.

For example, it is not mentioned here: https://cloud.google.com/firestore/docs/manage-data/add-data#update-data

**Comment by cherylEnkidu** [comment]
Hi @0xJem , if you search for `overwrit` keyword, you will find several sentences mentioning about this difference. But we agree this subtle difference needs to highlight and the team is working on this.

**Comment by 0xJem** [comment]
> Hi @0xJem , if you search for `overwrit` keyword, you will find several sentences mentioning about this difference. But we agree this subtle difference needs to highlight and the team is working on this.

Overwrite is mentioned 3 times on the page that I linked to, but nowhere does it mention that the converter will not be used.
