### ISSUE TITLE
TypeError: Cannot assign to read only property 'toJSON' of object 'Error'

### ISSUE THREAD

**Issue by JuergenSimon** [firebase/firebase-admin-node#215]
* Operating System version: macos 10.12.6, Node 9.5.0
  * Firebase SDK version: 5.9.0
  * Library version: 4.10.1
  * Firebase Product: admin (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
Installed firebase-admin using instructions here: https://www.npmjs.com/package/firebase-admin
Added firebase-admin to a module as instructed using:
```
var admin = require('firebase-admin');
```

in a module in a loopback node application. Application fails to start with the following error:

```
/Users/simon/Projects/APPICS/src/appics-backend/node_modules/firebase-admin/lib/utils/error.js:65
    FirebaseError.prototype.toJSON = function () {
                                   ^

TypeError: Cannot assign to read only property 'toJSON' of object 'Error'
    at /Users/abcdefg/Projects/APPICS/src/appics-backend/node_modules/firebase-admin/lib/utils/error.js:65:36
    at Object.<anonymous> (/Users/simon/Projects/APPICS/src/appics-backend/node_modules/firebase-admin/lib/utils/error.js:72:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/abcdefg/Projects/APPICS/src/appics-backend/node_modules/firebase-admin/lib/firebase-namespace.js:21:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
Waiting for the debugger to disconnect...

Process finished with exit code 1

```

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
'use strict';

let admin = require("firebase-admin");
```

**Comment by hiranya911** [comment]
What happens if you try this without loopback?

**Comment by JuergenSimon** [comment]
Sorry, that does not compute. This is a loopback application (basically it's a express application). I can't just run the car without the motor.

**Comment by hiranya911** [comment]
Try it without loopback to see if it's a loopback-specific issue.

**Comment by JuergenSimon** [comment]
Alright, so I tried this simply (in an extra file):

```
'use strict';
let admin = require("firebase-admin");
admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: 'https://appics-push.firebaseio.com'
});
```

And I got no exception.

**Comment by hiranya911** [comment]
So far we have only received this one report about this problem. Since the problem appears to be specific to the Loopback environment, I think we need somebody from that project to take a look. If somebody thinks this is something that can be fixed in firebase-admin, please provide some details on the diagnosis and the fix, so we can follow up.

**Comment by abdurahmanadilovic** [comment]
I also have this issue, it appears that it's linked with the usage of 'use strict' mode. I found some info on this [mozzila dev network link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only). 

Can strict mode be used alongside firebase admin?

**Comment by hiranya911** [comment]
Hey @abdurahmanadilovic. Do you have a repro for this issue? Ideally something that just uses TypeScript and no other frameworks? The original reporter of this issue could only repro the problem on Loopback.

**Comment by abdurahmanadilovic** [comment]
I used this command to figure out where `toJSON` is defined as a read only property on `Error` objects

```sh
grep -r 'Object.defineProperty(Error.*' .
````

It was in my application code and not in any package. I just added `writable: true` to `Object.assignProperty` call and that fixed the issue.

@JuergenSimon can you please run the grep command and check where `toJSON` is defined as a read only property?
