### ISSUE TITLE
[Firestore] Regional endpoint support?

### ISSUE THREAD

**Issue by ottob** [firebase/firebase-admin-node#2159]
This seems to be a new feature. In the [documentation](https://cloud.google.com/firestore/docs/regional-endpoints#set_a_regional_endpoint) there are currently only examples for Java and Python.

Is this feature not yet available in the node library? If it is, how can I specify regional endpoint?

**Comment by MarkDuckworth** [comment]
Looks like you specify the regional endpoint through the `host` setting, which is available in the Node.js library. 

```
    const db = initializeFirestore(app);

    db.settings({
        host: 'us-east1-firestore.googleapis.com'
    });

    await db.collection("foo").add({time: Date.now()});
    const result = await db.collection("foo").get();
    ```
    
    @morganchen12 do you know why the documentation for this feature only covers Java and Python?

**Comment by MarkDuckworth** [comment]
@lahirumaramba The snippets for other libraries have not been generated, but the `host` setting can be used in any SDK to set a regional endpoint. DevRel is aware of this gap. You may choose to close this ticket.

**Comment by lahirumaramba** [comment]
Thank you @MarkDuckworth !
