### ISSUE TITLE
[FR] Workload Identify Federation 

### ISSUE THREAD

**Issue by enchorb** [firebase/firebase-admin-node#2168]
This library does not work with the credential generated by WLIF (type "external_account").

WLIF is recommended best practice across all Google docs, and other Google libraries / Firebase libraries in different languages have support for this.

**Comment by lahirumaramba** [comment]
Duplicate of #1377 
We are currently working on migrating credentials to `google-auth-library-nodejs`, which will fix this issue. Please follow #1377 for updates.
