### ISSUE TITLE
subscribeToTopic throwing  authenticate to the FCM servers error

### ISSUE THREAD

**Issue by preteambuy** [firebase/firebase-admin-node#2176]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: ___MAC Ventura 13.3.1__
  * Firebase SDK version: __9.5.0___
  * Firebase Product: __Messaging___ (auth, database, storage, etc)
  * Node.js version: __12.16.3___
  * NPM version: __6.14.4___

### [REQUIRED] Step 3: Describe the problem

Trying to register tokens to topic throws Authentication error.
#### Steps to reproduce:

admin.messaging().subscribeToTopic(deviceToken, topicName)

The above throws FCM authentication error

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

 {
    index: 0,
    error: FirebaseMessagingError: An error occurred when trying to authenticate to the FCM servers. Make sure the credential used to authenticate this SDK has the proper permissions. See https://firebase.google.com/docs/admin/setup for setup instructions.
        at FirebaseMessagingError.FirebaseError [as constructor] (/Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/utils/error.js:44:28)
        at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/utils/error.js:90:28)
        at new FirebaseMessagingError (/Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/utils/error.js:256:16)
        at Function.FirebaseMessagingError.fromTopicManagementServerError (/Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/utils/error.js:304:16)
        at /Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/messaging/messaging.js:146:63
        at Array.forEach (<anonymous>)
        at mapRawResponseToTopicManagementResponse (/Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/messaging/messaging.js:142:26)
        at /Users/predeep/git/talentd_bl/node_modules/firebase-admin/lib/messaging/messaging.js:623:20
        at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      errorInfo: [Object],
      codePrefix: 'messaging'
    }
  }

#### Relevant Code:

```
try {
        admin.messaging().subscribeToTopic(deviceToken, topicName)
            .then(function(response) {
                console.log('Successfully subscribed to topic:', response);
                console.log(response["errors"]) //it has the error 
            })
            .catch(function(error) {
                console.log('Error subscribing to topic:', error);
            });
    }catch(e){
        console.log(e);
    }
```

**Comment by chong-shao** [comment]
Sorry for the delay in reply.  For this type of issue investigation I'd recommend filing a Firebase support ticket from https://firebase.google.com/support/troubleshooter/contact . Thanks!
