### ISSUE TITLE
[FR] Support for Firebase In App Messaging

### ISSUE THREAD

**Issue by Ethan1983** [firebase/firebase-admin-node#2184]
**Is your feature request related to a problem? Please describe.**

We would like to use Firebase Cloud Functions (using Admin SDK) to send Firebase In App Messages programatically based on real time data generated in Cloud Firestore. Currently, Admin SDK supports only FCM Notifications.

**Describe the solution you'd like**

Admin SDK (https://firebase.google.com/docs/admin/setup) to support Firebase In App Messaging.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by chong-shao** [comment]
Hello, currently we can't provide a timeline for supporting this feature. Will close this for now.

**Comment by pikonek** [comment]
Hi @chong-shao is this already supported?

**Comment by chong-shao** [comment]
Hi @pikonek  If I understand correctly this is not supported.

**Comment by Ethan1983** [comment]
@chong-shao Is there any other work around?

**Comment by nccapo** [comment]
Any news about this feature?
