### ISSUE TITLE
no such file or directory, open '...grpc/node_modules/dashdash/node_modules/assert-plus/package.json.3046197349'

### ISSUE THREAD

**Issue by jesperlandmer** [firebase/firebase-admin-node#222]
### [REQUIRED] Step 2: Describe your environment

  * Environment: Vagrant 1.8.6
  * Platform: Node.js 8.9.4
  * Firebase SDK version: 5.8.1
  * Library version: NPM
  * Firebase Product: functions

#### Steps to reproduce:

Setted up the functions directory like this:

`$ firebase init functions`
`$ cd functions`

Installed the dependencies (i.e. firebase-admin v5.8.1):
`$ sudo npm install`

Gets this error:
```
npm ERR! path /vagrant/cloud/functions/node_modules/@google-cloud/common-grpc/node_modules/grpc/node_modules/dashdash/node_modules/assert-plus/package.json.3046197349
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/cloud/functions/node_modules/@google-cloud/common-grpc/node_modules/grpc/node_modules/dashdash/node_modules/assert-plus/package.json.3046197349'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
Using firebase-admin version 5.2.1 works.

**Comment by hiranya911** [comment]
@schmidt-sebastian can we run this by the grpc team as well?

**Comment by schmidt-sebastian** [comment]
@jesperlandmer Are you still facing this issue? We haven't had any reports of similar nature and would recommend that you completely remove your node_modules and try to install again. Sorry for the trouble!

**Comment by marshmellow1328** [comment]
These 2 issues appear to be related: https://github.com/firebase/firebase-js-sdk/issues/1234
@jesperlandmer, what OS are you using for your Vagrant box? I'm trying to figure out if it's a Vagrant-related problem with grpc or an OS-related problem.

**Comment by hiranya911** [comment]
I'm closing this since there hasn't been any reports of this recently. Lets keep an eye on the issue reported for grpc for any updates.
