### ISSUE TITLE
[FR] How to property initialize firebaseConfig with 2nd gen functions runtime?

### ISSUE THREAD

**Issue by 0xunreal** [firebase/firebase-admin-node#2222]
**Is your feature request related to a problem? Please describe.**
The globally initialized singleton of firebaseAdmin cannot be initialized using the new parameterized configuration feature of 2nd gen functions. 

**Describe the solution you'd like**
A code sample/documentation on how to deal with this scenario.

**Describe alternatives you've considered**
Staying on 1st gen for now, but it would be better to upgrade.

**Additional context**
`const firebaseConfig = {
    privateKey: privateKey.value().replace(/\\n/g, '\n'),
    projectId: projectId.value(),
    clientEmail: clientEmail.value(),
  };

firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.cert(firebaseConfig),
});`

throws an error:
`{"severity":"WARNING","message":"params.PRIVATE_KEY.value() invoked during function deployment, instead of during runtime."}
{"severity":"WARNING","message":"This is usually a mistake. In configs, use Params directly without calling .value()."}
{"severity":"WARNING","message":"example: { memory: memoryParam } not { memory: memoryParam.value() }"}
{"severity":"WARNING","message":"params.PROJECT_ID.value() invoked during function deployment, instead of during runtime."}
{"severity":"WARNING","message":"This is usually a mistake. In configs, use Params directly without calling .value()."}
{"severity":"WARNING","message":"example: { memory: memoryParam } not { memory: memoryParam.value() }"}
{"severity":"WARNING","message":"params.CLIENT_EMAIL.value() invoked during function deployment, instead of during runtime."}
{"severity":"WARNING","message":"This is usually a mistake. In configs, use Params directly without calling .value()."}
{"severity":"WARNING","message":"example: { memory: memoryParam } not { memory: memoryParam.value() }"}`

related SO article: https://stackoverflow.com/questions/76323571/how-to-properly-initialize-custom-class-instance-with-parameterized-configuratio

**Comment by lahirumaramba** [comment]
Looks like the answer in SO explains the error message you get. `In configs, use Params directly without calling .value().`

I am closing this assuming you already fixed the issue. We can reopen later if needed.
