### ISSUE TITLE
[firebase-admin/firestore] Missing export for AggregateQuery, AggregateQuerySnapshot

### ISSUE THREAD

**Issue by bdaz** [firebase/firebase-admin-node#2229]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 13.13.1
  * Firebase SDK version: firebase-admin v11.9.0
  * Firebase Product: Admin.firestore
  * Node.js version: v1
  * NPM version: v7.XX

### [REQUIRED] Step 3: Describe the problem
firebase-admin/firestore does not export `AggregateQuery` or `AggregateQuerySnapshot`.

#### Steps to reproduce:
`import { AggregateQuery } from 'firebase-admin/firestore'`

results in:

`Module '"firebase-admin/firestore"' has no exported member 'AggregateQuery'`

**Comment by cherylEnkidu** [comment]
Hi @bdaz ,

Both `AggregateQuery` and `AggregateQuerySnapshot` is not available in production yet. Please feel free to use count directly. https://firebase.google.com/docs/firestore/query-data/aggregation-queries#node.js
