### ISSUE TITLE
FR: Shallow Support

### ISSUE THREAD

**Issue by dgadelha** [firebase/firebase-admin-node#223]
### Environment

  * Operating System version: Google Cloud Functions
  * Library version: 5.9.1
  * Firebase Product: Database

### Description

Is there any way we can implement `shallow` in Database Admin Node.js SDK for usage with `.ref(ref).once('value')`?

### Relevant Links:

https://firebase.google.com/docs/database/rest/retrieve-data#shallow

https://github.com/firebase/firebase-admin-python/issues/61

**Comment by hiranya911** [comment]
This cannot be supported on the websocket interface as far as I know. You can follow up at https://github.com/firebase/firebase-js-sdk where the RTDB client code is developed, but the answer is most likely no.
