### ISSUE TITLE
FR: support createCustomToken using default google credentials

### ISSUE THREAD

**Issue by manishtpatel** [firebase/firebase-admin-node#224]
Firebase functions need custom credentials to use createCustomToken() for now. Looks like a missing functionality, we need to manage different credentials for each environment just to use createCustomToken(). There is no reason to not support createCustomToken() using default google credentials.

**Comment by manishtpatel** [comment]
In a second thought could be encryption of the token issue with different credentials.

**Comment by hiranya911** [comment]
@manishtpatel This is in our roadmap. Can't provide a specific timeline yet, but please know that this is definitely something we wish to support.

**Comment by sbnon** [comment]
Coming from <https://github.com/firebase/firebase-functions/issues/3>.

With Firebase Functions v1.0 no longer supporting manually setting the certificate; is there any update on this? Alternatively, can support be added back to the Admin API to allow manually setting the certificate?

Is there an alternative way to enable createCustomToken on Firebase Functions?

**Comment by raymondma1** [comment]
+1

**Comment by hiranya911** [comment]
`admin.initializeApp()` still accepts the [same parameters](https://firebase.google.com/docs/reference/admin/node/admin#.initializeApp) as before -- nothing has changed here. You can parse a service account file, and specify a certificate credential as shown here: https://firebase.google.com/docs/admin/setup#initialize_the_sdk

Firebase Auth and Admin SDK will make this use case easier to implement in a future release, but for now you should manually pass the certificate credential.

**Comment by raymondma1** [comment]
@hiranya911 Yup, did that instead and works fine! Thanks

**Comment by hiranya911** [comment]
I've started making some progress towards supporting this use case (creating custom tokens without a service account). My first attempt is now undergoing testing in the https://github.com/firebase/firebase-admin-node/tree/hkj-jwt-sign branch. Stay tuned.

**Comment by camstuart** [comment]
+1

**Comment by hiranya911** [comment]
This feature is now implemented.
