### ISSUE TITLE
[Firestore]  Servertimestamp is no defined

### ISSUE THREAD

**Issue by ivanandresdiaz** [firebase/firebase-admin-node#2258]
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: windows 10
  * Firebase SDK version:  "firebase-admin": "^11.10.1",
  * Firebase Product: Firestore
  * Node.js version: v18.16.0
  * NPM version: 9.8.0
  * Typescript

#### Steps to reproduce:

What happened? How can we make the problem occur?

I am using cloud functions and the firebase-admin SDK. 
So I upgraded the firebase-admin from`10.0.2` to `11.10.1`.

I had this global Variable from the timestamp in Cloud functions 

`
// utils\serverTimestamp.js
import * as admin from "firebase-admin";

const serverTimestamp = admin.firestore.FieldValue.serverTimestamp;
`

it showed me this error:

```
TypeError: Cannot read properties of undefined (reading 'serverTimestamp')
    at Object.<anonymous> (C:\Users\ivana\Documents\functions\lib\utils\serverTimestamp.js:
```

This will print Firestore logs to the console.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
// 1. Download cloud functions. 

import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

export const helloWorld = functions.https.onRequest((request, response) => {
// Here it is the error
  const timestamp = admin.firestore.FieldValue.serverTimestamp();
// Here it is the error
  console.log("timestamp", timestamp);
  response.send("Hello from Firebase!");
});

```
 ERROR in console 

```
TypeError: Cannot read properties of undefined (reading 'serverTimestamp')
    at Object.<anonymous> (C:\Users\ivana\Documents\functions\lib\utils\serverTimestamp.js:
```

 Maybe the problem is the version Node  v18.16.0 that I am using. or maybe this can be an important issue

**Comment by lahirumaramba** [comment]
Please see my comment here: https://github.com/firebase/firebase-admin-node/discussions/1959#discussioncomment-3985176

**Comment by seth-stitik** [comment]
@lahirumaramba life saver 🙏
