### ISSUE TITLE
[Firestore]    Precondition .update( { field: 1 }, { exists: true }) not working.

### ISSUE THREAD

**Issue by ivanandresdiaz** [firebase/firebase-admin-node#2260]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: windows 10
  * Firebase SDK version: 10.0.2
  * Firebase Product: Firestore
  * Node.js version: v18.16.0
  * NPM version: 9.8.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
in cloud functions, I initialize de database. 
I want to update a Field only if it exists. Otherwise don't do it.

I was searching and I found that Update has a second argument  [Type](https://firebase.google.com/docs/firestore/reference/rest/v1/Precondition?hl=es-419) like this `admin.firestore.Precondition`. This is what the Type of precondition says For updating, the document has to exist
```
  export interface Precondition {
    /**
     * If set, the last update time to enforce.
     */
    readonly lastUpdateTime?: Timestamp;

    /**
     * If set, enforces that the target document must or must not exist.
     */
    readonly exists?: boolean;
  }

```

#### Relevant Code:
. So I use it but it throws me an error. 
```
// TODO(you): code here to reproduce the problem
  await db.collection("mycollection").doc("id").update(
          { field: 1 },
          {
// This is nor working
            exists: true,
          }
        );
```
### Error 
`
"error Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument \"preconditionOrValues\" is not a valid precondition. \"exists\" is not an allowed precondition.\n    at WriteBatch.update...
`. 

I understand based on the documentation, it should work.

**Comment by lahirumaramba** [comment]
Hi @ivanandresdiaz,
Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.

In the future please use StackOverflow for usage questions. Thanks!

**Comment by ehsannas** [comment]
As @lahirumaramba said, please use https://github.com/googleapis/nodejs-firestore repo for reporting issues. and StackOverflow for usage questions.

But now that we're here: the second parameter to the API should be an array of values or preconditions.
So the following should work:
```js
  await db.collection("mycollection").doc("id").update(
          { field: 1 },
          [{exists: true}]
        );
```
The error message can/should be improved though.
