### ISSUE TITLE
admin.messaging().sendEachForMulticast() caused no response with over 38 tokens

### ISSUE THREAD

**Issue by gouteru** [firebase/firebase-admin-node#2277]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Node16, cloud functions 4.4.1
  * Firebase SDK version: 11.10.1
  * Firebase Product: messaging
  * Could functions region: asia-notheast1

### [REQUIRED] Step 3: Describe the problem

First, I have seen APNS auth errors from the response of sendEachForMulticast, that error was mitigated on Aug 4 20:45 PDT.
However, some of my app users reported that they have not received push notification after the error was mitigated.
I have taken a look at my Cloud Functions log and found strange logs.

This log below 449 push notifications should be sent to each user but the response of admin.messaging().sendEachForMulticast() was never responded to because I could not find any okCount log.

> INFO 2023-08-05T08:14:40.737267Z  sendPushNotification  tokens.length: 449

okCount 449 log should be output but no log found.

This case, no push notification was sent to users.

After the strange no response above, the below log indicates that my cloud function is working properly because okCount 38 responded after sendPushNotification log.

> INFO 2023-08-05T08:48:29.247598Z  sendPushNotification schoolId, tokens.length: 38
> INFO 2023-08-05T08:49:52.992594Z  okCount: 38

I can see other logs that small number of push notification tokens (less than 38), admin.messaging().sendEachForMulticast() was responded to properly. but over 38 (could be more), for instance 449 tokens case, sendEachForMulticast never responded and push notifications at that time never sent.
(I know sendEachForMulticast can send upto 500 tokens at a time.)

This no response issue is still on going.

> INFO 2023-08-08T23:36:57.444633Z sendPushNotification tokens.length: 448

No response and no okCount log  output.

Also, another error found when token length was 91, all 91 tokens were responded as ECONNRESET and okCount was 0.
```
2023-08-09 12:08:47.668 JST
sendEachForMulticast FirebaseAppError: Error while making request: Client network socket disconnected before secure TLS connection was established. Error code: ECONNRESET
    at /workspace/node_modules/firebase-admin/lib/utils/api-request.js:178:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorInfo: {
    code: 'app/network-error',
    message: 'Error while making request: Client network socket disconnected before secure TLS connection was established. Error code: ECONNRESET'
  },
  codePrefix: 'app'
}
```

This is impossible to debug at app developer side I need someone's support to solve this issue.

#### Steps to reproduce:

just send 448 tokens with sendPushNotification.

#### Relevant Code:

my payload template is the below. tokens is set by sendPushNotification(), 
```
      let base = {
        tokens: [],
        notification: {
          title: 'title',
          body: 'Hello'
        },
        data: {
          schoolId: schoolId,
          category: 'posts',
          itemId: itemId
        },
        android: {
          ttl: 259200, // 3 days in seconds
          priority: 'normal',
          notification: {
            sound: 'default'
          }
        },
        apns: {
          headers: {
            'apns-priority': '5',
            'apns-expiration': '10' 
          },
          payload: {
            aps: {
              badge: 1,
              sound: 'default'
            }
          }
        },
        webpush: {
          headers: {
            Urgency: 'high',
            TTL: '259200'
          }
        }
      }
```

my sendPushNotification function is the below.
```
async function sendPushNotification (schoolId, tokens, uniqueUIDs, payload, uiLang) {
  const schoolRef = fireStore.collection('/schools').doc(schoolId)
  const membersRef = schoolRef.collection('members')
  const maxTokens = 500

  functions.logger.log('sendPushNotification tokens.length: ', tokens.length)
  functions.logger.log('sendPushNotification payload: ', payload)

  if (tokens.length === 0) {
    return
  }

  let listUnits = Math.ceil(tokens.length / maxTokens)
  functions.logger.log('Math.ceil listUnits: ', listUnits)

  let emailMemberUIds = []
  let retryMemberTokens = []
  let retryMemberUIDs = []
  let errorMemberRefs = []
  let errorMemberObjs = []
  let okCount = 0
  for (let i = 0; i < listUnits; i++) {
    let len = maxTokens
    let tokensUnit = []
    let uniqueUIDsUnit = []
    if (i === (listUnits - 1)) {
      len = tokens.length - ((listUnits - 1) * maxTokens)
    }
    let idx = i * maxTokens
    for (let k = idx; k < (idx + len); k++) {
      tokensUnit.push(tokens[k])
      uniqueUIDsUnit.push(uniqueUIDs[k])
    }
    if (tokensUnit.length > 0) {
      payload.tokens = tokensUnit
      const response = await admin.messaging().sendEachForMulticast(payload)

      for (let j = 0; j < response.responses.length; j++) {
        const error = response.responses[j].error
        if (error) {
          if (error.code === 'messaging/invalid-registration-token' ||
            error.code === 'messaging/registration-token-not-registered') {
            functions.logger.error('sendEachForMulticast token error: ', uniqueUIDsUnit[j].uid, error)
            errorMemberRefs.push(membersRef.doc(uniqueUIDsUnit[j].id))
            errorMemberObjs.push({fcmToken: 'error'})
            emailMemberUIds.push(uniqueUIDsUnit[j])
          } else if (error.code === 'messaging/internal-error') {
            retryMemberTokens.push(tokensUnit[j])
            retryMemberUIDs.push(uniqueUIDsUnit[j])
            functions.logger.error('sendEachForMulticast Intenal Error: ', uniqueUIDsUnit[j].uid, error)
          } else {
            functions.logger.error('sendEachForMulticast Other Error: ', uniqueUIDsUnit[j].uid, error)
            emailMemberUIds.push(uniqueUIDsUnit[j])
          }
        } else {
          okCount += 1
        }
      }
    }
  }
  functions.logger.log('okCount: ', okCount)
  if (errorMemberRefs.length > 0) {
    functions.logger.log('Token error users update: ', errorMemberRefs.length)
    await updateDocs(fireStore, errorMemberRefs, errorMemberObjs)
  }

  if (retryMemberTokens.length > 0) {
    okCount = 0
    functions.logger.warn('Retry!! : ', retryMemberTokens.length)
    let reErrorMemberRefs = []
    let reErrorMemberObjs = []
    payload.tokens = retryMemberTokens
    const response = await admin.messaging().sendEachForMulticast(payload)

    for (let j = 0; j < response.responses.length; j++) {
      const error = response.responses[j].error
      if (error) {
        if (error.code === 'messaging/invalid-registration-token' ||
          error.code === 'messaging/registration-token-not-registered') {
          functions.logger.error('sendEachForMulticastretry token error: ', retryMemberUIDs[j].uid, error.code)
          reErrorMemberRefs.push(membersRef.doc(retryMemberUIDs[j].id))
          reErrorMemberObjs.push({fcmToken: 'error'})
        } else if (error.code === 'messaging/internal-error') {
          functions.logger.error('sendEachForMulticastRetry Internal Error: ', retryMemberUIDs[j].uid, error)
        } else {
          functions.logger.error('sendEachForMulticastRETRY Other Error: ', retryMemberUIDs[j].uid, error)
        }
        emailMemberUIds.push(retryMemberUIDs[j])
      } else {
        okCount += 1
      }
    }
    functions.logger.log('Retry okCount: ', okCount)

    if (reErrorMemberRefs.length > 0) {
      functions.logger.log('Retry token error users update: ', reErrorMemberRefs.length)
      await updateDocs(fireStore, reErrorMemberRefs, reErrorMemberObjs)
    }
  }

  if (emailMemberUIds.length === 0) {
    return
  }
  sendPushErrorEmail(emailMemberUIds, uiLang)
}
```

**Comment by Doris-Ge** [comment]
Hi @gouteru, thanks for the reporting the issue and sorry for the inconvenience!

> First, I have seen APNS auth errors from the response of sendEachForMulticast, that error was mitigated on Aug 4 20:45 PDT.   

Yes. As https://status.firebase.google.com/incidents/NowVgaeZF7G8Fbdh9jzU shows, there was an FCM incident on Aug 4, but it has been mitigated. I believe it has nothing to do with the issue of `sendEachForMulticast`.
 
> for instance 449 tokens case, sendEachForMulticast never responded and push notifications at that time never sent.

Also, it's expected that it takes more time for `sendEachForMulticast` to return if the `payload` contains more tokens. 449 tokens are way more than 38 tokens. So if `await admin.messaging().sendEachForMulticast(payload)` call never returned and no push notifications were sent, then it's very likely that the server was too busy to fullfill the requests at that time. I don't  know how Cloud Function works. Could it be possible that Cloud Function decides to kill a run of `sendPushNotification` call if it gets stuck at `sendEachForMulticast` and timed out? If so, then the `sendPushNotification` call for the 449 tokens case may be terminated before `sendEachForMulticast` returned. This could explain why there were neither error logs nor okCount log output. 

> Also, another error found when token length was 91, all 91 tokens were responded as ECONNRESET and okCount was 0.
If this only happens occasionally, then it appears to be some network issues that are out of our control.

I tried to reproduce the issue in my local environment, but I couldn't. I tried a few times and was able to successfully get a response for a `sendEachForMulticast` call with 500 tokens every time. 

Have you seen this no response issue with `sendEachForMulticast` happen before Aug 4? 
Is this issue still happening all the time for each `sendEachForMulticast` with more than 38 tokens?
If this issue only happens when calling `sendEachForMulticast` with a large number of tokens in the `payload` and it happens very frequently but not always, I would suggest to split a large `sendEachForMulticast` call into multiple small ones.  For example, send to at most 35 tokens via one `sendEachForMulticast` call.

**Comment by gouteru** [comment]
Thanks for response.
I haven't seen this type of error or no response cases before Aug 4. But I had recently changed messaging function from  sendToDevice() to sendEachForMulticast() due to sendToDevice was marked as deprecated.

And yes, it's happened almost every time when sendEachForMulticast called with over 38 tokens. 
So I did split a large number of tokens into multiple 35 tokens. 

This week is the Obon holiday in Japan, so few users are using it, so I'll see how it goes next week and report back.

**Comment by gouteru** [comment]
_split a large number of tokens into multiple 35 tokens_ worked fine. 
I can use this  for now and take a look deeper my function code. I realized probably somewhere in my function has non promised part and my function finished before sendEachForMulticast was finished.

**Comment by codesterLalit** [comment]
I am facing same issues, has anyone found the solution yet? Is it version specific issue?
