### ISSUE TITLE
[FR] Show warning if passing undefined value to Firestore's update()

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-admin-node#2284]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when passing an `undefined` value to `update()` call without any issue in the IDE/lint, but then getting a runtime error after the function is deployed.

**Describe the solution you'd like**
Show warning in IDE if an undefined value is passed to `update()`
```ts
const value: string | undefined = undefined

admin.firestore(app)
    .collection("collection")
    .doc("docId")
    .update({
        id: value // show a warning here
    })
```

**Comment by cherylEnkidu** [comment]
Hi @risalfajar, 
Given that in some scenarios `undefinded` is a valid use case, we cannot restrict the type here. If it is helpful in your case, consider setting `ignoreUndefinedProperties?: boolean;` to true in https://googleapis.dev/nodejs/firestore/latest/Firestore.html#settings

**Comment by cherylEnkidu** [comment]
Hi,

I will close this ticket for now, please feel free to reopen it if you have more concerns.
