### ISSUE TITLE
`firestore-admin/storage` `getDownloadURL` import/require produces ESLint/TS errors

### ISSUE THREAD

**Issue by as4** [firebase/firebase-admin-node#2292]
Hi there! I'm using cloud functions with `firebase-admin` version 11.10.1, so deps are here:

``` 
"dependencies": {
    "@google-cloud/pubsub": "^4.0.2",
    "@google-cloud/tasks": "^4.0.0",
    "firebase-admin": "^11.10.1",
    "firebase-functions": "^4.4.1"
}
```

I want to use `getDownloadURL` function which has been added to `firebase-admin/storage` package in version `11.10`, but WebStorm "sees" it in a different package and the following line:

```
import {getDownloadURL} from 'firebase-admin/lib/storage';
```

But with this I get an error in the functions console:

```
⚠  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/storage' is not defined by "exports" in /Users/<foo>/firebase/functions/node_modules/firebase-admin/package.json
```

If I change the line to this:

```
import {getDownloadURL} from 'firebase-admin/storage';
```

I get ESLint error then:

```
ESLint: Unable to resolve path to module 'firebase-admin/storage'.(import/no-unresolved)
```

To make it work I had to suppress the error by adding a directive:

```
// eslint-disable-next-line import/no-unresolved
import {getDownloadURL} from 'firebase-admin/storage';
```

Then it works finally.

I also can go with `require` like it's described in the docs:
https://firebase.google.com/docs/storage/admin/start#shareable_urls

But we don't use `require` on our project. I think something is wrong in `firebase-admin` module exporting or with TS types.

**Comment by lahirumaramba** [comment]
Hi @as4, please see: https://github.com/firebase/firebase-admin-node/discussions/1359#discussioncomment-977158 I think the issues are related.
