### ISSUE TITLE
Once in a few days i get 401 from APNS

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [firebase/firebase-admin-node#2294]
I have webhook wich is triggered randomly when users doing some things and sometimes firebase-admin messaging returns 401 when trying to send push. I cannot manualy reproduce it but it in logs.

here is my code

this init function is invoked upon server start in main.ts
```ts
const serviceAccount = require('../../../senioassist-fb.json');
export class AuthService {
   static init() {
        admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
        });
    }
}
```

and after i have 

```ts
export class PushNotificationsService {
try {
                await admin.messaging().send(messages[0]);
}} catch (err) {
            var m = messages.map(m => JSON.stringify(m)).join(' ;==============; ');
            errorLoggingService.logError(err, m, ErrorTag.PushNotification);
            isSuccess = false;
        }
```

any idea?

p.s. i found something similar here: https://github.com/firebase/firebase-functions/issues/579 maybe?

**Comment by chong-shao** [comment]
Sorry for the delay in reply.  For this type of issue investigation I'd recommend filing a Firebase support ticket from https://firebase.google.com/support/troubleshooter/contact . Thanks!
