### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by rishabhAjay** [firebase/firebase-admin-node#2320]
### Environment

  * Operating System version: Windows 10
  * Firebase SDK version: 11.11.0
  * Firebase Product:  Cloud Messaging
  * Node.js version: 18.17.1
  * NPM version: 9.8.1

### The Error:

After I upgraded firebase-admin to the latest version, this error popped up:

```shell
TypeError: Cannot read properties of undefined (reading 'match')
    at scanIdentifier (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:259:96)
    at parseName (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:317:29)
    at TagParser._parseNamePath (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:474:20)
    at TagParser.parseNamePathOptional (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:491:25)
    at TagParser.parse (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:769:34)
    at parseTag (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:790:26)
    at Object.parse (C:\Users\User\Desktop\Project\node_modules\doctrine\lib\doctrine.js:868:23)
    at build (C:\Users\User\Desktop\Project\node_modules\swagger-jsdoc\src\specification.js:227:39)
    at module.exports (C:\Users\User\Desktop\Project\node_modules\swagger-jsdoc\src\lib.js:32:10)
    at Object.<anonymous> (C:\Users\User\Desktop\Project\src\utils\swagger.ts:31:33)
```

I am using swagger-jsdoc(v6.2.5)

### Steps to reproduce:

I did some digging by console logging the incoming input from where the error was thrown:

```shell
PRINTING THE SOURCE FROM doctrine:
The FirebaseAuthRequestHandler constructor used to initialize an instance using a FirebaseApp.

@param app - The app used to fetch access tokens to sign API requests.
@constructor.
PRINTING THE SOURCE FROM doctrine:
The FirebaseAuthRequestHandler constructor used to initialize an instance using a FirebaseApp.

@param app - The app used to fetch access tokens to sign API requests.
@constructor.
```

There is a "." after the `@constructor` YAML definition. Was this intended? I removed this dot and reran the application. The error did not resurface after this change.

#### Relevant Code:

Screenshots of the path and code in the package:
<img width="851" alt="dotInConstructor" src="https://github.com/firebase/firebase-admin-node/assets/63163183/54fbdf05-73ee-4fa9-aac4-2a7db20fc616">

<img width="555" alt="2023-09-29 22_51_16-auth-api-request d ts - OIG-Nodejs - Visual Studio Code" src="https://github.com/firebase/firebase-admin-node/assets/63163183/1d083ed9-0223-4da8-8d36-a18de3041f56">

**Comment by lahirumaramba** [comment]
Thank you @rishabhAjay for filing this issue. Looks like a typo. Let's discuss on #2321

**Comment by ronakdiyora** [comment]
Still I am facing the same issue with below environment. This MR change is not reflected. Please check and verify 

### Environment

- Firebase SDK version: 11.11.0
- Firebase Product: Cloud Messaging
- Node.js version: 18.16.0
- NPM version: 9.5.1

**Comment by rishabhAjay** [comment]
Yeah. Just checked it by downloading the latest version of the package. That line of code apparently still persists. However, I was able to fix it by changing the paths in the `apis` field of the swaggerJSDoc options to only read the yaml specified in my route files instead of scanning the whole project(something like `src/routes/*`). @ronakdiyora

**Comment by ronakdiyora** [comment]
Thank you for quick reply @rishabhAjay. I tried using this way `apis: ['./routes/*.ts']` but for typescript that ".ts" is not recognizing the yaml swagger.

**Comment by rishabhAjay** [comment]
> Thank you for quick reply @rishabhAjay. I tried using this way `apis: ['./routes/*.ts']` but for typescript that ".ts" is not recognizing the yaml swagger.

is the YAML being added as comments within those `ts` files?
