### ISSUE TITLE
[Auth] Set the mail to null, to be able to clear the previous value.

### ISSUE THREAD

**Issue by ClubDelTaxi** [firebase/firebase-admin-node#2329]
### [READ] Step 1: Are you in the right place?

**Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.**

If you still think the problem is related to the code in this repository, then read on.

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Firebase Product: Auth
  * Node.js version: 18
  "firebase-admin": "^11.6.0",

#### Steps to reproduce:

I am working with the NodeJS Firebase Admin SDK on Node 18 ("firebase-admin": "^11.6.0") and I am facing the difficulty of removing a mail from a user, to free that mail and be able to use that mail in another user.

I already tried with:

```
const user = await admin.auth().updateUser(userId, {
  email: null,
  emailVerified: false,
});

```
and with

```
const user = await admin.auth().updateUser(userId, {
  email: '',
  emailVerified: false,
});
```

Of the ways I get the same error:
**'The email address is improperly formatted.'**

I think the Admin SDK has no way to perform this action
it's right?

**Comment by Xiaoshouzi-gh** [comment]
Email is not a deletable attribute.  Please see [here](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth-api-request.ts#L1413C1-L1420C1).  A workaround might be - updating the current account with a valid temp email address.

**Comment by ClubDelTaxi** [comment]
Understood, thanks for the response.
Thank you very much for your work, it helps many people
