### ISSUE TITLE
passwordPolicyConfig doesn't exist on projectConfigManager

### ISSUE THREAD

**Issue by jingconan** [firebase/firebase-admin-node#2333]
Hi Firebase team,

Our engineer still didn't find the passwordPolicyConfig doesn't exist on projectConfigManager. It is the same issue that is mentioned in https://github.com/firebase/firebase-admin-node/issues/2056

I wonder what's the status of that feature. Has it been GA'ed already? If not, when do we expect it will be GA? Looking forward to hearing from you. Thanks.

**Comment by majster** [comment]
I Had same issue because i was using older version of firebase-admin package. Can confirm it works with 11.11.0

**Comment by comicat-hu** [comment]
```
const projectConfigManager = getAuth(app).projectConfigManager();
const projectConfig = await projectConfigManager.getProjectConfig();
const passwordPolicy = projectConfig.passwordPolicyConfig;
```

it can works with 11.11.1

**Comment by lahirumaramba** [comment]
Closing as this seems to be resolved now.
