### ISSUE TITLE
Error: 2 UNKNOWN: Authentication backend unknown error

### ISSUE THREAD

**Issue by markmxr** [firebase/firebase-admin-node#2375]
### Describe your environment

  * Operating System version: Microsoft Windows Server 2022
  * Firebase SDK version: ^8.2.0
  * Firebase Admin: ^9.4.2
  * Firebase Product: Firestore
  * Node.js version: 16.19.1
  * NPM version: 9.8.1

This is happening on a NestJS API.

#### Relavent Issue
https://github.com/firebase/firebase-admin-node/issues/1903

^ Saw this closed thread and @cherylEnkidu said to make a new ticket.

We've been experiencing this issue for quite some time now and it's becoming more and more frequent. Over the last 7 days I've seen this error over a hundred times.

This is the same stack trace that appears on all errors
```
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js in Object.callErrorFromStatus at line 31:19
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js in Object.onReceiveStatus at line 352:49
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js in Object.onReceiveStatus at line 328:181
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js in <anonymous> at line 188:78
node:internal/process/task_queues in processTicksAndRejections at line 78:11
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js in ServiceClientImpl.makeServerStreamRequest at line 336:30
/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js in ServiceClientImpl.<anonymous> at line 105:19
/workspace/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js in <anonymous> at line 205:29
/workspace/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js in <anonymous> at line 38:28
/workspace/node_modules/google-gax/build/src/normalCalls/timeout.js in <anonymous> at line 44:16
/workspace/node_modules/google-gax/build/src/streamingCalls/streaming.js in Object.request at line 126:40
/workspace/node_modules/retry-request/index.js in makeRequest at line 139:28
/workspace/node_modules/retry-request/index.js in retryRequest at line 107:5
/workspace/node_modules/google-gax/build/src/streamingCalls/streaming.js in StreamProxy.setStream at line 117:37
/workspace/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js in StreamingApiCaller.call at line 54:16
/workspace/node_modules/@google-cloud/firestore/build/src/index.js in Firestore.getAll at line 902:23
...
```

Is there any other information I can provide that can help?

**Comment by bryan-d** [comment]
Also experiencing this issue for the past few days. We've been running the same code in production for the past few months and the issue has just recently come up without any changes on our end.

Any ideas?

**Comment by DevboiDesigns** [comment]
Also experiencing this issue

**Comment by kaushlakers** [comment]
We have also seen this error a few times in the last day. Code is pretty much unchanged.
```
{
  "code": 2,
  "details": "Authentication backend unknown error.",
  "metadata": {
    "www-authenticate": [
      "Bearer realm=\"https://accounts.google.com/\""
    ]
  },
  "note": "Exception occurred in retry method that was not classified as transient"
}
```

**Comment by cherylEnkidu** [comment]
Hi folks, sorry you are are still experiencing this issue. Please open the Firebase support ticket which requires project info. The backend engineers need the project id to further investigate the problem.

**Comment by lahirumaramba** [comment]
Closing this issue for now. Please open a Firebase support ticket per https://github.com/firebase/firebase-admin-node/issues/2375#issuecomment-1832796724
