### ISSUE TITLE
Managing users from Clodflare Workers

### ISSUE THREAD

**Issue by step135** [firebase/firebase-admin-node#2377]
The Cloudflare workers can not use Firebase Admin SDK, so the only way would be to make calls through Firebase Admin REST API, but those calls are anywhere described. How to create a new account? How to list users? How to disable any user? These are basic functionalities but anywhere described in documentation.

**Comment by step135** [comment]
There is no reaction after two months. Is this repo death?

**Comment by lahirumaramba** [comment]
This SDK requires a full Node.js environment and currently does not support other runtimes. Similar issue is tracked in #1801 

For REST API docs, you need to look for the correct reference for each service. For example, you can find Auth REST API docs on https://firebase.google.com/docs/reference/rest/auth

**Comment by step135** [comment]
How is it connected to Admin SDK? Give at least one example where AUTH REST API help to manage users?!
