### ISSUE TITLE
FR: export as namespace admin; in declaration file

### ISSUE THREAD

**Issue by ibrahimduran** [firebase/firebase-admin-node#239]
I've been trying to use admin.auth.DecodedIdToken in my global declaration file but I've found out that [`export = admin`](https://github.com/firebase/firebase-admin-node/blob/master/src/index.d.ts#L581) only exports types in `admin` without nested namespaces. I did a quick research and learned that `export as namespace admin;` can be used to whole namespace.

Is there any particular reason for not to export whole namespace?

**Comment by ibrahimduran** [comment]
I need to extend Express Request object to support user property on authenticated requests but currently DecodedIdToken interface is not accessible in a declaration file.
 
my_typing.d.ts
```ts
/// <reference types="express" />
/// <reference types="firebase-admin" />

declare module Express {
  export interface Request {
    user?: admin.auth.DecodedIdToken // Error: Cannot find namespace admin.
  }
}
```

**Comment by hiranya911** [comment]
Following seems to work for me (at least my IDE is happy with it):

```
import * as admin from 'firebase-admin';

declare module Express {
  export interface Request {
    user?: admin.auth.DecodedIdToken;
  }
}

```

**Comment by ibrahimduran** [comment]
VSCode also does not complain about it but I think it's because using top-level import statements causes a file to be treated as a source file. So as I know it's not possible to import from module in a global declaration file, in such case it breaks the whole declaration.

Compiler throws `Property 'user' does not exists on type 'Request'.` error for code above.

**Comment by hiranya911** [comment]
We use imports in our typings file: https://github.com/firebase/firebase-admin-node/blob/master/src/index.d.ts#L17

**Comment by ibrahimduran** [comment]
Yes, I'm aware of that import statements are used in modules declaration files. As I said:

> using top-level import statements causes a file to be treated as a source file

By source file what I really mean is module file. Module files have their own scope and have to be directly imported to use them as said in [Microsoft/TypeScript#5506](https://github.com/Microsoft/TypeScript/issues/5506#issuecomment-153254151).

What I'm really trying to achieve here is extend the Express.Request in a global declaration file instead of a module file that needs to be imported everywhere and strictly set as type of variables.

Here's the minimal reproduction [repository](https://github.com/ibrahimduran/firebase-admin-239-repro). Only way I managed to compile this code is using export as namespace admin;.

**Comment by LogansUA** [comment]
Hello.

I'm also suffering from this. I want to add type hinting for firebase message payload (i.e. [MessagingPayload](https://github.com/firebase/firebase-admin-node/blob/9fe20f0c64e35f2daeaa0df2c45ffce186804c0a/src/index.d.ts#L474) type, but since the `index.d.ts` export only admin namespace - I can't use anything from it 😞 

Here's an example
```typescript
import * as admin from 'firebase-admin';

export class PushService {
    /**
     * Generate payload
     *
     * @returns {admin.messaging.MessagingPayload}
     */
    public generatePayload(): admin.messaging.MessagingPayload {
        return {
            notification: {
                title: 'Title',
                text: 'Body',
            },
            data: {
                route: '/example',
            },
        };
    }
}
```
Error message:
```
TS2339: Property 'MessagingPayload' does not exist on type '(app?: App) => Messaging'.
```

Do you have any solutions for such cases?

Thank you.

**Comment by hiranya911** [comment]
The above code sample compiles fine. And VSCode wires the type definitions correctly. Are you sure it's the above code snippet that triggers the given error? It is rather strange since the code makes no references to `App`, which is indicated in the error message.

**Comment by LogansUA** [comment]
@hiranya911 I'm using WebStorm 2018.1. Regarding `app`, you're right, I get this code slightly out of context of my application, but the problem still the same, the `admin` not exporting anything useful.

Here's the screenshot from my IDE 
<img width="528" alt="screen shot 2018-04-23 at 11 56 23 am" src="https://user-images.githubusercontent.com/7515743/39116568-76bec488-46ed-11e8-97d8-2a0942ffaddf.png">

**Comment by hiranya911** [comment]
But if the code compiles with tsc (which it does), and works fine in some IDEs (e.g. VSCode), I can't see this as a problem in the SDK:

<img width="1030" alt="vscode_nodejs" src="https://user-images.githubusercontent.com/2375201/39145702-66c6e4ec-46e9-11e8-8cf1-c5d92e79d808.png">

**Comment by ibrahimduran** [comment]
I've just come across a workaround posted in 2016 for this issue, which still works as a charm. It can be found here with additional details https://github.com/Microsoft/TypeScript/issues/7352#issuecomment-191547232. It worked for me and I think this issue can be closed since there is a workaround without modifying the library code.
