### ISSUE TITLE
Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request

### ISSUE THREAD

**Issue by sarathkritikal** [firebase/firebase-admin-node#2402]
Suddenly, I got this issue from the firebase push notification function.

**Comment by lahirumaramba** [comment]
Hi @sarathkritikal it is hard to provide an answer with the limited information provided in the issue description. Please provide a code sample or a minimal repro so we can investigate the issue. Thanks!

**Comment by lahirumaramba** [comment]
Closing for lack of information. Please file a new issue if you are still experience problems with this.
