### ISSUE TITLE
Using sendSignInLinkToEmail on the server side

### ISSUE THREAD

**Issue by acanimal** [firebase/firebase-admin-node#241]
Hi,
I'm working on an app that uses email-link to log users and a custom NodeJS API to work with some data.

The problem is we have the need to use `auth.sendSignInLinkToEmail` on the server side, once we have checked some parameters stored on DB.

Is there any way to run `auth.sendSignInLinkToEmail` on NodeJS like in the firebase client SDK?

**Comment by bojeil-google** [comment]
No there is not. You will need to include the client library to send the email from a server environment.

**Comment by acanimal** [comment]
Thanks
