### ISSUE TITLE
FR: Search users by name or email address

### ISSUE THREAD

**Issue by diegofrata** [firebase/firebase-admin-node#242]
I'd love to be able to search users by their display name or part of a display name, but I also can't see any reason not to allow the search to be done by email address (eg. finding all users with a gmail.com email).

Right now my only option is to list all users and do the work manually. It's wasteful and won't scale. Ultimately it would also be worth to be able to perform simple queries such as count, so I could display how many users I have. But I'd settle for being able to search display name and email addresses.

**Comment by acanimal** [comment]
The alternative I follow is store some user information in firebase database to allow better searches.

**Comment by hiranya911** [comment]
I don't think search functionality is really in the roadmap for Firebase Auth. Full text search is always a complicated use case, and even the Firebase database solutions don't support it natively. I guess the only solution I can think of is indexing the user information in a separate system like Algolia or ElasticSearch, and then facilitating search through that. You can use a Cloud Function to automatically index all new user data into the search engine, and keep them up to date.

Checkout this solution proposed for Firestore: https://firebase.google.com/docs/firestore/solutions/search

You can do that same with Firebase Auth.

@bojeil-google wdyt?

**Comment by bojeil-google** [comment]
As @hiranya911 mentioned, we don't have any plan to allow rich query searching in Firebase Auth. We will allow searching by providing list of emails, uids, phone numbers or federated IDs, nothing beyond that. I recommend the alternatives already suggested by @hiranya911.

**Comment by hiranya911** [comment]
There's still no plans to support this feature. Please file via Firebase Support is further follow up is needed.
