### ISSUE TITLE
upgrade to firebase-admin v12.0.0 not resolved dependency

### ISSUE THREAD

**Issue by marco-mastella** [firebase/firebase-admin-node#2423]
### [REQUIRED] Step 2: Describe your environment

Attached my package.json file
[package.json](https://github.com/firebase/firebase-admin-node/files/13936520/package.json)
SO: Windows 10 Home

### [REQUIRED] Step 3: Describe the problem
After the install of lastest version of firebase-admin (v12.0.0) on npm install it shows and error for not resolved dependency.
# npm resolution error report

While resolving: firebase-functions-test@3.1.0
Found: firebase-admin@12.0.0
node_modules/firebase-admin
  firebase-admin@"^12.0.0" from the root project
  peer firebase-admin@"^10.0.0 || ^11.0.0 || ^12.0.0" from firebase-functions@4.6.0
  node_modules/firebase-functions
    firebase-functions@"^4.6.0" from the root project
    peer firebase-functions@">=4.3.0" from firebase-functions-test@3.1.0
    node_modules/firebase-functions-test
      dev firebase-functions-test@"^3.1.0" from the root project

Could not resolve dependency:
peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0" from firebase-functions-test@3.1.0
node_modules/firebase-functions-test
  dev firebase-functions-test@"^3.1.0" from the root project

Conflicting peer dependency: firebase-admin@11.11.1
node_modules/firebase-admin
  peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0" from firebase-functions-test@3.1.0
  node_modules/firebase-functions-test
    dev firebase-functions-test@"^3.1.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

i already opened the Case 10265821 and Firebase team answered to open an issue 

#### Steps to reproduce:

install firebase-admin (v12.0.0)

**Comment by lahirumaramba** [comment]
Thank you, @marco-mastella for reporting this issue. This needs to be addressed in the `firebae-funcitons-test` repo. The team will add support for firebase-admin v12 https://github.com/firebase/firebase-functions-test/blob/8cc337f038f2a56f0495886a11cd24ca02312ca8/package.json#L59

FYI @taeold

**Comment by ltshannon** [comment]
I'm encountering this issue. What do I need to do to fix it?

**Comment by elPre** [comment]
Same here.
How can I get to the /www-data-home/.npm/_logs/2024-08-23T22_51_43_888Z-eresolve-report.txt
Hope you guys can solve it fast! I need so bad.

npm error ERESOLVE could not resolve
npm error
npm error While resolving: firebase-functions@4.4.1
npm error Found: firebase-admin@12.3.1
npm error node_modules/firebase-admin
npm error   firebase-admin@"^12.3.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer firebase-admin@"^10.0.0 || ^11.0.0" from firebase-functions@4.4.1
npm error node_modules/firebase-functions
npm error   firebase-functions@"^4.3.1" from the root project
npm error   peer firebase-functions@">=4.3.0" from firebase-functions-test@3.1.0
npm error   node_modules/firebase-functions-test
npm error     dev firebase-functions-test@"^3.1.0" from the root project
npm error
npm error Conflicting peer dependency: firebase-admin@11.11.1
npm error node_modules/firebase-admin
npm error   peer firebase-admin@"^10.0.0 || ^11.0.0" from firebase-functions@4.4.1
npm error   node_modules/firebase-functions
npm error     firebase-functions@"^4.3.1" from the root project
npm error     peer firebase-functions@">=4.3.0" from firebase-functions-test@3.1.0
npm error     node_modules/firebase-functions-test
npm error       dev firebase-functions-test@"^3.1.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /www-data-home/.npm/_logs/2024-08-23T22_51_43_888Z-eresolve-report.txt
npm error A complete log of this run can be found in: /www-data-home/.npm/_logs/2024-08-23T22_51_43_888Z-debug-0.log; Error ID: beaf8772

**Comment by lahirumaramba** [comment]
Looks like you are still on an older version of `firebase-functions` (`npm error firebase-functions@"^4.3.1" from the root project`). If you are still having issues with the latest version of `firebase-functions` and `firebase-admin` please open a new issue.
