### ISSUE TITLE
FR: idempotency_key for messaging.send()

### ISSUE THREAD

**Issue by deremer** [firebase/firebase-admin-node#243]
### Describe your environment
`"firebase-admin": "~5.11.0"`
We use RTDB, Auth, Analytics, Storage, Messaging, PubSub

### Describe the problem
It'd be useful if the messaging() product could include an `idempotency_key` for a message we wish to send to a user.

We use Firebase Functions to respond to RTDB events to send push notifications to users. Occasionally, we receive an error from the FCM service (e.g., `Error: fcm.googleapis.com network timeout. Please try again.`). We _could_ enable retries on the Cloud Function to attempt to resend the push notification in the event of a function error. However, CF retries may loop for several days. Imagine a scenario where something in the function causes it to error, but after the message delivery is successful... the user may receive (many, many) duplicate push notifications.

We _could_ persist the message ID to the RTDB or elsewhere after successfully sending the push notification, and then check this field before subsequent runs to ensure the message is only sent once.

However, what happens if the DB write fails for some reason? Ideally the FCM system would handle this for us if we provide an idempotency_key of some type. As duplicate push notifications would be a massively big problem for user experience, perhaps it could be something core to the FCM product.

**Comment by hiranya911** [comment]
I filed this as a feature request for the FCM team internally. Thanks for the feature request.

**Comment by hiranya911** [comment]
Btw, also look at collapsible messages support available for Android and APNS: https://firebase.google.com/docs/cloud-messaging/concept-options#delivery_options

**Comment by deremer** [comment]
Thanks! That actually will help for some of our user cases and we’ll look to implement it!

Unfortunately I don’t think it’d fix the scenario where a cloud function is retrying indefinitely…

Thanks for your help on this!

Cheers,
David

--- 
David DeRemer

PHONE: +1 (646) 801-6385
WEB:  https://goposse.com ( https://goposse.com/ )
BLOG:  https://blog.goposse.com ( https://blog.goposse.com/ ) 

INSTAGRAM:  @goposse ( https://www.instagram.com/goposse/ ) 
TWITTER:  @goposse ( https://twitter.com/goposse )
FACEBOOK:  possenyc ( https://www.facebook.com/possenyc )

**Comment by deremer** [comment]
@hiranya911 I googled for `fcm idempotency` and found my own Github issue again, which I had forgotten about. Any update on the feature request?

**Comment by amitkot** [comment]
@hiranya911 could you please update about the status of this feature?
Thanks!

**Comment by hiranya911** [comment]
The FCM team has closed that feature request as "Won't fix". They recommend including a custom-generated identifier in each message sent out (possibly as a data field), and then collapsing the duplicates at the receiver end:

> this is solvable by the app developer creating a identifier for each message and including it in the payload. they can then collapse the dupes on their side. The duplication risk should be quite limited hence the recommendation to do this within the app.

If you wish to follow up further, report directly at https://firebase.google.com/support (mention the original issue ID 77217406)

**Comment by chris13524** [comment]
Receiver-side deduplication was my thought, but it doesn't work for Web PWAs because if no notification is displayed instead the user will get a push notification saying "App was updated in the background"
