### ISSUE TITLE
 FirebaseAuthError: There is no user record corresponding to the provided identifier. It was working in Node 18.12 but not working in 20.11.0

### ISSUE THREAD

**Issue by brijeshkothari6492** [firebase/firebase-admin-node#2441]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10_____
  * Firebase SDK version: 13.1.0_____
  * Firebase Product: auth_____ (auth, database, storage, etc)
  * Node.js version: 20.11.0_____
  * NPM version: _____

### [REQUIRED] Step 3: Describe the problem

 FirebaseAuthError: There is no user record corresponding to the provided identifier. It was working in Node 18.12 but not working in 20.11.0 I have double checked its working fine on 18.12.1 simply without any change but its breaking with error on 20.11.0

There is no user record corresponding to the provided identifier.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

<img width="923" alt="image" src="https://github.com/firebase/firebase-admin-node/assets/118822083/ac1a9049-4c2b-4970-92f9-1be6903341b5">

#### Relevant Code:

<img width="444" alt="image" src="https://github.com/firebase/firebase-admin-node/assets/118822083/c493cc23-66b7-44b1-920b-4877f9882be0">

<img width="959" alt="image" src="https://github.com/firebase/firebase-admin-node/assets/118822083/cd04bc32-5e5a-4002-baba-313a4aa0dcec">

```
// TODO(you): code here to reproduce the problem
```

**Comment by IsoDevMate** [comment]
i am getting tehsame error currently runnig same node version how did you solve this error

**Comment by IsoDevMate** [comment]
I am also experiencing the same error currently running node v20.10.0 and i get the same challemge with firebase thought i am using graphql . I'm creating a document in firestore when that contains a token hash .The token hash will be used in  tandem with the email and password to create a user account   
![image](https://github.com/firebase/firebase-admin-node/assets/127542979/e0171346-1801-48b1-9c35-b17800e5777f)

**Comment by lahirumaramba** [comment]
I don't see any integration test failures on this API. Are you still facing this issue? It would help if you can provide us with a minimal repro
