### ISSUE TITLE
when using sendEach with a batch that contains entry x with invalid url, the whole batch fails instead of only x

### ISSUE THREAD

**Issue by jens-dehnert-winkler-ay** [firebase/firebase-admin-node#2467]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: aws docker
  * Firebase SDK version: "11.10.1"
  * Firebase Product: 
  * Node.js version: node 20
  * NPM version: 

### [REQUIRED] Step 3: Describe the problem

Expectation: when using sendEach, each message should be treated isolated, as if I would call send for each of the messages myself.
This works fine, if the message is valid. If it is invalid (e.g. the image url does not pass the validation), the whole batch is rejected, even if all other messages are valid.

#### Steps to reproduce:

calling messaging `sendEach` function fails for all messages if a single message is invalid.
This is because the loop maps the objects to a synchronous function instead of using async in l/ 297.

#### Relevant Code:

 (https://github.com/firebase/firebase-admin-node/blob/0da72ef60535b6a9d0267e3843f45512718b8e74/src/messaging/messaging.ts#L272)

**Comment by jens-dehnert-winkler-ay** [comment]
https://github.com/jens-dehnert-winkler-ay/firebase-admin-node
need to set up the environment. will take a moment longer than expected... :( 
https://github.com/jens-dehnert-winkler-ay/firebase-admin-node

**Comment by DyosTheNerd** [comment]
Please take a look here :) 
https://github.com/firebase/firebase-admin-node/pull/2469
