### ISSUE TITLE
Firebase AdminSDK in AWS Lambda (module initialisation error: Error)

### ISSUE THREAD

**Issue by kumarkeviv** [firebase/firebase-admin-node#247]
### Describe your environment

  * Operating System version: AWS Lambda
  * Firebase SDK version: 5.11.0
  * Firebase Product: Firestore

### Describe the problem
I have been trying to connect my lambda function with Firestore DB using Admin SDK but its throwing error "module initialisation error: Error"

Its clearly an issue with Firesbase admin sdk, as every-time I comment this component, the rest of the component works fine. Could you please let me know what is the issue?

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
```
'use strict';
const Alexa = require('alexa-sdk');
const firebase = require('firebase-admin');
const APP_ID = '---';

const SKILL_NAME = '----';
const HELP_MESSAGE = '---';
const HELP_REPROMPT = '----';
const STOP_MESSAGE = '---';

module.exports.Test = (event, context, callback) => {

    context.callbackWaitsForEmptyEventLoop = false;

    if (firebase.apps.length == 0) {
        firebase.initializeApp({
            credential: firebase.credential.cert('---'),
            databaseURL: "---"
        });
    }

    var db = firebase.firestore();
    var docRef = db.collection('users')
        .doc('alovelace');

    var setAda = docRef.set({
        first: 'Ada',
        last: 'Lovelace',
        born: 1815
    });
};

const handlers = {
    'LaunchRequest': function () {
        this.emit('BasicFunction');
    },
    //Help
    'AMAZON.HelpIntent': function () {
        const speechOutput = HELP_MESSAGE;
        const reprompt = HELP_REPROMPT;

        this.response.speak(speechOutput)
            .listen(reprompt);
        this.emit(':responseReady');
    },
    //Cancel
    'AMAZON.CancelIntent': function () {
        this.response.speak(STOP_MESSAGE);
        this.emit(':responseReady');
    },
    //Stop
    'AMAZON.StopIntent': function () {
        this.response.speak(STOP_MESSAGE);
        this.emit(':responseReady');
    },
};

exports.handler = function (event, context, callback) {
    const alexa = Alexa.handler(event, context, callback);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
```

####Logs from CloudWatch
```
module initialization error: Error
at FirebaseAppError.Error (native)
at FirebaseAppError.FirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:39:28)
at FirebaseAppError.PrefixedFirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:85:28)
at new FirebaseAppError (/var/task/node_modules/firebase-admin/lib/utils/error.js:119:28)
at Function.Certificate.fromPath (/var/task/node_modules/firebase-admin/lib/auth/credential.js:142:19)
at new CertCredential (/var/task/node_modules/firebase-admin/lib/auth/credential.js:192:25)
at Object.cert (/var/task/node_modules/firebase-admin/lib/firebase-namespace.js:224:58)
at Object.<anonymous> (/var/task/index.js:14:41)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
```

**Comment by hiranya911** [comment]
Are you using Docker to deploy your function?

**Comment by kumarkeviv** [comment]
No, I am installing the dependency in local folder along with my code. Later uploading the zipped folder to lambda function via console.

**Comment by hiranya911** [comment]
You have to use Docker to use Firestore clients in AWS Lambda: https://medium.com/@samstern_58566/how-to-use-cloud-firestore-on-aws-lambda-4bf6d3a473d9

**Comment by kumarkeviv** [comment]
Hi @hiranya911 

Thanks for the quick response, I am trying to use the suggested solution but it doesn't seems to be working.

Every-time, I follow the steps  listed in blog, its resulting in empty node_modules folder, even though the code executes properly.

Also I tried to directly import the package as you mentioned here in #104 
"I've published an RC at https://storage.googleapis.com/firebase-admin-node/firebase-admin-5.4.3-rc0.tgz"

**Comment by kumarkeviv** [comment]
@hiranya911 adding more asset and error log.

`Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:4:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)`

//Missing firebase_admin folder after executing the code.
![missing_firebase_admin](https://user-images.githubusercontent.com/17118240/38496169-c799c61a-3bfc-11e8-9b0e-c0f471019978.PNG)

Not sure, how to resolve this issue :(

**Comment by hiranya911** [comment]
What's in your package.json?

**Comment by kumarkeviv** [comment]
I am trying to use Firebase admin for my Alexa app.
So, my final package.json is like:

**Comment by kumarkeviv** [comment]
Any help?

**Comment by hiranya911** [comment]
@samtstern who may have some ideas.

**Comment by samtstern** [comment]
@kumarkeviv check out this blog post I wrote about using Cloud Firestore on AWS Lambda, which will tell you how to get `firebase-admin` set up.

**Comment by samtstern** [comment]
https://medium.com/@samstern_58566/how-to-use-cloud-firestore-on-aws-lambda-4bf6d3a473d9

**Comment by hiranya911** [comment]
@samtstern  I believe he's following that article, but running into this weird issue (@kumarkeviv can you confirm?)

**Comment by kumarkeviv** [comment]
Can anyone help me on this? Its over a month.

**Comment by kushwaha03** [comment]
firebase-admin file is generate via node modules so write cmd on CLI 
npm install firebase-admin
firstly go to ur directory folder then run

**Comment by albertvolkman** [comment]
Docker worked, but this works as well-
`nvm exec 8.10 npm install`

**Comment by tahmina8765** [comment]
Docker works only when I use javascript, but if I use serverless framework with nodejs-typescript, then docker does not work for me. But the following works -

https://medium.com/mtlserverless/firestore-the-serverless-framework-the-easy-way-262e574581d0
