### ISSUE TITLE
Planned v5.12.0 release

### ISSUE THREAD

**Issue by tfonfara** [firebase/firebase-admin-node#248]
Hi @hiranya911,

when did you plan to release v5.12.0 of the SDK? I'm really looking forward to it because of the changes in your recent pr https://github.com/firebase/firebase-admin-node/pull/236 😊

Cheers

**Comment by hiranya911** [comment]
@tfonfara This just went out: https://firebase.google.com/support/release-notes/admin/node#5.12.0
