### ISSUE TITLE
Writing to Firestore directly in the middle of a transaction updateFunction causes a deadlock/hang

### ISSUE THREAD

**Issue by mmmulani** [firebase/firebase-admin-node#2481]
I ran into this code mistake I made recently, and I think it would be nice if the API could help catch this issue.

#### Steps to reproduce:

Try writing to a document directly while in a transaction.
```
await db.runTransaction(async t => {
  const docRef = db.collection('cities').doc('Toronto');
  await docRef.set(...);
});
```

While of course, this is a code issue caused by the programmer, it is particularly frustrating to debug as it seems to cause a deadlock/unfulfilled promise. Possibly the API could help catch this issue by marking the stack and throwing an error (maybe only in dev?).

**Comment by cherylEnkidu** [comment]
Hi @mmmulani ,

Could you please be more specific of which problem you are running into and what would you expected SDK behaviour be like? Because `set()` can be used in transaction.

**Comment by mmmulani** [comment]
oh sorry, I cleaned up my example but from what I tested, this will cause your Node server to just hang:

```
await db.runTransaction(async t => {
  const docRef = db.collection('cities').doc('Toronto');
  await docRef.set(...);
});
```

while the correct code to write is:

```
await db.runTransaction(async t => {
  const docRef = db.collection('cities').doc('Toronto');
  t.set(docRef, ...);
});
```

my ideal SDK behaviour would be that the Cloud Firestore API uses something like [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) to mark when a promise/thread is inside a transaction, and warns you if you use an api like `docRef.set()` or `docRef.get()` manually while you are still in the scope of the transaction.

**Comment by cherylEnkidu** [comment]
Hi @mmmulani ,

I run the code snippet below but the code returns successfully. Can you provide a minimal repo app?

```
await db.runTransaction(async t => {
  const docRef = db.collection('cities').doc('Toronto');
  await docRef.set(...);
});
```
