### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by zgosalvez** [firebase/firebase-admin-node#250]
* Operating System version: OSX 10.13.4, Node 6.11.5
  * Firebase SDK version: 4.12.1
  * Library version: 5.12.0
  * Firebase Product: firebase-functions

Upgrade to firebase-admin 5.12.0 in package.json. Then run `npm install`.

```sh
UNMET PEER DEPENDENCY firebase@4.12.1
UNMET PEER DEPENDENCY firebase-admin@5.12.0
...
npm WARN firebase-functions@1.0.0 requires a peer of firebase-admin@~5.11.0 but none was installed.
npm ERR! code 1
```

**Comment by hiranya911** [comment]
As you can see the firebase-functions has a dependency on `firebase-admin@~5.11.0`. Which means it won't work with 5.12.0. You should stick to 5.11.0. Report this at https://github.com/firebase/firebase-functions if you wish to follow up further, but there's nothing we can do in `firebase-admin` to resolve this.
