### ISSUE TITLE
firebase-admin 5.12.0 fails to compile with tsc

### ISSUE THREAD

**Issue by ndkcha** [firebase/firebase-admin-node#252]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: OSX 10.11.3
  * Firebase SDK version: 5.12.0
  * Library version: _____
  * Firebase Product: firebase-admin for node.js (auth, database, storage, etc)

#### Steps to reproduce:

_What happened? How can we make the problem occur?_

I'm using typescript environment to code the server on Node.js
When I compile the code, it's returning with an error:

```
> rimraf dist && tsc --outDir dist

node_modules/firebase-admin/lib/index.d.ts(18,22): error TS7016: Could not find a declaration file for module '@google-cloud/storage'. '/<path-to-project>/node_modules/@google-cloud/storage/src/index.js' implicitly has an 'any' type.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```
I have the upgraded firebase-admin to the latest version (5.12.0)
```
"firebase-admin": "^5.12.0",
```

**Comment by hiranya911** [comment]
Compiles fine for me. Make sure GCS typings (`@types/google-cloud__storage` package) are installed and visible to tsc. That is the `typeRoots` are defined correctly in the project config.

**Comment by ndkcha** [comment]
I have `@types/google-cloud_storage` package installed. and here is my tsconfig file. 
Can you check if it is correct or not?

![screen shot 2018-04-06 at 1 11 50 pm](https://user-images.githubusercontent.com/8328240/38434440-561500fc-399c-11e8-863d-bd326d6fda7f.png)

**Comment by rwpino** [comment]
I have the same issue

**Comment by hiranya911** [comment]
You have specified `types` in the config. This means only `reflect-metadata` types are visible to the compiler. 

See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

```
If types is specified, only packages listed will be included. For instance:

{
   "compilerOptions": {
       "types" : ["node", "lodash", "express"]
   }
}

This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included.
```

**Comment by ndkcha** [comment]
Even when i add,`
"types": [
            "reflect-metadata",
            "google-cloud__storage"
        ],
` it returns me the same error.

**Comment by rwpino** [comment]
I add 

```
 "@google-cloud/storage": "^1.6.0",
 "@types/google-cloud__storage": "^1.1.7",
```

to my package.json with the firebase-admin

`"firebase-admin": "^5.12.0",`

and I m having the same issue, 

my tsconfig look like 

```
{
    "compilerOptions": {
        "outDir": "dist",
        "target": "es6",
        "module": "commonjs",
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "emitDecoratorMetadata": true,
        "sourceMap": false,
        "rootDirs": [
            "src",
            "test",
            "node_modules/@types"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```

in the typescript website says if you don't include _typeRoots_  parameter the @types will be added automatically

**Comment by shahidcodes** [comment]
For now I am skipping lib check in typescript config until we've a workaround or a fix
`    "skipLibCheck": true, `
