### ISSUE TITLE
Type: AndroidConfig: ttl misleading ?

### ISSUE THREAD

**Issue by pquerner** [firebase/firebase-admin-node#2524]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: 12.0.0
  * Firebase Product: messaging
  * Node.js version: 20.10.0
  * NPM version: 10.2.3

### [REQUIRED] Step 3: Describe the problem

I think the wording on the docs or in this repo are wrong regarding AndroidConfig ttl value.

#### Relevant Code:

According to 
https://github.com/firebase/firebase-admin-node/blob/9ab37f5d6ed6e03307869a3d46ef855b65666047/src/messaging/messaging-api.ts#L394-L397
(also present in latest master, but git blame didnt show any relevant touches here in recent years)

the ttl should be a `number` in milliseconds.

But according to the web documenation [1] the notation is quite different.
To quote:

> string ([Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) format)

> How long (in seconds) the message should be kept in FCM storage if the device is offline. The maximum time to live supported is 4 weeks, and the default value is 4 weeks if not set. Set it to 0 if want to send the message immediately. In JSON format, the Duration type is encoded as a string rather than an object, where the string ends in the suffix "s" (indicating seconds) and is preceded by the number of seconds, with nanoseconds expressed as fractional seconds. For example, 3 seconds with 0 nanoseconds should be encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should be expressed in JSON format as "3.000000001s". The ttl will be rounded down to the nearest second.

> A duration in seconds with up to nine fractional digits, ending with 's'. Example: "3.5s".

So, which is it now? A `string`, a `number`? Milliseconds or seconds?

[1] https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig

**Comment by lahirumaramba** [comment]
What you have linked in [1] are reference docs for the REST API. You can find the Firebase Admin Node.js SDK reference docs at [here](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.androidconfig.md?_gl=1*1d90ekt*_up*MQ..*_ga*NTY2MTYwNTA3LjE3MTI2ODc5NDg.*_ga_CW55HF8NVT*MTcxMjY4Nzk0OC4xLjAuMTcxMjY4Nzk0OC4wLjAuMA..#androidconfigttl), which defines `ttl` as a `number` in milliseconds.
