### ISSUE TITLE
RemoteConfig condition names invalid via the Admin SDK but not console

### ISSUE THREAD

**Issue by RKaySilverorange** [firebase/firebase-admin-node#2535]
### Step 2: Describe your environment

  * Operating System version: Mac OS Sonoma 14.2.1
  * Firebase SDK version: 11.5.0
  * Firebase Product: Remote Config
  * Node.js version: ^18.13.0
  * yarn version: 1.22.19

### Step 3: Describe the problem

I am creating a RemoteConfigTemplate which requires manipulating `condition` fields depending on a deployment target. 

The the condition names I am using seem to be accepted within the console (I prototyped our RemoteConfig setup in the firebase console initially), but they fail validation when I call `configAdmin.validateTemplate(template)` via the Admin SDK:

> message: '[VALIDATION_ERROR]: [POTato iOS Dev, POTato Android Dev, POTato Android Beta, POTato iOS Beta, POTato Android Prod, POTato iOS Prod] are not valid condition names. All keys in all conditional value maps must be valid condition names.'

POTato is just a stand in for a client's app name, but it follows the same pattern. 

I wasn't able to find documentation on valid condition names, and I am thrown a bit by the fact that they seem to be valid when used via the firebase console. 

Is there any spec available on what is a valid condition name? Also, if this isn't intended and filing a bug with the issue tracker would be useful, I am happy to do that.

#### Steps to reproduce:

Create a RemoteConfigTemplate in JSON locally. I initially did this by pulling down the RemoteConfig set up in the console as a JSON string. Set one of the conditions to have a name which matches the pattern specified above, and then attempt to validate it. 

I read the template from a file using `const template = configAdmin.createTemplateFromJSON(json);` then validate it from there using `await configAdmin.validateTemplate(template);`. 

#### Relevant Code:
Example JSON conditions
```
`"conditions": [
    {
      "name": "POTato iOS Dev",
      "expression": "app.id == 'EXAMPLE'",
      "tagColor": "PURPLE"
    },
    {
      "name": "POTato Android Dev",
      "expression": "app.id == 'EXAMPLE'",
      "tagColor": "PURPLE"
    }
  ]` 
```

**Comment by jenh** [comment]
Parameter names don't allow spaces and the console usually blocks entry--can you remember how you added the parameter names to the Firebase console? Was it imported via the console or REST API?

Sounds like there may be a bug there (and our error message can be better and [documentation](https://firebase.google.com/docs/remote-config/parameters#limits_on_parameters_and_conditions) clearer)!

**Comment by RKaySilverorange** [comment]
Hello @jenh,

Thank you for responding. 

Yes, these values were added via the console initially. I just tested this again with the variant name "Space Bar", and here is the result:

![Screenshot 2024-04-23 at 6 10 49 AM](https://github.com/firebase/firebase-admin-node/assets/127134019/086b7c70-a984-49a8-88db-25464ec3a47b)

![Screenshot 2024-04-23 at 6 11 18 AM](https://github.com/firebase/firebase-admin-node/assets/127134019/2f438878-273d-4d68-a800-a7b765c2479f)

Let me know if I can provide any further info.

**Comment by RKaySilverorange** [comment]
Hello,

I just attempted to publish a script via the Admin SDK and unfortunately I am now getting a different validation error. This time I used names which don't have spaces. 

This response was given when I called `config.publishTemplate(template);` (`config` was a RemoteConfig object):
```
Error: [VALIDATION_ERROR]: [potato_ios_dev, potato_android_dev] are not valid condition names. All keys in all conditional value maps must be valid condition names.
```

**Comment by jenh** [comment]
Sorry--I got parameters and conditions confused there--condition names can definitely have spaces.

I'm able to publish a config with added and changed condition names with and without underscores using the [sample code](https://github.com/firebase/quickstart-nodejs/blob/master/config/index.js#L45). Seems to work with a config pulled using the Admin SDK, but am running into (different) issues with the formatted JSON downloaded straight from the console UI.

Can you file a [case for the Firebase Developer Support team](https://firebase.google.com/support/troubleshooter/remote_config/help) with example code you're using to make the change and a sample config (and how it was obtained) for our Support team to take a closer look? Thank you!

**Comment by RKaySilverorange** [comment]
@jenh I am just checking with my CTO about what I'm allowed to provide (it's a client's codebase); but if that's fine I will definitely file the issue.

Would it be possible for you to provide me with the template that you get from the Admin SDK (assuming it isn't sensitive)? I would like to compare it against what I have to see if something about the structure I am using is wrong.

Either way, thank you for the help.

**Comment by RKaySilverorange** [comment]
Closing the issue. I did end up finding an error in my JSON template which was leading to that validation issue.

**Comment by Davtyanag** [comment]
@
[config.json](https://github.com/user-attachments/files/17173561/config.json)
Initially created in firebase console, and same error 
 message: '[VALIDATION_ERROR]: [anyuser] are not valid condition names. All keys in all conditional value maps must be valid condition names.'
 
 I tried different names and nothing helps. Downloaded using sample code.
