### ISSUE TITLE
Initialiaze from FIREBASE_CONFIG environment variable

### ISSUE THREAD

**Issue by pantos27** [firebase/firebase-admin-node#254]
Can you give an example of the data that should be in the FIREBASE_CONFIG environment variable when calling initializeApp
I see that there should be an object in the 'credential' property
But it also checks for a method called 'getAccessToken'

**firebase-app.js:203**
```
if (typeof credential !== 'object' || credential === null || typeof credential.getAccessToken !== 'function') {
            throw new error_1.FirebaseAppError(error_1.AppErrorCodes.INVALID_APP_OPTIONS, "Invalid Firebase app options passed as the first argument to initializeApp() for the " +
                ("app named \"" + this.name_ + "\". The \"credential\" property must be an object which implements ") +
                "the Credential interface.");
        }
```

How can I create this method through the environment variable string?

**Comment by hiranya911** [comment]
You cannot set credential via `FIREBASE_CONFIG`. It is for setting other Firebase options (databaseURL, projectId etc). SDK will resort to using Application Default Credentials when initialized in this manner. 

You can find some detailed info at https://medium.com/google-cloud/firebase-separating-configuration-from-code-in-admin-sdk-d2bcd2e87de6

**Comment by vietthang197** [comment]
### 

> [`_****_`]([url](

- 

- [ ] 

- [ ] 

- 

1. 

1. url

))
