### ISSUE TITLE
ESBuild failures related to farmhash on firebase-admin v12.1.0

### ISSUE THREAD

**Issue by infovore** [firebase/firebase-admin-node#2542]
### Environment

  * Operating System version: _Mac OS Ventura (13.x) on Intel_
  * Firebase SDK version: _firebase-admin v12.1.0)_
  * Firebase Product: _firebase-admin_ for node
  * Node.js version: _20.5.1_
  * NPM version: _9.8.0_

#### Steps to reproduce:

Starting work on a colleague's project, I run `npm install`. We've pinned `firebase-admin` to `^12.0.0`; this installs `12.1.0`. This works correctly.

When I build my SvelteKit project - which will eventually use ESBuild - I get the [same errors as reported in this StackOverflow post](https://stackoverflow.com/questions/78403686/why-am-i-getting-module-not-found-error-cant-resolve-build-debug-farmhash) - "_can't resolve build/Debug/farmhash.node_".

When I pin `firebase-admin` to `12.0.0` (specific version): no such error. So the StackOverflow post, filed a day or two ago, seems to be related to something in the `12.1.0` changes.

Beyond this, I'm a bit lost, but managed to find evidence of someone else with the same issue, and now have a workaround - pinning to an old verison. There seem to have been other `farmhash` issues that Doug Stevneson has mentioned.

**Comment by infovore** [comment]
Update: `farmhash` needs to be specified as an ESBuild external. In the case of `svelte-adapter-appengine`, that was an extra configuration step I hadn't configured, is all.

**Comment by balloman** [comment]
@infovore can you talk a little bit more about what you did? I reverted to 12.0.0, but I'm hoping this doesn't prevent me from upgrading indefinitely

**Comment by infovore** [comment]
@balloman of course - I added `farmhash` to the `externals` section of my esbuild configuration.

Vite - in `optimizeDeps.externals` - and other build tools should have similar configuration options.

**Comment by ramigabai** [comment]
Did anyone made it work with @nx/esbuild ? Adding `"external": [ "farmhash" ]` doesn't work..

**Comment by dantheli** [comment]
I'm also facing this with Next.js and had to downgrade to 12.0.0 in order to build as well.
