### ISSUE TITLE
Firestore Repeatedly Returning Error: 5 NOT_FOUND

### ISSUE THREAD

**Issue by sr5434** [firebase/firebase-admin-node#2563]
### [READ] Step 1: Are you in the right place?

**Cloud Firestore support is provided by the [`@google-cloud/firestore`](https://npmjs.com/package/@google-cloud/firestore) library. Therefore the easiest and most efficient way to get Firestore issues resolved is by directly reporting them at the [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo.**

If you still think the problem is related to the code in this repository, then read on.

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu
  * Firebase SDK version: 13.9.0
  * Firebase Product: Firestore
  * Node.js version: v20.12.1
  * NPM version: 10.5.0

#### Steps to reproduce:

When I call the API Route, instead of creating a new user in Firestore, I get a vague "Error: 5 NOT_FOUND" error message with no additional details. I have used this code before in other projects and can confirm that it used to work.

#### Relevant Code:

The following is a NextJS API Route I used.

```javascript
import { NextResponse, Response } from 'next/server'

import { getFirestore } from "firebase-admin/firestore";
import * as admin from 'firebase-admin'

const serviceAccount = require('../../../service_account.json');
if (admin.apps.length === 0) {
  admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      databaseURL: 'https://database.firebaseio.com'
  });
}
const db = getFirestore();

export async function POST(req){
  const {userId} = getAuth(req);
  const usersDb = db.collection('users');
  await usersDb.doc("example-user-id").set({
    customers: []
  });
  return NextResponse.json({ result: "Success" });
}
```

**Comment by lahirumaramba** [comment]
Did you enable Firestore from the Firebase console? I have seen this error before when Firestore is not properly set up from the console.

**Comment by sr5434** [comment]
When I create a firebase app instead of using a service account it works sometimes

**Comment by caravelle-inc** [comment]
@lahirumaramba @sr5434 
I am also experiencing this issue.

I have two projects, one for development and one for production, and I am initializing Firestore using a service account. The development project does not have this issue. However, when I set up the production project yesterday, the problem occurred. (BTW, the same problem occurs in the production project, even in the emulator environment.) We have confirmed that the correct service account for the project is being loaded.

Here are the details:

```json
// package.json
{
 "engines": {
    "node": "18"
  },
  "dependencies": {
    "firebase-admin": "^11.11.1",
    "firebase-functions": "^5.0.1"
  }
}
```

```javascript
// firebaseConfig.js
const admin = require("firebase-admin");
require("dotenv").config({ path: `.env.${process.env.NODE_ENV}` });
const serviceAccount = require(process.env.SERVICE_ACCOUNT_KEY);

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
console.log(serviceAccount);

const db = admin.firestore();
module.exports = { db };
```

I found the same information and wanted to share it for your reference:
[https://ja.stackoverflow.com/questions/99288/node-js-%e3%81%a7-gcp-%e3%81%ae-cloud-functions-%e3%81%8b%e3%82%89-firestore-%e3%81% ae%e3%83%87%e3%83%bc%e3%82%bf%e3%82%92%e5%8f%96%e5%be%97%e3%81%99%e3%82%8b%e6%96%b9%e6%b3%95%e3%81%8c%e5%88%86%e3%81%8b%e3%82%89%e 3%81%aa%e3%81%84](https://ja.stackoverflow.com/questions/99288/node-js-%e3%81%a7-gcp-%e3%81%ae-cloud-functions-%e3%81%8b%e3%82%89-firestore-%e3%81%ae%e3%83%87%e3%83%bc%e3%82%bf%e3%82%92%e5%8f%96%e5%be%97%e3%81%99%e3%82%8b%e6%96%b9%e6%b3%95%e3%81%8c%e5%88%86%e3%81%8b%e3%82%89%e3%81%aa%e3%81%84)


Thank you for reading!

**Comment by dconeybe** [comment]
I'll take a look at this tomorrow. For now, do you have some log output showing the entire stack trace and error message that you could post?

**Comment by sr5434** [comment]
I was able to get the code working when I used the Firebase NPM package on the backend and created a web app in the firebase console.

**Comment by dconeybe** [comment]
Is your problem solved?

**Comment by sr5434** [comment]
Yes

**Comment by caravelle-inc** [comment]
The production project required a specified database ID. The issue is resolved. Thank you!

**Comment by edsonboldrini** [comment]
Hello @sr5434 and @caravelle-inc 

> I was able to get the code working when I used the Firebase NPM package on the backend and created a web app in the firebase console.

> The production project required a specified database ID. The issue is resolved. Thank you!

I'm stuck with the same problem. Can you provide the full steps of what solved your problem? if it isn't a bother I will appreciate to see your `package.json`, `firebaseConfig.js/ts` and also the calling for the `collection`, for example: a simple `get()` to get all documents of a collection.

**Comment by tushgup** [comment]
I'm also facing the same problem, could someone share what they did to resolve it?

**Comment by tobyL05** [comment]
I'm getting the exact same error whenever I try to read/write to cloud firestore. Even after following the docs exactly.

**Comment by dconeybe** [comment]
For anyone experiencing this issue, please open a new issue with the specifics of your scenario.

**Comment by ugursirmen** [comment]
@dconeybe Hello, I experienced this issue nowadays and I realized that I deleted '(default)' named database. If you have not this default, you cannot access another one, I know this is stupid but when I re-created a database with '(default)' name and use it, the error resolved :) I hope this was helpful.

**Comment by dconeybe** [comment]
Thanks for the info, @ugursirmen. We'll look into the effects of deleting the default database.

**Comment by tobyL05** [comment]
I managed to solve this issue by adding my database id to getFirestore() like so `getFirestore(<database_id>)`. I didn't realize I set my own custom database id in the Firebase Console when I created my database nor did I realize that the database id was there on the console the whole time.

![Screenshot 2024-07-15 at 22 37 28](https://github.com/user-attachments/assets/404dfe9d-cfa2-4131-bb8d-968cec1b4982)

**Comment by PistonShot1** [comment]
making the parameter for the databaseId as required for `getFirestore()` would be great

**Comment by Dafomchollom** [comment]
> I managed to solve this issue by adding my database id to getFirestore() like so `getFirestore(<database_id>)`. I didn't realize/forgot that I set my own custom database id in the Firebase Console when I created my database nor did I realize that the database id was there on the console the whole time.
> 
> ![Screenshot 2024-07-15 at 22 37 28](https://private-user-images.githubusercontent.com/79076160/348766650-404dfe9d-cfa2-4131-bb8d-968cec1b4982.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTQyNDcsIm5iZiI6MTcyMjYxMzk0NywicGF0aCI6Ii83OTA3NjE2MC8zNDg3NjY2NTAtNDA0ZGZlOWQtY2ZhMi00MTMxLWJiOGQtOTY4Y2VjMWI0OTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZmY3NTI3MzBhNzk2MTg3ZWU5MmNhNjIwYmM5YmFhYTdjYmQ1NzBmODA2OGE0ZDE1MjE3MWE5YzNjZjg2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z5ew4WTDGoHtP6wBFkO1cHJg8CHUkEnTdVchq6bknn4)

this works fine for me thanks

**Comment by maanmuca** [comment]
> firebaseConfig

thanks , it worked only in that way

**Comment by every821** [comment]
thanks

**Comment by clavidk** [comment]
I had a similar issue and it was because I had named my database `prod`  instead of keeping it the default name `(default)`. Deleting prod and creating a new db with the `(default)` name solved the issue for me.

**Comment by peternowell** [comment]
I ran into this issue too, and providing my custom database ID to the `getFirestore` function didn't solve it. I needed to delete my database and create a new one named `(default)`. Is this a bug?

**Comment by gabrielostolaza** [comment]
adding the databaseId worked when trying to use the clientSDK, does anyone know how this translate for the adminSDK when trying to access Firestore?

**Comment by kisscompany** [comment]
> I managed to solve this issue by adding my database id to getFirestore() like so `getFirestore(<database_id>)`. I didn't realize/forgot that I set my own custom database id in the Firebase Console when I created my database nor did I realize that the database id was there on the console the whole time.
> 
> ![Screenshot 2024-07-15 at 22 37 28](https://private-user-images.githubusercontent.com/79076160/348766650-404dfe9d-cfa2-4131-bb8d-968cec1b4982.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NTkzMjAsIm5iZiI6MTczMTk1OTAyMCwicGF0aCI6Ii83OTA3NjE2MC8zNDg3NjY2NTAtNDA0ZGZlOWQtY2ZhMi00MTMxLWJiOGQtOTY4Y2VjMWI0OTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE5NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZmQxNzZiMTRiMTlkOGMwZWQ0ZDBlYzVhNWU1MTM1NjQ5N2QyNmU2MDczNmFkMzhiMDZmMzI5YjZjOGU5YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JhLl4zFZr760AHGbMQg3OcBSvD14kaJpYguR_L5ddOU)

Perfect. it works for me 👍

**Comment by Johnconfit** [comment]
> default

It is look crazy, but it real. By changing default by another name, the error occurs. To fix that, we need to rename with default

**Comment by emmethalm** [comment]
I concur. the solution for me (using the admin sdk) was to simply delete my database from the firebase firestore dashboard and create a new one with the default name "(default)".

**Comment by gtnsimon** [comment]
Hi everyone, I encountered a similar issue while using the `@google-cloud/firestore` package, which is used under the hood when calling `getFirestore()`. It turned out I had a very old version installed that did not support the `databaseId` option. Make sure your `firebase-admin` package is update to date. Hope this helps!

**Comment by Jijun-TANG** [comment]
> I managed to solve this issue by adding my database id to getFirestore() like so `getFirestore(<database_id>)`. I didn't realize/forgot that I set my own custom database id in the Firebase Console when I created my database nor did I realize that the database id was there on the console the whole time.
> 
> ![Screenshot 2024-07-15 at 22 37 28](https://github.com/user-attachments/assets/404dfe9d-cfa2-4131-bb8d-968cec1b4982)

OMG thank you so much, it solved my problem! For informations, I put "app" inside the getFirestore() function and it doesn't work

**Comment by VentsislavAntov** [comment]
> [@dconeybe](https://github.com/dconeybe) Hello, I experienced this issue nowadays and I realized that I deleted '(default)' named database. If you have not this default, you cannot access another one, I know this is stupid but when I re-created a database with '(default)' name and use it, the error resolved :) I hope this was helpful.

This was it. Thanks!

**Comment by iamrita** [comment]
Wow this thread saved me! Basically, unless you specify a particular ID in `getFirestore()`, your ID for the Firestore database must be `(default)`. Was this documented somewhere and I missed this?

**Comment by grallc** [comment]
> I had a similar issue and it was because I had named my database `prod` instead of keeping it the default name `(default)`. Deleting prod and creating a new db with the `(default)` name solved the issue for me.

Thanks, just saved me a lot of time.
It really is crazy it works this way though (and not documented anywhere?)

**Comment by krishnashetty0** [comment]
Yes, thread saved me!
ChatGPT, Gemini couldn't help - Had to come here through old way  :)

**Comment by BrianJenney** [comment]
I too came here and was saved! I needed to specify the name of the DB however like this

```
export const adminDb = getFirestore(adminApp, 'default'); //could not connect until adding 'default'
export const adminStorage = getStorage(adminApp);
export { adminApp };
```

**Comment by garispe** [comment]
I had the same error. I'm using only the Admin SDK and access to database from Firebase Cloud functions. To solve it, I added the databaseId to Firestore settings:

```typescript
admin.firestore().settings({
    projectId: serviceAccountKey.project_id,
    ignoreUndefinedProperties: true,
    databaseId: "my-database-name"
});

**Comment by enip2473** [comment]
I am saved too! Thanks for your help and also call for a clearer error message.

**Comment by ivanlesko** [comment]
spent a solid 8 hours trying to figure this out 🫠 deleting the database and creating a new one with the "(default)" name fixed it.

**Comment by enriquebarco** [comment]
> I ran into this issue too, and providing my custom database ID to the `getFirestore` function didn't solve it. I needed to delete my database and create a new one named `(default)`. Is this a bug?

This also helped me. Thank you. Just like others in this thread, I spent more time than I should on this little bug.

**Comment by xavipolo** [comment]
Thanks for the clues 😉 

```typescript
import admin, { ServiceAccount } from "firebase-admin";
import serviceAccountJson from "../../firebaseServiceAccountKey.json";

const serviceAccount = serviceAccountJson as ServiceAccount;

try {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    projectId: serviceAccount.projectId,
  });
  console.log("Firebase Admin initialized");
} catch (e: any) {
  if (!e.message.includes("already exists")) {
    console.error("Error initializing Firebase Admin SDK:", e);
  }
}

admin.firestore().settings({
  databaseId: "dsp-utils-db",
});

const db = admin.firestore();

export default db;

```

**Comment by anilatalay** [comment]
Firebase does not automatically create a database for you. You need to go to [https://console.cloud.google.com/firestore/databases](https://console.cloud.google.com/firestore/databases?utm_source=chatgpt.com)
 and create one manually.
After that, you should use it like this: getFirestore("DATABASE_NAME");

**Comment by titocosta** [comment]
I had this issue when I launched my latest firebase project. It seems that `firebase-admin` uses `(default)` as default db name whereas adding a new database from the firebase console now uses `default`.

I solved the issue by explicitly specifying the database name to `default` with `const db = getFirestore(adminApp, 'default');`.

**Comment by MarioDev001** [comment]
Tive o mesmo problema e é por falta do nome do banco de dados, estou usando typescript. 
exemplo de como deve ficar.
`
const db = admin.firestore();
db.settings({ databaseId: 'nome do bd });
`

**Comment by pramolb** [comment]
You need to create a database with the name **(default)**.

Note: The parentheses are mandatory. A database named default (without parentheses) is treated as a regular database. If you use default, you must explicitly specify it when initializing the database.
i.e., default ≠ (default)

**Comment by SamuelSantos96** [comment]
I was able to find a workaround by using the `@google-cloud/firestore` Node.js package.
  
  ```js
  import { Firestore } from '@google-cloud/firestore';
  
  export const db = new Firestore({
    projectId: "PROJECT_ID",
    databaseId: "DB_ID",
    credentials: {
      client_email: "CLIENT_EMAIL",
      private_key: "PRIVATE_KEY"
    }
  });
  ```
  
  Documentation: [https://googleapis.dev/nodejs/firestore/latest/](https://googleapis.dev/nodejs/firestore/latest/)

**Comment by lahirumaramba** [comment]
Admin Node.js SDK supports multiple Firestore databases. You can set the database name in `getFirestore()`

```ts
import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

initializeApp();

// 1. Access the default database ('(default)')
const defaultDb = getFirestore();

// 2. Access a named database (e.g., 'customer-data')
const customerDb = getFirestore('customer-data');
```

If you are having issues with the above, please open a **new** issue instead of responding here so we can track that separately.

**Comment by meMehtab** [comment]
> I had a similar issue and it was because I had named my database `prod` instead of keeping it the default name `(default)`. Deleting prod and creating a new db with the `(default)` name solved the issue for me.

Thanks a lot... It saved me a lot of time
