### ISSUE TITLE
Unable to provision custom bucket, error "does not have storage.buckets.create access to project ..."

### ISSUE THREAD

**Issue by tommed** [firebase/firebase-admin-node#261]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10 (latest updates)
  * Firebase SDK version:  3.18.4 (firebase --version)
  * Library version:  5.12.0 (firebase-admin in packages.json)
  * Firebase Product: storage (via npm package firebase-admin)

#### Steps to reproduce:

Trying to create a custom bucket via the `firebase-admin` npm module and even though my service account 100% has the `storage.buckets.create` permission (I've even created a custom role and explicitly assigned it this along with having the standard *Storage Admin* permission too).

I get the following error:

> firebase-adminsdk-lwphn@XXX.iam.gserviceaccount.com does not have storage.buckets.create access to project 265909605284.

I believe this error is not accurate - or I'm doing something really stupid??

#### Relevant Code:

```javascript
const admin = require('firebase-admin');

const serviceAccount = require('./storage-service-account.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  projectId: serviceAccount.project_id,
  authDomain: 'XXX.firebaseapp.com',
  storageBucket: 'XXX.appspot.com',
});

const bucket = admin.storage().bucket('my.custom.bucket');
bucket.create() // OR bucket.get({ autoCreate: true });
```

**Comment by hiranya911** [comment]
Can you try the same directly with the GCS client library?

```
const storage = require('@google-cloud/storage');
const cert = require('./storage-service-account.json');
const storageClient = storage({
        credentials: {
          private_key: cert.private_key,
          client_email: cert.client_email,
        },
});
const bucket = storageClient.bucket('my.custom.bucket');
bucket.create();
```

This will help us localize the error a little bit better.

**Comment by tommed** [comment]
Thanks. I still get this:

```bash
(node:15068) UnhandledPromiseRejectionWarning: ApiError: firebase-adminsdk-lwphn@XXXX.iam.gserviceaccount.com does not have storage.buckets.create access to project 265909605284.
    at Object.parseHttpRespBody (C:\Users\Me\Desktop\test-google-storage\node_modules\@google-cloud\common\src\util.js:199:30)
    at Object.handleResp (C:\Users\Me\Desktop\test-google-storage\node_modules\@google-cloud\common\src\util.js:137:18)
    at C:\Users\Me\Desktop\test-google-storage\node_modules\@google-cloud\common\src\util.js:502:12
    at Request.onResponse [as _callback] (C:\Users\Me\Desktop\test-google-storage\node_modules\retry-request\index.js:195:7)
    at Request.self.callback (C:\Users\Me\Desktop\test-google-storage\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Me\Desktop\test-google-storage\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
(node:15068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
```

**Comment by hiranya911** [comment]
Ok, I managed to reproduce this error. I believe this happens because the Admin SDK does not specify a project ID when [initializing](https://github.com/firebase/firebase-admin-node/blob/master/src/storage/storage.ts#L77) the Storage client. This is good enough to access an existing bucket (whose names are global), but not sufficient to create new buckets. I think there's a simple fix. 

@tommed can you modify the above code as follows, and see if that works?

```
const storage = require('@google-cloud/storage');
const cert = require('./storage-service-account.json');
const storageClient = storage({
        projectId: cert.project_id, // Set project ID
        credentials: {
          private_key: cert.private_key,
          client_email: cert.client_email,
        },
});
const bucket = storageClient.bucket('my.custom.bucket');
bucket.create();
```

If this works out, I can do the same fix in the Firebase Admin SDK.

**Comment by tommed** [comment]
Ok thanks!! Next error: `The bucket you tried to create is a domain name owned by another user.` - though I used a domain which I do own (and Google DNS is managing), though I haven't updated the DNS to point to storage.google..... - do I need to do this prior to creating the bucket?

**Comment by tommed** [comment]
...Ok so quick update, I tried this with the domain name `tomklmnb.vipro.online.`  which has a CNAME registered with `c.storage.googleapis.com.` (within the same Google Cloud project) and got the same error: 

```bash
PS C:\Users\Me\test-google-storage> node .\index.js
(node:12944) UnhandledPromiseRejectionWarning: ApiError: The bucket you tried to create is a domain name owned by another user.
    at Object.parseHttpRespBody (C:\Users\Me\test-google-storage\node_modules\@google-cloud\common\src\util.js:199:30)
    at Object.handleResp (C:\Users\Me\test-google-storage\node_modules\@google-cloud\common\src\util.js:137:18)
    at C:\Users\Me\test-google-storage\node_modules\@google-cloud\common\src\util.js:502:12
    at Request.onResponse [as _callback] (C:\Users\Me\test-google-storage\node_modules\retry-request\index.js:195:7)
    at Request.self.callback (C:\Users\Me\test-google-storage\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Me\test-google-storage\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
(node:12944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In my service account, I am using the project `vapps-online` which is the same project that owns and manages the `vipro.online` domain name.

**Comment by hiranya911** [comment]
GCP support should be able to help you out. We have limited experience dealing with this particular issue. Firebase users typically use the default bucket associated with the project, which is what's exposed via the Firebase Storage client API.

The Cloud Storage Node.js client team might also have a rough idea what's going on here. They can be reached at https://github.com/googleapis/nodejs-storage

**Comment by tommed** [comment]
Thanks. I emailed them on the 4th, but had no response yet. Unfortunate as I was really hoping to get a workaround for this for a work project. If you have any way of nudging them about this - I'd be extremely grateful!

**Comment by hiranya911** [comment]
@tommed I filed a bug report internally as well. I'll keep an eye on it.
