### ISSUE TITLE
Usage of legacy API

### ISSUE THREAD

**Issue by rodolfoamarques** [firebase/firebase-admin-node#2635]
### Describe your environment

  * Operating System version: all
  * Firebase SDK version: latest (12.2.0)
  * Firebase Product: FCM
  * Node.js version: all
  * NPM version: all

### Describe the problem

the `messaging().send()` method continues to utilise the old API even though it has been deprecated since 2023 and removed since June 2024 as per [this documentation](https://firebase.google.com/support/faq#deprecated-api-shutdown)

#### Steps to reproduce:

Calls/Usage of the above method results in a `TOPIC_MESSAGE_RATE_EXCEEDED` error.

#### Relevant Code:

in this [very repository](https://github.com/firebase/firebase-admin-node/blob/5620e9c6bd59a5db1cad26a64557d8175bbb49f8/src/messaging/messaging.ts#L46) we can find the following code:

```
const FCM_SEND_HOST = 'fcm.googleapis.com';
const FCM_SEND_PATH = '/fcm/send';
const FCM_TOPIC_MANAGEMENT_HOST = 'iid.googleapis.com';
const FCM_TOPIC_MANAGEMENT_ADD_PATH = '/iid/v1:batchAdd';
const FCM_TOPIC_MANAGEMENT_REMOVE_PATH = '/iid/v1:batchRemove';
```

According to the latest documentation, the API to be used should be https://fcm.googleapis.com/v1/projects/{PROJECT_ID}/messages:send

**Comment by devj3ns** [comment]
related: https://github.com/firebase/firebase-admin-node/issues/2602

**Comment by lahirumaramba** [comment]
Thanks @devj3ns !

Hey folks, please see my response in https://github.com/firebase/firebase-admin-node/issues/2602#issuecomment-2322053273

The deprecated endpoints mentioned in the issue are being used in `sendToTopic` and sendToCondition` APIs. These APIs are now deprecated in v12.4.0+
