### ISSUE TITLE
[FR] Optimize Token Retrieval for `Messaging#sendEach` to Reduce Unnecessary Fetch Requests

### ISSUE THREAD

**Issue by bombard1004** [firebase/firebase-admin-node#2645]
**Is your feature request related to a problem? Please describe.**
`Messaging#sendEach` makes an HTTP request for each message. The problem is that it attempts to retrieve a token for each request. Although the tokens are cached internally, the requests are processed concurrently, so the cached value cannot be used, leading to a burst of unnecessary token fetch requests.

**Describe the solution you'd like**
Instead of attempting to retrieve a token for each request, a token should be obtained before sending the requests and then injected into each send request.

**Describe alternatives you've considered**

**Additional context**
Add a `token: string` parameter to `FirebaseMessagingRequestHandler#invokeHttp2RequestHandlerForSendResponse` and include it when creating the request object.
Inside `AuthorizedHttp2Client#send`, remove the `getToken` call and instead find and add the token from the request object passed as a parameter.

**Comment by jonathanedey** [comment]
Thanks @bombard1004 for spotting this. This might be better solved in `getToken()` since it affects any authorized requests that are sent concurrently. We should be tracking and returning the existing promise to the refreshed token if one is already being requested. 

Something like:
```
public getToken(forceRefresh = false): Promise<FirebaseAccessToken> {
  if (forceRefresh || this.shouldRefresh()) {
    if (!this.isRefreshing) {
      this.promiseToCachedToken_ = this.refreshToken();
    }
    return this.promiseToCachedToken_
  }
  return Promise.resolve(this.cachedToken_);
}
```
Where isRefreshing is used as a latch.

What do you think?

**Comment by bombard1004** [comment]
Hi @jonathanedey, thank you for your reply. I agree with your suggestion as this approach indeed covers the issue with concurrent requests more generally. 

Thank you for pointing out a simpler and clearer way. I will close the existing PR accordingly.
