### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1)

### ISSUE THREAD

**Issue by jbeckton** [firebase/firebase-admin-node#266]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 10.13.4
  * Firebase SDK version: 5.12.0
  * Library version: 5.12.0
  * Firebase Product: admin.firestore

#### Steps to reproduce:

What happened? How can we make the problem occur?

 passing an object instance to admin.firebase().collection().doc().set();
I know this is invalid, i am trying to test error handling

This could be a description, log/console output, etc.

(node:4861) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object.

#### Relevant Code:

```
const newDoc = new UserDocument( { email: req.body.email, firstName: req.body.firstName, lastName: req.body.lastName } );

            admin.firestore().collection( 'users' ).doc( userRecord.uid ).set( newDoc )
                .then( () => {
                    // success
                },
                    ( err ) => {
                      //  failed
                    } )
                .catch( ( err ) => {
                    // failed
                } );
```

I am not aware of any other ways to handle promise rejections and errors than the above code. i am trying to test my error handling code so I broke the code on purpose but my error handling never executes because node thinks the promise rejection is not handled.

**Comment by schmidt-sebastian** [comment]
Our input validation logic that does not reject the returned Promise. Instead, it throws an exception immediately as you provide the invalid input. This allows us to return a stacktrace of where the problem occurred. It usually points to problems that should be addressed during development. 

If your code relies on using our input validation (for example, you are passing objects from an end user), please wrap your calls in a Promise:

```
const newDoc = new UserDocument( { email: req.body.email, firstName: req.body.firstName, lastName: req.body.lastName } );

return Promise.resolve().then(() =>          
       admin.firestore().collection( 'users' ).doc( userRecord.uid ).set( newDoc )
);
```

**Comment by jbeckton** [comment]
@schmidt-sebastian  Thank you for addressing this issue. I was expecting your code to reject the promise and I could handle it with a failed callback or catch. Your reasoning makes sense so i have wrapped my code in a try catch and I am able to handle any errors as expected. I was not planning on relying on your code to validate mine but I did want to make sure I had error handling working properly so I broke it on purpose and this is when I discovered the unintended behavior.

**Comment by Jonarod** [comment]
Hey, sorry to comment on this closed issue but I still have the issue after wrapping my firebase calls:

```js
async function checkUser(uid){
  return new Promise( async (resolve, reject) => {
    try {
      let currentUser = await firebase_admin.auth().getUser(uid)
      return resolve(currentUser)
    } catch (e){
      return reject({status: 400, m:'invalid user'})
    }
  })
}
```

then anywhere in my code:

```js
    try {
      let currentUser = await checkUser(parsedData.user)
    } catch (e){
      return reject({status: 400, m: e})
    }
```
always breaks my app with following error:

```bash
(node:7447) UnhandledPromiseRejectionWarning: #<Object>
(node:7447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Jonarod** [comment]
Scratch that... I had a missing `catch(e)` further down the road, unrelated to `Firebase-admin`
Sorry for that...
