### ISSUE TITLE
Access Token Expired Error with Firebase Admin SDK v12.3.1 

### ISSUE THREAD

**Issue by tinyscratch** [firebase/firebase-admin-node#2672]
I updated to the latest version of  **"firebase-admin": "12.3.1" but am still getting this issue with authentication. The same code was working easier, correct. I read that this version refresh token issue is fixed, but i am still getting this issue. please let me know how to resolve this. i am not able to upload bulk data using a Node.js script 

at Object.<anonymous> (/Users/tushar/Documents/codebase/Node/bulk-upload-script/bulk-upload-playlist-songs.js:107:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 16,
  details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
  metadata: Metadata {
    internalRepr: Map(4) {
      'google.rpc.errorinfo-bin' => [Array],
      'grpc-status-details-bin' => [Array],
      'www-authenticate' => [Array],
      'x-debug-tracking-id' => [Array]
    },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient',
  statusDetails: [
    ErrorInfo {
      metadata: [Object],
      reason: 'ACCESS_TOKEN_EXPIRED',
      domain: 'googleapis.com'
    }
  ],
  reason: 'ACCESS_TOKEN_EXPIRED',
  domain: 'googleapis.com',
  errorInfoMetadata: {
    service: 'firestore.googleapis.com',
    method: 'google.firestore.v1.Firestore.Commit'
  }
}

**Comment by lahirumaramba** [comment]
Hey @jonathanedey, could this be related to https://github.com/firebase/firebase-admin-node/pull/2648?

**Comment by jonathanedey** [comment]
I don't think it should be unless Firestore use our internal getToken method before making their rpc call.

**Comment by kiwavi** [comment]
Hi. Getting this error using the raw protocol on nodeJS. How does one get the refresh token using the raw protocol? The docs point out that this is handled automatically. Thanks.
