### ISSUE TITLE
messaging/unknown-error when using sendEachForMulticast

### ISSUE THREAD

**Issue by davideicardi** [firebase/firebase-admin-node#2687]
* Operating System version: AWS Lambda
  * Firebase SDK version: `firebase-admin` 12.3.0 (but also previous versions)
  * Firebase Product: message notification
  * Node.js version: Node.JS 18
  * NPM version: 9

I have a project that send notification messages to Android and IoS. We use `sendEachForMulticast` method. It worked fine for several months. But recently we started to receive the following error:

```
{
"code":"messaging/unknown-error"
"message":"Operation is not implemented, or supported, or enabled. Raw server response: "{"error":{"code":501,"message":"Operation is not implemented, or supported, or enabled.","status":"UNIMPLEMENTED"}}""
}
```

We create the messages, using the `MulticastMessage` type, with the following structure:

```
{
      tokens: [token1, token2],
      data: {
         // ... (string->string)
      },
      android: {
        priority: 'normal',
        ttl: TTL_SECONDS * 1000,
      },
      fcmOptions: {
        analyticsLabel: 'my-label',
      },
      apns: {
        payload: {
          aps: {
            alert: {
              titleLocKey: 'key1',
              locKey: 'key2',
              locArgs: ['value1'],
            },
          },
          contentAvailable: true,
        },
        headers: {
          'apns-expiration': `${Math.floor(Date.now() / 1000) + TTL_SECONDS}`,
        },
      },
    };
```

Any ideas of what can be the problem? It could be related to https://firebase.google.com/docs/cloud-messaging/migrate-v1?authuser=0&hl=en ?

**Comment by davideicardi** [comment]
Sorry, my fault. I still used `sendMulticast` deprecated method.

**Comment by quanndh** [comment]
> sendMulticast

hi what should we use instead?

**Comment by davideicardi** [comment]
sendEachForMulticast 
From the latest version of the lib

**Comment by Sanjeevbadnur** [comment]
Hi Team,

Issue : 
       Facing inconsistent push notifications. With same token without any changes push notifications works for some times and does not works some times.
    
Platform : Android and IOS
Codebase : node.js
Firebase-admin sdk version : 12.4.0
Node.js version: Node.JS 20

Sample node code : 
```
let message = {
  tokens: array of fcm tokens
  notification: 
    {
       title: "test_title",
       body: push notification message,
    },
  data: 
    {
       data: payload,
       alertType: "crash",
    },
};

let response = await firebaseAdmin.messaging().sendEachForMulticast(message);
``` 

The error message is random and either one of them 
1. {"success":false,"error":{"code":"messaging/mismatched-credential","message":"SenderId mismatch"}}

2. {"success":false,"error":{"code":"messaging/unknown-error","message":"Operation is not implemented, or supported, or enabled. Raw server response: \"{\"error\":{\"code\":501,\"message\":\"Operation is not implemented, or supported, or enabled.\",\"status\":\"UNIMPLEMENTED\"}}\""}}

3. {"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}}

**Comment by p29hieu** [comment]
> Hi Team,
> 
> Issue : Facing inconsistent push notifications. With same token without any changes push notifications works for some times and does not works some times.
> 
> Platform : Android and IOS Codebase : node.js Firebase-admin sdk version : 12.4.0 Node.js version: Node.JS 20
> 
> Sample node code :
> 
> ```
> let message = {
>   tokens: array of fcm tokens
>   notification: 
>     {
>        title: "test_title",
>        body: push notification message,
>     },
>   data: 
>     {
>        data: payload,
>        alertType: "crash",
>     },
> };
> 
> let response = await firebaseAdmin.messaging().sendEachForMulticast(message);
> ```
> 
> The error message is random and either one of them
> 
> 1. {"success":false,"error":{"code":"messaging/mismatched-credential","message":"SenderId mismatch"}}
> 2. {"success":false,"error":{"code":"messaging/unknown-error","message":"Operation is not implemented, or supported, or enabled. Raw server response: "{"error":{"code":501,"message":"Operation is not implemented, or supported, or enabled.","status":"UNIMPLEMENTED"}}""}}
> 3. {"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}}

Same Issue

**Comment by levepic** [comment]
Where is it stated that sendEach is deprecated? https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging#messagingsendeach Its still in the docu. Thanks for the answer I couldnt find out whats wrong since they secretely changed the method and the error response is misleading, also tests are misleading because for some of the requests they let it go through while randomly others get refused!:D

**Comment by byeong1** [comment]
same issue

Platform : Android and IOS
Codebase : node.js
Firebase-admin sdk version : 12.2.0,
Node.js version: Node.JS 20.12.1

use fn : sendAll()

----------
Sometimes attempts with the same token will fail and sometimes they will succeed.

**Comment by gokul1630** [comment]
> same issue
> 
> Platform : Android and IOS Codebase : node.js Firebase-admin sdk version : 12.2.0, Node.js version: Node.JS 20.12.1
> 
> use fn : sendAll()
> 
> Sometimes attempts with the same token will fail and sometimes they will succeed.
> 
> [ERROR]
> 
> ```
> [2024-09-12T04:43:08.339Z]  500   ERROR: (Error)Operation is not implemented, or supported, or enabled.
> Raw server response:
> "{"error":{"code":501,"message":"Operation is not implemented, or supported, or enabled.","status":"UNIMPLEMENTED"}}"
> ```

try `sendEachForMulticast`
https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging.md#messagingsendeachformulticast

**Comment by byeong1** [comment]
> > same issue
> > Platform : Android and IOS Codebase : node.js Firebase-admin sdk version : 12.2.0, Node.js version: Node.JS 20.12.1
> > use fn : sendAll()
> > Sometimes attempts with the same token will fail and sometimes they will succeed.
> > [ERROR]
> > ```
> > [2024-09-12T04:43:08.339Z]  500   ERROR: (Error)Operation is not implemented, or supported, or enabled.
> > Raw server response:
> > "{"error":{"code":501,"message":"Operation is not implemented, or supported, or enabled.","status":"UNIMPLEMENTED"}}"
> > ```
> 
> try `sendEachForMulticast` https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging.md#messagingsendeachformulticast

nice!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sawaYch** [comment]
> > same issue
> > Platform : Android and IOS Codebase : node.js Firebase-admin sdk version : 12.2.0, Node.js version: Node.JS 20.12.1
> > use fn : sendAll()
> > Sometimes attempts with the same token will fail and sometimes they will succeed.
> > [ERROR]
> > ```
> > [2024-09-12T04:43:08.339Z]  500   ERROR: (Error)Operation is not implemented, or supported, or enabled.
> > Raw server response:
> > "{"error":{"code":501,"message":"Operation is not implemented, or supported, or enabled.","status":"UNIMPLEMENTED"}}"
> > ```
> 
> try `sendEachForMulticast` https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging.md#messagingsendeachformulticast

Thanks u really save my day 😄 !!
According to the change log, we may upgrade to >=11.7.0
https://firebase.google.com/support/release-notes/admin/node#cloud-messaging_2

**Comment by kokitkar1** [comment]
const response = await admin.messaging().sendEachForMulticast(messageSend);  // Use sendMulticast
use this function didnt get any response further

**Comment by gy0857478** [comment]
> const response = await admin.messaging().sendEachForMulticast(messageSend); // Use sendMulticast use this function didnt get any response further

Any Error Response ?

**Comment by onzou** [comment]
> sendEachForMulticast From the latest version of the lib

Thanks a lot.

**Comment by sumitkumardey91** [comment]
Push notifications are not being delivered in the Android Edge browser when using:
`await this.app.messaging().sendEachForMulticast(message);
`Notifications work as expected in all other browsers.

**Comment by tushar-3154** [comment]
async sendPushNotificationsAllUsers(
    app: admin.app.App,
    deviceTokens: string[],
    title: string,
    body: string,
  ) {
    try {
      const message = {
        notification: { title, body },
        tokens: deviceTokens,
      };

      const response = await app.messaging().sendEachForMulticast(message);
      console.log(response);
    } catch (error) {
      console.error(
        'Error sending push notifications:',
        error?.errorInfo || error,
      );
    }
  }

error :
{
  responses: [ { success: false, error: [FirebaseAppError] } ],
  successCount: 0,
  failureCount: 1
}
