### ISSUE TITLE
FCM: Using http agent causes timeout in 12.3.0 and up

### ISSUE THREAD

**Issue by jaydenschulz09** [firebase/firebase-admin-node#2697]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version:  alpine linux 3.19 
  * Firebase SDK version:  12.3.0 and up
  * Firebase Product: FCM
  * Node.js version: 20.10.0
  * NPM version: 10.2.3

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Since 12.3 we are no longer able to send push notifications using firebaseAdmin.messaging().sendEachForMulticast. We get timeouts only. This is when using an http agent with the sdk. 12.2.0 and lower all work as expected. If I dont use an http agent 12.3.0 and up work correctly but I need to use agent within prod env.  

#### Relevant Code:

```js
const firebaseAdmin = require("firebase-admin");
const { httpsOverHttp } = require("tunnel");

/**
 * @type {import("firebase-admin").AppOptions}
 */
const options = {};
const tunnel = httpsOverHttp({
  proxy: {
    host: config.proxy.host,
    port: config.proxy.port,
  },
});
// assign tunnel to be used by sdk
options.httpAgent = tunnel;
// assign tunnel to be used for tokens
options.credential = firebaseAdmin.credential.cert(config.firebase.serviceAccount, tunnel);

firebaseAdmin.initializeApp(options);

/**
 * @class creates a FirebaseClient object
 */
class FirebaseClient {
  /**
   *
   * @param {import("firebase-admin/lib/messaging/messaging-api").MulticastMessage} notification
   * @returns {Promise}
   */
  sendNotification(notification) {
    return firebaseAdmin.messaging().sendEachForMulticast(notification);
  }
}

module.exports = { FirebaseClient };
```

If you initialize your sdk like so and try to send a push notification you get a timeout. When checking logs it appears the token call works but the FCM call does not. We only get back the below error.

{
        "codePrefix": "app",
        "errorInfo": {
            "code": "app/network-timeout",
            "message": "Error while making request: timeout of 15000ms exceeded."
        },

**Comment by lahirumaramba** [comment]
Hi @jaydenschulz09
In `v12.3.0` we added HTTP/2 support for `sendEach()` and `sendEachForMulticast()` APIs. as far as I know `tunnel` does not support `http2` and I think that's why you are running into this issue.

You can use the `enableLegacyTransport()` method to use the legacy HTTP/1.1 transport or  look for a way to set up the proxy that understands HTTP/2.

**Comment by lahirumaramba** [comment]
My initial assumption might be incorrect as it seems like the httpAgent shouldn't affect the current HTTP/2 implementation in `sendEachForMulticast()`. Could you still test with `enableLegacyTransport()` to check if forcing HTTP/1 works? Thanks!

(cc: @jonathanedey )

**Comment by jaydenschulz09** [comment]
@lahirumaramba This seems to solve the issue.
