### ISSUE TITLE
Server side remote configuration not working on variables in groups

### ISSUE THREAD

**Issue by RodXander** [firebase/firebase-admin-node#2728]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS
  * Firebase SDK version: 12.6.0
  * Firebase Product: remote configuration
  * Node.js version: 20
  * NPM version: 10.5.0

#### Steps to reproduce:

1. In the Firebase Remote Configuration Dashboard, create a variable inside of a group:
![Screenshot 2024-10-13 at 7 10 22 PM](https://github.com/user-attachments/assets/06053bbb-1bd9-4297-b4a3-54a5fb44d042)

2. Try accessing the variable like so fails:

`template.parameters['test_variable']?.defaultValue?.value;`

**Comment by kjelko** [comment]
Thanks for the report! This issue should have been fixed with some internal changes around Nov 20
