### ISSUE TITLE
Improve HTTP Client Implementation

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-node#274]
We need to  improve and refactor our HTTP client code. Currently we are using a `SignedApiRequestHandler` abstraction that uses the `https` package under the hood. This implementation is quite complex to understand and extend. It is also not very amenable to testing. I propose we explore alternatives, and come up with a simpler, more readable and more testable abstraction for making HTTP calls. 

Admin SDK relies on many remote REST APIs and we need a solid HTTP client layer that is both robust and easy to use.

**Comment by NeoLegends** [comment]
We've just had the need to do a batch processing on all of our existing users, and I noticed that there is some room left for performance implementation within the current HTTP stack. For example, you're not using an `https.Agent` to cache DNS lookups and Keep-Alive-Connections, which seems to hurt performance quite a bit.

**Comment by hiranya911** [comment]
This has been implemented. Auth module is already using it, and others will be migrated soon.

**Comment by hiranya911** [comment]
This has been rolled out to all the modules that make HTTP calls.
