### ISSUE TITLE
nsp alerts security vulnerability for protobufjs <=6.8.5

### ISSUE THREAD

**Issue by olastor** [firebase/firebase-admin-node#275]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux x64, Fedora 28
  * Firebase SDK version: 5.12.1
  * Library version: Unknown
  * Firebase Product: firebase-admin-node

#### Steps to reproduce:

`nsp check`

#### Relevant Code:

```
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Denial of Service                                                  │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ protobufjs                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 5 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 5.0.3                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <=6.8.5                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >=6.8.6                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ myproject@0.1.0 > firebase-admin@5.12.1 >             │
│            │ @google-cloud/firestore@0.14.0 > google-gax@0.16.1 > grpc@1.11.3 > │
│            │ protobufjs@5.0.3                                                   │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/605                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

**Comment by schmidt-sebastian** [comment]
We have updated our Protobuf version to 6.8.6.
