### ISSUE TITLE
firebase-admin's farmhash-modern requirement - Node Version Issue

### ISSUE THREAD

**Issue by sanhardik** [firebase/firebase-admin-node#2753]
Operating System: Ubuntu
Code running in Docker
Firebase Admin version: 12.7.0
Node.js version - 16

I had filed a similar issue https://github.com/firebase/firebase-js-sdk/issues/8583

Recent version of farmhash-modern@1.1.0 has a requirement of Node 18 and above. 
However, our code runs on Node 16 and this change has broken existing code. 

In the other issues, the resolution was to revert or fix the dependency.
Can we fix the farmhash-modern dependency to 1.0.0 that allows Node 16

Error:
```error farmhash-modern@1.1.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"````

**Comment by lahirumaramba** [comment]
Hi @sanhardik looks like `farmhash-modern` broke the semantic versioning. Our planned next release would be a major version bump and we also plan to drop support for Node 14 and 16 (which are now deprecated). To fix this issue, please use module resolutions in your package.json until you are ready to upgrade to Node 18. We are also looking into replacing farmhash with an alternative implementation to solve other incompatibilities around that library.
