### ISSUE TITLE
 Conditions with multiple topics not working. Not arriving at device

### ISSUE THREAD

**Issue by holoduke** [firebase/firebase-admin-node#277]
**setup**

Debian 7.11
Firebase 15.0.2
Library version v5.12.1
Firebase Product: Cloud messaging

**Problem:**
I am using the node firebase admin to send messages to Android devices. All works. Except when I try to send messages to multiple topics. In the example code below I simply subscribe to 2 topics and directly afterwards i send a notifications to multiple topics in a condition. Nothing arrives on my Phone. When you just send to one topic, the notification arrives successfully. I don't get why it is not working. There is no error response from the firebase admin. just: 'projects/admob-app-id-xxxx/messages/xxxx'

Execute the code below to see it

```var admin = require("firebase-admin");
var serviceAccount = require("./serviceAccountKey.json");
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
databaseURL: "https://admob-app-id-xxxxx.firebaseio.com"
});

var registrationTokens = ["xxxxx"];
var topica = "AAA";
var topicb = "BBB";
var data = {};

var message = { 
            condition : "'"+topica+"' in topics || '"+topicb+"' in topics",
            data: {'message':JSON.stringify(data)},
            android: {
                ttl: 36000 * 1000,
                priority: 'normal',
                collapseKey: "test"
            }
        };



        admin.messaging().subscribeToTopic(registrationTokens, topica)
            .then(function(response) {

                admin.messaging().subscribeToTopic(registrationTokens, topicb)
                    .then(function(response) {

                        admin.messaging().send(message, dryRun)
                            .then((response) => {
                            console.log('success', response);
                    }).catch((error) => {
                            console.log('error', error);
                    });

                    })
                .catch(function(error) {
                    console.log('Error subscribing to topic:', error);
                });
            })
            .catch(function(error) {
                console.log('Error subscribing to topic:', error);
        });`

**Comment by hiranya911** [comment]
This might be related https://stackoverflow.com/questions/47569891/topic-name-case-sensitivity-and-condition-not-working

**Comment by holoduke** [comment]
Yes. It looks like that person has the same problem.

**Comment by sampson-chen** [comment]
The Admin SDK forwards the request to FCM Send Service HTTP API, which forwards it to the underlying topics infrastructure.

Please open a ticket with Firebase Support so we can gather more details to help troubleshoot and debug. Thanks!
