### ISSUE TITLE
[FR] In actionCodeSettings , I cannot use OneLink domain as dynamicLinkDomain

### ISSUE THREAD

**Issue by keisan1231** [firebase/firebase-admin-node#2771]
**Is your feature request related to a problem? Please describe.**

We use methods like generateSignInWithEmailLink to authenticate and then directly redirect to the app via Dynamic Links. However, since the Dynamic Links service is scheduled to be discontinued in August, we are attempting to replace it with AppsFlyer's OneLink.

**Describe the solution you'd like**
I would like to be able to set AppsFlyer's OneLink domain as the dynamicLinkDomain.

**Describe alternatives you've considered**
I considered creating that mechanism myself without using the generateEmailVerificationLink method, but if possible, I would like to continue using generateEmailVerificationLink as it is.

**Additional context**

This code get error "Error: The provided dynamic link domain is not configured or authorized for the current project."
I have already done [this](https://github.com/user-attachments/assets/07b74f94-f754-4a81-9572-c22bc6968260)（onelink.me is appsflyer onelink）

```js
const actionCodeSettings = {
  url: 'https://www.example.com/checkout?cartId=1234',
  handleCodeInApp: true,
  iOS: {
    bundleId: 'com.example.ios',
  },
  android: {
    packageName: 'com.example.android',
    installApp: true,
    minimumVersion: '12',
  },
  // FDL custom domain.
  dynamicLinkDomain: 'coolapp.page.link',
};

admin.auth().generateEmailVerificationLink(to_email, actionCodeSettings);
```

**Comment by Xiaoshouzi-gh** [comment]
Our team is actively working on this, please stay tuned.

**Comment by keisan1231** [comment]
@Xiaoshouzi-gh I am looking forward to it
Please let me know a current alternative method using OneLink that is equivalent to `generateEmailVerificationLink`

**Comment by Xiaoshouzi-gh** [comment]
You cannot use any customized domain as your dyanamicLinkDomain value when calling generateEmailVerificationLink.  Our API need to verify if the domain provided is a valid FDL domain and has the correct owner in our backend.

**Comment by keisan1231** [comment]
OK, I see
Thank you for response
