### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by iRoachie** [firebase/firebase-admin-node#283]
### Environment

  * Operating System version: OS X 10.13.4
  * Firebase SDK version: 3.18.5
  * Library version: (firebase-admin)
  * Firebase Product: admin

###  Problem
Running npm install fails with error: 
```
npm i --save firebase-admin
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^6.8.0
```
#### Steps to reproduce:
`npm install --save firebase-admin`

**Comment by t-yng** [comment]
I have the same problem.

**Comment by taybell** [comment]
Same problem

**Comment by dem97171** [comment]
Same problem [this issue](https://github.com/dcodeIO/protobuf.js/issues/1057).
I did
`npm -g config set registry https://registry.npm.taobao.org`
before
`npm install --save firebase-admin`

**Comment by hiranya911** [comment]
I assume this issue, which seem to have been caused by a temporary glitch in NPM servers, is now resolved. At least I don't see it any more in our CI servers.
