### ISSUE TITLE
Typescript: @google_cloud/storage and firebase-admin have conflicting definitions of Storage

### ISSUE THREAD

**Issue by osdiab** [firebase/firebase-admin-node#289]
* Operating System version: Mac OS 10.13.4
  * Library version: ^5.12.0, @google_cloud/storage version: ^1.6.0
  * Firebase Product: storage (auth, database, storage, etc)

#### Steps to reproduce:

Make a Node project with both `@google-cloud/storage` and `firebase-admin` as dependencies. Can't make a function that takes either of these libraries definitions of `Storage`, because their type signatures differ; I am trying to configure the buckets they use differently depending if I'm on test or prod environment, but since even their definitions for the `bucket` function differ, it's a pain.

#### Relevant Code:

```
import * as Storage from "@google-cloud/storage";
import { storage as adminStorage } from "firebase-admin";

function getBucket(storage: Storage.Storage | adminStorage.Storage, bucketName: string) {
  return storage.bucket(bucketName);
  // above error: Cannot invoke an expression whose type lacks a call signature. Type '((name?: string | undefined) => Bucket) | ((name: string | Bucket) => Bucket)' has no compatible call signatures.
}
```

Pretty annoying!

**Comment by hiranya911** [comment]
These 2 types are not supposed to be compatible. `admin.storage.Storage` is Admin SDK's Storage API and has one method:

```
declare namespace admin.storage {
  interface Storage {
    app: admin.app.App;
    bucket(name?: string): Bucket;
  }
}
```

GCS `Storage` type supports many other things:

```
class Storage {
        constructor(config?: ConfigurationObject);
        acl: Acl;
        bucket(name: string | Bucket): Bucket;
        channel(id: string, resourceId: string): Channel;
        createBucket(name: string, metadata?: BucketConfig): Promise<[Bucket, ApiResponse]>;
        getBuckets(query?: BucketQuery): Promise<[Bucket[]]>;
        getBucketsStream(query?: BucketQuery): Promise<[ReadStream]>;
        Channel: (storage: Storage, id: string, resourceId: string) => Channel;
        File: (bucket: Bucket, name: string, opts: BucketFileOptions) => File;
        Bucket: (storage: Storage, name: string) => Bucket;
}
```

They were never intended to be used the way you're trying to. If you must do this, define your own interface with a `bucket()` method, and create 2 implementations wrapping Firebase and GCS APIs.

**Comment by fanismahmalat** [comment]
@hiranya911 so how should I type my bucket from firestore-admin? I used to type it as `Bucket` from `@google-cloud/storage` but now the types are not the same

**Comment by lahirumaramba** [comment]
You should still be able to type is as `Bucket`. The admin sdk exposes the same type.
https://cloud.google.com/nodejs/docs/reference/storage/latest/Bucket

**Comment by guillaumeprevost** [comment]
Hi, I have a similar issue : I had implemented test cases with Jest that worked well until recently.
Now I get an error from my editor in my test file : 

```
import init from './firebase-config'
const { auth, firebaseFunctions, firebaseTest } = init('imagethumbnails')
import * as admin from 'firebase-admin'
import { Bucket } from '@google-cloud/storage'

...

jest.spyOn(admin.storage(), 'bucket').mockImplementation(() => ({
  file: jest.fn(() => ({
    download: jest.fn(),
    delete: jest.fn(),
  })),
  upload: jest.fn()
} as unknown as Bucket))

...
```

The error is raised when TypeScript compares the Bucket type in admin.storage().bucket and the Bucket type in @google-cloud/storage : 

```
Type 'import("./node_modules/@google-cloud/storage/build/src/bucket").Bucket' is not assignable to type 'import("./node_modules/firebase-admin/node_modules/@google-cloud/storage/build/src/bucket").Bucket'.
  The types of 'storage.createBucket' are incompatible between these types.

    Type '{ (name: string, metadata?: import("./node_modules/@google-cloud/storage/build/src/storage").CreateBucketRequest): Promise<import("./node_modules/@google-cloud/storage/build/src/storage").CreateBucketResponse>; (name: string, callback: import("./node_modules/@google-cloud/st...' is not assignable to type '{ (name: string, metadata?: import("./node_modules/firebase-admin/node_modules/@google-cloud/storage/build/src/storage").CreateBucketRequest): Promise<import("./node_modules/firebase-admin/node_modules/@google-cloud/storage/build/src/storage").CreateBucketResponse>; (name: string, callbac...'.
      Types of parameters 'metadata' and 'callback' are incompatible.
        Type 'BucketCallback' has no properties in common with type 'CreateBucketRequest'.ts(2322)
[index.d.ts(1198, 33): ]()The expected type comes from the return type of this signature.
```

**From what I understand, the types (Storage, Bucket) as defined in `@google-cloud/storage v5.3.0` imported by firebase-admin is not compatible with the latest version `5.18.2` that is used in my project.**

I don't know if firebase-admin should upgrade its dependencies to the latest version, or if this issue should be raised in  @google-cloud/storage to make theie types compatible between versions.

**Comment by JS-GitRepo** [comment]
You have to type the import out manually as intellisense / TypeScript do not pick them up automatically, but you can change your Bucket types import from 
```js
import { Bucket } from "@google-cloud/storage"
```
to
```js
import { Bucket } from "firebase-admin/node_modules/@google-cloud/storage"
```

**Comment by JS-GitRepo** [comment]
I was able to resolve by finding the corresponding @google-cloud/storage version in the firebase-admin/node_modules, then setting my @google-cloud/storage version to be the same in package.json. 

Deleted node_modules and reinstalled. All is working well now with type imports from @google-cloud/storage

**Comment by mrjackyliang** [comment]
> I was able to resolve by finding the corresponding @google-cloud/storage version in the firebase-admin/node_modules package.json, then setting my @google-cloud/storage version to be the same in my projects package.json.
> 
> Afterword, deleted node_modules and reinstalled them. All is working well now with type imports from @google-cloud/storage

Confirming this workaround worked for me.

**Comment by sebastianrueckerai** [comment]
The workaround means ad package downgrade, that hardly even qualifies as a workaround. Could someone look at this issue and fix it? It is still present...
