### ISSUE TITLE
Error parsing triggers: Cannot find module '@custom-path'

### ISSUE THREAD

**Issue by rwmb** [firebase/firebase-admin-node#294]
* Operating System version: win10
  * Firebase SDK version: latest
  * Firebase Product: all
  
I'm trying to use Path Mapping for Cloud Functions but when I use a custom path like import * as b from '@custom-path/barrel' I get an error on tslint for implicit imports. If I disable this rule and try to deploy, I get the following error:

> Error parsing triggers: Cannot find module '@custom-path'

Code example:
```
 "baseUrl": "../",
    "paths": {
      "@be-utils/*": ["functions/src/utils/*"],
    }
```

Tried this as well:
```
"baseUrl": ".",
  "paths": {
    "@custom-path/*": ["src/utils/*"],
    "@other-path/*": ["../other/path/*"]
  }
```

Am I doing something wrong?
If not, how can I use path mapping with Cloud Functions? Thanks.
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

**Comment by hiranya911** [comment]
Please use stackoverflow or the Google group for usage questions such as this.

**Comment by rwmb** [comment]
Ok I give up. I can't get help on this anywhere, thanks

**Comment by zhamid-src** [comment]
Did you ever figure it out? I have the same issue and it was working before.
