### ISSUE TITLE
Install without compiling gRPC module

### ISSUE THREAD

**Issue by albinekb** [firebase/firebase-admin-node#295]
* Operating System version: Amazon Linux 4.4.4
  * Firebase SDK version: 5.12.1
  * Library version: ?
  * Firebase Product: Messaging

#### Steps to reproduce:

`yarn add firebase-admin` or `npm install firebase-admin` will start to compile some gRPC native module with node-gyp since there aren't any pre-built binaries for this platform.

This requires a lot of memory, making it so we can't run our server on a t2.micro (512MB), and instead need to use t2.medium, just because it's trying to compile this native module.

Is there any way to use firebase messaging without needing to compile native module on install..?

_I worked around this by compiling it inside docker before deploying. It would be nice if these packages was split out as separate things so we didn't need to install everything including this native dependency when I just need the messaging parts_

**Comment by hiranya911** [comment]
@schmidt-sebastian in what scenarios does the installer decide to compile native code vs reuse a precompiled binary?

**Comment by schmidt-sebastian** [comment]
The GRPC pre-builts are provided by the GRPC team. The are published at well-known URLs, and only when these URLs don't exist does NPM end up compiling GRPC from source. I will ping the GRPC team and let them know that we need pre-builts for Linux 4.4.4 on AWS.

**Comment by albinekb** [comment]
Would be nice to have them for the latest 4.5.2 too 🙏

**Comment by murgatroid99** [comment]
That error log says that it's downloading gRPC 1.7. That is a pretty old version, and it doesn't have prebuilt binaries for Node 9. Are you installing an older version of `firebase-admin`? As for the `node-gyp` problem, I can only think that there is something unusual with your Node installation. I believe that it normally just comes with npm.

**Comment by albinekb** [comment]
But why do we have to compile this native module when we don't use that functionallity? Can't it be put in a separate library or as a peer dependency you need to explicitly opt-in to.

**Comment by Lizzardd** [comment]
I have a similar issue

npm install -g firebase-admin    

> grpc@1.13.1 install /usr/local/lib/node_modules/firebase-admin/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.13.1 and node@8.11.3 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/.node-gyp'
gyp ERR! System Linux 4.15.0-1014-gcp
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/firebase-admin/node_modules/grpc
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-1014-gcp
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/firebase-admin/node_modules/grpc
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/lib/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-06T09_18_08_653Z-debug.log

**Comment by hiranya911** [comment]
@schmidt-sebastian how about we make Firestore an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies), at least until these installation issues get sorted out?
