### ISSUE TITLE
MODULE_NOT_FOUND Error while creating Document

### ISSUE THREAD

**Issue by warlockdn** [firebase/firebase-admin-node#304]
I am using firebase-admin to add and update documents to firebase. While creating a document in localhost its clearly able to create and update documents.

Now I have uploaded the same thing to the server and installed everything. On creating a document. I receive this error through winston.

{"code":"**MODULE_NOT_FOUND**","level":"info","message":"Error"}

Can't seem to understand what exactly is a issue here.

**Environment:-**

Nodejs v8.1.1
Express with MongoDB
Using Babel build.

Please advise.

**Comment by hiranya911** [comment]
This is not an error raised by firebase-admin. So you will have to debug through the rest of your software stack to figure out what's going on.
