### ISSUE TITLE
'npm install --save firebase-admin' installs and uses dns, dgram and native-dns which are deprecated

### ISSUE THREAD

**Issue by nvrrdt** [firebase/firebase-admin-node#31]
When I do an 'npm run dev' I get missing dependencies, probably based on the fact that dns, dgram and native-dns are deprecated and thus not maintained.

''' 
This dependency was not found:

* dns in ./~/firebase-admin/~/isemail/lib/isemail.js

To install it, you can run: npm install --save dns
'''

Thanks for any information to solve this issue.

**Comment by jshcrowthe** [comment]
Hey @nvrrdt the firebase-admin SDK doesn't expose a `dev` script so I don't have any context of the script you're talking about.

Additionally `dns`, `dgram`, and `native-dns` are nowhere in the dependency tree for the Admin Node SDK.

_I validated this by executing the following commands at the root of the pakcage:_
-`npm ls | grep dns`
-`npm ls | grep dgram`
-`npm ls | grep native-dns`

**Comment by jshcrowthe** [comment]
@nvrrdt I'm going to close this for now, if you find any more information on this please let me know!

**Comment by nvrrdt** [comment]
@jshcrowthe , sorry for the delay, I couldn't delve in this earlier.
Anyhow: 'npm install --save firebase-admin' works flawlessly
the moment I add 'import * as admin from 'firebase-admin'' I get:
` ERROR  Failed to compile with 11 errors                                                                                                                          7:03:00 AM

These dependencies were not found:

* net in ./~/forever-agent/index.js, ./~/tunnel-agent/index.js and 3 others
* tls in ./~/forever-agent/index.js, ./~/tunnel-agent/index.js and 1 other
* fs in ./~/request/lib/har.js, ./~/firebase-admin/lib/auth/credential.js
* dns in ./~/firebase-admin/~/isemail/lib/isemail.js

To install them, you can run: npm install --save net tls fs dns`

I really have no idea why I get this.
Any pointers are really appreciated.

**Comment by jshcrowthe** [comment]
@nvrrdt can you provide me a little context of your use case? Those are all native node libs that should all be available in a Node client. Are you trying to run this in a browser?

**Comment by nvrrdt** [comment]
@jshcrowthe , it's basically a vue project which I'd like to connect to a firebase backend. I'd like to implement a search field with autocomplete/suggest, for this search field I wanted to use firebase/flashlight to connect to an elasticsearch implementation as explained on firebase/flashlight, which also explains to add firebase-admin to my project.
In case you need my project files, it's [https://github.com/nvrrdt/ego](https://github.com/nvrrdt/ego)
I am trying to run this in a browser.

**Comment by nvrrdt** [comment]
@jshcrowthe , I figured out I installed firebase-admin in the wrong directory and I shouldn't even have installed firebase-admin. I now have time to work on this and if I encounter a new problem I will resort to stackoverflow. Thanks anyway and sorry for bothering you.

**Comment by jshcrowthe** [comment]
@nvrrdt no worries at all! Just as a good rule of thumb, if you are looking to use firebase in a "client" environment (i.e. a web app, mobile app, etc) use the Firebase SDK. The Admin SDKs are more for privileged server clients.

**Comment by aaaguirrep** [comment]
Hi, did you fix the issue?

I am having the same issue, i have reported in the next link:
https://stackoverflow.com/questions/52711421/issue-using-firebase-admin-dependencies-were-not-found
