### ISSUE TITLE
firebase-admin v5.13.0 - Unexpected error while acquiring application default credentials: Could not load the default credentials

### ISSUE THREAD

**Issue by itspradhan** [firebase/firebase-admin-node#310]
* Operating System version: MacOs High Sierra

#### This issue kept repeating for all tasks in cloud store - get/set

```
const admin = require("firebase-admin");
const serviceAccount = require("./service-key.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://[db-name].firebaseio.com"
});

var db = admin.firestore();

var newPostRef = db.collection('posts').add({
  post: "Hello!",
  username: "snowboard"
}).then(ref => {
  console.log('Added document with ID: ', ref.id);
});

```
#### Error:

`Unexpected error while acquiring application default credentials: Could not load the default credentials
`
#### Temporary Solution:

Meanwhile, I downgraded to version 5.12.0 of firebase-admin and was able to read and write the document from/to the cloud store.

**Comment by hiranya911** [comment]
This is already fixed. See #308 and the Firestore issues referenced in there.
