### ISSUE TITLE
messaging/localization

### ISSUE THREAD

**Issue by mirelalazar** [firebase/firebase-admin-node#311]
Trying to send localised messages.
I'm getting the following error: 
Invalid JSON payload received. Unknown name "title_loc_args" at 'message.notification': Cannot find field.

**Comment by hiranya911** [comment]
Notification type does not support `titleLocArgs`: https://firebase.google.com/docs/reference/admin/node/admin.messaging.Notification

It's only supported in `AndroidNotification` and `ApsAlert`.
