### ISSUE TITLE
Firebase Functions on 5.13.0 produce "Cannot read property 'seconds' of null" errors.

### ISSUE THREAD

**Issue by kawauso** [firebase/firebase-admin-node#312]
Firebase Functions on 5.13.0 produce "Cannot read property 'seconds' of null" errors.

```
TypeError: Cannot read property 'seconds' of null
    at Function.fromProto (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/timestamp.js:91:46)
    at _firestore.request.then.resp (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:472:42)

```

**Comment by hiranya911** [comment]
Functions peer dependency is on 5.12.1. You should stick to that version, until the next version of Functions comes out.

**Comment by stevejcox** [comment]
Seeing the same issue on functions 2. Is there an ETA on when a new admin will be released supporting functions 2?

**Comment by kawauso** [comment]
This issue shouldn't be closed until the errors gone.

**Comment by hiranya911** [comment]
@kawauso there's nothing to be done at the `firebase-admin` level as it already uses the latest Firestore. @laurenzlong @schmidt-sebastian any thoughts?

**Comment by schmidt-sebastian** [comment]
Hey! Chiming in here. Are you using empty write batches? It looks like we choke on the server response if you don't add a write operation. We will fix this in the next release of `@google-cloud/firestore`. Thanks for finding this one!

**Comment by stevejcox** [comment]
Looks like there was an edge case where it was possible that the batch could have been empty, so it confirms your theory. I've made an adjustment to prevent that in my code.

Appreciate your responses @hiranya911  and @schmidt-sebastian
