### ISSUE TITLE
send message to array of registrationToken

### ISSUE THREAD

**Issue by shSina** [firebase/firebase-admin-node#315]
there should be some way to send a notification to array of registrationTokens ,
```js
const registrationToken = 'some user token'
const message = {
	token:registrationToken,
	data: {
		test: 'test'
	},
	notification: {
		title: "test",
		body: "test"
	},
	topic:'test'
}
```

**Comment by mskv** [comment]
There is the [sendToDevice](https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging.ts#L762) method that allows to send to multiple device tokens in bulk, but it's got its own issues. The message definition seems to have evolved in [send](https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging.ts#L730) method. It allows to specify more platform-specific fields with `apns`, `android` and `webpush` keys. Some of them don't seem to be available in `sendToDevice` in any way.

For instance I need to set
```
apns: {
  headers: {
    "apns-collapse-id": "..."
  }
}
```
But there does not seem to be any way to do it using the `sendToDevice`. 

The plain `send` does not support bulk-send however. The only way I see to send to multiple devices AND benefit from the additional platform-specific settings is to use `send` multiple times. But there is the problem with the HTTP client in this package mentioned in the following comment: https://github.com/firebase/firebase-admin-node/issues/274#issuecomment-391902891 , making this alternative even less attractive. 

Am I missing something or is this a correct description of the current state of affairs?

**Comment by hiranya911** [comment]
@crysislinux you should use the old `sendToDevice()` method if you need this functionality today. We are planning to support a new token-based multicast feature, but it will be months before we have anything ready for testing.

**Comment by miladr0** [comment]
@hiranya911 thanks for answer, i think `sendToDevice()` is not available in last version. i think this feature is needed by every one.

**Comment by hiranya911** [comment]
`sendToDevice()` is very much available.

API docs: https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging
Source: https://github.com/firebase/firebase-admin-node/blob/v6.4.0/src/messaging/messaging.ts#L820

**Comment by crysislinux** [comment]
@hiranya911 Thanks.

@miladr0 sendToDevice works here

**Comment by hiranya911** [comment]
Update: We are working on a new batch send API that is aimed at supporting this use case more elegantly. Stay tuned.

**Comment by MHDuke** [comment]
can you please clarify whether this feature available in the API but is missing in node admin sdk, Or, is it not available in API altogether?

**Comment by hiranya911** [comment]
It's not supported by the FCM service (not supported by the FCM v1 API to be exact). You can explore the FCM REST API here: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

**Comment by chong-shao** [comment]
This feature is released today. See https://firebase.google.com/support/releases

**Comment by mattiagalati** [comment]
Are there some previsions for support this feature in Admin SDK for Python?
related to https://github.com/firebase/firebase-admin-python/issues/196

**Comment by hiranya911** [comment]
@mattiagalati, yes eventually we want to support it in Python. I will reopen the above issue, and open it up for pull requests, in case somebody would like to contribute us some code.

**Comment by nesttle** [comment]
Interested!
