### ISSUE TITLE
FR: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'id' of null

### ISSUE THREAD

**Issue by djom20** [firebase/firebase-admin-node#32]
Hello,

So I'm try to call the key in the snapshot but I get this error:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'id' of null`

I'm using firebase-admin: 4.2.1 and nodejs 6.9.1, the firebase product is storage, I'm using MacOx and my code is:

``` 
var db = admin.database().ref('events/-KlGpV1rBu9iACpwdluZ').orderByKey(),
        deferred = Q.defer(),
        childData = null,
        info = [];

    db.once("value").then(function(snapshot) {
        snapshot.forEach(function(childSnapshot) {
            console.log('key', childSnapshot.key);
            console.log('val', childSnapshot.val());

            info.push(childSnapshot.key);
        });

        deferred.resolve(info);
    });

    return deferred.promise;
```

I have been reading all documentation about the key and I didn't found any issue in the code. Is possible that the problem is that the documentation is not updated or has issues?

Thanks

**Comment by hiranya911** [comment]
I think this has something to do with your use of `Q`. It doesn't seem to be a problem with the Firebase database client. I'm testing with the following bit of code:

```
var db = admin.database().ref('events').orderByKey();
db.once("value").then(function(snapshot) {
        snapshot.forEach(function(childSnapshot) {
            console.log('key', childSnapshot.key);
            console.log('val', childSnapshot.val());
        });
});
```

My database has the following nodes:

```
+- events
   `----- k1: "v1"
    |---- k2: "v2"
```
I get the output:

```
key k1
val v1
key k2
val v2
```
Seems all right to me.

**Comment by hiranya911** [comment]
I tried with the `Q` library as well, and it seems to work fine.

```
var db = admin.database().ref('events2').orderByKey();
var deferred = Q.defer();
var info = [];
db.once("value").then(function(snapshot) {
        snapshot.forEach(function(childSnapshot) {
            console.log('key', childSnapshot.key);
            console.log('val', childSnapshot.val());
            info.push(childSnapshot.key);
        });

        deferred.resolve(info);
}, function(error){
  deferred.reject(error);
});

deferred.promise.then(function(data){
  console.log(data);
});
```

Output:

```
key k1
val v1
key k2
val v2
[ 'k1', 'k2' ]
```

**Comment by hiranya911** [comment]
I will close this ticket, since I cannot seem to find a bug here in the Admin SDK code. Please feel free to reopen with more information if you continue to run into problems.
