### ISSUE TITLE
All firestore set(doc) calls fail due to "Error:Argument "documentPath" is not a valid ResourcePath. Path must be a non-empty string"

### ISSUE THREAD

**Issue by sharanan** [firebase/firebase-admin-node#320]
### Environment

  * Operating System version: macOS High Siera (10.13.3)
  * Firebase Admin Node SDK version: 5.12.1
  * Firebase Functions version: 1.0.3
  * Firebase Product: Firestore, Functions

### Problem
While creating a new document/collection in firestore using firebase admin node sdk, within a cloud function, all requests fail with following error:-

Argument "documentPath" is not a valid ResourcePath. Path must be a non-empty string.
    at Object.exports.(anonymous function) [as isResourcePath] (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/validate.js:86:15)
    at CollectionReference.doc (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/reference.js:2113:16)
    at Promise (/user_code/lib/api.js:10:37)
    at Object.exports.createNewClient (/user_code/lib/api.js:8:12)
    at Object.<anonymous> (/user_code/lib/index.js:55:33)
    at next (native)
    at /user_code/lib/index.js:7:71
    at __awaiter (/user_code/lib/index.js:3:12)
    at Request.request [as _callback] (/user_code/lib/index.js:47:70)
    at Request.self.callback (/user_code/node_modules/request/request.js:185:22)
 
#### Steps to reproduce:
Try creating a new doc using firestore -> collection.doc(doc.id).set(doc)

#### Relevant Code:
My application code that's failing (this was working a few minutes ago and started failing without any changes):-
export const createNewClient = (client) => {
  return new Promise((resolve, reject) => {
    store.collection("clients").doc(client.id).set(client).then(docRef => {
      resolve(client);
    }, error => {
      reject(error);
    });
  });
}

**Comment by schmidt-sebastian** [comment]
Can you let us know what `client.id` is? That would help me determine what is going on here.

**Comment by sharanan** [comment]
Its a hashcode generated with uuid/v4. 
Here's a sample:- `7d266f05-f476-4e0e-b11f-ad48e39952b8`

**Comment by loloDawit** [comment]
having the same issue
         `Error: Argument "documentPath" is not a valid ResourcePath. Path must be a non-empty string.
    at Object.exports.(anonymous function) [as isResourcePath] (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/validate.js:89:23)
    at CollectionReference.doc (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:1813:22)
    at exports.updateLikeCount.functions.https.onRequest (/user_code/lib/index.js:14:43)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:686:7
    at /var/tmp/worker/worker.js:670:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

**Comment by schmidt-sebastian** [comment]
@loloDawit Note that your code is missing parenthesis. It should be

```
doc("postId").get()
```

 instead of 
```
doc("postId".get()
```

**Comment by loloDawit** [comment]
that a typo here is the exact code 
     

    admin.firestore().collection("posts").doc(postId).get().then((data)=>{
        console.log(data);
        let likeCount = data.data().likeCount || 0; // if like doesn't exists pass 0
        let like = data.data().like || [];

        let updateData = {}; 

        if(action == "like"){
            updateData["likeCount"] = ++likeCount; 
            updateData[`like.${userId}`] = true; 
        }else{
            updateData["likeCount"] = --likeCount; 
            updateData[`like.${userId}`] = false; 
        }

        admin.firestore().collection("posts").doc(postId).update(updateData).then(()=>{
            response.status(200).send("Done")
        }).catch((err)=>{
            response.status(err.code).send(err.message);
        })
    }).catch((err)=>{
        response.status(err.code).send(err.message); 
    })
})
`

**Comment by loloDawit** [comment]
I've figured out the issue. the issue is not related to firebase. It's the way I was testing my code using the postman app. The raw data needs to be in JSON format. By default is set to text, it must be changed to JSON(application/json)

**Comment by FlavioMarquesInf** [comment]
> that a typo here is the exact code
> 
> ```
> admin.firestore().collection("posts").doc(postId).get().then((data)=>{
>     console.log(data);
>     let likeCount = data.data().likeCount || 0; // if like doesn't exists pass 0
>     let like = data.data().like || [];
> 
>     let updateData = {}; 
> 
>     if(action == "like"){
>         updateData["likeCount"] = ++likeCount; 
>         updateData[`like.${userId}`] = true; 
>     }else{
>         updateData["likeCount"] = --likeCount; 
>         updateData[`like.${userId}`] = false; 
>     }
> 
>     admin.firestore().collection("posts").doc(postId).update(updateData).then(()=>{
>         response.status(200).send("Done")
>     }).catch((err)=>{
>         response.status(err.code).send(err.message);
>     })
> }).catch((err)=>{
>     response.status(err.code).send(err.message); 
> })
> ```
> })
> `

this is from Feedly app cource, a change the like function and works:

  like(post) {
    const body = {
      postId: post.id,
      userId: firebase.auth().currentUser.uid,
      action: post.data().likes && post.data().likes[firebase.auth().currentUser.uid] === true ? 'unlike' : 'like'
    };

    console.log(body);

    const headers = new HttpHeaders()
      .set('Access-Control-Allow-Origin', '*')
      .set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT')
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json');

    // OBS: o (responseType: 'text') impede que a resposta seja parseada como json,
    // evitando erro, pois nesse caso a resposta é uma string apenas e não um objeto json.
    const url = 'https://us-central1-feedly-5d2b1.cloudfunctions.net/updateLikesCount';
    this.http.post(url, body, {
      headers: headers,
      responseType: 'text',
    }).subscribe(data => {
      console.log(data);
    }, error => {
      console.log(error);
    });

  }

**Comment by jbiddulph** [comment]
any fix for this yet?

**Comment by karthigb** [comment]
Same issue

**Comment by smashah** [comment]
To those still having this issue try:

`admin.firestore().collection('whatever').doc(""+id);`

or use ``${id}`` surrounded with backtics `

**Comment by baristaGeek** [comment]
@smashah thanks. This is the most straightforward solution

**Comment by CodierVersuche** [comment]
> To those still having this issue try:
> 
> `admin.firestore().collection('whatever').doc(""+id);`
> 
> or use `${id}` surrounded with backtics `

both these not working for me

**Comment by jpelton-stroud** [comment]
just ran into this in my own project, discovered that the data I was grabbing did, in fact, have an object with an empty key:
````
   { items: { '': [Object], A: [Object], B: [Object], C: [Object] },
     size: 4 }
````

**Comment by smashah** [comment]
If you have issues with empty properties then please try stringifying the object then immediately parsing it then sending it to Firestore.

E.g

.....update(JSON.parse(JSON.stringify(objectToSend)))

**Comment by jpelton-stroud** [comment]
Awesome, I'll give it a shot; thanks for the heads up!

**Comment by pradeepgill007** [comment]
The document id you are passing as a reference is not matching with document id in the Firestore in case of an updation.

**Comment by kierandesmond** [comment]
Hi All,

I have this issue only with a trigger / onCreate -
To me it looks like standard trigger code. Compared it to the docs and still no joy. Any ideas?

`
exports.onIntroductionAdded = functions
.region("europe-west1")
.firestore.document('introductions/{introductionId}')
.onCreate(async (snapshot) => {
  // const batch = db.batch();
  try {


}
catch(e){

}
}`

Thank you,
Kieran

**Comment by laurenzlong** [comment]
@kierandesmond If you are able to deploy the function, then the code you provided is not what's causing the issue, it's probably another line of code inside your function.

**Comment by GzhiYi** [comment]
> I've figured out the issue. the issue is not related to firebase. It's the way I was testing my code using the postman app. The raw data needs to be in JSON format. By default is set to text, it must be changed to JSON(application/json)

That is right.Set body to "JSON" will solve this issue.
![image](https://user-images.githubusercontent.com/21136420/85517968-5e9a1e00-b632-11ea-8cbf-39058fba0f96.png)

**Comment by sk8killer** [comment]
I also encounter this error but with a query : 

```
console.log('SIREN number to check :', siren)
console.log('siren isNumber :', Number.isInteger(siren))
const q = await db.collection('Customer').where('Siren', '==', siren).get()
```

It throws an error as described here wheareas I checked that the variable was indeed a Number and an integer. 

```
SIREN number to check : 437526296
siren isNumber : true
throw new Error('${(0, validate_1.invalidArgumentMessage)(arg, 'resource path')} Path must be a non-empty string.');
Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.
```

But I am on a query !!! "siren" is not a ressource path !

I tried to update every package, I also tried stringyfy then parsing it... whitout luck.

Seems that firebase-function have a bug here.

Any help ?
