### ISSUE TITLE
Uploading image to storage through admin gives "Error during request"

### ISSUE THREAD

**Issue by chriseenberg** [firebase/firebase-admin-node#325]
#### Environment details

  - OS: MacOS 10.13.5
  - Node.js version: 6.11.5
  - npm version: 3.10.10
  - firebase-admin: 5.13.1
  - firebase-functions: 2.0.2
  - `@google-cloud/storage` version: 1.7.0
  - Typescript: 2.8.3

#### Steps to reproduce
  1. attempt to upload an image with the following structure:
```
import * as admin from "firebase-admin";

const autoFile = await admin
        .storage()
        .bucket()
        .upload("tempFilePath", {
          destination: "orientedFilePath",
          metadata: { contentType: "image/jpeg" }
        });
```
When doing this - i get the following "error" in the console:

```
error: { ApiError: Error during request.
    at Object.parseHttpRespBody (/Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/@google-cloud/common/src/util.js:187:32)
    at Object.handleResp (/Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/@google-cloud/common/src/util.js:131:18)
    at /Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/@google-cloud/common/src/util.js:496:12
    at Request.onResponse [as _callback] (/Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/retry-request/index.js:195:7)
    at Request.self.callback (/Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/user/Documents/Developer/project-project-2018/firebase/functions/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: undefined,
  errors: undefined,
  response: undefined,
  message: 'Error during request.' }
```
I find it rather hard to provide more information than this, now that the error is so vague.

I should mention that before we try to upload an image, we download the image first from storage, which works fine.

I will of course provide more information if you need anything else. This was the initial information i could think of.

Kind regards Chris

**Comment by hiranya911** [comment]
Following worked fine for me (notice the contentType value):

```
const bucket: Bucket = admin.storage().bucket();
return bucket.upload("/usr/local/google/home/hkj/Downloads/android.png", {
      destination: 'testme.png',
      metadata: { contentType: "image/png" },
    }).then((res) => {
      console.log('success', res);
    }).catch((err) => {
      console.log('error', err);
    });
```

If I set contentType to just `image` this would timeout -- not sure why. Can you give the above a try? If that works I think we should move this to https://github.com/googleapis/nodejs-storage for follow up.

**Comment by chriseenberg** [comment]
@hiranya911  I'm sorry, that was a typo on my part, i already have contentType: 'image/jpeg' in that field.

**Comment by chriseenberg** [comment]
@hiranya911 This error does occur even though i remove the `metadata: { contentType: "image/jpeg" } `

It does not time out.

**Comment by paulsUsername** [comment]
@chriseenberg How did you resolve this? I am experiencing the same issue. This matter what metadata I attach, it isn't visible through firebase. If I go into the Google Cloud console, I can see the image fine but in Firebase it won't appear.
