### ISSUE TITLE
FR: Add sample code that will showcase this new API features

### ISSUE THREAD

**Issue by gigocabrera** [firebase/firebase-admin-node#33]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: Firebase Admin Node.js SDK (v5.0.0)
  * Library version: 5.0
  * Firebase Product: Admin (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
I want to use the the Firebase Admin Node.js SDK (v5.0.0) to manage users of my app (add/delete users), but I'm not able to find sample code that would allow me to learn how to implement this API for my needs.

**Comment by hiranya911** [comment]
What about https://firebase.google.com/docs/auth/admin/manage-users#create_a_user and https://firebase.google.com/docs/auth/admin/manage-users#delete_a_user ?

If they don't serve your purpose, please elaborate and we can look into updating our docs accordingly.

**Comment by gigocabrera** [comment]
I have an ionic+angular app with a firebase backend that is available in the App Store (apple). As I mentioned before I want to use the Firebase Admin Node.js SDK (v5.0.0) to manage users. 

Can I create an angular app and incorporate the firebase admin SDK so I can manage users? If so, do you have a sample?

**Comment by mbleigh** [comment]
The Admin SDK is meant to run high trust operations, almost always on a
server or in a secure environment. In general you would not want to use it
for something like an Ionic app.

**Comment by gigocabrera** [comment]
@mbleigh I'm not trying to use it for an app. I'm trying to build a simple custom console that will run on my local PC so I can manage users of my existing app. My problem is that I'm fairly new to all these technologies that I need a sample app that I can look at and learn so then I can customize it for my needs

**Comment by jshcrowthe** [comment]
@gigocabrera the Node Admin SDK takes dependencies on packages that preclude the possibility of using it in a client environment (i.e. the Node `fs` package). You will need to use the [Firebase JS SDK](https://npm.im/firebase) to have a functioning firebase implementation for your app.

As a workaround for the elevated privilege issue, you could, through rules, give your user (and only your user) read/write access to the whole database. But that could introduce its own set of issues.

**Comment by gigocabrera** [comment]
@jshcrowthe thanks. 

Maybe someone can point me to a blog post / article from somebody who has implemented the Firebase Admin Node.js SDK successfully. 

It would make things easier for developers like me coming from other technologies, to learn by example.

**Comment by gigocabrera** [comment]
This is exactly what I want to accomplish but I don't know where to start:

-- from https://firebase.google.com/docs/admin/setup -- 
Create your own simplified admin console to do things like look up Authentication user data or change an Authentication user's email address

**Comment by hiranya911** [comment]
[Quickstart samples](https://github.com/firebase/quickstart-nodejs) are usually a good place to start. You can also reach out to [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk) google group where this kind of questions get more visibility.

**Comment by hiranya911** [comment]
I'm going to close this ticket. Please use our firebase-talk google group for any questions about the API and/or usage help.

**Comment by gigocabrera** [comment]
From the links below I was able to learn how to use this new API and much much more. 

https://www.youtube.com/watch?v=LOeioOKUKI8&t=813s
https://blog.realworldfullstack.io/real-world-app-part-12-cloud-functions-for-firebase-8359787e26f3
https://github.com/firebase/functions-samples/tree/master/authorized-https-endpoint

I hope this helps any other developer like me coming from a different technology stack.

**Comment by djom20** [comment]
Hi, I have a similar case, I don't can find any docs about the login with an user in the firebase admin, someone know how to make it?

**Comment by hiranya911** [comment]
Admin SDK does not support user logins, and it should not be used for end user operations due to security reasons.
