### ISSUE TITLE
Run a Transaction on a root node or on a direct child of it

### ISSUE THREAD

**Issue by MrIceman** [firebase/firebase-admin-node#335]
Hi, I am not sure whether following problem is a design decision or an issue.

Let's assume we have this DB Structure:
{
 users: {... /* a node with many users here, having their id as index */ ...},
 messages: {... /* same as users */ ... 
}

whenever I call a transaction on a root-node reference and try to access the child "users", I receive a a node with 0 children. However, I'd like to have access to all children from users.

`DatabaseReference transactionReference = FirebaseDatabase.getInstance().getReference().getRoot().runTransaction(new  Transaction.Handler() {

 @Override
            public Transaction.Result doTransaction(MutableData currentData) {
                MutableData mutableUsersNode = currentData.child("users"); 
                //mutableUsersNode.getChildrenCount() would return 0 when in fact it is more
}
});
`

I can , however, access the children of any Mutable node when it is not one of the root leafs (here users and messages).
Am I doing something wrong here?

What's the best solution to run an atomic transaction on a top-level value?

best regards

**Comment by hiranya911** [comment]
This looks like Java. Please report at https://github.com/firebase/firebase-admin-java
