### ISSUE TITLE
Firestore arrayUnion() silently drops server timestamp values

### ISSUE THREAD

**Issue by jwngr** [firebase/firebase-admin-node#336]
### Environment

  * Operating System version: All
  * Firebase SDK version: 6.0.0
  * Firebase Product: Firestore

### Problem

Thanks for adding the new `admin.firestore.FieldValue.arrayUnion()` and `admin.firestore.FieldValue.arrayRemove()` features. They're super handy! I think I found a bug in it though. When you try to add an item which contains `admin.firestore.FieldValue.serverTimestamp()` via `admin.firestore.FieldValue.arrayUnion()`, the timestamp is never set and the corresponding field is dropped.

#### Steps to reproduce:

1. Run the repro below.

**Expected result:** 

The database should look like this:

<img width="758" alt="screen shot 2018-08-12 at 10 34 29 pm" src="https://user-images.githubusercontent.com/4149793/44010472-aea0811c-9e80-11e8-88b1-23c4080c8a02.png">

**Actual result:**

The database ends up looking like this:

<img width="501" alt="screen shot 2018-08-12 at 10 33 52 pm" src="https://user-images.githubusercontent.com/4149793/44010481-b6d1940c-9e80-11e8-93e2-8f18e3edde40.png">

If you switch the non-working `admin.firestore.FieldValue.serverTimestamp()` with `new Date()`, the expected result occurs. 

#### Relevant Code:

```
return admin.firestore().doc('items/2').set({
  someArray: admin.firestore.FieldValue.arrayUnion({
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    foo: 'bar',
  }),
})
  .then(() => console.log('Success!'))
  .catch((error) => console.log('Error:', error));
```

Note that this also fails, resulting an an empty `someArray` array:

```
return admin.firestore().doc('items/2').set({
  someArray: admin.firestore.FieldValue.arrayUnion(
    admin.firestore.FieldValue.serverTimestamp()
  ),
})
  .then(() => console.log('Success!'))
  .catch((error) => console.log('Error:', error));
```

**Comment by jwngr** [comment]
Poor effort, @firebase-oss-bot.

**Comment by schmidt-sebastian** [comment]
Hey "jwngr", thanks for filing this issue. Note that we currently don't support Server Timestamps inside of Array values. It looks like we are missing some client-side validation here. We will add it shortly.
