### ISSUE TITLE
6.0.0 w/ firestore dies "Cannot find module 'protobufjs/minimal'" even after npm i @google-cloud/firestore

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-admin-node#338]
I've upgraded firebase-admin to 6.0.0 and it compiles OK, but after I run code (firestore) I get exception `Failed to import the Cloud Firestore client library for Node.js. Make sure to install the "@google-cloud/firestore" npm package.`

Well, I then do as told and installed that package, but the error message still persists.

The full error message is here:

```console
{ Error: Failed to import the Cloud Firestore client library for Node.js. Make sure to install the "@google-cloud/firestore" npm package. Original error: Error: Cannot find module 'protobufjs/minimal'
    at FirebaseFirestoreError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseFirestoreError (/srv/node_modules/firebase-admin/lib/utils/error.js:207:23)
    at initFirestore (/srv/node_modules/firebase-admin/lib/firestore/firestore.js:119:15)
    at new FirestoreService (/srv/node_modules/firebase-admin/lib/firestore/firestore.js:43:32)
    at /srv/node_modules/firebase-admin/lib/firebase-app.js:261:20
    at FirebaseApp.ensureService_ (/srv/node_modules/firebase-admin/lib/firebase-app.js:327:23)
    at FirebaseApp.firestore (/srv/node_modules/firebase-admin/lib/firebase-app.js:259:28)
  errorInfo: 
   { code: 'firestore/missing-dependencies',
     message: 'Failed to import the Cloud Firestore client library for Node.js. Make sure to install the "@google-cloud/firestore" npm package. Original error: Error: Cannot find module \'protobufjs/minimal\'' } }
```

It still says: `Cannot find module 'protobufjs/minimal'`

Looking at the `package.json` of `@google-cloud/firestore` here https://github.com/googleapis/nodejs-firestore/blob/master/package.json, it seems clear that protobufjs is a _dev_ dependency of that lib.

Should I `npm i protobufjs` or should I peek deeper?

**Comment by swftvsn** [comment]
Hmm, it seems that the version of protobufjs installed is quite old, 5.0.3, observed from the node_modules folder.

It seems that google-gax actually has two different versions of protobufjs in it's dependency tree, namely 5.0.3 and 6.8.8.

```console
├─┬ @google-cloud/firestore@0.16.0
│ ├─┬ google-gax@0.17.1
│ │ ├─┬ grpc@1.13.1
│ │ │ └─┬ protobufjs@5.0.3
│ │ ├─┬ protobufjs@6.8.8
```

My npm version is `6.3.0`, don't know why it selects the older dep? This bug may very well belong to `@google-cloud/firestore` or `npm` repo itself. Any pointers are welcome at this point.

**Comment by swftvsn** [comment]
OK, I can confirm, that running `npm i protobufjs` fixed the problem for me, so the culprit is that for some reason npm selects the older version of protobufjs. Including it to the project makes npm select the correct version and everything works ok.

The interesting bit is that protobufjs is present in the dependency tree ONLY as a child dep of `@google-cloud/firestore`.

**Comment by schmidt-sebastian** [comment]
Hi! Thanks for reporting this. Looks like this dependency snug in when we regenerated our Protobuf files. We will make this an explicit dependency of our own.

**Comment by swftvsn** [comment]
Thank you for the quick response time @schmidt-sebastian !
