### ISSUE TITLE
auth.UserRecord is missing 'phoneNumber' field

### ISSUE THREAD

**Issue by rjhuijsman** [firebase/firebase-admin-node#34]
* Operating System version: N/A
  * Firebase SDK version: N/A
  * Library version: 5.0.0
  * Firebase Product: Auth

The Cloud Functions for Firebase SDK uses the Firebase Admin SDK as its source for a TypeScript definition of an `auth.UserRecord`. The `auth.UserRecord` currently contains the following fields:
```
public readonly uid: string;
public readonly email: string;
public readonly emailVerified: boolean;
public readonly displayName: string;
public readonly photoURL: string;
public readonly disabled: boolean;
public readonly metadata: UserMetadata;
public readonly providerData: UserInfo[];
```
However, when a Cloud Function is invoked for an Auth user creation that uses phone authentication, the UserRecord sent as a JSON object also contains a `phoneNumber` field:
```
{
  "metadata": {
    "createdAt": "2017-06-01T23:01:23.000Z",
    "lastSignedInAt": "2017-06-01T23:01:23.000Z"
  },
  "phoneNumber": "+1555123456",
  "providerData": [
    {
      "providerId": "phone",
      "uid": "+1555123456"
    }
  ],
  "uid": "C6simWCCNlO3Mdyq9PYyY1O8qPJ3"
}
```
This new `phoneNumber` is currently hard to access for TypeScript users, since it's not yet present in the `auth.UserRecord`.

We should add the `phoneNumber` field to the Node.js Admin SDK.

**Comment by hiranya911** [comment]
This was released today: https://firebase.google.com/support/release-notes/admin/node#5.1.0
