### ISSUE TITLE
Cannot bundle packages using firebase-admin (regression in 6.0.0 from 5.13.1)

### ISSUE THREAD

**Issue by vieira** [firebase/firebase-admin-node#341]
* Operating System version: macOS 10.13.6
  * Firebase SDK version: 6.0.0
  * Library version: 6.0.0
  * Firebase Product: realtime database

Since upgrading firebase-admin to 6.0.0 (from 5.13.1) webpack (with target nodejs) fails to build a bundle when containing `import firebase from 'firebase-admin'`. This is a regression from 5.13.1 where the same code bundled just fine.

```
ERROR in /builds/guuru/platform/node_modules/@google-cloud/firestore/build/protos/firestore_proto_api.js
Module not found: Error: Can't resolve 'protobufjs/minimal' in '/builds/guuru/platform/node_modules/@google-cloud/firestore/build/protos'
 @ /builds/guuru/platform/node_modules/@google-cloud/firestore/build/protos/firestore_proto_api.js 4:16-45
 @ /builds/guuru/platform/node_modules/@google-cloud/firestore/build/src/field-value.js
 @ /builds/guuru/platform/node_modules/@google-cloud/firestore/build/src/index.js
 @ /builds/guuru/platform/node_modules/firebase-admin/lib/firebase-namespace.js
 @ /builds/guuru/platform/node_modules/firebase-admin/lib/default-namespace.js
 @ /builds/guuru/platform/node_modules/firebase-admin/lib/index.js
 @ /builds/guuru/platform/packages/firebase-srv/src/admin.js
 @ /builds/guuru/platform/packages/firebase-srv/index.js
 @ ./index.js
error An unexpected error occurred: "Command failed.
```

Using the following webpack configuration:

```
module.exports = {
  entry: './index.js',
  target: 'node',
  node: false,
  resolve: {
    mainFields: ['main', 'module'],
  },
  optimization: {
    minimize: false,
  },
  module: {
    rules: [{
      test: /\.m?js$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
      },
    }],
  },
  stats: {
    warnings: false,
  },
};
```

**Comment by hiranya911** [comment]
Probably a dupe of #338. @schmidt-sebastian any thoughts?

**Comment by schmidt-sebastian** [comment]
Do you either re-installing your dependencies or explicitly installing @google-cloud/firestore@0.16.1? We added protobufjs as an explicit dependency, which should resolve your issue.

**Comment by vieira** [comment]
@schmidt-sebastian Thank you, reinstalling after manually deleting node_modules worked.

**Comment by odedniv** [comment]
For anyone coming here looking for a way to use GCP services from Google Cloud Functions and hitting a snag with webpack - you don't need webpack in GCF since you don't upload the artifact with the dependencies, you upload `package.json` and GCF will download the dependencies itself.
