### ISSUE TITLE
FR: Firestore export/import capapability

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-admin-node#342]
* Firebase Product: firestore

Hi :)

would be super cool to have the export and import functionality available in the admin SDKs to not have to use the REST API solely for this functionality
https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases?authuser=0

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over! We will put this on our list of potential features for one of our upcoming releases. We will update this issue as we go along, but please be very patient with us.

**Comment by wilhuff** [comment]
We've shipped this as part of `@google-cloud/firestore` [1.2.0](https://github.com/googleapis/nodejs-firestore/releases/tag/v1.2.0).

The next `firebase-admin-node` release will pick this up.
