### ISSUE TITLE
FCM not sending notification to iOS/Android notification center when app is closed

### ISSUE THREAD

**Issue by EliSadaka** [firebase/firebase-admin-node#343]
* Operating System version: Windows 10
  * Firebase SDK version: 6.0.0
  * Firebase Product: Cloud Messaging

### [REQUIRED] Step 3: Describe the problem
When sending a notification using `messaging().send()` with the `notification` parameter set and the client iOS/Android app is in the background or closed, I expect the notification to be sent to the device's notification center/drawer instead of being handled by the app. This seems to be how it works when using the legacy method `sendToDevice()`. When trying to do the same with the new API though, while the notification is retrieved when the app is in the foreground, when the app is in the background or closed the notification does not get handled at all. It doesn't get caught by the app and it isn't sent to the device's notification center/drawer.

The difference I've noticed is that the newer `send()` method sends a `RemoteMessage` object no matter what I set the message payload to, whereas `sendToDevice()` sends a `Notification` object when the `notification` field is set in the payload. Perhaps this is why the notifications aren't being sent to the device's notification center? I can't use the legacy API though because it's missing features that I need.

How do I get the behaviour that I want with the newer API? Am I doing something wrong with how I'm creating the messages?

#### Relevant Code:
The following code does not send a notification to the client device's notification center when the app is in the background or closed:
```
const message = {
      notification: {
        title: "Title,
        body: "Body",
      },
      token: [token],
};

admin.messaging().send(message)
.then((response) => {
        console.log('Successfully sent message:', response);
}).catch((error) => {
        console.log('Error sending message:', error);
});
```
However, this does:
```
const message = {
      notification: {
        title: "Title,
        body: "Body",
      }
};

admin.messaging().sendToDevice([token], message)
.then((response) => {
        console.log('Successfully sent message:', response);
}).catch((error) => {
        console.log('Error sending message:', error);
});
```

**Comment by askilondz** [comment]
It seems like projects that were setup before the new FCM API, thus using the legacy API, needs to enable the new API manually:
https://console.developers.google.com/apis/library/fcm.googleapis.com

I didn't find this step in the docs but it seems new firebase projects that are created with messaging now will have this enabled by default. I could be wrong on that but my staging firebase project has this API enabled which I created well after my production project which didn't have it enabled.

**Comment by EliSadaka** [comment]
In the case of our project, we started after the new API was introduced and so it was already enabled, and yet we were still experiencing this issue.

**Comment by askilondz** [comment]
Looking at your code you were passing an array to the token field `token: [token]` but the new v1 api doesn't currently supporting sending to multiple device tokens with a single call like you could in the legacy `sendToDevice` call. Right now the `token` field only accepts a single string but apparently the multi-token support is on the backburner for the new api:
https://stackoverflow.com/questions/50505274/why-use-a-legacy-api-for-a-firebase-fcm-notifications-sample

**Comment by EliSadaka** [comment]
I was passing a string to the `token` field, it's just that I replaced the string with `[token]` in the example above so that I wouldn't expose the actual token. I could have made that more clear though.

**Comment by Aibier** [comment]
Hi Guys, i can able to send a notification to ios but android failed with configuration 

`
const payload = {
         notification: {
                title: 'THis is my testing from API',
                body: 'This is my body'
         }
}
const deviceToken= ['iosDeviceToken','addroidDeviceToekn']
admin.messaging().sendToDevice(deviceToken, payload)
            .then((_response) => {
                Console.log(_response);
                Console.log(`notification fired at ${new Date()}`);
            })
            .catch((error) => {
                Console.log(`Error sending message: ${error.message} at ${new Date()}`);
            });`

or i just send notification to ios, it works; but send to android does not work. I tried to send testing notification from Firebase console to android it works fine. 

could anyone help me figureout whats issue on this?

**Comment by chong-shao** [comment]
Hi EliSadaka, could you file a support bug via https://firebase.google.com/support/ ? From there we can continue to investigate this issue. Thanks!
