### ISSUE TITLE
Duplicate Notification Received upon FCM Error

### ISSUE THREAD

**Issue by mortillan** [firebase/firebase-admin-node#346]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: N/A (we are using Firebase Functions)
  * Firebase SDK version: 
  * Library version: firebase-admin 6.0.0
  * Firebase Product: Messaging

### [REQUIRED] Step 3: Describe the problem

Received duplicate notification upon error from firebase-admin messaging.

> { Error: The service is currently unavailable.
    at FirebaseMessagingError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseMessagingError (/srv/node_modules/firebase-admin/lib/utils/error.js:241:16)
    at Function.FirebaseMessagingError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:271:16)
    at FirebaseMessagingRequestHandler.handleHttpError (/srv/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:125:50)
    at /srv/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:113:23
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  errorInfo: 
   { code: 'messaging/server-unavailable',
     message: 'The service is currently unavailable.' },
  codePrefix: 'messaging' }

#### Steps to reproduce:

This is the first time it has happened. We just sent a notification after a Firestore trigger is executed (onCreate). And we encountered that error. It does not happen always. Since it is intermittent, I cannot provide a way to reproduce it.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

We just sent the notification using this piece of code

` return admin.messaging().send(message)
    .then((response) => {
      return console.log('Response: ', response);
    })
    .catch((err) => {
      console.error(err);
    });
`

No retry at all. So if the server respond w/  'Error: The service is currently unavailable.' I expect 

1. Firebase Messaging does not send it at all
2. Firebase Messaging handles the retrying and no duplicate notification should occur.

```
// TODO(you): code here to reproduce the problem
```

Thanks,
Kian

**Comment by hiranya911** [comment]
@kixortillan how often would you say this happen?

Tagging @sampson-chen to follow up.

**Comment by kixortillan** [comment]
@hiranya911 Actually this only happened twice on the same day with a time difference of less than 10 mins. It never happened again. Also, (I'm not so sure) I think the mobile phone received the notification, w/c is the opposite of what the error message stated. Because our QA team raised that they received a duplicate notification where in fact my logs state that an error has occurred while sending it.

That's all I can provide for now. Just want to give you a heads-up so maybe the Firebase team may revisit the implementation of this sometime.

Thanks!

**Comment by almassapargali** [comment]
Getting duplicate notifications occasionally too. We're sending notification on http request.

**Comment by erez-guesty** [comment]
the same issue.. duplicate notifications and errors
```Error: The service is currently unavailable.\n at FirebaseMessagingError.FirebaseError [as constructor]

**Comment by davidbooth** [comment]
Same happens to us occasionally.

**Comment by chong-shao** [comment]
Sorry for the slow response on this issue. Did this happen again recently? It would be helpful to know the exact time when this happened.

**Comment by tuledev** [comment]
I got duplicated notifications with sendAll(), frequently.

**Comment by tuledev** [comment]
Confirmed this issue comes from google services

**Comment by chong-shao** [comment]
Hi @tuledev can you file a support ticket in https://firebase.google.com/support ? From there we can start get for information from your requests etc.

**Comment by ngandhy** [comment]
fwiw - I'm getting this daily using the python library.
