### ISSUE TITLE
document usage of arrayUnion() & arrayRemove()

### ISSUE THREAD

**Issue by vincentlaucy** [firebase/firebase-admin-node#348]
* Firebase SDK version: v0.16.1

Are they currently supported as in https://github.com/googleapis/nodejs-firestore/pull/287 ? if so, please update the document at https://firebase.google.com/docs/firestore/manage-data/add-data

**Comment by samtstern** [comment]
Part one:
https://github.com/firebase/snippets-node/commit/5ad041a54a4dfa3695d36ea544d0bded456dcdbe

**Comment by samtstern** [comment]
Part two:
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1207

**Comment by hiranya911** [comment]
@schmidt-sebastian can this be closed now?

**Comment by schmidt-sebastian** [comment]
Yes!

**Comment by bilics** [comment]
It does not seem to be working when the field does not yet exist. 

Is this the intended behaviour ?

Thanks

**Comment by schmidt-sebastian** [comment]
These operators create the field if the field does not yet exist, or convert it to an array if it is of a different type. Does this not work for you?

**Comment by bilics** [comment]
Hi @schmidt-sebastian - sorry, my mistake - it does work.
