### ISSUE TITLE
can not install firebase-admin!

### ISSUE THREAD

**Issue by anlexN** [firebase/firebase-admin-node#35]
![default](https://cloud.githubusercontent.com/assets/8686739/26811176/bd4a762e-4aa2-11e7-8e5f-6bb1c4fd009e.PNG)
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: win10 pro
  * Firebase SDK version: latest
  * Library version: latest
  * Firebase Product: cloud messaging (auth, database, storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by anlexN** [comment]
node version 8.0.0, npm version 5.0.0
it is not about code !!!!!, it is about can't install firebase-admin, ok! can you think about install issue?

**Comment by jthegedus** [comment]
This is an npm5 issue. There are many regressions with npm5 atm. They're being tracked here https://github.com/npm/npm/issues/16991 . If you don't find that error in the list then you should create a new issue on npm.

**Comment by jshcrowthe** [comment]
@anlexN many of the issues in the original NPM 5.0.0 release have been fixed in the patch releases that followed the launch (currently at 5.0.4)

Please try upgrading your NPM (`npm install -g npm`) and try again. Feel free to re-open if this is still an issue.

**Comment by jthegedus** [comment]
A quick check reveals it does seem to resolve the problem. npm5.0.3 is what's packaged with node8.1.2 though (the current latest release). So users will still see the issue unless they manually upgrade npm. Hopefully Node release an update soon with the new npm5.0.4
