### ISSUE TITLE
UnhandledPromiseRejectionWarning when trying to deploy

### ISSUE THREAD

**Issue by FiringBlanks** [firebase/firebase-admin-node#351]
### Environment

  * Operating System version: Windows 10
  * Firebase SDK version: Not sure. `firebase -v` not working
  * Library version: Not sure
  * Firebase Product: Hosting

### The Problem

I'm trying to deploy my project to Firebase Hosting. It was working fine a week ago but it suddenly starting to give me this error today when I tried deploying again:

```
+  functions: Finished running predeploy script.
i  storage: checking storage.rules for compilation errors...
+  storage: rules file storage.rules compiled successfully
i  firestore: checking firestore.rules for compilation errors...
+  firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  storage: uploading rules storage.rules...
i  firestore: uploading rules firestore.rules...
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (48.56 KB) for uploading
+  functions: functions folder uploaded successfully
i  hosting: found 38 files in public directory
⠹  hosting: hashing files [37/38] (97%)(node:22660) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EPERM: operation not permitted, open 'C:\Program Files\Git\projects\hmn2\.firebase\hosting.0.cache'
(node:22660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧  hosting: adding files to version [38/38] (100%)
```

The weird thing is that I even tried my week-old code that was successfully deployed. Even that is getting this error now, so it must be an issue with my environment. But I haven't made any updates to my environment that I'm aware of.

**Comment by hiranya911** [comment]
You're in the wrong repo. This is for the Firebase Admin SDK (server-side Node.js library for Firebase). You probably need https://github.com/Firebase/firebase-tools
