### ISSUE TITLE
DataSnapshot not exposed on firebase.database

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebase-admin-node#360]
* Operating System version: any
  * Firebase SDK version: 6.0.0
  * Firebase Product: database

### Describe the problem

`DataSnapshot` is not exposed on `firebase.database`.  From the documentation I would expect to find it at `firebase.database.DataSnapshot`.  I would like to access this for comparison purposes, eg. determining if a thing is a snapshot.

#### Steps to reproduce:

I have made a runnable example on glitch.me:

- See the code: https://glitch.com/edit/#!/hungry-roarer
- Observe the results: https://hungry-roarer.glitch.me

#### Relevant Code:

```js 
var firebase = require('firebase-admin');
console.log(firebase.database.DataSnapshot)
// => undefined 

console.log(Object.keys(firebase.database)) 
// => Reference, Query, Database, enableLogging, INTERNAL, 
//    ServerValue, TEST_ACCESS, initStandalone
```

**Comment by hiranya911** [comment]
Are you referring to the `DataSnapshot` type? If so it is exposed in our index.d.ts file. Consequently, following TypeScript compiles and runs fine:

```
it('once() returns the current value of the reference', () => {
      return ref.once('value')
        .then((snapshot: admin.database.DataSnapshot) => {
          const value = snapshot.val();
          expect(value.success).to.be.true;
          expect(typeof value.timestamp).to.equal('number');
        });
});
```

**Comment by hiranya911** [comment]
Please report this at https://github.com/firebase/firebase-js-sdk. What's exposed from `firebase.database` is actually determined by the `@firebase/database` package: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/index.node.ts#L65

If it's a typings issue, we could fix it in our source.
