### ISSUE TITLE
FIREBASE FATAL ERROR: Database initialized multiple times.

### ISSUE THREAD

**Issue by sarovin** [firebase/firebase-admin-node#362]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Docker node:8.11.1-alpine
  * Firebase version: 5.5.2
  * Firebase ADMIN: 5.13.1

#### Steps to reproduce:

Hi, I have a nextjs app (that use SSR).
I want use a cloud function as described here => https://github.com/firebase/functions-samples/tree/Node-8/nextjs-with-firebase-hosting

Now i want add express and connect-session-firebase ( connect-session-firebase require firebase-admin ) to my function as this:

```
const admin = require('firebase-admin');
const functions = require('firebase-functions');
const next = require('next');

const firebase = admin.initializeApp();
const FBDatabase = firebase.database();

const nextApp = next({ dev: false, conf: { distDir: 'next' } });
const handle = nextApp.getRequestHandler();

const server = express();
server.use(
  session({
    store: new FirebaseSession({
      database: FBDatabase,
    }),
    name: '__session', // With GCF only this name is permitted
    secret: '<SECRET>',
    secure: true,
    resave: false,
    rolling: true,
    httpOnly: true,
    cookie: {
      maxAge: 100000,
      domain: '<MY-URL>',
    }, // week
    saveUninitialized: false,
  }),
);

server.get('*', (req, res) => handle(req, res));

exports.next = functions.https.onRequest(async (req, res) => {
  await nextApp.prepare();
  return server(req, res);
});
```
But i have this error in my app because the nextjs app also uses firebase ( no firebase-admin ).

```
@firebase/database: FIREBASE FATAL ERROR: Database initialized multiple times. Please make sure the format of the database URL matches with each database() call.
```

This error appear with firebase-admin@5.13.1. I don't have problem with version 5.12.1

**Comment by hiranya911** [comment]
I haven't tested with `connect-session-firebase`, but without it the SDK/RTDB API works well in the Functions environment. I'd recommend reporting this at https://github.com/benweier/connect-session-firebase and get their input on the matter.

**Comment by daveteu** [comment]
> ### [REQUIRED] Step 2: Describe your environment
> * Operating System version: Docker node:8.11.1-alpine
> * Firebase version: 5.5.2
> * Firebase ADMIN: 5.13.1
> 
> #### Steps to reproduce:
> Hi, I have a nextjs app (that use SSR).
> I want use a cloud function as described here => https://github.com/firebase/functions-samples/tree/Node-8/nextjs-with-firebase-hosting
> 
> Now i want add express and connect-session-firebase ( connect-session-firebase require firebase-admin ) to my function as this:
> 
> ```
> const admin = require('firebase-admin');
> const functions = require('firebase-functions');
> const next = require('next');
> 
> const firebase = admin.initializeApp();
> const FBDatabase = firebase.database();
> 
> const nextApp = next({ dev: false, conf: { distDir: 'next' } });
> const handle = nextApp.getRequestHandler();
> 
> const server = express();
> server.use(
>   session({
>     store: new FirebaseSession({
>       database: FBDatabase,
>     }),
>     name: '__session', // With GCF only this name is permitted
>     secret: '<SECRET>',
>     secure: true,
>     resave: false,
>     rolling: true,
>     httpOnly: true,
>     cookie: {
>       maxAge: 100000,
>       domain: '<MY-URL>',
>     }, // week
>     saveUninitialized: false,
>   }),
> );
> 
> server.get('*', (req, res) => handle(req, res));
> 
> exports.next = functions.https.onRequest(async (req, res) => {
>   await nextApp.prepare();
>   return server(req, res);
> });
> ```
> 
> But i have this error in my app because the nextjs app also uses firebase ( no firebase-admin ).
> 
> ```
> @firebase/database: FIREBASE FATAL ERROR: Database initialized multiple times. Please make sure the format of the database URL matches with each database() call.
> ```
> 
> This error appear with firebase-admin@5.13.1. I don't have problem with version 5.12.1

**how did you solve your problem?**

**Comment by pierroo** [comment]
I know I might be one year late, but did you find a solution to this @daveteu or @sarovin ?
I'm very much stuck, unable to use both database from firebase-admin and from firebase. :/
