### ISSUE TITLE
Firestore `set()` with `{merge: true}` does not merge empty objects

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-admin-node#365]
* Operating System version: any
  * Firebase SDK version: 6.0.0
  * Library version: _____
  * Firebase Product: Firestore

#### Steps to reproduce:

Behaviour is exactly the same as described in https://github.com/firebase/firebase-js-sdk/issues/1168, tested using transactions.

To reproduce, set any document to `{ data: { "i-am": "important" } }` and run the code below in a transaction. `data` will be set to an empty object. Didn't test it with simple set.

#### Relevant Code:

```ts
transaction.set(documentReference, { data: {} }, { merge: true })
```

**Comment by wilhuff** [comment]
Sorry for the delay in resolving this, but upon review we believe this is working correctly, and consistently with the other SDKs.

See commentary here: https://github.com/firebase/firebase-js-sdk/issues/1371#issuecomment-445066500.
