### ISSUE TITLE
FR: find user by phone number

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-admin-node#37]
With the release of phone number authentication many apps will not have email address as a unique key.  It would be very useful to have a 'findUserByPhoneNumber()` call in the admin SDK to match the email one.

**Comment by bojeil-google** [comment]
Related to this: https://github.com/firebase/firebase-admin-node/issues/34

**Comment by jsayol** [comment]
I was looking into creating a PR for this but it seems like the `getAccountInfo` endpoint of the auth API doesn't yet allow to search users by `phoneNumber`, only `email` and `localId`.

Feel free to comment here if/when that's added and I'll push the PR :)

P.S.: the [documentation for the REST API](https://firebase.google.com/docs/reference/rest/auth/#section-get-account-info) should probably include the available request properties, in the same way [the old documentation did](https://developers.google.com/identity/toolkit/web/reference/relyingparty/getAccountInfo#request-body).

**Comment by bojeil-google** [comment]
Thank you for your help but I plan to implement this when the Auth backend supports it. It is not yet implemented. It is also part of a bigger change which features new API.

**Comment by sprmn** [comment]
Related to this issue and #34, it would also be useful if we could change a phone number via tha admin sdk. I guess this will also be part of the new API you were referring to? Is there anything we can do to help?

**Comment by bojeil-google** [comment]
Hang tight, it's all coming soon.

**Comment by hiranya911** [comment]
This was released today: https://firebase.google.com/support/release-notes/admin/node#5.1.0
