### ISSUE TITLE
stuck with Promise pending with listAllUsers();

### ISSUE THREAD

**Issue by Narkle** [firebase/firebase-admin-node#370]
### Environment
- Operating System version: any
- Firebase SDK version: 6.0.0
- Library version: _____
- Firebase Product: Authentication

### The Problem

I just copy and paste the code of https://firebase.google.com/docs/auth/admin/manage-users#list_all_users
in a test.js. I added every config part just before and it's working i retrieve all my user info accounts. The problem is  when i type `node test.js` the code is never ending after my last user info was returned.

I add  :
```
async function listAllUsers(nextPageToken) {
  // List batch of users, 1000 at a time.
  await firebaseAdmin.auth().listUsers(1000, nextPageToken)
...
  }
}

var test = listAllUsers();
console.log(test);
```
But it return 
`Promise { <pending> }`

I don't know why ?

**Comment by bojeil-google** [comment]
This looks like a question to stackoverflow. You need to provide a minimal, complete and verifiable example. You are just printing out the promise immediately. What are you seeing works as expected.

**Comment by stamler** [comment]
@Narkle In your `test.js` try `listAllUsers().then(process.exit(0))`. This will end the node process when the promise resolves.
