### ISSUE TITLE
firestore APIs fails with TypeError

### ISSUE THREAD

**Issue by sergeybekrin** [firebase/firebase-admin-node#372]
* Operating System version: **macOS 10.13.4** 
  * Node version: **v9.11.2**
  * Firebase SDK version: **6.0.0**
  * Firebase Product: **firestore**

#### Steps to reproduce:

Hey there 👋I've found that any firestore call fails with `TypeError: channel.createCall is not a function`. Full stack trace:
```
TypeError: channel.createCall is not a function
    at getCall (<PROJECT>/node_modules/grpc/src/client_interceptors.js:651:22)
    at <PROJECT>/node_modules/grpc/src/client_interceptors.js:1081:16
    at <PROJECT>/node_modules/grpc/src/client_interceptors.js:1381:14
    at _buildChain (<PROJECT>/node_modules/grpc/src/client_interceptors.js:1384:33)
    at Object.getInterceptingCall (<PROJECT>/node_modules/grpc/src/client_interceptors.js:1346:10)
    at ServiceClient.Client.makeBidiStreamRequest (<PROJECT>/node_modules/grpc/src/client.js:673:47)
    at apply (<PROJECT>/node_modules/lodash/lodash.js:478:17)
    at ServiceClient.wrapper (<PROJECT>/node_modules/lodash/lodash.js:5323:16)
    at <PROJECT>/node_modules/@google-cloud/firestore/build/src/v1beta1/firestore_client.js:150:41
    at <PROJECT>/node_modules/google-gax/build/src/streaming.js:186:28
```

Things I've tried:
* Other APIs including realtime database works fine
* Downgrading `firebase-admin` to `5.13.1` and `5.12.0` didn't help
* Standalone `@google-cloud/firestore` module has the same issue
* Downgrading `grpc` to `1.14.2` via [yarn's `resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) didn't help

#### Relevant Code:

```js
const firebase = require('firebase-admin');

firebase.initializeApp({
  credential: firebase.credential.cert('/path/to/key.json'),
  databaseURL: 'https://<PROJECT_DATABASE>.firebaseio.com/',
});

firebase.firestore().settings({
  timestampsInSnapshots: true,
});

firebase
  .firestore()
  .collection('whatever')
  .limit(1)
  .onSnapshot(snapshot => {
    snapshot.forEach(doc => {
      console.log(doc.id, '=>', doc.data());
    });
  });
```

**Comment by sergeybekrin** [comment]
Alright, so it might've been an issue with node_modules in my monorepo. Cleaning cache and doing hard re-install fixed it. Sorry for that 😅

**Comment by morgler** [comment]
Any solution to this? Cleaning cache did not help in my case :(. For me it happens during testing (https://firebase.google.com/docs/functions/unit-testing).

**Comment by ahmadawais** [comment]
Deleting and reinstalling the node_modules did it for me 🙌
