### ISSUE TITLE
error: (node:38507) [google-auth-library:DEP004] DeprecationWarning

### ISSUE THREAD

**Issue by mdrideout** [firebase/firebase-admin-node#376]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.13.6
  * Firebase SDK version: 
```
    "firebase": "^5.5.5",
    "firebase-admin": "^6.1.0",
    "firebase-functions": "^2.0.5"
```
  * Library version: _____
  * Firebase Product: admin auth

### [REQUIRED] Step 3: Describe the problem
Since upgrading to these versions, now receive error during firestore reads.
```
error: (node:38507) [google-auth-library:DEP004] DeprecationWarning: The `getRequestMetadata` method on the `OAuth2` class has been deprecated, and will be removed in the 3.0 release of google-auth-library. Please use the `getRequestHeaders` method instead.
```

#### Steps to reproduce:

Receive error when making the firestore call. The authentication and everything works fine. The function actually completes successfully. I get the above error in my logs.

```
// Verify the token
    admin.auth().verifyIdToken(token)
    .then((decodedToken) => {
        return db.collection('users').doc(decodedToken.uid).get();
    })
    .then(doc => {
        ...
```

**Comment by squirly** [comment]
Confirmed I am also getting this with the following versions:
```
"firebase-admin": "6.1.0",
"firebase-functions": "2.1.0",
```

**Comment by NawarA** [comment]
@squirly good find! Can you guys update the `firestore` package to 0.18.1, to include this fix?

**Comment by ovaris** [comment]
Yes please, this is driving me nuts:
![image](https://user-images.githubusercontent.com/2553533/48371953-cc940a80-e6c5-11e8-8a5d-e206c229f690.png)

**Comment by hiranya911** [comment]
You need @google-cloud/firestore 0.19.0 for the fix (which was released just yesterday). We will follow up with a release of firebase-admin soon.
