### ISSUE TITLE
Multiple WHERE clause means I cannot filter on the same field twice.

### ISSUE THREAD

**Issue by dackers86** [firebase/firebase-admin-node#381]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS High Sierra Version 10.13.6 
  * Firebase SDK version:  >= 6.0.0
  * Library version: >= 6.0.0
  * Firebase Product: Firestore database 
#### Steps to reproduce:

What happened? How can we make the problem occur?
I am trying to build a Firestore Query (https://firebase.google.com/docs/reference/js/firebase.firestore.Query#where). Through this I am unable to use multiple where clauses on the same field. This would be considered a logical OR, however the alternative is to build multiple queries.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
Firestore doesn't support OR queries: https://firebase.google.com/docs/firestore/query-data/queries#query_limitations

You have to build multiple queries, and find the intersection.
