### ISSUE TITLE
FR: Export admin.firestore.Transaction

### ISSUE THREAD

**Issue by menehune23** [firebase/firebase-admin-node#387]
### Describe your environment

  * Library version: 6.0.0
  * Firebase Product: firestore

### Describe the problem

Currently, within a cloud function written in TypeScript, I can reference a type like `admin.firestore.DocumentSnapshot`. It would also be useful to be able to do the same for `admin.firestore.Transaction`, as it seems to be missing from the exports of `admin.firestore`.

**Comment by hiranya911** [comment]
This has been implemented.

**Comment by menehune23** [comment]
Fantastic!
