### ISSUE TITLE
React-Webpack project: Module parse failed in json files when using firebase-admin

### ISSUE THREAD

**Issue by developerPratik** [firebase/firebase-admin-node#39]
My system specs:
  * Operating System version: Ubuntu 16.05 LTS 64-bit
  * Firebase SDK version: 3.6.10
  * Library version: firebase-admin:4.1.2
  * Firebase Product: firebase-admin

Step 3: Describe the problem

Whenever I try to use firebase-admin in my webpack-react project, it throws a bunch of errors, 
"Module parse failed: /path/to/file.json Unexpected token (2:6) 
You may need an appropriate loader to handle this file type."

As a result, a bunch other errors: "Module not found : Error: Cannot resolve 'file' or 'directory' occurs
#### Steps to reproduce:
I used npm to install firebase-admin, and defined it in my project js file. The error occurs when I run the project with "npm start"

#### Relevant Code:
 import * as admin from 'firebase-admin"

**Comment by jshcrowthe** [comment]
In a "client" application, you would want to use the [Firebase JS SDK](https:///npm.im/firebase ), not the admin SDK. The admin SDK is not designed to run in a non-server environment.

**Comment by kaueDM** [comment]
@jshcrowthe sorry for revive this issue, but i need to remove other users from my reactjs admin dashboard. How can i do it if  `firebase-admin` is server-only?

**Comment by hiranya911** [comment]
You should implement the user delete logic as a server-side script or a cloud function, and then get your react app to invoke that endpoint. Pass the ID token from the app to the server endpoint, where it can be validated using the admin SDK.
