### ISSUE TITLE
FR: UTF8 is not a function

### ISSUE THREAD

**Issue by gogolander** [firebase/firebase-admin-node#396]
Hi.

I think I'm posting this in the right place but I'm not sure so, if I'm not, sorry.
I'm trying to use the json credential to auth my nodej client to send a notification. But whenever I try to initialize the app I get the error:

> Error sending message: { [Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Failed to parse access token response: Error: Error while making request: utf-8 is not a function. Error code: undefined".]
>   errorInfo: 
>    { code: 'app/invalid-credential',
>      message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Failed to parse access token response: Error: Error while making request: utf-8 is not a function. Error code: undefined".' },
>   codePrefix: 'app' }

After a little digging, I found that the error seems related to those lines in `firebase-admin/lib/utils/api-request.js`:
`154: data = Buffer.from(JSON.stringify(config.data), 'utf-8');`
`160: data = Buffer.from(config.data, 'utf-8');`

Replacing `Buffer.from()` with `new Buffer()` seems to solve the issue but I'm wondering: could it have unintended consequences in production mode?

### My environment

  * Operating System version: Linux Ubuntu 16.04
  * NodeJS version: 4.2.6
  * NPM: 3.5.2
  * Firebase SDK version: 6.2.0
  * Library version: _____
  * Firebase Product: admin

**Comment by hiranya911** [comment]
What is your Node.js environment?

**Comment by gogolander** [comment]
NodeJS v6.2.0

**Comment by hiranya911** [comment]
We test on Node6 regularly, and haven't encountered any issues: https://travis-ci.org/firebase/firebase-admin-node. Also calls to `Buffer.from()` has been in our codebase for many months now, and no other user has reported similar issues. Please provide a complete and minimal repro so we can look into it.

**Comment by gogolander** [comment]
The script is basically copied from the Firebase Admin example:
`const admin = require("firebase-admin");
const serviceAccount = require("./firebase-auth.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://<mydb>.firebaseio.com"
});
console.log('inizializzato');

var registrationToken = 'edJv..._Yc0';

// See documentation on defining a message payload.
var message = {
  data: {
    score: '850',
    time: '2:45'
  },
  token: registrationToken
};

// Send a message to the device corresponding to the provided
// registration token.
admin.messaging().send(message)
  .then(function(response) {
    // Response is a message ID string.
    console.log('Successfully sent message:', response);
  })
  .catch(function(error) {
    console.log('Error sending message:', error);
  });`

The error is: 
`Error sending message: { [Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Failed to parse access token response: Error: Error while making request: utf-8 is not a function. Error code: undefined".]
  errorInfo: 
   { code: 'app/invalid-credential',
     message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Failed to parse access token response: Error: Error while making request: utf-8 is not a function. Error code: undefined".' },
  codePrefix: 'app' }`

**Comment by gogolander** [comment]
Sorry I messed up my PC nodejs and the my server nodejs versions: the correct version is

NodeJS v4.2.6
Firebase-admin: v6.2.0
NPM: v3.5.2

**Comment by hiranya911** [comment]
We dropped support for Node 4 in our 6.0.0 release: https://github.com/firebase/firebase-admin-node/releases/tag/v6.0.0

Please use a more recent Node.js distribution.
