### ISSUE TITLE
Firestore transaction async/await & promise.

### ISSUE THREAD

**Issue by Oskang09** [firebase/firebase-admin-node#401]
#### Environment
  * Operating System version: Linux ( Ubuntu 18.04 )
  * Firebase SDK version: firebase-admin 6.3.0
  * Firebase Product: firestore

#### Steps to reproduce:

As i know the async function will automatically return promise data rite? but when i make it become async/await has thrown this error to me `Error: You must return a Promise in your transaction()-callback.`. Is there my misunderstanding or wrong way i have done?

#### Relevant Code:

// Promise ( working as well )
```
async runQuery(firestore)
    {
        this.QueryResult = await firestore.runTransaction(transaction =>
        {
            return Promise.resolve(this.QueryAction(transaction, firestore));
        });
        return this;
    }
```
// Async/Await ( error occurs )
```
async runQuery(firestore)
    {
        this.QueryResult = await firestore.runTransaction(async transaction =>
        {
            // as i know function with async will auto become return Promise.resolve(returned data) rite?
            return this.QueryAction(transaction, firestore);
        });
        return this;
    }
```

// Example QueryAction
```
async (transaction, firestore) =>
        {
            if (key)
            {
                documentReference = firestore.collection(collection).doc(key);
            }
            else
            {
                documentReference = firestore.collection(collection).doc();
            }

            key = documentReference.id;
            await transaction.create(documentReference, value);

            return { key, value };
        }
```

**Comment by hiranya911** [comment]
Please use StackOverflow for usage questions.

**Comment by Oskang09** [comment]
I don't think this is usage question... log the message out it is promise but still throw error...

![screenshot from 2018-12-06 21-36-53](https://user-images.githubusercontent.com/15674107/49587614-55d5ee80-f99f-11e8-8523-2cd189ff1bf5.png)
