### ISSUE TITLE
listUsers result array is not automatically sorted by date, as specified in docs

### ISSUE THREAD

**Issue by SUVOLewis** [firebase/firebase-admin-node#404]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS High Sierra, V.10.13.6
  * Firebase SDK version: Firebase Tools for Node.JS 6.0.1
  * Firebase Product: Auth (Firebase Admin SDK)

### The Problem
According to the Firebase admin docs, listUsers() will return a list of users automatically sorted by the date they were created if no page token is specified: https://firebase.google.com/docs/auth/admin/manage-users#list_all_users

However, upon viewing my results, it appears that Firebase returns a list of users which have been sorted alphabetically by UID, rather than date:
![image](https://user-images.githubusercontent.com/42211658/49286632-aaa2d200-f492-11e8-9fcc-1601cce84934.png)

(Due to how the console shows logs on Firebase, the bottom result is the first result, and so on)

If I go onto the auth console and order by UID, I can see that the order is exactly the same, as shown here:
![image](https://user-images.githubusercontent.com/42211658/49287205-7fb97d80-f494-11e8-923e-982123e8319d.png)

#### Steps to reproduce:
Simply create a few user accounts on Firebase where the UID and creation date will sort the users differently. (eg. a UID beginning with 'a' and a creation date of 28/11/2018, a UID beginning with 'b' that has a creation date of 26/11/2018 and a UID beginning with 'c' that has a creation date of 27/11/2018.
Upon executing listUsers(), you will get a..., b...., c..., alphabetically ordered. According to the documentation, you should get back b, c, a.

#### Relevant Code:
Here's the snippet I'm currently using in my Node.JS cloud functions.
```
export function deleteTestUsers() {
    const p = new Promise((resolve, reject) => {
        admin.auth().listUsers(1000).then((response) => {
            response.users.forEach(user => {
                console.log('user', user.toJSON());
            });
            resolve();
        });
    })
    return p;
}
```

**Comment by bojeil-google** [comment]
That documentation is incorrect. We plan to fix it but haven't had the chance to get to it. Users are not sorted by date creation.

**Comment by SUVOLewis** [comment]
Thanks guys!

**Comment by filipesperandio** [comment]
Any way to order that list somewhere?

**Comment by pierroo** [comment]
A bit late to the party but: how can we retrieve those users sorted by creation date?

**Comment by alexisrodiz** [comment]
Any update about listing users sorted by creation date?
