### ISSUE TITLE
JavaScript heap out of memory when using on('child_add' for 60k+ rows

### ISSUE THREAD

**Issue by CurtisHumphrey** [firebase/firebase-admin-node#406]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS (latest)
  * Firebase SDK version: firebase-admin 5.12.1
  * Firebase Product: database

#### Steps to reproduce:

When I switch to not using a limit on this line
```
fire_db.ref(`/metrics_raw/${metric_name}`).on('child_added', invoke_sender)
```

I get the following error
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

It never calls the invoke_sender before it crashes

**Comment by CurtisHumphrey** [comment]
I'm going to do the work in 100 record chunks and will post the basic code setup one I have it working for anyone in the future who has this issue

**Comment by hiranya911** [comment]
RTDB code resides here: https://github.com/firebase/firebase-js-sdk. Please report there. I also believe this is just the existing RTDB behavior. All child nodes get downloaded and cached in memory.
