### ISSUE TITLE
Why is passwordHash and passwordSalt only available with listUsers()?

### ISSUE THREAD

**Issue by compojoom** [firebase/firebase-admin-node#408]
node 6
    "firebase-admin": "^5.11.0",
    "firebase-functions": "0.9.1",
  * Firebase Product: auth

I'm trying to migrate the users from Project A to Project B. The tricky part is that users can continue to register on Project A and I want to automatically copy their userobj to Project B.
I was hoping to use the auth.onCreate trigger in combination with auth.importUsers

I used auth().getUser to get a userRecord. Unfortunately for me in order to create a proper userRecord for the importUsers function I need a passwordHash and passwordSald property. The value returned from getUser however doesn't have a correct passwordHash and it has undefined for passwordSalt.

If I use the auth().listUsers() function then the returned object has completly different password hash and salt. Why aren't we able access the password salt & hash with auth.getUser()?

The docs here https://firebase.google.com/docs/reference/admin/node/admin.auth.UserRecord state that passwordHash and passwordSalt is only available with listUsers(), but why?

**Comment by hiranya911** [comment]
`listUsers()` API is designed to support the use case of migrating users across systems. `getUser()` is not designed for that. Over to @bojeil-google who can provide more context.

**Comment by ShashirajSingh** [comment]
The same thing is working fine on my colleague's system (getting password hash's value), then why it is giving passwordhash undefined on my system.whenever i am using 
 " Admin.auth().getUserByEmail(email) "

showing below error:-
![Screenshot_1](https://user-images.githubusercontent.com/51989252/73660417-282d2800-46be-11ea-8307-e8277b05a159.png)

![Screenshot_26](https://user-images.githubusercontent.com/51989252/73660418-282d2800-46be-11ea-81d3-88f4ba463e00.png)



Versions of node and firebase is also same on both the machines.

Please let me know if you have any solution for this issue.


Versions of node and firebase is also same on both the machines.

Please let 'sme know if you have any solution for this issue.

**Comment by simplogics** [comment]
@ShashirajSingh I guess you need to add permissions in gcloud IAM account for the service account used in firebase. Try setting the service account as project owner for testing

**Comment by ykorach** [comment]
Hi, I am facing the same issue, and I tried to add the service account of the admin SDK as project owner in the IAM console (screenshot below) but it didn't the password hash and salt is still undefined.
Does anyone have any suggestions?
 Thank's
![image](https://user-images.githubusercontent.com/15183075/87635882-71db6d80-c748-11ea-9f08-958eddd50320.png)

**Comment by AdamBCo** [comment]
Is there any update on this issue?

**Comment by dilizarov** [comment]
Ditto on updates for this issue. I was going to leverage the passwordHash for some one-time JWTs, but I don't think I can actually extract the passwordHash for just 1 user.

@hiranya911 @bojeil-google thoughts?

**Comment by dilizarov** [comment]
My workaround for this issue is that I store a random token in my database and change this random token whenever the password is changed (which I handle on my server).

It's pretty ugly, but until passwordHash is accessible via `getUser` or until `listUsers` lets you search by email address or uid or something, then it'll have to do.

**Comment by nraj-willow** [comment]
Very bad design decision from gcp firebase. We have many scenario where we need to get hash and salt of a user. Currently we have to loop through all n users via listUsers, Then get that one users salt and hash.

A reason to think before you decide on using firebase for authentication.

**Comment by rndlaine** [comment]
`listUsers()` requires to have the `firebaseauth.configs.getHashConfig` permission to return the `passwordSalt` and `passwordHash` properties.

As explained in the doc: https://firebase.google.com/docs/auth/admin/manage-users#password_hashes_of_listed_users

**Comment by mike-suggitt** [comment]
> Hi, I am facing the same issue, and I tried to add the service account of the admin SDK as project owner in the IAM console (screenshot below) but it didn't the password hash and salt is still undefined. Does anyone have any suggestions? Thank's ![image](https://user-images.githubusercontent.com/15183075/87635882-71db6d80-c748-11ea-9f08-958eddd50320.png)

Did you manage to solve this at all? I'm having the same issue

**Comment by dyohan9** [comment]
I have the same problem, did anyone manage to solve it?

**Comment by mjkweon17** [comment]
I am also facing the same problem. I hope there is a solution.

**Comment by mdrideout** [comment]
Also facing this problem, is there a solution in the works?

**Comment by erikslatter** [comment]
Same here. Trying to integrate Firebase Auth backend as a provider for auth.js, but I'm surprised to learn that I can't get the passwordHash and passwordSalt of a given user even if I have configured access for it in IAM. Fetching all users and narrowing it down seems overkill for my use case.

**Comment by CodeEventHorizon** [comment]
Having the same issue with listUsers(), it is very frustrating that passwordHash & passwordSalt aren't available in getUser(),
currently using multi-tenancy and we need to transfer a user from Tenant A to Tenant B
