### ISSUE TITLE
Firebase won't work on zeit's now

### ISSUE THREAD

**Issue by pariola** [firebase/firebase-admin-node#410]
I deployed a serverless function on Zeit's NOW and found out the `firebase-admin` package wasn't working there

`index.js`
```js
const admin = require("firebase-admin");
const serviceAccount = require("./secret/firebase_account.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();
const subsCollection = db.collection("subs");

module.exports = (req, res) => {
  subsCollection.doc("test").set({ name: "123" });
  res.writeHead(200, "hello");
  res.end("Hi");
};
```

the above code runs but nothing is saved on firestore!

**Comment by hiranya911** [comment]
`set()` method returns a Promise and you have to wait for it to resolve. As of now, your function exits before the Firestore write can have a chance to complete.
