### ISSUE TITLE
Requests don't support localAddress parameter

### ISSUE THREAD

**Issue by NicholasMendes** [firebase/firebase-admin-node#411]
Describe your environment

  * Operating System version: MacOS Mojave 10.14.2 beta (18C52a)
  * Library version: **All** (6.1.0)
  * Firebase Product: Messaging

Describe the problem

Firebase-admin-node doesn't support **localAddress** parameter on http request. This is useful if you have limited internet connection and want to route where the requests are sent through.

Relevant Code:

The following code can be aded to solve this issue.

file: **api-request.js**
line: **158**

```
var options = {
            hostname: parsed.hostname,
            port: parsed.port,
            path: parsed.path,
            method: config.method,
            headers: headers,
            localAddress: undefined,
        };
if (process.env.LOCAL_ADDRESS) {
            options.localAddress = process.env.LOCAL_ADDRESS;
}
```

**Comment by hiranya911** [comment]
Is this supported by any other GCP libraries? We are somewhat reluctant to support options that are not supported in the GCP ecosystem.

**Comment by hiranya911** [comment]
Closing this as won't fix for now. The exact use case and the value addition is unclear.
