### ISSUE TITLE
Allowed values for setDisplayName() in IosApp and AndroidApp

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-admin-node#414]
### Step 1: Are you in the right place?

  Yes :-)

### Step 2: Describe your environment

  * Operating System version: Linux 4.19.4
  * Firebase SDK version: n/a
  * Library version: 6.3.0
  * Firebase Product: project management

```
$ yarn list --pattern firebase
yarn list v1.12.3
├─ @firebase/app-types@0.3.2
├─ @firebase/app@0.3.5
├─ @firebase/database-types@0.3.2
├─ @firebase/database@0.3.7
├─ @firebase/logger@0.1.2
├─ @firebase/util@0.2.3
├─ firebase-admin@6.3.0
├─ firebase-tools@6.1.2
└─ firebase@2.4.2
```

(`firebase` is only installed because of `firebase-tools`)

### Step 3: Describe the problem

Using the new project management features (thanks!), when calling `setDisplayName()` on an `IosApp` or `AndroidApp` I can pass any string as the new name and it gets accepted. When doing that same operation through the console, only certain characters are accepted ("*Can only contain letters, numbers, spaces, and these characters: - !*").

The behavior should be consistent between the two. While the SDK should do this check, it should also be done on the backend side. Otherwise, using the REST API directly would still allow this.

#### Steps to reproduce:

1. Obtain an IosApp or AndroidApp through `admin.projectManagement()`
2. Call `setDisplayName()` on that app with an "invalid" name

#### Relevant Code:

```js
const apps = await admin.projectManagement().listAndroidApps();
apps[0].setDisplayName('Not$a@valid/name_');
```

**Comment by nbegley** [comment]
Thank you for the report! I've updated the validation in the public API to match the Firebase Console. This change will take effect within the next few days.
