### ISSUE TITLE
Infinite messaging function

### ISSUE THREAD

**Issue by ArthurKnoep** [firebase/firebase-admin-node#420]
* Operating System version: Linux Deepin 15.8 (based on Debian 8.0)
  * Firebase SDK version: 6.3.0
  * Library version: (I'm not sure to understand what's this)
  * Firebase Product: messaging
  * Node version: 10.9.0

#### Issue

When I run the simple code right below, my program never end. The program print the id of the message in firebase but after that my program stay in execution.

#### Steps to reproduce:

```js
const message = {
    notification: {
        title: 'Title',
        body: 'Body'
    },
    token: "<my personal token>"
};

firebase.messaging().send(message)
    .then(rsp => console.log(rsp))
    .catch(err => console.error(err));
```

**Comment by hiranya911** [comment]
`initializeApp()` starts workers that continue to run in the background. You need to call ensure clean up by calling the `delete()` method on `FirebaseApp` instance.
