### ISSUE TITLE
Why DataMessagePayload is a map of strings to string instead of map of string to any?

### ISSUE THREAD

**Issue by renannprado** [firebase/firebase-admin-node#424]
### Describe your environment

  * Operating System version: Linux
  * Library version: 6.0.0
  * Firebase Product: messaging

### Describe the problem

I'm trying to send a notification whose `data` will contain booleans, numbers, etc.
But the API (namely [`DataMessagePayload`](https://github.com/firebase/firebase-admin-node/blob/25098bfa11465bd55260527ab763ad024af75ad9/src/index.d.ts#L519)) right now defines a map of strings to string. I'm not sure if this error happens only because of the typescript definition and/or if this is intended at all.

#### Steps to reproduce:

Just try to run below code or something similar and you'll face the following error inside of your cloud function (in my case):

```
Error: Messaging payload contains an invalid value for the "data.isNewCustomer" property. Values must be strings.
    at FirebaseMessagingError.Error (native)
    at FirebaseMessagingError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseMessagingError (/user_code/node_modules/firebase-admin/lib/utils/error.js:241:16)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:782:27
    at Array.forEach (native)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:779:32
    at Array.forEach (native)
    at Messaging.validateMessagingPayload (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:772:21)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:500:37
```

#### Relevant Code:

```typescript
export const onNotificationCreated = functions.region(region).firestore
    .document(`${notificationsCollection}/{id}`).onCreate((snapshot, context) => {

    console.log(`got notification created event for notification event ${snapshot.id}`)
    console.log("data: ", snapshot.data())

    const token = "xxx"

    return admin.messaging().sendToDevice(
        token,
        {
            data: snapshot.data()["data"],
            notification: {
                title: "blablablabla"
            }
        }
    ).then((value) => {
        console.log("push notification sent with success", value)
    })
})
```

**Comment by hiranya911** [comment]
FCM API only accepts string values in the payload. You have to convert other types into strings.

From the documentation of the REST API: https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json

> Values in string types are recommended. You have to convert values in objects or other non-string data types (e.g., integers or booleans) to string.

**Comment by renannprado** [comment]
@hiranya911 recommended and required are two have different meanings. Doesn't it make sense to change the documentation?

**Comment by hiranya911** [comment]
I'll ping the documentation team, and get them to take a look. There's not a lot happening in the space of legacy FCM API right now. Most of our effort is going towards developing and documenting the v1 API. Typing requirements are more definitively defined there: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message
