### ISSUE TITLE
Firestore mismatch between the REST API and this SDK

### ISSUE THREAD

**Issue by bsiddiqui** [firebase/firebase-admin-node#427]
* Operating System version: macOS v10.14
  * Firebase SDK version: 6.4.0
  * Firebase Product: firestore

I have different results when querying using the node admin sdk than when using the API. 

I noticed this because I used the node sdk to remove this document, so technically the node sdk is returning the result I expect. The issue, however, is that the REST API and GUI in the console show that the document still exists. This makes me concerned that I could have many other documents that are mismatched.

FWIW, I tested the python sdk and got the same results as REST, and the GUI so there's something odd happening with the node sdk.

This query returns a document:
```
GET https://firestore.googleapis.com/v1beta1/projects/homevest-production/databases/(default)/documents/removed_properties/7232527961?key={YOUR_API_KEY}
```

This query does not return a document
```js
firestore.collection('removed_properties').doc('7232527961')
  .get()
  .then(doc => {
    console.log(doc.exists) // false
  })
  .then(() => process.exit(0))
```

**Comment by bsiddiqui** [comment]
I just tried inserting a document with the node sdk and that document is found when I query for it using the node sdk but it's not found when querying with REST or the python sdk... there seems to be a completely mismatch in actions taken with these sdks

**Comment by samtstern** [comment]
@bsiddiqui first of all, hi!  I recognize your name from HackNY mailing lists (I was 2012).

Just to confirm:
  * Python, REST, and the Firebase console say the document **does exist**
  * Node.js says the document **does not exist**
  * You deleted this document using the Node SDK.  I assume you did `firestore.collection('removed_properties').doc('7232527961').delete()` or something similar. 
  * You believe the _correct_ result is that the document is deleted, right?

**Comment by bsiddiqui** [comment]
@samtstern hi! This actually ended up being user error 😅

I recently migrated our account to an org and was using the wrong service cert with the node sdk. Whoops, sorry.

**Comment by samtstern** [comment]
Phew!  Because any other explanation would have been pretty scary.  Glad you solved it.
