### ISSUE TITLE
FR: [Messaging] Add option to retry sending or expose Retry-After header

### ISSUE THREAD

**Issue by jamesdam** [firebase/firebase-admin-node#43]
According to https://firebase.google.com/docs/cloud-messaging/admin/errors, clients should honor Retry-After header for `messaging/server-unavailable` and `messaging/internal-error`.

However, the MessagingDevicesResponse does not include a Retry-After header.

**Comment by hiranya911** [comment]
It is up to the server to decide whether to include that header in the response or not. If it is not present in the response, the client may retry immediately.

**Comment by jamesdam** [comment]
Thanks, @hiranya911 !

I don't know how I can check if the header exists. The formatted response does not mention it. https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingDevicesResponse.

**Comment by hiranya911** [comment]
I suppose we need to expose that header in the response somehow. Will look into it.

**Comment by sdomagala** [comment]
Hello @hiranya911,
Is there any update on it?
I can't find anything in the docs or in the code.

Cheers

**Comment by hiranya911** [comment]
@sdomagala there hasn't been much direct progress on this. However, we recently re-implemented how the SDK makes HTTP calls (see #280 and all the PRs referenced therein). This makes it easier for us to support this requirement.

**Comment by kixortillan** [comment]
@hiranya911 Hello Firebase Team.

Is this thread related to my newly created issue [here](https://github.com/firebase/firebase-admin-node/issues/346#issue-355826881)

Thanks!

**Comment by hiranya911** [comment]
Just sent #518 for review, which implements the retry framework for the SDK.

**Comment by hiranya911** [comment]
As of #556 the SDK automatically retries on 503 errors (up to 4 retries), and it also honors the Retry-After header when available. Otherwise it would use regular exponential backoff.

**Comment by treyshedrick** [comment]
For this would it also make sense on a 500 error as well?

**Comment by meor9zcu12** [comment]
Hi, May I know does the retry also apply to QUOTA_EXCEEDED?
I have lot of messages still failed due to QUOTA_EXCEEDED when using FCM admin SDK 9.2.0.

Note: I have already consulted Firebase Support about QUOTA_EXCEEDED issue, and they told me I need to handle retry-after header.
