### ISSUE TITLE
npm install --save firebase-admin always stuck. 

### ISSUE THREAD

**Issue by probelalkhan** [firebase/firebase-admin-node#430]
Trying from past 1 week. But nothing work so far. This is what happens when I run the command. 
![ssss](https://user-images.githubusercontent.com/9478845/50516245-c02a0c80-0acf-11e9-94b5-93a38f5d939c.PNG)

I tried, reinstalling firebase cli, nodejs and npm. I tried with different nodejs and npm versions. I tried clearing npm cache, setting to http but nothing worked so far. It is getting stuck always. 

My system configuration is
Windows 10, 64 bit 

I am using Node 10.15.0
and npm 6.4.1

Any help is appreciated.

**Comment by hiranya911** [comment]
Can you install other npm packages? Try something like `npm install --save @google-cloud/firestore`.

Try passing the `--verbose` flag and see what turns up.

**Comment by hiranya911** [comment]
We cannot look into this without more information. Please reopen with more details.
