### ISSUE TITLE
Firebase fails to fetch a valid Google OAuth2 access token on Windows

### ISSUE THREAD

**Issue by gabrielmoncea** [firebase/firebase-admin-node#436]
* Operating System version: Windows 10
  * Firebase SDK version: no SDK used
  * Library version: firebase-admin@6.4.0
  * Firebase Product: Realtime database

### [REQUIRED] Step 3: Describe the problem
I built a script to download data from the Realtime database, on Mac. Here things work fine. But when tested the script on Windows I get the following error:
```
@firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"Failed to parse access token response: Error: Server responded with status 400.\"."}
```

#### Steps to reproduce:
Build a script that access data from Realtime database, using `firebase-admin`. Run it on Windows.

#### Relevant Code:

```
var admin = require("firebase-admin");
var serviceAccount = require("./adminsdk.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://<project-id>.firebaseio.com"
});
var db = admin.database();
var dataRef = db.ref("ref");
```

**Comment by hiranya911** [comment]
Possible causes include:
1. Clock out of sync (most likely, since you're only seeing this on one environment)
2. Service account and the database URL are for 2 different projects

Please use Stackoverflow if you wish to follow up with further questions.

**Comment by gabrielmoncea** [comment]
@hiranya911 but you need the service account in order to access the database, correct?

**Comment by Andrewvanbeek** [comment]
@hiranya911 How did you fix the clock sync error?

**Comment by meet02** [comment]
@hiranya911  How did you solve clock sync error?

Can u provide solution for me

Thanks

**Comment by hiranya911** [comment]
Not sure how to fix it for Windows. On Linux you would usually use a service like ntp.

**Comment by gabrielmoncea** [comment]
@Andrewvanbeek @meet02 on Windows you just update the OS clock. Something like update current time. I am using dual boot, and every time I log in my Linux distro the windows clock gets desyncronised

**Comment by Wokoro** [comment]
On windows, I was able to fix the issue by navigating to **change date and time settings > Internet time > change settings > Update now ** with the **synchronize with the internet server checkbox** checked.

**Comment by EitanWeMatch** [comment]
i am experiencing the same issue but when i am running my Nodejs application in a docker container.

`@firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"Error fetching access token: Error while making request: getaddrinfo EAI_AGAIN accounts.google.com:443. Error code: EAI_AGAIN\"."}`

clocks is synced, is there anyone with the same issue as me ?

**Comment by GustavoHGS** [comment]
Still facing this issue... wish you guys had some guidance because I've already spent a few hours on this :/

**Comment by DiegoMGar** [comment]
I am having this issue too and im not having a clue of where to start to solve it.

**Comment by GustavoHGS** [comment]
For those who are facing this issue, I actually found out that this lib is just for node environments, that is, if you have an frontend app (like my case, a reactjs web app) it won't work. I figured I will probably have to use firebase functions get what I want done (which is deleting a user from firebase auth by UID).

If anyone has anything to add or confirm my thoughts I would really appreciate as well...

**Comment by DiegoMGar** [comment]
My problem was solved sending the data as a miltipart form instead of a json. Forcing us to not use json in node... Wtf.

**Comment by kennydifiore** [comment]
> My problem was solved sending the data as a miltipart form instead of a json. Forcing us to not use json in node... Wtf.

@DiegoMGar Can you elaborate on what you changed to a multipart form?  This issue just crept up and I wasn't having problems in the past.  Any data you can provide will be extremely helpful!

**Comment by arol** [comment]
Just for reference in case someone is looking for a solution:

One of my students was having this issue with Windows (WSL).
Indeed the error was a clock out of sync, but Windows clock was ok.
The problem was that the Linux clock (WSL) was out of sync.
You can verify if it's your case with the `date` command in your terminal.

If it's actually out of sync try this:

```bash
~$ sudo hwclock -s
``` 

Hope it helps 👍
