### ISSUE TITLE
Firestore onWrite trigger callback has undefined context

### ISSUE THREAD

**Issue by miickel** [firebase/firebase-admin-node#440]
firebase-tools:

    firebase --version
    > 6.2.2

package.json:

    "firebase-admin": "^6.5.0",
    "firebase-functions": "^2.1.0",

index.js:

    exports.handleWrite = functions
      .firestore
      .document('collection/{doc}')
      .onWrite((data, context) => {
        // context === undefined
      })

According to [the documentation][1], the callback should have `context`, just as the other triggers for Firestore.

What am I missing here?

  [1]: https://firebase.google.com/docs/reference/functions/functions.firestore.DocumentBuilder#onWrite

**Comment by bageren** [comment]
Did you find a solution? Facing the same problem.
