### ISSUE TITLE
Cant Import users with facebook/twitter provider

### ISSUE THREAD

**Issue by RobertoAyala2112** [firebase/firebase-admin-node#441]
Im running a code to import users into my Firebase proyect. The problem is that Facebook/Twitter imported users get an empty provider identificator in Firebase Console and then cant singIn because of "auth/account-exists-with-different-credential" error.
I dont get errors when I run my code. 
Also, I realised that If I change "facebook.com" by "google.com" it works fine.

My testing code:

```
var userImportOptions = {
    hash: {
        algorithm: 'HMAC_SHA256',
        key: Buffer.from('secretKey')
    }
};

admin
    .auth()
    .importUsers([{
        uid: 'asd123',
        firstName: 'Roberto',
        lastName: 'Ayala',
        email: '2112ayala@gmail.com',
        picture: 'https://graph.facebook.com/10214464120199982/picture?height=250',
        emailVerified: true,
        providerData: {
            displayName: 'Roberto Ayala',
            email: '2112ayala@gmail.com',
            photoURL: 'https://graph.facebook.com/10214464120199982/picture',
            providerId: 'facebook.com',
            uid: '10214464120199982'
        }
    }], userImportOptions)
    .then(function(userImportResult) {
        console.log(userImportResult.successCount);
    })
    .catch(function(error) {
        console.log(error);
    });
```

The imported user:

![screenshot 3](https://user-images.githubusercontent.com/43068281/51132899-46558b00-1812-11e9-8710-039ee9384d27.png)

Thank you for helping!

**Comment by hiranya911** [comment]
@RobertoAyala2112 `providerData` only accepts an array. See API docs: https://firebase.google.com/docs/reference/admin/node/admin.auth.UserImportRecord#providerData

Anything else gets ignored.

https://github.com/firebase/firebase-admin-node/blob/026748d6a10693c967fe8e410bcbb204f97850ba/src/auth/user-import-builder.ts#L182-L192

@bojeil-google should the SDK throw an error, when an object is passed?

**Comment by RobertoAyala2112** [comment]
Hello @hiranya911 and thanks for helping!

I tried passing an array but I get the same result

```
admin
    .auth()
    .createUser({
        uid: 'asd123',
        firstName: 'Roberto',
        lastName: 'Ayala',
        email: '2112ayala@gmail.com',
        picture: 'https://graph.facebook.com/10214464510199982/picture?height=250',
        emailVerified: true,
        providerData: [
            {
                displayName: 'Roberto Ayala',
                email: '2112ayala@gmail.com',
                photoURL: 'https://graph.facebook.com/10214464510199982/picture',
                providerId: 'facebook.com',
                uid: '10214464510199982'
            }
        ]
    })
    .then(function(userRecord) {
        console.log('Successfully created new user:', userRecord.uid);
    })
    .catch(function(error) {
        console.log('Error creating new user:', error);
    });
```

**Comment by RobertoAyala2112** [comment]
Update: Passing an array only works with admin.auth().importUsers method. The same user data using admin.auth().createUser doesnt works.

In my case It would be better if I could use admin.auth().createUser because of I get immediately the created user data

**Comment by hiranya911** [comment]
`createUser()` does not support specifying providers: https://firebase.google.com/docs/reference/admin/node/admin.auth.CreateRequest

I don't think the auth team is planning to support it.

**Comment by RobertoAyala2112** [comment]
Ok, thanks a lot @hiranya911. Have a nice day!

**Comment by bojeil-google** [comment]
I believe we ignore invalid keys: https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth-api-request.ts#L206

We are kinda stuck with it for this API as changing that to throw could break existing implementations. We would need a major version change.

**Comment by hiranya911** [comment]
@bojeil-google it doesn't look like there's anything actionable in this issue for us right now. Can we close it as WAI?

**Comment by bojeil-google** [comment]
Yeah, sounds good.
