### ISSUE TITLE
Removing/overriding hardcodes token validator URLs

### ISSUE THREAD

**Issue by TomasRup** [firebase/firebase-admin-node#447]
Hi, I’m unable to cover my app with integration tests without having to call actual firebase instance.

I would like to create a mock server/testkit that would imitate firebase, but I cannot go through the auth because here:

https://github.com/firebase/firebase-admin-node/blob/master/src/auth/token-verifier.ts

You have CLIENT_CERT_URL hardcoded.

Maybe we could write it like:
const CLIENT_CERT_URL = process.env.CLIENT_CERT_URL || 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com';

If you agree with this, I can create a MR.

**Comment by hiranya911** [comment]
We don't wish these parameters to be configurable. You can use a tool like nock to mock the outgoing requests. See how we do it in our own unit tests:

https://github.com/firebase/firebase-admin-node/blob/4e526abafa94033bae405005dd8ba416ff7261a4/test/unit/auth/token-verifier.spec.ts#L51-L59

Alternatively, you can also try stubbing the `HttpClient` class: https://github.com/firebase/firebase-admin-node/blob/master/src/utils/api-request.ts#L132

**Comment by TomasRup** [comment]
@hiranya911 this would only help me writing unit tests, but not integration.

If you don’t want to let env variables to be overriden, you could provide a testkit.

**Comment by TomasRup** [comment]
Hey, that would be e2e testing and pretty unstable as we would be testing not only our system but also firebase. Also that would require network connectivity.

What IT should be doing is starting up an actual application of mine, doing http calls to it and looking how does it work as a whole server.

Even if I wanted to test against actual firebase, that would reauire me to put serviceAccountKey.json in the repo so it runs on CI.

That’s why I want to test just my app as a http server (how does it integrate as a whole). Not as a bunch of js files (units).

**Comment by hiranya911** [comment]
We don't consider this URL (and several others like it) to be configurable. For things that are configurable, like the RTDB URL, we see the value of providing an emulator -- or a testkit as you call it. In fact, Firebase already provides an official RTDB emulator: https://firebase.google.com/docs/database/security/test-rules-emulator. There's ongoing work to provide more tools like that in the future.

As for non-configurable URLs, we currently treat them as internal implementation details of the SDK. We may change them, or the backend services that the SDK contacts may change their behavior. If you must run the type of integration tests you're suggesting, our recommendation would be to treat the entire `auth.verifyIdToken()` method as a blackbox, and put it behind an interface. Then you can use your own implementation of it during integration tests, and not test the Firebase SDK at all. Basically expect our implementation of `auth.verifyIdToken()` to behave correctly.

In the past we have reclassified some of our settings as configurable based on developer requests/demand. But this is the first time we have received any requests concerning this particular URL. If we see more demand for the same capability, we are happy to reconsider.

**Comment by TomasRup** [comment]
Thank you for explanations/suggestions!
