### ISSUE TITLE
Firestore "timestampsInSnapshots setting now defaults to true" error in Cloud Functions

### ISSUE THREAD

**Issue by mikemclin** [firebase/firebase-admin-node#449]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Mojave 10.14.2
  * Browser version: Chrome 71.0.3578.98
  * Firebase SDK version: 5.8.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem
An error message shows in the FIrebase Cloud Functions Logs when modifying a Firestore doc with a timestamp.

#### Steps to reproduce:
* In a Cloud Function, modify a Firestore doc with a timestamp property.
* See error:

```
@firebase/firestore: Firestore (5.8.0):
The timestampsInSnapshots setting now defaults to true and you no
longer need to explicitly set it. In a future release, the setting
will be removed entirely and so it is recommended that you remove it
from your firestore.settings() call now.
```

* Remove the explicit setting of `timestampsInSnapshots` from your codebase.
* In a Cloud Function, modify a Firestore doc with a timestamp property.
* See different error: 

```
The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

  const firestore = new Firestore();
  const settings = {/* your settings... */ timestampsInSnapshots: true};
  firestore.settings(settings);

With this change, timestamps stored in Cloud Firestore will be read back as
Firebase Timestamp objects instead of as system Date objects. So you will also
need to update code expecting a Date to instead expect a Timestamp. For example:

  // Old:
  const date = snapshot.get('created_at');
  // New:
  const timestamp = snapshot.get('created_at');
  const date = timestamp.toDate();

Please audit all existing usages of Date when you enable the new behavior. In a
future release, the behavior will change to the new behavior, so if you do not
follow these steps, YOUR APP MAY BREAK.
```

---

Originally posted here: https://github.com/firebase/firebase-js-sdk/issues/1498

**Comment by hiranya911** [comment]
This is what I would expect to see at this stage. `@firebase/firestore` (the JS SDK) has already stopped supporting timestampsInSnapshots option. But `firebase-admin` (the Admin SDK) still does. These 2 libs should not be mixed in general -- especially in a server-side environment such as Cloud Functions.

`firebase-admin` will also drop support for this setting in an upcoming release.

**Comment by mikemclin** [comment]
I was not using `@firebase/firestore`.  I always use firestore from `firebase-admin`.  However, I did have `firebase` included in my `package.json`, because I have a piece of code that needs to verify a password.  So even though nowhere in my Cloud Functions do I reference `firestore` from `firebase`, I only get it from `firestore-admin`, I still will get these errors?

**Comment by surajgupta57** [comment]
how should i fix this??
[2019-02-11T09:52:26.403Z]  @firebase/firestore: Firestore (5.8.1): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now

**Comment by mikemclin** [comment]
@surajgupta57, it is a pretty descriptive error.  Just do what it says.  Somewhere in your code you have `firestore.settings({ timestampsInSnapshots: true });`.  That needs to be removed.

**Comment by surajgupta57** [comment]
i hadn't written this things..

**Comment by paulo-campos** [comment]
Plese see this issue https://github.com/angular/angularfire2/issues/1993
comment of the SnisarOnline solved my problem

**Comment by MuhammadTahir7** [comment]
@firebase/firestore: Firestore (5.8.1): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.
facing this issue
can u resolve my issue i can provide u my code

**Comment by surajgupta57** [comment]
send me your code

**Comment by MuhammadTahir7** [comment]
https://github.com/MuhammadTahir7/AngularCrud 
here is the code @surajgupta57

**Comment by onexdata** [comment]
I'm getting this issue too, and I'm just using the default firebase demo settings 🤔 Anyone know what I need to do? I'm using Vue.

**Comment by smamun56** [comment]
firestore.settings({ timestampsInSnapshots: true }); use this to solve your prob

**Comment by jeremyfrancis** [comment]
In react native. Would commend out the line where the issue was and then another error showed up. Something at the core is wrong.
