### ISSUE TITLE
FR: createUser by specify providerID (facebook.com, google.com)

### ISSUE THREAD

**Issue by perjerz3434** [firebase/firebase-admin-node#45]
I am currently using passportjs with Node.js in firebase functions to create authentication.
The problem is I used Facebook authentication. However when I create account using the following command. It still creates account by email only. There is no provider if I check in console.
```
admin
        .auth()
        .createUser({
          email: profile.emails[0].value,
          emailVerified: false,
          displayName: profile.displayName,
          photoURL: profile.photos[0].value,
          disabled: false,
          providerData: [
            {
              displayName: profile.displayName,
              email: profile.emails[0].value,
              photoURL: profile.photos[0].value,
              providerId: 'facebook.com',
              uid: profile.id
            }
          ]
        })
```
And when I try to sign-in from client side by Facebook with the same email. I cannot sign in since there is email existing in Firebase Authentication. On the other hands, if I create account from Client Side App by Facebook. I cannot create admin.auth().createUser({ .... }) with the same Facebook email.

I think it happen because. The account is no linking together if we create account by Firebase Admin.

**Comment by bojeil-google** [comment]
Yeah, you can't currently create a federated account (such as Facebook, Google, etc) with createUser. Typically users that are migrating from an existing auth system have the need to use this functionality (in case their existing users were Facebook users). In that case the CLI SDK gives you the ability to upload existing Facebook users: https://firebase.google.com/docs/cli/auth#authimport
Regardless, we are looking into supporting this feature with Firebase Auth admin SDK.

**Comment by JochenDB** [comment]
@bojeil-google @hiranya911 Is there a timeline for this? Is there a suggested workaround? I can't keep doing a CLI action to keep syncing my users.

**Comment by bojeil-google** [comment]
Hey @JochenDB, we don't have a timeline for this. I will keep this post updated when I have an update. Most developers only need this feature for migration purposes and the CLI SDK is sufficient for that. That said, we will still support this.

**Comment by rhodgkins** [comment]
@bojeil-google it would also be great if when this gets implemented its also included in the `updateUser` function too. It would be create if we could add providers to an existing user (as far as I'm aware currently only available on the client side SDK)!

**Comment by bojeil-google** [comment]
Hey folks, the `importUsers` API was released yesterday:
https://github.com/firebase/firebase-admin-node/releases/tag/v5.11.0
The guide is located here:
https://firebase.google.com/docs/auth/admin/import-users

**Comment by RobertoAyala2112** [comment]
Same problem here, facebook users get an empty provider image in Firebase Console and cant singIn.
I dont get errors when I run my code.

My testing code:

```
var userImportOptions = {
    hash: {
        algorithm: 'HMAC_SHA256',
        key: Buffer.from('secretKey')
    }
};

admin
    .auth()
    .importUsers([{
        uid: 'asd123',
        firstName: 'Roberto',
        lastName: 'Ayala',
        email: '2112ayala@gmail.com',
        picture: 'https://graph.facebook.com/10214464120199982/picture?height=250',
        emailVerified: true,
        providerData: {
            displayName: 'Roberto Ayala',
            email: '2112ayala@gmail.com',
            photoURL: 'https://graph.facebook.com/10214464120199982/picture',
            providerId: 'facebook.com',
            uid: '10214464120199982'
        }
    }], userImportOptions)
    .then(function(userImportResult) {
        console.log(userImportResult.successCount);
    })
    .catch(function(error) {
        console.log(error);
    });
```

**Comment by System32-0101** [comment]
The quick solution I have found is to use a UUID generation library and [importUsers](https://firebase.google.com/docs/auth/admin/import-users#import_users_without_passwords) from Firebase Documentation

Im currently developing in **NodeJS with Express, Passport Strategies**
In my code:
```js
await admin.auth().importUsers([{
                    uid: uuidv4(),
                    email: profile.emails[0].value,
                    displayName: profile.displayName,
                    photoURL: profile.photos[0].value,
                    providerData: [{ providerId: "google.com", uid: profile.id, email: profile.emails[0].value, displayName: profile.displayName, photoURL: profile.photos[0].value }]
                }]);
```
                
- Where 'admin' is the NodeJS library `firebase-admin`
- For the uuid generation I used `uuid` library

And just register a single-user array with ImportUsers, this also appears in firebase as Google Provider.
![Provider showing correctly as google in Firebase](https://i.ibb.co/dfPzPn6/image.png)
