### ISSUE TITLE
Unable to batch write more than 250 items when using FieldValue.serverTimestamp()

### ISSUE THREAD

**Issue by dsl101** [firebase/firebase-admin-node#456]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 6.0.0
  * Firebase Product: firestore

### [REQUIRED] Step 3: Describe the problem

See https://github.com/firebase/firebase-functions/issues/408 for original issue, requested repost here.

The following code:

```
exports.mockBatchUpdate = functions.https.onCall(async data => {
  const projectRef = firestore.collection('projects').doc('batchUpdates')
  const batchSize = data.batchSize

  // Example data to be stored per document
  const output = _.times(batchSize, n => ({
    url: `http://nowhere.com/${n}`,
    index: n,
    other: `This is item ${n}`
  }))

  const batch = firestore.batch()
  _.forEach(output, item => {
    batch.set(projectRef.collection('output').doc(String(item.index)), {
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      ...item
    })
  })

  return batch.commit()
})
```

throws `Error: 3 INVALID_ARGUMENT: maximum 500 writes allowed per request` when attempting to write more than 250 items. This is due to `admin.firestore.FieldValue.serverTimestamp()` causing an additional write per item.

@joehan has filed an internal bug reference for the documentation (124449660) for `firestore.batch()` , but perhaps `admin.firestore.FieldValue.serverTimestamp()` should not be counted in the 500-item limit in batch operations so that the limit is accurate even when timestamps are involved.

**Comment by wilhuff** [comment]
Thanks for bringing this up and following up here.

The limit on the number of items in a batch is enforced by the server. As you've observed, server timestamps are transmitted to the server as an additional write that updates the a field with the request timestamp.

How these are counted isn't really anything we can change. We just uniformly count all writes whether they update a single field or a whole document.

We should update the documentation as you've already discussed with @joehan.
