### ISSUE TITLE
FR: Blacklist property `message_type` in DataMessagePayload

### ISSUE THREAD

**Issue by golopot** [firebase/firebase-admin-node#463]
### Describe your environment
  * Operating System version: 4.20.7-arch1-1-ARCH
  * Firebase SDK version: 7.0.0
  * Firebase Product: messaging

### Describe the problem
Device does not receive message if `payload.data` contains the property `message_type: "foo"`. It seems that `message_type` is a reserved  property handled somewhere by fcm. The property `message_type` is mention in this [fcm doc page](https://firebase.google.com/docs/cloud-messaging/server).

#### Steps to reproduce:
```javascript
const topic = 'some-topic';

const payload = {
  data: {
    message_type: 'foo',
  }
};

admin.messaging().sendToTopic(topic, payload)
```
### Feature Request
Throw Error if data contains (invalid) property `message_type`.

**Comment by hiranya911** [comment]
This is only mentioned in the XMPP API. I don't think it's something that can be used with the REST API, which is what the SDK uses. @chong-shao any idea what's going on? (please note that this is the legacy FCM API).

**Comment by chong-shao** [comment]
I reproduced this bug myself. Will send out a fix soon.

**Comment by fishst1k** [comment]
Is this really an issue with the node library?  I'm seeing the same issue in the firebase-admin-python sdk.  Seems like maybe there is something on the other side, the server the SDK communicates with.  Any way we can know if something changed over there?  We've been using `message_type` in our payloads for over a year and just started having issues in the last week :(

**Comment by chong-shao** [comment]
Hi fishst1k, is there any workaround you can introduce to avoid using message_type in your payloads? 
The fix we recently introduced makes the service return an error when message_type field is set (as described in the Feature Request in golopot's comment).

**Comment by fishst1k** [comment]
Is this a legit feature request?  Shouldn't the data in the payload be customizable and therefore not be restricted by reserved keywords?  We can definitely work around it, but would prefer not to as it is a fair amount of work (and testing).  Just want to make sure we are all doing the right thing ;-)

**Comment by hiranya911** [comment]
I would like to point out that this issue was originally reported for the legacy FCM API. But if it can be repro'ed with Python, that means the v1 FCM API has the same problem.

@chong-shao, what are the reserved keys for the data payload? Can we give them more unique names (e.g. fcminternal.message_type)?

**Comment by chong-shao** [comment]
Yes I introduced the fix in both the v1 FCM API and the legacy API. 

Currently. the reserved keys are:
"from"
"message_type"
"google.*"
"gcm.notification.*"

Change the reserved keyword to "fcminternal.message_type" requires a larger scale change in our backend.

**Comment by hiranya911** [comment]
I think we should just document these keywords and call it a day. @chong-shao can you work with the docs team to get the necessary page updated? We might want to update our API references too.

**Comment by hiranya911** [comment]
This is documented for the v1 API at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

Let's also document it for the legacy API.

**Comment by chong-shao** [comment]
The legacy API documentation update is submitted and it will be live soon.
