### ISSUE TITLE
Bug: Small subset of users not receiving push notifications [messaging().send...]

### ISSUE THREAD

**Issue by Bug-Reaper** [firebase/firebase-admin-node#464]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10 && Max OSX Mojave
  * Firebase SDK version:  7.0.0
  * Library version: 16?
  * Firebase Product: Messaging 

### [REQUIRED] Step 3: Describe the problem

A small subset of our users are not receiving remote push notifications sent via messaging().send.

We seem to be getting two different types of responses from messaging().send:

**Response Type A**
"response":"projects/<OurProjectID>/messages/1550865983585723
**Response Type B**
 "response":"projects/<OurProjectID>/messages/0:1550864692174221%64f3f09064f3f090

Users receiving **Response Type A** are getting push notifications without issue.
Users receiving **Response Type B** are failing to receive push notifications

What's the difference between these two responses? Has anyone else run into an issue with certain users not receiving remote push notifications?

#### Steps to reproduce:
It's reproduced dependent on FCM token.

#### Relevant Code:

```
      const message = {
        notification: {
          title,
          body,
        },
        data,
        token,
        // Apple specific settings
        apns: {
          headers: {
            'apns-priority': '10',
          },
          payload: {
            aps: {
              sound: 'default',
            },
          },
        },
        android: {
          priority: 'high',
          notification: {
            sound: 'default',
          },
        },
      }
      
      try {
        const response = await admin.messaging().send(message, config.firebase.messaging.dryRun)
        logger.debug({ response }, 'Push notification sent')
      } catch (err) {
        logger.error({ err, message }, 'Unable to send push notification')
      }
```

**Comment by hiranya911** [comment]
I don't think this is something that can be addressed here. I would advice you to contact Firebase support where you can share more details specific to your project: https://firebase.google.com/support/troubleshooter/

**Comment by timominous** [comment]
Are there any resolutions to this? I'm experiencing exactly the same problem with the difference in response formats.
