### ISSUE TITLE
Options object not supported for Firestore snapshot listener

### ISSUE THREAD

**Issue by jperasmus** [firebase/firebase-admin-node#466]
* Operating System version: MacOS Mojave (v10.14.2)
  * Firebase SDK version: v7.0.0
  * Firebase Product: firestore

### Describe the problem

[Firebase reference documentation](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#onSnapshot) states that you can have an options object as the first argument for the `DocumentReference.onShapshot()` method. This works for the `firebase` JavaScript client SDK, but not for this Node.js SDK.

Specifying an options object for this package produces the following error:

```
node_modules/@google-cloud/firestore/build/src/validate.js:93
                    throw new Error(message);
                    ^

Error: Argument "onNext" is not a valid function.
    at Validator.(anonymous function).values [as isFunction] (node_modules/@google-cloud/firestore/build/src/validate.js:93:27)
    at Query.onSnapshot (node_modules/@google-cloud/firestore/build/src/reference.js:1485:25)
    at Object.subscribeRaw (flamelink-js-sdk/packages/schemas/dist/cjs/cf/index.js:1864:29)
    at Object.subscribe (flamelink-js-sdk/packages/schemas/dist/cjs/cf/index.js:1871:24)
    at flamelink-js-sdk/packages/schemas/dist/cjs/cf/index.js:2004:21
    at Array.forEach (<anonymous>)
    at subscribeAndCacheSchemas (flamelink-js-sdk/packages/schemas/dist/cjs/cf/index.js:2003:24)
    at factory (flamelink-js-sdk/packages/schemas/dist/cjs/cf/index.js:2023:5)
    at schemas (flamelink-js-sdk/packages/schemas/dist/cjs/index.js:13:62)
    at flamelink-js-sdk/packages/app/dist/index.node.cjs.js:1249:24
```

Based on what I could tell, the problem is that this method is only expecting the first argument to be the `onNext` function:

<img width="771" alt="firestore-snapshot-options" src="https://user-images.githubusercontent.com/6787452/53489034-b0f81880-3a98-11e9-9bb6-0f7c584136db.png">

This code is actually in the `@google-cloud/firestore/build/src/reference.js` package, but that does not seem to be publicly available apart from via this repo.

#### Steps to reproduce:

- Initialize Firebase admin app
- Setup listener for a Firestore collection with the first argument an options object

#### Relevant Code:

```
const admin = require('firebase-admin')

const adminApp = admin.initializeApp({
  credential: <setup-credentials>
  ),
  databaseURL: 'https://something.firebaseio.com'
})

adminApp
  .firestore()
  .collection('someCollection')
  .onSnapshot(
    {
      includeMetadataChanges: true
    },
    onNextCallback,
    onErrorCallback
  )
```

**Comment by jperasmus** [comment]
Here is how the client SDK handles it: https://github.com/firebase/firebase-js-sdk/blob/6a0154aee104a163d6d3b1a28d80fcbb9bace908/packages/firestore/src/api/database.ts#L971

**Comment by hiranya911** [comment]
You're comparing JS SDK's API reference docs against the Firestore Node.js SDK. They have slightly different API surfaces. The server-side Node.js SDK does not support an options argument: https://cloud.google.com/nodejs/docs/reference/firestore/0.20.x/DocumentReference#onSnapshot

**Comment by hiranya911** [comment]
Assigning to the Firestore SDK team to comment on if this option should be added to the server-side SDK.

**Comment by wilhuff** [comment]
@hiranya911 is correct. There are no snapshot listener options in the server-side node SDK.

In particular, the `includeMetadataChanges` option doesn't exist there because those kinds of transitions only happen when there's a local cache involved. The server-side SDKs have no cache.

**Comment by jperasmus** [comment]
Thanks, @hiranya911 and @wilhuff 

It makes sense what you say about the `includeMetadataChanges` option specifically.

The thing that confused me was reading the Firebase reference docs and clicking the links under the `Node.js (client)` section, it actually takes you back to the standard JS docs.

<img width="296" alt="node js docs" src="https://user-images.githubusercontent.com/6787452/53518904-b2e2cb80-3ada-11e9-93c0-e25d68a95d1c.png">

This is my mistake. Thanks for your time.
