### ISSUE TITLE
FR: Support for the Firestore emulator using the environment variable

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-admin-node#472]
See this issue for motivation:
https://github.com/firebase/quickstart-nodejs/issues/59

Right now you can make the google-cloud Firestore library talk to the emulator:
```js
import { Firestore } from '@google-cloud/firestore';
import { credentials } from 'grpc';

const firestore = new Firestore({
  port: 8080,
  projectId: 'YOUR_PROJECT_ID',
  servicePath: 'localhost',
  sslCreds: credentials.createInsecure(),
});
```

It would be nice if the Admin SDK could detect this environment variable and set it up automatically:
```
FIRESTORE_EMULATOR_HOST=[::1]:8080,127.0.0.1:8080
```

**Comment by hiranya911** [comment]
@schmidt-sebastian what is the best place to address this? Change the Firestore Node.js client to support the env variable, or change `firebase-admin`?

**Comment by schmidt-sebastian** [comment]
I'd say this should be done by the GCloud Firestore SDK.
