### ISSUE TITLE
Uploading Files to Firebase using Admin SDK (Nodejs)

### ISSUE THREAD

**Issue by codekeyz** [firebase/firebase-admin-node#474]
According to the [Docs](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-nodejs), I have to pass the filename to the function in order to upload a file.
```typescript
// Uploads a local file to the bucket
await storage.bucket(bucketName).upload(filename, {
  // Support for HTTP requests made with `Accept-Encoding: gzip`
  gzip: true,
  metadata: {
    // Enable long-lived HTTP caching headers
    // Use only if the contents of the file will never change
    // (If the contents will change, use cacheControl: 'no-cache')
    cacheControl: 'public, max-age=31536000',
  },
});
```
I am using Firebase Admin SDK (Nodejs) in my server side code and clients send file in form-data which i get as File Objects. How then do i upload this when the function accepts only filename leading to filepath.

I want to be able to do something like this
```typescript

app.use(req: Request, res: Response) {
 const file = req.file;
// upload file to firebase storage using admin sdk
}

```

**Comment by hiranya911** [comment]
Please use Stackoverflow for usage help questions such as this one.
