### ISSUE TITLE
Node.js 8/ES2017 Error: Argument "updateFunction" is not a valid function.

### ISSUE THREAD

**Issue by igorakkerman** [firebase/firebase-admin-node#477]
Setting `"target": "es2017"` in _tsconfig.json_ along with `"engines": { "node": "8" }` in _package.json_ results in an error logged as:
> Argument "updateFunction" is not a valid function.

When I remove the target and the code is transpiled to JS, the application works fine.

Here's the code snippet

    async registerItem(id: string, eventId: string): Promise<void> {
        const collection = firestore().collection("col");

        await firestore().runTransaction(async transaction => {
            const snapshot = await transaction.get(collection.doc(id));
            await this.registerEvent(transaction, eventId);
            await this.createItem(transaction, snapshot, id);
        });
    }

It is transpiled to ES2017 as:

    async registerItem(id, eventId) {
        const collection = firebase_admin_1.firestore().collection("col");
        await firebase_admin_1.firestore().runTransaction(async (transaction) => {
            const snapshot = await transaction.get(collection.doc(id));
            await this.registerEvent(transaction, eventId);
            await this.createItem(transaction, snapshot, id);
        });
    }

Here's the stacktrace:
```
Error: Argument "updateFunction" is not a valid function.
    at Object.validateFunction (/srv/node_modules/@google-cloud/firestore/build/src/validate.js:65:19)
    at Firestore.runTransaction (/srv/node_modules/@google-cloud/firestore/build/src/index.js:484:20)
    at MyService.registerItem (/srv/lib/MyService.js:12:44)
    at exports.requestLogged.functions.firestore.document.onCreate (/srv/lib/main.js:23:10)
    at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at /worker/worker.js:825:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by schmidt-sebastian** [comment]
Thank you for sending this over! Fortunately, this issue has been fixed in `@google-cloud/firestore` (https://github.com/googleapis/nodejs-firestore/releases/tag/v1.1.0)

If you upgrade to Firebase Admin 7.1.0 you should pull in this new dependency automatically. Do let us know if you still encounter this issue with the updated version.

**Comment by igorakkerman** [comment]
Funny, seems I ran into this issue right on the day it got fixed/released. I hadn't checked for a new version before reporting. Works fine now, thank you!
