### ISSUE TITLE
INTERNAL ASSERT FAILED: Invalid user info response

### ISSUE THREAD

**Issue by evertonrobertoauler** [firebase/firebase-admin-node#481]
* Operating System version: Fedora 29
  * Firebase SDK version: @firebase/app@0.3.9
  * Library version: firebase-admin@^7.1.0
  * Firebase Product: auth

I replaced the user info by '...' for security reasons.

Calling the method admin.auth().getUser('userId'), I'm getting this response from authRequestHandler.getAccountInfoByUid:

```json
{
  "localId": "...",
  "email": "...",
  "displayName": "...",
  "photoUrl": "...",
  "emailVerified": true,
  "providerUserInfo": [
    { "providerId": "phone", "federatedId": "" },
    {
      "providerId": "google.com",
      "displayName": "...",
      "photoUrl": "...",
      "federatedId": "...",
      "email": "...",
      "rawId": "..."
    },
    {
      "providerId": "facebook.com",
      "displayName": "...",
      "photoUrl": "...",
      "federatedId": "...",
      "email": "...",
      "rawId": "..."
    },
    { "providerId": "phone", "rawId": "...", "phoneNumber": "..." }
  ],
  "validSince": "...",
  "disabled": false,
  "lastLoginAt": "1552858679099",
  "createdAt": "1552858670000",
  "customAuth": true,
  "phoneNumber": "..."
}
```

I started getting this error, after I imported this user using the method admin.auth().importUsers([user]) with the following data:

```ts
const user = {
      uid: '...',
      displayName: '...',
      email: '...',
      emailVerified: true,
      metadata: {
        creationTime: 'Sun, 17 Mar 2019 21:37:50 GMT',
        lastSignInTime: 'Sun, 17 Mar 2019 21:37:50 GMT'
      },
      phoneNumber: '...',
      photoURL: '...',
      providerData: [
        {
          uid: '...',
          displayName: undefined,
          email: undefined,
          photoURL: undefined,
          providerId: 'phone',
          phoneNumber: '...'
        },
        {
          uid: '...',
          displayName: '...',
          email: '...',
          photoURL:  '...',
          providerId: 'google.com',
          phoneNumber: undefined
        },
        {
          uid: '...',
          displayName: '...',
          email: '...',
          photoURL: '...',
          providerId: 'facebook.com',
          phoneNumber: undefined
        }
      ]
    };
```

I don't know why the API is returning this empty 'phone' provider info:

providerUserInfo:  [{ "providerId": "phone", "federatedId": "" }, ...]

**Comment by bojeil-google** [comment]
It is hard to tell. The user seems to have 2 phone providers which should not be possible. Can you open a ticket with [Firebase support](https://firebase.google.com/support/). We will need to ask you for some sensitive information related to your project and the specified user and this is not the appropriate forum for this.

**Comment by hiranya911** [comment]
Please follow up via Firebase Support as mentioned above.

**Comment by seanemmer** [comment]
@evertonrobertoauler @bojeil-google @hiranya911 I am facing the same issue - two phone providers are getting appended to the user when I run `importUsers`.  Was this ever resolved?  Should I open a ticket?

<img width="264" alt="image" src="https://user-images.githubusercontent.com/8183188/94717256-11f36c80-031e-11eb-9da1-8368fbfb1fab.png">
