### ISSUE TITLE
Calling revokeRefreshTokens prevents script from terminating

### ISSUE THREAD

**Issue by dandv** [firebase/firebase-admin-node#484]
After calling [admin.auth().revokeRefreshTokens](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#revokeRefreshTokens), a setTimeout handler is left running, which prevents the Node process from exiting.

#### Relevant Code:

The code is comprised of sections pasted almost verbatim from [Initialize the SDK](https://firebase.google.com/docs/admin/setup#initialize_the_sdk) and [Revoke refresh tokens](https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens). It uses the [why-is-node-running](https://github.com/mafintosh/why-is-node-running) module to show what prevents the script from exiting.

```
const log = require('why-is-node-running');
const admin = require('firebase-admin');
const serviceAccount = require('./firebase-adminsdk.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

// Revoke all refresh tokens for a specified user for whatever reason.
// Retrieve the timestamp of the revocation, in seconds since the epoch.
const uid = 'XXX';

admin.auth().revokeRefreshTokens(uid)
  .then(() => {
    return admin.auth().getUser(uid);
  })
  .then((userRecord) => {
    return new Date(userRecord.tokensValidAfterTime).getTime() / 1000;
  })
  .then((timestamp) => {
    console.log('Tokens revoked at: ', timestamp);
    log();
  });
```
`why-is-node-running` will display something like:

```
Tokens revoked at:  1552984694
There are 17 handle(s) keeping the process running

[...]

# Timeout
node_modules/firebase-admin/lib/firebase-app.js:162 - this.tokenRefreshTimeout_ = setTimeout(function () {
node_modules/firebase-admin/lib/firebase-app.js:104 - _this.setTokenRefreshTimeout(refreshTimeInSeconds * 1000, numRetries);
[..]
```

If this is WAI, then the [Initialize the SDK](https://firebase.google.com/docs/admin/setup#initialize_the_sdk) page should mention a teardown procedure.

**Comment by hiranya911** [comment]
`app.delete()` is the tear down method. We don't want to document this in the setup page, since only certain types of applications would ever need to call it.

**Comment by hiranya911** [comment]
https://firebase.google.com/docs/reference/admin/node/admin.app.App#delete

**Comment by dandv** [comment]
As I pointed out in [two](https://github.com/firebase/firebase-admin-node/issues/91) other [issues](https://github.com/firebase/firebase-admin-node/issues/150), calling app.delete() is under-documented, and developers have kept running into the problem of the process not terminating, for years.

> We don't want to document this in the setup page

Is there a better place than the setup page, to document the teardown method?

**Comment by Joshfindit** [comment]
*Please note: <https://firebase.google.com/docs/reference/admin/node/admin.app.App#delete> is 404 now. I assume moved to <https://firebase.google.com/docs/reference/admin/node/admin.app.App-1#delete>, but while it seems reasonable based on the URL and looks similar compared to archive.org's copy, I cannot say definitively*
