### ISSUE TITLE
Failed to parse response data

### ISSUE THREAD

**Issue by taina0407** [firebase/firebase-admin-node#49]
* Operating System version: Ubuntu 16.04
  * Firebase SDK version: ____
  * Library version: 5.0.0
  * Firebase Product: notification

### [REQUIRED] Step 3: Describe the problem
I'm using firebase-admin to fire FCM notifications to iOS and Androids clients. The module work fine but some time throw exception "Failed to parse response data"
I've tried to search but seem no one report it before and I don't know why it's happen.

#### Steps to reproduce:
Fire FCM notification 
```
fcmSender.messaging().sendToDevice(registrationTokens, fcmPayload, fcmOptions)
```

Here is trace log:
```
Error: Failed to parse response data: "SyntaxError: Unexpected end of JSON input". Raw serverresponse: "."
  File "/backend/node_modules/firebase-admin/lib/utils/error.js", line 39, col 28, in FirebaseAppError.FirebaseError [as constructor]
    var _this = _super.call(this, errorInfo.message) || this;
  File "/backend/node_modules/firebase-admin/lib/utils/error.js", line 84, col 23, in new FirebaseAppError
    return _super.call(this, {
  File "/backend/node_modules/firebase-admin/lib/utils/api-request.js", line 104, col 48, in IncomingMessage.<anonymous>
    var parsingError = new error_1.FirebaseAppError(error_1.AppErrorCodes.UNABLE_TO_PARSE_RESPONSE, "Failed to parse {snip}
  File "events.js", line 110, col 20, in emitNone
  File "events.js", line 207, col 7, in IncomingMessage.emit
  File "_stream_readable.js", line 1047, col 12, in endReadableNT
  File "internal/process/next_tick.js", line 102, col 11, in _combinedTickCallback
  File "internal/process/next_tick.js", line 198, col 9, in process._tickDomainCallback
```

**Comment by hiranya911** [comment]
How often does this happen? Do you have a deterministic way to reproduce it?

**Comment by hiranya911** [comment]
I have a feeling the above stacktrace has nothing to do with messaging (FCM). I would have expected to see some messaging related files or classes in the stacktrace. The error clearly originated at [HttpRequestHandler](https://github.com/firebase/firebase-admin-node/blob/master/src/utils/api-request.ts#L104) which is used by the entire SDK to make HTTP calls. But if the invocation originated at messaging API, the error would have been converted into a `FirebaseMessagingError` at [FirebaseMessagingRequestHandler](https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/messaging-api-request.ts#L103).

To start with I'm going to improve the error messages thrown by the HttpRequestHandler. Then we will have more information to debug this type of issues.

**Comment by taina0407** [comment]
Thank for your fast reply @hiranya911 
I'm sorry that I'm tried to but not able to find a correct way to reproduce it. It happened for me 16 times over 2 months. My app did send around 12k requests over that time.

I think this error may cause by the networking problem, but if you can improve the error messages that would be great. So we can determine should retry the request or not.

![image](https://user-images.githubusercontent.com/5900860/27972937-4aa90d08-6382-11e7-80b6-65e403076457.png)

Thanks

**Comment by hiranya911** [comment]
I have updated the error message. I'll try to get this improvement released in a few days. 

You're probably right about this being a network issue. We'll know more once we have more details in the error message.

**Comment by taina0407** [comment]
Hi @hiranya911 ,

Seem like the output error still not enough information to trace the problem :(

`FCM sending message failed { Error: Failed to parse response data: "SyntaxError: Unexpected end of JSON input". Raw serverresponse: "". Status code: "200". Outgoing request: "POST fcm.googleapis.com/fcm/send"
    at FirebaseAppError.FirebaseError [as constructor] (/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseAppError (/node_modules/firebase-admin/lib/utils/error.js:84:23)
    at IncomingMessage.<anonymous> (/node_modules/firebase-admin/lib/utils/api-request.js:104:48)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  errorInfo: 
   { code: 'app/unable-to-parse-response',
     message: 'Failed to parse response data: "SyntaxError: Unexpected end of JSON input". Raw serverresponse: "". Status code: "200". Outgoing request: "POST fcm.googleapis.com/fcm/send"' } }`

**Comment by hiranya911** [comment]
This is somewhat useful. I can check with the FCM team whether this is a server-side issue. I think this is some low-level issue though -- a loss of connection or a connection reset.

**Comment by hiranya911** [comment]
Starting from v5.3.0 Admin SDK retries HTTP requests on low-level errors. That should help with this too.

**Comment by hiranya911** [comment]
@taina0407 did you get a chance to try your implementation with Admin SDK v5.3.0 or higher? Does it help alleviate the problem?

**Comment by taina0407** [comment]
@hiranya911 I already upgrade to v5.3.0 and it seem the problem stop happen for 1 month already, so I think it   resolved now. Thanks
