### ISSUE TITLE
Still getting The behavior for Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK error

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-admin-node#495]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.2.1"

### [REQUIRED] Step 3: Describe the problem

I see `The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK` error in console logs. Though I have set `timestampsInSnapshots` to true and I don't use timestamps nor Date objects at all. Instead I store dates as integer values in Unix timestamp format

#### Relevant Code:

```
import * as admin from 'firebase-admin'
import * as functions from 'firebase-functions'

const firebase = functions.config().firebase
admin.initializeApp(firebase)
admin.firestore().settings({ timestampsInSnapshots: true })
```

**Comment by hiranya911** [comment]
You need firebase-admin v7 or up if you're going to use firebase-function 2.2.x.

**Comment by agordeev** [comment]
@hiranya911 `npm update firebase-admin` doesn't update the package. How do I update?

**Comment by daniel-farina** [comment]
in your packages.json

```
 "firebase-admin": "^7.3.0",
```
