### ISSUE TITLE
External resource holds or pending timers

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-admin-node#496]
### Describe your environment

  * Operating System version: Darwin Kernel Version 18.5.0
  * Firebase SDK version: v7.2.0
  * Library version: ?
  * Firebase Product: auth

### Describe the problem

Process hangs forever if a single auth call is performed.

#### Steps to reproduce:

Run the following to see process exit gracefully:
```ts
import * as admin from 'firebase-admin';

admin.initializeApp();
```

Run the following to see process hang forever after `done` is logged in the console:
```ts
import * as admin from 'firebase-admin';

admin.initializeApp();

admin
  .auth()
  .getUser('test')
  .catch(() => console.log('done'));
```

**Comment by hiranya911** [comment]
You need to delete the app if you wish to ensure graceful termination.

https://firebase.google.com/docs/reference/admin/node/admin.app.App#delete

**Comment by merlinnot** [comment]
Thanks, that seems to work.
