### ISSUE TITLE
ERROR TypeError: Cannot read property 'charAt' of undefined     at new e (jspdf.min.js:269)     at 

### ISSUE THREAD

**Issue by arjav197** [firebase/firebase-admin-node#497]
Issues regarding using jspdf in angular 

### 1.Package.json

`{

  "name": "project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "core-js": "^2.5.4",
    "jspdf": "^1.5.2",
    "ngx-pagination": "^3.2.1",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "uikit": "^3.0.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.4",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jspdf": "^1.2.2",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}`

### 2. Error:

ERROR TypeError: Cannot read property 'charAt' of undefined
    at new e (jspdf.min.js:269)
    at GeneratereportComponent.push../src/app/generatereport/generatereport.component.ts.GeneratereportComponent.downloadPDF (generatereport.component.ts:14)
    at Object.eval [as handleEvent] (GeneratereportComponent.html:5)
    at handleEvent (core.js:21673)
    at callWithDebugContext (core.js:22767)
    at Object.debugHandleEvent [as handleEvent] (core.js:22470)
    at dispatchEvent (core.js:19122)
    at core.js:19569
    at HTMLButtonElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)

 
3. Code 

### generatereport.ts file

`import { Component} from '@angular/core';
import  * as jsPDF from 'jspdf';

@Component({
  selector: 'app-generatereport',
  templateUrl: './generatereport.component.html',
  styleUrls: ['./generatereport.component.css']
})

export class GeneratereportComponent {
 
 downloadPDF(){

   const doc=new jsPDF();
    doc.text('Some text',15,25);
    doc.save('test.pdf');
  }
}`

### generatereport.html

`<div>
<p>
  generatereport works!
</p>
<button class="uk-button uk-button-primary" (click)="downloadPDF()">Export as PDF</button>
</div>
`

**Comment by hiranya911** [comment]
@arjav197 what does this has to do with the `firebase-admin` package?
