### ISSUE TITLE
Admin SDK using wrong service account when initialized without params in Cloud Functions

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-admin-node#500]
### [READ] Step 1: Are you in the right place?
Yes.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux (kernel 5.0.5)
  * Firebase SDK version: n/a
  * Library version: 7.2.0
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem
I just deployed a Cloud Function that uses the admin SDK to create custom tokens. I initialize it without any parameters: `admin.initializeApp()`.

When triggering the function I get this error (project information redacted):
``
Permission iam.serviceAccounts.signBlob is required to perform this operation on service account projects/-/serviceAccounts/<project-id>@appspot.gserviceaccount.com.; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature.
``

It looks like it's using the service account ```<project-id>@appspot.gserviceaccount.com``` instead of ```firebase-adminsdk-<random>@<project-id>.iam.gserviceaccount.com```. The first one lacks the *Service Account Token Creator* IAM permission necessary to sign blobs and create custom tokens.

#### Steps to reproduce:
1. Initialize Admin SDK without params
2. Write a Cloud Function that creates custom tokens
3. Deploy using the Firebase CLI
4. Trigger function

#### Relevant Code:
```js
const admin = require('firebase-admin');
const functions = require('firebase-functions');

admin.initializeApp();

export.createToken = functions.https.onRequest((req,res) => {
  return admin.auth()
    .createCustomToken('123456')
    .then(token => res.send(token));
});
```

**Comment by hiranya911** [comment]
This is working as intended. `<project-id>@appspot.gserviceaccount.com` is what get used in the Cloud Functions and App Engine environments for token signing. From the [documentation](https://firebase.google.com/docs/auth/admin/create-custom-tokens#letting_the_admin_sdk_discover_a_service_account):

> If the Firebase Admin SDK has to discover a service account ID string, it does so when your code creates a custom token for the first time. The result is cached and reused for subsequent token signing operations. The auto-discovered service account ID is usually one of the default service accounts provided by the Google Cloud Platform:
>
> * Default Compute Engine service account
> * [Default Cloud Functions service account](https://cloud.google.com/functions/docs/concepts/iam#runtime_service_account)

And [also](https://firebase.google.com/docs/auth/admin/create-custom-tokens#service_account_does_not_have_required_permissions):

> If the service account the Firebase Admin SDK is running as does not have the iam.serviceAccounts.signBlob permission, you may get an error message like the following:
>
> Permission iam.serviceAccounts.signBlob is required to perform this operation
on service account projects/-/serviceAccounts/{your-service-account-id}.
>
> The easiest way to resolve this is to grant the "Service Account Token Creator" IAM role to the service account in question, usually {project-name}@appspot.gserviceaccount.com

**Comment by jsayol** [comment]
Sorry about that Hiranya, I tried looking this up before opening the issue but didn't find those docs. Thanks for the links!
