### ISSUE TITLE
[question] Notify multiple users by token

### ISSUE THREAD

**Issue by thiagoalmedeiros** [firebase/firebase-admin-node#502]
Hi guys,

Is there a way to send a notification to a list of tokens only once or do I need to implement an iteration?

I have to notify multiple users when a packet is close to expiring.

**Comment by hiranya911** [comment]
https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendMulticast

Please use StackOverflow for usage questions such as this one.
