### ISSUE TITLE
functions shell treats timestamps as date, deployed functions like Timestamps

### ISSUE THREAD

**Issue by compojoom** [firebase/firebase-admin-node#503]
We are running firebase-admin "^6.3.0" and firebase-functions "^2.1.0". We haven't updated to the v7 of firebase admin because we have code that expects the data to be a date and we don't want to deal with timestamps yet.  We are storing a created and modified time by using the firebase.FieldValue.Timestamp()

Now we have a stupid problem. When testing with the functions shell my date is shown as a string:
` console.log('modified date', comment.modified, oldComment.modified, comment.modified === oldComment.modified)`
output is:
`modified date 2019-04-10T10:08:38.142Z 2019-04-10T10:08:38.141Z false`

on the server however - comment.modified is shown as Timestamp object? whaaaat?
`Timestamp { _seconds: 1554973960, _nanoseconds: 961000000 } Timestamp { _seconds: 1554975741, _nanoseconds: 925000000 }`

Am I missing something here? Why this discrepancy? 
Just for the test I tried doing:
`admin.firestore().settings( { timestampsInSnapshots: true })`

but even with that the functions shell is treating my dates as string. 

Why are the deployed functions treating the dates as timestamps? Has something in the firestore backend changed so that it always returns a timestamp, no matter what SDK is used?

On my machine the functions shell is running on node 11, the deployed functions are running with node 8?

**Comment by hiranya911** [comment]
Hi @compojoom. I think you're getting a Timestamp back, which gets printed to the console as a string. Try `console.log(new Date())` for comparison.

I believe the latest versions of the Functions SDK treat Firestore time values as timestamps. You should follow up at https://github.com/firebase/firebase-functions.
