### ISSUE TITLE
Add RxJs

### ISSUE THREAD

**Issue by polRk** [firebase/firebase-admin-node#511]
Я предлагаю добавить возможность работать с Observeble. 
I suggest adding the ability to work with Observeble.

```
import {from, of} from 'rxjs'

from(firestore.collection('col')).pipe(
   map(col => col.docs),
   take(1),
   mergeMap(doc => of(doc.update()))
   tap(console.log)
)

firestore.pipe(
   map(col => col.docs),
   take(1),
   mergeMap(doc => of(doc.update()))
   tap(console.log)
)

``` 

Now i can use rxjs wrapper, but it's not cool

```
fromPromise(firestore.collection('col'))
 // or
new Observable(observer => {
  firestore.collection('col').get().then(r => {observer.next(r)}).then(r => observer.close())
}).pipe(
   map(col => col.docs),
   take(1),
   mergeMap(doc => of(doc.update()))
   tap(console.log)
)
```

**Comment by schmidt-sebastian** [comment]
@polRk Thanks for sending this over! We do not have any immediate plans to add native support for Rx, but we will consider it in the future. Our API should already be usable with the Observer pattern, but it is true that you do have to jump through some hoops (as shown in your code snippet).

If anyone else would like to see better support in either the Admin SDK or the Mobile SDK, please do let us know.

**Comment by hiranya911** [comment]
I'm going to close this since I don't see any pending action items for this repo. If Rx support is ever implemented for Firestore, it should be done in https://github.com/googleapis/nodejs-firestore where the Firestore code lives.
