### ISSUE TITLE
FR: admin.auth().generateRecoverEmailLink

### ISSUE THREAD

**Issue by m-spyratos** [firebase/firebase-admin-node#517]
**Feature request:**

I'd like to be able to generate a link that allows email address change revocations (similar to the other link methods: `generateEmailVerificationLink`, `generatePasswordResetLink` and `generateSignInWithEmailLink`).

Following the generated link, `recoverEmail` mode can be handled as specified in the [Create custom email action handlers](https://firebase.google.com/docs/auth/custom-email-handler) page.

**Example:**

```
generateRecoverEmailLink(email, actionCodeSettings) returns Promise containing string
```
```
admin.auth()
    .generateRecoverEmailLink('user@example.com', actionCodeSettings)
    .then(function(link) {
      // The link was successfully generated.
    })
    .catch(function(error) {
      // Some error occurred, you can inspect the code: error.code
    });
```

**Comment by bojeil-google** [comment]
Recovery email is tied to an email update operation. It doesn't work on its own.

**Comment by hiranya911** [comment]
@bojeil-google I'll assign this to you to update (or close) as necessary.

**Comment by m-spyratos** [comment]
@bojeil-google With [Admin Auth SDK](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth), you can use the `updateUser` method to change a user's email. You could even use `importUsers` for the same purpose.

It would be nice to programmatically be able to send the recover email link, when I decide to change the user's email from within my service. Currently, I am forced to use the Web client to update a user's email.

**Comment by bojeil-google** [comment]
This is a bit tricky to support as this is directly tied to another operation (`updateEmail`). Though I do agree we should provide a channel to customize these type of emails, but it won't be as trivial as generating other type of email links. Feel free to file a [feature request](https://firebase.google.com/support/) for it.

**Comment by hiranya911** [comment]
I don't see an action item for the Admin SDK repo (at least not yet). Please file backend feature requests at the above link

**Comment by AndreinaRiera** [comment]
Hello! 
I am also needing this functionality.
As of today it has not yet been added and this ticket has been closed. 

Is there any news?
Did you develop your own complete web flow to solve it? @m-spyratos 

@bojeil-google
