### ISSUE TITLE
arrayUnion fail in 7.3.0

### ISSUE THREAD

**Issue by gnarco** [firebase/firebase-admin-node#523]
Hi

I was using firebase-admin@7.0.0

I updated to firebase-admin@7.3.0

I use arrayUnion.
Working perfectly in 7.0.0

Got 
Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Argument "dataOrField" is not a valid Document. Couldn't serialize object of type "ArrayUnionTransform" (found in field events). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
in 7.3.0

I reverted to 7.0.0, working again.

Is arrayUnion usage changed between these 2 versions ? 

Thanks

**Comment by rsgowman** [comment]
I don't believe there's been any change between the two... Could you provide a code snippet demonstrating how you're using it?

For reference, here's how we expect it to be used (switch the language to node.js):
https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array

When I use the following, it seems to work fine with both 7.0.0 and 7.3.0:

```javascript
const admin = require('firebase-admin');

const serviceAccount = require("./path/to/your/creds/file.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseUrl: "https://your_project_here.firebaseio.com"
});

const db = admin.firestore();
const docref = db.collection('col1').doc('doc1');

function getData() {
  docref.get()
    .then((snapshot) => {
      console.log(snapshot.data());
    })
    .catch((err) => {
      console.log("Error getting data", err);
    });
}   

getData();

docref.update({
    letters: admin.firestore.FieldValue.arrayUnion('c')
  })
  .then(() => {
    console.log("update ok!");
    getData();
  })
  .catch((err) => {
    console.log("Error updating data", err);
  });

```

Output:
```
$ node test.js 
{ letters: [ 'a', 'b' ] }
update ok!
{ letters: [ 'a', 'b', 'c' ] }
```

**Comment by rsgowman** [comment]
I'm going to close this issue for now, but if you're still having trouble, please feel free to reopen it.
