### ISSUE TITLE
firebase functions:config:set fails with uppercase environment variables

### ISSUE THREAD

**Issue by tfesslerCWC** [firebase/firebase-admin-node#528]
* Operating System version: Macos 10.14.4
  * Firebase SDK version: 6.9.1
  * Node JS Version: 8.16.0
  * Firebase Product: functions

Description:
UPPER CASE characters are required for some environment variables from some GOOGLE API's.    The current version of the firebase admin for node prevents the use of uppercase characters. 

Setting this configuration:
firebase functions:config:set GOOGLE_APPLICATION_CREDENTIALS="/Users/mickeymouse/functions/promotions-google-services.json"

Results in this error:
Error: Invalid config name GOOGLE_APPLICATION_CREDENTIALS, cannot use upper case

**Comment by hiranya911** [comment]
You're in the wrong repo. Function SDK and the associated tooling are in https://github.com/firebase/firebase-functions and https://github.com/firebase/firebase-tools

AFAIK the `functions:config:set ` is not meant to be used for regular environment variables. It is used to configure parameters that are then accessed from the Functions code. See https://firebase.google.com/docs/functions/config-env

**Comment by cybex-dev** [comment]
fwiw
[Firebase Environment variables docs](https://firebase.google.com/docs/functions/config-env?authuser=0#set_environment_configuration_with_the)

> Keep in mind that only lowercase characters are accepted in keys; uppercase characters are not allowed.

A bit odd that uppercase isn't allowed, I'm sure there is a good reason for it.
