### ISSUE TITLE
Improve index.d.ts

### ISSUE THREAD

**Issue by Crazometer** [firebase/firebase-admin-node#53]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: any
  * Firebase SDK version: any
  * Library version: latest
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem

`index.d.ts` sometimes has `any` where not required

e.g

`admin.database().ref('someref').once('value')` is `Promise<any>` when it should return the same type as the `successCallback` e.g. `Promise<admin.database.DataSnapshot>`.

**Comment by hiranya911** [comment]
This has been fixed in the database code a few days ago:

https://github.com/firebase/firebase-js-sdk/commit/a8919cdd16f3a4811efcc8736d2f167955f54047

**Comment by hiranya911** [comment]
This will be fixed when #54 is addressed.
