### ISSUE TITLE
when i am set data with doc id as number. it is not setting(adding) data or not throwing error

### ISSUE THREAD

**Issue by Harshad-Akhani** [firebase/firebase-admin-node#532]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: mac os Mojave
  * Firebase SDK version: 
  * Library version: 
  * Firebase Product: database(firestore).

### [REQUIRED] Step 3: Describe the problem
I want my document id as timestamp so i get timestamp try to set document.
but when i check i don't find data as well as i don't find any error. i also add catch block despite of i don't get error. but now i am getting error
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.    
#### Relevant Code:

       
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
Can you provide some code that reproduces this? It's difficult to picture your use case/issue without an example.

**Comment by schmidt-sebastian** [comment]
It would help us to know if you are converting the Timestamp to a String before you use it as a document ID. Document paths only support strings.

The following should work:

```
var time: Timestamp;
firestore.collection('coll').doc(time.toString()).set(...);
```

On the other hand, this should throw a validation error:


```
var time: Timestamp;
firestore.collection('coll').doc(time).set(...);
```

**Comment by hiranya911** [comment]
I assume the last comment provides enough context to answer the original question. Feel free to reopen if there's a bug that should be further investigated.
