### ISSUE TITLE
Auth error:FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up

### ISSUE THREAD

**Issue by florent1933** [firebase/firebase-admin-node#540]
### Describe your environment

  * Library version:
"firebase": "5.7.0",
"firebase-admin": "5.13.1",
  * Firebase Product: database

### Describe the problem

I am running a server in production and regularly I have this error: 
```
7|single   | [2019-05-26T07:16:19.801Z]  @firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"socket hang up\"."} 
7|single   | Auth error:FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up
```

This error happens randomly (~1 week or ~2 weeks after the server has started) and when it's happen, I have to restart the server.

**Comment by hiranya911** [comment]
I believe the JS SDK automatically re-connects after a failure like this. @schmidt-sebastian @Feiyang1 can you take a look?

**Comment by michaelReyder** [comment]
Has there been any new developments with this issue? I'm running "firebase-admin" version 7.4.0, and as mentioned in the OP, when running on our remote servers I'm seeing the following error:

'Error Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: Client network socket disconnected before secure TLS connection was established. Error code: ECONNRESET".'

**Comment by michaelReyder** [comment]
@Feiyang1  @schmidt-sebastian  @hiranya911  Could we please get some insight into this? Or perhaps you could advise as to where one might start looking to diagnose/remedy the issue?

**Comment by schmidt-sebastian** [comment]
@michaelReyder Unfortunately, I don't have much in terms of insightful updates :/ As you stated, we are retrying to fetch the OAuth token, but fail to do so even after four attempts. Are you able to update your code to use a different instance of the SDK once this error occurs?

**Comment by liho98** [comment]
same issues here! any firebase experts here to solve the issue?

**Comment by olieydt** [comment]
same issue here! using the firebase-admin npm package and every week or so a request will fail randomly with this error
Error: Request had invalid authentication credentials. Expected OAuth 2 access token

**Comment by hiranya911** [comment]
Can you folks describe your use case and environment a bit? Where is this code running (Cloud Functions, your own server etc)? What kind of operations are they executing (simple reads and writes, event listeners)?

@olieydt your issue seems to be quite different from the other cases reported here. In other cases, the SDK is failing to fetch a token from the Google OAuth2 servers. In your case somehow the SDK ended up with an invalid token?

Any chance we can get a debug log from a server that's experiencing this issue?

**Comment by olieydt** [comment]
@hiranya911 You are right, in my case it seems like the token isnt refreshed correctly. The rate of failures is similar to the issue referenced above.
We are running firebase-admin 8.4.0 on Node.js 10.16.0. A cron job runs every minute which makes use of a few _get_ calls, every week or two one of the calls produces the error "Request had invalid authentication credentials. Expected OAuth 2 access token"

**Comment by dweekly** [comment]
We are also seeing this issue in our project.

**Comment by atulshukla** [comment]
This is very frequent , We are using firebase functions.

**Comment by JuanRamino** [comment]
Same here. We get an ECONNRESET error.

**Comment by hiranya911** [comment]
If anybody's seeing this error frequently, please file a support request at https://firebase.google.com/support. And please provide more information than provided here (exact environment, Node.js version, SDK version, example code, and ideally a debug log).

**Comment by dweekly** [comment]
> If anybody's seeing this error frequently, please file a support request at https://firebase.google.com/support. And please provide more information than provided here (exact environment, Node.js version, SDK version, example code, and ideally a debug log).

Thanks, @hiranya911 - I've filed Case 00018754 with details.

**Comment by iouhammi** [comment]
@dweekly please any update from the support about the issue?

**Comment by dobromyslov** [comment]
Any update on this? I'm still experiencing this several times a day.

**Comment by danias** [comment]
I am getting this after doing thousands of Firestore sets. The data seems to have been updated but can I be sure that they have after getting this message? I see above @schmidt-sebastian mentioning something about retries. Is there a chance updates happen normally even if I get this message?

**Comment by Vinay-V9** [comment]
may be it is due to internet connection.

**Comment by wallstudios** [comment]
I'm seeing this sporadically as well. The function is a cloud trigger (firestore.document('doc/{docid}').onCreate).
It then looks up some user data then loads an image from storage. 

const functions = require('firebase-functions');
let admin = require("firebase-admin");

FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up
    at ClientRequest.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**Comment by gruckionvit** [comment]
I am noticing this error in my AWS::CloudWatch logs for production on an AWS Lambda function via API Gateway.

```json
{
  "code": 4,
  "details": "Deadline exceeded",
  "metadata": {
    "internalRepr": {},
    "options": {}
  }
}
```

This issue is discussed on [StackOverflow](https://stackoverflow.com/questions/46655344/firebase-cloud-function-with-firestore-returning-deadline-exceeded) as well.

```
    "firebase": "^7.14.2",
    "firebase-admin": "^8.11.0",
```

I am going to use AWS::SQS to place the write requests into a queue as it's important that these don't fail.

**Comment by schmidt-sebastian** [comment]
Closing this as we have no other updates at this point. Feel free to ping us to re-open.

**Comment by Cironic** [comment]
I am still facing this Problem.
Some insight in the environment: it's a node.js backend (currently running localy on my pc) where I want to trigger notifications to users that are subscribed.
when I am not behind our corporate proxy everything works like a charm but as soon as I am behind it, FCM doesn't work anymore.

I used the workaround I saw mutliple times, but somehow I can't gte it to work.

**here is the code**, I would be glad for some advice:

```
const admin = require('firebase-admin');
const serviceAccount = require('../../MY_PROJECT.json');
const tunnel = require('tunnel2');

const proxyAgent = tunnel.httpsOverHttp({
  proxy: {
    host: 'HERE I ENTERED THE CORPORATE PROXY', // is that correct???
    port: PORTNUMBER OF THE CORPORATE PROXY,

  },
});
var firebaseApp = admin.initializeApp({
  credential: admin.credential.cert(serviceAccount, proxyAgent),
  databaseURL: 'https://MY_PROJECT.firebaseio.com/',
});
```
**The Error I get:**
```
Error sending message: FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: tunneling socket could not be established, cause=socket hang up. Error code: ECONNRESET".
```

@schmidt-sebastian maybe you can tell me whether there are mistakes and it should work or if there is another way to solve that issue?

**Comment by schmidt-sebastian** [comment]
Looks like there is an answer here: https://stackoverflow.com/questions/43107493/firebase-nodejs-behind-proxy-server

**Comment by Cironic** [comment]
Well it really worked, but since it took me quiet a while to figure out how I'll leave a comment how I got it to work:

```
const proxyAgent = tunnel.httpsOverHttp({
  proxy: {
    host: 'YOUR_PROXY_HOST',
    port: YOUR_PROXY_PORT,
    proxyAuth: 'user:password', // Optional, required only if your proxy require authentication
  },
});
```

what took me so long to find is that you have to use the proxyAgent both in the `initializeApp()` and directly in AppOptions like this:
```
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount, proxyAgent),
  databaseURL: 'https://<DATABASE_NAME>.firebaseio.com'
  httpAgent: proxyAgent,
});
```
