### ISSUE TITLE
Firestore numbers greater than 2^53 are all stored as 9223372036854776000

### ISSUE THREAD

**Issue by Yonom** [firebase/firebase-admin-node#548]
#### Describe your environment

  * Operating System version: Firebase Functions, Node 8
  * Firebase SDK version: Unsure
  * Library version: "firebase-admin": "^8.0.0", "firebase-functions": "^2.3.1"
  * Firebase Product: Firestore Database

#### Steps to reproduce:

Run the relevant code in a Firebase function. A document will be created in firestore under test/test. The value of `testValue` will be 9223372036854776000 (2^53, Number.MAX_SAFE_INTEGER). Expected value for testValue: 11381641093478793584000.

This behavior differs from Firebase Web SDK's, where all numbers are properly stored and retrieved.

#### Relevant Code:

```js
await firebase.firestore().doc('test/test').set({
  testValue: 11381641093478793584000 // Large integer greater than 2^53
});
```

**Comment by schmidt-sebastian** [comment]
Hi! Thanks for filing this issue. This looks like it's happening inside of ProtobufJS. I will see if there is something we can do about it - but the optimal behavior we can achieve over 2^52 is precision loss.

**Comment by schmidt-sebastian** [comment]
I did some more Math, and it looks like the number you are quoting is actually 2^63: https://www.google.com/search?q=log(9223372036854776000)%2Flog(2)&rlz=1C5CHFA_enUS849US849&oq=log(9223372036854776000)&aqs=chrome.0.69i59j69i57j6.10022j0j7&sourceid=chrome&ie=UTF-8

In this case, this is a limitation with our backend. For signed integers, we only support 63 bit precision (https://firebase.google.com/docs/firestore/manage-data/data-types). The behavior you should see in Node is that numbers from 0 to 2^53 should get mapped correctly, while any number from 2^53 to 2^63 may lose some precision. Any numbers larger than 2^63 will get capped at 2^63 by the backend (and vice versa for negative numbers).

If you want to store numbers larger than 2^64, you have to pass them as floating point numbers. You need to make sure they do not pass this check: https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/serializer.ts#L119. The Web SDK seems to do this automatically for numbers greater than 2^53 and I will check with my team if that is something that we should do in this SDK as well.

**Comment by Yonom** [comment]
Thank you for your reply.

> https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/serializer.ts#L119
This check cannot be bypassed for any number greater than 2^53, as the double precision will not allow anything but full integers.

Do you have an ETA of when a fix will be made available? 
Are there any workarounds we can use in the meantime?

**Comment by schmidt-sebastian** [comment]
This should be fixed as part of the next release.
