### ISSUE TITLE
FirebaseError : Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object

### ISSUE THREAD

**Issue by jetaimefrc** [firebase/firebase-admin-node#549]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Majove 10.14.2
  * Library version: ^6.1.0
  * Firebase Product: firestore

#### Steps to reproduce:

When i tried to setting firestore, i used both SSL and timestampsInSnapshots but have the same result as the title. And after i refresh page => TypeError: Can not read property 'firestore' of null.
Anyone can help me settle this problem ?
#### Relevant Code:

```
import * as firebase from 'firebase/app'
import 'firebase/firestore'
require('dotenv').config({ encoding: 'utf8' })

const firebaseConfig = {
  apiKey: process.env.API_KEY,
  authDomain: process.env.AUTH_DOMAIN,
  databaseURL: process.env.DATABASE_URL,
  projectId: process.env.PROJECT_ID,
  storageBucket: process.env.STORAGE_BUCKET,
  messagingSenderId: process.env.MESSAGING_SENDER_ID,
  appId: process.env.APP_ID
}
// Initialize Firebase
let firebaseApp = null
if (!firebase.apps.length) {
  firebaseApp = firebase.initializeApp(firebaseConfig)
}
firebaseApp.firestore().settings({ ssl: true })

export default firebaseApp.firestore()
```

**Comment by hiranya911** [comment]
Wrong place. This is the repo for the `firebase-admin` Node.js library. Above code sample is for the Firebase JS SDK.
