### ISSUE TITLE
Firebase Authentification - Delete trigger and revoking tokens

### ISSUE THREAD

**Issue by tspoke** [firebase/firebase-admin-node#550]
### Environment

  * Operating System version: macOS mojave
  * Firebase Product: auth & firebase web interface (auth section)
  * Libraries : 

```
"firebase-admin": "7.1.0",
"firebase-functions": "2.2.0",
```

###  Problem

> The problem is about the deletion of users in nodejs and with the web interface. I don't know if this issue should be here because it's more a global issue than a nodejs issue.

Firebase auth seems to have an unwanted behavior when deleting a user from the Firebase web interface in the Authentification section.

If I delete a user from there, my trigger is called (node) and I can cleanup user data. But, the user is still connected on the mobile android app : its tokens are still valid.

To revoke the token I tried to call `admin.auth().revokeRefreshTokens(userId)` in my trigger, but the user has already been deleted in Firebase, so I get this error :

```
Error: There is no user record corresponding to the provided identifier.
```

From there I thought about creating an API endpoint and call it from my app (delete the user from the nodejs and cleanup tokens). But if I do this, the deletion of users from the Firebase web interface will be inconsistent/different from the deletion done by my code and the user will stay connected (as long as the token is valid).

• IMO the deletion of a user should delete/revoke all its tokens
• Revoking tokens from a deleted user (missing) should not throw an error because the tokens still exist even if the user does not!

#### Steps to reproduce

- Create a user in firebase auth
- Create a trigger watching for : `functions.auth.user().onDelete`
- In the called function, try to revoke tokens of the deleted user `admin.auth().revokeRefreshTokens(userId)`

**Comment by bojeil-google** [comment]
The last ID token is likely still valid until its natural lifetime. The refresh token is automatically revoked on deletion (there is not need to manually revoke). You can detect revocation (due to deletion) as described in the [official docs](https://firebase.google.com/docs/auth/admin/manage-sessions#detect_id_token_revocation).
