### ISSUE TITLE
nested require prevents import with rollup

### ISSUE THREAD

**Issue by brewster1134** [firebase/firebase-admin-node#555]
i am trying to build an admin interface to my firestore and using rollup to generate the bundled assets. when i follow the steps in the [documentation](https://firebase.google.com/docs/admin/setup#add_the_sdk) (and additionally trying to use my local emulators based on this [github issue](https://github.com/firebase/quickstart-nodejs/issues/59)), however when either `firebase-admin` or `@google-cloud/firestore` are  imported, they each contain further `require` statements. i have tried every possible combination of es6 import syntaxes & multiple rollup plugins, but do not see a solution for using the admin sdk in my app without needing full commonjs support.

perhaps this aspect of firebase does not support being built with these newer bundlers? tyia

###### app.js
```js
import * as admin from 'firebase-admin';
```

###### bundle.js
```js
var firebase = require("./default-namespace");
// ...
module.exports = firebase;
```

###### app.js
```js
import { Firestore } from '@google-cloud/firestore'
```

###### exception
```shell
[!] Error: Unexpected token (Note that you need rollup-plugin-json to import JSON files)
node_modules/@google-cloud/firestore/package.json (2:8)
```

**Comment by hiranya911** [comment]
Not sure I fully understand what's going on. Are you trying to use these libraries in a client-side application?

**Comment by hiranya911** [comment]
I'm going to assume this happened because the SDK was used in a client-side framework (the original post mentions an "admin interface"). Please provide more details if that's not the case.

**Comment by brewster1134** [comment]
the admin interface, refers to a CRUD web app interface to manage the firestore data. i am trying to set it up to run via firebase hosting. i'm not sure what you mean about a client-side application, but if this is considered one, what should i be using instead?

**Comment by hiranya911** [comment]
Yes, your use case seems like a client-side usage. Both `firebase-admin` and `@google-cloud/firestore` are designed for server-side Node.js applications. They do not work in scenarios where the code executes in end user's web browser.

You should be using the regular `firebase` package, which is designed for client-side web apps.
