### ISSUE TITLE
@types/jsonwebtoken dependency

### ISSUE THREAD

**Issue by AdriVanHoudt** [firebase/firebase-admin-node#56]
Why is @types/jsonwebtoken a dependency and not a dev dep?
See https://github.com/firebase/firebase-admin-node/blob/master/package.json#L28

**Comment by hiranya911** [comment]
I believe it is required to support custom token minting and ID token verification in Firebase Auth.

**Comment by AdriVanHoudt** [comment]
But those are just typescript typedefs no? I can't see them being required (but I can be wrong ofc)

**Comment by hiranya911** [comment]
We might be able to get rid of it. I'll try it out and if all goes well fix it in a future release.
