### ISSUE TITLE
Use of legacy metadata endpoints

### ISSUE THREAD

**Issue by langleyd** [firebase/firebase-admin-node#560]
* Library version: latest (Currently 8.0)
  * GKE 1.12

#### Steps to reproduce:

Use of the admin api within GKE 1.12 failed with error:
Your client does not have permission to get URL <code>/computeMetadata/v1beta1/instance/service-accounts/default/token</code> from this server. Legacy metadata endpoint accessed: /computeMetadata/v1beta1/instance/service-accounts/default/token

As noted here the legacy endpoints as now disabled by default:
https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#disable-legacy-apis

#### Relevant Code:

I think this code should be updated to use`/v1`:

https://github.com/firebase/firebase-admin-node/blob/master/src/auth/credential.ts#L32

**Comment by ramzimaalej** [comment]
I'm facing the same issue too

**Comment by ramzimaalej** [comment]
can you please make theses changes available?

**Comment by sferencik** [comment]
I had the same issue when running `firebase list` but that's because I had forgotten to pass the `--token`. Without the token, firebase defaults to authentication via app default credentials, and ends up here. Woth the token you don't encounter this v1/v1beta1 issue.
