### ISSUE TITLE
Tokens type with MongooseArray conflict with android TTL

### ISSUE THREAD

**Issue by Mangosteen-Yang** [firebase/firebase-admin-node#566]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MAC OS 10.14
  * Firebase SDK version: 8.1.0
  * Library version: Node 12, Mongoose 5.5.14
  * Firebase Product: messaging

#### Steps to reproduce:

I send notifications with `admin.messaging().sendMulticast(message)`
However, If I set android TTL and `toknes` as a `MongooseArray` I got error `TTL must be a non-negative duration in milliseconds` **[case1]**
If I remove TTL in android object only, success. **[case2]**
If I **do not** remove TTL in android object and change tokens from `MongooseArray` to `Array` only, success. **[case3]**

#### Relevant Code:

case 1:
```
message: {
  notification: { title: 'title', body: 'body' },
  data: { demo: 'data' },
  android: {
    ttl: 3600000,
    notification: { icon: 'stock_ticker_update', color: '#41dff4' }
  },
  apns: { payload: { aps: [Object] } },
  tokens: ["demo:token"]
}

console.log(message.tokens.constructor);
// [Function: CoreMongooseArray]

// After call admin.messaging().sendMulticast(message)

    Error: TTL must be a non-negative duration in milliseconds
        at FirebaseMessagingError.FirebaseError [as constructor] (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/utils/error.js:42:28)
        at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/utils/error.js:88:28)
        at new FirebaseMessagingError (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/utils/error.js:253:16)
        at validateAndroidConfig (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/messaging/messaging-types.js:249:19)
        at Object.validateMessage (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/messaging/messaging-types.js:49:5)
        at /Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/messaging/messaging.js:260:31
        at CoreMongooseArray.map (<anonymous>)
        at Messaging.sendAll (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/messaging/messaging.js:259:29)
        at Messaging.sendMulticast (/Users/shuo/Documents/iwin-api/node_modules/firebase-admin/lib/messaging/messaging.js:308:21)
        at Object.pushToDeviceOrTopic (/Users/shuo/Documents/iwin-api/app/services/notification/push.notification.service.js:68:23)
        at Object.notifyOneUser (/Users/shuo/Documents/iwin-api/app/api/notification/notification.controller.js:77:27)
        at processTicksAndRejections (internal/process/task_queues.js:88:5)
```

case 2:
```
message: {
  notification: { title: 'title', body: 'body' },
  data: { demo: 'data' },
  android: {
    notification: { icon: 'stock_ticker_update', color: '#41dff4' }
  },
  apns: { payload: { aps: [Object] } },
  tokens: ["demo:token"]
}

console.log(message.tokens.constructor);
// [Function: CoreMongooseArray]

// After call admin.messaging().sendMulticast(message)
// Success!
```

case 3:
```
message: {
  notification: { title: 'title', body: 'body' },
  data: { demo: 'data' },
  android: {
    ttl: 3600000,
    notification: { icon: 'stock_ticker_update', color: '#41dff4' }
  },
  apns: { payload: { aps: [Object] } },
  tokens: ["demo:token"]
}

console.log(message.tokens.constructor);
// [Function: Array]

// After call admin.messaging().sendMulticast(message)
// Success!
```

**Comment by hiranya911** [comment]
Can you provide a standalone repro? I tried the following and it works fine for me:

```
const firebase = require('firebase-admin');
const mongoose = require('mongoose');

const app = firebase.initializeApp({
    projectId: 'test-project'
});

var parentSchema = mongoose.Schema({tokens: 'array'});
var Parent = mongoose.model('Parent', parentSchema);
var parent = new Parent;
parent.tokens.push('token1');
console.log(parent.tokens.constructor);

const msg = {
    notification: { title: 'title', body: 'body' },
    data: { demo: 'data' },
    android: {
        ttl: 3600000,
        notification: { icon: 'stock_ticker_update', color: '#41dff4' }
    },
    apns: { payload: { aps: {} } },
    tokens: parent.tokens,
};

(async () => {
    try {
        const batchResponse = await firebase.messaging().sendMulticast(msg);
        console.log('Done');
    } catch (err) {
        console.log(err);
    }
    await app.delete();
})();
```

This generates the output:
```
[Function: CoreMongooseArray]
Done
```

The error you're seeing is thrown by the following code: https://github.com/firebase/firebase-admin-node/blob/6c0204c0e4893bfd8157b1c6fe567296bd38f67d/src/messaging/messaging-types.ts#L517-L521

This can only happen when the TTL value is set to something other than a JS number type. There's probably some issue in your code which is causing this.

**Comment by hiranya911** [comment]
Ok, was able to reproduce this using an array with more than 1 element. This happens because elements in mongoose do not get deep copied properly. You will have to use a regular array of tokens.

**Comment by hiranya911** [comment]
I spent some more time tinkering with this issue, and I've found an interesting discrepancy. The problem here is that `MongooseArray` is a custom class that extends the JS `Array` type. And the SDK doesn't deep copy such custom types correctly, which is what causes this error. So I've been trying to reproduce the issue using a test case, and it appears when the code is written using TypeScript, the problem goes away. Consider the following example.

Example code:
```
class CustomArray extends Array { }

const array = new CustomArray();
array.push(1);
array.push(2);

const doubleArray = array.map((item) => item * 2);
console.log(doubleArray, doubleArray.constructor);
```

The above code, when executed directly as a JS script produces the following output:
```
CustomArray [ 2, 4 ] [Function: CustomArray]
```

But the same code, when compiled as TypeScript into ES5, produces this output:
```
[ 2, 4 ] [Function: Array]
```

Notice how the `CustomArray` has become a regular `Array`. Other ES5 users should be similarlt protected from this error.

**Comment by Mangosteen-Yang** [comment]
@hiranya911 Interesting findings! Thanks.
Do you think it is a bug or not? 

Right now I get data as `CustomArray ` then transfer to `Array` to avoid the error.
We may refactor our application with TypeScript in the future.

**Comment by hiranya911** [comment]
@Mangosteen-Yang, I think it can be interpreted both as a bug and a user error :) But I'm open to fixing the SDK code to handle custom array types in `MulticastMessage` gracefully. So please stand by.

In the meantime you can do this in your code:

```
const msg = {
    notification: { title: 'title', body: 'body' },
    data: { demo: 'data' },
    android: {
        ttl: 3600000,
        notification: { icon: 'stock_ticker_update', color: '#41dff4' }
    },
    apns: { payload: { aps: {} } },
    tokens: Array.from(parent.tokens), // Convert to a regular array
};
```
