### ISSUE TITLE
FR: Add support for checkActionCode and applyActionCode to auth() implementation

### ISSUE THREAD

**Issue by kelle62819** [firebase/firebase-admin-node#57]
I tried making a custom email action handler in a firebase cloud function and found that these methods weren't available with the firebase-admin-node implementation.

**Comment by bojeil-google** [comment]
Yeah you need to use the client SDK (require('firebase')) for that.

**Comment by bojeil-google** [comment]
Just to clarify, we don't see a need to add those to the admin SDK. This is meant to be consumed on the client side. If you insist on using them in the backend, simply require the client SDK as I mentioned.

**Comment by kelle62819** [comment]
The reason I want to do this on the backend is because I want to make updates to the user record without them having to authenticate on the client side. In the previous iteration I had the app polling to see if the email had been verified, but this seems pretty clunky to me. I would much rather have a webhook triggered on account validation that updates their user profile. Ideally the angularfire2 user observable would just reflect the update to emailVerified, but this doesn't happen you have to poll and do a reload. By putting the action handler on the backend I can handle the validation and immediately update the database record. Very clean solution.

**Comment by kelle62819** [comment]
I did get this working. But in my use case I have to include both the client and admin modules. Seems like a lot of unnecessary duplication. Thanks for the help.

**Comment by bojeil-google** [comment]
Hey @kelle62819, it seems you have your own custom email action handler:
https://firebase.google.com/docs/auth/custom-email-handler
You can easily detect the emailVerified change by using real-time database. In your custom landing page (client side), on applyActionCode, you need to set some boolean emailVerified for a user specific database node that you listen to in your other clients to detect this change. No polling will be needed.

I personally think an emailVerified Firebase function event trigger should be something we should look into. Will relay that to the Firebase Auth team.

**Comment by code-tree** [comment]
It seems like many people suggest saving the user's email address on the client-side to the database, which obviously works well if the applyActionCode() is processed client-side. But this appears to be a security hole, as the user can save a different address to the database than the one that was actually verified. The only way to ensure the address that is saved to db is the same as the one that is verified is to process server-side.

Am I missing something, or is this genuinely a security hole? (at least the way it is being implemented by some developers)

**Comment by bojeil-google** [comment]
If you are using client side real time database to propagate that the email was verified, you will only use that to notify the signed in user, but you will call `currentUser.reload()` and then check `currentUser.emailVerified`. That would be the source of truth and not the db event change which is unauthenticated.

Quick update on this issue, we now provide the ability to pass a continue URL after verification. This could be used to pass state back to the app and notify it that the email was verified. To learn more about this: 
https://firebase.google.com/docs/auth/web/passing-state-in-email-actions

**Comment by code-tree** [comment]
@bojeil-google In my case one user books another user, and an email is sent on behalf of user A to user B. User A triggers a cloud function which needs to know user B's verified email address. So I have to store each user's verified email address in database to allow for this.

Solutions on the web seem to involve doing this client-side, which I assume would allow setting any address if hacked.

(it just occurred to me that another solution might be using `getUser()` in the admin tools to get user B's email address and check it's verified)

**Comment by bojeil-google** [comment]
I don't know how one user 'books' another user. Email verification is not a mechanism to send sign up invites. A user has to first sign up before sending an email verification. If you are having a user sign up on another user's behalf, then it is a security issue.

**Comment by code-tree** [comment]
Sorry, I mean two user's who have both already signed up (and my app checks that they have both verified their email addresses). User A is booking a tutoring session with user B, and the app sends an email on user A's behalf to user B.
