### ISSUE TITLE
Calling `Firebase.initializeApp` more than once causes `default Firebase app already exists` error.

### ISSUE THREAD

**Issue by ccorcos** [firebase/firebase-admin-node#571]
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
"firebase-admin": "5.12.1",

When I call `Firebase.initializeApp()` more than once, I get this error:

```
Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
```

Its really annoying because I want to create isolated servers for each test without having to run a separate instance of Node. Can you please fix this so more than one can run side-by-side?

**Comment by hiranya911** [comment]
There's nothing to fix. This is how this API is expected to work. If you want to run multiple instances of FirebaseApp, you need to give them different names. See https://firebase.google.com/docs/reference/admin/node/admin.app.App.html#name for some examples.

**Comment by ccorcos** [comment]
Interesting. So I can make up a random string each time?

**Comment by hiranya911** [comment]
That's up to you. As far as the SDK is concerned, each instance of FirebaseApp must have a different name.

**Comment by Johnrobmiller** [comment]
> There's nothing to fix. This is how this API is expected to work. If you want to run multiple instances of FirebaseApp, you need to give them different names. See https://firebase.google.com/docs/reference/admin/node/admin.app.App.html#name for some examples.

Your app is breaking on Next.js projects with this error. There is nothing in the docs that clues people in on how to fix it. So there actually is something for you guys to fix.

**Comment by DrjavaB** [comment]
> There's nothing to fix. This is how this API is expected to work. If you want to run multiple instances of FirebaseApp, you need to give them different names. See https://firebase.google.com/docs/reference/admin/node/admin.app.App.html#name for some examples.

the link you sent doesn't work...

**Comment by jstncno** [comment]
Based on comments on this thread, the answer provided is not very helpful, i.e. this error breaks Next.js projects with no help info and the provided link leads to a 404.

I've resurrected this issue with a more narrow scope stating that this error breaks Next.js apps:
https://github.com/firebase/firebase-admin-node/issues/2111

**Comment by YoungiiJC** [comment]
I am also getting this error in Firebase Functions.

```typescript
export const someFirebaseFunction = functions.https.onRequest(
  async (request, response) => {
    ...
    initializeApp();
    ...
  }
)
```

**Comment by hariacharya7** [comment]
I was also getting this error but apparently wrapping the `initializeApp` function under a conditional statement which is executed if `firebaseError` is `false` solves this issue.  The below is how this issue was resolved for me:
```
 if (!FirebaseError) {
      admin.initializeApp({
        credential: admin.credential.cert(cred), //cred is my firebase config file.
    });
 }
```

**Comment by hariacharya7** [comment]
A way to resolve this issue is to make the function async and try and catch the error but also continue doing your task:
```
try {
      admin.initializeApp({
        credential: admin.credential.cert(cred),
      });
      return respond();
    } catch (e) {
      return respond();
    }

function respond(){
// perform your task
}
```
