### ISSUE TITLE
Enforce UserImportOptions when importing users with passwords

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-node#577]
When importing users with passwords, `UserImportOptions` must be specified. But the SDK does not check for this condition correctly. Instead it generates the following error when the user records contain passwords and `UserImportOptions` is not specified:

```
.../node_modules/firebase-admin/lib/auth/user-import-builder.js:176 if (!validator.isNonNullObject(options.hash)) { TypeError: Cannot read property 'hash' of undefined....
```

See https://stackoverflow.com/questions/56680087/firebase-admin-import-users-doesnt-work

**Comment by bojeil-google** [comment]
Just to confirm, is the issue that we are not validating `options` is `nonNullObject` first?

**Comment by hiranya911** [comment]
@bojeil-google. Yes, I think we should check `options` is specified before checking `options.hash`.
