### ISSUE TITLE
FR:analytics_label support in FCM

### ISSUE THREAD

**Issue by xuaninbox** [firebase/firebase-admin-node#580]
Got the warning on FCM Reports Console saying we should add analytics_label to the messages but it seems it's only available in REST api. Is there a plan to add it in node sdk?

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?authuser=0#fcmoptions

**Comment by hiranya911** [comment]
Yes, it's planned. Don't have a time frame yet.

**Comment by ralfiannor** [comment]
I have a problem when running firebase admin SDK. All notification analytics don't work. Is there no analytic notification in firebase admin sdk ?

**Comment by hiranya911** [comment]
Implemented in #597

**Comment by afestein** [comment]
Thanks @hiranya911 - we're really excited to use this feature. Any chance we could get a release? 😄

**Comment by the-real-mrcs** [comment]
> Thanks @hiranya911 - we're really excited to use this feature. Any chance we could get a release?

This is now available since v8.4.0.
