### ISSUE TITLE
getUserByEmail should return undefined if a user does not exist.

### ISSUE THREAD

**Issue by burtonator** [firebase/firebase-admin-node#581]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 19.04
  * Firebase SDK version: 8.2.0
  * Library version: 8.2.0
  * Firebase Product: firestore

### [REQUIRED] Step 3: Describe the problem

getUserByEmail('fakeuser@example.com')

will throw an error if the user isn't present.  

This isn't a failure but is a totally rational situation.  There's no way to lookup a user by email and determine if there was a legitimate failure or not.

All these getUserByX functions should also return a null/undefined instead of throwing an error on a missing value.

**Comment by hiranya911** [comment]
> There's no way to lookup a user by email and determine if there was a legitimate failure or not.

You should check the error code for `auth/user-not-found`. That is how these APIs are meant to be used:

https://github.com/firebase/firebase-admin-node/blob/1086515e34cab653ec4b4fa29c19d96f4600de4b/test/integration/auth.spec.ts#L281-L284
