### ISSUE TITLE
Pagination does not work properly 

### ISSUE THREAD

**Issue by nilinyi** [firebase/firebase-admin-node#591]
### Environment
  * Operating System version: macOS 10.14.5
  * firebase-admin version: 7.4.0
  * google-cloud/firestore version: 2.2.3
  * Firebase Product: Cloud Firestore & Cloud Functions

### Describe the problem
Whenever I call `startAfter`, it will always show me the below error in the log. The error does not make sense to me because even if I chose to return the documents whose `id` field, the field I used to sort documents, after character `a` or `A`, I still cannot get anything back but the same error:

```
Error: 3 INVALID_ARGUMENT: cursor position is outside the range of the original query
```

### Steps to reproduce:

Here is my query. The query is to get the documents such that its field `geolocation.geohash_4` equals to `qwer` AND its field `geolocation.geohash_5` NOT equal to `qwert` (I perform the inequality query by combining `<` and `>`). Also the returned documents should be sorted by `id` for me to do pagination.

NOTE: The reason I do `orderBy("geolocation.geohash_5")` first is necessary since this [article](https://cloud.google.com/appengine/docs/standard/go/datastore/query-restrictions) said: 

> Properties used in inequality filters must be sorted first

Here is the code:
```js
let query1 = 
await
COLLECTION_REF
.where("geolocation.geohash_4", '==', "qwer")
.where("geolocation.geohash_5", '>', "qwert")
.orderBy("geolocation.geohash_5")
.orderBy('id')
.startAfter("some-doc-id")
.get();

let query2 = 
await
COLLECTION_REF
.where("geolocation.geohash_4", '==', "qwer")
.where("geolocation.geohash_5", '<', "qwert")
.orderBy("geolocation.geohash_5")
.orderBy('id')
.startAfter("some-doc-id")
.get();

let combined = query1.docs().concat(query2.docs());
```
The expected result should be that, either `query1` or `query2` succeeds with returned documents and the other succeeds with empty array. However, right now the result is that, one query succeeds with empty array and the other failed with the above error: `Error: 3 INVALID_ARGUMENT: cursor position is outside the range of the original query`.

### Here are my documents in the Collection 
```json
[{
        "id": "BSc0yXZILbaDWgHbqwer",
        "geolocation": {
            "geohash_9": "y0zh7zpve",
            "geohash_8": "y0zh7zpv",
            "geohash_7": "y0zh7zp",
            "geohash_6": "y0zh7z",
            "geohash_5": "y0zh7",
            "geohash_4": "y0zh",
            "geohash_3": "y0z",
            "geohash_2": "y0",
            "geohash_1": "y"
        }
    },
    {
        "id": "aiuwoernesDWgHb54qe",
        "geolocation": {
            "geohash_9": "y0zhe8dvd",
            "geohash_8": "y0zhe8dv",
            "geohash_7": "y0zhe8d",
            "geohash_6": "y0zhe8",
            "geohash_5": "y0zhe",
            "geohash_4": "y0zh",
            "geohash_3": "y0z",
            "geohash_2": "y0",
            "geohash_1": "y"
        }
    },
    {
        "id": "4q5wefdsaaDWgHb9idh",
        "geolocation": {
            "geohash_9": "y0zhe2t6x",
            "geohash_8": "y0zhe2t6",
            "geohash_7": "y0zhe2t",
            "geohash_6": "y0zhe2",
            "geohash_5": "y0zhe",
            "geohash_4": "y0zh",
            "geohash_3": "y0z",
            "geohash_2": "y0",
            "geohash_1": "y"
        }
    }
]
```

### Other noticeable
After some attempts, the `startAfter` seems to work for the first `orderBy` field `geolocation.geohash_5` instead, not the second field `id` in this case. However, the `startAfter` is called right after the second `orderBy`, which should mean that the pagination should perform against the nearest `orderBy` field, the second field, right?

**Comment by schmidt-sebastian** [comment]
@nilinyi Thanks for contacting us! I think what you are seeing is the expected behavior. I filed a bug with the backend team to improve our error message, which hopefully will make it more clear what is going on.

`startAfter` uses the values in the order specified by the `orderBy`. If you have two orderBys, the mapping is as follows:

```
query
  .orderBy('foo')
  .orderBy('bar')
  .startAfter('fooValue')

// or: 
query
  .orderBy('foo')
  .orderBy('bar')
  .startAfter('fooValue', 'barValue')
```

The error message you are seeing is because the value of "some-doc-id" is not of the same type as "geolocation.geohash_5".

You can find more information here: https://firebase.google.com/docs/firestore/query-data/query-cursors
