### ISSUE TITLE
FR: Ability to run a cloud function forever

### ISSUE THREAD

**Issue by mikemilla** [firebase/firebase-admin-node#592]
Hey team!

Adding a feature request here for the ability to run a cloud function indefinitely. The goal here is to get the ability to continuously listen to stream of external data, perform some logic forever, or something else that will not get cleared by firebase after a certain amount of time.

I am aware that Google Cloud VM instances can do something similar, but it would be very nice to have this feature built into firebase to go along with all the database side logic of apps we build.

Love the product so far!

Thanks,
Mike

**Comment by hiranya911** [comment]
This is what Cloud Functions for Firebase is for: https://firebase.google.com/docs/functions

Also look at the `firebase-functions` package: https://npmjs.com/package/firebase-functions
