### ISSUE TITLE
Disabling sound/vibration on notification does not work

### ISSUE THREAD

**Issue by danmdinu** [firebase/firebase-admin-node#594]
* Operating System version: Android 8.0 (issue reproduces on more devices)
  * Firebase SDK version:  7.0.0
  * Library version: 7.0.0
  * Firebase Product: messaging

### [REQUIRED] Step 3: Describe the problem
I'm trying to disable sound/vibration on specific notifications sent via firebase admin package. I've tried using the sound property described in the documentation here (https://firebase.google.com/docs/cloud-messaging/http-server-ref). There's no info about disabling the sound but reading on stackoverflow people set this property to null or an empty string. That doesn't work for me, sounds/vibrations still happen on every notification. 

#### Relevant Code:

```
export const sendMessage = async () => {
  var message = {
    data: {
      type: NotificationType.MESSAGE,
      fromUserId,
    },
    notification: {
      title: `title`,
      body: 'body'
      sound: '', // tried setting this to: null, empty string, non-existing resource name, removing it completely
    },
  }

  return app.messaging().sendToTopic(topic, message);
```

**Comment by chong-shao** [comment]
Hi @danmdinu , my understanding is that since Android 8 the sound parameter does not control the sound: there's concept of notification channels and each channel's sound and vibration behavior can be configured separately. 

For older versions of Android, when the sound field is null, empty string, non-existing resource name, or missing, the default sound setting on the device will be used. I think one way to override the device's local sound config with your message's sound config is to have a valid silent sound file placed in the device and refer to that in your message request.

**Comment by chong-shao** [comment]
Correction: setting empty string for the sound field before Android 8 should silent the notification.

**Comment by danmdinu** [comment]
thanks @chong-shao for the reply. Is there any example how to use notification channels with firabase admin sdk? 
Thanks!

**Comment by danmdinu** [comment]
I've tried this:

```
export const sendMessage = async () => {
  var message = {
    data: {
      type: NotificationType.MESSAGE,
      fromUserId,
    },
    notification: {
      title: `title`,
      body: 'body'
    },
    android: { 
       notification: { 
         channelId: 'lowprio',
      }    
   }
  }
```

  return app.messaging().sendToTopic(topic, message);

but getting 

> Error: Messaging payload contains an invalid "android" property. Valid properties are "data" and "notification". at FirebaseMessagingError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28) at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28) at new FirebaseMessagingError (/srv/node_modules/firebase-admin/lib/utils/error.js:253:16) at /srv/node_modules/firebase-admin/lib/messaging/messaging.js:800:23 at Array.forEach (<anonymous>) at Messaging.validateMessagingPayload (/srv/node_modules/firebase

**Comment by hiranya911** [comment]
You are using a new-format message with the legacy API (`sendToTopic`). 

Old format message (accepted by methods like `sendToTopic`: https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingPayload.html

New format message (accespted by `send`): https://firebase.google.com/docs/reference/admin/node/admin.messaging.html#message

I don't think the old format messages support specifying channel ID. So you have to use the new format message, and also use the `send()` method.
