### ISSUE TITLE
FR: add image option in notification

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-node#598]
There are new options for image in notification : https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?authuser=0#notification

**Comment by chemidy** [comment]
I already did the feature I have to do a PR

**Comment by rohitjmathew** [comment]
@hiranya911 could you roughly estimate when this feature would be taken up?

**Comment by rohitjmathew** [comment]
Thank you @lahirumaramba @hiranya911 👍
