### ISSUE TITLE
typescript - Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by abhishekp1996** [firebase/firebase-admin-node#599]
* Operating System version: Ubuntu 16.04
  * Firebase SDK version: Not sure
  * Library version: 8.2.0
  * Firebase Product: firebase-admin (auth, database, storage, etc)
  * Typescript version: 3.5.3

### the problem
I am working on typescript project and after installing this library my typescript is not compiling. It shows the following error,

```
node_modules/@google-cloud/common/node_modules/google-auth-library/build/src/auth/oauth2client.d.ts:298:55 - error TS1039: Initializers are not allowed in ambient contexts.

298     protected static readonly GOOGLE_TOKEN_INFO_URL = "https://oauth2.googleapis.com/tokeninfo";
```

#### Steps to reproduce:

1. Install the firebase-admin package
2. Run the code, you get the error.

#### Strange Thing
When I compile this tsc code from an npm script it shows this error.
But when I do just tsc it doesn't show any warning.

Is anyone else facing the same error, or I am doing something wrong?

My typescript version is 3.5.3 and using NodeJS 10.X

**Comment by hiranya911** [comment]
This is an issue that occurs on older versions of TypeScript (older than 3.1). Your environment is probably picking an older version of the TS compiler for some reason.

**Comment by abhishekp1996** [comment]
@hiranya911 Thanks for replying.

I never had Typescript less than 3.3.X. The error first came on my system. I upgraded my typescript version to 3.5.3 and still the error persisted.

Then I moved the code on my colleague's system and again this same error. And after that I moved the code to server, and again there also same error. All of us have typescript 3.5 +

Like I said, the strange thing is that when I do just tsc it works perfectly. But when I do `npm run start` and start script contains `tsc && NODE_ENV=dev node build/app.js` then the error comes it.

**Comment by hiranya911** [comment]
Can you share your package.json?

**Comment by abhishekp1996** [comment]
@hiranya911  Sure. Here are they. (renamed from .json to .txt)

[package.txt](https://github.com/firebase/firebase-admin-node/files/3425179/package.txt)
[tsconfig.txt](https://github.com/firebase/firebase-admin-node/files/3425180/tsconfig.txt)

**Comment by hiranya911** [comment]
As suspected you're using TypeScript v2. Your package.json defines TypeScript version as `"typescript": "^2.8.3",`. This is the compiler that gets picked up by NPM scripts.

**Comment by abhishekp1996** [comment]
@hiranya911 Thank you very much! This saved me. Sorry for me being silly. Have a great day!
