### ISSUE TITLE
Request: Add `registrationToken` to `FirebaseError`-Type

### ISSUE THREAD

**Issue by tobiasmuecksch** [firebase/firebase-admin-node#600]
# Introduction
When sending a push-notification to multiple registrationTokens I process the `MessagingDeviceResult`s. Some results look like this:

```
{
"error":
  {
    "code":"messaging/registration-token-not-registered",
    "message":"The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons. See the error documentation for more details. Remove this registration token and stop using it to send messages."
  }
}
```

As you can see, this error message suggests to ` Remove this registration token and stop using it to send messages.`. The problem is, that this `MessagingDeviceResult` object does not contain any information about **which** of the many tokens is not registered. Therefore I cannot delete it.

# Request
Therefore I request to add the `registrationToken` to the [FirebaseError-Type](https://firebase.google.com/docs/reference/admin/node/admin.FirebaseError.html) (which is the type of the `deviceResult.error` in the demo code below).
Of course it's also necessary to populate this field when the above mentioned `messaging/registration-token-not-registered` error occurs.

# Demo Code

```
const tokens = ['tokenA', 'tokenB'];

const payload = {badge: 1, title: 'Hello', body: 'world'};
const options = {priority: 'high',contentAvailable: false, timeToLive: 60 * 60 * 24};

const admin = FirebaseAdmin.initializeApp({/*config here...*/});

admin.messaging().sendToDevice(deviceTokens, payload, options)
  .then((response) => {

    response.results.forEach((deviceResult) => {
      if (deviceResult.error) {
        console.log('Delivery failed. Showing result:\n', deviceResult);
      }
    });

});
```

# StackOverflow
I have also created a StackOverflow question regarding this topic.
Just FYI:

https://stackoverflow.com/questions/57161160/firebase-admin-get-token-of-failed-notification-delivery-result

**Comment by tobiasmuecksch** [comment]
As you can see in this StackOverflow answer https://stackoverflow.com/a/57161806/1646019 it looks like, FCM returns `MessagingDevicesResponse`s in the same order as the provided registrationTokens. I couldn't find any statement on that in the official docs. If that is **reliably** the case, I'd suggest to add this information to the docs and/or the readme of this repo.

**Comment by hiranya911** [comment]
This is already documented in https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingDevicesResponse.html#results

> results: MessagingDeviceResult[]
An array of MessagingDeviceResult objects representing the status of the processed messages. The objects are listed in the same order as in the request. That is, for each registration token in the request, its result has the same index in this array. If only a single registration token is provided, this array will contain a single object.
