### ISSUE TITLE
[Question] - Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded

### ISSUE THREAD

**Issue by fabiogmartins** [firebase/firebase-admin-node#605]
Hello there,

can you help me?

I need to create a large volume of documents (and sub-collections).

What is the best way to do this process?

I tried to split operations into batches (500 operations) and execute batches via promises.

However, I am getting the error messages:
  - TRANSACTION_TOO_BIG
  - DEADLINE_EXCEEDED

----

I created code to test and exemplify the scenario.

https://github.com/fabiogmartins/test_firebase/blob/master/src/index.ts

It is set to create 10000 documents, when executing it is returning the message: Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded

Tks,
Fabio

**Comment by hiranya911** [comment]
Please use Stackoverflow for usage help and advice.
