### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: documentRef.getCollections is not a function

### ISSUE THREAD

**Issue by congpc** [firebase/firebase-admin-node#606]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.14.5
  * Firebase SDK version: 7.2.1
  * Library version: firebase-tools v'7.2.1' & firebase-admin v'8.3.0' & firebase-functions v'3.2.0'
  * Firebase Product: admin & firestore (auth, database, storage, etc)

#### Steps to reproduce:

- I was used firebase-tools v'7.0.0' & firebase-admin v'7.0.0' & firebase-functions v'2.3.0', then can use method 'getCollections' of DocumentReference. 

- But I was upgrade version firebase-tools v'7.2.1' & firebase-admin v'8.3.0' & firebase-functions v'3.2.0', then I can't use this method and occur this error. 

Did you deprecated this method or not? I still see The documentation at here for this method 'https://firebase.google.com/docs/firestore/query-data/get-data#list_subcollections_of_a_document'

#### Relevant Code:

```
await documentRef.getCollections()
```

**Comment by congpc** [comment]
Oh, I saw you was changed method name 'listCollections', but you don't mention this method is deprecated :(, Ref: (https://googleapis.dev/nodejs/firestore/latest/DocumentReference.html#listCollections)

**Comment by hiranya911** [comment]
This is one of the breaking changes that went out with Firestore 2.0.0 and Admin 8.0.0. But the documentation still shows the old method it seems. @schmidt-sebastian FYA.

**Comment by schmidt-sebastian** [comment]
It looks like we forgot to update our docs. Thanks for catching that!

@samtstern Can you update the code snippets on https://firebase.google.com/docs/firestore/query-data/get-data#list_subcollections_of_a_document to use `listCollections()` for Java and Node?

`getCollections` was deprecated as of v0.18.0.

**Comment by hiranya911** [comment]
I've created an internal bug to track the documentation update. Closing this since there's no action items for this repo.
