### ISSUE TITLE
Cloud Firestore node.js invalid use of type “object” as a Firestore argument

### ISSUE THREAD

**Issue by kiwicopple** [firebase/firebase-admin-node#618]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS
  * Firebase SDK version: 8.3.0
  * Library version: _____
  * Firebase Product: Firestore database
  * Node Version: 10.15.1

#### Steps to reproduce:

This issue (by someone else) describes both the problem and the resolution: https://stackoverflow.com/questions/55065567/cloud-firestore-node-js-invalid-use-of-type-object-as-a-firestore-argument

For prosperity, I am facing the same problem using Node-Red to send a JSON object like this:

```javascript
    payload: {
        text: "hello world",
        createdAt: new Date(),
        user: { _id: 1000 } // This causes the issue
    }
```
Which is then called in the function:

```javascript
this.firestore.collection(col).add(payload)
```

And throws the error:

```javascript
Invalid use of type "object" as a Firestore argument
```

The workaround, as the SO thread explains is to edit
`node_modules/@google-cloud/firestore/build/src/serializer.js`

and change `isPlainObject` to

```
function isPlainObject(input) {
    return util_1.isObject(input);
}
```

----

Is there a more permanent solution that I can use? This is fine on my development environment, but I will need to deploy this to an environment where I cannot edit node_modules

Many thanks

**Comment by schmidt-sebastian** [comment]
@kiwicopple Thanks for sending this over.

Can you run the following on your local machine:


```
const obj = {
	payload: {
        text: "hello world",
        createdAt: new Date(),
        user: { _id: 1000 } // This causes the issue
    }
};

console.log('Node version: ' + process.version);
console.log('Prototype matches: ' + (Object.getPrototypeOf(obj) === Object.prototype));
```

For me this prints:

```
Node version: v10.15.3
Prototype matches: true
```

**Comment by kiwicopple** [comment]
Thanks for the swift response @schmidt-sebastian 

After sleeping on this I think it may be better/easier to solve this within the library using `firebase-admin` (found here: https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Write/WriteNode.js). 

For more context and anyone who reads this, here was my solution

The issue is with the library above is that they do an `Object.assign({}, load)` with the payload, but this doesn't "go deep". So this is the result:

```javascript
// See line 44 of the above where msg.payload = { "foo": "bar", "user": { "_id", 1000 } }
const payload = this.preparePayload(msg.payload)

// Top level has a "prototype"
console.log('Prototype matches: ' + (Object.getPrototypeOf(obj) === Object.prototype));
// -> Prototype matches: true

// Nested objects don't
console.log('Prototype matches: ' + (Object.getPrototypeOf(obj.user) === Object.prototype));
// -> Prototype matches: false 

console.log('Node version: ' + process.version);
//  -> Node version: v8.16.0 - note this was different to my environment a NodeRed was running in a docker container
```
 
And I think the only way to solve it is to call `JSON.parse(JSON.stringify(msg.payload))`

Thanks for the help @schmidt-sebastian  - I'll close this for now
