### ISSUE TITLE
Unable to Proxy Firebase Url

### ISSUE THREAD

**Issue by therynamo** [firebase/firebase-admin-node#63]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOs Sierra 10.12.5
  * Firebase SDK version: shouldn't make much of a difference in this issue
  * Library version: ^5.1.0
  * Firebase Product: `database`

### [REQUIRED] Step 3: Describe the problem

When attempting to use `firebase-admin`s `initializeApp` function, the URL is strictly enforced. I'm sure this is intended, however it is keeping me from proxying the firebase URL to a local server for testing. Example:
```js
firebase.initializeApp({
  credential: firebase.credential.cert(FIREBASE_CREDENTIALS),
  databaseURL: 'http://localhost:4001/https://my.firebaseio.com'
});
```

Resulting in the following error:

```bash
Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com
```

I use [mockyeah](https://github.com/ryanricard/mockyeah/wiki/Service-Snapshot-CLI) for integration testing, which is a nice solution for being able to record snapshots for outgoing requests and their responses. The only caveat is that in order to record the response you have to proxy the URL so that the server can make the call itself. 

The issue isn't necessarily with implementation on either side. My overall question is, would supporting a proxied URL be feasible?

#### Relevant Code:

Listed above.

**Comment by hiranya911** [comment]
This bit of logic actually comes from the firebase-js-sdk: https://github.com/firebase/firebase-js-sdk/blob/master/src/database/core/util/libs/parser.ts

We are simply distributing the minified version of that code with the Admin SDK (at least for now --
 this may change in the future). For now can you report this requirement in that repo?

**Comment by therynamo** [comment]
Sounds great, thanks @hiranya911!

**Comment by hiranya911** [comment]
I will close this ticket, since this is already been tracked in firebase-js-sdk project.
