### ISSUE TITLE
[FR] How to use RealtimeDatabase emulator in sdk admin?

### ISSUE THREAD

**Issue by jhorlima** [firebase/firebase-admin-node#631]
I would like to use the realtimedatabase emulator to test some hooks I am creating without having to submit to production.

**Comment by ryanpbrewster** [comment]
This works for me:
```
const admin = require("firebase-admin");
async function main() {
  admin.initializeApp({ databaseURL: "http://localhost:9000?ns=foo" });

  await admin.database().ref().set(42);

  const root = await admin.database().ref().once("value");
  console.log(root.val());
}

main().catch(err => console.error(err)).then(() => {
  console.log("ok!");
  admin.apps.forEach(app => app.delete());
});
```

**Comment by hiranya911** [comment]
@ryanpbrewster is there any docs page we can point developers to? If not shall we work on putting together one?

**Comment by ryanpbrewster** [comment]
We're actively working on expanding this guide: https://firebase.google.com/docs/emulator-suite

I do not believe it currently has any information on how to connect with the Node.js SDK, but it will shortly.

**Comment by hiranya911** [comment]
Sounds good. Thanks @ryanpbrewster.

I'll close this issue since there's no action item for this repo.
