### ISSUE TITLE
MessagingDeviceResult does not include canonicalRegistrationToken

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-admin-node#637]
Using Firebase admin SDK 6.1.0.

According to the documentation found [here](https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingDeviceResult.html) the response of `messaging.sendToDevice` should contain information about canonical tokens.

A long time ago I've seen this working but it was removed at some point. I don't know if the documentation is outdated or it should be considered a bug in the library.

This data is valuable because if you send messages to say 10 tokens, and 7 were not valid anymore, you can remove those tokens from your database.

Currently I'm relying on the error responses being returned in the same order as the supplied tokens. So if response at index 7 is an error with code `messaging/registration-token-not-registered` I remove the token that I passed to `sendToDevice` at index 7.

But this is an assumption I had to make and I don't know if it is completely safe. In any case this should be documented.

**Comment by hiranya911** [comment]
@chong-shao can you take a look?

@0x80 any reason why you haven't migrated to the new FCM APIs? The new APIs have clear and well-documented semantics IMO. And if something's missing, we can work on it.

**Comment by 0x80** [comment]
@hiranya911 Last time I looked I concluded that there is no modern API to address individual devices. I need to be able to send notifications to hundreds of devices at once, but topics are simply not an option because I send notifications to a sub-selection of users which is calculated dynamically. 

Or did I miss something and the new FCM APIs do include batch sending with registration tokens?

**Comment by hiranya911** [comment]
Check the documentation on `sendAll()` and `sendBatch()` APIs (released several months ago).

**Comment by 0x80** [comment]
@hiranya911 Aha I missed that. I found your article [here](https://medium.com/@hiranya911/firebase-introducing-the-cloud-messaging-batch-apis-in-the-admin-sdk-2a3443c412d3)

It is unclear to me what the benefits are of this new API compared to the old one. I currently send messages in batches of 500. This new API is limited to 100 tokens at a time, so that doesn't appear to be an improvement.

What would be the main reasons to switch to the new API?

**Comment by hiranya911** [comment]
The improvements are in the backend architecture. We can look into increasing the message limit per batch in the future. Also we'd probably deprecate the old API at some point.

**Comment by 0x80** [comment]
Alright, I will plan to update in the near future then. We do get errors occasionally so if the backend architecture is better that would be enough reason to do so.

**Comment by 0x80** [comment]
@hiranya911 I switched to the new API yesterday, but I see no improvements in performance. In fact the v1 legacy API reported an average latency of 63ms and the new FCM API reports 223ms average latency.

Also since I've upgraded firebase-admin from v6 to v8 the messaging API (both legacy and new) seems to be leaking memory. My cloud function responsible for sending the messages is increasingly using more memory and then hits a limit and errors and starts building memory footprint again. The problem only occurs as a result of sending a lot of messages to around 4-5k device tokens (in batches of course). If I cap the maximum at 2k the process seems to remain stable.

I know this is not a proper bug report but I wanted to mention it anyway...

**Comment by 0x80** [comment]
@hiranya911 never mind the latency. I misread the chart. The 223ms was the 99 percentile. The 50 percentile is exactly the same as that of the legacy api.

**Comment by hiranya911** [comment]
@0x80 I don't think there are any measurable performance improvements. What I said was there are improvements in the backend architecture -- resulting in better scalability, load balancing and observability at our end.

**Comment by chong-shao** [comment]
Close the issue for now. Feel free to reopen if there's more to discuss :)
