### ISSUE TITLE
[FR] Documentation for Image option in notifications

### ISSUE THREAD

**Issue by rohitjmathew** [firebase/firebase-admin-node#655]
With the latest v8.6.0, the option to send [images](https://github.com/firebase/firebase-admin-node/pull/648) in notifications has been added. The existing [reference document](https://firebase.google.com/docs/reference/admin/node/admin.messaging.Notification) has not been updated.

Would be great if the documentation could be updated. If this will takes time then do mention how this would work here for the time being as sending an image URL with the option image does not seem to be attaching an image to the notification.

**Comment by hiranya911** [comment]
Option name is `imageUrl`.

https://github.com/firebase/firebase-admin-node/blob/4ae950d895c69442561990195566a90882f24890/src/index.d.ts#L4176-L4179

Our docs are frozen at the moment, so expect the updates to be published in a week or so.

**Comment by rohitjmathew** [comment]
@hiranya911 thanks for the quick response. I have tried with the option imageUrl and still don't seem to be getting an image in my notification on my device. This is my notification payload:

```
"notification": {
  "title": "Notification Testing",
  "body": "Hello! This is a test message",
  "imageUrl": "https://lh3.googleusercontent.com/17Yiswf2USMLEi8au4qTVThQrIIZ3dozKvn5B67IE78HMJr03VSe3O1CoiU9hEI2Vw"
}
```
I have checked that the image is a PNG and is less than 1 MB as per the requirements present in the [API documentation](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#notification). Could you help me out with what could be a possible reason for why the image is not getting attached.

**Comment by hiranya911** [comment]
Can you share a complete code snippet? With the full message and the send API call.

**Comment by hiranya911** [comment]
Can you also log the message to the console and share the output?

```
console.log(message);
```

Feel free to redact any sensitive parts. @lahirumaramba did some testing where he verified the `imageUrl` is being correctly sent to the FCM service. So this might be a backend issue.

**Comment by rohitjmathew** [comment]
Sure. Here is the message object that we send to FCM:
```
{ 
    name: 'APP_NOTIFICATION_TEST',
    notification: {
        title: 'Testing App Notification',
        body: 'Hi User, Welcome to ****! This is a test message.',
        imageUrl: 'https://lh3.googleusercontent.com/17Yiswf2USMLEi8au4qTVThQrIIZ3dozKvn5B67IE78HMJr03VSe3O1CoiU9hEI2Vw' 
    },
    data: {},
    android: { 
        priority: 'NORMAL',
        ttl: 86400000,
        fcm_options: { 
            analytics_label: 'APP_NOTIFICATION_TEST' 
        } 
    },
    token: '***FIREBASE_TOKEN***' 
}
```

**Comment by hiranya911** [comment]
I just verified again, that the SDK is sending the right message to the backend:

```
{"message":{"notification":{"title":"Testing App Notification","body":"Hi User, Welcome to ****! This is a test message.","image":"https://lh3.googleusercontent.com/17Yiswf2USMLEi8au4qTVThQrIIZ3dozKvn5B67IE78HMJr03VSe3O1CoiU9hEI2Vw"},"data":{},"android":{"priority":"NORMAL","ttl":"86400s","fcm_options":{"analytics_label":"APP_NOTIFICATION_TEST"}},"topic":"foo"}}
```

That looks good. @rohitjmathew please verify you're indeed using v8.6.0 of the Admin SDK. Older versions will silently drop the imageUrl parameter altogether.

@chong-shao @lahirumaramba can you folks take a look and see what's going on? (we might need to move this thread to a support request or an internal bug)

**Comment by rohitjmathew** [comment]
Yes, I have checked that I'm using v8.6.0 and have also deleted node_modules and tried again. 

Also attaching the firebase-admin dependency from package.json for my service :
```
"firebase-admin": "^8.6.0",
```

**Comment by chong-shao** [comment]
Hi Rohit, to investigate the issue on our backend, I would suggest filing a support ticket to Firebase. From there you can share the information including the token and message id necessary for the debugging. Thanks!

**Comment by fullflash** [comment]
i receive image when using **image** in the payload not **imageUrl** documentation is total mess.

**Comment by hiranya911** [comment]
If you're using the Node.js SDK, the field is called `imageUrl`: https://github.com/firebase/firebase-admin-node/blob/6bcffa2fdca8ee9b9fb49a0109ddc72f4f6d4c2e/src/messaging/index.ts#L99-L102

If you're using the REST API, the field is called `image`: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification

**Comment by fullflash** [comment]
i am using firebase admin sdk and yes in docs and js property is called imageUrl
but no image is displayed only when using image instead of imageUrl.

```
const payload = {
        notification: {
            title: pushTitle,
            body: pushBodyMsg,
            mutableContent:"true",
            contentAvailable:"true",
            image:pushImgUrl,

        },

    };
firebaseAdminSdk.messaging().sendToTopic(topicName,payload);
```

**Comment by hiranya911** [comment]
This issue is about the new v1 API. You're using the [legacy API](https://firebase.google.com/docs/cloud-messaging/send-message#adminSDK-legacy-send-methods). In the legacy API there's no documented `image` or `imageUrl` property. But the chances are the backend REST API accepts an `image` property just like the v1 REST API.

https://firebase.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload
