### ISSUE TITLE
Issue with viewing logs

### ISSUE THREAD

**Issue by momoDragon** [firebase/firebase-admin-node#656]
I am not able to view the whole functions log when using google chrome. 
But i am able to view it only when using firefox. 

Issue occurs when using mac and chrome 
Issue does not occur when using windows with chrome

*image from chrome*
<img width="1026" alt="Screenshot 2019-09-19 at 11 37 47 PM" src="https://user-images.githubusercontent.com/40727575/65259447-404d4200-db37-11e9-841e-45ff3b95bb25.png">
as u can see there is no drop down to see the full log

*image from firefox*
<img width="1071" alt="Screenshot 2019-09-19 at 11 38 11 PM" src="https://user-images.githubusercontent.com/40727575/65259486-522ee500-db37-11e9-8416-93fb5adb3d77.png">
as u can see there is a dropdown to click to view the full log

**Comment by hiranya911** [comment]
Please file a ticket at https://firebase.google.com/support/troubleshooter/report/bugs/

This repo has nothing to do with  Functions or the Firebase Console.
