### ISSUE TITLE
Messaging: Notifications not delivered to iOS

### ISSUE THREAD

**Issue by tamngonesv030** [firebase/firebase-admin-node#663]
I using Firebase Admin sdk for dotnet.
I send notification to Android is ok but I can't send notification to iOS.

var mess = new Message()
            {
                Token = token,
                //Notification = new Notification()
                //{
                //    Body = notificationBody,
                //    Title = title
                //},
                Apns = new ApnsConfig()
                {
                    Headers = new Dictionary<string,string>(){},
                    Aps = new Aps()
                    {
                        ContentAvailable = false,
                        Badge = 1,
                        Sound = "default",
                        Alert = new ApsAlert() { 
                        Title = "test",
                        Body = "test body",
                        ActionLocKey = "loc-key",
                        },
                    },

                },
            };
            mess.Apns.CustomData = new Dictionary<string, object>()

**Comment by schmidt-sebastian** [comment]
@tamngonesv030 Thanks for filing this issue. Can you let us know what version of our products you are using?

There is likely a device-specific issue here, but since this is specific to In-App Messaging, I will have to hand you over to that team.

**Comment by hiranya911** [comment]
I think this issue is reported in the wrong repo. Description mentions .NET. I'm going to close this. @tamngonesv030 please report in the .NET SDK repo or better yet -- file a support request. This is not the kind of issue that can be debugged and fixed at the SDK code.

https://firebase.google.com/support

**Comment by tamngonesv030** [comment]
I'm using firebase admin SDK server-side .NET version 1.9.0 to push notification to client (iOS/Android)
I created message push to android then it's ok but when I create a message to push iOS client then it don't. I could not find the cause of the error from the error message:

A first chance exception of type 'FirebaseAdmin.Messaging.FirebaseMessagingException' occurred in mscorlib.dll
