### ISSUE TITLE
Wanting to create a system admin page for my Firebase project, is there any way I can break the rules and use the firebase-admin SDK on a client side browser? Or will all my efforts to workaround the warnings be for nothing?

### ISSUE THREAD

**Issue by jamie-chapman** [firebase/firebase-admin-node#664]

**Comment by jamie-chapman** [comment]
N.B The the problem I ran into was using the firebase/database SDK after successfully initialising with the admin initializeApp function, I got the error "TypeError: rtdb.initStandalone is not a function".

**Comment by hiranya911** [comment]
Use Stackoverflow for questions.
