### ISSUE TITLE
TypeError: rtdb.initStandalone is not a function

### ISSUE THREAD

**Issue by fsproru** [firebase/firebase-admin-node#685]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Mojave, Version 10.14.6
  * Firebase SDK version: firebase-admin@8.3.0
  * Firebase Product: database
  * Node.js version: v10.15.2
  * NPM version: 6.4.1

#### Steps to reproduce:

I'm including `firebase-admin` SDK into my Electron + Vue.js app generated with Vue CLI. The npm gets included fine and I can import it no problem. Once I make a call to read a value from the database like this

```
database().ref(reference).child(child).once(valueKey)).val()
```

I get a runtime error like this one.

```
TypeError: rtdb.initStandalone is not a function
```

I found this issue on StackOverflow where they recommend to set `resolve.mainFiles` to `['main', 'module']`. We currently don't have `resolve.mainFiles` set to anything. I tried setting it to `['main', 'module']` and it causes even more issues with the rest of our npms included in the project.

Is there a way to include `firebase-admin` npm without depending on `resolve.mainFiles`? Perhaps as a standalone package/

#### Relevant Code:

```
database().ref(reference).child(child).once(valueKey)).val()
```

**Comment by hiranya911** [comment]
Looks like `resolve.mainFiles` is some Webpack configuration? AFAIK firebase-admin cannot be used with Webpack (at least not easily). Also Webpack is usually used with front-end applications. Since you're using Electron and Vue.js, I get the feeling that you're trying to use firebase-admin in a front-end application. That's not supported. It can only be used in backend Node.js environments.

**Comment by saumyasinghal747** [comment]
I don't understand - Electron is used for building native desktop applications and has a working, valid backend Node server. I'm using the exact same tools and I'm trying to include firebase-admin in my backend code, using Vue-CLI's electron builder plugin. I'm getting the above error. Can anyone help me? Thank you!
