### ISSUE TITLE
Cannot set custom claim in Firebase Admin

### ISSUE THREAD

**Issue by rlee1990** [firebase/firebase-admin-node#687]
When I run the setCustomUserClaims from inside a cloud function it never sets the claim.
Here is the code:
`exports.addAccess = functions.https.onCall((data, context) => {
    const isAdmin = data.admin;
    const isStaff = data.staff;
    const email = data.email;

    return admin.auth().getUserByEmail(email).then((user) => {
        return admin.auth().setCustomUserClaims(user.uid, {
            admin: isAdmin,
            staff: isStaff,
        });
    }).then(() => {
        return admin.auth().getUserByEmail(email).then((u) => {
            console.log(u.customClaims);
        });
    }).catch((error) => {
            console.log('Error adding claims: ', error);
        });
})`

**Comment by hiranya911** [comment]
Code looks fine and also works fine for me.

```
const admin = require('firebase-admin');

const email = '...';

admin.initializeApp();
return admin.auth().getUserByEmail(email).then((user) => {
  return admin.auth().setCustomUserClaims(user.uid, {
      admin: true,
      staff: false,
  });
}).then(() => {
  return admin.auth().getUserByEmail(email).then((u) => {
      console.log(u.customClaims);
  });
}).catch((error) => {
      console.log('Error adding claims: ', error);
});
```

Output:
```
{ admin: true, staff: false }
```

Have you checked the Functions log output? Specifically, how did you determine that it is not working?

**Comment by rlee1990** [comment]
@hiranya911 this is what I get in the output:
`{}`

**Comment by rlee1990** [comment]
@hiranya911 I shouldn't have to be on the blaze plan for this right?

**Comment by hiranya911** [comment]
>  I shouldn't have to be on the blaze plan for this right?

No you don't.

Can you also log the following:

```
console.log({
        admin: isAdmin,
        staff: isStaff,
});
```

**Comment by rlee1990** [comment]
@hiranya911 Thanks for that they were undefined had a typo on getting that data. All works now
