### ISSUE TITLE
getSignedUrl() not working with sub-directories

### ISSUE THREAD

**Issue by herrfugbaum** [firebase/firebase-admin-node#698]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: WSL 1 running Ubuntu 18.04 on Windows 10 Pro 1903
  * Firebase SDK version: 8.6.1
  * Firebase Product: storage
  * Node.js version: 12.6.0
  * ~~NPM~~ Yarn version: 1.17.3

#### Steps to reproduce:

It is not possible to get a valid signed URL, if the uploaded file is inside another directory than the root directory of the bucket,
or - in other words - if the filename that you pass starts with `mydirectory/`. Or, most likely, contains a `/` anywhere.

#### Relevant Code:

```typescript
const result = await bucket.upload('file.txt', {
  destination: 'mydirectory/file.txt',
});
```

```typescript
const signingOptions = {
  version: "v4",
  action: "read",
  expires: Date.now() + 15 * 60 * 1000,
};

const [url] = await bucketReference
  .file(filename)
  .getSignedUrl(signingOptions);

console.log(url);
```

Open the logged link in a browser and get:

```xml
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>
  The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
  </Message>
  ...
</Error>
```

If you upload the file to the root of the bucket everything will work as expected.
Maybe it has something to do with the signing of the `/` (literal `/` vs encoded `%2F`) character.

In the gsutil docs for the [signurl command](https://cloud.google.com/storage/docs/gsutil/commands/signurl) you can read:
> Note: Unlike the gsutil ls command, the signurl command does not support operations on sub-directories. For example, if you run the command: [...]

However, I couldn't find the same info for the node.js SDK. So, is this expected behavior or a bug?

**Comment by hiranya911** [comment]
Please report at https://github.com/googleapis/nodejs-storage, where the Storage Node.js client is developed.
