### ISSUE TITLE
[FR] Request for `url`-like prop/method on files uploaded to storage

### ISSUE THREAD

**Issue by galki** [firebase/firebase-admin-node#701]
**Is your feature request related to a problem? Please describe.**
I'd like to get the URL of an image after saving it to Storage, so I can save it in Firestore and display the image later. Right now there is `getSignedUrl()` and `metadata.mediaLink` (for downloading) but apparently we can view images with the following URLs:

_Public files_
> https://storage.googleapis.com/[BUCKET_NAME]/[IMAGE_PATH]

_Files viewable with access key_
> https://firebasestorage.googleapis.com/v0/b/[BUCKET_NAME]/o/[IMAGE_PATH]?alt=media&token=[ACCESS_TOKEN]

But there is no property or method that returns these URLs. It seems like people are just stitching them together in the understanding that this is a hack that might break in the future if the actual URL format happens to change at some point.

**Describe the solution you'd like**
I'd like a property or method to exist on a bucket file instance that would return either of the above mentioned URLs depending on whether the file is public or not, or whether an access token exists in the metadata.

**Describe alternatives you've considered**
Stitching the URL together by myself.

**Comment by hiranya911** [comment]
Firebase Storage access keys and the associated URL format is not really supported in the server-side GCS client. But the GCS team might be interested in exposing the other public URL format. But please report this at https://github.com/googleapis/nodejs-storage. That's where the respective code and the team can be found.

**Comment by galki** [comment]
Thank you. The new issue is at https://github.com/googleapis/nodejs-storage/issues/931
