### ISSUE TITLE
Getting: Firebase service named 'database' already registered error, even tho I am not importing firebase/database anywhere.

### ISSUE THREAD

**Issue by jousi592** [firebase/firebase-admin-node#713]
**Describe your environment**

  * Operating System version: Mac OS 10.15.1
  * Firebase SDK version: 8.8.0
  * Firebase Product: database (auth, database, storage, etc)
  * Node.js version: 8.15.1
  * NPM version: 6.9.0
  * "firebase": "7.5.0",
  * "firebase-admin": "8.8.0",
  * "firebase-functions": "3.3.0",

**Describe the problem**

#### Steps to reproduce:

When I call `firebase deploy --only functions`, it stops on step `functions: preparing functions directory for uploading...` and throws:
`database: Firebase: Firebase service named 'database' already registered (app/duplicate-service).`

This is the where the error is found:
`at error (....../functions/node_modules/@firebase/app/dist/index.node.cjs.js:41:21)`

#### Relevant Code:

The only way I reference `database` is through:
```
// Init firebase access to DB
const firebase_admin = require("firebase-admin");

// Get a database reference
const firebase_db = firebase_admin.database();
```
I dont import or require `"firebase/database"` anywhere in my code.

**Comment by hiranya911** [comment]
Can you provide a minimal repro for us to try out?

**Comment by jousi592** [comment]
Yes I was able to pin down the code causing this error, but still havent managed to remedy the situation.

Here is the code:

```
const firebase = require("firebase"); // -------- This seems to be causing the problem
const { firebase_config, project_name, id_of_project } = require("../config")

// Initialize Firebase
const config = firebase_config
const app = firebase.initializeApp(config);

const log_in_user = ({ body }, res) => {
  app
    .auth()
    .signInWithEmailAndPassword(body.email, body.password)
    .then(() => {
      res.send([
        true,
        config,
        `user_logged_in_to_admin=${project_name}-${id_of_project};`
      ])
    })
    .catch(error => {
      if (error.code === "auth/wrong-password") {
        console.log("1: Wrong password.");
      } else {
        console.log("2:",error.message);
      }
      res.send([false])
    });
}

module.exports = log_in_user
```

I have tried using `firebase/authentification` directly, but then I cant `initializeApp(config)` to prepare for the sing in call:
```
.auth()
.signInWithEmailAndPassword(body.email, body.password)
```

So I am a bit lost as to how to structure the code to get it working again.

**Comment by hiranya911** [comment]
Ok, so this is because you're trying to use both `firebase` and `firebase-admin` together. That's not really a recommended usage pattern. Those two packages are designed for different environments, targeting very different use cases.

If you insist on using these 2 packages together you will probably have to install `@firebase/app` and `@firebase/auth` instead of the aggregate `firebase` package. Otherwise you run the risk of initializing the database module twice.

**Comment by jousi592** [comment]
@hiranya911 

So how do you suggest I structure it using `@firebase/app` and `@firebase/auth`?

I tried:
```
const firebase_auth = require("@firebase/auth");
const firebase_app = require("@firebase/app");
const { firebase_config, project_name, id_of_project } = require("../config")

// Initialize Firebase
firebase_app.initializeApp(firebase_config);

const log_in_user = ({ body }, res) => {
  firebase_auth
    .signInWithEmailAndPassword(body.email, body.password)
    .then(() => {
      res.send([
        true,
        firebase_config,
        `user_logged_in_to_admin=${project_name}-${id_of_project};`
      ])
    })
    .catch(error => {
      if (error.code === "auth/wrong-password") {
        console.log("1: Wrong password.");
      } else {
        console.log("2:",error.message);
      }
      res.send([false])
    });
}

module.exports = log_in_user
```

But that doesnt work unfortunately, so I dont understand how to do it using the separately imported modules.

**Comment by jousi592** [comment]
Luckily my friend directed me and told me I just had to `require` the `firebase/auth` and not assign or use it.

So this configuration worked:
```
const firebase = require("firebase/app");
require("firebase/auth");
const { firebase_config, project_name, id_of_project } = require("../config")

// Initialize Firebase
const config = firebase_config
const app = firebase.initializeApp(config);

const log_in_user = ({ body }, res) => {
  app
    .auth()
    .signInWithEmailAndPassword(body.email, body.password)
    .then(() => {
      res.send([
        true,
        config,
        `user_logged_in_to_admin=${project_name}-${id_of_project};`
      ])
    })
    .catch(error => {
      if (error.code === "auth/wrong-password") {
        console.log("1: Wrong password.");
      } else {
        console.log("2:",error.message);
      }
      res.send([false])
    });
}

module.exports = log_in_user

```
