### ISSUE TITLE
Cannot `initializeApp` on local machine: ENOTFOUND metadata.google.internal

### ISSUE THREAD

**Issue by Domiii** [firebase/firebase-admin-node#745]
NOTE: I am coming over from [this issue on `firebase-tools`](https://github.com/firebase/firebase-tools/issues/1708) (because it was the first match on Google, despite being a problem with `firebase-admin`).

## Environment
* `firebase-admin`: `v8.9.0`

## Problem

I have followed [this reference](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) to initialize my app:

`admin.initializeApp({ credential: admin.credential.applicationDefault(), ... })`

(actually omitting `credential` entirely has the exact same result), and fail with following error when running on local machine (not in cloud):

> Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal. Error code: ENOTFOUND"

## metadata.google.internal?

Here is the oddest part: it is trying to get a token from some `metadata.google.internal` domain which sounds like it can only work in a Google Cloud Function? Is local development not supported anymore?

Either way; I debugged a little, and found that it happens in `node_modules/firebase-admin/lib/auth/credential.js`

which unconditionally wants to connect to an **internal** URL to get an access token:

```js
var GOOGLE_METADATA_SERVICE_HOST = 'metadata.google.internal';
// ...
  public getAccessToken(): Promise<GoogleOAuthAccessToken> {
    const request: HttpRequestConfig = {
      method: 'GET',
      url: `http://${GOOGLE_METADATA_SERVICE_HOST}${GOOGLE_METADATA_SERVICE_PATH}`,
      headers: {
        'Metadata-Flavor': 'Google',
      },
      httpAgent: this.httpAgent,
    };
    return requestAccessToken(this.httpClient, request);
  }
```

Link to relevant source code: [[1](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/credential.ts#L382)] [[2](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/credential.ts#L31)]

**Comment by hiranya911** [comment]
You need to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to use app default credentials locally. The documentation page you've linked states this:

> After creating a service account, you have two choices for providing the credentials to your application. You can either set the GOOGLE_APPLICATION_CREDENTIALS environment variable explicitly, or you can pass the path to the service account key in code.

**Comment by Domiii** [comment]
Indeed, I initialize `dotenv` correctly. Tested it in another file where things worked out, but did not double check configuration options right before calling `initializeApp`.

Thanks!

**Comment by Leandro-Albano** [comment]
I scratched my head on this one and turns out the following does not work:

```
process.env.FIREBASE_AUTH_EMULATOR_HOST = 'http://localhost:5001';
process.env.FIREBASE_AUTH_EMULATOR_HOST = 'localhost:5001';
```

but this does:

`127.0.0.1:5001`
