### ISSUE TITLE
publish the types to npm registry [FR]

### ISSUE THREAD

**Issue by buddudevelopers** [firebase/firebase-admin-node#749]
**Is your feature request related to a problem? Please describe.**
To use libraries with typescript, we need the types in npm registry
but typing `npm install --save @types/firebase-admin` produces an error 
`npm ERR! 404 '@types/firebase-admin@latest' is not in the npm registry`
**Describe the solution you'd like**
I would like firebase-admin types to be available in npm registry for ease of use with typescript
**Describe alternatives you've considered**
Generating the types my self `npx typings install github:firebase/firebase-admin-node/src/index.d.ts
`Not ideal because its probably the wrong version

**Comment by hiranya911** [comment]
`firebase-admin` ships with types included. You don't need a separate `@types/*` package to use it with TypeScript.
