### ISSUE TITLE
[Firestore] 8.9.0 version extremely slow with firestore emulator

### ISSUE THREAD

**Issue by diginikkari** [firebase/firebase-admin-node#750]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version:  MacOS 10.15.2
  * Firebase SDK version: 7.6.1
  * Firebase Product: Firestore / firebase-admin 8.9.0
  * Node.js version: 12.4.0
  * NPM version: 6.13.4

### [REQUIRED] Step 3: Describe the problem

firebase admin firestore calls are extremely slow compared to version 8.8.0. when running against firestore emulator. There are also random timeouts.  Unfortunately I can't point any specific call. I have integration test with 190 tests with many firebase admin firestore calls. With version 8.8.0 my tests took 22s to run and with 8.9.0 it takes 433s (with many tests errored because timeouts).

This is could be related to #748, but I have not found any difference when running older version of @google/firestore. Only package I have noticed affecting this is firebase-admin.

#### Steps to reproduce:

Upgrade firebase-admin to version 8.9.0 and run many calls against local firestore emulator.

#### Logs from couple test files:

fast, firebase-admin@8.8.0 (8 seconds) [firestore.8.8.0.log](https://github.com/firebase/firebase-admin-node/files/4026098/firestore.8.8.0.log)
slow, firebase-admin@8.9.0 (74 seconds) [firestore.8.9.0.log](https://github.com/firebase/firebase-admin-node/files/4026100/firestore.8.9.0.log)

**Comment by schmidt-sebastian** [comment]
This has been fixed and released as Firestore 3.3.1.
