### ISSUE TITLE
***.iam.gserviceaccount.com does not have storage.objects.delete access to ***.appspot.com/***

### ISSUE THREAD

**Issue by gabrielmoncea** [firebase/firebase-admin-node#757]
### Environment

  * Operating System version: macOS Catalina 10.15.2
  * Firebase SDK version: ^8.9.0
  * Firebase Product: Storage
  * Node.js version: 10.16.3
  * NPM version: 6.11.3

#### Steps to reproduce:

I'm initialising the app with a new service account and when I'm trying to upload a file on firebase storage I get this error that the service account doesn't have access to it.

The problem is that the email specified from the error comes from an old service account.

#### Relevant Code:

```

const serviceAccount = require('./adminsdk.json');
const admin = require("firebase-admin");

const app = admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    storageBucket: 'gs://bucket.appspot.com'
}, 'appname' );

const bucket = admin.storage(app).bucket();
const uuid = uuidv4()

try {
  await bucket.upload(path, {
    metadata: {
      metadata: {
        firebaseStorageDownloadTokens: uuid
      }
    }
  })
} catch(error) {
  console.log(error)
}

```

**Comment by hiranya911** [comment]
I think this is because of the way you've specified your `storageBucket` option. It should just be the name of the bucket without any prefixes like `gs://`.

**Comment by gabrielmoncea** [comment]
@hiranya911 the [documentation](https://firebase.google.com/docs/storage/admin/start) says what you said, but I have the same script on another branch for a different project and it works just fine.

**Comment by hiranya911** [comment]
Looks like the new versions of `@google-cloud/storage` does indeed allow prefixes. In that case we can't really speculate why your code works in one environment/project but not the other. There are couple of strange behaviors reported here:

1. Application complaining about the `storage.objects.delete` permission while your code only has `upload()`.
2. The error message mentioning an old service account?

It sounds like either you're not invoking the code that you think you're, or your code is not loading the service account that you intended to. Either way, this doesn't look like a bug in the API, as this is a common use case that normally works. I'd recommend carefully going through your code (possibly with additional log statements) to verify all assumptions. If nothing comes out of it please [contact support](https://firebase.google.com/support), and provide your project details (bucket name and service account) so we can look into what's going on.

**Comment by gabrielmoncea** [comment]
@hiranya911 is there anything I can do to make if work again? Like reseting the project or something else

**Comment by timhj** [comment]
The same issue is happening for me on 'copy' from one bucket to the next. Using the latest version of the PHP cloud-storage API.
`
        $training_version = $training_bucket->object($gcs_relative_url);
    	if(!$training_version->exists()){
    		// if a version of the file doesn't exist, copy it across to training bucket.
    		$crops_bucket = $gcs_client->bucket($this->bucket);
    		$cropped_version = $crops_bucket->object($gcs_relative_url);
			$cropped_version->copy($training_bucket_name); // copy it across to training bucket.
`

Error message is: 
`Google\Cloud\Core\Exception\ServiceException [ 403 ]: { "error": { "code": 403, "message": "XXX@XXXX.iam.gserviceaccount.com does not have storage.objects.delete access to BUCKET_NAME/pdfs/2/8/7/2874/34-34-19.jpg.", "errors": [ { "message": "XXX@XXXX.iam.gserviceaccount.com does not have storage.objects.delete access to BUCKET_NAME/pdfs/2/8/7/2874/34-34-19.jpg.", "domain": "global", "reason": "forbidden" } ] } }`	

Debugging the call made to the API show that all info is correct:
### Google\Cloud\Storage\Connection\Rest->send( arguments )
`
0 | string(7) "objects"
1 | string(4) "copy"
2 | array(4) (  
"destinationBucket" => string(22) "CORRECT_DEST_BUCKET"     
"destinationObject" => string(28) "pdfs/2/8/7/2874/34-34-19.jpg"     
"sourceBucket" => string(7) "CORRECT_SRC_BUCKET"     
"sourceObject" => string(28) "pdfs/2/8/7/2874/34-34-19.jpg" )`

Why does a copy request require the delete permission?
