### ISSUE TITLE
The "timestampsInSnapshots" option for Firestore ignored when set to false on latest version

### ISSUE THREAD

**Issue by Dygerati** [firebase/firebase-admin-node#758]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 19.04
  * Firebase SDK version: 8.7.0
  * Firebase Product: firestore
  * Node.js version: 12.13.1
  * NPM version: 6.12.1

#### Steps to reproduce:

The "timestampsInSnapshots" setting is simply ignored when set to false. I understand this is deprecated, but it should still work?

#### Relevant Code:

```
const admin = require('firebase-admin');

admin.initializeApp({
   ...
});

admin.firestore().settings({
   timestampsInSnapshots: false
});

(async () => {
   const doc = await admin
      .firestore()
      .collection('testcollection')
      .doc('1CJrlVFg9lBKKM7MmhjG')
      .get();

   console.log(doc.data().createdAt);
})();

// Timestamp { _seconds: 1546467747, _nanoseconds: 0 }

```

**Comment by hiranya911** [comment]
No it's no longer supported. It was removed with Firestore v3.0.0

https://github.com/googleapis/nodejs-firestore/releases/tag/v3.0.0

**Comment by Dygerati** [comment]
Ah, that being the case I'd encourage updating the documentation:
https://firebase.google.com/docs/reference/js/firebase.firestore.Settings

**Comment by Badbreaddead** [comment]
What is the latest version which supports timestampsInSnapshots ?

**Comment by hiranya911** [comment]
@Badbreaddead v8.8.0 was the last release to depend on Firestore v2. So I'd expect that to be last release to support the above option.
