### ISSUE TITLE
[cloud] SenderId mismatch

### ISSUE THREAD

**Issue by YajanaRao** [firebase/firebase-admin-node#783]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS 10.15.3 (19D76)
  * Firebase SDK version: 8.9.2
  * Firebase Product:  messaging (auth, database, storage, etc)
  * Node.js version: 12
  * NPM version: 6.13

### [REQUIRED] Step 3: Describe the problem
`errorInfo: {
    code: 'messaging/mismatched-credential',
    message: 'SenderId mismatch'
  },`

#### Steps to reproduce:

1. Use key json file from service account tab
2. Use token from cloud messaging tab

#### Relevant Code:
![Screenshot 2020-02-11 at 2 15 41 PM](https://user-images.githubusercontent.com/38914337/74221898-20cad780-4cd9-11ea-9210-026cb1747279.png)

**Comment by hiranya911** [comment]
The token has to be generated using one of the Firebase client SDKs on a client device. There are no tokens in the console that you can send notifications to.
