### ISSUE TITLE
Can't change an user's email address to an address previously used by a deleted account

### ISSUE THREAD

**Issue by red42** [firebase/firebase-admin-node#786]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 18.04.4 LTS
  * Firebase SDK version: firebase-admin 8.9.0
  * Firebase Product: auth / admin
  * Node.js version: 11.12.0
  * NPM version: 6.13.2

### [REQUIRED] Step 3: Describe the problem

I'm trying to change a user's email address to the email address of a previously deleted user's, but that fails with the following error:
```
   { code: 'auth/email-already-exists',
     message: "The email is already in use as another user's initial email." }
```

This seems to be the same as described here - https://github.com/firebase/firebase-js-sdk/issues/1905#issuecomment-584448170

I understand this should be the behavior for existing accounts, but a deleted account should free the email address to be used by another account.

#### Steps to reproduce:

The deleted user was using Google authentication. The user I'm trying to update is using email/password.

The user was deleted using the Firebase console.

Multiple accounts per email address is enabled.

#### Relevant Code:

```
admin.auth().updateUser(USERID, {
  email: EMAIL_ADDRESS
})
.then((result) => {
      console.log(result);
      process.exit();
})
.catch((error) => {
  console.log("ERROR:\n", error);
  process.exit(1);
});
  
```

**Comment by bojeil-google** [comment]
I replied to the other bug and file an internal issue about this. I will close this one as it is a duplicate.
