### ISSUE TITLE
[FR] Scope firebase-admin using `databaseAuthVariableOverride` or similar

### ISSUE THREAD

**Issue by alexpchin** [firebase/firebase-admin-node#787]
This is more of a question rather than a feature request...

I am unsure why it's not more commonplace to "scope" the firebase admin using a UID of a logged-in user so that you can use the same client-side rules on the server-side? It seems odd to be able to implement one set of rules for the clientside but then have to perform lots more lookups if you move the logic to the server-side?

It seems like it could potentially be achieved with: `databaseAuthVariableOverride`

**End goal:** To be able to implement firestore rules on the server using the same rules file as is used on the client?

**Comment by hiranya911** [comment]
This has several questions rolled into it. I'll try my best to address them all.

1. Our server-side SDKs do not have a concept of a "logged in user". They are used to implement machine-to-machine interactions at scale, and both Firestore and the Real-time Database (RTDB) do not enforce any security rules on the requests coming from these SDKs. This is also why we call them "Admin SDKs". They essentially give you "admin" access to your project's resources, without taking any security rules into consideration. Both Firestore and RTDB consider the code written using the Admin SDK to be trusted, as opposed to the end-user apps written using our client SDKs, which are considered untrusted.

2. Having said that, sometimes it is useful to be able to enforce security rules on the requests made by the Admin SDKs. RTDB supports this today via `databaseAuthVariableOverride`. Set the override to something like `{uid: 'alice'}`, and RTDB will pretend as if those Admin SDK requests were made by a logged in user with the UID "alice". Rules will be enforced as usual in this case.

3. Firestore does not provide any such feature as of today. So the thing you're trying to achieve is simply not possible (see https://firebase.google.com/docs/firestore/security/overview). Although this is a somewhat popular feature request. I'd advise you to join the line by reporting your requirement at https://firebase.google.com/support. This is not something that can be supported in the SDK (i.e. this GitHub repo). It needs to be first supported in the core Firestore database product.

**Comment by alexpchin** [comment]
Thanks for the comprehensive response. This question came about because I wanted to move logic from my clientside to the serverside to separate concerns. However, this obviously means that the rules do not work.

Would the official advice from Firebase be to keep logic on the clientside?

**Comment by hiranya911** [comment]
Yes. Developing serverless, client-side apps is where Firebase really shines. Whenever appropriate, you should complement your client-side logic with some trusted server-side code running in your own servers or in a managed cloud environment like Cloud Functions. This is where the Admin SDKs come in. But they are meant to complement the client-side logic -- not replace them.

Check out the following post for some tips and examples on using Admin SDKs, client SDKs and security rules together: https://firebase.googleblog.com/2019/03/firebase-security-rules-admin-sdk-tips.html
