### ISSUE TITLE
Value of FirebaseAppError.code is unexpected

### ISSUE THREAD

**Issue by justinrosenthal** [firebase/firebase-admin-node#80]
In the `FirebaseAppError` constructor, it prepends the string `app/` to the error code before calling `super`.  This makes it very difficult to look at an instance of `FirebaseAppError` at runtime and determine which error code it has.

For example:
```js
let err = new FirebaseAppError(AppErrorCodes.NETWORK_ERROR, "ECONNRESET");
if (err.code === AppErrorCodes.NETWORK_ERROR) {
  // ...
} else {
  // Unexpectedly we end up here because err.code === ('app/' + AppErrorCodes.NETWORK_ERROR)
}
```

Is there a suggestion for how to deal with this? I couldn't find an example elsewhere in the codebase.

**Comment by hiranya911** [comment]
Can't we rely on `FirebaseAppError` to always behave this way? If so we can test for equality with `'app/' + code` or at least check for `err.code.endsWith(code)`. I'm not sure why we do this error code prefixing business, but it seems to be the convention followed in the whole SDK (See `FirebaseAuthError` and `FirebaseMessagingError` for example).

**Comment by justinrosenthal** [comment]
Indeed there are ways to check as long as you know the inner workings of `FirebaseAppError` (though you'd prefer not to litter the magic string `/app` all over the codebase), but for the uninitiated developer, it's not obvious why my code above doesn't work.

Before I went ahead and implemented a conditional other than `=== <code>` I wanted to ask what the maintainers suggest.

**Comment by hiranya911** [comment]
I'm going to resolve this since `PrefixedFirebaseError` introduced in #85 makes error code checking easier.
