### ISSUE TITLE
admin.database.Query.on callback wrong params

### ISSUE THREAD

**Issue by RANGELJ** [firebase/firebase-admin-node#805]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Catalina (10.15.3)
  * Firebase SDK version: 8.9.2
  * Firebase Product: database
  * Node.js version: 12.13.0
  * NPM version: 6.14.1

### [REQUIRED] Step 3: Describe the problem
The type definition for admin.database.Query.on
containse a callback that could be undefined:
```
    on(
      eventType: admin.database.EventType,
      callback: (a: admin.database.DataSnapshot | null, b?: string) => any,
      cancelCallbackOrContext?: Object | null,
      context?: Object | null
    ): (a: admin.database.DataSnapshot | null, b?: string) => any;
```

But in the client version of firebase, the type of the a parameter of the callback is always admin.database.DataSnapshot, and I am unable to locate some documentation that states that in the admin sdk, the on callback could pass a null instead of a snapshot

#### Steps to reproduce:

Write this code in a project that has the firebase-admin dependency in a ts file:
```
import admin from 'firebase-admin'

admin.database().ref().on('value', (snapshot: admin.database.DataSnapshot) => {
    console.log(snapshot.val())
})
```

What happened? How can we make the problem occur?
It will show an error when compiling the ts file:
Types of parameters 'snapshot' and 'a' are incompatible.
    Type 'DataSnapshot | null' is not assignable to type 'DataSnapshot'.
      Type 'null' is not assignable to type 'DataSnapshot'

```
import admin from 'firebase-admin'

admin.database().ref().on('value', (snapshot: admin.database.DataSnapshot) => {
    console.log(snapshot.val())
})
```

**Comment by hiranya911** [comment]
@schmidt-sebastian wdyt? Can we just update the typings of the Admin SDK?

**Comment by schmidt-sebastian** [comment]
We fixed them in the JS SDK in https://github.com/firebase/firebase-js-sdk/commit/aca99669dd8ed096f189578c47a56a8644ac62e6 (we reverted the original fix to release this with I/O).

Ideally, we would port all fixes of the index.d.ts file to firebase-admin.

**Comment by hiranya911** [comment]
@schmidt-sebastian can you help us port the necessary changes in our d.ts file?

On a related note, does it make sense to perhaps export the typings of the JS SDK through Admin for RTDB? Kind of similar to how we deal with Firestore typings. Not sure that's possible in this context, given complex dependency hierarchy of the JS SDK.

**Comment by schmidt-sebastian** [comment]
You could potentially just depend on https://www.npmjs.com/package/@firebase/database-types

Let me know if that works, then we don't need to update these types.

**Comment by hiranya911** [comment]
I think the problem is `database-types` has a dependency on `app-types`, which is different from the Admin SDK definitions for App.
