### ISSUE TITLE
[Firestore] Array Contains query result is different depending on the point how the where clause is added

### ISSUE THREAD

**Issue by aronsuarez** [firebase/firebase-admin-node#817]
* Operating System version: MacOS 10.15 and official node 10 container on cloud run
  * Firebase SDK version: 8.10.0
  * Firebase Product: Firestore
  * Node.js version: 10

### [REQUIRED] Step 3: Describe the problem

When I run an array contains query but create the reference first and add later the where clause it will give me the wrong result. The same query run with the where clause direct on the reference will work

#### Relevant Code:

// This will work
const ref = firestore.collection('cars').where('colors', 'array-contains', 'green'); 

// This give some wrong result back with false results
const ref = firestore.collection('cars')
ref.where('colors', 'array-contains', 'green');

**Comment by schmidt-sebastian** [comment]
@aronsuarez Thanks for filing this issue! The Query class itself is immutable, and every Query operation returns a new copy of the class. Hence, if you modify your second example a bit, it should work as expected:

```
let ref = firestore.collection('cars')
ref = ref.where('colors', 'array-contains', 'green');
await ref.get();
```

**Comment by antoniooi** [comment]
Looks like this problem still persists:

**Not working:**
```
var allAccRef = db.collection("Accounts");
if (subscriptionContains !== null) {
   allAccRef.where("Subscriptions", "array-contains", subscriptionContains);
}; 
```
**Working:**
`var allAccRef = db.collection("Accounts").where("Subscriptions", "array-contains", subscriptionContains);
`

**Comment by schmidt-sebastian** [comment]
The Query class is immutable. Please see the comment above for a code sample that shows how to re-assign the returned instance.

**Comment by antoniooi** [comment]
> The Query class is immutable. Please see the comment above for a code sample that shows how to re-assign the returned instance.

Ok, got it, thank you. Already updated my project code and proven working. Thanks again!
