### ISSUE TITLE
[Firestore]How to manage single firestore instance for the whole unit testing period?

### ISSUE THREAD

**Issue by manwithsteelnerves** [firebase/firebase-admin-node#818]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OSX Mojave
  * Firebase Admin version: 8.10
  * Firebase Product: Firestore
  * Node.js version: 10
  * NPM version: 6

### [REQUIRED] Step 3: Describe the problem
I created firestore instance and setting it in my database handler so that rest of the calls use the same db instance (which is local emulator firestore instance).

```
import * as firebase from '@firebase/testing';


import { addDefaultClientApplications } from "./seed/client-applications.seed";
import database  from '../../src/common/handlers/database.handler';

// Helper function to setup the test db instance
function authedApp() {
    return firebase
      .initializeAdminApp({ projectId: 'test-id' })
      .firestore();
  }

export const init = async () => {
    const db = authedApp();
    database.set(db);
    await addDefaultClientApplications();
}
```

Database Handler takes the firestore instance and hold it in databaseInstance variable.
```
import * as admin from 'firebase-admin';

let databaseInstance : admin.firestore.Firestore;

class DatabaseHander {
    get() : admin.firestore.Firestore {


        if (process.env.NODE_ENV !== "test") { //TODO check
            console.log("Database Instance : ", databaseInstance , process.env.SERVER_URL);
            databaseInstance = admin.firestore();
        }
    
        return databaseInstance;
    }
    
    set(db : any) {
        databaseInstance = db;
    }
}

export default new DatabaseHander(); 
```

When i start the unit test with below command, For seeding the local firestore I create an instance by calling init method(please check first code snippet) and set that instance to the databaseHandler.

Process environment variables are set when launching the tests with below command. 
```
    "test": "cross-env SERVER_URL=http://localhost:5001/test/us-central1/api/v1 cross-env NODE_ENV=test ts-node tests/index.ts"
```
Now when I'm unit testing "SignIn" http function, all process environment variables getting cleared automatically and leading to initialising the production firestore instance ( databaseInstance = admin.firestore();).

This makes it totally not testable with emulators as my functions rely on auth token a lot to get the logged in user role and other information.

Can someone help on how to solve this?

**Comment by hiranya911** [comment]
Please use StackOverflow for usage help and related questions.
