### ISSUE TITLE
[Firestore]

### ISSUE THREAD

**Issue by nikhilwairagade** [firebase/firebase-admin-node#819]
TypeError: Path must be a string. Received { nested: { google: { nested: [Object] } } }
this error come when I run test case.

**Comment by schmidt-sebastian** [comment]
@nikhilwairagade Sorry to hear about this! What test case are you running? If it is not one of our test cases, can you provide a reproduction and share the versions of the dependencies you are using?

**Comment by nikhilwairagade** [comment]
@schmidt-sebastian I got the solution for that can you tell me how to write test cases for nodejs and firestore based application using jest supertest .how to close server .

**Comment by nikhilwairagade** [comment]
"@google-cloud/storage": "4.1.3",
    "@grpc/grpc-js": "0.6.15",
    "angular-sweetalert": "1.1.2",
    "async": "2.6.1",
    "base64-img": "1.0.4",
    "bcrypt": "3.0.6",
    "body-parser": "1.18.3",
    "concat-stream": "2.0.0",
    "content-type": "1.0.4",
    "cookie-parser": "1.4.3",
    "cors": "2.8.5",
    "crypto": "1.0.1",
    "csv-writer": "1.5.0",
    "ejs": "2.6.1",
    "elasticsearch": "15.4.1",
    "express": "4.16.4",
    "file-system": "2.2.2",
    "firebase": "5.5.9",
    "firebase-admin": "8.9.0",
    "firebase-functions": "3.3.0",
    "firebase-functions-helper": "0.6.0",
    "generate-password": "1.4.1",
    "google-libphonenumber": "3.2.6",
    "google-spreadsheet": "2.0.8",
    "http": "0.0.0",
    "jwt-simple": "0.5.5",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "node-cron": "2.0.3",
    "node-rest-client": "3.1.0",
    "postmark": "2.2.0",
    "process-nextick-args": "2.0.0",
    "querystring": "0.2.0",
    "raw-body": "2.3.3",
    "request": "2.88.0",
    "rxjs": "6.4.0",
    "shopify-api-node": "2.16.0",
    "shopify-validate": "1.0.0",
    "supertest": "^4.0.2",
    "underscore": "1.9.1",
    "util-deprecate": "1.0.2",
    "uuid": "3.3.2",
    "xmlhttprequest": "1.8.0"
  },
  "devDependencies": {
    "eslint": "4.12.0",
    "eslint-plugin-promise": "3.6.0",
    "jest": "^25.1.0"
  },

**Comment by nikhilwairagade** [comment]
![Screenshot from 2020-03-17 16-13-56](https://user-images.githubusercontent.com/61176270/76849700-e7ebc880-686b-11ea-88c7-e01c71a5f90b.png)
![Screenshot from 2020-03-17 16-13-31](https://user-images.githubusercontent.com/61176270/76849713-f2a65d80-686b-11ea-82a5-a1ed95f1e603.png)

**Comment by schmidt-sebastian** [comment]
@nikhilwairagade Sorry, we don't have the resources to answer general usage questions here. Please take a look at our guides (on firebase.google.com) or on StackOverflow. If this doesn't answer your question, please ask on StackOverflow. The community as well as our Developer Relations team can help you there.

**Comment by nikhilwairagade** [comment]
nhhh
