### ISSUE TITLE
Index generation link displayed in console leads to blank page

### ISSUE THREAD

**Issue by joshmossas** [firebase/firebase-admin-node#821]
## My Environment
OS - Windows 10
Firebase SDK Version - firebase-admin@8.10.0
Firebase Product - firestore
Node.JS Version - v12.13.0
NPM Version - 6.11.2

## The Problem
When you create try to run a query that requires an index with the Firebase Admin SDK it generates a link to create an index. Clicking on this link leads to a blank page.
![image](https://user-images.githubusercontent.com/31548851/76825688-9b12de00-67e8-11ea-9784-20ec595d368e.png)

## Proposed Solution
Upon inspection it appears both single quotation mark `'` and the comma `,` are unintentionally being included at the end of the url.
![image](https://user-images.githubusercontent.com/31548851/76825862-107eae80-67e9-11ea-8df3-97d5388d76ea.png)

After deleting those extra characters from the url it successfully routes to the proper page
![image](https://user-images.githubusercontent.com/31548851/76825970-4b80e200-67e9-11ea-851c-3d488a11fe6b.png)

**Comment by hiranya911** [comment]
I think this is a copy-and-paste error on your part. I can see from the screenshot that the provided URL is correct. Your terminal/shell wrongly interprets the trailing `'` and `,` as part of the clickable link.

**Comment by joshmossas** [comment]
Yea, seems like you're correct. This is an issue with Powershell.

With  `console.error(err)` Powershell incorrectly includes the `'` and `,` as part of the clickable link

![image](https://user-images.githubusercontent.com/31548851/77126527-6173ea00-6a17-11ea-8dc6-4d5c9759d212.png)

When I do `throw err` there are no issues since the `'` and `,` are not present.

![image](https://user-images.githubusercontent.com/31548851/77126351-ca0e9700-6a16-11ea-8d14-8aa2f52e0075.png)

Thanks.

**Comment by minawalphonce** [comment]
the issue exists now without powershell 
i m using mac terminal
the link seems to be fine in the terminal without extra chars
but when i put in browser, it asks me to select an account as i have multiple 
then it redirects to the firebase with extra chars. these are not part of the url in terminal
