### ISSUE TITLE
Allocation of RTDB instance when used in callable cloud functions and Firestore cloud functions triggers in Node.js as admin

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-admin-node#824]
Question:
- Would there be one forever continuous RTDB connection allocated for callable cloud functions and Firestore cloud functions triggers? Two RTDB instances: one for callable cloud functions and the other for Firestore cloud functions triggers? Or many RTDBs instances connecting and disconnecting many times every time callable cloud functions or Firestore cloud functions triggers are invoked?

Reason:
I understand that it is costly to disconnect RTDB and connect RTDB as to establish new web socket connection, there needs to be security handshake and other overheads - resulting in more billing. My RTDB is using 1 MB of data download every day. I am using RTDB for one client (my iPhone) and Cloud functions for development and testing purposes, and I am only passing around hundreds of bytes of String data. I suspect maybe because RTDB instances are connecting and disconnecting many times in cloud functions it is costing 1MB of data downloaded everyday.

Related Subquestions:
- If I use RTDB in Cloud function trigger such as onUpdate, RTDB would connect and disconnect every time the function is triggered? 
- Is Cloud function essentially one machine so only one RTDB connection is maintained in the background at all times for each Firebase project?

**Comment by hiranya911** [comment]
Almost all these questions are answered in https://cloud.google.com/functions/docs/concepts/exec#stateless_functions

Simply put, Cloud Functions are stateless. Logically, each event is handled by a freshly started Functions instance, and the instance is terminated after handling the event. The runtime may reuse the same Function instance to handle some events that happen around the same time. But for all intents and purposes, you should assume that each event is processed by a newly started Function instance.

Please use StackOverflow for follow up questions.
