### ISSUE TITLE
[FR] Add Analytics Reporting

### ISSUE THREAD

**Issue by AmitMY** [firebase/firebase-admin-node#827]
**Is your feature request related to a problem? Please describe.**
We want to keep track on user events in one place (firebase analytics), and right now can't log events in the measurement protocol via the node server.

**Describe the solution you'd like**
Port `analytics` from the client SDK to the admin sdk, to allow `logEvent`

**Describe alternatives you've considered**
Tried `universal-analytics`, or other GA APIs, couldn't get my events to show in the firebase events dashboard

**Comment by manwithsteelnerves** [comment]
@ToddKerpelman Are you aware of any good alternatives to handle this?

**Comment by hiranya911** [comment]
Closing as a duplicate of #949. Let's continue the conversation there.
