### ISSUE TITLE
App Store redirect not working for iOS Email Auth Dynamic Links

### ISSUE THREAD

**Issue by antpuleo2586** [firebase/firebase-admin-node#834]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.15.3
  * Firebase SDK version: 8.10.0
  * Firebase Product: auth 
  * Node.js version: 10.16.3
  * NPM version: 6.9.0

#### Steps to reproduce:

Using the link generated by

`const link = await admin.auth().generateSignInWithEmailLink(userEmail, actionCodeSettings)`

does not redirect the user to the App Store when the iOS app is not installed.

However, if I add the `isi` and remove the `ifl` params, this correctly redirects to the App Store and successfully logs the user in after they download the app.

My actionCode settings are correct and this works when the app is installed.

Is this a bug or is this intended behaviour? Because I was under the impression that users should be redirected to stores when the app is not installed, as they do on Android.

Thanks!

**Comment by bojeil-google** [comment]
This is intended. `ActionCodeSettings` does not expose the option to install the iOS app when not installed. We did this on purpose because the process how these FDL redirects work is not reliable in certain versions of iOS. There is a low risk the link and the underlying code is intercepted by the wrong app. That is not an acceptable risk for sensitive auth operations.

**Comment by antpuleo2586** [comment]
Thanks for your reply. Do you have any more information around the circumstances under which this may occur? Which versions of iOS, in particular, does this affect?

Thanks

**Comment by athornz** [comment]
@bojeil-google I've been struggling to figure out this exact issue.

It would be great to have more information on which versions of iOS this affects as installing the app from a link and logging in the user is critical to our email based login workflow.
