### ISSUE TITLE
{"code":"messaging/mismatched-credential","message":"The caller does not have permission"}

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-admin-node#836]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: google cloud
  * Firebase SDK version: latest
  * Library version: 8.10.0
  * Firebase Product: cloud messaging (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

i'm trying to send a very simple message to a topic with FCM

```
const messaging = require('firebase-admin').initializeApp({
   serviceAccountId: 'fcm-publisher@igibo-b0b27.iam.gserviceaccount.com',
   projectId: "igibo-b0b27",
   messagingSenderId : '708969080657',
   appId : '1:708969080657:android:0595cd589585bd68'
}).messaging();


exports.sm_jivo_webhook = (req, res) => {

var message = {
  data: {
    activity: 'chat',
  },
  notification: {
    title: 'Resposta do suporte',
    body: 'Volte ao chat para verificar a resposta as suas dúvidas'
  },
  topic: '46f5b99a-5619-3a6b-a0e7-7ca1757b8930'
};


messaging.send(message)
  .then((response) => {
  res.status(200).send(JSON.stringify(response));  })
  .catch((error) => {
   res.status(200).send(JSON.stringify(error));
  });

};
```
the topic is right
the projectId is right  
the messagingSenderId  is right  
the serviceAccuontId is right and is an account with admin privileges to fcm  

https://i.ibb.co/DYDKsgr/Clipboard01.jpg

**Comment by hiranya911** [comment]
Your initialization logic is wrong.

`serviceAccountId`: Used only for signing custom tokens in the `admin.auth()` module. Not used for any FCM operations.
`messagingSenderId`: Not supported by the Admin SDK. Ignored.
`appId`: Not supported by the Admin SDK. Ignored.

You need to either pass your service account as the `credential` property, or correctly configure application default credentials in your environment. Because you are not specifying `credential`, your code is picking up some default credentials from your environment, which are clearly wrong for the topic you're trying communicate with.

**Comment by bolds07** [comment]
why am i not allowed to re-open it...

first your guys should have a look at the documentation you put on your website... all properties i use i took from the basic guides...

SECOND IT DOESNT WORK

i uploaded the function to the gcf directly (even it is one of the WORST dashboards in the world) so i could set ut all variables for sure... and still this piece of crap you call api. doesnt work

 
![image](https://user-images.githubusercontent.com/19866062/78473191-491f0180-7771-11ea-8fb6-ceebe664811e.png)

same error

**Comment by Sanjeevbadnur** [comment]
Hi Team,

Issue : 
       Facing inconsistent push notifications. With same token without any changes push notifications works for some times and does not works some times.
    
Platform : Android and IOS
Codebase : node.js
Firebase-admin sdk version : 12.4.0

Sample node code : 
```
let message = {
  tokens: array of fcm tokens
  notification: 
    {
       title: "test_title",
       body: push notification message,
    },
  data: 
    {
       data: payload,
       alertType: "crash",
    },
};

let response = await firebaseAdmin.messaging().sendEachForMulticast(message);
``` 

The error message is random and either one of them 
1. {"success":false,"error":{"code":"messaging/mismatched-credential","message":"SenderId mismatch"}}

2. {"success":false,"error":{"code":"messaging/unknown-error","message":"Operation is not implemented, or supported, or enabled. Raw server response: \"{\"error\":{\"code\":501,\"message\":\"Operation is not implemented, or supported, or enabled.\",\"status\":\"UNIMPLEMENTED\"}}\""}}

3. {"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}}
