### ISSUE TITLE
[FR] Question: "tokens list multicast" vs "device group"?

### ISSUE THREAD

**Issue by gajicm93** [firebase/firebase-admin-node#837]
This is a question rather than feature request.

We're having a use case of implementing chat functionality, and would be using Firebase messaging for background notifications obviously.

The app would have chat threads, consisting of e.g. 5 people, and those people could be logged on to e.g. 2 devices at the same time, so each chat thread sends to e.g. ~10 devices.

According to the documentation, topics are obviously not fit for a ~10 device use case, so now we're trying to decide between multicast to [tokens list](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices) and sending to a [device group](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-device-groups).

Can you explain me (or point me to a documentation) that explains the **difference** between the 2 and which is better fit for our use case? And also how does a device join a device group?

Thanks!

**Comment by hiranya911** [comment]
For most use cases you should use setMulticast. Device groups are part of the legacy FCM API: https://firebase.google.com/docs/cloud-messaging/send-message#adminSDK-legacy-send-methods

The pages linked from there provides details on how to create and manage device groups: https://firebase.google.com/docs/cloud-messaging/http-server-ref#device-group-management
