### ISSUE TITLE
firebase-admin dependency errors

### ISSUE THREAD

**Issue by esparkman** [firebase/firebase-admin-node#84]
* Operating System version: macOS 10.12.6
  * Firebase SDK version: 5.2.1
  * Library version: 5.2.1
  * Firebase Product: admin

I'm seeing some dependency issues.
firebase-admin: 5.2.1
```
➜  customer-manager (master) ✗ yarn add firebase-admin                                                    .../customer-manager
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ @google-cloud/storage@1.2.1
└─ firebase-admin@5.2.1
Done in 4.74s.

➜  customer-manager (master) ✗ yarn start                                                                 .../customer-manager

yarn start v0.27.5
$ node build/dev-server.js
> Starting dev server...

 ERROR  Failed to compile with 22 errors                                                                            10:37:27 PM

These dependencies were not found:

* fs in ./~/firebase-admin/lib/auth/credential.js, ./~/@google-cloud/storage/src/bucket.js and 10 others
* net in ./~/faye-websocket/lib/faye/websocket/client.js, ./~/forever-agent/index.js and 3 others
* tls in ./~/faye-websocket/lib/faye/websocket/client.js, ./~/forever-agent/index.js and 1 other
* child_process in ./~/google-auth-library/lib/auth/googleauth.js
* dns in ./~/isemail/lib/isemail.js

```

**Comment by katowulf** [comment]
Are those dependencies in fact installed? Is ./~/.../ the right path when referenced from build/dev-server.js? What does the yarn config file look like? There's a lot more to include here before we can help with debugging.

**Comment by esparkman** [comment]
This was on a brand new repo. Should I have to install dependencies by hand? That doesn't seem right.

**Comment by hiranya911** [comment]
Are you trying to use `firebase-admin` in a client-side or browser environment? That is not supported. Some of the missing modules (fs, net etc.) are only available in server-side Node.js environments.

**Comment by crossRT** [comment]
I installed firebase-admin on a brand new project which running webpack4 + typescript, getting these dependencies issue as well.

```
WARNING in ./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
16:20-67 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/grpc/src/grpc_extension.js
32:12-33 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/src/grpc_extension.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts

WARNING in ./node_modules/bytebuffer/dist/bytebuffer-node.js
Module not found: Error: Can't resolve 'memcpy' in '/Users/crossrt/www/malaysia-election/node_modules/bytebuffer/dist'
 @ ./node_modules/bytebuffer/dist/bytebuffer-node.js 29:38-55
 @ ./node_modules/protobufjs/dist/protobuf.js
 @ ./node_modules/grpc/index.js
 @ ./node_modules/@google-cloud/common-grpc/src/index.js
 @ ./node_modules/@google-cloud/firestore/src/index.js
 @ ./src/index.ts
```

Any idea how could these happened?

**Comment by ixjakub** [comment]
@crossRT did you found any solutions? I try using `firebase-admin` with Netlify functions and get similar errors.

**Comment by aaaguirrep** [comment]
Hi, did you find any solutions? I have the same issue.

**Comment by crossRT** [comment]
> Hi, did you find any solutions? I have the same issue.

Hi, as I mentioned above, I didn't find any solution.
Using plain ES6 javascript instead of typescript will solve this project.

**Comment by FredrikNoren** [comment]
Had a similar issue, removed node_modules and reinstalled and it worked.

**Comment by aaaguirrep** [comment]
It didn't work. It shows:

These dependencies were not found:

* child_process in ./node_modules/google-auth-library/build/src/auth/googleauth.js,
./node_modules/grpc/node_modules/detect-libc/lib/detect-libc.js
* fs in ./node_modules/@google-cloud/storage/src/file.js, ./node_modules/@google-cloud/storage/src/bucket.js and 34 others
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js
To install them, you can run: npm install --save child_process fs net tls

**Comment by huy-lv** [comment]
Why is this issue closed? I got the same problem with this dependency
```
    "firebase": "^5.5.3",
    "firebase-admin": "^6.5.0",
```

**Comment by aaaguirrep** [comment]
You áre using the same library at front-end and it is nota possible.

Firebase is used at front-end
Firebase-admin is used at back-end

I installed firebase-admin at back-end and it worked.

**Comment by redaben** [comment]
@ixjakub Did you find a solution ? I have the same pb running firebase-admin with netlify functions

**Comment by ixjakub** [comment]
I finally turned away from Firebase at all. I can't help you.

**Comment by chinchang** [comment]
@hiranya911 Any update on this issue? Facing the same error.

**Comment by hiranya911** [comment]
There's no resolution. If your runtime complains about missing dependencies like `fs`, `net` and `child_process`, then that's a good indication that the Admin SDK should not be used in that environment.

**Comment by hiranya911** [comment]
The error message is complaining about built-in Node packages like fs and net:

```
* fs in ./~/firebase-admin/lib/auth/credential.js, ./~/@google-cloud/storage/src/bucket.js and 10 others
* net in ./~/faye-websocket/lib/faye/websocket/client.js, ./~/forever-agent/index.js and 3 others
* tls in ./~/faye-websocket/lib/faye/websocket/client.js, ./~/forever-agent/index.js and 1 other
* child_process in ./~/google-auth-library/lib/auth/googleauth.js
* dns in ./~/isemail/lib/isemail.js
```

We don't declare them explicitly, but expect the Node.js environment to provide them. I don't know how to "fix" `firebase-admin` so it can resolve these built-ins. If anybody knows of a fix, or provide some pointers I'd be happy to take a look.

The solution to this problem most likely exists in the webpack domain. According to Google search there are many similar issues reported agains various other libraries, with no specific resolution in sight. But the following issue discusses several potential fixes, that seem to have fixed a similar issue to some: https://github.com/mysqljs/mysql/issues/1563

**Comment by amit00978** [comment]
After installed  ```  "firebase-admin": "^8.3.0" ``` it gives an error ```While trying to resolve module `fs````  . any help really appreciated.

**Comment by amalshehu** [comment]
Having the same issue, Why it looks closed ? @esparkman

**Comment by antoinerousseau** [comment]
Having the same issue when running `netlify-lambda` and a TypeScript function:

```
WARNING in node_modules/hash-stream-validation/index.js
Module not found: Error: Can't resolve 'fast-crc32c' in 'node_modules/hash-stream-validation'
 @ node_modules/hash-stream-validation/index.js
 @ node_modules/@google-cloud/storage/build/src/file.js
 @ node_modules/@google-cloud/storage/build/src/index.js
 @ node_modules/firebase-admin/lib/storage/storage.js
 @ node_modules/firebase-admin/lib/firebase-namespace.js
 @ node_modules/firebase-admin/lib/default-namespace.js
 @ node_modules/firebase-admin/lib/index.js
 @ ./supervisor.ts

WARNING in node_modules/configstore/node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'worker_threads' in 'node_modules/configstore/node_modules/write-file-atomic'
 @ node_modules/configstore/node_modules/write-file-atomic/index.js
 @ node_modules/configstore/index.js
 @ node_modules/gcs-resumable-upload/build/src/index.js
 @ node_modules/@google-cloud/storage/build/src/file.js
 @ node_modules/@google-cloud/storage/build/src/index.js
 @ node_modules/firebase-admin/lib/storage/storage.js
 @ node_modules/firebase-admin/lib/firebase-namespace.js
 @ node_modules/firebase-admin/lib/default-namespace.js
 @ node_modules/firebase-admin/lib/index.js
 @ ./supervisor.ts
```

Any clue?

**Comment by rodrigogs** [comment]
Firebase ecosystem is such a mess. They don't give a shit about webpack use cases, because they want you to use Google Cloud Functions...

**Comment by rodrigogs** [comment]
The following line in `webpack.config.js` solves the problem to me btw:

```javascript
module.exports = {
  ...
  externals: [ 'aws-sdk', 'commonjs2 firebase-admin' ],
  ...
};
```

**Comment by majindageta** [comment]
> The following line in `webpack.config.js` solves the problem to me btw:
> 
> ```js
> module.exports = {
>   ...
>   externals: [ 'aws-sdk', 'commonjs2 firebase-admin' ],
>   ...
> };
> ```

Hi! Did you found any issue using this or is production safe?

**Comment by rodrigogs** [comment]
> > The following line in `webpack.config.js` solves the problem to me btw:
> > ```js
> > module.exports = {
> >   ...
> >   externals: [ 'aws-sdk', 'commonjs2 firebase-admin' ],
> >   ...
> > };
> > ```
> 
> Hi! Did you found any issue using this or is production safe?

Not at all. It's working perfectly in production right now.

**Comment by bartkoedijk** [comment]
In my project i used  the npm package: `"firebase-admin"` for accessing the `firestore` object like this:
`import { firestore } from "firebase-admin";`

But firestore can also be imported like this:
`import firestore from '@react-native-firebase/firestore';`

I removed the `"firebase-admin"` package and my problem was solved:)

**Comment by IamMasterWayne** [comment]
"react": "^16.13.1"
"firebase": "^7.19.1"
"firebase-admin": "^9.1.1"

_./node_modules/hash-stream-validation/index.js_
**Module not found: Can't resolve 'fast-crc32c'**

_./node_modules/configstore/node_modules/write-file-atomic/index.js_
**Module not found: Can't resolve 'worker_threads'**


**Facing this Issue while trying to add Firebase Admin SDK to my React Web app**

**Comment by Gibbo3771** [comment]
@IamMasterWayne 

The Firebase Admin SDK is a server only library, the errors you are seeing are due to this. If you need to do admin operations, you need to do it in a trusted environment and expose it via an API of some kind (lambda, rest etc etc).

**Comment by advantage-software** [comment]
> "react": "^16.13.1"
> "firebase": "^7.19.1"
> "firebase-admin": "^9.1.1"
> 
> _./node_modules/hash-stream-validation/index.js_
> **Module not found: Can't resolve 'fast-crc32c'**
> 
> _./node_modules/configstore/node_modules/write-file-atomic/index.js_
> **Module not found: Can't resolve 'worker_threads'**
> 
> **Facing this Issue while trying to add Firebase Admin SDK to my React Web app**

Do you find a solution to this?

**Comment by AaronLayton** [comment]
I am getting this same error, what ever it is, user error or package error, it is obvious this is not clear to the end user

```bash
asset bundle.js 20.8 MiB [compared for emit] (name: main)
runtime modules 1.37 KiB 6 modules
modules by path ./node_modules/ 8.05 MiB
  javascript modules 7.73 MiB 578 modules
  json modules 329 KiB
    modules by path ./node_modules/google-gax/ 39.4 KiB 7 modules
    modules by path ./node_modules/@google-cloud/ 78 KiB 6 modules
    modules by path ./node_modules/protobufjs/ 10 KiB 4 modules
    modules by path ./node_modules/ent/ 54 KiB
      ./node_modules/ent/reversed.json 22.3 KiB [built] [code generated]
      ./node_modules/ent/entities.json 31.7 KiB [built] [code generated]
modules by path ./src/*.ts 1.41 KiB
  ./src/index.ts 1.07 KiB [built] [code generated]
  ./src/firebase-admin-instance.ts 353 bytes [built] [code generated]
27 modules

WARNING in ./node_modules/hash-stream-validation/index.js 5:8-30
Module not found: Error: Can't resolve 'fast-crc32c' in 'D:\Projects\Git\ibms-mqtt-watcher\node_modules\hash-stream-validation'
 @ ./node_modules/@google-cloud/storage/build/src/file.js 26:29-62
 @ ./node_modules/@google-cloud/storage/build/src/index.js 20:13-30
 @ ./node_modules/firebase-admin/lib/storage/storage.js 55:22-62
 @ ./node_modules/firebase-admin/lib/firebase-namespace.js 225:26-62
 @ ./node_modules/firebase-admin/lib/default-namespace.js 19:27-58
 @ ./node_modules/firebase-admin/lib/index.js 19:15-45
 @ ./src/firebase-admin-instance.ts 1:0-40 3:5-22 4:4-23 5:20-41 11:15-20
 @ ./src/index.ts 2:0-46 22:4-19

WARNING in ./node_modules/retry-request/index.js 73:21-39
Module not found: Error: Can't resolve 'request' in 'D:\Projects\Git\ibms-mqtt-watcher\node_modules\retry-request'
 @ ./node_modules/google-gax/build/src/streamingCalls/streaming.js 22:21-45
 @ ./node_modules/google-gax/build/src/index.js 62:18-55
 @ ./node_modules/@google-cloud/firestore/build/src/index.js 401:95-121 1067:37-71 1348:15-43
 @ ./node_modules/firebase-admin/lib/firebase-namespace.js 242:28-62
 @ ./node_modules/firebase-admin/lib/default-namespace.js 19:27-58
 @ ./node_modules/firebase-admin/lib/index.js 19:15-45
 @ ./src/firebase-admin-instance.ts 1:0-40 3:5-22 4:4-23 5:20-41 11:15-20
 @ ./src/index.ts 2:0-46 22:4-19

2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```

I am only importing the `firebase-admin` into a NodeJS app and attempting to send a notification. It is TypeScript if that affects anything

```ts
import * as admin from "firebase-admin";
var serviceAccount = require("../serviceAccountKey.json");

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}

export default admin;
```

```ts
import admin from './firebase-admin-instance'

const payload = {
    notification: {
        title: "Server says there is a problem",
        message: "Some issue happened at " + new Date().getTime()
    }
};

admin.messaging().sendToDevice(dummyAccounts, payload)
.then(function(response) {
    console.log("Successfully sent message:", response);
})
.catch(function(error) {
    console.log("Error sending message:", error);
});
```

**Comment by hiranya911** [comment]
Today, you cannot use `firebase-admin` in Webpack without externalizing it. You will have to apply a workaround like the one mentioned here: https://github.com/firebase/firebase-admin-node/issues/84#issuecomment-630311771

**Comment by AaronLayton** [comment]
@hiranya911 I got it working _without_ externalizing it. I have currently got the following installed

```
"@firebase/app": "^0.6.27",
"firebase-admin": "^9.10.0"
```

I used the below to import firebase - note the `import * as admin`

```ts
import * as admin from "firebase-admin";
```

The most I get now are warnings that I can't find a npm installed version of these packages so falls back to local versions of them (assume shipped by firebase)

<img width="866" alt="2021-06-28_18h54_50" src="https://user-images.githubusercontent.com/694964/123682025-65113600-d842-11eb-8476-e17d8cef2291.png">

**Comment by hiranya911** [comment]
Thanks for sharing this @AaronLayton. I suppose the fix you did here is to install `@firebase/app` along side `firebase-admin`. It's not a runtime dependency for Admin SDK, but Webpack thinks it is. If you were to use `firebase-admin` without installing other dependencies you will have to externalize it.

**Comment by iamkratos** [comment]
I'm building a NextJS app using "next-firebase-auth", and ran into this issue. My deploys were building fine, but then this started popping up. The way I fixed the issue:

- I applied [#84](https://github.com/firebase/firebase-admin-node/issues/84#issuecomment-630311771)
- I ran npm install --save fast-crc32c
- Then the error changed, and I had to run npm i retry-request request

This was able to fix my deploys, let me know if it works for y'all

**Comment by moschan** [comment]
I tried this settings and it worked so far.

```.json
{
    "next": "11.0.1",
    "firebase": "^8.6.8",
    "firebase-admin": "^9.10.0"
}
```

```js
///next.config.js
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false
      config.resolve.fallback.child_process = false
      config.resolve.fallback.request = false
      config.resolve.fallback.net = false
      config.resolve.fallback.worker_threads = false
      config.resolve.fallback.tls = false
    }
    return config
  }
}
```

**Comment by SeiwonPark** [comment]
> I tried this settings and it worked so far.
> 
> ```json
> {
>     "next": "11.0.1",
>     "firebase": "^8.6.8",
>     "firebase-admin": "^9.10.0"
> }
> ```
> 
> ```js
> // next.config.js
> module.exports = {
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.resolve.fallback.fs = false
>       config.resolve.fallback.child_process = false
>       config.resolve.fallback.request = false
>       config.resolve.fallback.net = false
>       config.resolve.fallback.worker_threads = false
>       config.resolve.fallback.tls = false
>     }
>     return config
>   }
> }
> ```

exactly followed installed versions but didn't work for me :(

**Comment by wjeliot** [comment]
I found that I received this error in Next.js when I mingled my `firebase-admin` app with my `firebase` client side app. To solve it, I ensured that `firebase-admin` was never imported in a client-facing file, and then (and this is crucial) I separated the initialisation of the two apps so they were initialised in separate files.

**Comment by SeiwonPark** [comment]
> I found that I received this error in Next.js when I mingled my `firebase-admin` app with my `firebase` client side app. To solve it, I ensured that `firebase-admin` was never imported in a client-facing file, and then (and this is crucial) I separated the initialisation of the two apps so they were initialised in separate files.

---

Thank you so much! You saved my day!

I could find:

* package version didn't matter
* initializing **Firebase Client SDK** and **Firebase Admin SDK** need to be **separated**
* **`typeof window` shouldn't be `undefined`** (as window object is in client-side - but Next.js runs Server-Side first)

And I could have solved the issue. My file structure and codes:

```
├── firebase/
│    ├── firebaseAdmin.ts
│    ├── firebaseClient.ts
│    └── firebaseConfig.ts
├── pages/
├── public/
├── styles/
```

```json
// package.json

"dependencies": {
    "axios": "^0.21.1",
    "dotenv": "^10.0.0",
    "firebase": "^8.8.0",
    "firebase-admin": "^9.11.0",
    "next": "11.0.1",
    "nookies": "^2.5.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@types/react": "17.0.15",
    "@typescript-eslint/eslint-plugin": "^4.29.0",
    "@typescript-eslint/parser": "^4.29.0",
    "eslint": "7.31.0",
    "eslint-config-next": "11.0.1",
    "eslint-plugin-react": "^7.24.0",
    "typescript": "4.3.5"
  }
```

```typescript
// firebaseAdmin.ts

import * as firebaseAdmin from "firebase-admin";
import { firebaseAdminConfig } from "./firebaseConfig";

if (!firebaseAdmin.apps.length) {
	firebaseAdmin.initializeApp({
		credential: firebaseAdmin.credential.cert(firebaseAdminConfig)
	});
}

export { firebaseAdmin };
```

```typescript
// firebaseClient.ts

import "firebase/auth";
import firebaseClient from "firebase/app";
import { firebaseClientConfig } from "./firebaseConfig";


if (typeof window !== "undefined" && !firebaseClient.apps.length) {
	firebaseClient.initializeApp(firebaseClientConfig);
	firebaseClient
		.auth()
		.setPersistence(firebaseClient.auth.Auth.Persistence.SESSION);
	(window as any).firebase = firebaseClient;
}

export { firebaseClient };
```

```typescript
// firebaseConfig.ts

export const firebaseClientConfig = {
	apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
	authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
	projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
	storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
	messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};


export const firebaseAdminConfig = {
	privateKey: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY,
	clientEmail: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL,
	projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
};
```
(I've made an `.env.local` file and then saved those keys)

+) you don't have to modify this file, but my setting for `next.config.js`

```javascript
// eslint-disable-next-line no-undef
module.exports = {
	webpack: (config, { isServer }) => {
		if (!isServer) {
			config.resolve.fallback.fs = false;
			config.resolve.fallback.child_process = false;
			config.resolve.fallback.request = false;
			config.resolve.fallback.net = false;
			config.resolve.fallback.worker_threads = false;
			config.resolve.fallback.tls = false;
		}
		return config;
	}
};
```

I wish this could be a help

**Comment by kevincoleman** [comment]
> In my project i used the npm package: `"firebase-admin"` for accessing the `firestore` object like this:
> `import { firestore } from "firebase-admin";`
> 
> But firestore can also be imported like this:
> `import firestore from '@react-native-firebase/firestore';`
> 
> I removed the `"firebase-admin"` package and my problem was solved:)

Thank you for sharing this @bartkoedijk! I was pulling hair out over this one, and your comment saved me.
