### ISSUE TITLE
Access multiple database in same project

### ISSUE THREAD

**Issue by amarjeetanandsingh** [firebase/firebase-admin-node#843]
How to access different Firebase Database in the same project?

Can't find relevant documentation. The closest i can find is suggesting to create another app.

https://firebase.google.com/docs/admin/setup#initialize-multiple-apps

**Comment by amarjeetanandsingh** [comment]
```node
const admin = require('firebase-admin');
const serviceAccount = require('./config/serviceAccount.json');
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "https://db1_url.firebaseio.com"
});

let app = admin.app();
let ref = app.database("https://db2_url.firebaseio.com").ref();
```

Is this is a correct way to access other database in the same project?

**Comment by hiranya911** [comment]
Yes. For any API questions, you can also just look at the published API references.

https://firebase.google.com/docs/reference/admin/node/admin.app.App#database

**Comment by amarjeetanandsingh** [comment]
Hi @hiranya911 
Thanks for the response.
I feel like this should be mentioned in doc somewhere https://firebase.google.com/docs/database/admin/start

If allowed, I am pretty excited to take this work of updating the document.

**Comment by hiranya911** [comment]
Thanks @amarjeetanandsingh. Our docs are not open source. But you can go to the above page and submit some feedback to our docs team. Use the "Send Feedback" button at the bottom of the page.
