### ISSUE TITLE
[FR] FirestoreDataConverter support for Admin SDK

### ISSUE THREAD

**Issue by komape** [firebase/firebase-admin-node#854]
**Is your feature request related to a problem? Please describe.**
I cannot use a FirestoreDataConverter as am I used to it for the Web Client SDK. See [here on StackOverflow](https://stackoverflow.com/questions/61275909/firestoredataconverter-throws-error-for-admin-sdk-but-not-for-javascript-or-node).

**Describe the solution you'd like**
To be able to use a FirestoreDataConverter as in the Web Client SDK.

**Describe alternatives you've considered**
Manually parse the model objects, very annoying if it is possible the other way.

**Comment by hiranya911** [comment]
Please report Firestore feature requests directly at https://github.com/googleapis/nodejs-firestore

**Comment by schmidt-sebastian** [comment]
FirestoreDataConverter is already part of `@google-cloud/firestore`. You should be able to use it with `firebase-admin` if you install a recent version.

See https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L83

**Comment by komape** [comment]
@schmidt-sebastian As you can see in my [StackOverflow question](https://stackoverflow.com/questions/61275909/firestoredataconverter-throws-error-for-admin-sdk-but-not-for-javascript-or-node) it is not working. Should I file a bug report?

**Comment by schmidt-sebastian** [comment]
There is a known issue with the types of the converter on Node: https://github.com/googleapis/nodejs-firestore/issues/938. The Node converted doesn't take a DocumentSnapshot, but instead the data of the snapshot.
 
This will be fixed in our next major release.
