### ISSUE TITLE
License incomplete

### ISSUE THREAD

**Issue by jonathangroves** [firebase/firebase-admin-node#858]
The text in the License (https://github.com/firebase/firebase-admin-node/blob/master/LICENSE) does not include the name of the copyright holder nor date.
Brackets are provided near the bottom of the file for these data to be added.

**Comment by hiranya911** [comment]
Pretty sure you're not required to modify those placeholders. The text just above it states: 

```
     To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!) 
```

And we do follow that advice when adding the license header to individual source files.

As a further reference, here's the LICENSE file from Apache's own HTTPD project, where the placeholder values are kept as is: https://svn.apache.org/viewvc/httpd/httpd/trunk/LICENSE?view=markup#l189
