### ISSUE TITLE
firebase 

### ISSUE THREAD

**Issue by DhwaniDesai835** [firebase/firebase-admin-node#865]
<?php

require_once './vendor/autoload.php';

use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

$serviceAccount = ServiceAccount::fromJsonFile(__DIR__.'/bakery-2ec50-6585681c6217.json');

$firebase = (new Factory)
    ->withServiceAccount($serviceAccount)
->withDatabaseUri('https://bakery-2ec50.firebaseio.com/')
    ->create();

$database = $firebase->getDatabase();

?>
![Capture](https://user-images.githubusercontent.com/55911607/80121196-9db3e080-85a9-11ea-9b14-96590766b8fd.PNG)

**Comment by hiranya911** [comment]
Looks like PHP code. We don't provide a PHP API.
