### ISSUE TITLE
[Firestore] Cannot read property 'DEADLINE_EXCEEDED' of undefined while processing firestore query

### ISSUE THREAD

**Issue by ad34** [firebase/firebase-admin-node#867]
### Describe your environment

  * Operating System version: mac os mojave 10.14.6 (18G3020)
 * Firebase SDK version: 8.11.0
  * Firebase Product: Firestore
  * Node.js version: v12.16.2
  * NPM version: 6.14.4

### [REQUIRED] Step 3: Describe the problem

While executing a query from server side, I get this error in the catch
TypeError: Cannot read property 'DEADLINE_EXCEEDED' of undefined\n    at /.../server/node_modules/@google-cloud/firestore/build/src/util.js:125:99\n    at Array.map (<anonymous>)\n    at Object.isPermanentRpcError (/.../server/node_modules/@google-cloud/firestore/build/src/util.js:125:63)\n    at Firestore._retry (/.../server/node_modules/@google-cloud/firestore/build/src/index.js:828:28)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)

#### Relevant Code:

```

 const r = firestore.collection('acollection');

        r
            .where('somefield', '=', somevalue)
            .where('timestampfield', '>=', unixformattimestamp)
            .get().catch()
```

my timestamp format is maybe incorrect, but the error reported is not appropriate
I cannot reproduce the issue is I remove the second where condition

**Comment by ad34** [comment]
setting a composite index fixes the issue, however the error reported is misleading.

**Comment by schmidt-sebastian** [comment]
@ad34 Sorry for not looking at this much earlier.

I suspect that you are getting the error because the version of `google-gax` you are using does not export the `Status` enum. This was added in v1.13.0 of Google Gax, which this library now depends on. Can you confirm what version of `google-gax` you have installed?

**Comment by ad34** [comment]
@schmidt-sebastian  thanks, you are right, forcing the dependency to 1.13 like this solved the issue 

"resolutions": {
    "**/google-gax": "1.13.0"
  }

the message is clear now : 

9 FAILED_PRECONDITION: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/xxxxx/firestore/indexes?create_comp

**Comment by kiptoomm** [comment]
I saw this error while trying to run the firebase emulator to test functions. Turns out I had used a mix of yarn and npm to install dependencies. Cleaning out `node_modules`, removing lock files, and then re-installing with only either yarn or npm helped
