### ISSUE TITLE
proxy via httpAgent does not work on firebase-admin^8

### ISSUE THREAD

**Issue by wollowizard** [firebase/firebase-admin-node#870]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOs Catalina 10.15.4
  * Firebase SDK version: 8.11.0
  * Firebase Product: database (auth, database, storage, etc)
  * Node.js version: v12.16.2
  * NPM version: 6.14.4

### [REQUIRED] Step 3: Describe the problem
specifying an httpAgent (to make requests behind a proxy) does not work anymore since version 8. same code works between version 6.4 and ^7.
I get the error 
Failed to connect to proxy 127.0.0.1:3128 with error getaddrinfo ENOTFOUND 127.0.0.1:3128
Failed to connect to proxy 127.0.0.1:3128 with error getaddrinfo ENOTFOUND 127.0.0.1:3128
Failed to connect to proxy 127.0.0.1:3128 with error getaddrinfo ENOTFOUND 127.0.0.1:3128

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
package json
"dependencies": {
    "firebase-admin": "^8.11.0",
    "tunnel2": "0.0.4"
  }






var admin = require('firebase-admin');
const tunnel = require('tunnel2')
const serviceAccount = {..................}

const proxyAgent = tunnel.httpsOverHttp({
  proxy: {
    host: '127.0.0.1',
    port: 3128
  }
});
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount, proxyAgent),
  databaseURL: '..................',
  httpAgent: proxyAgent
});

admin.firestore().collection("..................")
.doc("..................")
.get().then(r => console.log(JSON.stringify(r)))
```

**Comment by hiranya911** [comment]
Your error states `Failed to connect to proxy 127.0.0.1:3128 with error getaddrinfo ENOTFOUND 127.0.0.1:3128` which means Node.js is trying to connect to the proxy but failing to.  Looks like an issue with the proxy server itself. The SDK has clearly passed the `http.Agent` to the Node.js HTTP API.

**Comment by wollowizard** [comment]
> Your error states `Failed to connect to proxy 127.0.0.1:3128 with error getaddrinfo ENOTFOUND 127.0.0.1:3128` which means Node.js is trying to connect to the proxy but failing to. Looks like an issue with the proxy server itself. The SDK has clearly passed the `http.Agent` to the Node.js HTTP API.

The same exact code with firebase-admin <8 works.  Just changing the package json dependency from 7 to 8 breaks it. So it must be the firebase-admin package

**Comment by hiranya911** [comment]
It's most likely the `tunnel` package then. I just verified my [old proxy example](https://medium.com/faun/firebase-accessing-firestore-and-firebase-through-a-proxy-server-c6c6029cddb1) on the latest Admin SDK, and it worked just fine.

Proxy access log:
```
1588180925.255    231 172.17.0.1 TCP_TUNNEL/200 3870 CONNECT accounts.google.com:443 - HIER_DIRECT/172.217.5.109 -
1588180925.987    731 172.17.0.1 TCP_TUNNEL/200 4054 CONNECT fcm.googleapis.com:443 - HIER_DIRECT/216.58.194.170 -
```

**Comment by wollowizard** [comment]
I'll try your code and let you know.
I only need to set https_proxy env car, right?

**Comment by hiranya911** [comment]
Ok, it appears connecting to Firestore through a proxy may be broken. The env variable may have changed in the recent versions of `grpc`.  In the past setting `https_proxy` worked but now it fails with an error:

```
Failed to connect to proxy localhost:3128 with error getaddrinfo ENOTFOUND localhost:3128 localhost:3128:80
Failed to connect to proxy localhost:3128 with error getaddrinfo ENOTFOUND localhost:3128 localhost:3128:80
(node:14827) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)
    at ChannelImplementation.tryPick (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/channel.js:214:32)
    at Object.updateState (/home/hiranya/Projects/firebase/proxy-test/node_modules/@grpc/grpc-js/build/src/channel.js:82:26)
```

@schmidt-sebastian can you advise how to do this with the latest Admin SDK? This is my code:

```
var admin = require('firebase-admin');

admin.initializeApp({
  credential: admin.credential.applicationDefault(),
});

admin.firestore().collection("messages")
    .doc("foo")
    .set({value: 123}).then(r => console.log('Done'))
```

**Comment by hiranya911** [comment]
After an offline chat with @schmidt-sebastian I managed to get Firestore proxy support working. Here's what I had to do:

1. Install latest `@ grpc/grpc-js`
  - `npm install @grpc/grpc-js`
  - `rm -rf node_modules/google-gax/node_modules/@grpc`
2. Set the `https_proxy` env variable.

Then I was able to get the Firestore calls going through the proxy:

```
1588184944.417    172 172.17.0.1 TCP_TUNNEL/200 4162 CONNECT www.googleapis.com:443 - HIER_DIRECT/172.217.14.106 -
1588184944.721    525 172.17.0.1 TCP_TUNNEL/200 3928 CONNECT firestore.googleapis.com:443 - HIER_DIRECT/216.58.194.202 -
```

Note that as in  the old versions, you don't have to specify `httpAgent` just to access Firestore through proxy. `httpAgent` is only needed for a handful of services like Auth and FCM.

**Comment by hiranya911** [comment]
@schmidt-sebastian feel free to add any addition context and close this. I assume the installation will automatically pull in the latest grpc eventually.

**Comment by wollowizard** [comment]
Is it gonna work if I just pass the httpAgent instead of setting the https_proxy env var?

**Comment by schmidt-sebastian** [comment]
Note that you can just install an additional version of grpc-js and pass it into the Firestore constructor:

```
npm install @grpc/grpc-js@latest


const grpc = require("@grpc/grpc-js");
firestore.settings( { grpc } );
```

We will upgrade our GRPC dependency next Monday, which will make this unnecessary. Unfortunately, we are not able to push new releases this week.

**Comment by hiranya911** [comment]
> Is it gonna work if I just pass the httpAgent instead of setting the https_proxy env var?

Not for Firestore. See my earlier comment. 

`httpAgent` is used only by APIs like Auth and FCM that the SDK integrates via http. Firestore is not one of those services as it uses grpc for integration.

**Comment by schmidt-sebastian** [comment]
We just published an upgrade to FIrestore's network stack that should enable Proxy support by default.

**Comment by hiranya911** [comment]
This WAI now.
