### ISSUE TITLE
[firebase-admin] Add RemoteConfig typing

### ISSUE THREAD

**Issue by SeanOThomas** [firebase/firebase-admin-node#871]
* Node.js version: v12.4.0
  * firebase-admin version: 8.11.0

#### Steps to reproduce:

1. Install firebase-admin
2. Try to access RemoteConfig using `admin.remoteConfig()`

Result:

`[ts] Property 'remoteConfig' does not exist on type 'App'. [2339]`

**Comment by hiranya911** [comment]
Typings look fine as far as I can tell:

https://github.com/firebase/firebase-admin-node/blob/0ac248e10b663d3bb0901e495fa6adcdbf448522/src/index.d.ts#L530
https://github.com/firebase/firebase-admin-node/blob/0ac248e10b663d3bb0901e495fa6adcdbf448522/src/index.d.ts#L406

This is most likely a case of you're using an older version of Admin SDK. Can you verify the library version by checking the `node_modules/firebase-admin/package.json` file?

**Comment by lahirumaramba** [comment]
Tested using a fresh Node.js app with `firebase-admin` version: 8.11.0 and could not reproduce the issue. Please verify that you are using `firebase-admin` version: 8.11.0. Let us know if you have any questions. Closing this issue.
