### ISSUE TITLE
[Cloud messaging] Send scheduled push notification

### ISSUE THREAD

**Issue by magic-coding** [firebase/firebase-admin-node#872]
Is there way to send scheduled push notification using admin SDK? I want to send scheduled push notification instead of using a cloud function pubsub schedule to send notification on a specific date and time.

**Comment by lahirumaramba** [comment]
To my understanding the Admin SDK or the Firebase Cloud Messaging does not have an API to schedule notifications.

It looks like a common way to handle scheduled notifications is to store the message information in a database and periodically check for notifications that need to be sent. You could achieve this using Cloud Functions or Cloud Tasks API. If you do not want to use either of those, you could try using `node-schedule` (assuming you will not use it in a Cloud Function).

You could also send a silent message to your clients and handle the display of the notification later on the client side.

Please [see this for a more detailed answer](https://stackoverflow.com/a/60714000). Hope this helps!

**Comment by chong-shao** [comment]
Firebase Console also supports message scheduling. The HTTP send API currently does not support scheduling. Admin SDK also does not support scheduling since the SDK talks to the HTTP API.

**Comment by ksydex** [comment]
@chong-shao Any information on when it's gonna be supported in HTTP API, or if it's ever be supported?

**Comment by kasvith** [comment]
Is there any way to achieve this?

**Comment by Kernelogy** [comment]
The lack of such a feature is a great drawback with firebase, to acheive this functionality we have to write our own cron jobs @kasvith

**Comment by kasvith** [comment]
@Kernelogy true. Although its in the console its a shame they did not expose on firebase admin
