### ISSUE TITLE
Snyk vulnerability report: low severity

### ISSUE THREAD

**Issue by bondz** [firebase/firebase-admin-node#88]
Testing the current version of this module `firebase-admin@5.2.1` with snyk/snyk results in a low severity warning and makes it exit with an error.

This can be resolved by updating `jsonwebtoken@7.1.9` to `jsonwebtoken@7.4.1`.

[Vulnerability report](https://snyk.io/test/npm/firebase-admin/5.2.1)

#### Steps to reproduce:

`snyk test firebase-admin`

**Comment by hiranya911** [comment]
Fixed
