### ISSUE TITLE
Logout user from app after updated with new email.

### ISSUE THREAD

**Issue by ianitsky** [firebase/firebase-admin-node#882]
* Operating System version: Linux Mint 19.3
  * Firebase SDK version: 8.12.0
  * Firebase Product: auth
  * Node.js version: 8.17.0
  * NPM version: 6.14.4

If I save the user email with "admin.auth().updateUser", the app logout the user.

#### Steps to reproduce:

In my app (android), I logged in user with phone number.
After that, on the second screen, I capture the user data (name, email, dob, etc) and send to a function on the server (to maintain the app simple).
If I update the user with this email, the app logout the current user.
But if I don't set the email, the app continues logged in.

#### Relevant Code:
Code that is not ok
```
await admin.auth().updateUser(context.auth.uid, {
    email: data.email,
    emailVerified: data.emailVerified,
    displayName: `${data.name} ${data.surname}`,
})
```

Code that is ok
```
await admin.auth().updateUser(context.auth.uid, {
    /*email: data.email,*/
    emailVerified: data.emailVerified,
    displayName: `${data.name} ${data.surname}`,
})
```

**Comment by hiranya911** [comment]
This is the normal behavior. `updateUser()` does not revoke the existing login sessions unless a major change is made to the user account.

> Refresh tokens expire only when one of the following occurs:
>  * The user is deleted
>  * The user is disabled
> * A major account change is detected for the user. This includes events like password or email address updates.

https://firebase.google.com/docs/auth/admin/manage-sessions

**Comment by ianitsky** [comment]
@rajesh-h You can create a custom token on the server and login the customer on the front again.

`admin.auth().createCustomToken(user.uid)
.then((customToken) => {
    resolve(customToken);
})
.catch(error => reject(error.errorInfo));`
