### ISSUE TITLE
Can not get lastRefreshTime 

### ISSUE THREAD

**Issue by fpeterdev** [firebase/firebase-admin-node#887]
### [READ] Step 1: Are you in the right place?

  yes

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10 Home Version 1903
  * Firebase SDK version: 8.12.1
  * Firebase Product: auth
  * Node.js version: 8.15.0
  * NPM version: 6.4.1

### [REQUIRED] Step 3: Describe the problem

I can't retrieve the lastRefreshTime for any user. Tried for several users, both in the emulator and on the server, always with the same result.

#### Relevant Code:

```
const uid = 'myUserId';
const myUser = await admin.auth().getUser(uid);
console.log(JSON.stringify(myUser.metadata, null, 2));
console.log(JSON.stringify(myUser.metadata.lastRefreshTime));
```
The code above always writes the following to the console output respectively:
```
// first console.log()
{
  "lastSignInTime": "Tue, 12 May 2020 07:41:34 GMT",
  "creationTime": "Fri, 04 Jan 2019 09:18:21 GMT"
}
//second console.log()
"Thu, 01 Jan 1970 00:00:02 GMT"
```

**Comment by bojeil-google** [comment]
Seems like a bug.
I noticed we are using [`parseDate`](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/user-record.ts#L33) to parse this when it is using the `.toISOString()` format:

`"lastRefreshAt": "2020-05-12T08:11:19.863Z"`

When we should be handling it like [`enrolledAt`](https://github.com/firebase/firebase-admin-node/blob/master/src/auth/user-record.ts#L223)

**Comment by hiranya911** [comment]
I think this is because how `UserMetata.toJson()` is implemented:

```
public toJSON(): object {
    return {
      lastSignInTime: this.lastSignInTime,
      creationTime: this.creationTime,
    };
  }
```

**Comment by rsgowman** [comment]
You're both right; there's two bugs here. One with the way the time is parsed (lastRefreshAt is returned from the server differently then the other timestamps) and the other bug (or at least omission) is that the toJSON method doesn't report the lastRefreshTime.

Actually, there's a third bug too: importing users does not record the lastRefreshTime. (Noticed that while looking at this bug.) The other two probably only apply to the node port, but this one likely applies to all 5.

The incorrect parsing of lastRefreshedAt bugs me; I knew the time was returned by the backend differently, and I've even handled that correctly in the other ports (though will definitely need to go back and verify that now that I know I've missed this at least once). Unfortunately, javascript's Date constructor is too permissive, as were our tests. Had either been a little tighter, this would've been caught much earlier. I've adjusted the tests to require a tighter bound on the resulting timestamp.

**Comment by fpeterdev** [comment]
Thank you for the quick response and fix. Really appreciate it!
