### ISSUE TITLE
Difference between sendToTopic() and send({ payload, topic })

### ISSUE THREAD

**Issue by sujeet-agrahari** [firebase/firebase-admin-node#893]
I am using Admin SDK for node.js. I see on this page both `send()` and `sendToTopic()` is mentioned.

Same for, `sendToDevice()` and `send()`.

What is the difference between these methods?

What is the difference between `sendMulticast()` and `sendAll()`?

`sendToTopic()` and `sendToDevice()` these methods takes an optional `options` argument. How can I pass that argument with `send()`

When should I use `send()` over these methods?

**Comment by hiranya911** [comment]
See https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging for the API details.

`sendTo***()` APIs are part of the FCM legacy API and are further described here: https://firebase.google.com/docs/cloud-messaging/send-message#adminSDK-legacy-send-methods

Examples for `sendAll()` and `sendMulticast()` are at https://firebase.google.com/docs/cloud-messaging/send-message
