### ISSUE TITLE
High number of realtime db disconnects due to unhealthy connection

### ISSUE THREAD

**Issue by mquinn-leverege** [firebase/firebase-admin-node#897]
* Operating System version: node-alpine 12
  * Firebase SDK version: 8.12.1
  * Firebase Product: database
  * Node.js version: 12.16.3
  * NPM version: 6.14.3

We've found an issue that using the Firebase Admin SDK on an API server running in a Kubernetes cluster that surfaces itself in a large number of disconnects due to unhealthy connections. I have attempted to reproduce the issue locally but haven been unsuccessful. Our use case is an IOT application with approx. 150,000 devices reporting messages at a constant rate. On average we make 30 requests/second to this API endpoint to get data and at times there are peaks of about 200 requests/second. On each report, we use the `once()` method to get the current stored state of the device that is reporting. All that is to say we are making heavy use of once and it is not practicable for use on since we run a stateless system. If we enable firebase logging, when the system is running at full load we begin to see a steady stream of logs in the form of "Connection created -> Websocket connecting to <database url> -> Closing unhealthy connection after timeout -> Closing realtime connection -> Shutting down all connections -> Websocket is being closed -> Websocket connection was disconnected."

We are using a sharding system with multiple database instances where device data is stored in one of 10 instances based on a hash of it's id and we are staying well below the request and connection limits for each instance according to our firebase metrics.

Our only thought is that there may be some kind of limitation to our unconventional use of the `once()` method that we aren't aware of since it seems the more general use case for firebase is to listen for realtime updates.

Are there any additional steps we might take to troubleshoot this issue?

**Comment by hiranya911** [comment]
What's the portion of requests that fail with an error like this? And what's your network setup like?

**Comment by mquinn-leverege** [comment]
For the last 10 minutes of traffic, there have been ~10,000 requests and ~900 of them have timed out. Our network setup is a VPC behind a standard CloudNAT. Average egress data processed by NAT is around 384KiB. Our GKE has private cluster and VPC-native enabled.

**Comment by schmidt-sebastian** [comment]
We will take a look. Can you send your Project ID and timestamps to `mrschmidt<at>google.com`?

**Comment by schmidt-sebastian** [comment]
Our backend team was able to see some timeouts for some of your queries, but these happened earlier than the time window you provided. Since this is a highly project specific issue, it might make sense for you to follow up with them directly. Do you mind filing a support request via https://cloud.google.com/support-hub ?

Closing this issue for now as this does not seem to be an SDK issue. Please feel free to comment should you have additional information.
