### ISSUE TITLE
Update libuv dependency to fix 'Assertion failed: new_time >= loop->time'

### ISSUE THREAD

**Issue by rejhgadellaa** [firebase/firebase-admin-node#898]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 1909
  * Browser version: Nodejs 12.16.1
  * Firebase SDK version: firebase-admin 8.12.1
  * Firebase Product: firebase-admin

### [REQUIRED] Describe the problem

The libuv library (a dependency of the js admin sdk) throws an error when firebase-admin is used on certain systems that run on 10th gen Intel processors:

> Assertion failed: new_time >= loop->time

See https://github.com/libuv/libuv/issues/1633

This was fixed in a recent commit in the 1.x branch:
https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24

Please update the firebase-admin's dependency to use the new version.

#### Steps to reproduce:

N/A

#### Relevant Code:

N/A

**Comment by hiranya911** [comment]
We don't have such a dependency. Here's our list of dependencies from the `package.json`:

```
"dependencies": {
    "@firebase/database": "^0.6.0",
    "@types/node": "^8.10.59",
    "dicer": "^0.3.0",
    "jsonwebtoken": "8.1.0",
    "node-forge": "0.7.4"
  },
  "optionalDependencies": {
    "@google-cloud/firestore": "^3.0.0",
    "@google-cloud/storage": "^4.1.2"
  },
```

**Comment by hiranya911** [comment]
I don't see anything we can do in our codebase to resolve the above issue. AFAICT libuv is not even a transitive dependency for `firebase-admin`. If somebody can provide more details on what can be done in our code to resolve this, we'd be happy to take another look.

**Comment by null-reference** [comment]
Yeah, I get this error when running `firebase login`...

> i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
> 
> ? Allow Firebase to collect CLI usage and error reporting information? (Y/n) Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

**Comment by hiranya911** [comment]
If it's an issue with the Firebase CLI please report at https://github.com/firebase/firebase-tools

**Comment by bzoz** [comment]
libuv is a C library that Node.js uses to abstract different OSes. You will have to update Node.js to fix this bug.

**Comment by rejhgadellaa** [comment]
Heh now I feel stupid 😄 I assumed it was firebase-admin because projects that use it were the only ones I'm having issues with. Thanks for clarifying!

**Comment by ashok3612** [comment]
> Yeah, I get this error when running `firebase login`...
> 
> > i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
> > ? Allow Firebase to collect CLI usage and error reporting information? (Y/n) Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

I also get the same error even I got updated the firebase admin to the latest one.

**Comment by SureshKrishnaaR** [comment]
(FIXED)
I had the same problem guys...!
What I did was I mentioned the firebase-tools version while installing them, that is
𝐧𝐩𝐦 𝐢𝐧𝐬𝐭𝐚𝐥𝐥 -𝐠 𝐟𝐢𝐫𝐞𝐛𝐚𝐬𝐞-𝐭𝐨𝐨𝐥𝐬 𝟖
And after running this command this problem was resolved so go ahead and try out this!
If it didn't work still try reinstalling nodejs (https://nodejs.org/en/download/) and repeating the same procedure..........
This will work out for sure...!
