### ISSUE TITLE
Service Account json does not match type ServiceAccount required for admin.credential.cert()

### ISSUE THREAD

**Issue by paulrenshaw** [firebase/firebase-admin-node#903]
## Environment

  * Operating System version: macOS 10.15.5 (Catalina)
  * Firebase SDK version: 8.12.1
  * Firebase Product: firebase-admin
  * Node.js version: 10.20.1
  * NPM version: 6.14.4

## Problem

When using TypeScript in VS Code and trying to pass a service account object imported from a .json file downloaded from the firebase console, serviceAccount is underlined in the following code 

```
import admin from 'firebase-admin'
import serviceAccount from './serviceAccount.json'

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  })
}
```

with problem 

```
Type '{ type: string; project_id: string; private_key_id: string; private_key: string; client_email: string; client_id: string; auth_uri: string; token_uri: string; auth_provider_x509_cert_url: string; client_x509_cert_url: string; }' has no properties in common with type 'ServiceAccount'.
```

the type ServiceAccount is defined in firebase-admin/lib/index.d.ts {} admin as 

```
interface ServiceAccount {
    projectId?: string;
    clientEmail?: string;
    privateKey?: string;
  }
```

## Steps to reproduce:

install firebase-admin
download service account json file from Firebase Console
import service account json file using typescript (with resolveJsonModule flag)
attempt to pass the service account variable to admin.credential.cert() to be used to initialise

**Comment by hiranya911** [comment]
You have to use the `require('path/to/serviceAccount')` syntax. If you import as shown above then you must manually convert it into the interface format expected by the SDK.
