### ISSUE TITLE
Update jsonwebtoken and node-forge

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-admin-node#905]
For some reason the version of `jsonwebtoken` is pinned to 8.1.0 (last updated 3 years ago) and `node-forge` is pinned to 0.7.4 (last updated 2 years ago).

Consider either bumping their versions or using the caret `^` if there's no good reason to have them pinned.

Note that both packages have received several updates including bug fixes and security updates, `jsonwebtoken` latest version is 8.5.1 and `node-forge` 0.9.1.

Note that pinning the versions mean that `npm` won't deduplicated the dependencies and multiple versions may be present in a project, making deployments slower and using more memory.

**Comment by killroy42** [comment]
The node-forge version is causing a `We found potential security vulnerabilities in your dependencies.` dependabot warning on github now.
