### ISSUE TITLE
admin.auth().getUserByEmail() seems to hang in Mocha test

### ISSUE THREAD

**Issue by matthew-carroll** [firebase/firebase-admin-node#918]
### Describe your environment

  * Operating System version: macOS Mojave 10.14.6
  * Firebase SDK version: 8.2.0
  * Firebase Product: auth 
  * Node.js version: v12.16.3
  * NPM version: 6.14.4

### Describe the problem

I'm writing Mocha tests for my cloud functions. Within one of my tests I'm executing:

```
const userRecord = await admin.auth().getUserByEmail('...');
```

This line, specifically, appears to cause mocha execution to hang. No other detail within my tests seem to cause that same hang.

I'm wondering if this call is establishing some kind of long-lived connection that keeps the process active. In any event, this seems like a bug.

### Repro

```
  it('hangs forever', async() => {
    const userRecord = await admin.auth().getUserByEmail('someuser');
    console.log('Execution has ended.');
  });
```

Run with:

`mocha --reporter spec`

The above test will execute, it will display `Execution has ended` in the console, and Mocha will report success. However, the process hangs indefinitely.

**Comment by hiranya911** [comment]
You need to tear down the `FirebaseApp` instance. From our own integration tests:

https://github.com/firebase/firebase-admin-node/blob/98b4788edda80cc2fe5deea47ffeb9938bfdcab7/test/integration/setup.ts#L100-L107
