### ISSUE TITLE
[FR] Moving to @firebase/admin module naming

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-admin-node#919]
Problem:
With the main Firebase libraries moved to `@firebase/xxx` naming convention (e.g. `@firebase/testing`), `firebase-admin` looks a bit like an outlier.

There may be reasons for keeping it this way, but it does look a bit odd and I double checked that it's not about a bogus module pretending to come from official Firebase.

**Describe the solution you'd like**
Ability to have `"@firebase/admin": "^8.9.10"` in `package.json`

**Describe alternatives you've considered**
Currently using the `firebase-admin: "^8.21.1"`.

**Comment by hiranya911** [comment]
`@firebase/*` is strictly reserved for our client (JS) SDK packages. `firebase-admin` is intentionally named so to look distinct from the client SDKs. Our official documentation should answer any doubts about the authenticity of the package: https://firebase.google.com/docs/admin/setup
