### ISSUE TITLE
[Firestore] Cannot use Firestore ^4.0.0

### ISSUE THREAD

**Issue by mad-it** [firebase/firebase-admin-node#921]
Firestore recently released a newer version of their SDK with a bunch of new features and fixes. This SDK release is a major release which dropped node 8 support.

We cannot update to the newest version of Firestore when having `firebase-admin` as a dependency due to the version missmatch [here](https://github.com/firebase/firebase-admin-node/blob/master/package.json#L64).

Is there any way we can use the newest Firestore SDK in combination with `firebase-admin` ?

**Comment by schmidt-sebastian** [comment]
I will work with @hiranya911 to figure something out. Unfortunately, we cannot yet drop Node 8 support from the Firebase SDKs as a whole as we have product dependencies within Google that have yet to fully migrate.

**Comment by sk-** [comment]
I don't understand the comment, your Google dependencies would still be using the latest 8.x version from `firebase-admin-node` which supports Node 8. The rest of us could migrate to the next major version of this library.

Is there at least an ETA for when this migration may be completed?

firestore 4 brings a lot of improvements, and will bring even more (e.g. `BulkWriter`).
@schmidt-sebastian Will you consider backporting the bug fixes and new features to the 3.x branch?

**Comment by hiranya911** [comment]
Firestore v4 no longer works on Node 8. But `firebase-functions` can't drop Node 8 support yet, and `firebase-admin` is also tied up in the same issue (we can technically drop Node 8 support in `firebase-admin` and do a major release like Firestore did, but that will likely inconvenience a large number of Functions users). 

@laurenzlong any idea when the Functions Node 10 migration would be complete?

**Comment by laurenzlong** [comment]
@mbleigh has more context on the Node 10 migration for functions.

**Comment by mbleigh** [comment]
@hiranya911 we are currently using `^8.10.0` as the semver string in `firebase init`, and we will be defaulting to Node 10 beginning tomorrow. I'm comfortable with `firebase-admin` immediately dropping Node 8 support so long as it's done in a major version.

**Comment by hiranya911** [comment]
Thanks @mbleigh. We will get started on the migration.

**Comment by hiranya911** [comment]
Firestore and GCS versions have been upgraded in #934. Will be included in the next release (v9)
