### ISSUE TITLE
[FR] Make @firebase/database an optional dependency

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-admin-node#922]
**Is your feature request related to a problem? Please describe.**
Our project does not use the Firebase Real Time Database, however it is being installed as a dependency. This increases our dependencies size by over 7.5Mb, and also add some more transitive dependencies which are not needed.

**Describe the solution you'd like**
Make `@firebase/database` an optional dependency, just like `@google-cloud/firestore` and `@google-cloud/storage`.

**Comment by hiranya911** [comment]
Making it an optional dependency doesn't mean NPM won't install it. 

From https://docs.npmjs.com/files/package.json#optionaldependencies
```
If a dependency can be used, but you would like npm to proceed if it cannot be found or 
fails to install, then you may put it in the optionalDependencies object.
```

The package will still get installed (just like Firestore and Storage). So you will still have to manually remove it.

**Comment by hiranya911** [comment]
Closing as won't fix. Optional dependencies are not a viable solution to the given problem. Peer dependencies could be, but results in nasty warnings that most users won't like (https://github.com/npm/npm/issues/3066). 

The dependency size issue raised here is a valid concern, and we are thinking about it as part of separate modularization effort that's currently in progress.

**Comment by BorntraegerMarc** [comment]
@hiranya911 Is there an issue to follow & vote for the separate modularization? If not, I'm happy to create one.
