### ISSUE TITLE
Using verifyIdToken()` with the second argument causes serverless function to timeout

### ISSUE THREAD

**Issue by chiubaca** [firebase/firebase-admin-node#929]
* Operating System version: Ubuntu Xenial 16.04 
  * Firebase SDK version: 8.13.0
  * Firebase Product: auth
  * Node.js version: v12.18.0 
  * NPM version: 6.14.4

#### Steps to reproduce:

Using `verifyIdToken(idToken, true)` with the second argument to check if the token has been revoked causes Netlify serverless Function to timeout.   

#### Relevant Code:

Publish the following code below to a Netlify function, then hit the endpoint which includes a valid JWT  with an "Authorization" header and the lambda function will consistently timeout.

However if you remove the second argument from `verifyIdToken()` and republish the function again, there are no issue at all. 

```js
const admin = require("firebase-admin")

const SERVICE_ACCOUNT = JSON.parse(process.env.FIREBASE_CONFIG);

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(SERVICE_ACCOUNT)
  });
}

exports.handler = async function (event, context, callback) {

  try {
    // Extract JWT from header
    const JWT = event.headers.authorization;

    // Verify JWT, if user deleted, or JWT is invalid, this will throw an error
    const user = await admin.auth().verifyIdToken(JWT, true);

    callback(null, {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(user)
    });
  } catch (error) {
    console.error("There was an error", error);
    callback(null, {
      statusCode: 400,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ error })
    });
  }
};

```

**Comment by hiranya911** [comment]
Can you reproduce the issue locally or in any other environment? Without a repro I don't think we can do much about this issue, since it works normally in our test environments.

**Comment by chiubaca** [comment]
Weirdly, the issue cant be reproduced on a local machine. It only occurs when it's published on Netlify.
If it helps, I have published two endpoints which I used to verify this issue personally.

broken:
https://deploy-preview-7--jottivity.netlify.app/.netlify/functions/broken
logs : https://app.netlify.com/sites/jottivity/functions/broken?scope=deploypreview:7

working:
https://deploy-preview-7--jottivity.netlify.app/.netlify/functions/working
logs: https://app.netlify.com/sites/jottivity/functions/working?scope=deploypreview:7

I think those logs are accessible if you have a Netlify account

**Comment by hiranya911** [comment]
Can't really speculate as to why something wouldn't work in a specific environment. Have you tried reaching out to the Netlify Support or developer community?

**Comment by chiubaca** [comment]
I have indeed, I've posted the same issue on the Netlify community forums - https://community.netlify.com/t/netlify-function-timeout-after-10-seconds-when-published/18220

And I've spent a few hours troubleshooting this issue on the Firebase slack where we were able to pinpoint the issue to that `verifyIdToken()` method which was causing the problem.

**Comment by hiranya911** [comment]
Ok, that forum post actually helped. 

> This is often resolved by changing the function code to include calls to close “the connection”. As far as what “the connection” actually is, it is typically a connection to an API or database.

You need to clean up the App instance (`app.delete()`) to ensure proper clean up of the Admin SDK: https://firebase.google.com/docs/reference/admin/node/admin.app.App#delete

This is not required in most environments. But it appears it's required in Netlify.

**Comment by chiubaca** [comment]
nice, that worked! I included `await admin.app().delete()` just before returning the http response. now it works locally and also when published to Netlify without any timeouts 👍 .

It does seem like quite a daunting method to call though, just my own personal thoughts. However, thank you helping me finally get to bottom of this issue.

**Comment by hiranya911** [comment]
> It does seem like quite a daunting method to call though, just my own personal thoughts. 

Yeah, it's not the best name, but we are stuck with it for historical reasons. Most applications don't need to call it explicitly (notably none of the Google Cloud Functions code require it). But some environments can be more picky about calling it.

**Comment by zaarheed** [comment]
I’m having a similar timeout issue on Netlify, but when using the JavaScript Web SDK. Is there an equivalent `.delete()` method to close the Firestore connection on the Web SDK too?

https://github.com/netlify/next-on-netlify/issues/66#issue-731895731

**Comment by alexanvl** [comment]
We started to see this error at 2022-09-23 09:49:08.055 PDT in the firebase-admin@11.0.1 package, running in a node:16 container within GKE.  Setting the `checkedRevoked` parameter seems to resolve the issue and we're try to determine what caused it.
