### ISSUE TITLE
firebase-functions@3.8.0 requires a peer of firebase-admin@^8.0.0 

### ISSUE THREAD

**Issue by awhitford** [firebase/firebase-admin-node#950]
After upgrading to `firebase-admin 9.0.0`, this warning appears:
```
npm WARN firebase-functions@3.8.0 requires a peer of firebase-admin@^8.0.0 but none is installed. You must install peer dependencies yourself.
```
Should one wait until there is a `firebase-functions` update, or is this a benign warning?

**Comment by hiranya911** [comment]
You can't use `firebase-admin` v9 with the existing Functions SDK distributions. You need to wait until they upgrade their peer dependency.

**Comment by awhitford** [comment]
Thank you for clarifying.
