### ISSUE TITLE
[FR] Firebase Cloud Messaging HTTP v1 API

### ISSUE THREAD

**Issue by rubenvereecken** [firebase/firebase-admin-node#953]
I write this with `firebase-admin@9.0.0` in mind. I only just realised that `firebase-admin` only supports the legacy HTTP API of Firebase Messaging. Are there any plans to implement the new [Firebase Cloud Messaging HTTP v1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)? I believe the main change is a clear divide between Android and iOS options.

**Comment by hiranya911** [comment]
It already supports the HTTP v1 API: https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#send
