### ISSUE TITLE
[FR] Push Notification trigger scheduling using Admin SDK and FCM.

### ISSUE THREAD

**Issue by harshittrehan** [firebase/firebase-admin-node#955]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to exist a FCM API to schedule a push notification for a later date/time using the Admin SDK.

**Describe the solution you'd like**
I need to set a schedule/trigger time programmatically based on some calculations done by getting the data of the user from Cloud Firestore.
Hence, I am using Cloud Functions + Admin SDK to get data and do my time calculations, and now I need FCM + Admin SDK to set trigger date based on my calculation results, which doesn't seem possible atm.

**Describe alternatives you've considered**
I considered using Cloud Scheduler to set up cron jobs but the number of resulting API calls would be far from economical. 

**Additional context**
Not that this matters a lot (or it just might..), I think most other cloud platforms already have this feature and it would be cool to have this incorporated in Firebase as well!

**Comment by hiranya911** [comment]
Please file as a feature request at https://firebase.google.com/support

This needs to be implemented as a core FCM feature, and only then SDKs can begin to support it.
