### ISSUE TITLE
Firebase auth throwing "Must initialize with a cert credential or ..." even though app is already initialized

### ISSUE THREAD

**Issue by thetminko** [firebase/firebase-admin-node#956]
* OS - AWS linux 2 - Docker container (node:11.2-alpine)
  * Firebase SDK version: 9.0.0
  * Firebase Product: auth
  * Node.js version: 11.2.0
  * NPM version: 6.4.1

#### Steps to reproduce:
I have two JS files:
1. server.js
2. service.js

In server.js, I initialize the firebase admin app with 
`const serviceJson = require('../../firebase-service-account.json');
 const firebaseOptions = {
    credential: firebaseAdmin.credential.cert(serviceJson, firebaseHttpAgent),
    httpAgent: firebaseHttpAgent
  };
  firebaseAdmin.initializeApp(firebaseOptions);
`
After this, I printed out the app, `firebaseAdmin.apps[0].name` and it printed out Default

And in service.js, I verify ID token in a function 
`
   const firebaseAuth = firebaseAdmin.auth();
    this.logger.info(`Verify token Firebase app: [${firebaseAdmin.apps[0].name}]`); // this prints Default too
    const decodedFirebaseIdToken = await firebaseAuth.verifyIdToken(firebaseIdToken, true);
`

But, when this function is called, this error message is thrown
Must initialize app with a cert credential or set your Firebase project ID as the GOOGLE_CLOUD_PROJECT environment variable to call verifyIdToken().

I tried in v8.13.0, and its the same behaviour. I tried in v7.0.0, it is working fine, no errors were thrown.

Could you direct me what is wrong with this issue?

**Comment by hiranya911** [comment]
Can you provide a minimal repro for us to test?

**Comment by thetminko** [comment]
@hiranya911 Thanks for the reply, let me get back on you this. I couldn't replicate on my local machine, just that on our servers, it is having this issue. Once we use the version 8.13.0 or 9.0.0, it throws this error. If we use version 7.0.0, everything works perfectly.

**Comment by thetminko** [comment]
@hiranya911 Let me close this issue first before I can get this replicated. Thanks!

**Comment by AKGP** [comment]
I am getting this issue on my local with 10.0.0 version 
Please help
