### ISSUE TITLE
Sending data to firebase storage always fail

### ISSUE THREAD

**Issue by saher-elgendy** [firebase/firebase-admin-node#959]
I am using Postman to mimic firebase and firestore requests, i still don't have any frontend code, only cloud functions code, the problem is that i can't mimic uploading any data to firebase storage using postman and i always get` internal server error` or an empty json object.

I tried to reproduce the issue with minimal possible code and i created this [repo](https://github.com/saher-elgendy/Cloud-Functions-Issue)

I am using **postman** to sign in via` './signin'` route, then using the token returned from the sign in process as request headers authorization value(JWT) to authorize uploading an image in the next process via `'/image'` route, but this always fail, I get `internal server error`, this is not the only error i get, because sometimes i get an empty json object with no action in the storage

**Comment by hiranya911** [comment]
Your Cloud Function calls many APIs (Firestore, Auth, Storage and even the Web SDK), and also uses third-party libraries. It's not a minimal repro and we cannot debug this. I would therefore just point you to the Busboy example at https://cloud.google.com/functions/docs/writing/http#multipart_data. Your implementation lacks many of the aspects in that example, so I'd recommend looking into that first. Specifically your code doesn't handle the `end` events for individual file writes, and the resulting Promises.

Once you've done that, and you still suspect something's wrong with the Storage APIs, please report a new issue with a better MCVE.

**Comment by saher-elgendy** [comment]
I believe it is firebase torage bug, because the same code works a couple of times to upload images to the storage but never worked again!
