### ISSUE TITLE
Newly Created user not able to login from localhost works fine from the hosted url.

### ISSUE THREAD

**Issue by jontysouvik** [firebase/firebase-admin-node#972]
* Operating System version: Win 7
  * Firebase SDK version: firebase admin 8.10.0
  * Firebase Product: auth
  * Node.js version: 10

#### Steps to reproduce:

When an user is created using admin sdk that user is not able to login from localhost. but it is working fine form hosted url like *.web.app
getting a response of 
```
{
      a: null,
      code: "auth/user-not-found",
      message: "There is no user record corresponding to this identifier. The user may have been deleted.",
​      stack: ""
}
```
when created an user from firebase web admin ui that user is able to log in from localhost

#### Relevant Code:

```
export const createNewUser_v1 = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    return null;
  }
  let newAdminData;
  try {
    newAdminData = await admin.auth().createUser({
      email: data.email,
      emailVerified: false,
      // phoneNumber: `+91${data.phone}`,
      password: '123123',
      // displayName: 'John Doe',
      // photoURL: 'http://www.example.com/12345678/photo.png',
      disabled: false
    });
    functions.logger.info(newAdminData, { structuredData: true });
    return newAdminData;
  } catch (error) {
    return error;
  }
});
```

**Comment by hiranya911** [comment]
Sounds like your app in localhost is running against a different Firebase project, and therefore cannot find the user account.

**Comment by bojeil-google** [comment]
I can't tell from the information provided here. No client side code is provided. I suspect the different API keys are being used in each domain.

**Comment by jontysouvik** [comment]
UPDATE: Issue Seems to be with Email Address.
if Email address is same email which is the project owner. I am getting User not found for other email its working fine.
Is there any policy about that??

**Comment by bojeil-google** [comment]
We don't have such policy. You need to provide a mechanism to recreate this. Right now, we don't have anything tangible to help us debug this issue.

**Comment by jontysouvik** [comment]
As it is too hard to reproduce and there might be Unknown variables on my end. I am closing the Issue. as it is not much of a real world scenario. Thanks for you help.
