### ISSUE TITLE
[FR] Ignore undefined values rather than throw exceptions

### ISSUE THREAD

**Issue by ROODAY** [firebase/firebase-admin-node#976]
The node.js SDK for Firebase already has this feature (it was brought up in [this issue](https://github.com/googleapis/nodejs-firestore/issues/1031)). Can it please be implemented here as well?

**Comment by hiranya911** [comment]
`admin.firestore().settings({ignoreUndefinedProperties: true});`  should do the trick, provided your `@google-cloud/firestore` dependency is recent enough.

**Comment by ROODAY** [comment]
@hiranya911 I don't see `@google-cloud/firestore` in my dependencies, should it have been added by `yarn add firebase-admin` or should I add it manually? Also, the way I was calling it previously was
```
const admin = require("firebase-admin");
admin.initializeApp();
const firestore = admin.firestore();
firestore.settings({ignoreUndefinedProperties: true});
```
Is that incorrect/do I need to set it explicitly by `admin.firestore().settings({ignoreUndefinedProperties: true});`?

**Comment by dobromyslov** [comment]
@ROODAY `@google-cloud/firestore` is provided by `firebase-admin` via it's own node_modules.
Installing your separate `@google-cloud/firestore` along with `firebase-admin` is dangerous especially when you want to use FieldValue.serverTimistamp.

You just need to 
```
import * as admin from 'firebase-admin';

if (!admin.apps.length) {
  admin.initializeApp();
}

const firestore = admin.firestore();
firestore.settings({ignoreUndefinedProperties: true});
```

**Comment by ROODAY** [comment]
@dobromyslov Thanks for the tip! Is the important bit `import * as admin from 'firebase-admin';`?
