### ISSUE TITLE
Cloud not install firebase-admin

### ISSUE THREAD

**Issue by aorfevre** [firebase/firebase-admin-node#980]
### Could not install firebase-admin

Once I try to install firebase-admin with `npm i --save firebase-admin` I have the following error 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @google-cloud/firestore@^3.0.0 (node_modules/firebase-admin/node_modules/@google-cloud/firestore):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found - GET https://registry.npmjs.org/@google-cloud%2ffirestore - Not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @google-cloud/storage@^4.1.2 (node_modules/firebase-admin/node_modules/@google-cloud/storage):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found - GET https://registry.npmjs.org/@google-cloud%2fstorage - Not found

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@firebase%2fdatabase - Not found
npm ERR! 404 
npm ERR! 404  '@firebase/database@^0.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'firebase-admin'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aorfevre/.npm/_logs/2020-08-06T09_50_00_938Z-debug.log
```

I have tried to find @firebase/database in github, but it seems to be changed to https://github.com/firebase/firebase-js-sdk

#### Environnment 
node --version v12.0.0
npm --version 6.9.0

**Comment by sanskar2999** [comment]
I am also facing the same issue

**Comment by LouisPetrik** [comment]
Facing something similar here:

error Couldn't find package "@protobufjs/aspromise@^1.1.2" required by "protobufjs@^6.8.9" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@protobufjs/base64@^1.1.2" required by "protobufjs@^6.8.9" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)

**Comment by phoebelord** [comment]
Me too

Could it be related to current npm issues? https://status.npmjs.org/

**Comment by hiranya911** [comment]
It was an NPM outage: https://status.npmjs.org/incidents/cksjqc1w11v5
