### ISSUE TITLE
.info/connected does not change to false when offline

### ISSUE THREAD

**Issue by tonila** [firebase/firebase-admin-node#99]
### Environment

Debian buster
Node.js v 8.5.0
firebase-admin v ^5.0.0

#### Steps to reproduce:

1. Start application and wait for console log "Firebase connected!"
2. Go offline (switch off wifi or remove lan cable etc.)

When internet connection is disabled, application should print "Firebase disconnected".
It seems, it never does!

#### Relevant Code:

```javascript
"use strict";

var path = require('path');
var admin = require("firebase-admin");

var serviceAccount = require(path.join(__dirname, "some-firebase-adminsdk-lu0x5-82c66d50f5.json"));

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://some.firebaseio.com/"
});

const database = admin.database();

var connectedRef = database.ref(".info/connected");
connectedRef.on("value", function(snap) {
  if (snap.val() === true) {
    console.log("Firebase connected!");
  } else {
    console.log("Firebase disconnected!");
  }
});
```

**Comment by zyzski** [comment]
experiencing similar behavior. set to offline mode in network tab it goes disconnected -> connected immediately.

`
16:04:12.402 connected: false
16:04:12.530 connected: true
`

**Comment by hiranya911** [comment]
I've verified that this issue occurs with latest RTDB code as well. Reported at https://github.com/firebase/firebase-js-sdk/issues/249. Lets track the progress there.
